### ISSUE TITLE
Coral Install and example works, but edgetpu import not

### ISSUE THREAD

**Issue by hansamann** [google-coral/edgetpu#1]
I've been folliwing this guide: https://coral.withgoogle.com/docs/accelerator/get-started/

I n the end I run the example to classify an image, it all works.

But this will not work:

root@32d1e00c6940:/coral/tflite/python/examples# python3 -c 'import edgetpu; print("OK") '
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'edgetpu'

What am I missing? I need to get the edgetpu python lib installed... 

thx
Sven

**Comment by Namburger** [comment]
Hi @hansamann -
I have edgetpu installed here:
```master✗✗✗✗✗✗ nam% python3.6 -c 'print(__import__("edgetpu").__path__)'
['/usr/lib/python3/dist-packages/edgetpu']
```
I believe it should be in that directory for you too. Can you check if it's in your 
`python3 -c 'print(__import__("sys").path)'` ?

**Comment by Namburger** [comment]
Ahh @hansamann 
Just realized that you are using the `tflite_runtime` api to run the demo. You can install the new edgetpu api via:
```
$ sudo apt-get install python3-edgetpu
```
take a look at this September updates:
https://coral.withgoogle.com/news/updates-09-2019/

**Comment by hansamann** [comment]
Many thx, the new python edgetpu lib helped me. Works. Now using the USB accelerator from my freshly crafted docker image on a rpi4. Very sweet.

**Comment by jingw222** [comment]
Hey, 
Installing the Debian package `python3-edgetpu` works fine but only under global system environment. However how can I import and use `edgetpu` in my virtual environment? Is there a pypi release available for the package?

**Comment by Namburger** [comment]
@jingw222 You can take a look at [these packages](https://coral.ai/software/#alternative-packages).
I believe the `edgetpu-2.13.0-py3-none-any.whl` is what you are looking for.
