### ISSUE TITLE
ReadLabelFile is missing a 'return'

### ISSUE THREAD

**Issue by Martin-Oehler** [google-coral/edgetpu#10]
During the latest release, `ReadLabelFile()` in `dataset_utils.py` was made deprecated. I suspect, the function is now supposed to call `read_label_file()` but the `return` statement is missing, so it always returns `None`. This breaks existing code.

[Offending code line](https://github.com/google-coral/edgetpu/blob/75e675633c2110a991426c8afa64f122b16ac372/edgetpu/utils/dataset_utils.py#L47)

**Comment by Namburger** [comment]
@Martin-Oehler you are correct, good catch!

**Comment by Namburger** [comment]
@Martin-Oehler Update: We've fixed this internally and will release on next update, thanks again!
