### ISSUE TITLE
In depth power / resource usage profiling

### ISSUE THREAD

**Issue by najiji** [google-coral/edgetpu#101]
Is there an API / possibility to profile the executed model layer by layer as well as the energy usage of the chip? The solution is marketed at 0.5 W/TOPS, however, there seems to be no way to profile this or to run the chip in a lower-performance less power hungry setting. What is the roadmap for this?

**Comment by Namburger** [comment]
@najiji 
Sorry, there is not api for querying for profiling execution layers by layers currently. I'll add this to our feature request list.
As for using different power consumption settings, we do provides the std and the max operating frequencies.

**Comment by najiji** [comment]
Ok, great! I found that the C++ API allows for setting of a performance mode, one of 

```
["Low", "Medium", "High", "Max"] (Default is "Max")
```

Is there any information how these settings affect power consumption and performance?

**Comment by Inesteem** [comment]
I too am greatly interested in those answers; additionally I would appreciate to know if there are any performance counters as mentioned in the paper regarding the tpu v1 from 2017 that are accessible through software?

**Comment by usbguru** [comment]
@najiji 
There are no published articles yet about power consumption vs. performance.  Yours could be the first!  

@Inesteem 
The edge TPU architecture is significantly different from the 2017-tpu-v1 design.  There are no performance counters.   You can make some rough estimates by the difference between the initial and secondary inferences to calculate the transfer time.  Then compare that against the inference time of models with different sizes.
