### ISSUE TITLE
TPU Device temperature

### ISSUE THREAD

**Issue by takaya1219** [google-coral/edgetpu#102]
Is there a way to know the temperature of the USB Accelerator?

**Comment by Namburger** [comment]
@takaya1219 
Sorry, but currently there isn't an API to query the TPU's temperature right now.

**Comment by jlz3008** [comment]
With mendel, try

`cat /sys/devices/virtual/thermal/thermal_zone0/temp `

**Comment by takaya1219** [comment]
@Namburger 
It's very disappointing. thank you for answering.

**Comment by Namburger** [comment]
@takaya1219 apologies, we do have an interface for pcie just not available for USB, I'll put this in as a feature request.

**Comment by PushkarChatterji** [comment]
Is there a way to find the temperature for the Dev Board?

**Comment by manoj7410** [comment]
@PushkarChatterji To get a reading of the board's temperature, you can use this command below. Please keep in mind that the output measurement is in 1/1000 of degrees celsius.

cat /sys/class/thermal/thermal_zone0/temp

**Comment by pmundt** [comment]
@Namburger As I have both the dev board and the USB version, I'd like to know what interface exists for measuring the temperature in the pcie case?

**Comment by Namburger** [comment]
@pmundt as @manoj7410 pointed out,
```
cat /sys/class/thermal/thermal_zone0/temp
```
Will give you the board's temperature. 

For [reading PCIe temperature](https://coral.ai/docs/m2/get-started/#read-the-edge-tpu-temperature) (haven't been discussed yet):
```
cat /sys/devices/_pci0000:00/0000:00:01.0/000:01:00.0_/apex/apex_0/temp
```
Keep in mind that the name is different for each pcie devices.

Unfortunately, no interface for reading the usb temperature at this time.

**Comment by pmundt** [comment]
@Namburger thanks. I was planning on having a prometheus exporter for the temperature so that we could monitor this and determine when to swap between standard and max containers. It would be great to get this for USB as well, but I suppose we'll have to live with measuring the ambient temperature and extrapolating for the time being.

**Comment by pmundt** [comment]
If you are taking feature requests, it would be nice if we could get this through e.g. an ioctl on the apex device nodes, as we could then use the same interface for all types, rather than having to implement different sysfs lookup logic based on device type.

**Comment by pmundt** [comment]
For anyone else interested in this, I've thrown together a prometheus exporter that includes the temperature here: https://github.com/adaptant-labs/edgetpu-exporter

Working fine on my Coral Dev Board.

**Comment by Namburger** [comment]
@pmundt we do take FRs!
I have included this in our list, it's a little long at the moment but I'll try to make a case for it.
That's nice, I use Prometheus for [this project](https://github.com/Namburger/restor) also, but haven't exported anything on the HW side
