### ISSUE TITLE
undefined reference to `coral::GetTempPrefix[abi:cxx11]()'

### ISSUE THREAD

**Issue by Eashwar93** [google-coral/edgetpu#103]
**System overview:**

Ubuntu 18.04
TF 2.1 built from source

**Problem**
I'm trying to build the example minimal.cc for x86 architecture. When I use the make file for the entire edgetpu package, the build is fine and I get the executables. But when I locally build the minimal.cc independent of Bazel, I'm getting build error. I did modify the build file a little bit to generate binaries that could be run on x86 CPU. Please refer below to the make file and the error message when I use that file to build minimal.cc
```

MAKEFILE_DIR := $(realpath $(dir $(lastword $(MAKEFILE_LIST))))
TENSORFLOW_DIR ?= /home/eashwara/tensorflow

minimal: minimal.cc model_utils.cc
	g++ -std=c++11 -o minimal minimal.cc model_utils.cc \
	-I$(MAKEFILE_DIR)/../../../ \
	-I$(MAKEFILE_DIR)/../../../libedgetpu/ \
	-I$(TENSORFLOW_DIR) \
	-I$(TENSORFLOW_DIR)/tensorflow/lite/tools/make/downloads/flatbuffers/include \
	-L$(TENSORFLOW_DIR)/tensorflow/lite/tools/make/gen/linux_x86_64/lib \
	-L$(MAKEFILE_DIR)/../../../libedgetpu/direct/k8/ \
	-ltensorflow-lite -l:libedgetpu.so.1.0 -lpthread -lm -ldl

clean:
	rm -f minimal
```

![Screenshot from 2020-04-29 22-20-54](https://user-images.githubusercontent.com/51912916/80642681-27125980-8a67-11ea-84db-08e84e350c5c.png)

I can assure you that the tensorflow path is right and I also built and installed the dependency "benchmark"
The minimal.cc file that I tried to build is [this](https://github.com/google-coral/edgetpu/blob/master/src/cpp/examples/minimal.cc)

Please let me know if I have made any obvious mistakes.

**Comment by Namburger** [comment]
@Eashwar93 sorry about that, it looks like `test_utils.cc` wasn't included in the make rule which is what contains that helper function. Also, please make sure that you've built `libtensorflow-lite.a` from [this commit](https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5), otherwise you will get issue similar [to this one](https://github.com/google-coral/edgetpu/issues/54) (matter fact I've notice that we have quite a few issues regarding building). 
Since all these complexities will causes lots of confusion, I've made a separate repo for compiling this minimal example: https://github.com/Namburger/edgetpu-minimal-example/blob/master/README.md
It is a single cmake rule it'll allow you to compile our code any where in 3 simple steps:
```
$ mkdir build && cd build
$ cmake ..
$ make
```

**Comment by Namburger** [comment]
@Eashwar93 
No worries, I'm just more concern that our stuffs doesn't work right out of the box lol
What compiler/version are you using? Our code base requires compiler that support at least [C++11](https://en.wikipedia.org/wiki/C%2B%2B11). For instance, `std::is_same<decltype(ret), int>::value`, `decltype`, and `auto` key words are language that only started with c++11.

I also just realized that I tell cmake that the required version is [c++17](https://github.com/Namburger/edgetpu-minimal-example/blob/master/CMakeLists.txt#L7).

Your fix: 
You could try upgrading your c/c++ compiler to support c++17 OR upgrading it to at least support c++11 and change my CMakeLists.txt:
From
```
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -std=c++17 -lstdc++")
```
To
```
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -std=c++11 -lstdc++")
```

Here is my version for reference:
```
$ gcc --version
gcc (Debian 9.2.1-28) 9.2.1 20200203
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Eashwar93** [comment]
@Namburger I really had an outdated c++compiler. I updated and it works like a charm. Thanks a lot for making our lives simpler.

Sometimes its good that it doesn't work out of the box which gives us an opportunity to understand whats happening under the hood which is quite useful to debug

**Comment by Eashwar93** [comment]
> @Eashwar93 sorry about that, it looks like `test_utils.cc` wasn't included in the make rule which is what contains that helper function. Also, please make sure that you've built `libtensorflow-lite.a` from [this commit](https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5), otherwise you will get issue similar [to this one](https://github.com/google-coral/edgetpu/issues/54) (matter fact I've notice that we have quite a few issues regarding building).
> Since all these complexities will causes lots of confusion, I've made a separate repo for compiling this minimal example: https://github.com/Namburger/edgetpu-minimal-example/blob/master/README.md
> It is a single cmake rule it'll allow you to compile our code any where in 3 simple steps:
> 
> ```
> $ mkdir build && cd build
> $ cmake ..
> $ make
> ```
> 
> FYI: code was modified to include support for CPU models also.

thats great that it support CPU models as well. Thanks
