### ISSUE TITLE
Benchmark questions

### ISSUE THREAD

**Issue by s9013xx** [google-coral/edgetpu#105]
Hi
Is there any way to get the performance of each layer in one model? like this : 

Layer-Name-time(ms)
0:conv1/7x7_s2:5.63
1:pool1/3x3_s2:1.06
2:pool1/norm1:0.54
3:conv2/3x3_reduce:0.97
4:conv2/3x3:11.55
5:conv2/norm2:1.44

Thank you!

**Comment by Namburger** [comment]
@s9013xx 
Apologies, this is not supported at this time, but it is in our list of feature request!

**Comment by Namburger** [comment]
Related: https://github.com/google-coral/edgetpu/issues/41
