### ISSUE TITLE
edge tpu not leaving high power demand state after inference

### ISSUE THREAD

**Issue by Inesteem** [google-coral/edgetpu#109]
Hi,

I used the edge tpu usb accelerator for some time performing power measurements for my masters thesis. After needing to reset my system and reinstalling the whole software stack the power properties of the accelerator I am using have changed the slightest bit. Previously it happend to stay in some sort of idle state consuming something around 300 mW when not in use. Now, after using it the first time, it seemingly never returns in that low power state and instead consumes something between 900 and 1000mW even if it didnt perform any inferences in a while. Now I am wondering, is this some software problem/change, caused by another Tensorflow Version (I used TF 2.0, now I am using 2.1), or is my accelerator broken? Something else?

Thank you in advance!

**Comment by usbguru** [comment]
What host hardware and O/S are you using?  How are you measuring the supply current?

**Comment by Inesteem** [comment]
I have an external measurement setup, that works just fine by intercepting the power supply of the accelerator and reddirecting it via a shunt.  That should be accurat.

My OS is Ubuntu  18.04. I am using python 3.6.9, edgetpu.__version__ equals 2.14.0. TF as mentioned is 2.1.0. 
I do not use any cuda stuff; i use an asus laptop. with an i7 intel processor. 
I am confident to close any application connected to the accelerator (by using an interpreter object) before expecting it to idle. 
Hope that covers the question:D

**Comment by usbguru** [comment]
When you run the parrot inference test:  https://coral.ai/docs/accelerator/get-started/
What current measurements do you get before, during, and after?  Does it stay high after 5 minutes? 10 minutes?

**Comment by Inesteem** [comment]
Power before is something between 300 and 400 mW (I unplugged and replugged the TPU after using it for a while, it was still warm, usually it has in idle state something less then but close to 300 mW).  
The neural network execution has a peak power demand of something close to 1100 mW; after that it stays for at least 15 mins at a little bit more than 1000mW . Then I stopped the measurement. It never returns to idle, like it did some weeks ago.

**Comment by usbguru** [comment]
I am ordering a USB power monitor dongle today.  It will be interesting to see what my system does.

**Comment by Inesteem** [comment]
I would love to compare it! My theory is, since the TPU is very deterministic, that our measurements should be very similar. It definitely holds for the same accelerator, that multiple measurements of the same neural networks match.

**Comment by usbguru** [comment]
My measurements are quite similar to yours.  I am using this power meter (bought on amazon):

https://satechi.net/products/satechi-type-c-power-meter-for-new-macbook-macbook-pro-type-c-devices

I ran three tests:
1) Measured 0.07A before parrot inference, 0.18 to 0.19A right after the inference.  31 minutes later it was still at 0.18 to 0.19A.   Thats 350mW before inference, and 900mW after.

2) unplugged USB Accelerator, plugged it back in, and measured 0.07A.  After parrot inference, the measurement was 0.18 to 0.19.  Thirty-five minutes later it was still at 0.18 to 0.19A.

3) unplugged USB Accelerator, plugged it back in, and measured 0.07A.  After parrot inference, the measurement was 0.18 to 0.19.  Ten hours and thirty minutes later it was still at 0.18 to 0.19A.

**Comment by Inesteem** [comment]
Thank you, thank you so much! That is so good to know; Do you use the same software stack? Which tensorflow version? I think I will use a docker container to test some earlier TF versions. Just to be sure, because earlier this year the tpus behaviour was different. I think this is not ment to be this way, the TPU should return into idle state after inferencing (at least after 5-10 seconds).

**Comment by usbguru** [comment]
I have only the latest runtime installed:
sudo apt show libedgetpu1-max
Version: 14

How long ago did you install a previous version?  Do you recall what version it was?  I could try down-grading my system and see if the problem goes away.

**Comment by Inesteem** [comment]
I dont know it exactly; But I think before march everything was the old way. I needed to setup my whole system 6 - 8 weeks ago. Then, after a while, i recognized the change. I definitely used another tf version back then, TF 2.0. But for the rest... i have no idea :(
Maybe the edgetpu compiler was different too, but i didnt log using different versions (which i should have done).
When I have some time left I will do some experiments with docker containers. I will publish them here, if I find a version featuring a lower idle power demand of the accelerator. 

BTW, I am using the libedgetpu-std version, not the max. But I am sure that the max version should also have a lower power demand when idling.
