### ISSUE TITLE
DeeplabV3 MobileNetV2 Quantization for USB Coral TPU with custom input size ((100, 100) rather than (513, 513))

### ISSUE THREAD

**Issue by saturnin13** [google-coral/edgetpu#110]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device: Coral TPU
- TensorFlow installed from (source or binary): pip install tensorflow==1.15.0
- TensorFlow version (use command below):1.15.0
- Python version:3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Please provide the entire URL of the model you are using?**

https://github.com/tensorflow/models/blob/394baa9f21424d3522ccfbdcee8acd3840891ff6/research/deeplab/g3doc/quantize.md

**Describe the current behavior**
Good Evening,

I have been following the steps in https://github.com/tensorflow/models/blob/394baa9f21424d3522ccfbdcee8acd3840891ff6/research/deeplab/g3doc/quantize.md to quantize a DeeplabV3 MobileNetV2 model for the USB Coral TPU but I cannot get it to work.

Even when I start from the models provided at the bottom (not the 8_bits, the raw models), I cannot get it to run. And I even get different problem for both models.

For the deeplabv3_mnv2_pascal_train_aug:  
- The ```deeplab/train.py``` script for quantizing runs successfully.  
- The ```deeplab/export_model.py``` scripts step works.  
- The ```tflite_convert``` works too.  
- EdgeTPU compiler gets cryptic error message: ```Internal compiler error. Aborting!```

For the deeplabv3_mnv2_dm05_pascal_trainaug:
- The `deeplab/train.py` script for quantizing runs gets:
```ValueError: Total size of new array must be unchanged for MobilenetV2/Conv/weights lh_shape: [(3, 3, 3, 16)], rh_shape: [(3, 3, 3, 32)]```
I tried [this solution](https://github.com/tensorflow/models/issues/7869) unsuccessfully.

- Using the .pb file directly, the `deeplab/train.py` with quantization aware training fails with python crashing.

- Doing a post-quantization in python directly works.
- edgetpu_compiler works.
- But once ran on the TPU, we get 0.87 TPS, most likely because the edgetpu-converter cannot convert all to edgtpu.

Any guidance to get it working would be great. I am also open to solutions not following the guide from tensorflow.

**Describe the expected behavior**

It should not crash.

**Code to reproduce the issue**

Note: This might be related to https://github.com/google-coral/edgetpu/issues/72

Take the 2 models at the bottom of the https://github.com/tensorflow/models/blob/394baa9f21424d3522ccfbdcee8acd3840891ff6/research/deeplab/g3doc/quantize.md page (not the 8_bits one) and try to quantize them following the guide and run them on an USB Coral Edge TPU.

**Other info / logs**

See above

**Comment by Namburger** [comment]
Hello @saturnin13 
Could you attach both models so I can take a look?
Since you reached out to us via our private channel, you can also send it to us there.

**Comment by saturnin13** [comment]
The models that I have tried unsuccessfully to get working are the ones directly on the https://github.com/tensorflow/models/blob/394baa9f21424d3522ccfbdcee8acd3840891ff6/research/deeplab/g3doc/quantize.md page. The one at the bottom, namely mobilenetv2_dm05_coco_voc_trainaug and mobilenetv2_coco_voc_trainaug. I have also sent you our personal models via the private mean for you to be able to have a look.

**Comment by Namburger** [comment]
@saturnin13 
Thanks I'll response to you via our private channel!

**Comment by sramirez** [comment]
Any news about this topic?

**Comment by Namburger** [comment]
@sramirez My colleague shared his procedure for exporting and converting the model from thewith deeplabv3_mnv2_dm05_pascal_trainaug_8bit checkpoints. I'll share here for other to reference:
```
python deeplab/export_model.py \
    --checkpoint_path=../../deeplabv3_mnv2_dm05_pascal_trainaug_8bit/model.ckpt \
    --quantize_delay_step=0 \
    --crop_size=55 \
    --crop_size=55 \
    --model_variant="mobilenet_v2" \
    --decoder_output_stride="" \
    --export_path=../../deeplabv3_mnv2_dm05_pascal_trainaug_8bit/frozen_inference_graph.pb \
    --depth_multiplier=0.5 
```
```
tflite_convert \
  --graph_def_file=../../frozen_inference_graph.pb \
  --output_file=../../frozen_inference_graph.tflite \
  --output_format=TFLITE \
  --input_shape=1,55,55,3 \
  --input_arrays="MobilenetV2/MobilenetV2/input" \
  --inference_type=QUANTIZED_UINT8 \
  --inference_input_type=QUANTIZED_UINT8 \
  --std_dev_values=128 \
  --mean_values=128 \
  --change_concat_input_ranges=true \
  --output_arrays="ArgMax"
```
Here is the compiled model:
[frozen_inference_graph_edgetpu.tflite.tar.gz](https://github.com/google-coral/edgetpu/files/4718144/frozen_inference_graph_edgetpu.tflite.tar.gz)
