### ISSUE TITLE
Integration with OpenCV (Python)

### ISSUE THREAD

**Issue by sagilar** [google-coral/edgetpu#111]
The latest Mendel OS (v4.0 Day) adds support to OpenCV, but the documentation doesn't offer too much for this.

I'm trying to run a face recognition system using OpenCV (Python). It runs, but pretty slow, similar to how a Raspberry PI would run. I would like to integrate the capabilities of the TPU with OpenCV to improve the speed of video recognition, such as the `edgetpu_demo` does when running on the TPU.
Someone could say, hey you should use tf models instead, but the reality is that OpenCV makes much easier the implementation of custom models with few steps; that's why I decided to use OpenCV instead.

So, is there a chance to make run an OpenCV python code on the TPU instead on the CPU?

If it is not possible, I would like to hear additional alternatives. As I said, the system is running, slowly but running.

P.S: I use Coral Edge TPU Dev-Board.

Thanks in advance.

**Comment by Namburger** [comment]
@sagilar Sorry for the confusion, Opencv is used on our board for pre-processing inputs only (video stream, capturing frame, resizing...), the inference part on the edgetpu are only supported with tflite

**Comment by sagilar** [comment]
Ok, thanks for your response. Could you guide me if possible to a tutorial to modify the FaceNet model with my own dataset and convert it into tflite then?

Thank you so much. Have a great day.

**Comment by Namburger** [comment]
@sagilar I'm not aware of any facenet specific model, however we do have a ssd face detection model [here](https://github.com/google-coral/edgetpu/blob/master/test_data/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite) if that works for you.
[Here is an example](https://gist.github.com/Namburger/2f8523d14d738edff75e115835120738) of how you can use it with opencv!
