### ISSUE TITLE
Require armel versioned ARMv6 libedgetpu

### ISSUE THREAD

**Issue by kqalea** [google-coral/edgetpu#112]
Currently ARMv6 libedgetpu is build with armhf which default hard float enable

Which will cause ABI problem on some old openwrt devices because it is
default setup to soft float point and will not dynamic link the libedgetpu 

Do you consider release armel versioned library for old device s?

**Comment by Namburger** [comment]
@kqalea 
Interesting that you are asking for this!
Even with our armv6 release, we don't see many users who are using it. I'll bring this up with our team and will let you know.

**Comment by Namburger** [comment]
FYI this request will be fulfilled with this repo :)
https://github.com/google-coral/libedgetpu

**Comment by kqalea** [comment]
This is great!!! Thanks
