### ISSUE TITLE
RESIZE_NEAREST_NEIGHBOR error, again

### ISSUE THREAD

**Issue by albertfaromatics** [google-coral/edgetpu#114]
Hi,

I'm trying to convert a tflite model with the compiler to be deployed on the Coral USB, but I'm getting the error:

ERROR: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR ' version '3'

I'm using google colab to achieve the conversion, and I have tried using tensorflow2.2.0, tf-nightly2.3.0 and tensorflow1.15, all of them give me some kind of error when applying the tflite model to the compiler

Which version should I use? It was working 1 month ago, same model, with tf2.1, but it is not working now.

Thanks

**Comment by Namburger** [comment]
@albertfaromatics What compiler version are you using?
This should have been fixed with [this release](https://github.com/google-coral/edgetpu/issues/31#issuecomment-585836272).

**Comment by albertfaromatics** [comment]
Latest one. I'm installing from apt

**Comment by Namburger** [comment]
Can you attach your model?
Hopefully the new compiler release didn't break this feature

**Comment by albertfaromatics** [comment]
[converted_model.zip](https://github.com/google-coral/edgetpu/files/4634385/converted_model.zip)

This model was converted using the last tf-nightly version on google colab.

I get the error with this

**Comment by Namburger** [comment]
@albertfaromatics 
Thanks for the report. This model passes on our head compiler now, it'll be fixed by next release. Apologies but I don't have a release date for the next one. 
Closing for now.

**Comment by Namburger** [comment]
@albertfaromatics sorry for the long wait but the new compiler should be shipped within this month, mean while, our lead allowed us to compile from HEAD and send to users :)
[converted_model_edgetpu.tflite.tar.gz](https://github.com/google-coral/edgetpu/files/4885232/converted_model_edgetpu.tflite.tar.gz)

**Comment by ricardodeazambuja** [comment]
Hi @Namburger. I'm trying a really simple toy model to test the resize (Edge TPU Compiler version 15.0.340273435). I tried bilinear and nearest, but the compiler keeps telling me:
```
Operator                       Count      Status

MUL                            1          Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        1          Operation version not supported
RESIZE_BILINEAR                1          Operation version not supported
```

Here is my really simple toy model:
```
input1 = tf.keras.layers.Input(shape=input_shape)
input2 = tf.keras.layers.Input(shape=input_shape)
input1_r = tf.keras.layers.experimental.preprocessing.Resizing(100, 100, interpolation='bilinear')(input1)
input2_r = tf.keras.layers.experimental.preprocessing.Resizing(100, 100, interpolation='nearest')(input2)

outputs = tf.keras.layers.Multiply()([input1_r,input2_r])
```

**Comment by Xoisai** [comment]
Hello @ricardodeazambuja, did you manage to get this working for RESIZE_NEAREST_NEIGHBOR?
