### ISSUE TITLE
rpi3b usb accelerator abnormal inference speed.... very sloooow

### ISSUE THREAD

**Issue by natxopedreira** [google-coral/edgetpu#115]
Hello

Im running a raspbery pi3b with Buster, python 3.7 and fresh usb accelerator install
[https://coral.ai/docs/accelerator/get-started/ ](https://coral.ai/docs/accelerator/get-started/ )

pip3 freeze result
`tflite-runtime==2.1.0.post1`

Im running this example
[https://github.com/google-coral/tflite/tree/master/python/examples/detection](https://github.com/google-coral/tflite/tree/master/python/examples/detection)

And in the page is mentioned this benchmark as reference
-------------------------------------------------------------------------------------
INFO: Initialized TensorFlow Lite runtime.
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
33.92 ms
19.71 ms
19.91 ms
19.91 ms
19.90 ms
-------RESULTS--------
tie
  id:     31
  score:  0.83984375
  bbox:   BBox(xmin=228, ymin=421, xmax=293, ymax=545)
person
  id:     0
  score:  0.83984375
  bbox:   BBox(xmin=2, ymin=5, xmax=513, ymax=596)

But im getting a much slower inferece speed
-------------------------------------------------------------------------------------
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
276.87 ms
75.67 ms
75.27 ms
74.61 ms
74.14 ms
-------RESULTS--------
tie
  id:     31
  score:  0.83984375
  bbox:   BBox(xmin=226, ymin=417, xmax=290, ymax=539)
person
  id:     0
  score:  0.83984375
  bbox:   BBox(xmin=2, ymin=5, xmax=507, ymax=590)

**Comment by albertfaromatics** [comment]
USB 2.0 connection maybe?

**Comment by Namburger** [comment]
@natxopedreira did you run the edgetpu model of the CPU model?
This seems like results from the ssd_mobilenet CPU model.

**Comment by natxopedreira** [comment]
I run tpu, per docs

`python3 detect_image.py \
  --model models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite \
  --labels models/coco_labels.txt \
  --input images/grace_hopper.bmp \
  --output images/grace_hopper_processed.bmp`

**Comment by natxopedreira** [comment]
I don't think is because usb2 as i have another usb accelerator that is able to get 20fps inferencing 3 models on a 320x240 video.

I expect to have similar performance

**Comment by Namburger** [comment]
@natxopedreira 
Can you share the output of this command?
```
$ dpkg -l | grep edgetpu
```
Your results seems wayyy too fast for a CPU model but definitely too slow for edgetpu.

FYI:
```
pi% dpkg -l | grep edgetpu
ii  libedgetpu1-max:armhf                14.0                                armhf        Support library for Edge TPU
ii  python3-edgetpu                      14.0                                armhf        Edge TPU Python API
```

Here is a USB2.0 result:
```
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
221.34 ms
35.75 ms
35.74 ms
35.84 ms
35.54 ms
```

**Comment by natxopedreira** [comment]
@Namburger 
I just take a fresh sd card loaded with Buster and im able to reproduce the data i was getting
`Note: The first inference is slow because it includes loading the model into Edge TPU memory.
278.10 ms
75.63 ms
75.69 ms
75.06 ms
75.28 ms
-------RESULTS--------
tie
  id:     31
  score:  0.83984375
  bbox:   BBox(xmin=226, ymin=417, xmax=290, ymax=539)
person
  id:     0
  score:  0.83984375
  bbox:   BBox(xmin=2, ymin=5, xmax=507, ymax=590)`

The output to this
`dpkg -l | grep edgetpu`

`ii  libedgetpu1-std:armhf                 14.0                                   armhf        Support library for Edge TPU
ii  python3-edgetpu                       14.0                                   armhf        Edge TPU Python API`

**Comment by natxopedreira** [comment]
Thats what i did on a fresh sd card

`echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
`
`curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -`

`sudo apt-get update`

`sudo apt-get install libedgetpu1-std`

`pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_armv7l.whl`

` sudo apt-get install python3-edgetpu`

`mkdir coral && cd coral`
`git clone https://github.com/google-coral/tflite.git`
`cd tflite/python/examples/detection`
`./install_requirements.sh`

`python3 detect_image.py \
  --model models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite \
  --labels models/coco_labels.txt \
  --input images/grace_hopper.bmp \
  --output images/grace_hopper_processed.bmp`

**Comment by Namburger** [comment]
@natxopedreira Can you try using the max operating frequencies instead?
```
$ sudo apt install libedgetpu1-max
```

**Comment by natxopedreira** [comment]
@Namburger 
`ii  libedgetpu1-max:armhf                 14.0                                   armhf        Support library for Edge TPU`
`ii  python3-edgetpu                       14.0                                   armhf        Edge TPU Python API`

Tried 4 different ports on rpi, no more USB devices are connected, im using a ssh connection. I get allways the same speed +-2-3ms

----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
270.32 ms
75.66 ms
75.56 ms
75.93 ms
75.56 ms
-------RESULTS--------
tie
  id:     31
  score:  0.83984375
  bbox:   BBox(xmin=226, ymin=417, xmax=290, ymax=539)
person
  id:     0
  score:  0.83984375
  bbox:   BBox(xmin=2, ymin=5, xmax=507, ymax=590)

**Comment by Namburger** [comment]
@natxopedreira 
I'll bring this up with my team, we'll try to reproduce and keep you updated.

**Comment by natxopedreira** [comment]
@Namburger 
Thank you, let me know if i can help

**Comment by Namburger** [comment]
> I don't think is because usb2 as i have another usb accelerator that is able to get 20fps inferencing 3 models on a 320x240 video.

Hi, I just realized this, does this means that one of your accelerator is much faster than the other?

**Comment by natxopedreira** [comment]
Hi @Namburger is another brand of device

**Comment by Namburger** [comment]
@natxopedreira gotcha, I'll order a pi3 b and try to reproduce, unfortunately this is not reproducible on my pi4

**Comment by natxopedreira** [comment]
@Namburger 
Let me know if there is something i can try/do so you do not have to buy rpi3b

**Comment by Namburger** [comment]
@natxopedreira 
Thanks, and sorry for this issue but I'm not too sure what you could do here. Essentially, I'm trying to recreate the issue and try with different accelerators to see if your may have a HW issue?
It's just a little hard to tell since mine is a pi4 and I can't reproduce, anyways, what OS are you running on?

**Comment by natxopedreira** [comment]
@Namburger 
Im on raspbian Buster, do not worry i understand that replicate an issue is not always easy.

When i mentioned the results i get with the other brand was to show that in my current platform, rpi3b Buster USB2.0 i was able to get that kind of performance.

I also make a clean system install in a sd industrial grade card to try.

Dont know what HW issue i can get.... but im not an expert here.

**Comment by natxopedreira** [comment]
@Namburger 
Are you able to reproduce the issue?

**Comment by Namburger** [comment]
@natxopedreira sorry for the late update...
Basically I've went through this with our team and it turns out that we do have regular benchmarks/testing for multiple platforms. As it turns out, the ssd-mobilenet v1 performs around 60-70ms and v2  around 65-75ms quite consistently. These numbers are surprisingly much slower in the pi4 as I've experience. I'm not sure if there are anything we can do to fix this, as it seems platform independent, unfortunately.

**Comment by natxopedreira** [comment]
@Namburger Not a problem.
I was feeling bad as i was forcing to buy new hardware and always exist the possibility that i was making something wrong, but seems that was not my fault.

I will keep the device to use in another project where we use a different platform.

Thanks for your time
