### ISSUE TITLE
Unable to install tflite_runtime on Coral Devboard

### ISSUE THREAD

**Issue by BalajiNJL** [google-coral/edgetpu#116]
Hi,

I am following the steps mentioned in this 'Get started' document 
https://coral.ai/docs/dev-board/get-started/#4-update-the-mendel-software 

sudo apt-get update
sudo apt-get dist-upgrade

pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl
I get an error as follows
mendel@lime-goose:~$ pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl
tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl is not a supported wheel on this platform.

I tried latest version from 
https://www.tensorflow.org/lite/guide/python
https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl

I still get the same error. Can someone point me to correct version.

Thanks,
-Balaji NJL

**Comment by Namburger** [comment]
Can you share these output:
```
uname -a
python3 --version
cat /etc/os-release
```

**Comment by BalajiNJL** [comment]
Thanks for quick response. Here it is.

$ uname -a
Linux lime-goose 4.9.51-imx #1 SMP PREEMPT Thu Jan 31 01:58:26 UTC 2019 aarch64 GNU/Linux
$ python3 --version
Python 3.5.3
$ cat /etc/os-release
PRETTY_NAME="Mendel GNU/Linux 2 (Beaker)"
NAME="Mendel GNU/Linux"
VERSION_ID="2"
VERSION="2 (beaker)"
ID=mendel
ID_LIKE=debian
HOME_URL="https://aiyprojects.withgoogle.com/"
SUPPORT_URL="https://aiyprojects.withgoogle.com/"
BUG_REPORT_URL="https://aiyprojects.withgoogle.com/"

**Comment by Namburger** [comment]
@BalajiNJL 
This is the same issue with this one: https://github.com/google-coral/tflite/issues/17#issuecomment-624124069, you can look there for answer.
FYI: The issue is due to you having a much outdated OS, while our documentation is for a newer one.
