### ISSUE TITLE
[PoseNet] Compile model out of components and co-compile 2nd model for TPU

### ISSUE THREAD

**Issue by FHermisch** [google-coral/edgetpu#117]
Hi,
I want to have my custom model co-compiled with PoseNet for EdgeTPU. This leads to the task to compile the PoseNet model (e.g. [https://github.com/google-coral/project-posenet/blob/master/models/mobilenet/components/posenet_mobilenet_v1_075_481_641_quant.tflite](url)) again out of the basic part and the decoder part.  
Is there a way of doing this with the regular edgetpu compiler (and also co-compile my model)? Is there another way to achieve this - maybe calculating the memory footprint and cache-hashes manually and writing these as meta-data into the compiled models?  
I already read the discussion on #86 - this seams to be more on feeding the output of the basic model into the decoder model. Not compiling the combined model.  
My environment used:  
Edge TPU Compiler version 2.1.302470888  
Coral Dev Board with Mendel-Day  
My custom model is very small with 6 operations - taking 15.00KiB of On-chip memory   

Best regards,
Florian

**Comment by Namburger** [comment]
@FHermisch You should be able to cocompile the 2 models like this:
```
$ edgetpu_compiler -s posenet_mobilenet_v1_075_481_641_quant.tflite <your_model>.tflite
```

**Comment by FHermisch** [comment]
Hi Namburger, 
thanks ,but this is only compiling the 'basic' part of the posenet model which produces heatmaps as output - I want to integrate the decoder part too? (sorry, I only put the link to the quant model in my initial question, which is of course easy to compile).
In the repositories there are the 'quant' models, the 'decoder' models and the 'quant_decoder' models. I want to have a new 'quant_decoder' model which is co-compiled with my model.

A call to  
`edgetpu_compiler -s posenet_mobilenet_v1_075_481_641_quant_decoder.tflite <mymodel>tflite `  
leads to:  
```
Edge TPU Compiler version 2.1.302470888
ERROR: Encountered unresolved custom op: PosenetDecoderOp.
ERROR: Node number 32 (PosenetDecoderOp) failed to prepare.
Internal compiler error. Aborting!
```  
How to inject the decoder part as the missing custom op into that operation?

**Comment by Namburger** [comment]
@FHermisch 
I see, the decoder op is a custom op, I don't believe that the compiler that we release would allow this. @mtyka do you have more insight on this?

**Comment by mtyka** [comment]
Correct, unfortunately right now you can't co-compile PoseNet because the compiler cannot be made to ignore the custom decoder op. The work around is to co-compile only the base-model without the custom decoder and then call the decoder manually afterwards as discussed in https://github.com/google-coral/edgetpu/issues/86 (the decoder runs on CPU anyways so it shouldn't matter performance wise.

**Comment by FHermisch** [comment]
Hello Mike, 
thanks - I suspected that there is currently no other way. As I would like to present this during training sessions, it would have been great to end up with two *_edgetpu.tflite models which can be handled in the same way and being co-compiled to run on TPU (ok - with some ops running on CPU). Now it has to end with two models and some custom code which cannot be compiled - more difficult to explain... I hope for 'eel'.
