### ISSUE TITLE
Is the edgetpu internal accumulated value available

### ISSUE THREAD

**Issue by jk78346** [google-coral/edgetpu#118]
I'm not sure but I guess that edgetpu hardware has some sort of accumulator in longer bits (maybe 32bits ?) rather than 8bits. If not, it seems not possible for edgetpu to provide reasonable accuracy of results because of overflow issue. However, I just want to know if it is possible that we can retrieve the intermediate accumulation result in longer bits representation before output requantization? 

I know that both input and output data are in fix-pointed numbers, which means for the output we are equivalently choosing a range of 8 bits to represent the data. But since so, it must have the accumulated result in higher precision (with more bits stored) in the hardware for us to choose from. 

The idea comes from the architecture of TPU [paper](https://arxiv.org/pdf/1704.04760.pdf).

**Comment by Namburger** [comment]
@jk78346 Apologies, but I expect that more info of the TPU's internal will be shared at a later time, however right now we can't share anything that's isn't in the public documentation on our page.
