### ISSUE TITLE
TPU streaming server not working

### ISSUE THREAD

**Issue by kpham123** [google-coral/edgetpu#119]
I noticed while running the camera demos [here](https://coral.ai/docs/dev-board/camera/#using-a-streaming-server) that after some time I started seeing the mdt shell close by socket exception. The streaming server was working initially. 

mendel@queen-zebra:~$ Socket exception: An existing connection was forcibly closed by the remote host (10054)
Connection to queen-zebra at 192.168.101.2 closed with exit code -1

Seemed as if TPU entered high power state because fan turned on. This was ok a few times and I would just reconnect to the board again until I started to also get below error: 
mendel@queen-zebra:~$ edgetpu_detect \
> --model ${DEMO_FILES}/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(edgetpu_detect:4051): Gtk-[1;33mWARNING[0m **: [34m05:10:11.342[0m: cannot open display:

Same issue occurs when I try "edgetpu_demo --stream". So now any streaming server based application won't run. Any ideas to fix the streaming server issue? 

EDIT: I'll also add that it seems like "ps -u" is showing a lot less processes are currently running. I had used "ps -u" to find the pid of server and kill it a few times and restart it on initial socket disconnect. I don't recall exactly what process had been running the first time but now there are none.

**Comment by Namburger** [comment]
@kpham123 
Can you try restarting the weston service and/or the dev board and run it again?
```
$ sudo systemctl restart weston
```
or 
```
$ sudo reboot now
```

**Comment by kpham123** [comment]
It's working again now, thanks. For some reason the restart I tried prior didn't work.
