### ISSUE TITLE
How to get the Coral Dev Board to auto run a detection inference on power-up

### ISSUE THREAD

**Issue by PushkarChatterji** [google-coral/edgetpu#120]
Hello,

I have an object detection model that I am able to run using the CLI. It takes the video feed from a USB camera plugged in and displays to the connected screen via HDMI.

I am unable to get this script to auto run on power-up. 

When I convert this to s systemd / systemctl service I get the following error:

`mendel@red-finch:~$ sudo systemctl status detect.service
● detect.service - IFP Detector
   Loaded: loaded (/lib/systemd/system/detect.service; static; vendor preset: enabled)
   Active: active (running) since Tue 2020-05-19 11:09:08 UTC; 12s ago
 Main PID: 4004 (python3)
    Tasks: 14 (limit: 797)
   Memory: 157.5M
   CGroup: /system.slice/detect.service
           └─4004 /usr/bin/python3 -W ignore -u detect.py

May 19 11:09:08 red-finch systemd[1]: Started IFP Detector.
May 19 11:09:12 red-finch python3[4004]: Unable to init server: Could not connect: Connection refused
May 19 11:09:12 red-finch python3[4004]: Traceback (most recent call last):
May 19 11:09:12 red-finch python3[4004]:   File "detect.py", line 174, in <module>
May 19 11:09:12 red-finch python3[4004]:     main()
May 19 11:09:12 red-finch python3[4004]:   File "detect.py", line 128, in main
May 19 11:09:12 red-finch python3[4004]:     geo = screen.get_monitor_geometry(screen.get_primary_monitor())
May 19 11:09:12 red-finch python3[4004]: AttributeError: 'NoneType' object has no attribute 'get_monitor_geometry'
`   
I am guessing that the script is unable to connect to the wayland display server which is why I am unable to find the resolution of the connected monitor.

Any help on how to get this to auto run would be appreciated!

Thanks.

**Comment by Namburger** [comment]
Hello, could you take a look at my example service file:
```
[Unit]
Description=systemd auto face detection service
After=weston.target

[Service]
PAMName=login
Type=simple
User=mendel
WorkingDirectory=/home/mendel
Environment=DISPLAY=:0
ExecStart=/bin/bash /usr/bin/detect_service.sh
Restart=always

[Install]
WantedBy=multi-user.target
```
The `detect_service.sh` script just runs this:
```
edgetpu_detect --model fullpath/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite --label fullpath/coco_labels.txt
```

I believe what you need is the `After=weston.service` and the `Environment=DISPLAY=:0`
I have the whole instruction [here](https://gist.github.com/Namburger/1f42de2bd9a316e6e8f6538ec599c676).

**Comment by PushkarChatterji** [comment]
Thanks! This works.
