### ISSUE TITLE
Tensors must be 3-dimensional

### ISSUE THREAD

**Issue by jakelevi1996** [google-coral/edgetpu#121]
As stated in the [Edge TPU Model Requirements documentation](https://coral.ai/docs/edgetpu/models-intro/#model-requirements):

> Tensors are either 1-, 2-, or 3-dimensional. If a tensor has more than 3 dimensions, then only the 3 innermost dimensions may have a size greater than 1.

To me this seems quite limiting, as it prevents me from doing image processing using CNNs in batches, where 4 dimensions are needed (batch size, height, width, number of channels). The reason I want to perform inference in batches is as follows: I am trying to benchmark different edge AI platforms by testing accuracy and latency when performing inference on the MNIST test-set (10,000 images); on the Coral Dev Board, when performing inference on the TPU, the fastest inference time I can get (using a single dense output layer and no hidden layers) is about 3s, whereas on my PC CPU I can get comfortably <1s. I assume the reason the TPU cannot get a lower inference time is because the batch size is 1, and therefore after every image, the Dev Board has to transfer the inference results back to the CPU, and load a new image into the TPU. I assume (/hope) the Dev Board inference time would be a lot faster if it could process the images in batches, which would require it to allow rank-4 tensors when using CNNs.

**Comment by Namburger** [comment]
@jakelevi1996 
Hi again! So the limits in the tensor dimensions is due to some HW limitation in the edgetpu. I don't think there's a way to beat this with SW but we are looking to expand the product lines to fit the need for batch processing. The best work around for this at this point is to have multiple tpus that each deal with different inputs. Unfortunately, I understand that it's not the best solution :/

**Comment by jakelevi1996** [comment]
Hi @Namburger , thanks again for the speedy response (as per usual by now!) I suspected this issue might not be easy to fix, but thought I'd raise it anyway because I couldn't see this exact issue anywhere else, and I think that solving it would make the Dev Board a more flexible product

**Comment by Namburger** [comment]
@jakelevi1996 Thanks for the awareness, we definitely have this in mind. Timing may not be on our side during these time but definitely follow our [news](https://coral.ai/news) for updates!
