### ISSUE TITLE
[PoseNet] : Encountered unresolved custom op: PosenetDecoderOp.

### ISSUE THREAD

**Issue by Eashwar93** [google-coral/edgetpu#123]
Hello Team,

I am experimenting with all types of models with EdgeTPU to be used in a robot. I'm using C++ for the inference to make it really fast. I was able to build packages for Classification and Detection and I set onto Human Pose Estimation as it would be really helpful in detecting pedestrians on the fly. I wanted to understand the output tensor shape of posenet model and found it to be 340 * 170 *10 * 1.

While loading the model in the interpreter I guess I'm getting the the below error

`Encountered unresolved custom op: PosenetDecoderOp.`

So I did a bit of research and I found that I need to PosenetDecoderOp is a custom Operation that is not defined in the standard operation list of TFlite to be linked to the resolver.

I found the source code for the Decoding operation in the [edgetpu repo](https://github.com/google-coral/edgetpu/tree/master/src/cpp/posenet)

I'm currently using Cmake as the build tool and not Bazel for the package that I'm creating.

Is there any example on how to deal with this issue?

**Comment by Namburger** [comment]
@Eashwar93 I think you'll just need to to build the decoder ops and register it similar to how we did with our native layer: https://github.com/google-coral/edgetpu/blob/master/src/cpp/basic/basic_engine_native.cc#L89

**Comment by Eashwar93** [comment]
@Namburger Ah ok, thanks a lot, I will try to implement this and comeback again if I have some issues

**Comment by Eashwar93** [comment]
@Namburger Works completely fine. Thanks once again for the strong support

**Comment by Eashwar93** [comment]
@Namburger I tried writing a inference in C++ with posenet. The raw decoded output vector from the posenet that I received is a bunch of zeros to be precise a vector of 521 zeros.

I assure you that the input dimensions are correct and I did not get any build errors when I linked the Decode Op.

Any idea what I could possibly do wrong here. Let me know in-case if you want to inspect my Cmake file. I can share it if needed.

**Comment by mtyka** [comment]
Which exact network are you running ? All zeros in out put may be correct (if no poses are detected). 
Also, the output from the decoder network is 4 separate tensors, take a look at the example here https://github.com/google-coral/project-posenet
The outputs could be for example:

KeyPointCoordinates (10 poses, 17 key points, x and y)

name: poses
type: float32[1,10,17,2]
quantization: -10 ≤ q ≤ 10
location: 4

KeyPoint scores (10 poses, 17 key points)
name: poses:1
type: float32[1,10,17]

Pose scores (10 poses)
name: poses:2
type: float32[1,10]

Number of detected poses (one scalar)
name: poses:3
type: float32[1,1]


Now that's exactly 521 floats (10*17*2 + 10*17+ 10 + 1) 
Looks like your output vector is the buffer of these 4 tensors concatenated.

Looks like it works but there's a problem with the input image or the input image has no poses in it (in which case you'd get all zeros)

**Comment by Eashwar93** [comment]
@mtyka Thanks for your detailed response. I tried running the following models 
[model1](https://github.com/google-coral/project-posenet/blob/master/models/mobilenet/posenet_mobilenet_v1_075_353_481_quant_decoder_edgetpu.tflite)
[model2](https://github.com/google-coral/project-posenet/blob/master/models/mobilenet/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite)
Actually I'm aware of the [posenet](https://github.com/google-coral/project-posenet)  repo and understood how I need to post-process the buffer of the 4 tensors concatenated.

I can assure you that I'm using the same OpenCV Image pre-processing pipeline that I used for detection and classification of video stream which works. Image Pre-processing code snippets for your reference. `image_width` is set to **481** and `image_height` is set to **641** by default so that I can reshape it to **353 x 481** later on using OpenCV depending on the model I use. 

```
edge::HumanPoseEngine engine(model_path, edgetpu_context, with_edgetpu);
	const auto& required_input_tensor_shape = engine.GetInputShape();

	cv::VideoCapture cam_frame(source);
	if(!cam_frame.isOpened())
	{
		std::cout << "Error opening camera \n";
	}
	cam_frame.set(cv::CAP_PROP_FPS, 30.0f);
	cam_frame.set(cv::CAP_PROP_FRAME_HEIGHT, image_height);
	cam_frame.set(cv::CAP_PROP_FRAME_WIDTH, image_width);

	cv::Mat frame;

	while(true)
	{
		cam_frame >> frame;
		const auto& input = edge::GetInputFromImage(frame,required_input_tensor_shape[1],required_input_tensor_shape[2],required_input_tensor_shape[3]);
```
GetInputFromImage function
```
std::vector<uint8_t> GetInputFromImage(cv::Mat input_frame,const int& width, const int& height, const int& channels)
	{
		cv::resize(input_frame, input_frame, cv::Size(width,height));
		cv::cvtColor(input_frame,input_frame,CV_BGR2RGB);
		cv::Mat flat = input_frame.reshape(1, input_frame.total()*input_frame.channels());
		std::vector<uint8_t> in_vec= input_frame.isContinuous()? flat : flat.clone();
		return in_vec;
        }
```

Do you see anything odd here in my Input preprocessing that might just lead to zeros or am I using wrong models? Please let me know.

**Comment by mtyka** [comment]
I think you probably have width and height reversed. The input shape of the network is
1*y*x*3 so 1*481*641*3 so height is 481 and width is 641

**Comment by Eashwar93** [comment]
@mtyka Thanks a lot! It works. Is this convention[1,h,w,c] the same for all the models?
 I'm able to visualize the keypoints in my camera stream. Also the the keypoints are in the (y,x) form which I totally forgot. Also its nice that the keypoint results are scaled according to the input size of the network.

I just ran into another problem. There is a offset of the keypoints in the x axis. Is there any offset correction that I need to perform? I the image size is exactly `h=353 x w=481` as I used the model `353 x 481` model. The Y axis seems to be ok. I wondered if I flipped the frame, but I haven't as  I move the to the left the points move to the left as well and not to the right.

I followed your python code in the posenet repo and found [this line.](https://github.com/google-coral/project-posenet/blob/f74ff7973e4b4349aaad9f50c7f0bc77fe33775b/pose_camera.py#L59) 
I understand you are doing some offset and scaling but could not quite get what exactly is going on.

The scaling part I understand, I suppose that  I need to scale the keypoints by a ratio of the `diplay size/network input size` but I don't quite get the offset part if there exists any.

Below image for your reference.
![pose_1](https://user-images.githubusercontent.com/51912916/83069360-0a6b4080-a06a-11ea-9ae1-e53b0763310e.png)

**Comment by mtyka** [comment]
Yes NHWC is a typical convention for neural nets. Note that normal images are actually also in this order even though we usually talk about x&y and not y&x.

The rescaling issue is because your input image (the image you attached) has a different aspect ratio than the network input, but the rescaling code likely preserves aspect ratio and probably adds black borders in stead of stretching the image. The keypoints y&x coordinates are relative to the actual input image that goes into the network.

**Comment by Eashwar93** [comment]
@mtyka you are absolutely right. I thought I made sure that the image I'm displaying is the same as the image I have sent to the NN, but its not. Thanks again for your strong support. I will look into this further.
I should have debugged this by myself, sorry for the inconvenience.

**Comment by simoneangarano** [comment]
> @Eashwar93 I think you'll just need to to build the decoder ops and register it similar to how we did with our native layer: https://github.com/google-coral/edgetpu/blob/master/src/cpp/basic/basic_engine_native.cc#L89

Sorry, could you please explain how am I supposed to do that? Thank you!
