### ISSUE TITLE
TensorFlow tf.lite.experimental.load_delegate compatibility

### ISSUE THREAD

**Issue by leigh-johnson** [google-coral/edgetpu#124]
Hi,

Thanks for all the work y'all do!

I noticed `12-1` is the last version of `libedgetpu1-std` that is compatible with TensorFlow's `tf.lite.experimental.load_delegate` API.

Based on #71, I can see libedgetpu1-std is linked against a specific TensorFlow rev, and that future revs of TensorFlow contain load_delegate API changes that are not compatible with `libedgetpu`. As a workaround, you've packaged a pinned rev of `tf.lite.Interpreter` and released as a `tflite_runtime` wheel. 

* Are y'all waiting for the delegate API to be moved out of the experimental package to support it?

* What's the timeline on `libedgetpu` becoming open-source? I'd love to assist by proposing a patch for this issue. 
E.g. I'd love to see the source for https://github.com/google-coral/edgetpu/blob/657d2b654101540164af240eacb31440ff6f535d/libedgetpu/edgetpu_c.h#L98

I'm also Google Developer Expert (machine learning) so I might be able to connect with folks who are invested in resourcing this. I'm also happy to do recon by attending SIG meetings, if that's what's missing here. Let me know what is blocking you on this.

**Comment by Namburger** [comment]
@leigh-johnson 
Thanks for submitting the issue, sorry, didn't see this earlier but I've responded to most of this directly via this issue https://github.com/leigh-johnson/rpi-deep-pantilt/issues/13#issuecomment-634016827

Just to clarify, the commit that we linked against for this release is based on [this commit](https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5). We are definitely aware of all the issues this is causing, especially for c++ users, as you can see this [growing list](https://github.com/google-coral/edgetpu/issues?q=label%3Abuild+is%3Aclosed) :)

This is still a working in progress and we don't have a release date yet, unfortunately.
