### ISSUE TITLE
 TFLite 2.2.0 delegate API not working with Edge TPU runtime

### ISSUE THREAD

**Issue by othmaneAZ** [google-coral/edgetpu#126]
Tensorflow-lite API : Release r2.2.0 
EdgeTPU runtime : latest version of 1st April 2020 https://dl.google.com/coral/edgetpu_api/edgetpu_runtime_20200331.zip
------------------------------------------------------------------------------------------------------------- 
Hello, 
I'm trying to run an inference using the release r2.2.0 of the tensorflow-lite API and especially the delegates API by adding an experimental delegate to the interpreter instantiation. For the EdgeTPU runtime I'm using the version mentioned above. 
` interpreter = tflite.Interpreter(self._model_file, 
                                            experimental_delegates=[tflite.load_delegate('libedgetpu.so.1')]) ` 
I'm getting this error **RuntimeError: Internal: Unsupported data type in custom op handler: -1342003056Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.**

**Comment by Namburger** [comment]
Duplication of this issue: https://github.com/google-coral/edgetpu/issues/44

@othmaneAZ
Unfortunately, tensorflow package will no longer work with `libedgetpu.so` at this time. Please use the `tflite_runtime` package instead of the full tensorflow package as documented [here](https://coral.ai/docs/edgetpu/tflite-python/#load-tensorflow-lite-and-run-an-inference).

**Comment by lawrence-jeff** [comment]
I realize this is closed - but the language of the referenced page certainly doesn't make the limitation clear. It specifically says "you can access from the full tensorflow package"

__Although you can access the TensorFlow Lite API from the full tensorflow Python package, we recommend you instead use the tflite_runtime package. This package includes only the Interpreter class and load_delegate() function, which is all that's required to run inference, saving you a lot of disk space._

Shouldn't this say "You must use the tflite_runtime package. The full Tensorflow lite API is not currently supported"?

**Comment by Namburger** [comment]
@lawrence-jeff woa, thanks for the suggestion, that is indeed true. One way that should works in theory is if you build your own tensorflow package from [source](https://github.com/tensorflow/tensorflow) using the same commit as our shared library: https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5

But that's totally not something that we'd want users to have to do
