### ISSUE TITLE
Posenet models using Tensorflow-lite python API on EdgeTPU accelerator 

### ISSUE THREAD

**Issue by othmaneAZ** [google-coral/edgetpu#127]
Hello, 
I'm trying to run an inference using the **` posenet_mobilenet_v1_075_353_481_quant_decoder.tflite`** using the **`Tensorflow-Lite`** and experimental delegates and not the Edge TPU Python API. I'm using the right version of the Tflite_runtime documented [here](https://coral.ai/docs/edgetpu/tflite-python/#load-tensorflow-lite-and-run-an-inference). I can't find any reliable example. I tried to make a very sample example for pose estimation and the source code is bellow: 

`img = Image.open('couple.jpg')
img.resize((353, 481), Image.NEAREST)
model_file = "posenet_mobilenet_v1_075_353_481_quant_decoder_edgetpu.tflite"
interpreter = tflite.Interpreter(model_path=model_file,
                                experimental_delegates=[tflite.load_delegate('libedgetpu.so.1')])
input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

interpreter.allocate_tensors()
print("Allocated tensors")

input_data = np.expand_dims(img, axis=0)

interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()`

I'm getting this very famous error : 
`RuntimeError: Encountered unresolved custom op: xxx Node number 0 failed to prepare.`

I'm not I am understanding this well, I have seen in this issue #86 that a **posenet_decoder.so** should be built using a BUILD script and then called instead of the **libedgetpu.so** in the experimental delegates to register the custom op. Are we calling implicitly the edgetpu runtime in this posenet_decoder ? Can you enlighten me on how we use posenet models with TFlite python API on Edge TPU Accelerator ? 

Thank you,

**Comment by Namburger** [comment]
@othmaneAZ 
From what I understand, you'll need to register both the `libedgetpu.so` and `posenet_decoder.so`. From #86, @mtyka suggestion was to have 2 separate interpreters for handling the decoder and the other ops. 
For using a single interpreter, I wonder if something like this will works: `load_delegate(['libedgetpu.so.1', 'posenet_decoder.so'])` to load both ops?
Anyhow, if you use our basic engine instead, we've already registered both ops [like this](https://github.com/google-coral/edgetpu/blob/master/src/cpp/basic/basic_engine_native.cc#L87) (the python api wraps around the c++ api so it'll be the same thing if you just use the basic engine from [here](https://github.com/google-coral/edgetpu/blob/master/edgetpu/basic/basic_engine.py)).
Mike also had a posenet engin that wraps around the basic engine [here](https://github.com/google-coral/project-posenet/blob/master/pose_engine.py) that you can reference for usage.

**Comment by Namburger** [comment]
Okay, so based on  [this documentation](https://www.tensorflow.org/api_docs/python/tf/lite/experimental/load_delegate) the tflite's python API does allows you to have multiple delegates, just tested and this works:

```
import tflite_runtime.interpreter as tflite
tpu = tflite.load_delegate('libedgetpu.so.1')
posenet = tflite.load_delegate('posenet_decoder.so')
interpreter = tflite.Interpreter('posenet_mobilenet_v1_075_353_481_quant_decoder.tflite'), 
                                               experimental_delegates=[tpu, posenet])
```

I guess you can refer to #86 for usage instructions. Anyhow, you can get the `posenet_decoder.so` by building it with 
`bazel build src/cpp/posenet/posenet_decoder.so` and it'll be in the `bazel-bin/*` directory.
When running, make sure to point `LD_LIBRARY_PATH=path/to/posenet_decoder.so` so that tflite can find it!

Closing for now, feel free to ask more questions if need more details :)
