### ISSUE TITLE
Couldn't establish a cellular connection with a USB modem

### ISSUE THREAD

**Issue by sagilar** [google-coral/edgetpu#128]
I've been working with the coral edge tpu for more than a year; even I updated the OS version to mendel 4. Everything was right working with the new OpenCV support and those things, but now I need to establish a connection to access Internet using a cellular modem (module U-Blox SARA R410M) and it hasn't been possible with the mendel OS. I've tried with Windows (10) and Ubuntu with the same modem and the connection work in both OSs, this means that the module works for that.
So, I tried to replicate the same of the Ubuntu case on the Coral board, using `wvdial` and `nmcli` but noone seems to work. The wvdial, which uses PPP, can access the module via AT commands and initializes the communication well, but when trying to establish the ppp internet interface it returns `the PPP daemon has died. (exit code = 4)` which means `no PPP kernel support`. When using the NetworkManager cli (nmcli), which bases on the ModemManager to set up the modem correctly, can't even find the modems attached to the USB port.
So, using a coral devboard, an item which is supposed to be employed in Internet of Things applications, but without support for cellular connectivity doesn't make sense at all.
Is there any way to solve this and achieve a cellular connection with USB modems? I appreciate your help and guidance. Thank you in advance.

**Comment by Namburger** [comment]
@sagilar 
This is most likely just due to a missing driver, I would definitely ask the vendor if there are necessary driver needed to communicate with the device

**Comment by sagilar** [comment]
The board recognizes the USB driver as "Bus - Device - ID:05c6:90b2 Qualcomm, Inc.", but I think it is not assigning a TTY port to access the modem.
I also tried upgrading the NetworkManager package to the lastest version and installing other ppp managers. Now the issue is the NM is failing to start and won't manage the networks (even downgrading the version and uninstalling the installed ppp packages). Complex situation to adapt a cellular modem to the Coral dev board.

Thanks for your help.

**Comment by Namburger** [comment]
@sagilar I have a feeling that there are just missing kernel modules needed for this device. Mendel comes with very minimal configs to work with our HW, adding necessary modules is quite easy but requires rebuilding of the kernel. Take a look at this query as an example: https://github.com/f0cal/google-coral/issues/56#issuecomment-632120325

I tried to investigate into the U-Blox SARA R410M but this is my very first time hearing about it, so it's really best to contact the U-Blox vendor to see if that is the case.

**Comment by Namburger** [comment]
FYI, regarding your queries on #133, I got my arduino to work before, but it's in my office and I don;t have access to it at this time. You should be able to interface it with:
```
$ sudo screen /dev/ttyACM0 9600
```
For FTDI drivers, AFAIK(I may be wrong here) linux will have their own driver that you need  to install: https://packages.debian.org/jessie/libftdi-dev
However, the linux driver wouldn't works for some vendor as their HW is proprietary and they would ship the drivers to talk to their HW. For instance: https://packages.debian.org/jessie/libftdi-dev
