### ISSUE TITLE
dev board use python-periphery PWM

### ISSUE THREAD

**Issue by LINYOUWEI0804** [google-coral/edgetpu#131]
Follow the sample webpage：

# Open PWM chip 0, channel 0
pwm = PWM(0, 0)

# Set frequency to 1 kHz
pwm.frequency = 1e3
# Set duty cycle to 75%
pwm.duty_cycle = 0.75

pwm.enable()

# Change duty cycle to 50%
pwm.duty_cycle = 0.50

pwm.close()

But i get this error:
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gg.py", line 7, in <module>
    pwm.frequency = 1e3
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 270, in _set_frequency
    self.period = 1.0 / frequency
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 228, in _set_period
    self.period_ns = int(period * 1e9)
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 179, in _set_period_ns
    self._write_channel_attr("period", str(period_ns))
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 118, in _write_channel_attr
    f_attr.write(value + "\n")
OSError: [Errno 22] Invalid argument

I think the frequency() function is missing

**Comment by Namburger** [comment]
Humn, I don't think `frequency` is missing, that's part of the standard python's [peripherals](https://python-periphery.readthedocs.io/en/latest/index.html) library. I just did a simple test and this is all working for me:
```
from periphery import PWM

for i in range (0, 3):
    print('testing pwm:', i)
    pwm = PWM(i, 0)
    pwm.frequency = 1e3
    pwm.duty_cycle = 0.75
    pwm.enable()
    pwm.duty_cycle = 0.5
    pwm.close()
```
Can you try running that? If it is not working, can you share some outputs:
```
$ uname -a
$ cat /etc/os-release
```

**Comment by LINYOUWEI0804** [comment]
testing pwm: 0
testing pwm: 1
testing pwm: 2
Can work normally,But after trying a few times, there will still be errors：
testing pwm: 0
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "x.py", line 6, in <module>
    pwm.frequency = 1e3
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 270, in _set_frequency
    self.period = 1.0 / frequency
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 228, in _set_period
    self.period_ns = int(period * 1e9)
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 179, in _set_period_ns
    self._write_channel_attr("period", str(period_ns))
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 118, in _write_channel_attr
    f_attr.write(value + "\n")
OSError: [Errno 22] Invalid argument

**Comment by LINYOUWEI0804** [comment]
uname -a：
Linux orange-eft 4.14.98-imx #1 SMP PREEMPT Fri Nov 8 23:28:21 UTC 2019 aarch64 GNU/Linux

cat /etc/os-release：
PRETTY_NAME="Mendel GNU/Linux 4 (Day)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.withgoogle.com/"
SUPPORT_URL="https://coral.withgoogle.com/"
BUG_REPORT_URL="https://coral.withgoogle.com/"
VERSION_CODENAME="day"

**Comment by Namburger** [comment]
@LINYOUWEI0804 humn, I added a loop and did this for 10000 times without issues. Can you try [reflashing](https://coral.ai/docs/dev-board/reflash/#update-your-dev-board-with-apt-get) the board?

**Comment by FHermisch** [comment]
Hi,
got exactly the same error today.
Seems that the "period" value got to "0" which causes internal DIV/0 errors. 
Just try to do a print on your created PWM object and it will fail with DIV/0:  
```
Traceback (most recent call last):
  File "pwmfancon.py", line 12, in <module>
    print( pwm)
  File "/home/mendel/.local/lib/python3.7/site-packages/periphery/pwm.py", line 334, in __str__
    .format(self._channel, self._chip, self.period, self.duty_cycle * 100, self.polarity, str(self.enabled))
  File "/home/mendel/.local/lib/python3.7/site-packages/periphery/pwm.py", line 241, in _get_duty_cycle
    return float(self.duty_cycle_ns) / self._period_ns
ZeroDivisionError: float division by zero
```
You can check the period value by locating the device on the mendel system and do a cat on period. E.g.:  
`cat /sys/class/pwm/pwmchip0/pwm0/period`  
I fixed it by just putting a value into period_ns (btw. what exactly does the period value do?):
```
from periphery import PWM
pwm00 = PWM(0,0)
pwm00._set_period_ns(1000000)
pwm00.close()
```
Now, my pwm code is working again.

**Comment by FHermisch** [comment]
OK, I drilled this down.  
Reproducing the error:  
```
from periphery import PWM
pwm = PWM(0, 0)
pwm.duty_cycle = 0
pwm.frequency = 5000
pwm.duty_cycle = 0.98
pwm.frequency = 5500
```  
Fixing it:  
Always change the duty cycle to 0 before changing the frequency. Otherwise you can end up with an internal 'duty_cycle_ns' value which is higher then 'period_ns' which crashes in the described way. As pwm values are written to disk (in the mendel-devices?), this situation will not fix itself but can only be solved by generating a situation with 'duty_cycle_ns < period_ns'. E.g. by setting duty_cycle to 0.
