### ISSUE TITLE
Error with Ubuntu 20.04 / Support for Python 3.8

### ISSUE THREAD

**Issue by luke-iqt** [google-coral/edgetpu#132]
I was trying to build a Docker image based on Ubuntu 20.04 and it failed. I think this is because Ubuntu uses Python 3.8 but python3-edgetpu only support up to Python 3.7. 

Is support for 3.8 planned? I rolled back to an earlier version of Ubuntu for now.

This was the error from apt-get:
 `python3-edgetpu : Depends: python3 (< 3.8) but 3.8.2-0ubuntu2 is to be installed`

**Comment by Namburger** [comment]
@luke-iqt good one, this also happened to me. I'm actually not sure where we at on this but I'm sure it is in our road map. For the time being, I suggest installing 3.7 also, everything is working for me this way. I'll follow up with you on future supports of 3.8

**Comment by Namburger** [comment]
@luke-iqt I guess this is expected but yes we will be supporting python3.8 in future releases :)

**Comment by Fonta88** [comment]
Hi all, I got the same error and installing also python 3.7 does not solve it.
Please @Namburger could explain what steps you've done to solve the issue installing 3.7?

**Comment by Namburger** [comment]
@Fonta88 can you paste the exact error that you are having?
Some tips: installing `python3.7` may still keeps your default python as 3.8, so you may need to be more explicit when using it.
For instance when installing a library via pip, instead of this:
```
$ sudo pip3 install edgetpu
```
I switched to
```
$ sudo python3 -m pip install edgetpu
```

When using the library, I'd do something like this:
```
$ python3.7 file.py
```

**Comment by Fonta88** [comment]
Hi @Namburger 

isn't possible to install edgetpu with pip, I get the following error:
No matcing distribution found for edgetpu

It seems that it must be installed with apt-get.

There's something I'm missing to use pip?

**Comment by Namburger** [comment]
@Fonta88 
Sorry, I just realized I missed typed above, you should be doing this:
```
python3.7 -m pip install https://dl.google.com/coral/edgetpu_api/edgetpu-2.14.0-py3-none-any.whl
```

**Comment by luke-iqt** [comment]
Thanks @Namburger !! Also worth nothing, looks like TFLite compiler and what-not are only on 3.7, so probably best to wait for that to move to 3.8 first.
https://www.tensorflow.org/lite/guide/python

**Comment by Fonta88** [comment]
Thanks @Namburger, it works!

**Comment by Namburger** [comment]
yes, sorry guys, we are aiming for 3.8 supports with next release!

**Comment by Namburger** [comment]
Reopening this one and will close once we starts support for python3.8

**Comment by ibrewster** [comment]
I'm just curious: what was the major change(s) (in brief) between python 3.7 and 3.8 that made this not work with 3.8? I would think that 3.8 would have added new features, maybe deprecated some things, as well as improvements/bug fixes for existing features, but not actually removed/changed anything significant over 3.7 (unless it was something that had been deprecated in an earlier release), but I haven't actually gone through the change logs to find out...

**Comment by Namburger** [comment]
Hi guys, still not released yet, but you guys can try downloading this:
https://drive.google.com/file/d/1xIB_zq_ctMVP1oyi3rPpFkPmvNvZcV1p/view?usp=sharing

@ibrewster The build rules just doesn't have a .so for python3.8, we are still inverstigating `tflite_runtime` api, but this should do for the edgetpu api in the mean time.

**Comment by ibrewster** [comment]
> Hi guys, still not released yet, but you guys can try downloading this:
> https://drive.google.com/file/d/1xIB_zq_ctMVP1oyi3rPpFkPmvNvZcV1p/view?usp=sharing
The link says "You need access" :-)

**Comment by Namburger** [comment]
whoopes, just updated

**Comment by ibrewster** [comment]
Awesome, thanks. That works perfectly!

**Comment by caijinana** [comment]
i connection the wifi but can't ping other website successfully,who can help me ,and i also get the fllowing error:
 Unsupported data type in custom op handler: 0Node number 0 (edgetpu-custom-op) failed to prepare.

**Comment by manoj7410** [comment]
I believe this has been fixed. Feel free to reopen if this issue still persists.
