### ISSUE TITLE
Coral dev board doesn't recognize ttyUSB devices

### ISSUE THREAD

**Issue by sagilar** [google-coral/edgetpu#133]
I've been trying to establish a serial connection with several USB devices using the unique USB port that the board has. The connection with Arduino boards was successful, but I've tried with 1) a cellular modem and 2) and FTDI and they are not assigned a ttyUSB port.
I realized the Arduino driver assigns and ttyACM port, which in fact, when I connect my laptop to the Coral dev board via USB (OTG port) uses the same driver as Arduino (cdc_acm).
Now, when I connect either a FTDI chip or the U-Blox cellular modem and using  the ´usb-devices´ command, I realized it lists ´Driver=(None)´. For the case of the U-Blox cellular modem, which uses 4 different drivers, all of them are ´None´.
It presents a critical situation in terms of peripheral capabilities and doesn't help too much to integrate external devices, sensors, or communication interfaces to the Coral dev board, which is absolutely unfortunate and useless.

Is there any way to install the drivers externally or definitively there is no way to work with those devices?
Thanks for your answer. I hope this limitation will be overcome.

**Comment by Namburger** [comment]
Hi, let's keep communication here: https://github.com/google-coral/edgetpu/issues/128
