### ISSUE TITLE
couldn't create tensorflowLite.dll with d855adf

### ISSUE THREAD

**Issue by Suzawa0** [google-coral/edgetpu#134]
I can't build a tensorflowlite.dll with commit d855adf, but I can with newer.

With the newer I have this problem : 
ERROR: Internal: Unsupported data type in custom op handler: -2103536448
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.

Have you one idea how it's possible to build tensorflowlite.dll (or libtensorflowlite) with tensorflow:d855adf ?
Or how I can use edgettpu with newer tensorflow ?

**Comment by Namburger** [comment]
@Suzawa0 
Sorry about that, this release of `libedgetpu` only works with `d855adf` and that commit has a build bug for `libtensorflow-lite.a` build. You'll need to apply this small patch: https://github.com/tensorflow/tensorflow/commit/72cd947f231950d7ecd1406b5a67388fef7133ea

**Comment by Namburger** [comment]
FYI In the future, you can build using any tensorflow version with this :) 
https://github.com/google-coral/libedgetpu

**Comment by Suzawa0** [comment]
Thank you for your quick reply
I would try the solution in the evening.
really eager to see your libedgeTPU
