### ISSUE TITLE
Recompile the MobileNet SSD v2 (Faces)

### ISSUE THREAD

**Issue by d-lareg** [google-coral/edgetpu#135]
Hello,
I try to compile the provided MobileNet SSD v2 (Faces) network to make co compiling possible.

While converting the .pb to .tflie file works fine, I'm facing an error when executing the edgetpu compiler.

To convert the model to .tflite I use this command:

```
tflite_convert 
--output_file=face_ssd.tflite 
--graph_def_file=tflite_graph.pb 
--inference_type=QUANTIZED_UINT8 
--input_shapes=1,320,320,3 
--input_arrays normalized_input_image_tensor 
--output_arrays TFLite_Detection_PostProcess
--mean_values 128 
--std_dev_values 128
--allow_custom_ops
--change_concat_input_ranges=false 
--allow_nudging_weights_to_use_fast_gemm_kernel=true
```

But when I try to compile the result by executing `edgetpu_compiler -s ./face_ssd.tflite` I get the error message:

```
Edge TPU Compiler version 2.1.302470888
ERROR: :160 NumOutputs(node) != 4 (1 != 4)
ERROR: Node number 121 (TFLite_Detection_PostProcess) failed to prepare.

Internal compiler error. Aborting!
```

Any idea what could be wrong?

best

gerald

**Comment by Namburger** [comment]
Hi, what tensorflow version did you use to convert the model?

**Comment by d-lareg** [comment]
Tensorflow 1.15

**Comment by Namburger** [comment]
@d-lareg ahh, just realized that you only give a single output arguments, but object detection models have 4 outputs as [documented here](https://www.tensorflow.org/lite/models/object_detection/overview#model_output).
I guess `tflite_convert` tools is a little tricky, but here is how I would convert it:
```
$ tflite_convert \ 
--output_file=face_ssd.tflite \
--graph_def_file=tflite_graph.pb \
--inference_type=QUANTIZED_UINT8 \
--input_shapes=1,320,320,3 \
--input_arrays normalized_input_image_tensor \
--output_arrays "TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3" \ 
--mean_values 128 \
--std_dev_values 128 \
--allow_custom_ops \
--change_concat_input_ranges=false \
--allow_nudging_weights_to_use_fast_gemm_kernel=true
```
