### ISSUE TITLE
ERROR: Encountered unresolved custom op: edgetpu-custom-op

### ISSUE THREAD

**Issue by Eashwar93** [google-coral/edgetpu#139]
Could anyone please tell me why I would run into issues like this?

![temp](https://user-images.githubusercontent.com/51912916/84152379-d843e080-aa64-11ea-8866-2b2eb29eb6a0.png)

This error doesn't happen only for this package but for all the packages I have created. I haven't changed any of the code or the Cmake list file.

What else could I have messed up possibly systemwide to get this error in all the edgetpu packages I have.

**Comment by Eashwar93** [comment]
Sorry my USB port wasn't working

**Comment by Namburger** [comment]
This happens to me too many times LOL
