### ISSUE TITLE
Edge tpu install does not work

### ISSUE THREAD

**Issue by DamianRivas** [google-coral/edgetpu#141]
I'm sure I know what the problem is, I can't find any new udev rules that were supposed to be installed according to this: https://coral.ai/docs/accelerator/get-started/#3-run-a-model-using-the-tensorflow-lite-api

Here is the error I get when I attempt to run the example code:
```
(facenet-training) ➜  classification git:(master) ✗ python3 classify_image.py \
--model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels models/inat_bird_labels.txt \
--input images/parrot.jpg

Traceback (most recent call last):
  File "/home/damian/.virtualenvs/facenet-training/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 161, in load_delegate
    delegate = Delegate(library, options)
  File "/home/damian/.virtualenvs/facenet-training/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 120, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_image.py", line 124, in <module>
    main()
  File "classify_image.py", line 101, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 74, in make_interpreter
    tflite.experimental.load_delegate(EDGETPU_SHARED_LIB,
  File "/home/damian/.virtualenvs/facenet-training/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 163, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

Please provide better setup instructions for the edge TPU. I've been searching all over but I can't find what the udev rule is supposed to be so I can't just create it myself and no matter what combinaion of reinstalling the package and reboooting and replugging the edge tpu, the udev rules are not automatically created as the tutorial states.

Also, please make better instructions that include the use of the full `tensorflow` library not just the `tflite_runtime`

**Comment by DamianRivas** [comment]
More context. I do have this file in my system:
```
/usr/lib/x86_64-linux-gnu/libedgetpu.so.1
```
I am on Pop! OS which is basically Ubuntu. Version 20.04.
```
➜  ~ hostnamectl
   Static hostname: galago-pro
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: b733ba9f19444339a07fbf98c5e7d0fc
           Boot ID: 78ac9965a58948b481f2f724ec0d96ea
  Operating System: Pop!_OS 20.04 LTS
            Kernel: Linux 5.4.0-7634-generic
      Architecture: x86-64
```

**Comment by DamianRivas** [comment]
Further context because I am using the full tensorflow package. I changed the import to this
```python
import tensorflow as tf
tflite = tf.lite
```

And below that I changed the `load_delegate` part
```python
def make_interpreter(model_file):
  model_file, *device = model_file.split('@')
  return tflite.Interpreter(
      model_path=model_file,
      experimental_delegates=[
          tflite.experimental.load_delegate(EDGETPU_SHARED_LIB,
                               {'device': device[0]} if device else {})
      ])
```

**Comment by DamianRivas** [comment]
Ok to troubleshoot further I ran the example on my Raspberry Pi an dit actually works there, and it doesn't appear to have the udev rule installed...
```
(cv) pi@raspberrypi:~/projects/coral/tflite/python/examples/classification $ python3 classify_image.py --model models/mo
bilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
123.6ms
10.0ms
10.0ms
10.0ms
10.0ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.77734
```
```
(cv) pi@raspberrypi:~/projects/coral/tflite/python/examples/classification $ ls -la /etc/udev/rules.d/
total 12
drwxr-xr-x 2 root root 4096 Jun 10 15:58 .
drwxr-xr-x 4 root root 4096 May 16 10:28 ..
-rw-r--r-- 1 root root 1367 May 13 22:13 99-com.rules
```

**Comment by Namburger** [comment]
@DamianRivas 
Hey sorry for the late response, we're on different timezone. Anyhow I guess all the debugging may have caused lots of confusions. But here are some clarification:

> Also, please make better instructions that include the use of the full tensorflow library not just the tflite_runtime

We don't document it because that will no longer works, unfortunately. The tflite API were built on different commits than `libedgetpu.so` and `tflite_runtime` is required. This would be exactly what you should follows: https://coral.ai/docs/edgetpu/tflite-python/#load-tensorflow-lite-and-run-an-inference

For more context on `ValueError: Failed to load delegate from libedgetpu.so.1`, that usually happens due to your application not able to access the TPU. We actually debated on whether or not to add this to our docs, but this is more of standard linux group situation, and most distributions already have this. Anyhow, something like this should works:
```
$ sudo usermod -aG plugdev $USER
$ sudo reboot now
```
