### ISSUE TITLE
USB Accelerator: Any way to use in non-privileged containers?

### ISSUE THREAD

**Issue by dmm** [google-coral/edgetpu#143]
Is there a way to use the USB accelerator in a docker container without the "--privileged" flag? 

I understand the desire to provide a quick and easy way for people to get started but privileged containers undermine most of the isolation provided by docker. 

Even a convoluted or complicated workaround to allow non-privileged would be useful.

A few resources describing the downsides of privileged containers:

https://blog.trendmicro.com/trendlabs-security-intelligence/why-running-a-privileged-container-in-docker-is-a-bad-idea/

https://medium.com/better-programming/docker-tips-mind-the-privileged-flag-d6e2ae71bdb4

Thanks!

**Comment by Namburger** [comment]
@dmm 
Thanks for reaching out.  
Please keep in mind that VMs and docker isn't officially supported by us but I'll definitely give some suggestions.
This issue probably doesn't have anything to do with the USB Accelerator at all. It is more of a docker usage, I haven't tested this, but something as simple as this should do:
```
docker run -it --device=/dev/ttyUSB<path-to-coral>  <image-name> /bin/bash
```

**Comment by Namburger** [comment]
FYI, I just tried it and it works!

Cheers

**Comment by dmm** [comment]
Thanks for the quick reply! It works great.

**Comment by ykhorzon** [comment]
@Namburger 

I tried the similar `docker run -it --device=/dev/apex_0:/dev/apex_0 /bin/bash` for Coral mini pcie device but it does not work.

Any hint? thanks

**Comment by manoj7410** [comment]
@ykhorzon Is your Coral PCIe device visible to the host machine ?
