### ISSUE TITLE
ERROR: Didn't find op for builtin opcode 'TRANSPOSE_CONV' version '3'

### ISSUE THREAD

**Issue by fjp** [google-coral/edgetpu#147]
Hi, I am trying to compile a model that uses `tensorflow.keras.layers.Conv2DTranspos` and get the following error:

```console
$ edgetpu_compiler model_quant.tflite
Edge TPU Compiler version 2.1.302470888
ERROR: Didn't find op for builtin opcode 'TRANSPOSE_CONV' version '3'

ERROR: Registration failed.

Invalid model: model_quant.tflite
Model could not be parsed
```

I followed the [Retrain a classification model using post-training quantization](https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb) notebook. I've installed tf-nightly:

```console
$ pip list | grep tf
tf-estimator-nightly           2.3.0.dev2020061401
tf-nightly                     2.3.0.dev20200614
tflite-runtime                 2.1.0.post1
```

Create a TensorFlow Lite model with [`TFLiteConverter`](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter). 
The following creates a basic (un-quantized) TensorFlow Lite model:

```python
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)
tflite_model = converter.convert()
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)
```

Convert the model again with post-training quantization:

```python
dataset_dir = "path/to/dataset"

# A generator that provides a representative dataset
def representative_data_gen():
    dataset_list = tf.data.Dataset.list_files(dataset_dir + '*.jpg')
    dataset_list = dataset_list.take(110)
    for i in range(100):
        image = next(iter(dataset_list))
        image = tf.io.read_file(image)
        image = tf.io.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [IMAGE_SIZE, IMAGE_SIZE])
        image = tf.cast(image / 255., tf.float32)
        image = tf.expand_dims(image, 0)
        yield [image]

# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.int8]
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# These set the input and output tensors to uint8 (added in r2.3)
converter.inference_input_type = tf.uint8    # also tried with tf.int8
converter.inference_output_type = tf.uint8 # also tried with tf.int8
# And this sets the representative dataset so we can quantize the activations
converter.representative_dataset = representative_data_gen
tflite_model = converter.convert()

with open('model_quant.tflite', 'wb') as f:
    f.write(tflite_model)
```

Finally tried to compile the `model_quant.tflite` with the edgetpu-compiler (version 2.1.302470888) as mentioned above.

According to the documentation `Transpose_CONV` should be one of the supported [operations](https://coral.ai/docs/edgetpu/models-intro/#supported-operations).

Any idea how to fix this error? Thank you.

**Comment by Namburger** [comment]
@fjp Thanks for reporting this issue.

FYI We've been getting a few of these: https://stackoverflow.com/questions/62321919/edge-tpu-compiler-error-didnt-find-op-for-builtin-opcode-resize-nearest-neigh

My best guess is that the newer tensorflow version has changed the `transpose_conv` to something the compiler hasn't supported. Most likely can be workaround by not using the `tf-nightly` and downgrade to an older version of tensorflow. I'll try to reproduce this issue today and see and check with our team.

**Comment by Namburger** [comment]
@fjp Could you clarify what you've changed from the retrain script?
I'm guessing that you changed `tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'),` to `tf.keras.layers.Conv2DTranspose`?

**Comment by fjp** [comment]
@Namburger thanks looking into this and the provided link. I've also tried using tensorflow 2.2 which results in the following error:

```console
$ edgetpu_compiler model_quant.tflite
Edge TPU Compiler version 2.1.302470888

Internal compiler error. Aborting!
```

I am not using the model from the retrain script but my own. It contains:

```python
from tensorflow.keras.layers import Conv2DTranspose
from tensorflow.keras.layers import LeakyReLU

...

x = Conv2DTranspose(x, (3, 3), strides=2, padding="same")(x)
x = LeakyReLU(alpha=0.2)(x)

...
```

I guess the problem is that `LeakyReLU` is not supported? However, the error mentions: `TRANSPOSE_CONV` is not supported (when using tf-nightly 2.3). 

I'll try to use ReLU instead of LeakyReLU and test with both tensorflow versions 2.2 and 2.3 (nightly).

**Comment by Namburger** [comment]
@fjp I have an updates:
The sweet spot is with `tensorflow2.2` for our released compiler right now.  Hopefully we can get a newer release soon so that it'll be more compatible with the latest version of tensorflow. FYI, you may need to uninstall `tf-nightly` completely and install tf2.2 :/
```
 » python3 -m pip install tensorflow==2.2
 » python3 -c 'print(__import__("tensorflow").__version__)'
2.2.0
```

Here is an example for making this model:
```
import tensorflow as tf
import numpy as np

# Create the base model from the pre-trained MobileNet V2
base_model = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3),
                                              include_top=False,
                                              weights='imagenet')

base_model.trainable = False
model = tf.keras.Sequential([
  base_model,
  tf.keras.layers.Conv2DTranspose(filters=32, kernel_size=3, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.GlobalAveragePooling2D(),
  tf.keras.layers.Dense(units=5, activation='softmax')
])
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()
print('Number of trainable weights = {}'.format(len(model.trainable_weights)))

converter = tf.lite.TFLiteConverter.from_keras_model(model)
# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_types = [tf.int8]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

# NOTE THAT THESE 2 OPTIONS ONLY AVAILABLE IN TF2.3 AND UP :/
# converter.inference_input_type = tf.uint8
# converter.inference_output_type = tf.uint8

def representative_data_gen():
   for _ in range(100):
       yield [np.random.random((1, 224, 224, 3)).astype(np.float32)]
converter.representative_dataset = representative_data_gen
tflite_model = converter.convert()

with open('model_quant.tflite', 'wb') as f:
    f.write(tflite_model)
```

and compile:
```
edgetpu_compiler -s model_quant.tflite                                       vunam@penguin
Edge TPU Compiler version 2.1.302470888

Model compiled successfully in 545 ms.

Input model: model_quant.tflite
Input size: 3.09MiB
Output model: model_quant_edgetpu.tflite
Output size: 3.11MiB
On-chip memory used for caching model parameters: 3.33MiB
On-chip memory remaining for caching model parameters: 4.39MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 74
Operation log: model_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 72
Number of operations that will run on CPU: 2

Operator                       Count      Status

DEQUANTIZE                     1          Operation is working on an unsupported data type
MEAN                           1          Mapped to Edge TPU
FULLY_CONNECTED                1          Mapped to Edge TPU
SOFTMAX                        1          Mapped to Edge TPU
ADD                            10         Mapped to Edge TPU
PAD                            5          Mapped to Edge TPU
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONV_2D                        35         Mapped to Edge TPU
TRANSPOSE_CONV                 1          Mapped to Edge TPU
RELU                           1          Mapped to Edge TPU
DEPTHWISE_CONV_2D              17         Mapped to Edge TPU
```

Hope this helps :)

**Comment by Namburger** [comment]
@fjp FYI, `LeakyRely` will fails, although I guess the compiler never got to it since it failed on `Conv2DTranspose` first :)

**Comment by fjp** [comment]
@Namburger when using tensorflow 2.2.0 and even keeping the options `converter.inference_input_type` and `converter.inference_output_type` (I guess they just have no effect in 2.2?) it is possible to compile the model (sometimes):

```console
Edge TPU Compiler version 2.1.302470888

Model compiled successfully in 100 ms.

Input model: model_quant.tflite
Input size: 5.59MiB
Output model: model_quant_edgetpu.tflite
Output size: 5.62MiB
On-chip memory used for caching model parameters: 3.00KiB
On-chip memory remaining for caching model parameters: 8.03MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 27
Operation log: model_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 1
Number of operations that will run on CPU: 26
See the operation log file for individual operation details.
```

According to this output the model currently isn't really optimized for the Edge TPU. Probably because of the unused converter options (`converter.inference_input_type` and `converter.inference_output_type`) and for this compilation run I still used `LeakyReLU` instead of just `ReLU`. 

And as mentioned, the model compiles only sometimes. Re-running the compilation sometime fails: 

```console
Edge TPU Compiler version 2.1.302470888

Internal compiler error. Aborting!
```

Is it possible to inspect why this is happening?

**Comment by Namburger** [comment]
@fjp Would you give `PRELU` a go instead, I'm not sure if `LeakyRelu` is  in our roadmap at this time

**Comment by fjp** [comment]
@Namburger yes I'll try using `PReLU`. Any ideas when it will be supported? Or is it already in tf 2.3? With tf 2.2 I am getting: `RuntimeError: Quantization not yet supported for op: PRELU`. 

And here is the current compiler output results using `ReLU`:

```console
$ edgetpu_compiler -s model_relu_quant.tflite
Edge TPU Compiler version 2.1.302470888

Model compiled successfully in 917 ms.

Input model: model_relu_quant.tflite
Input size: 5.58MiB
Output model: model_relu_quant_edgetpu.tflite
Output size: 5.63MiB
On-chip memory used for caching model parameters: 21.75KiB
On-chip memory remaining for caching model parameters: 7.45MiB
Off-chip memory used for streaming uncached model parameters: 3.00KiB
Number of Edge TPU subgraphs: 1
Total number of operations: 23
Operation log: model_relu_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 6
Number of operations that will run on CPU: 17

Operator                       Count      Status

RESHAPE                        2          Operation is otherwise supported, but not mapped due to some unspecified limitation
DEQUANTIZE                     1          Operation is working on an unsupported data type
FULLY_CONNECTED                2          More than one subgraph is not supported
LOGISTIC                       1          More than one subgraph is not supported
ADD                            2          Mapped to Edge TPU
ADD                            5          More than one subgraph is not supported
MUL                            2          Mapped to Edge TPU
MUL                            2          More than one subgraph is not supported
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
TRANSPOSE_CONV                 3          More than one subgraph is not supported
CONV_2D                        2          Mapped to Edge TPU
```

Still a lot of `More than one subgraph is not supported`, `Operation is otherwise supported, but not mapped due to some unspecified limitation` and `Operation is working on an unsupported data type`. Any hints on how to get more operations run on the Edge TPU?

**Comment by Namburger** [comment]
@fjp I see, is it okay to submit your model here for me to take a look?

**Comment by fjp** [comment]
Sure, here is the [link](https://drive.google.com/drive/folders/1CZwwfUV0uI3bGqi2b5NAUw5RlUoA_ZLV?usp=sharing) to the SavedModel.

**Comment by Namburger** [comment]
Sorry about that, I mean the tflite model, I wanted to run it through our internal compiler(with extra logs) to see where the compiler breaks the model into different subgraph and find out what can be done on the user side

**Comment by fjp** [comment]
Sorry for sharing the wrong model. I've uploaded the (quantized) tflite models (LeakyReLU, ReLU, PReLU) including the compiled ones. You find them at the same [link](https://drive.google.com/drive/folders/1CZwwfUV0uI3bGqi2b5NAUw5RlUoA_ZLV?usp=sharing). Thank you for taking the time.

**Comment by Namburger** [comment]
@fjp Okay, took a look, I found a bug in our compiler and it is quite messy now...
1) The relu model, the compiler broke off at the very first `reshape` op, which I believe due to large tensor size. I wanted to enable some internal features to get more logs and found a bug :( I'm guessing you are still using compiler version 2.0.291256449? Even the newer released (2.1.302470888) did not work. I'll file an internal bug to get this fix hopefully before we release the next version. 
2) LeakyRelu model is expected since it is not supported yet
3) For Prelu, I suspect you should be able to do full quantization with tf-nightly?

Apologies for all these issues

**Comment by fjp** [comment]
Thank you @Namburger for the investigation.

> 1. The relu model, the compiler broke off at the very first `reshape` op, which I believe due to large tensor size. 

I am also wondering why there are two Reshape ops. To build the model I use just one `x = Reshape((volumeSize[1], volumeSize[2], volumeSize[3]))(x)` with an input tensor of shape `TensorShape([None, 160000])` and output of `TensorShape([None, 50, 50, 64])`. Do you know if these tensor sizes are too large and what would be a suitable size? 

> I wanted to enable some internal features to get more logs and found a bug :( I'm guessing you are still using compiler version 2.0.291256449? Even the newer released (2.1.302470888) did not work. I'll file an internal bug to get this fix hopefully before we release the next version.

Thanks reporting this. As far as I can tell from the compiler output I am using the latest release (Edge TPU Compiler version 2.1.302470888). 

> 2. LeakyRelu model is expected since it is not supported yet

Any updates if this will be supported in the future?

> 3. For Prelu, I suspect you should be able to do full quantization with tf-nightly?

I'll give it a try, although the reason I opened this issue was because of tf-nighlty (2.3). Here is the error mentioned in the first post:

```console
$ edgetpu_compiler model_quant.tflite
Edge TPU Compiler version 2.1.302470888
ERROR: Didn't find op for builtin opcode 'TRANSPOSE_CONV' version '3'

ERROR: Registration failed.

Invalid model: model_quant.tflite
Model could not be parsed
```

However, for this compilation run I used LeakyReLU. I'll try PreLU with tf-nighly.

Thanks again for your help and updates.

**Comment by JanderHungrige** [comment]
Hi, as it seems up to tf version 2.5.0 the issue is still the same. 
Just to clarify, is the issue with tf changing the TransConv and the tflite converter not being able to handle it, correct? 

@Namburger : Is there an update on solving the TransConv issue in an upcoming tflite version?

thanks

**Comment by manoj7410** [comment]
@fjp Can you try to compile using the 16.0 version of the compiler ?

**Comment by hjonnala** [comment]
Fell free to reopen if issue still exist with compiler 16.0. Thanks!
