### ISSUE TITLE
python-periphery Control step-by-step motor problems

### ISSUE THREAD

**Issue by LINYOUWEI0804** [google-coral/edgetpu#149]
My expected function is to control the stepper motor to move step by step, the motor stops after 15 steps,but the result of the test is that the motor cannot stop.
I use the following code:

from periphery import PWM,GPIO
import time
pwm = PWM(0, 0)
def duty(angle):
    duty_cycle = ((0.05*50)+(0.19*50*angle/180))/100 #frequency=50
    return duty_cycle
for angle in range(0,181,15):
    dc = duty(angle)
    pwm.duty_cycle = dc
    print('{},{}'.format(angle , dc))
    time.sleep(1)
pwm.close()
print('end')

**Comment by Namburger** [comment]
@LINYOUWEI0804 hey!

Could you reformat the code? It's very hard to tell what exactly it is doing without spacing especially in python.

FYI: This is a better question for [python-[eriphery](https://github.com/vsergeev/python-periphery/issues) as we didn't write that library!

Closing for now, but I can continue to give suggestions on this threads.

**Comment by LINYOUWEI0804** [comment]
The frequency parameter can adjust the speed of the stepper motor, so which parameter can adjust the number of pulses

**Comment by LINYOUWEI0804** [comment]
Encountered the same error：OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "x1.py", line 12, in <module>
    pwm.frequency = b+i
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 270, in _set_frequency
    self.period = 1.0 / frequency
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 228, in _set_period
    self.period_ns = int(period * 1e9)
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 179, in _set_period_ns
    self._write_channel_attr("period", str(period_ns))
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 118, in _write_channel_attr
    f_attr.write(value + "\n")
OSError: [Errno 22] Invalid argument

I run this code :
from periphery import PWM
pwm = PWM(0, 0)
b=1
for i in range(0,100,2):
    pwm.frequency = b+i
    pwm.duty_cycle = 0.75
    pwm.enable()
    pwm.duty_cycle = 0.50
pwm.disable()
pwm.close()

Line 4 of the code 「 for i in range(0,100,2):」  This error occurs as long as the third parameter is not 1,If it is 1, you can make the motor rotate normally.Is this problem caused by the frequency suddenly being too large?

**Comment by Namburger** [comment]
Does this problem still occurs if you keep the frequency at constant?

**Comment by LINYOUWEI0804** [comment]
At first, if the value is too large, an error will occur.For example, give 200, but give 50 without problems,If you want to give a value of 200, you can only start from 50, and then the program value is changed to 60, 70 and slowly change to 200 before there will be no errors.
