### ISSUE TITLE
ERROR: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'

### ISSUE THREAD

**Issue by JakubGal** [google-coral/edgetpu#152]
Hello,
i am trying to convert tiny yolo v3. First I converted the model to .tflite using tensorflow 2.3 (nightly) and then I tried to convert using edgetpu_compiler so I could run it on Coral USB Accelerator but I got this error:

Edge TPU Compiler version 2.1.302470888
ERROR: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'

ERROR: Registration failed.

Invalid model: yolo_rcj.tflite
Model could not be parsed

Then I tried to convert the model using the older version of tensorflow(2.2) but I got this error:

<unknown>:0: error: failed while converting: 'main'
Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag): ResizeNearestNeighbor

But according to this, ResizeNearestNeighbor should be supported:
https://coral.ai/docs/edgetpu/models-intro/#supported-operations

I also checked the model with Netron and I thought everything looked fine. 
Here is the model:
https://drive.google.com/file/d/1p2x0mXoC-V2j4PMZi61QyP476Xp8hw1t/view?usp=sharing

I also found this repo on github so it should be possible but I don't know where I could have made a mistake. I also tried older versions of edgetpu_compiler but the same problem(In repo is used 2.0.267685300).Any ideas?

https://github.com/guichristmann/edge-tpu-tiny-yolo

**Comment by Namburger** [comment]
Hey, thanks for submitting the issue, could you try downgrading to tensorflow2.2?
Check out this answer: https://github.com/google-coral/edgetpu/issues/147#issuecomment-644246990

**Comment by JakubGal** [comment]
Thank you for the quick reply.
There is .h5:
https://drive.google.com/file/d/1iYGntXy-uAiIwxhlfOQEopqNacCPM5_P/view?usp=sharing




https://drive.google.com/file/d/1iYGntXy-uAiIwxhlfOQEopqNacCPM5_P/view?usp=sharing

**Comment by Namburger** [comment]
@JakubGal Thanks for submitting the model, I got it to converts with `tf2.1`but preproduced this issue with `tf2.2`...
```
import tensorflow as tf
import numpy as np
import sys

if len(sys.argv) < 2:
    print(f"Usage: %s model.h5" % (sys.argv[0]))
    sys.exit(1)

model = tf.keras.models.load_model(sys.argv[1])
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
def representative_dataset_gen():
  for _ in range(250):
    data = np.random.uniform(0.0, 1.0, size=(1, 416, 416, 3)).astype(np.float32)
    yield [data]
converter.representative_dataset = representative_dataset_gen
tflite_model = converter.convert()

with open('out.tflite', "wb") as f:
    f.write(tflite_model)
```

This will definitely be an issue going on ward, I suggest submitting an issue with [tensorflow team](https://github.com/tensorflow/tensorflow/issues) also, specifically on the tflite conversion.

I'll try to get more communication internally regarding the compiler on the `'RESIZE_NEAREST_NEIGHBOR' version '3'` issue with my team and will give you some updates.

**Comment by daynauth** [comment]
Have there been updates on this issue?

I'm getting the errors with both tf-nightly and tf 2.2.0.

**Comment by JakubGal** [comment]
@Namburger Thank you very much for your help and I apologize for the late reply.I really appreciate you helping me.
@daynauth  Use Tensorflow 2.1 to convert to .tflite and then everything should work.

**Comment by Namburger** [comment]
@JakubGal  Awesome, thanks for the update!
@daynauth did you get to try 2.1? 

FYI, we are expecting a compiler release this month which shall eliminate this issue

**Comment by daynauth** [comment]
tf 2.1 works in my case along with changing the converter to 
`converter =tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(file)`

**Comment by Namburger** [comment]
Awesome, thanks all for confirming, I'll keep issue open until new release confirm this fixes for newer tensorflow version also

**Comment by JakubGal** [comment]
Link to the problem I opened on tensorflow:
https://github.com/tensorflow/tensorflow/issues/41085

**Comment by Namburger** [comment]
@JakubGal @daynauth 
We haven't announced it yet, but you can now grab the new compiler via apt get
```
sudo apt install edgetpu-compiler
```
version should be `14.1.317412892`

Now you can upgrade to the newest tensorflow :)

**Comment by Namburger** [comment]
To clarify, I mean the original compiler issue `ERROR: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'` 

I'm not exactly sure about the regression between 2.1 and 2.2, so I'd still keep https://github.com/tensorflow/tensorflow/issues/41085 open

**Comment by rajansaini691** [comment]
Hello again! My model quantizes and compiles, but it has inference times of ~1.5s. According to the logs, the `RESIZE_NEAREST_NEIGHBOR` op is not mapped to the edge device, which may account for the slowdown. I am also using the newest compiler version with tensorflow 2.3. What should I do to make the mapping successful and improve performance?

[model](https://github.com/rajansaini691/retinanet-model-tflite/blob/master/tiny_yolo.tflite?raw=true)
[compiled model](https://github.com/rajansaini691/retinanet-model-tflite/blob/master/tiny_yolo_edgetpu.tflite?raw=true)
[logs](https://raw.githubusercontent.com/rajansaini691/retinanet-model-tflite/master/tiny_yolo_edgetpu.log)

**Comment by yangohuang** [comment]
tf2.4.2 （maybe >2.3.0 is ok）have a try
