### ISSUE TITLE
[Question] Power draw at standard clock ?

### ISSUE THREAD

**Issue by KyungWonPark** [google-coral/edgetpu#154]
Hello

I'd like to use TWO edgetpu s on my Raspberry Pi 4,
which can output 1.2 A of current in total, through its USB ports

But I can't find how much current edgetpu uses at maximum, when it's running at standard
clock frequency

I wonder would 1.2 A be enough to feed two edgetpus
Also for USB is serial, they will share USB 3.0 bandwidth
so I'd like to hear your opinion on using two edgetpus on raspberry pi

Thank you

**Comment by lilanxiao** [comment]
According to the [official documentation](https://coral.ai/docs/accelerator/datasheet/#power-specifications):

> The USB Accelerator is powered by 5 V from the USB interface through on-board power management chip (PMIC).
> 
> The device should be connected to a host computer with a USB cable that provides at least 500 mA at 5 V. Please note that when the device runs at maximum speed, it can draw a peak current of 900 mA.

**Comment by KyungWonPark** [comment]
> According to the [official documentation](https://coral.ai/docs/accelerator/datasheet/#power-specifications):
> 
> > The USB Accelerator is powered by 5 V from the USB interface through on-board power management chip (PMIC).
> > The device should be connected to a host computer with a USB cable that provides at least 500 mA at 5 V. Please note that when the device runs at maximum speed, it can draw a peak current of 900 mA.

Thank you very much!

**Comment by Namburger** [comment]
1.2A is not enough for both accelerator, unfortunately, I suggest a powered usb hub!
