### ISSUE TITLE
[Question] Using multiple edgetpu s ?

### ISSUE THREAD

**Issue by KyungWonPark** [google-coral/edgetpu#155]
Hello

Is there any limit in number of edgetpus I can use in one device ?

Also I'd like to know what(how much) data come and go while
TFLite is running on edgetpu
I guess after loading the model, if model size is small enough to be fitted in edgetpu,
only input -> .... -> output would come and go between host and edgetpu
for example, 300 * 300 * 4 bytes (image data)

If my model is composed of multiple layers,
and one layer runs on edgetpu 0, output of that layer go to edgetpu 1, and runs there,
How big is the overhead to move data between devices (latency...)? Compared to running it on 
imaginary coral accelerator that has 16 MB of memory

**Comment by Namburger** [comment]
@KyungWonPark 
> only input -> .... -> output would come and go between host and edgetpu

That's correct, input, model params, and outputs will be loaded on the tpu.

> Is there any limit in number of edgetpus I can use in one device ?

On an API standpoint, there are no limitation for the users on how many tpus can be used. But at some point it may not make sense, for instance, if your host only have 2 cores cpu, then having 8 tpus maybe a bit much for the 2 cores to process.

**Comment by KyungWonPark** [comment]
> @KyungWonPark
> 
> > only input -> .... -> output would come and go between host and edgetpu
> 
> That's correct, input, model params, and outputs will be loaded on the tpu.
> 
> > Is there any limit in number of edgetpus I can use in one device ?
> 
> On an API standpoint, there are no limitation for the users on how many tpus can be used. But at some point it may not make sense, for instance, if your host only have 2 cores cpu, then having 8 tpus maybe a bit much for the 2 cores to process.

Hmm... 
What about "input -> edgetpu 0 -> edgetpu 1 -> ... edgetpu n -> output" case?
Isn't only thing that host need to do is move data from one edgetpu to another?
I thought edgetpu would run on it's after launching it, just like CUDA

**Comment by Namburger** [comment]
@KyungWonPark I see, do you mean to process the outputs of edgetpu[0] on the edgetpu[1]?
For instance:
`input -> edgetpu[0] -> output[0] -> edgetpu[1] -> output[1] -> ...` 
that would requires transferring the outputs back to cpu each time at the moment and that's limited to bus speed of the host system (for instance usb vs pcie). 
I'm not sure if there is a way to beat this at the moment as all tpus are going to be on a separate device :/

**Comment by KyungWonPark** [comment]
> @KyungWonPark I see, do you mean to process the outputs of edgetpu[0] on the edgetpu[1]?
> For instance:
> `input -> edgetpu[0] -> output[0] -> edgetpu[1] -> output[1] -> ...`
> that would requires transferring the outputs back to cpu each time at the moment and that's limited to bus speed of the host system (for instance usb vs pcie).
> I'm not sure if there is a way to beat this at the moment as all tpus are going to be on a separate device :/

I've done some math here
Let's say I want to pipeline edgetpu s in serial manner, 
so each edgetpu handles one "segment" of entire model

- USB 3.0 has 5 Gbps bandwidth which is ~ 640 MB/s
- For each edgetpu, input should be supplied and output should be retrieved by host

With 8 edgetpus, 

(600 * 600 * 4 byte image) * (24 frames per second) * (2 * 8 data copy count)
is about 530 MB

Does that mean pipeline of 8 edgetpus can process 600 by 600 image in 24 fps,
in single USB 3.0 bus without bandwidth problem?

Also about latency, I heard that edgetpu is some sort of systolic array hardware
Then is it safe to guess that time edgetpu takes for inferencing is kinda constant
regardless of task it handles, if processing data size is same?

Thank you

**Comment by Namburger** [comment]
@KyungWonPark 
The math and the thinking looks correct, although keep in mind that 640 MB/s is the theoretical limit of USB3.0, in practice, I don't any HW actually achieved that. We also don't have that type of numbers off hand for the edgetpu
It is also good to mention that the rpi4 comes with 2 USB2.0 and 2 USB3.0, so that would also make some difference. 
Also, I would make sure that all the ops on your model can be passed to the edgetpu, otherwise you'll have some part on the tpu and some part in the cpu, that would not be so good!
