### ISSUE TITLE
LSTM support

### ISSUE THREAD

**Issue by ankandrew** [google-coral/edgetpu#156]
Are there plans to support LSTM or GRU on the edge TPU?

**Comment by Namburger** [comment]
@ankandrew Thanks for reaching out!
Yes, we are planning on this and started experimenting with it. 
FYI, tflite conversion for LSTM model is quite new for the tensorflow team and currently quantization of the model is still not available.
You can check here for the tflite roadmap: https://www.tensorflow.org/lite/guide/roadmap

**Comment by DiscretePython** [comment]
@Namburger I'm wondering if there are any updates on this given that some time has passed.
It seems that tflite still doesn't support full integer quantization for LSTMs but has added float16 support, which I realize doesn't help for running on an edge tpu... but maybe some progress has still been made?

**Comment by OctaM** [comment]
Hello, I have the same problem. Is there any timeline that i can follow? Or just update tensorflow from time to time and try to convert and see if it works?

**Comment by manoj7410** [comment]
The latest compiler release supports LSTM(Unidirectional only). Please check supported operations at https://coral.ai/docs/edgetpu/models-intro/#supported-operations

**Comment by DiscretePython** [comment]
Thank you for the update! This is fantastic news. I have an CRNN model I've now been able to compile and run on the Coral Dev Board.

Unfortunately, I'm running into a runtime error when trying invoke the same model on the USB TPU connected to a Raspberry PI 4.
`RuntimeError: Failed to execute request. Executable 'model' must have fully deterministic DMA hints when DMA descriptors from device are disabled.Node number 1 (EdgeTpuDelegateForCustomOp) failed to invoke.`

Is anyone else having this problem?

**Comment by manoj7410** [comment]
@DiscretePython Did you try on any other machine except this RPI4 ?

**Comment by DiscretePython** [comment]
Yes, I tried connecting the USB Accelerator to a laptop running x86_64 Ubuntu 20.04 and get the same runtime error.

I've had success running the model on a Coral dev board and a Gateworks SBC with a mini PCIe Accelerator so I'm wondering if it may be a problem related to the USB Accelerator.

**Comment by manoj7410** [comment]
@DiscretePython Are you able to run any other model with this USB Accelerator ?

**Comment by DiscretePython** [comment]
Yeah, I've never had any other issues running (non-LSTM) models on this particular USB Accelerator. I just ran [this example](https://github.com/google-coral/examples-camera) from the coral website today and it's working fine. This probably doesn't rule out my Accelerator as the problem but makes it seem unlikely.

To make sure it isn't a problem with my particular model, I created a very simple LSTM model (input, LSTM, output) and get the same error. I've shared it [here](https://drive.google.com/drive/folders/1AibsF8xRYnu3ec40ZvK96YIvWTWWRSPG?usp=sharing) along with a script to make an inference in case that helps. If this isn't an issue for anyone else with other LSTM models on the USB Accelerator then I'm wondering if it may be a problem with my tflite conversion process.

**Comment by hjonnala** [comment]
For LSTM model with USB accelerator to resolve:
`
RuntimeError: Failed to execute request. Executable 'model' must have fully deterministic DMA hints when DMA descriptors from device are disabled.Node number 1 (EdgeTpuDelegateForCustomOp) failed to invoke`.

try the command below:

`USB_ENABLE_BULK_DESCRIPTORS_FROM_DEVICE=1 python3 run_lstm.py $PATH/weather_forecast_quant.tflite`

**Comment by johannesheid** [comment]
@hjonnala Hey, has anything happened since last year that LSTM-Model can run without the `USB_ENABLE_BULK_DESCRIPTORS_FROM_DEVICE=1` command on the Coral USB accelerator + for example RaspberryPi4?

In addition, I would be very interested to know why this command is/was needed, what exactly it does and why it results in this large latency. My model is twice as fast on the CPU (RaspPi4) compared to using the USB accelerator with the `USB_ENABLE_...` command.

**Comment by MG-EuS** [comment]
I still get the error message `RuntimeError: Failed to execute request. Executable 'model' must have fully deterministic DMA hints when DMA descriptors from device are disabled.Node number 3 (EdgeTpuDelegateForCustomOp) failed to invoke.` when I try to run a simple model with an lstm layer using the coral USB accelerator.
Inference latency is crucial for us, so we can't use `USB_ENABLE_BULK_DESCRIPTORS_FROM_DEVICE=1` if it introduces additional latency. Please comment on this.
