### ISSUE TITLE
Internal compiler error. Aborting!

### ISSUE THREAD

**Issue by GiusBen** [google-coral/edgetpu#157]
Hi,
I'm trying to compile a fully quantized yolov3-tiny tflite model (leaky relu's dropped in favor of standard relu's, since they're not supported yet).

Unfortunately I get the following output:

```
Edge TPU Compiler version 2.1.302470888

Internal compiler error. Aborting!
```

I was able to compile fully quantized models identical to this one with the sole difference given by the input size ([608, 608, 3] and [416, 416, 3] work just fine, input is [1024, 1024, 3] in this case).
I can see from other threads that there's an ongoing effort to solve this bug. Any updates?
Thanks for your attention.

**Comment by Namburger** [comment]
Hi @GiusBen! 
Apologies for the generic error message, we are working to improve the logs, but "Internal compiler error" could means a few things, unfortunately. Sometimes it's a bug and at time it's with the user's model.
In this case, I believe ` [1024, 1024, 3]` for yolov3 may just have been a little too large for the edgetpu's RAM, if you would like to attach the model here, I could take a look.
