### ISSUE TITLE
ModuleNotFoundError: No module named 'edgetpu'

### ISSUE THREAD

**Issue by alitillawi** [google-coral/edgetpu#158]
* Doc trying to follow: https://coral.ai/docs/accelerator/get-started/#1c-on-windows
* Host OS: Windows 10
* Python3 version: 3.6.5

# What I ran:
-Pre-configuration and runtime for the edge TPU on windows were made
-Code for facial recognition via a TFlite trained model.

# What happened
    from edgetpu.classification.engine import ClassificationEngine
ModuleNotFoundError: No module named 'edgetpu'

**Comment by manoj7410** [comment]
Are you running the example by following the instructions given at : https://coral.ai/docs/accelerator/get-started/#3-run-a-model-using-the-tensorflow-lite-api ?

**Comment by Namburger** [comment]
@alitillawi 
Hey! The example on the [getting started page ](https://coral.ai/docs/accelerator/get-started/#3-run-a-model-using-the-tensorflow-lite-api) should be using the tflite API, which is from [this repo](https://github.com/google-coral/tflite/tree/master/python/examples/classification) and shouldn't need the `edgetpu` package.

I supposed you are running [this demo](https://github.com/google-coral/edgetpu/blob/master/examples/classify_image.py) instead? In that case, you'd need to install thee `edgetpu` module, from [this page](https://coral.ai/software#edgetpu-python-api) and it is most likely this package that you'll need:

https://dl.google.com/coral/edgetpu_api/edgetpu-2.14.0-cp36-cp36m-win_amd64.whl

**Comment by alitillawi** [comment]
So I believe the main issue was that I had 2 python environments. I have removed one of them and repeated the whole get started process again also with the suggested model using git bash.

on the one side I am still getting on my program:

    from edgetpu.classification.engine import ClassificationEngine
ModuleNotFoundError: No module named 'edgetpu'


and on the example program:
$ python classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 100, in main
    interpreter.allocate_tensors()
  File "C:\Program Files\Python36\lib\site-packages\tflite_runtime\interpreter.py", line 243, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "C:\Program Files\Python36\lib\site-packages\tflite_runtime\tensorflow_wrap_interpreter_wrapper.py", line 110, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.

**Comment by Namburger** [comment]
@alitillawi Awesome, now it seems like we have 2 problems :)

* `ModuleNotFoundError: No module named 'edgetpu'` means that either:

a) you don't have `edgetpu` module installed. If you have only installed everything from the getting started page, then edgetpu is definitely not installed. You'll have to install it [here](python).

b) it is installed, but the python version you are using couldn't find it in it's path. I'm not sure the exact path that `edgetpu` was installed for your system, but for me it's here:
```
~ » python3 -c 'print(__import__("edgetpu").__path__)'                                                 1 ↵ vunam@penguin
['/usr/lib/python3/dist-packages/edgetpu']
```
So in that case, one way you can add it to your python program is like so:
```
import sys
sys.path.append('/usr/lib/python3/dist-packages/edgetpu')
```
But that's the path it was installed for my system, you may have to look around to find yours.

* `RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.` is a new issue we just started seeing today. `1.14.1` is added pcie supports to our window driver, but didn't expected this to happen. If you try grabbing `1.14` (without the last `.1`) from [here](https://coral.ai/software#edgetpu-runtime), it should works (Just found out about this in this issue: https://github.com/google-coral/tflite/issues/21).

**Comment by Namburger** [comment]
FYI, for the second issue: `RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.` 
We fixed it! Just re-download the newest package (`1.14.1`) and everything should works!
sossy again for all these issues :)

**Comment by alitillawi** [comment]
Thank you for the support so far!

Status update:
- The sample project from the get sterted with the error below is now running:
RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.

What I did I have downloaded the whole rep. from https://github.com/google-coral/edgetpu, then I have run the scripts related to windows as well in the python directory the folder "edgetpu-2.14.0-py3.6.egg-info" was missing and it was added manually.


Now regarding my sample program I still no longer get the 
ModuleNotFoundError: No module named 'edgetpu'.

No I am getting: an error related to the wrapper:
ModuleNotFoundError: No module named 'edgetpu.swig.edgetpu_cpp_wrapper'

**Comment by alitillawi** [comment]
it seems that I am missing the file edgetpu_cpp_wrapper.py

**Comment by alitillawi** [comment]
Update after using pip install "https:...edgetpu for my python version" --upgrade all the missing files and modules were replaced. And I was able to run custom module.

it seems that the GIT and other installation systems are somehow inconsistent concerning paths under windows. 

Thanks again.

**Comment by Namburger** [comment]
Awesome! Glad to know you got it all figured out :)
Sorry again, the getting started really should be a straight forward step, but I think there were a few factors in this case where we were in a middle of adding new features to our `libedgetpu.dll`. 

FYI: the module from this repo won't work right out of the box, because our edgetpu modue is backed by c++ code, and it hasn't been built, that is why you are seeing the `edgetpu.swig.edgetpu_cpp_wrappe` issue. [This](https://github.com/google-coral/edgetpu/tree/master/src/cpp/swig) is the swig code that translates the c++ to python. To build it, you can do something like:
```
make DOCKER_IMAGE=ubuntu:18.04  DOCKER_CPUS="k8" DOCKER_TARGETS=swig docker-build
```
and you'l find some dynamic libraries built for the python module :)
Anyhow, unless you're looking to modify the library, the best way is to install the module from [here](https://coral.ai/software#edgetpu-python-api).
