### ISSUE TITLE
Trouble with compiling ssd_inception_v2

### ISSUE THREAD

**Issue by bguo919** [google-coral/edgetpu#161]
Hi,
I am trying to compile a (I think) fully quantized ssd_inception_v2 object detection model but am running into this compiler error.
```
Edge TPU Compiler version 2.1.302470888

Internal compiler error. Aborting! 
```
I'm fairly new to ml but I have a feeling it is due to the size of the model. If someone could look at it that would be great.

[ssd_inception_v2.tflite](https://drive.google.com/file/d/1sxSBDQu4DGP6mWlp0gfdg0cND1IB05Ou/view?usp=sharing)

**Comment by Namburger** [comment]
Hi @bguo919 
you are correct, unfortunately the model is a little too big and is causing some memory exhaustion on the tpu :/

**Comment by hjonnala** [comment]
@bguo919 please check the error with new compiler and try to fix it..
![image](https://user-images.githubusercontent.com/86132058/128907416-1b5e0f66-b704-4892-a844-339b3526485d.png)
