### ISSUE TITLE
Is There Edgetpu Tflite Model Based On Open Images for Object Detection?

### ISSUE THREAD

**Issue by jsl303** [google-coral/edgetpu#164]
Is there any object detection model for coral based on open image dataset >= v4?
I tried to convert the models below with no luck.I wonder if anyone already has.

- faster_rcnn_inception_resnet_v2_atrous_oidv4
- ssd_mobilenetv2_oidv4
- ssd_resnet_101_fpn_oidv4

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

It would be nice to be able to detect more than 90 classes from coco.

**Comment by Namburger** [comment]
@jsl303 we only had canned object detection models with the coco dataset, although we do have [tutorials](https://coral.ai/docs/edgetpu/retrain-detection/) for transfer learning with your own dataset.
For the models that failed to converts, have you got a chance to check if it meets the [requirements](https://coral.ai/docs/edgetpu/models-intro/#supported-operations)?

**Comment by jsl303** [comment]
I looked at the requirements, but unfortunately it's beyond my head.

If the 3 mentioned models from Tensorflow model zoo meet the 
requirements, it would be awesome if someone with expertise could 
convert and include them in this repo.

Of course, transfer learning is certainly a nice option, but I think it 
would be awesome for newbies like myself to be able to run object 
detection over 500 categories with Coral out of the box.

**Comment by jsl303** [comment]
It looks like PINTO0309/PINTO_model_zoo was able to convert and quantize to full int8 and compile for Coral Edge TPU.

https://github.com/PINTO0309/PINTO_model_zoo/issues/13#issuecomment-655587058
