### ISSUE TITLE
Mismatched glibc version

### ISSUE THREAD

**Issue by thinkski** [google-coral/edgetpu#17]
Running:

    make DOCKER_IMAGE=ubuntu:18.04  DOCKER_CPUS="aarch64" DOCKER_TARGETS=all docker-build

and testing one of the resulting binaries on a Coral EdgeTPU dev board, produces the following:

    mendel@edgetpu:~$ ./classify_image
    ./classify_image: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./classify_image)

Mendel ships with glibc 2.24:

    mendel@edgetpu:~$ ldd --version
    ldd (Debian GLIBC 2.24-11+deb9u4) 2.24

**Comment by dmitriykovalev** [comment]
This is because dev board still has Debian Stretch  (we are going to move to Buster soon). You can build code for dev board by specifying `DOCKER_IMAGE=debian:stretch`.

**Comment by Namburger** [comment]
> This is because dev board still has Debian Stretch (we are going to move to Buster soon). You can build code for dev board by specifying `DOCKER_IMAGE=debian:stretch`.

Just confirmed this is working

**Comment by gpapan** [comment]
@dmitriykovalev : Do you have an ETA for the Debian Stretch release? It is not included yet at https://coral.ai/software/ but it is mentioned at https://coral.googlesource.com/docs/+/refs/heads/master/Releases.md and https://packages.cloud.google.com/apt/dists and https://coral.googlesource.com/docs/+/refs/heads/release-day/GettingStarted.md .

**Comment by Namburger** [comment]
@gpapan it's released back in November 19 :)
https://coral.ai/news/updates-11-2019/
