### ISSUE TITLE
I2C Device or resource busy

### ISSUE THREAD

**Issue by sterlingrpi** [google-coral/edgetpu#174]
I am using the Coral dev board with the Adpeet Darkpaw quadruped. The servo control is based on the Adafruit PCA9685. I had to modify the I2C.py file https://github.com/adafruit/Adafruit_Python_GPIO/blob/master/Adafruit_GPIO/I2C.py#L40 to recognize the platform use return bus 1.

My issue is that if I boot the dev board while attached to the servo hat I get the error "OSError: [Errno 16] Device or resource busy". However, if I boot the dev board and THEN attach the servo hat everything works fine. I learned this because it was experienced by another user https://forums.adafruit.com/viewtopic.php?f=8&p=768469

What is going on? Why is the dev board connecting to the device on boot up? Is there a way to prevent this auto connect or at least clear the connection so the device is not busy when I go to access it?

**Comment by sterlingrpi** [comment]
Managed to find a solution to this. I changed "I2C_SLAVE" to "I2C_SLAVE_FORCE" on line 163 of smbus.py.
https://github.com/adafruit/Adafruit_Python_PureIO/blob/master/Adafruit_PureIO/smbus.py#L163

I would close this issue but I am still curious as to why this problem occurs.

**Comment by Namburger** [comment]
@sterlingrpi it is because there is a driver that's already using it.
```
mendel@coy-xylophone:~$ sudo i2cdetect -y -r 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- UU -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --    
```
You can use `I2C_SLAVE_FORCE` to overcome this, which is okay!
