### ISSUE TITLE
EdgeTPU PWM output low average voltage problem with Servo motor

### ISSUE THREAD

**Issue by namigalyv** [google-coral/edgetpu#175]
We have an MG996R model Servo motor.
The PWM output from the Coral is only 2.5V peak, and not very strong. We are using the HC4049 model buffer for this. But this doesn't work. We couldn't run our servo motor. Previously we have Raspberry PI 3 Model B and it was working smoothly.

We are following two libraries.
First, **Adafruit_CircuitPython_Motor**
And they have explained this situation in this article. https://learn.adafruit.com/circuitpython-on-google-coral-linux-blinka/pwm-outputs-servos
We tried the codes in the "Servo Control" section

Second, **python-periphery**
``from periphery import PWM``
``pwm = PWM(2, 0)``
``pwm.duty_cycle = 0``
``pwm.frequency = 5000``
``pwm.duty_cycle = 0.98``
``pwm.frequency = 5500``

We didn't get errors in both libraries but nothing happened.
Some people have this problem but there is no solution.
https://stackoverflow.com/questions/55385943/google-edgetpu-cant-get-pwm-to-work-with-python

References.

Linux arid-goose 4.9.51-imx #1 SMP PREEMPT Thu Jan 31 01:58:26 UTC 2019 aarch64 GNU/Linux

mendel@jumbo-zebra:~$ cat /etc/os-release
PRETTY_NAME="Mendel GNU/Linux 4 (Day)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.withgoogle.com/"
SUPPORT_URL="https://coral.withgoogle.com/"
BUG_REPORT_URL="https://coral.withgoogle.com/"
VERSION_CODENAME="day"

Do you have an idea to increase the power of the PWM output?
Thanks.

**Comment by Namburger** [comment]
@namigalyv 

Thanks @usbguru for this detailed answer:
"A buffering circuit is required.  The HC4049 is great for gluing logic chips together, but it is not intended for driving motors. The customer either has to design their own driver (hardware circuit) or they just drop in a driver chip like this one:  https://www.allegromicro.com/en/products/motor-drivers/brush-dc-motor-drivers/a3982"

That isn't a recommendation for the exact chip since it'd depends on your usage.

**Comment by namigalyv** [comment]
Thanks @Namburger  for your answer. 
We have already a driver(hardware circuit) but we are using it for 25MM metal gear motor as in Raspberry.

Adafruit document says you can handle this problem just one buffer. 2 days ago I opened this issue and they said this chip wasn't a buffer.
https://github.com/adafruit/Adafruit_CircuitPython_Motor/issues/45

So I ordered the same buffer again and I waiting. If it doesn't work this time either, they should update their documentation.

I didn't guess Raspberry's pinout and coral's pinout would be so different like this.

**Comment by Namburger** [comment]
@usbguru could you suggest a solution? Thanks

**Comment by usbguru** [comment]
@namigalyv 
The MG996R model Servo motor you have selected can take up to 2.5A at 6V:  [MG996R specs](https://components101.com/motors/mg996r-servo-motor-datasheet.  )
Driving the servo anywhere near its capacity will require a complex power driver.   Using just one buffer chip is serious underkill !


The HC4049 and the HC4050 are current buffers.  The Adafruit article shows an extremely simple circuit to drive the servo with the PWM output through the 4050 buffer to get enough current to the servo.   The 4049 is an inverting buffer, so it would also work, but it will change a 75% on PWM to a 25% on PWM.


Before connecting the servo, what voltages and waveform do you measure on the PWM pin?  
Do the periphery commands do as you expect?  
Have you verified the servo works by itself?


Also, you can get more than a 2.5V output on the PWM pin.    Your [Adafruit article](https://learn.adafruit.com/circuitpython-on-google-coral-linux-blinka/pwm-outputs-servos)  expects to see a 2.5V swing, but that is with the default configuration of the GPIO ports.  Changing the device tree can make that swing to 3.3V.

**Comment by mbrooksx** [comment]
An overlay is needed to provide a 3.3V swing. The pin configuration for the device tree overlay can be found here: https://coral.googlesource.com/linux-imx/+/refs/heads/master/arch/arm64/boot/dts/freescale/fsl-imx8mq-phanbell.dts#171

The number there (0x7f), can be decoded with this bitmask: https://coral.googlesource.com/linux-imx/+/refs/heads/master/Documentation/devicetree/bindings/pinctrl/fsl%2Cimx8mq-pinctrl.txt.

2.5V comes from PUE (pull up enable) being set while all GPIOs have a weak pull down. If this is removed (and you should remove LVTTL and ODE for maximum drive strength), the IO will drive 3.3V. Here's an overlay that does it. To enable, copy pwm.dtbo to /boot and then edit overlays.txt to add pwm into the list (i.e. overlays=pwm)

[PWM_Overlay.zip](https://github.com/google-coral/edgetpu/files/4955027/PWM_Overlay.zip)

**Comment by namigalyv** [comment]
Thanks all for your answers. I broke my servo motor accidentally while testing the hardware circuit and external battery.  And I ordered a new servo motor. I will get back to you about the results.

Thanks

**Comment by namigalyv** [comment]
@mbrooksx 

I copied pwm.dtbo file in /boot directory and edited overlays.txt
But nothing happened. Am I doing something wrong? especially about bitmask. I didn't know what to do with bitmask
```
mendel@jumbo-zebra:/boot$ ls
Image                   fsl-imx8mq-phanbell.dtb  pwm.dtbo
System.map-4.14.98-imx  fsl-imx8mq-yorktown.dtb  pwm.dts
boot.scr                lost+found               u-boot.imx
config-4.14.98-imx      overlays.txt             vmlinuz-4.14.98-imx
```
```
mendel@jumbo-zebra:/boot$ cat overlays.txt 
# List of device tree overlays to load. Format: overlay=<dtbo name, no extenstion> <dtbo2> ...
overlay=pwm
```

Thanks

**Comment by mbrooksx** [comment]
The overlay is applied on boot, you'll need to reboot. You can verify it is applied in the serial console (just before the kernel boots):

Normal Boot
Hit any key to stop autoboot:  0 
1800 bytes read in 6 ms (293 KiB/s)
## Executing script at 40480000
23112192 bytes read in 694 ms (31.8 MiB/s)
56208 bytes read in 11 ms (4.9 MiB/s)
107 bytes read in 3 ms (34.2 KiB/s)
loaded overlay.txt: pwm
581 bytes read in 2 ms (283.2 KiB/s)
overlay of pwm successful
## Flattened Device Tree blob at 43000000
   Booting using the fdt blob at 0x43000000
   Using Device Tree in place at 0000000043000000, end 0000000043010fff

Starting kernel ...

**Comment by namigalyv** [comment]
I have already restarted 100 times and could not verify it was applied.

**Comment by mbrooksx** [comment]
What is the output on your serial port?

**Comment by namigalyv** [comment]
I just saw the serial port.
```
Fastboot: Normal
Hit any key to stop autoboot: 0
1800 bytes read in 53 ms (32.2 Kib/s)
## Executing script at 40480000
32112192 bytes read in 907 ms (24.3 MiB/s)
44144 bytes read in 46 ms (936.5 KiB/s)
107 bytes read in 54 ms (1000 Bytes/s)
loaded overlay.txt: pwm
375 bytes read in 63 ms (4.9 Kib/s)
overlay of pwm succesful
## Flattened Device Tree blob at 43000000
   Booting using the fdt blob at 0x43000000
   reserving fdt memory region: addr=43000000 size=b000
   Using Device Tree in place at 0000000043000000, end 000000004300dfff

Starting kernel ...
```
It seems successful but servo doesn't working.
No problems with servos and cables.

These were the codes I was running
```
pwm = PWM(0,0)
pwm.frequency = 50
pwm.duty_cycle= 0.75
pwm.enable()

print(pwm.period)
print(pwm.frequency)
print(pwm.enabled)
pwm.duty_cycle = 0.50
pwm.close()
print("done")
```
Thanks

**Comment by namigalyv** [comment]
@mbrooksx 

In the PWM overlay file, you submitted, there was only overlay for pwm1 and pwm2. I measured voltages on the PWM pins.

PWM1: 1.65V
PWM2: 1.65V
PWM3: 0.85V

As a result, the servo motor didn't work.

Could this be due to my Mendel OS version?

**Comment by mehmetturanguzel** [comment]
> @mbrooksx
> 
> In the PWM overlay file, you submitted, there was only overlay for pwm1 and pwm2. I measured voltages on the PWM pins.
> 
> PWM1: 1.65V
> PWM2: 1.65V
> PWM3: 0.85V
> 
> As a result, the servo motor didn't work.
> 
> Could this be due to my Mendel OS version?

@mbrooksx

**Comment by mbrooksx** [comment]
Yes, I only did PWM 1 and 2. You would just need to add PWM3 to the DTS file and recompile in the same fashion.

Here is that.

[pwm_overlay.zip](https://github.com/google-coral/edgetpu/files/4990905/pwm_overlay.zip)

**Comment by namigalyv** [comment]
Thanks
Our pwm1 and pwm2 pins already were available to use. But the problem is 1.65V voltage, not enough for servo motor to work. I'm tried connected to pwm1 and pwm2. Doesn't work

**Comment by mehmetturanguzel** [comment]
> Thanks
> Our pwm1 and pwm2 pins already were available to use. But the problem is 1.65V voltage, not enough for servo motor to work. I'm tried connected to pwm1 and pwm2. Doesn't work

@mbrooksx

**Comment by namigalyv** [comment]
Hi,

our problem continues and we need your help. We did what you said, and the PWM pin output increase from 0.85V to 1.65V, but 1.65V is still not enough. We needed 3.3V. As you said before, you should "remove LVTTL and ODE for maximum drive power" but we couldn't find a document on how to do this. Our coral dev board going to be garbage.

Thanks

**Comment by namigalyv** [comment]
Hi,

we are fixed our problem. The problem is the Power cable. Our Power cable output is 5V/2A but the board requires 5V/3A.  We are changed Power cable and problem fixed.

Thanks
