### ISSUE TITLE
Internal compiler error. Aborting! 

### ISSUE THREAD

**Issue by danschu** [google-coral/edgetpu#176]
Edge TPU Compiler version 14.1.317412892

Model: [blubuuu.zip](https://github.com/google-coral/edgetpu/files/4949077/blubuuu.zip)

Based on
https://tfhub.dev/sayakpaul/lite-model/deeplabv3-mobilenetv2-ade20k/1/default/1
with post training quantization.

**Comment by Namburger** [comment]
@danschu 
It looks like you model's outputs of size (512X512X151) is just too large to fit on the edgetpu's RAM. Unfortunately, this is a HW limitation that we cannot overcome with SW at this time. I suggest shrinking the model output size and try compiling again

**Comment by danschu** [comment]
I removed the last upscaling layer, but I still get the same error.

[mymodel.zip](https://github.com/google-coral/edgetpu/files/4977629/mymodel.zip)

**Comment by danschu** [comment]
@Namburger: Can you please check the last attached file? I have removed the 512x512x151 layer, but I get the same error.
Thank you :)

**Comment by Namburger** [comment]
@danschu hey sorry, I forgot to update, this seems similar to an issue we've seen before and I've attached the model on the bug to have it looked at but haven't got a response yet. I'll ping it again today and will keep you updated

**Comment by danschu** [comment]
@Namburger 
Any news on the model? Is it a compiler bug? If so, when do we get a new version of the compiler?

**Comment by Namburger** [comment]
@danschu hey, so sorry for the late response, unfortunately it is still the size limitation which we currently don't have a way to overcome via software.
There are a couple of ops with inputs resolution of 65x65x960 and 257x257x96, these inputs are just a little too large, could you try shrinking those too?
Apologies, I understand that could cause much precision drop

**Comment by danschu** [comment]
@Namburger 
I used the new compiler (v15.0) and splited the model into many parts. The problem is on the attached part of the model. I think that is not the input resolution. I still get an "internal compile error". Can you have a look on it?

Thank you
[mymodel_segment_21_of_24.zip](https://github.com/google-coral/edgetpu/files/5577982/mymodel_segment_21_of_24.zip)
![image](https://user-images.githubusercontent.com/6059697/99882065-08033100-2c1e-11eb-9731-0164bad02bf7.png)

**Comment by danschu** [comment]
@Namburger Can you confirm this as a compiler bug?

**Comment by manoj7410** [comment]
Feel free to reopen if the issue still persists.
