### ISSUE TITLE
Internal compiler error. Aborting!

### ISSUE THREAD

**Issue by LINYOUWEI0804** [google-coral/edgetpu#178]
tf 2.2.0
ubuntu18.04
Edge TPU Compiler version 14.1.317412892

I use MobileNet V2 Image size 224*224*3
my model       https://drive.google.com/drive/folders/1DTnuCy1YrTurlktV7kkDqe5QDVeHuam2?usp=sharing

**Comment by Namburger** [comment]
@LINYOUWEI0804 Your `.h5` model is really odd, with input size of `(?,224,224,3)` how did you make the model? Please give as much details as possible
Also with tf2.2 for post training quantization, please turn off MLIR for now.

**Comment by LINYOUWEI0804** [comment]
creat Model:

model = tf.keras.models.Sequential()
model.add(tf.keras.applications.MobileNetV2(include_top=False, weights='imagenet', input_shape=(224 ,224 ,3)))
model.add(keras.layers.Flatten())
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(9, activation='softmax'))
print(model.summary())

Then use tf Post-training integer quantization   [https://www.tensorflow.org/lite/performance/post_training_integer_quant]

**Comment by LINYOUWEI0804** [comment]
My code:
[2.2.0.zip](https://github.com/google-coral/edgetpu/files/4958106/2.2.0.zip)

**Comment by LINYOUWEI0804** [comment]
Can be successfully compiled    The model should be changed to this：

model = tf.keras.applications.MobileNet(include_top=False, weights='imagenet', input_shape=(224 ,224 ,3))
x = GlobalAveragePooling2D()(model.output)
x = Flatten()(x)
x = Dropout(0.5)(x)
output_layer = Dense(9 ,activation = 'softmax')(x)
model = Model(inputs = model.inputs, outputs=output_layer)
model.trainable = True 
model.summary()

**Comment by LINYOUWEI0804** [comment]
Can be successfully converted into a model supported by tpu,but This error occurred when executing the .py file 

[mendel@orange-eft:~/sparrow$ python3 classify_image.py --model st_io_edgetpu.tflite 
Traceback (most recent call last):
  File "classify_image.py", line 27, in <module>
    main()
  File "classify_image.py", line 21, in main
    for result in engine.classify_with_image(img, top_k=3):
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 99, in classify_with_image
    return self.classify_with_input_tensor(input_tensor, threshold, top_k)
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 123, in classify_with_input_tensor
    input_tensor)
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 136, in run_inference
    result = self._engine.RunInference(input)
  File "/usr/lib/python3/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 111, in RunInference
    return _edgetpu_cpp_wrapper.BasicEnginePythonWrapper_RunInference(self, input)
RuntimeError: external/org_tensorflow/tensorflow/lite/core/subgraph.cc:1044 required_bytes != bytes (602112 != 150528)
]

label : [sparrow.txt](https://github.com/google-coral/edgetpu/files/4963910/sparrow.txt)

Image : ![0](https://user-images.githubusercontent.com/58504153/88253560-f0a24e80-cce4-11ea-991a-838aa210c3ef.JPG)

code [classify_image.py.zip](https://github.com/google-coral/edgetpu/files/4963908/classify_image.py.zip)

Model :  [st_io_edgetpu.tflite.zip](https://github.com/google-coral/edgetpu/files/4963906/st_io_edgetpu.tflite.zip)

**Comment by Namburger** [comment]
@LINYOUWEI0804 Looks like your model still has float I/O tensors, which won't with our classification engine. 
Can you try Post Training Quantization again with tf-nightly(>2.3) and turn off mlir by adding this line:
```
converter.experimental_new_converter = False
```
Then you should have a working tflite model!

**Comment by LINYOUWEI0804** [comment]
Thank you!it work.

**Comment by LINYOUWEI0804** [comment]
Can be successfully converted to a model in tpu format. But there will be this error in the dev board prediction:

mendel@orange-eft:~/sparrow$ python3 classify_image.py --model false_edgetpu.tflite 
Traceback (most recent call last):
  File "classify_image.py", line 27, in <module>
    main()
  File "classify_image.py", line 21, in main
    for result in engine.classify_with_image(img, top_k=3):
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 99, in classify_with_image
    return self.classify_with_input_tensor(input_tensor, threshold, top_k)
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 123, in classify_with_input_tensor
    input_tensor)
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 136, in run_inference
    result = self._engine.RunInference(input)
  File "/usr/lib/python3/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 111, in RunInference
    return _edgetpu_cpp_wrapper.BasicEnginePythonWrapper_RunInference(self, input)
RuntimeError: external/org_tensorflow/tensorflow/lite/core/subgraph.cc:1044 required_bytes != bytes (602112 != 150528)

Where is converter.experimental_new_converter = False?
Changed program：
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
tflite_models_dir = pathlib.Path("/home/must/下載/generater/edge_model/1/")
tflite_models_dir.mkdir(exist_ok=True, parents=True)
converter.experimental_new_converter = False
tflite_model_file = tflite_models_dir/"st_model.tflite"
tflite_model_file.write_bytes(tflite_model)

**Comment by Namburger** [comment]
1) Your model still has float IO tensor, try using tf-nightly. 
2) the converter line needs to be right before converter.convert()
