### ISSUE TITLE
Internal Compiler Error with RetinaNet

### ISSUE THREAD

**Issue by rajansaini691** [google-coral/edgetpu#182]
Hello! I am trying to get retinanet (from tensorflow's [tpu zoo](https://github.com/tensorflow/tpu/blob/master/models/official/detection/MODEL_ZOO.md)) to run on the edge device. I have successfully converted it to tflite and quantized it (after removing non-max suppression). Unfortunately, on `edgetpu_compile`, the compiler aborts, and decreasing the input size (which should implicitly shrink the output tensor) does not seem to help. I understand from other issues that the TPU's memory is constrained, but it is unclear to me what those constraints are specifically. What direction should I take to get the model up and running? I am considering reducing the model size and bounding box density, but would be open to any and all advice. 

For reference, [here is the model](https://github.com/rajansaini691/retinanet-model-tflite/raw/master/tflite/model.tflite).

**Comment by Namburger** [comment]
@rajansaini691 how did you quantize the model?
The model looks really odd when I visualize with netron:
![Screenshot 2020-07-23 at 2 27 30 PM](https://user-images.githubusercontent.com/25712149/88330200-ae7f0a00-ccf0-11ea-8eec-36dd8896eec4.png)

**Comment by rajansaini691** [comment]
@Namburger Thanks for the quick response. You know, I thought it looked strange too; thanks for confirming :)
Here's my quantization script: 
[export_tflite.txt](https://github.com/google-coral/edgetpu/files/4968359/export_tflite.txt)
I don't think I did anything too out-of-the-ordinary with the quantization, but I'm not sure. 

I'll also attach the SavedModel it accepts. 

I also used the following script (found in [tensorflow's tpu repository](https://github.com/tensorflow/tpu/blob/master/models/official/detection/GETTING_STARTED.md)) to go from the checkpoint to the savedmodel:
```
# Convert to SavedModel
mkdir -p tmp
EXPORT_DIR="$REPO_PATH/tmp"
CHECKPOINT_PATH="$REPO_PATH/out/model.ckpt-0"	# TODO Read as arg from user
PARAMS_OVERRIDE="{ architecture: { num_classes: 5 }, postprocess: { apply_nms: False } }"  # if any.
BATCH_SIZE=1
INPUT_TYPE="raw_image_tensor"
INPUT_NAME="input-to-image"
INPUT_IMAGE_SIZE="640,640"
python $TPU_REPO_PATH/models/official/detection/export_saved_model.py \
  --export_dir="${EXPORT_DIR?}" \
  --checkpoint_path="${CHECKPOINT_PATH?}" \
  --params_override="${PARAMS_OVERRIDE?}" \
  --batch_size=${BATCH_SIZE?} \
  --input_type="${INPUT_TYPE?}" \
  --input_name="${INPUT_NAME?}" \
  --input_image_size="${INPUT_IMAGE_SIZE?}" 
```
Probably the only possibly-relevant item here is that I had to disable non-max suppression to get quantization to work and reduce the model's # classes to match our dataset.

**Comment by rajansaini691** [comment]
[Here's the SavedModel](https://github.com/rajansaini691/retinanet-model-tflite/raw/master/tmp/saved_model.pb).

**Comment by rajansaini691** [comment]
Hi @Namburger just wanted to check in and see if you were able to reproduce the results. I'm happy to provide any more info if needed. No need to rush, just curious.

**Comment by Namburger** [comment]
@rajansaini691 Hey, sorry I haven't had a chance to reproduce, but the error seems similar to what I've seen in the past. At glance I can't tell if it's an issue with tflite quantization (since your model looks a little odd), or if it's a compiler bug
@Naveen-Dodda could you take a look at this if you have some bandwidth?

**Comment by rajansaini691** [comment]
@Namburger No worries, really appreciate your help and look forward to any insight! Do you think the patch will be released in the next month or so, or is it too soon to tell?

**Comment by Namburger** [comment]
@rajansaini691 sorry, it is too soon to tell, but one of our eng is going to look at this soon, should get an update sometimes within the next week.

**Comment by Naveen-Dodda** [comment]
Hello Rajan, 

edgetpe_compiler aborts as Model.tflite graph contains duplicate nodes (tensors are repeated). This is issue could be created at tflite end when you quatise the model. Currently we are supporting only models converted with TF 1.15. I have tired to reproduce the issues by quantizing your saved_model but this fails as we could not provide variables/. Can you conform which Tflite_convert have you used. 

Thanks

**Comment by rajansaini691** [comment]
@Naveen-Dodda Thank you. I was using tf 2.3's `TFLiteConverter` API to perform the conversion and quantization correctly. Unfortunately I could not get `tflite_convert` to work with tf 1.15 without crashing: `Check failed: std::floor((limit - start) / delta) == buffer.data.size() (79 vs. 80)`

The original model I am trying to convert is the r50-fpn over [here](https://github.com/tensorflow/tpu/blob/master/models/official/detection/MODEL_ZOO.md). I used their conversion script at `models/official/detection/export_saved_model.py` to convert to the SavedModel. (In case you wanted to reproduce my results, the only parameter I overrided was `apply_nms`, which I set to `false` to get quantization to work with 2.3).  

 What do you make of all of this, and what steps should I take to continue?

**Comment by Namburger** [comment]
@rajansaini691 update on the original issue, basically we've fixed similar issues that I mentioned. The model you posted is definitely odd and we believe that it is a tflite convertion problem which I suggest you reach out to the tensorflow team for.

**Comment by jpizarrom** [comment]
```
EXPORT_DIR="./detection_retinanet_r50-fpn-exp-tf.2.3.0.image_tensor.output_normalized_coordinates.no_output_image_info"
CHECKPOINT_PATH="./detection_retinanet_r50-fpn/model.ckpt"
PARAMS_OVERRIDE=""
BATCH_SIZE=1
INPUT_TYPE="image_tensor"
INPUT_NAME="input"
INPUT_IMAGE_SIZE="640,640"
python ./tpu/models/official/detection/export_saved_model.py \
  --export_dir="${EXPORT_DIR?}" \
  --checkpoint_path="${CHECKPOINT_PATH?}" \
  --params_override="${PARAMS_OVERRIDE?}" \
  --batch_size=${BATCH_SIZE?} \
  --input_type="${INPUT_TYPE?}" \
  --input_name="${INPUT_NAME?}" \
  --input_image_size="${INPUT_IMAGE_SIZE?}" \
  --output_normalized_coordinates=True \
  --output_image_info=False
```

```
tflite_convert \
  --saved_model_dir=./detection_retinanet_r50-fpn-exp-tf.2.3.0.image_tensor.output_normalized_coordinates.no_output_image_info \
  --output_file=./detection_retinanet_r50-fpn-exp-tf.2.3.0.image_tensor.output_normalized_coordinates.no_output_image_info.post_training_quantize.tflite \
  --post_training_quantize
```

```
python3 /home/pi/coral/tflite/python/examples/detection/detect_image.py \
  --model /home/pi/coral/detection_retinanet_r50-fpn-exp-tf.2.3.0.image_tensor.output_normalized_coordinates.no_output_image_info.post_training_quantize.tflite \
  --labels /home/pi/coral/tflite/python/examples/detection/models/coco_labels.txt \
  --input /home/pi/coral/tflite/python/examples/detection/images/grace_hopper.bmp \
  --output /home/pi/coral/tflite/python/examples/detection/images/grace_hopper_processed.bmp
```

**Comment by jpizarrom** [comment]
Hello,
Could it be because in the line L35 of the resolve_constant_range code is used std::ceil, and in L39 is used std::floor


https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/lite/toco/graph_transformations/resolve_constant_range.cc#L35

https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/lite/toco/graph_transformations/resolve_constant_range.cc#L39

**Comment by rajansaini691** [comment]
Hello! I used the new tf2 object detection API and got a "less weird" tflite model (attached). However, it also throws an internal compiler error. 

I'm guessing it has something to do with the postprocessing. A potential method of attack might be to cut it off by setting intermediate tensors, but I'm not sure what nodes to specify. 

[Here's the model](https://github.com/rajansaini691/retinanet-model-tflite/raw/master/out.tflite)

@Namburger Thank you so much for continuing to help by the way!!

**Comment by Namburger** [comment]
@rajansaini691 We are actually still working on tf2 OD API integration, I suggest sticking with tf1.15 for OD API at the moment. Here is a colab :)
https://github.com/Namburger/edgetpu-ssdlite-mobiledet-retrain
