### ISSUE TITLE
Cannot compile tflite model to TPU version with GAP2D for large tensor (Internal compiler error. Aborting!)

### ISSUE THREAD

**Issue by mistake0316** [google-coral/edgetpu#183]
I found that when doing golbal average pooling to large tensor, then the compiler will show error message.

(tensor shape 1x256x256x32)
>Edge TPU Compiler version 14.1.317412892
Internal compiler error. Aborting! 

I write a colab ipynb file at this link:
https://colab.research.google.com/drive/1J0a80nVw2dw2XnmJn-qEVFxKCiRvkgCH?usp=sharing

Is there any way to overcome this problem?
I really need to do this operation to large tensor.

<pre>
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
from functools import reduce
print(tf.__version__) #2.2.0

batch_shape = (1,256,256,32)
input = keras.layers.Input(batch_shape=batch_shape)
x = input
mean = keras.layers.GlobalAveragePooling2D()(x)
x = mean
model = tf.keras.Model(inputs=input,outputs=x)

print(f"tensor size : {reduce(lambda x,y:x*y, batch_shape)}")
print(model.summary())

def representative_data_gen():
  RNG = range(20)
  for itr in RNG:
    image = tf.random.normal(batch_shape)
    yield [image]

quantized_lite_path = "quant_medium.tflite"
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_data_gen
# converter.allow_custom_ops = True
# converter.experimental_new_converter = False
tflite_model = converter.convert()
open(quantized_lite_path, "wb").write(tflite_model)

!edgetpu_compiler {quantized_lite_path}
</pre>

**Comment by Namburger** [comment]
@mistake0316 
GlobalAveragePooling2D is not a [supported op](https://coral.ai/docs/edgetpu/models-intro/#supported-operations), can you use AveragePooling2D instead?

**Comment by mistake0316** [comment]
> @mistake0316
> GlobalAveragePooling2D is not a [supported op](https://coral.ai/docs/edgetpu/models-intro/#supported-operations), can you use AveragePooling2D instead?

@Namburger 
I need to compute Variance of along channel dimension, so I need to use GlobalAveragePooling.
However, if I fix the input shape, I can use AveragePooling2D with full kernal size to solve this problem, but it will make the flexibility of my model become very weak.

If use AveragePooling2D, I need to add lots of modification to my code to make sure it will be running as my thought. And re-compile the _edgetpu.tflite file whenever I just change input size, without any modification of layers' weight. I think it is very inconvenient for me.

**Comment by Namburger** [comment]
@mistake0316 I can definitely add `GlobalAveragePooling2D` to our feature request, but as of now the compiler just doesn't have this implemented :/ 
Would that be okay?

**Comment by mistake0316** [comment]
@Namburger 
It okay, I fix the input shape now, and waiting for your implementation for GlobalAveragePooling2D. :)

**Comment by mistake0316** [comment]
Hi, I fixed the input shape now, and replace layer from GAP2D to AvgPooling2D with full tensor size.
But it still showing **Internal compiler error. Aborting!** when I use very large tensor size (1, 256, 256, 32)
Is that solvable? :(

https://colab.research.google.com/drive/1p7hDgK9t2YhpaoEJr9FSze06kMfScBbG?hl=en#scrollTo=nC_qP4XEzA8v
****************
<pre>
!curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
!echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
!sudo apt-get update
!sudo apt-get install edgetpu-compiler

import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
from functools import reduce
print(tf.__version__) #2.2.0
batch_shape = (1,256,256,32)
input = keras.layers.Input(batch_shape=batch_shape)
x = input
mean = keras.layers.AveragePooling2D(batch_shape[1:3])(x)
x = mean
model= tf.keras.Model(inputs=input,outputs=x)

keras.utils.plot_model(model,show_shapes=True)

def representative_data_gen():
  RNG = range(20)
  for itr in RNG:
    image = tf.random.normal(batch_shape)
    yield [image]

quantized_lite_path = "quant.tflite"
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_data_gen
# converter.allow_custom_ops = True
# converter.experimental_new_converter = False
tflite_model = converter.convert()
open(quantized_lite_path, "wb").write(tflite_model)

!edgetpu_compiler {quantized_lite_path}
</pre>
