### ISSUE TITLE
E: Unable to locate package edgetpu

### ISSUE THREAD

**Issue by sigurdurbjartmar** [google-coral/edgetpu#186]
I can't install edgetpu-compiler on any machine I try. I've followed [this:](https://coral.ai/docs/edgetpu/compiler/#system-requirements) installation guide. I've tried to install on Debian 6.0 64bit, Ubuntu 20.04 64bit, and [this](https://github.com/mattiantonini/edgetpu-compiler-container) Docker container. I'm getting the same error: 

`E: Unable to locate package edgetpu-compiler"

I'm running on an Intel processor.

**Comment by Namburger** [comment]
Can you share the outputs of this command:
```
uname -a
lscpu
```

**Comment by Namburger** [comment]
@sigurdurbjartmar can you provide the above infomation?

**Comment by sigurdurbjartmar** [comment]
@Namburger This issue is solved and was a local error. The computer used also failed to install another package that needed 64bit. Tried on another known good computer and it worked perfectly. Thank you for your reply.

**Comment by pinaxe1** [comment]
The Edge TPU Compiler is no longer available for ARM64 systems (such as the Coral Dev Board), beginning with version 2.1.
Use [web-based compiler using Google Colab](https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb).
