### ISSUE TITLE
Node.js API?

### ISSUE THREAD

**Issue by moeiscool** [google-coral/edgetpu#188]
I see the python API but where is Node.js? Where is C++? with that we could at least make one without much trouble.

Think of it this way. I develop a DIY NVR platform (https://shinobi.video) . If each person bought a coral that would be a serious spike in sales. Add Node.js API wrappers and you’ll see what I mean ;)

Jetson Nano is a computer but similar idea. Because they made it easy for me to vend my software I made it so they could sell a lot more units.

**Comment by Namburger** [comment]
@moeiscool Hey!
Thanks for the suggestion, I can put the nodejs API as a suggestion, but we do have a C++ API, matter fact, the python API is a wrapper around the C++. Here is the docs for the C++ api: https://coral.ai/docs/edgetpu/tflite-cpp/#run-an-inference

Note also: there are [go-tflite](https://github.com/mattn/go-tflite) what will also allow you to bind our library with go, I'm not sure how hard is it to use this as alternative to nodejs, but I think go has a very good backend webstack also :)

**Comment by moeiscool** [comment]
thank you :) i am going to play with this! If i make anything usable I'll report back and perhaps we (the community) can make it merge ready. Cheers!

**Comment by Namburger** [comment]
@moeiscool I've put this is as a feature request, if we decided to move forward, I'll keep you up to date :). 
If you are interested in binding C++ to node, here is a standalone tflite object detection example in c++ (this should be a good start as it is much more simple than this repo): https://github.com/Namburger/edgetpu-detection-camera

**Comment by dermodmaster** [comment]
Please do not underrate this issue :heart: :)
NodeJS would be very awesome!

**Comment by mitchross** [comment]
@Namburger any update?

**Comment by Namburger** [comment]
Unfortunately, no :(
We just haven't got a chance to support other languages at this time as we're going through tons of refactoring and will have a new release soon

**Comment by mitchross** [comment]
@Namburger Can you share whats going on in this refactor?

**Comment by Namburger** [comment]
@mitchross Please take a look at [libcoral](https://github.com/google-coral/libcoral) and [pycoral](https://github.com/google-coral/pycoral), we'll soon deprecate this repo. It won't affects you if you are using tflite_runtime, we've also released a newer version of libedgetpu and the compiler. Watch out for our [release](https://coral.ai/news#releases) updates, there will be news soon.

Unfortunately, as much as I want nodejs supports to be a thing, we have prioritized other features and functionalities that couldn't fit this on our OKRs.

**Comment by xmoov** [comment]
I’m very surprised this has gotten so little traction. @Namburger has there been any new developments on the topic?

**Comment by eric-benjamin** [comment]
I’m very surprised this has gotten so little traction. @Namburger has there been any new developments on the topic?

**Comment by gokaybiz** [comment]
Any updates?
