### ISSUE TITLE
Internal compiler error. Aborting!

### ISSUE THREAD

**Issue by nicolausYes** [google-coral/edgetpu#189]
Experiencing error while compiling the model. Could the error message be more specific, so we could understand what's wrong and if the model is supported?
```
Edge TPU Compiler version 14.1.317412892
Internal compiler error. Aborting!
```

Attaching the model.
https://www.amazon.com/clouddrive/share/jGyMkyqWQmfPKZOZr3MzjLyZ2btdtCzTvWQS1E4a7nu

**Comment by trungnguyensju** [comment]
I got the same problem! Have no clue yet. If you have any update, could you please post it here. Thank you.

**Comment by Naveen-Dodda** [comment]
Hello, 

This a very generic error from the compiler. We valued your feedback and shared it. Team is working on it to share more detailed error msg. 

@trungnguyensju  could you attach your model as well. 

Thanks

**Comment by zldrobit** [comment]
I am experiencing the same problem! 
I am using TensorFlow v2.4.0 and EdgeTPU compiler 15.0.340273435.

The model is attached,
https://drive.google.com/file/d/18AZGsUwggoarKK797r1pgz3EyiICKVY8/view?usp=sharing
While I use `-a` option, the compiler exits abnormally
![image](https://user-images.githubusercontent.com/3896992/102749501-18ced000-439f-11eb-8212-993d1bedd566.png)

I can convert the model successfully without `-a`, but only one operation gets mapped to Edge TPU
![image](https://user-images.githubusercontent.com/3896992/102749720-77944980-439f-11eb-997a-eceac092c1b9.png)

**Comment by neilyoung** [comment]
I believe it makes not much sense to say "I have the same problem", but at least I try...

**Comment by Naveen-Dodda** [comment]
@neilyoung are you trying to use yolo5 on edgetpu ? 
If so please refer to [this repo](https://github.com/zye1996/Yolov5_EdgeTPU)

**Comment by NandhiniN85** [comment]
+1 I am also facing a similar error of "Internal compiler error. Aborting!" while using -a for compilation.
version used : Edge TPU Compiler version 15.0.340273435

Only one of the ops got mapped to TPU without using option -a. Please find the screenshot below.

![image](https://user-images.githubusercontent.com/57296966/118658822-60506f80-b80a-11eb-82c2-763845a25cf7.png)

**Comment by Naveen-Dodda** [comment]
@NandhiniN85 

Every model is fails due to a different reason. Can you please attach your model here to know more details why it fails to compile. 
you may refer to this [issue 356](https://github.com/google-coral/edgetpu/issues/356)

**Comment by NandhiniN85** [comment]
> @NandhiniN85
> 
> Every model is fails due to a different reason. Can you please attach your model here to know more details why it fails to compile.
> you may refer to this [issue 356](https://github.com/google-coral/edgetpu/issues/356)

Thanks for the update! I think it could be because of the size of the model. The input resolution was 600 x 800. So I tried 640 x 640 as well as 800 x 800 since the image had very small objects.

**Comment by neilyoung** [comment]
> @NandhiniN85
> 
> Every model is fails due to a different reason. Can you please attach your model here to know more details why it fails to compile.
> you may refer to this [issue 356](https://github.com/google-coral/edgetpu/issues/356)

Here is my problem
https://colab.research.google.com/drive/1y5YlBFzMAJmKR-qRnT7jzgzGRPtJ6AbM

**Comment by judahkshitij** [comment]
Hello @Naveen-Dodda I am facing the same error when trying to compile efficientdet-d1 model in tflite int8 format. I tried with two models, one with input 640x640 and one with 320x320 (in hopes to make compilation work). But I am getting "Internal compiler error. Aborting!" error for both models. Models are present here: https://drive.google.com/drive/folders/1dig57pnZD5-XMB7nzF5NbiCk5eiKOx5X?usp=sharing. Any help with this is appreciated. Thanks.

**Comment by akanksharma** [comment]
Hello @Naveen-Dodda ,

We are also getting the same issue on one of our quant models created with TF2.4. 
```
# edgetpu_compiler ufs_128_quant.tflite
Edge TPU Compiler version 14.1.317412892

Internal compiler error. Aborting! 
```
We have tried to reduce the model size to around 5 MB only but the issue still exists. 
We are however able to compile all other models except this one. 

Any help for this is appreciated.

Thanks in advance.

**Comment by hjonnala** [comment]
@akanksharma please share the ufs_128_quant.tflite model

**Comment by dtlam26** [comment]
I have quantized the SSD-Resnet50, but it seems to fail on the edgetpu_compiler like everyone, would you mind to check it out?
I attached it [here](https://drive.google.com/drive/folders/1TpE0w5i2Mw4ysY3G-U3p8HDE4KocTKFe?usp=sharing)
Is that because the file is too big?

**Comment by hjonnala** [comment]
@dtlam26 are you using new compiler? It says the model has large activation tensors so unable to compile.

![image](https://user-images.githubusercontent.com/86132058/129199122-8e7f8c0e-1802-4885-b41d-d72ca134f197.png)

**Comment by dtlam26** [comment]
> @dtlam26 are you using new compiler? It says the model has large activation tensors so unable to compile.
> 
> ![image](https://user-images.githubusercontent.com/86132058/129199122-8e7f8c0e-1802-4885-b41d-d72ca134f197.png)

I see, I still use the old version 15. How can I deal with this problem? Is there anyway I can extend the timeout so that it can manage somehow?

**Comment by hjonnala** [comment]
@dtlam26 please try with -t flag with 1000seconds it would compile.

![image](https://user-images.githubusercontent.com/86132058/129419269-f1758e29-8303-4f14-af7b-a0ab32f78195.png)

**Comment by dtlam26** [comment]
> @dtlam26 please try with -t flag with 1000seconds it would compile.
> 
> ![image](https://user-images.githubusercontent.com/86132058/129419269-f1758e29-8303-4f14-af7b-a0ab32f78195.png)

awesome! that should be. Thank you
