### ISSUE TITLE
Can we get better error reporting from the compiler please?

### ISSUE THREAD

**Issue by ppershing** [google-coral/edgetpu#190]
I know this was reported here several times but I want ot reiterate that "Internal compiler error. Aborting!" on anything that compiler does not like is really frustrating. If the compiler knows what is wrong, let it report a better message (at least "assertion failed xyz").

I am trying to train a custom signal detection model (based on reduced nvidia quartznet) and so far I came across plethora of seemingly random limitations such as
- input size (batch size) given other input dimensions
- random quantization problems (e.g. bias outside of int8 range), weird tflite files, unsupported operations, ...
- compiler not having enough memory for some models (despite they should take less than 1MB of memory which should still leave plenty of memory free)
When I hit the error, it is hard to tell what exactly did I mess up and the problem is greatly exacerbated by the fact that edgetpu_compiler is closed source and thus we have no clear idea what are its limitations.

Given the fact that there are multiple similar issues open, I would hope that you make error reporting a bit higher priority so that people can self-diagnose most of the problems.

On the other side -- should I open new issue and upload tflite model each time I come across this error?

**Comment by Namburger** [comment]
We understand your frustrations and appreciate you highlighting this issue in detail. The development team is aware of this issue and evaluating options to improve the compiler experience.

**Comment by usbguru** [comment]
Hi Peter,
Please continue to open new issues when you run into the internal compiler error.  We can test your model and see if this is something our compiler team is already working on, and perhaps give you a work-around.
