### ISSUE TITLE
Ubuntu 20.04, EdgeTpuDelegateForCustomOp

### ISSUE THREAD

**Issue by arun-kumark** [google-coral/edgetpu#192]
Dear all,

I am trying to test the classification example for EdgeTPU on my Ubuntu 20.04 LTS VM.
Following is the version information:
•	TF>=2.4.0-dev20200728
•	Ubuntu 20.04
•	Python 3.8
While running the example, I am facing the following problem:

`RuntimeError: Internal: Unsupported data type in custom op handler: 71112720Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.`

Additional information:
Command
`dpkg -l | grep edgetpu`
return
`ii  libedgetpu1-max:amd64                            14.1                                                 amd64        Support library for Edge TPU`
could you help me knowing possible debugging steps?

Kind Regards
Arun

**Comment by Namburger** [comment]
@arun-kumark Hi!
We haven't started supporting python3.8 yet. Did you build the python3.8 wheel package yourself? If you can you give as much details as possible? I maybe able to help, but the best option right now is to use python3.7

**Comment by arun-kumark** [comment]
Yes, I prepared my own wheel .

I prepared the **tflite_runtime-2.4.0-cp38-cp38-linux_x86_64.whl** and installed it following this guide.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

Could you help if I missed something?

Kind Regards
Arun

**Comment by Namburger** [comment]
@arun-kumark Ahhh, I see, please checkout [this commit](https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5) of tensorflow, apply [this patch](https://github.com/tensorflow/tensorflow/commit/72cd947f231950d7ecd1406b5a67388fef7133ea) and rebuild the tflite_runtime package!
Basically the issue is due to `libedgetpu1-max:amd64` needing that specific tensorflow commit as a a dependency.

**Comment by arun-kumark** [comment]
Hi,
Thanks for sharing this, I did exactly as you mentioned. The whl file is created too as I can see from build logs below:
But I couldn't find the build output in my PC. (I did updatedb, locate, find etc)

Copying tflite_runtime.egg-info to build/bdist.linux-x86_64/wheel/tflite_runtime-2.1.0.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/tflite_runtime-2.1.0.dist-info/WHEEL
**creating 'dist/tflite_runtime-2.1.0-cp38-cp38-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it**
adding 'tflite_runtime/__init__.py'
adding 'tflite_runtime/_interpreter_wrapper.cpython-38-x86_64-linux-gnu.so'
adding 'tflite_runtime/interpreter.py'
adding 'tflite_runtime/interpreter_wrapper.py'
adding 'tflite_runtime-2.1.0.dist-info/METADATA'
adding 'tflite_runtime-2.1.0.dist-info/WHEEL'
adding 'tflite_runtime-2.1.0.dist-info/top_level.txt'
adding 'tflite_runtime-2.1.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
+ [[ '' != \y ]]
+ exit 0

But surprisingly I couldn't find it anywhere. In fact gen folder not created, could you let me know where shall I find this file?

Kind regards
Arun

**Comment by Namburger** [comment]
Hi Arun, it should in the the `out` directory right?

**Comment by arun-kumark** [comment]
Hi Namburger,

unfortunately, the out directory not created, so I tool the whl file following the path given in Makefile, and found in /tmp/.. path instead. Installed finally.

Tested again, and got in same issue as below:

```
arun@arun:~/Documents/Google/vision/python/examples/classification$ sudo python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
2020-08-10 19:41:59.196959: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-10 19:41:59.196993: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "classify_image.py", line 123, in <module>
    main()
  File "classify_image.py", line 101, in main
    interpreter.allocate_tensors()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Internal: Unsupported data type in custom op handler: 62420304Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.
```

**Comment by Namburger** [comment]
humnn, that is odd that it comes out to /tmp. Could you share the outputs of these commands?
```
python3 -c 'print(__import("tflite_runtime").__git__version)'
python3 -c 'print(__import("tflite_runtime").__version)'
```

**Comment by Namburger** [comment]
Also, if you are interested in the edgetpu API instead: https://github.com/google-coral/edgetpu/issues/132#issuecomment-671509187

**Comment by arun-kumark** [comment]
Hi Nam,

I tried the experiment once again, but I am not able to find the whl file in the folder ..

```
arun@arun:~/Downloads/tensorflow/tensorflow/lite/tools/pip_package$ tree
.
├── build_pip_package.sh
**├── debian**
│   ├── changelog
│   ├── compat
│   ├── control
│   ├── copyright
│   └── rules
├── Dockerfile
├── Makefile
├── MANIFEST.in
├── README.md
├── setup.py
└── update_sources.sh

1 directory, 12 files
```

Logs says that it successfully created:

```
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/tflite_runtime
copying build/lib.linux-x86_64-3.8/tflite_runtime/__init__.py -> build/bdist.linux-x86_64/wheel/tflite_runtime
copying build/lib.linux-x86_64-3.8/tflite_runtime/interpreter_wrapper.py -> build/bdist.linux-x86_64/wheel/tflite_runtime
copying build/lib.linux-x86_64-3.8/tflite_runtime/interpreter.py -> build/bdist.linux-x86_64/wheel/tflite_runtime
copying build/lib.linux-x86_64-3.8/tflite_runtime/_interpreter_wrapper.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/tflite_runtime
running install_egg_info
Copying tflite_runtime.egg-info to build/bdist.linux-x86_64/wheel/tflite_runtime-2.1.0.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/tflite_runtime-2.1.0.dist-info/WHEEL
**creating 'dist/tflite_runtime-2.1.0-cp38-cp38-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it**
adding 'tflite_runtime/__init__.py'
adding 'tflite_runtime/_interpreter_wrapper.cpython-38-x86_64-linux-gnu.so'
adding 'tflite_runtime/interpreter.py'
adding 'tflite_runtime/interpreter_wrapper.py'
adding 'tflite_runtime-2.1.0.dist-info/METADATA'
adding 'tflite_runtime-2.1.0.dist-info/WHEEL'
adding 'tflite_runtime-2.1.0.dist-info/top_level.txt'
adding 'tflite_runtime-2.1.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
+ [[ '' != \y ]]
+ exit 0
```
I searched in all the places in my VM,but this **tflite_runtime-2.1.0-cp38-cp38-linux_x86_64.whl** is no where present.
I also couldn't find "build", "gen" or "out" directories

No idea what's wrong with this !

Additional information that you asked:
git version 2.25.1

**Comment by arun-kumark** [comment]
> Also, if you are interested in the edgetpu API instead: [#132 (comment)](https://github.com/google-coral/edgetpu/issues/132#issuecomment-671509187)

Yes, I installed this as well to test, the issue is same on my PC.

Kind regards
Arun

**Comment by arun-kumark** [comment]
> humnn, that is odd that it comes out to /tmp. Could you share the outputs of these commands?
> 
> ```
> python3 -c 'print(__import("tflite_runtime").__git_version)'
> python3 -c 'print(__import("tflite_runtime").__version)'
> ```
Unfortunately, these commands not working as is:
results:
```
arun@arun:~$ python3 -c 'print(__import("tflite_runtime").__git_version)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '__import' is not defined
```

the pip3 freeze gives the information of the versions on my VM

```
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow-cpu==2.3.0
tensorflow-estimator==2.3.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.4
texttable==1.6.2
tf-estimator-nightly==2.4.0.dev2020072801
tf-nightly==2.4.0.dev20200728
tflite-runtime==2.4.0
```
Thank you

Kind Regards
Arun

**Comment by Namburger** [comment]
Humnn, `tflite-runtime` is still saying 2.4.0 on pip shows, that may be an issue and I'm sorry, the commands are supposed to be:
```
python3 -c 'print(__import("tflite_runtime").__git_version__)'
python3 -c 'print(__import("tflite_runtime").__version__)'
```


> Yes, I installed this as well to test, the issue is same on my PC.

When you install the edgetpu API, you should be using these examples instead of the tflite examples: https://github.com/google-coral/edgetpu/tree/master/examples

**Comment by arun-kumark** [comment]
Ok, I uninstalled manually the problematic version 2.4.0, and then installed the 2.1.0. Now pip3 freeze output seen below:

```
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.4
texttable==1.6.2
tf-estimator-nightly==2.4.0.dev2020072801
tf-nightly==2.4.0.dev20200728
tflite-runtime==2.1.0
tornado==5.1.1
traitlets==4.3.3
```
Seems it pushes the same error as before.

```
arun@arun:~/Documents/Google/vision/python/examples/classification$ sudo python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
Traceback (most recent call last):
  File "classify_image.py", line 123, in <module>
    main()
  File "classify_image.py", line 101, in main
    interpreter.allocate_tensors()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/interpreter.py", line 243, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Internal: Unsupported data type in custom op handler: 54574512Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.
```
Appreciate your patience, kindly suggest, if something is wrong.

Also, both the commands unfortunately don't work,

It results to me:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '__import' is not defined
```

Kind Regards
Arun

**Comment by Namburger** [comment]
@arun-kumark sorry, I'm not sure why that isn't working :( keep in mind that we are also investigating the 3.8 build on our side, but I have a few questions:

* What changes did you make to it in-order to build the tflite_runtime package for python3.8?
* Did the edgetpu api example works for you? 
* How did you initialized the interpreter?

FYI: The command should have `__import__` instead of just `__import`, it's a typo on my part

**Comment by arun-kumark** [comment]
Oh! I see.. why commands didn't work, rather I could check this "__" missing. Thanks for the note !
```
python3 -c 'print(__import__("tflite_runtime").__version__)'
2.1.0
```

and 

```
arun@arun:~/Downloads/edgetpu/out/k8/examples$ python3 -c 'print(__import__("tflite_runtime").__git_version__)'
0.6.0-76902-gd855adfc5a
```

**What changes did you make to it in-order to build the tflite_runtime package for python3.8?**
I not did any change, I compiled the pip package as indicated in the git [readme.md](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package)

**Did the edgetpu api example works for you?**
No, I compiled the examples myself, as apt-get gave broken package error, no examples are build as follows:
arun@arun:~/Downloads/edgetpu/out/k8/examples$ tree
.
├── backprop_last_layer
├── classify_image
├── minimal
├── model_pipelining
├── two_models_one_tpu
└── two_models_two_tpus_threaded
I am yet testing these built binaries.

**How did you initialized the interpreter?**
To test the example program of Parrot, I am doing the following:
I installed the requirements with the script provided: install_requirements.sh
then I tested the classification_image.py as follows:
`sudo python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg`
Which throws the error.

Kind Regards
arun

**Comment by Namburger** [comment]
Hi Arun, so there are 2 APIs for using our library, the tflite_runtime API and the edgetpu API. 
We've been trying to use the tflite_runtime API that you built yourself and it isn't working, could you try the edgetpu API instead?

Can you try to install this wheel that we built (it is also experimental): https://github.com/google-coral/edgetpu/files/5052663/edgetpu-2.14.1-py3-none-any.zip
And then you can try these python examples: https://github.com/google-coral/edgetpu/tree/master/examples

> What changes did you make to it in-order to build the tflite_runtime package for python3.8?
I not did any change, I compiled the pip package as indicated in the git readme.md

Ahh, I see, you are using the experimental bazel build instead of the docker build, maybe that's why the out target was different :). I'm not sure about the tflite_runtime API, I'm sorry. We are also experimenting with it so it may be more feasible to wait until we can test and release it officially.

> Did the edgetpu api example works for you?
No, I compiled the examples myself, as apt-get gave broken package error, no examples are build as follows:
```
arun@arun:~/Downloads/edgetpu/out/k8/examples$ tree
.
├── backprop_last_layer
├── classify_image
├── minimal
├── model_pipelining
├── two_models_one_tpu
└── two_models_two_tpus_threaded
I am yet testing these built binaries.
```

Those are C++ binaries, it should works right?

**Comment by arun-kumark** [comment]
> Oh! I see.. why commands didn't work, rather I could check this "__" missing. Thanks for the note !
> 
> ```
> python3 -c 'print(__import__("tflite_runtime").__version__)'
> 2.1.0
> ```
> 
> and
> 
> ```
> arun@arun:~/Downloads/edgetpu/out/k8/examples$ python3 -c 'print(__import__("tflite_runtime").__git_version__)'
> 0.6.0-76902-gd855adfc5a
> ```
> 
> **What changes did you make to it in-order to build the tflite_runtime package for python3.8?**
> I not did any change, I compiled the pip package as indicated in the git [readme.md](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package)
> 
> **Did the edgetpu api example works for you?**
> No, I compiled the examples myself, as apt-get gave broken package error, no examples are build as follows:
> arun@arun:~/Downloads/edgetpu/out/k8/examples$ tree
> .
> ├── backprop_last_layer
> ├── classify_image
> ├── minimal
> ├── model_pipelining
> ├── two_models_one_tpu
> └── two_models_two_tpus_threaded
> I am yet testing these built binaries.
> 
> **How did you initialized the interpreter?**
> To test the example program of Parrot, I am doing the following:
> I installed the requirements with the script provided: install_requirements.sh
> then I tested the classification_image.py as follows:
> `sudo python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg`
> Which throws the error.
> 
> Kind Regards
> arun

the example I built before are working seems,
The result on one of the test example is as follows:
```

run@arun:~/Documents/edgetpu/out/k8/examples$ ./classify_image 
---------------------------
Egyptian cat
Score: 0.8125
---------------------------
tiger cat
Score: 0.128906
---------------------------
tabby, tabby cat
Score: 0.0351562

```

**Comment by arun-kumark** [comment]
Yes, the above python example is working as well.

```
arun@arun:~/Documents/edgetpu/examples$ sudo python3 classify_image.py --model mobilenet_v1_1.0_224_quant_edgetpu.tflite --label imagenet_labels.txt --image cat.bmp
---------------------------
Egyptian cat
Score :  0.83984375
---------------------------
tiger cat
Score :  0.11328125
arun@arun:~/Documents/edgetpu/examples$ 
```
Kind regards
Arun

**Comment by arun-kumark** [comment]
> I see, you are using the experimental bazel build instead of the docker build, maybe that's why the out target was different :).

I could not understand this quote you mentioned in your reply, what is the difference in bazel build and docker build ? Why they are not same, is there any document to follow this stream development ?

Thank you!

Kind Reards
Arun

**Comment by Namburger** [comment]
@arun-kumark docker build are usually more "uniform". For instance, in docker, you can have the same exact environment for each package and user can make the exact replica of the package if they build it with docker in a different machine. With bazel, the build environment depends on each machine.

For now, my suggestion is ubuntu18 or 19, as long as the system's default python is 3.7 then everything should works smoothly. 
Otherwise, you can also install python3.7 on your ubuntu20 work from there. The released tflite_runtime package shall be install able like this:
```
python3.7 -m pip install <package_name>
```

**Comment by arun-kumark** [comment]
Hi,
I understood the reason for having docker at your side, until officially released, I will wait to come back to Python 3.8.

There is no specific reason for choosing Python 3.8, as it was a default legacy python version, so we not downgraded it, as all AI models are working smoothly on the system.
To make them work with edgeTPU, I will downgrade to Python 3.7, I will update you downgrading the Python version and repeating the testing once again ! 

Thanks
Kind Regards
Arun

**Comment by arun-kumark** [comment]
Hi Nam,
I downgraded the Python from 3.8 to 3.7

```
python3 --version
Python 3.7.7
```

Also tensorflow is installed through pip now.

```
python3 -c 'print(__import__("tflite_runtime").__version__)'
2.1.0.post1

python3 -c 'print(__import__("tflite_runtime").__git_version__)'
0.6.0-76902-gd855adfc5a
(No change)
```


When I run the inference, I again get the same issue.

```
arun@arun:~/Documents/Google/vision/python/examples/classification$ sudo python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
2020-08-11 21:13:30.074313: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-11 21:13:30.074412: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "classify_image.py", line 123, in <module>
    main()
  File "classify_image.py", line 101, in main
    interpreter.allocate_tensors()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 243, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Internal: Unsupported data type in custom op handler: -1383525152Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.
```

Could you suggest once more, what's wrong with the setup now ?

Kind Regards
Arun

**Comment by Namburger** [comment]
can you run it with `python3.7 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg` instead of `python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg`?

**Comment by arun-kumark** [comment]
Ok, here is the result
```

arun@arun:~/Documents/Google/vision/python/examples/classification$ python3.7 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
2020-08-11 21:28:02.049399: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino_2020.2.120/data_processing/dl_streamer/lib:/opt/intel/openvino_2020.2.120/data_processing/gstreamer/lib:/opt/intel/openvino_2020.2.120/opencv/lib:/opt/intel/openvino_2020.2.120/deployment_tools/ngraph/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/lib/intel64:
2020-08-11 21:28:02.049524: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "classify_image.py", line 123, in <module>
    main()
  File "classify_image.py", line 101, in main
    interpreter.allocate_tensors()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 243, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Internal: Unsupported data type in custom op handler: -831053504Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.

```

**Comment by Namburger** [comment]
can you send an strace?
```
strace python3.7 ... 2> strace.txt
```
I have a feeling the wrong runtime were called

**Comment by arun-kumark** [comment]
[strace.txt](https://github.com/google-coral/edgetpu/files/5063014/strace.txt)

Please find attached strace.txt

Kind regards
Arun

**Comment by Namburger** [comment]
```
write(2, "python3.7: can't open file '...'"..., 70python3.7: can't open file '...': [Errno 2] No such file or directory
) = 70
```
sorry, no need to run the entire command, not just `python3.7 ...`
```
strace python3.7 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg 2> strace.txt
```

**Comment by arun-kumark** [comment]
[strace_new.txt](https://github.com/google-coral/edgetpu/files/5063197/strace_new.txt)

Sorry, 
I run this time the command you mentioned.
`strace python3.7 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg 2> strace.txt`

Kind Regards
arun

**Comment by Namburger** [comment]
Humnn, from the strace, it seems that the runtime were loaded okay, but can you try this:
```
sudo usermod -aG plugdev $USER
```
And do a full reboot?
Also, can you share the outputs of these:
```
$ md5sum /usr/lib/x86_64-linux-gnu/libedgetpu.so.1
$ ldd /usr/lib/x86_64-linux-gnu/libedgetpu.so.1
```

**Comment by arun-kumark** [comment]
I am sorry, 
yes, the device has to connect manually after reboot, I did sometimes back and it remained in disconnected mode.
I reconnected the device, here are the logs.

**md5sum /usr/lib/x86_64-linux-gnu/libedgetpu.so.1**
`cd4084aa31622574297ca2f8faac99aa  /usr/lib/x86_64-linux-gnu/libedgetpu.so.1`

**ldd /usr/lib/x86_64-linux-gnu/libedgetpu.so.1**
	linux-vdso.so.1 (0x00007ffdf5915000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f4fae97c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4fae79b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4fae64c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4fae631000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4fae60c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4fae41a000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f4fae3ee000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4faeaa5000)

traces after full reboot.
[strace_new_reboot.txt](https://github.com/google-coral/edgetpu/files/5063382/strace_new_reboot.txt)

I recollected the traces.

Please let me know too, what text you observe in traces.txt file for debugging.

Kind regards
Arun

**Comment by Namburger** [comment]
Hi, from the strace, I'm just try to see which libraries are loaded during runtime, this all seems correct so I'm not sure why it is not working. You did installed the tflite_runtime package from our released page right? https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter
I'm very confused as to why this isn't working...

**Comment by arun-kumark** [comment]
Yes, you are right. I have taken the whl (tflite_runtime-2.1.0.post1-cp37-cp37m-linux_x86_64.whl) from https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter.

I am using the Virtual Machine environment, is that not the limitation? I am not sure.
I have google Coral SDK board as well, I can try repeating experiments on SDK board also.

Kindly suggest.

Best Regards
arun

**Comment by Namburger** [comment]
So the 
```
RuntimeError: Internal: Unsupported data type in custom op handler: -831053504Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.
```
issue boils down to the tflite_runtime is mismatched with libedgetpu,
when you ran the command, I see these logs:
```
2020-08-11 21:28:02.049399: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino_2020.2.120/data_processing/dl_streamer/lib:/opt/intel/openvino_2020.2.120/data_processing/gstreamer/lib:/opt/intel/openvino_2020.2.120/opencv/lib:/opt/intel/openvino_2020.2.120/deployment_tools/ngraph/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/lib/intel64:
```
which I only see in newer tflite_runtime package. I'm not 100% on this :/ but it's possible that your build form python3.8 is still being used some how. My suggestion is to remove all related tflite_runtime package and reinstall

**Comment by arun-kumark** [comment]
Hi Nam,
I checked the python3.8 dependencies, and it's not depends on 3.8 now..
I did the experiment in a new virtual environment where only python 3.7 is present.
I am repeating the experiment on a new VM created for Ubuntu18.04 with default python version 
`Python 3.6.9`

```
arun@ubuntu:~/coral/tflite/python/examples/classification$ ldd /usr/lib/x86_64-linux-gnu/libedgetpu.so.1
	linux-vdso.so.1 (0x00007ffcf01ee000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f3eb9f51000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3eb9bc8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3eb982a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3eb9612000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3eb93f3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3eb9002000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f3eb8de4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3eba169000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3eb8bdc000)
```

```
arun@ubuntu:~/coral/tflite/python/examples/classification$ md5sum /usr/lib/x86_64-linux-gnu/libedgetpu.so.1
cd4084aa31622574297ca2f8faac99aa  /usr/lib/x86_64-linux-gnu/libedgetpu.so.1
```

```
arun@ubuntu:~/coral/tflite/python/examples/classification$ sudo python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 161, in load_delegate
    delegate = Delegate(library, options)
  File "/home/arun/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 120, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 99, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 73, in make_interpreter
    {'device': device[0]} if device else {})
  File "/home/arun/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 164, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1
```

But above file is present, 
Could you help once again seeing what's wrong, I am sure, something I am missing throughout.

I am taking the installation on the system from the same zip (whl) experimental you mentioned in above thread.

Kind Regards
Arun

**Comment by Namburger** [comment]
Hi @arun-kumark I think it's better if we can try all of this without using VMs. Our packages from here is quite proven and we knows that it works: https://coral.ai/docs/accelerator/get-started/#3-run-a-model-using-the-tensorflow-lite-api

Basically, VM doesn't allows access to USB devices by default and you can enable it [like this](https://www.tecmint.com/enable-usb-in-virtualbox/) but it throws another layer of complexity in the mix. If you want to keep using the VM, I would try to look around the VM's config to make sure this is allow first. Then you can try adding this linux rule (should be default for most modern linux OS) and then fully reboot your machine:
```
$ sudo usermod -aG plugdev <your linux user name>
```

**Comment by arun-kumark** [comment]
Thanks a lot Nam,

Unfortunately, from home office, I can test this device on VM only, as officially, for me it's not allowed to install a parallel OS on office PC, my host environment is Window 10.

Also, I followed the link that you shared for VM, I checked the Extension pack which turned out to be quite expensive extension. (1000 Euros + 200 Euro) 

I also now think, the problem is VM, but not sure how to debug it.

I am still debugging for the root cause for this limitation.

I will update soon.

Kind Regards
Arun

**Comment by Namburger** [comment]
Hi @arun-kumark humn, I think you should be getting these extension for free in virtual box o_0 that's is very expensive, what is your current VM vendor?

**Comment by arun-kumark** [comment]
My VM Vendor is VMware® Workstation 15 Player, 15.5.2 build-15785246. In which this extension not there.

I have an update.

I repeated the steps from beginning in the thread on fresh VM.

Here are the details for the Packages I am using:
**edgetpu==2.14.0
tflite-runtime==2.1.0.post1**

It's working as below:
I checked, the message that model is loading into Edge TPU memory is right, as when I disconnected the device from my VM, I got `ValueError: Failed to load delegate from libedgetpu.so.1 not loaded` error.

```
arun@arun:~/tflite/python/examples/classification$ sudo python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
12.2ms
3.1ms
3.1ms
2.8ms
2.7ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.77734
```
Thank you very much for helping throughout.

`So I can confirm, it's working on Ubuntu 20.04 and Python 3.8.2 version.` 👍 💯

**Comment by Namburger** [comment]
@arun-kumark Awesome! 
Thanks @dmitriykovalev for releasing the python3.8 wheel and @usbguru (Gene) for parallel assistance
