### ISSUE TITLE
The way to read core's current frequency and temperature 

### ISSUE THREAD

**Issue by pch0561** [google-coral/edgetpu#197]
Hi 

I want to measure core frequency and temperature on Coral. (like vcgencmd in Raspberry Pi or tegrastats in TX board)
Is there any way to read core's current information?

Thanks

**Comment by Namburger** [comment]
@pch0561 We currently don't have any nice tools for this task, but you can see the board's temperature using this command below:
```
$ cat /sys/class/thermal/thermal_zone0/temp
```

**Comment by usbguru** [comment]
@pch0561 
As Nam pointed out, you can read the temperature of the chip.  You can also read the dynamic frequency scaling registers:
https://coral.ai/docs/pcie-parameters/#configure-the-shutdownwarning-temperatures

trip_point0_temp: 250MHz threshold
trip_point1_temp: 125MHz threshold
trip_point2_temp: 62.5MHz threshold
hw_temp_warn2: automatic shutdown threshold

You can access the current values of these registers with the sysfs interface like this:
cat /sys/module/apex/parameters/trip_point0_temp

To determine the current frequency , measure the temperature and compare it to the dynamic frequency settings:

if temp>=trip_point2_temp, the edge TPU is running at 62.5MHz
     else if temp>= trip_point1_temp, the edge TPU is running at 125MHz
          else if temp >= trip_point0_temp, the edge TPU is running at 250MHz
               else the edge TPU is running at 500MHz
