### ISSUE TITLE
how to use c++ interface to show the image in the monitor？

### ISSUE THREAD

**Issue by dinghuawen** [google-coral/edgetpu#20]
i have a coral dev board. i want to show the detected result in my monitor. How can i use c++ interface to show the image in the monitor？

**Comment by Namburger** [comment]
@dinghuawen I recommend you look into external cpp libraries for showing images like gstreamer c++ with autovideo sink or xvimagesink or ximagesink. Otherwise, you should looks into general linux tools for displaying images on linux systems.

**Comment by mtyka** [comment]
@dinghuawen , the answer strongly depends on what the rest of your app wants to do. Are you showing single images ? Are you streaming video with overlays ?
For video consider gstreamer with video/image sinks as Namburger suggested. 
If you want to just have a graphical application, the devboard comes with Wayland (an X clone) which can support simple X windows or more sophisticated frameworks like Qt. Here's a minimal Qt app:

Simple hello world app:
```
#include <QApplication>
#include <QPushButton>
int main(int argc, char **argv) {
 QApplication app (argc, argv);
 QPushButton button ("Hello world !");
 button.show();
 return app.exec();
}
```

```CMakeLists.txt``` for building:

```
cmake_minimum_required(VERSION 3.1.0)
project(helloworld)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)
if(CMAKE_VERSION VERSION_LESS "3.7.0")
    set(CMAKE_INCLUDE_CURRENT_DIR ON)
endif()
find_package(Qt5 COMPONENTS Widgets REQUIRED)
add_executable(helloworld main.cc )
target_link_libraries(helloworld Qt5::Widgets)
```


To run do:
```
sudo apt install qtbase5-dev qtwayland5 
cmake ./
make
./hello_world -platform wayland
```

**Comment by dinghuawen** [comment]
Hi @mtyka, @Namburger 
Thank you for the responses. I solved the problem according to your  suggestions
