### ISSUE TITLE
Specified Tensorflow Commit does not build Tensorflow Lite

### ISSUE THREAD

**Issue by j-o-d-o** [google-coral/edgetpu#201]
The docs specify to build Tensorflow Lite with commit: d855adfc5a0195788bf5f92c3c7352e638aa1109. (https://coral.ai/docs/edgetpu/tflite-cpp/#build-your-project)

But when building Tensorflow Lite with that commit with these commands:
```
./tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/lite/tools/make/build_aarch64_lib.sh
```

I get this error:
```
tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(densify.o): In function `tflite::ops::builtin::densify::Eval(TfLiteContext*, TfLiteNode*)':
densify.cc:(.text+0x378): undefined reference to `tflite::optimize::sparsity::FormatConverter<signed char>::FormatConverter(std::vector<int, std::allocator<int> > const&, TfLiteSparsity const&)'
densify.cc:(.text+0x384): undefined reference to `tflite::optimize::sparsity::FormatConverter<signed char>::SparseToDense(signed char const*)'
densify.cc:(.text+0x5f0): undefined reference to `tflite::optimize::sparsity::FormatConverter<float>::FormatConverter(std::vector<int, std::allocator<int> > const&, TfLiteSparsity const&)'
densify.cc:(.text+0x5fc): undefined reference to `tflite::optimize::sparsity::FormatConverter<float>::SparseToDense(float const*)'
collect2: error: ld returned 1 exit status
```

It works fine on the current master branch. I am just wondering how everybody else is getting a working Tensorflow lite lib file from that commit. Haven't found any other posts about this, so I guess chances are, I am doing something wrong.

**Comment by Namburger** [comment]
HI @j-o-d-o!
Unfortunately, that commit had a makefile bug, you can apply this patch and it shall works: https://github.com/tensorflow/tensorflow/commit/72cd947f231950d7ecd1406b5a67388fef7133ea

More details here: https://github.com/google-coral/edgetpu/issues/137#issuecomment-641309262

**Comment by j-o-d-o** [comment]
That does the trick! Thanks for the quick response and help.

**Comment by Namburger** [comment]
no probs!
