### ISSUE TITLE
 flir camera captures falling objects

### ISSUE THREAD

**Issue by 87878877** [google-coral/edgetpu#202]
Sorry, I saw this tutorial on the webpage of https://coral.ai/projects/teachable-sorter/. After running the sorter.py program, I encountered some problems TypeError: is_good_photo() missing 1 required every time I value the line. positional argument:'sliding_wind ow' such an error, the camera model I use is flir's BFS-U3-04S2C-CS USB 3.1.
The following is my main program Spinnaker.py
[123.zip](https://github.com/google-coral/edgetpu/files/5095631/123.zip)

**Comment by Namburger** [comment]
@87878877 what arguments did you passed into it? The error message states that you are missing an argument, the expected arguments are defined [here](https://github.com/google-coral/project-teachable-sorter/blob/a58b016db4f10ecd304057faa00d2bc11a9e075e/Sorter/sorter.py#L56) as img, width, height, mean, sliding_window

**Comment by 87878877** [comment]
> @ 87878877您傳遞了哪些參數？錯誤消息指出您缺少參數，[此處](https://github.com/google-coral/project-teachable-sorter/blob/a58b016db4f10ecd304057faa00d2bc11a9e075e/Sorter/sorter.py#L56)將預期參數定義為img，寬度，高度，均值，sliding_window


The values ​​I returned are img, width, height, mean, sliding_window, but cmd tells me NameError: name'img' is not defined when I execute it, is there any solution?
![12](https://user-images.githubusercontent.com/38930353/90709983-026d1680-e2d0-11ea-8388-f6c2e83c868f.PNG)
![11](https://user-images.githubusercontent.com/38930353/90709985-0436da00-e2d0-11ea-985d-cfa66f9f3630.PNG)
![10](https://user-images.githubusercontent.com/38930353/90709987-04cf7080-e2d0-11ea-9668-d0e7334e9393.PNG)

**Comment by Namburger** [comment]
The error is: `Name Error: name 'img' is not defined`
That means you haven't initialed a variable calls 'img' yet.
