### ISSUE TITLE
Pad won't compile

### ISSUE THREAD

**Issue by InCogNiTo124** [google-coral/edgetpu#203]
Hello,

I have a quantized model I can't compile. I tried slicing my model in half and smaller, but no dice. Now, it literally has _only_ a Pad operation and it still won't compile.

The sliced model and converted model are [here](https://gofile.io/d/Ui6jmV)

I tried timing it and it takes around 1.5 minutes to finally fail with `"Internal compiler error."`

**Comment by Namburger** [comment]
@InCogNiTo124 it's rather the size of the inputs that rather causes these type of troubles, can you try making the input size smaller?

**Comment by InCogNiTo124** [comment]
@Namburger unfortunately, no, it is necessary for the input to be 640x480

**Comment by hjonnala** [comment]
@InCogNiTo124 give it a try with Edge TPU Compiler version 16.0.384591198. Feel free to reopen if issue still persists.
