### ISSUE TITLE
What are restrictions on ResizeNearestNeighbor?

### ISSUE THREAD

**Issue by ppershing** [google-coral/edgetpu#206]
Documantation states that 
> ResizeNearestNeighbor | All | Input/output is a 3-dimensional tensor. Depending on input/output size, this operation might not be mapped to the Edge TPU to avoid loss in precision.

I have problems with compiler crashing and my suspicion is this operation (though, it could also be MaxPool2D).
The interesting question is
  - a) what combination of `align_corners` and `half_pixel_centers` does edgeTPU compiler support?
  - b) are there any limitations on the dimensions? In particular, I think I might be hitting some maximum as I am upsampling a rather uneven shape of 1x4x834x128 with scale factor (1,2) to 1x4x1668x128

**Comment by Namburger** [comment]
@ppershing 
Apologies, this is rather a bug :( 
The compiler fails on this model only sometimes:

**Comment by ppershing** [comment]
- Interesting - so the compiler is non-deterministic?
- I am using tf nightly 2.4.0-dev20200719 for post-trianing quantization
- `RESIZE_NEAREST_NEIGHBOR        5          Operation version not supported` basically says that the operation wasn't mapped. What operation "version" is then supported?

**Comment by Namburger** [comment]
@ppershing sorry, my advice for now is to stick with tensorflow2.2 until we have next compiler release.

**Comment by ppershing** [comment]
Just curious - any idea when we can expect next compiler release?

Anyway, I manually edited tflite & downgraded OP version from 3 to 2 + removed `half_pixel_centers` which seems to be unsupported in v2 of the op. Now the compiler complains about `Image-interpolation layer won't run precisely enough on Edge TPU`
Can you give some insides what are considered precise-enough image interpolations by the compiler?

As for the tf2.2, converter fails on converting resize neares neighbor op. I also tried with bilinear, that one works but still produces too high tflite op version for the edgetpu compiler.

**Comment by rajansaini691** [comment]
@ppershing Just curious if you were able to get ResizeNearestNeighbor to convert? Theoretically, if we could reverse-engineer the linked repo's setup, we should be able to get that performance boost. Maybe one of tensorflow's nightly builds around December 28, 2019 should do it? (I got that from the commit history)

**Comment by ZhouKai90** [comment]
@Namburger I updated the edgetpu-compiler to 15.0.  But  when I used edgetpu-compiler_15.0 compile my tflite model , I still got the "RESIZE_NEAREST_NEIGHBOR Operation version not supported" error information. The newest version still hasn't fixed this problem?

**Comment by hjonnala** [comment]
Tested with Edge TPU Compiler version 16.0.384591198. ResizeNearestNeighbor  not able to map to edge TPU due to Image-interpolation layer won't run precisely enough on Edge TPU

![Screenshot from 2021-09-14 13-23-52](https://user-images.githubusercontent.com/86132058/133328639-3762f696-3c96-4368-a78f-be07aac24e99.png)
