### ISSUE TITLE
Box Tracking on Coral EdgeTPU

### ISSUE THREAD

**Issue by yascov** [google-coral/edgetpu#208]
Hi there,

Thanks for this amazing tool and examples.

I want to try out box tracking one edge device like raspberry pi with Coral TPU, are you guys planning to release it ? if not how can I start working on it ( Begginer here :-) ).

Thanks!

**Comment by Namburger** [comment]
@yascov Hi!
Do you mean like a object tracking algorithm or to retrain a model to detect boxes?

* For object tracking, we don't have an official demo, but my colleague @usbguru (Gene) has one in his repo: https://github.com/usbguru/track
I think the automl team is also working on one but I'm not familiar with it: https://github.com/google/automl-video-ondevice#for-coral-device

* If you want to retrain a model to detect boxes, you can follow my tutorial: https://github.com/Namburger/edgetpu-ssdlite-mobiledet-retrain

**Comment by yascov** [comment]
Hello @Namburger ,

Thank you. I was looking for object tracking demo with mediapipe on Coral Dev Board.
I will definitely take a look at those repos you suggested.


Thanks again.
Cheers.

**Comment by usbguru** [comment]
There are two mediapipe examples for Coral here:


https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/README.md



The object example generates data for object detection with screen
location.


Mediapipe does some tracking examples now using the box tracking
sub-graph:   https://google.github.io/mediapipe/solutions/box_tracking


These have not been combined into a single Coral demo yet.  You could be
the first one to publish this combination.



Gene Rice | Coral Field Application Engineer | riceg@google.com
<michaelbrooks@google.com>
