### ISSUE TITLE
is the libedgetpu.so  open source?

### ISSUE THREAD

**Issue by alephman** [google-coral/edgetpu#21]

**Comment by Namburger** [comment]
@alephman it's not open source, only the engines. You'll have to load it dynamically.

**Comment by alephman** [comment]
thanks!  Do you know how it works inside the box ?

**Comment by Namburger** [comment]
@alephman No problems! At a higher level, it just preload the model into the TPU's RAM and executes all supported operations on it. The catch is that the TPU was designed for processing tensors in with massively parallel capability which is the reason why it out perform CPUs by long shot.

**Comment by powderluv** [comment]
> thanks! Do you know how it works inside the box ?

Few notes from poking around FWIW:
1) It uses the Google GASKET/APEX driver (https://lwn.net/Articles/758745/) for the PCI-E SOM module - essentially punts the driver to the userspace into libedgetpu.so. You have the ability to monitor /dev/apex*
2) The USB version shows up as a MCU in DFU mode on the first run. This way you can load the TPU firmware on the first run via the DFU mode. You will notice lsusb enumerate as a Google Device on the second run. So if you are doing any benchmarking -- run it once to prime the pump :) This also avoids shipping new FW just a new version of libedgetpu that has the TPU fw bundled in it. 
3) The PCI-E version on the EdgeTPU version is faster

**Comment by alephman** [comment]
thanks @powderluv .
1) Does the PCIe version still need to download the firmware to TPU as like usb version?
2)  In usb version, you said that a google device is enumerated, I was wondering what usb class  the google device used?

**Comment by powderluv** [comment]
1. probably does. But haven't tested since I shifted to using the USB version
2. wireshark or usbmon will give you a play by play and the payload :)

**Comment by alephman** [comment]
thanks.

**Comment by anderssvedberg** [comment]
What does this mean if I want to run the edgetpu on a custom hardware? Is the USB accelerator only supported on the platforms that libedgeptu.so is precompiled for? 

I am looking into the possibility to run the USB accelerator on a iMX8X board (aarch64) that is very similar to the Coral dev board, but not identical. Is this possible without being able to recompile the libedgetpu.so ?

**Comment by Namburger** [comment]
@anderssvedberg we have libedgetpu.so compiled for armv7l, aarch64, and x86_64. Your board would have no issues!!

**Comment by Namburger** [comment]
FYI, soon :) 
https://github.com/google-coral/libedgetpu

**Comment by alephman** [comment]
LOL, thanks @Namburger
