### ISSUE TITLE
Unsupported data type in custom op handler

### ISSUE THREAD

**Issue by rgov** [google-coral/edgetpu#214]
Related to #44 but I thought I would start a new issue since that one is a bit stale.

I'm trying to use the `detect_image.py` example with Coral USB Accelerator on a Beaglebone Blue (like Beaglebone Black), an armv7l processor, running Ubuntu Bionic and Python 3.7.

I built the `tflite_runtime` version 2.3.0 for this device, and installed the `libedgetpu1-std` package:

```
$ dpkg -l | grep edgetp
ii  libedgetpu1-std:armhf                  14.1                                             armhf        Support library for Edge TPU
```

When trying to run the example, I get:

```
RuntimeError: Internal: Unsupported data type in custom op handler: 24348008Node number 2 (EdgeTpuDelegateForCustomOp) failed to prepare.
```

I changed the model to `ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite` because of another issue where the documented model URL does not work anymore.

**Comment by rgov** [comment]
Relevant comment: https://github.com/google-coral/edgetpu/issues/137#issuecomment-641309262

**Comment by Namburger** [comment]
@rgov Hi! 
Basically the issue is that you built your own `tflite_runtime` packages, which does not match the tensorflow commits that `libedgetpu.so` was built on which is [this one](https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5).
Any reason for not using our released package from here? 
https://www.tensorflow.org/lite/guide/python

**Comment by rgov** [comment]
Yes, unfortunately the released one does not work on this CPU. I think it is built with a FPU option that the processor does not support.

**Comment by Namburger** [comment]
@rgov 
I see, maybe you can try rebuilding it using this instructions?
https://github.com/google-coral/edgetpu/issues/198#issuecomment-674094275

**Comment by rgov** [comment]
I was able to build the specific version of `tflite_runtime` that was needed. Thank you.

**Comment by AustinDeric** [comment]
I also have this issue when following the documentation
