### ISSUE TITLE
`m` tool silently ignores errors, which could result in incomplete builds

### ISSUE THREAD

**Issue by pkitszel** [google-coral/edgetpu#215]
Hi,

first of all, I'm not sure if this is proper place to report bugs for *mendel*?

Actual bug:
`m` tool does not report errors through its exit code. As a result, rest of building environment got used to the fact, and is also building with errors...

**Comment by Namburger** [comment]
@pkitszel This is a good place :) 
Can you share some outputs?
```
$ uname -a
$ cat /etc/os-release
```
Also, can you capture a full build log and attach it here?
```
$ m > mendel_build_logs.txt
```
There is most likely an error somewhere that isn't showing up in the bottom of the log. You can also check progress like this on a separate term:
```
$ tail -f mendel_build_logs.txt
```

**Comment by pkitszel** [comment]
Thanks you for fast response,

I just started build, and I will attach log after it's completion.
In meanwhile, I spot just one place which could fail after proper error propagation from `m`. It is <coral-mendel-path>/build/docker.mk:86.

Here is patch with adds reporting errors from `m`: https://gist.github.com/pkitszel/d8472d31b8e298f52fd0e16fe3f65486

**Comment by pkitszel** [comment]
Ok, I made repro without any other patches, but the one I already linked to (attaching it also here).

For your convenience, I recorded also version (git HEAD) in all repositories used (by use of `repo forall` command) in file _sep-04--ver.txt_. 

I'm attaching also snapshot of version info from last month, where everything was ok, file _aug2020-ver.txt_

---

[aug2020-ver.txt](https://github.com/google-coral/edgetpu/files/5175927/aug2020-ver.txt)
[newest-mendel-build-output.log](https://github.com/google-coral/edgetpu/files/5175912/newest-mendel-build-output.log)
[sep-04--ver.txt](https://github.com/google-coral/edgetpu/files/5175913/sep-04--ver.txt)
[0001-Report-exit-code-from-m.patch.txt](https://github.com/google-coral/edgetpu/files/5175918/0001-Report-exit-code-from-m.patch.txt)

**Comment by Namburger** [comment]
@pkitszel hi, sorry for the late response, let me try to reproduce this issue in 20.04 and will keep you updated

**Comment by Namburger** [comment]
@pkitszel kindly resync the repo and build again we have made some recent changes that fixed some issues, sorry I forgot to get back to you earlier :)
