### ISSUE TITLE
Query USB CON PORT

### ISSUE THREAD

**Issue by LINYOUWEI0804** [google-coral/edgetpu#216]
I want to connect dev board to arduino but need COM PORT parameters (numbers like COM5, COM6), is there any command to check.

**Comment by LINYOUWEI0804** [comment]
Have you tried to send data to arduino from dev board?

**Comment by Namburger** [comment]
@LINYOUWEI0804 
I dont have a arduino with me currently, but I had one in my office and I remember being able to send data via [screen](https://linuxize.com/post/how-to-use-linux-screen/) on the dev board. 
First of course, you need to write a program to have the arduino listen over serial port and then screen in the dev board terminal with the same baudrate you used in your arduino program

**Comment by LINYOUWEI0804** [comment]
I use USB to connect,Does coral need to install arduino IDE and Do I need to send the arduino program to coral?
THANK!

**Comment by Namburger** [comment]
@LINYOUWEI0804 
sorry I can't quite remember but I believe I have the IDE on a different machine and upload the program to the Arduino. Something as simple as [this example](https://www.arduino.cc/reference/en/language/functions/communication/serial/read/):
```
Example Code
int incomingByte = 0; // for incoming serial data

void setup() {
  Serial.begin(9600); // opens serial port, sets data rate to 9600 bps
}

void loop() {
  // send data only when you receive data:
  if (Serial.available() > 0) {
    // read the incoming byte:
    incomingByte = Serial.read();

    // say what you got:
    Serial.print("I received: ");
    Serial.println(incomingByte, DEC);
  }
}
```
Upload that on the arduino, on the board you can type 
```
screen /dev/tty-path-to-arduino 9600
```
