### ISSUE TITLE
Compiler stuck

### ISSUE THREAD

**Issue by prashant45** [google-coral/edgetpu#217]
Hi,

The edgetpu_compiler is stuck for a long time when I am compiling my model.

[model-Conv2D-quant.tflite.tar.gz](https://github.com/google-coral/edgetpu/files/5202479/model-Conv2D-quant.tflite.tar.gz)

**Comment by Namburger** [comment]
Isn't this the same model from https://github.com/google-coral/edgetpu/issues/212#issue-689291359?
I'm getting that same error instead of compiler being stuck

**Comment by prashant45** [comment]
@Namburger 

Not exactly.
https://github.com/google-coral/edgetpu/issues/212#issue-689291359 uses `Conv1D` layer in tensorflow. If you look closely there are `Reshape` layers before the `Conv` layers. I think tensorflow-lite projects the ops to 4 dims using Reshape layer. Check the original input dimension.

To avoid that, I changed this model input to 4 dims and used `Conv2D` layers. You can see that there are no `Reshape ` layer before `Conv2D` layer.

[model-details.txt](https://github.com/google-coral/edgetpu/files/5202190/model-details.txt)

I am using,
```
tensorflow 2.3
Edge TPU Compiler version 14.1.317412892
```

**Comment by Namburger** [comment]
maybe you uploaded the wrong model?
the md5sum for both model from 212 and this one is giving me:
```
9917860e13b6f75b5cf6bd71e3b7558d
```
:)

**Comment by prashant45** [comment]
I renamed the filename in this issue, I hope that helps. The confusion might be because of the same filename for both models. Sorry for the confusion.

**Comment by Namburger** [comment]
I see, thanks, I just downloaded the new one and trying to compile now, it seems to be stuck as reported
Let me take a look and will update shortly

**Comment by Namburger** [comment]
@prashant45 I've reach out to another team regarding this, will keep you updated

**Comment by Namburger** [comment]
Update: This is fixed internally for us, I don't have a release date for this fix yet, unfortunately.
[Here](https://github.com/google-coral/edgetpu/files/5233062/edgetpu_217.tar.gz) is the compiled model!

**Comment by alexanderfrey** [comment]
@Namburger Very much waiting towards the new version ! Is there any eta ?

**Comment by Namburger** [comment]
@alexanderfrey I have no ETA, so sorry :(
we're having tons of roadblock, expect some library changes very soon though

**Comment by manoj7410** [comment]
I believe this was fixed with the newer release of the compiler. Feel free to reopen if the issue still persists.
