### ISSUE TITLE
Operation is otherwise supported and the performance

### ISSUE THREAD

**Issue by jk78346** [google-coral/edgetpu#219]
This is the model I intend to use( a simple multiply operation):
```
     (input_length, output_length) = paras
     input1 = keras.layers.Input(shape=(input_length*2, output_length))
     split  = Lambda(lambda x: tf.split(x, num_or_size_splits=2, axis=1))(input1)
     x1     = keras.layers.multiply(split)
     model  = tf.keras.models.Model(inputs=[input1], outputs=x1)
```

The EdgeTPU compiler shows the following message:
```
Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 0
Number of operations that will run on CPU: 2

Operator                       Count      Status

MUL                            1          Operation is otherwise supported, but not mapped due to some unspecified limitation
SPLIT                          1          Operation is otherwise supported, but not mapped due to some unspecified limitation
```
edgetpu_compiler version 14.1.317412892
tf version: 1.13.2

I'm wondering how can I get multiply operation running on edgetpu( since it is mentioned in document)? 
Also, is this sentence  ```A percentage of the model will instead run on the CPU, which is slower``` a valid statement for any operation / any size? Can I assume that once the mul op is running on TPU, it's performance is always gong to be better than running on CPU?

**Comment by Namburger** [comment]
@jk78346 hey! 
```
Operation is otherwise supported, but not mapped due to some unspecified limitation
```
Usually means the input resolutions is too high for that op, you may try to reduce the input size

**Comment by jk78346** [comment]
thank you for the reply!

**Comment by hjonnala** [comment]
Feel free to reopen if issue still persists.
