### ISSUE TITLE
Invoke Hangs using C API

### ISSUE THREAD

**Issue by snowzach** [google-coral/edgetpu#22]
I am working on a project DOODS https://github.com/snowzach/doods that is an image detection API wrapper around TF/TFLite with EdgeTPU support. I am experiencing random hangs during invoke when using the EdgeTPU.

DOODS is written in Go and uses a wrapper around the Tensorflow Lite C API. Is there a good way to debug the hang? Is this the right place to open the issue?

**Comment by Namburger** [comment]
@snowzach interesting project 👀
I'm away from my desk right now, but to eliminate all early suspects, can you try different USB 3.0 ports and/or would you happen to have another accelerator to try with? Humm I wonder if the gdb still can gives some info with the go wrapper

**Comment by snowzach** [comment]
Is there an environment variable you can set to get additional logging from tensorflow or the edgetpu library? It's not something I can easily reproduce unfortunately which makes me think it's hardware but a lot of my users are having the issue so maybe not.

**Comment by Namburger** [comment]
@snowzach I see, are you able to reproduce the issue on your end? I'm just suggesting those as early suspects but I can't tell if it's actually hardware related.
`libedgetpu` doesn't have any debugging variables but you can do this for tensorflow:
```
$ export TF_CPP_MIN_LOG_LEVEL={0||1||2||3}
```
where 0 shows the most and 3 shows the least. I'm not sure how this will play out with your go c wrapper. On another note, I don't believe the tensorflow output would also tell you much, maybe `strace` or `dmesg` would actually help in this case?
Btw, is your server trying to access the same accelerator at the same time with multiple threads by any chance? I know that as a back end service it's crucial to be able to handle multiple clients, but in term of resources, having multiple processes accessing the same USB devices at the same time may causes unintended behavior. A very basic example:
https://gist.github.com/Namburger/7b99d4622dff53ee4f76d720a92e286c

**Comment by snowzach** [comment]
@Namburger I did wonder about threaded access to the EdgeTPU and just went with the safe assumption that using it from multiple threads would lead to bad outcomes. :-)

I am using Tensorflow Lite, but I will try with the debugging flags to see if that produces something interesting. It's very irregular when it crashes. Some people it crashes once a day, others it's every 5 minutes. I am still leaning towards some power issue. 

So I am not a tensorflow expert, can I use the same Interpreter over and over again just changing the input and invoking it again or is there a process needed to reset the state? I wondered if that was somehow causing the issue as well. Thanks for the feedback.

**Comment by Namburger** [comment]
@snowzach 
To answer your question: 

> So I am not a tensorflow expert, can I use the same Interpreter over and over again just changing the input and invoking it again or is there a process needed to reset the state? 
Not a tensorflow expert either lol. But if by "changing the input" you meant the images inputs for inference, then that's totally fine. 

I'm not too sure if tflite has the same debugging mechanism as tensorflow. Right now I'd say that a USB port that can supplies up to 900mA (we measured this as the peak draws from our hardware) is crucial. Another thought is that for iot devices, I can see running a server like this can potentially consumes tons of power for cpu usage depending on the load. Maybe monitoring `htop` at time of crashes also? Btw, is it crashing or just hanging?

**Comment by snowzach** [comment]
@Namburger it would appear that it's just hanging. Unloading and reloading the library seems to get it working again.

**Comment by snowzach** [comment]
That's really interesting as well. I believe the USB 3.0 spec says 900ma which means it's probably driving it right up to the limit.

**Comment by Namburger** [comment]
@snowzach interesting, this could be helpful:
```
$ lsusb -v|egrep "^Bus|MaxPower"
Bus 002 Device 005: ID 18d1:9302 Google Inc. 
can't get debug descriptor: Resource temporarily unavailable
    MaxPower              896mA
...
```
I'm at ~ 900mA most of the time when running inference in iterations, which is fine on my system, but I don't think it'll translate well on iot devices, especially with CPUs also running with a smaller power supply.

**Comment by dmitriykovalev** [comment]
@snowzach Can you please provide more details about hang/crash? For example, `dmesg` output would be helpful or you can run you program under `gdb` and call [backtrace](https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_42.html) when it fails.

**Comment by snowzach** [comment]
At this point I have been running 10-15 detections per second for over 2.5 days without issue on a USB 3.0 on my Raspberry Pi 4. I am officially chalking the issue up to insufficient power/hardware issues for the time being. Thanks for your consideration and debugging suggestions. Closing for now.
