### ISSUE TITLE
Can't install gasket-dkms with linux-headers-rt-amd64 (debian 4.19.0-10-rt-amd64)

### ISSUE THREAD

**Issue by mrdolmo** [google-coral/edgetpu#220]
Analyzing gasket-dkms*.deb control file, dependencies

Depends: dkms (>= 2.1.0.0), linux-headers-686-pae | linux-headers-amd64 | linux-headers-generic | linux-headers

nevertheless I am building my own debian image with ELBE (https://elbe-rfs.org/) and using the kernel debian 4.19.0-10-rt-amd64 so therefore I am using linux-headers-rt-amd64 and not linux-header-amd64. 

When I run apt install gasket-dkms an error due to redefinition of several macros appears as well as implicit declarations, basically rwlock.h and rwlock_rt are involved (make.log attached). See bellow:

dpkg: error processing package gasket-dkms (--configure):
installed gasket-dkms package post-installation script subprocess returned error exit status 10
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
gasket-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

Checking /var/lib/dkms/gasket/1.0/build/make.log

Mon Sep 14 11:46:54 UTC 2020
make: Entering directory '/usr/src/linux-headers-4.19.0-10-rt-amd64'
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
In file included from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:12:
/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock.h:27: warning: "rwlock_init" redefined
#define rwlock_init(lock)     \

In file included from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/spinlock.h:302,
                 from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/wait.h:9,
                 from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/eventfd.h:13,
                 from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.h:11,
                 from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:4:
/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock_rt.h:102: note: this is the location of the previous definition
#define rwlock_init(rwl)    \

In file included from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:12:
/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock.h:67: warning: "read_trylock" redefined
#define read_trylock(lock) __cond_lock(lock, _raw_read_trylock(lock))
...
...
...
In file included from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/spinlock.h:302,
                 from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/wait.h:9,
                 from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/eventfd.h:13,
                 from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.h:11,
                 from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:4:
/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock_rt.h:31: note: this is the location of the previous definition
 #define write_trylock_irqsave(lock, flags)  \
 
In file included from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:12:
/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c: In function ‘gasket_handle_interrupt’:
/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock.h:71:26: error: implicit declaration of function ‘_raw_read_lock’; did you mean ‘do_raw_read_lock’? [-Werror=implicit-function-declaration]
 #define read_lock(lock)  _raw_read_lock(lock)

/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:158:2: note: in expansion of macro ‘read_lock’
  read_lock(&interrupt_data->eventfd_ctx_lock);

/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock.h:105:28: error: implicit declaration of function ‘_raw_read_unlock’; did you mean ‘do_raw_read_unlock’? [-Werror=implicit-function-declaration]
 #define read_unlock(lock)  _raw_read_unlock(lock)

/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:162:2: note: in expansion of macro ‘read_unlock’
  read_unlock(&interrupt_data->eventfd_ctx_lock);

In file included from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/spinlock_types.h:20,
                 from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/spinlock.h:82,
                 from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/wait.h:9,
                 from /usr/src/linux-headers-4.19.0-10-common-rt/include/linux/eventfd.h:13,
                 from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.h:11,
                 from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:4:
/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c: In function ‘gasket_interrupt_init’:
/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock_types_rt.h:39:1: error: expected expression before ‘{’ token
 {         \

/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock_types_rt.h:16:34: note: in expansion of macro ‘__RWLOCK_RT_INITIALIZER’
 #define __RW_LOCK_UNLOCKED(name) __RWLOCK_RT_INITIALIZER(name)

/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock.h:28:17: note: in expansion of macro ‘__RW_LOCK_UNLOCKED’
  do { *(lock) = __RW_LOCK_UNLOCKED(lock); } while (0)

/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:364:2: note: in expansion of macro ‘rwlock_init’
  rwlock_init(&interrupt_data->eventfd_ctx_lock);

In file included from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:12:
/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c: In function ‘gasket_interrupt_set_eventfd’:
/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock.h:83:11: error: implicit declaration of function ‘_raw_write_lock_irqsave’; did you mean ‘_raw_spin_lock_irqsave’? [-Werror=implicit-function-declaration]
   flags = _raw_write_lock_irqsave(lock); \

/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:529:2: note: in expansion of macro ‘write_lock_irqsave’
  write_lock_irqsave(&interrupt_data->eventfd_ctx_lock, flags);

/usr/src/linux-headers-4.19.0-10-common-rt/include/linux/rwlock.h:120:3: error: implicit declaration of function ‘_raw_write_unlock_irqrestore’; did you mean ‘_raw_spin_unlock_irqrestore’? [-Werror=implicit-function-declaration]
   _raw_write_unlock_irqrestore(lock, flags); \

/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:533:2: note: in expansion of macro ‘write_unlock_irqrestore’
  write_unlock_irqrestore(&interrupt_data->eventfd_ctx_lock, flags);

cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-4.19.0-10-common-rt/scripts/Makefile.build:308: /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o] Fehler 1
make[3]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[2]: *** [/usr/src/linux-headers-4.19.0-10-common-rt/Makefile:1545: _module_/var/lib/dkms/gasket/1.0/build] Fehler 2
make[1]: *** [Makefile:146: sub-make] Fehler 2
make: *** [Makefile:8: all] Fehler 2
make: Verzeichnis „/usr/src/linux-headers-4.19.0-10-rt-amd64“ wird verlassen

Installation is successful using linux-headers-amd64 instead of linux-headers-rt-amd64. 

Therefore my question, could be there support to include rt-amd as dependency

**Comment by Namburger** [comment]
Hello @mrdolmo sorry for my lack of knowledge here, but what is the difference between `rt-amd64` and the normal `amd64` package?
What happen if you try building your self?
```
# Download
$ apt download gasket-dkms
# Unpack
$ dpkg-deb -R gasket-dkms_1.0-13_all.deb gasket && cd gasket
# move source
$ sudo cp -r usr/src/gasket-1.0 /usr/src/gasket-dkms-1.0
# Build
$ sudo dkms add gasket-dkms/1.0 --kernelsourcedir=/usr/src/linux-headers--$(uname -r)
$ sudo dkms build gasket-dkms/1.0 --kernelsourcedir=/usr/src/linux-headers--$(uname -r)
$ sudo dkms install gasket-dkms/1.0 --kernelsourcedir=/usr/src/linux-headers--$(uname -r)
```

**Comment by mrdolmo** [comment]
Hello Namburger,

thank you very much for your fast response and your detailed instructions. I could build the module with my rt-kernel, rt stands for real time patch. We still need to evaluate proper funcion with hardware.

Additionally to your instructions I replaced following:
sed -i 's|#include <linux/rwlock.h>|#include <linux/rwlock_rt.h>|g' gasket/usr/src/gasket-1.0/gasket_interrupt.c

**Comment by Namburger** [comment]
@mrdolmo I see, so that looks like the issues is that the linux-headers-rt only supplies header files with the extra `rt`, where our code basically depends on the same file but not rt based. Thanks for your confirmation!

**Comment by mrdolmo** [comment]
Can confirm solution worked also with HW
