### ISSUE TITLE
error in coral::BuildEdgeTpuInterpreter 

### ISSUE THREAD

**Issue by vadim-SX** [google-coral/edgetpu#221]
Hi, I am trying to run my model:

[https://drive.google.com/drive/folders/1ubID-H0ctBLH0BZBTpg2uVCN9SK-vbcf?usp=sharing
](url)

and I get the next error in C++ :
Process finished with exit code 139
at
    std::unique_ptr<tflite::Interpreter> interpreter =
            coral::BuildEdgeTpuInterpreter(*model, edgetpu_context.get());

I don't get more info and don't know how to debug that.
any one have idea what can be the problem in the model?

`const std::string model_path = "/home/user/Downloads/yolov4-tiny-relu_edgetpu.tflite";

    // Read model.
    std::unique_ptr<tflite::FlatBufferModel> model =
            tflite::FlatBufferModel::BuildFromFile(model_path.c_str());
    if (model == nullptr) {
        std::cerr << "Fail to build FlatBufferModel from file: " << model_path
                  << std::endl;
        std::abort();
    }

    // Build interpreter.
    std::shared_ptr<edgetpu::EdgeTpuContext> edgetpu_context =
            edgetpu::EdgeTpuManager::GetSingleton()->OpenDevice();
    std::unique_ptr<tflite::Interpreter> interpreter =
            coral::BuildEdgeTpuInterpreter(*model, edgetpu_context.get());

    const auto& required_shape = coral::GetInputShape(*interpreter, 0);
`
it fails at
 
`  if (tflite::InterpreterBuilder(model, resolver)(&interpreter) != kTfLiteOk) 
`
at "model_utils.cc"

`
Edge TPU Compiler version 14.1.317412892
Input: yolov4-tiny-relu.tflite
Output: yolov4-tiny-relu_edgetpu.tflite

Operator                       Count      Status

PAD                            2          Mapped to Edge TPU
LOGISTIC                       2          Mapped to Edge TPU
ADD                            6          More than one subgraph is not supported
MAX_POOL_2D                    3          Mapped to Edge TPU
SPLIT_V                        12         Operation is working on an unsupported data type
QUANTIZE                       7          Mapped to Edge TPU
QUANTIZE                       19         Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       16         More than one subgraph is not supported
CONV_2D                        21         Mapped to Edge TPU
EXP                            6          Operation is working on an unsupported data type
CONCATENATION                  7          Mapped to Edge TPU
CONCATENATION                  2          More than one subgraph is not supported
SPLIT                          7          Mapped to Edge TPU
DEQUANTIZE                     14         Operation is working on an unsupported data type
RESIZE_BILINEAR                1          Mapped to Edge TPU
MUL                            18         More than one subgraph is not supported
SUB                            6          More than one subgraph is not supported
`

**Comment by Namburger** [comment]
Can you paste the full error or attach the model so I can try to run it?

**Comment by vadim-SX** [comment]
[yolov4-tiny-relu.zip](https://github.com/google-coral/edgetpu/files/5224675/yolov4-tiny-relu.zip)

**Comment by Namburger** [comment]
A few pieces of info is missing here for me do to further debug, would love to see if you registered the edgetpu ops with the resolver and the full error message when you ran the code. How ever I was able to create the interpreter with your model, here is the full code: 
```
int main(int argc, char* argv[]) {

  if (argc != 2) {
    std::cout << "Usage: main <model_path>\n";
    std::abort(); 
  } 

  const auto& tpus = edgetpu::EdgeTpuManager::GetSingleton()->EnumerateEdgeTpu();
  if (tpus.size() < 1) {
    std::cerr << "Can't find edgetpu\n";
    std::abort;
  }

  // Also list tpu devices
  std::shared_ptr<edgetpu::EdgeTpuContext> edgetpu_context =
      edgetpu::EdgeTpuManager::GetSingleton()->OpenDevice();

  size_t id{0};
  for (const auto& tpu : tpus) {
    std::cout << "tpu: " << id++ << "\ntype: " << tpu.type << "\npath: " << tpu.path << "\n";
  }

  // Build model.
  std::string model_path{argv[1]};
  std::cout << "Building model: " << model_path << "\n";
  std::unique_ptr<tflite::FlatBufferModel> model =
      tflite::FlatBufferModel::BuildFromFile(model_path.c_str());
  if (model == nullptr) {
    std::cerr << "Fail to build FlatBufferModel from file: " << model_path
              << std::endl;
    std::abort();
  }

  // Build interpreter.
  tflite::ops::builtin::BuiltinOpResolver resolver;
  resolver.AddCustom(edgetpu::kCustomOp, edgetpu::RegisterCustomOp());
  std::unique_ptr<tflite::Interpreter> interpreter;
  if (tflite::InterpreterBuilder(*model, resolver)(&interpreter) != kTfLiteOk) {
    std::cerr << "Failed to build interpreter." << std::endl;
  }
  std::cout << "Built interpreter success!" << "\n";

  // Bind given context with interpreter.
  interpreter->SetExternalContext(kTfLiteEdgeTpuContext, edgetpu_context.get());
  interpreter->SetNumThreads(1);
  if (interpreter->AllocateTensors() != kTfLiteOk) {
    std::cerr << "Failed to allocate tensors." << std::endl;
  }
  std::cout << "Tensors Allocated!" << "\n";
  return 0;
}
```

Cheers!

**Comment by vadim-SX** [comment]
I run you code and get next output:
/home/user/project/edgetpuinference/cmake-build-debug/edgetpuinference /home/user/Downloads/yolo4/yolov4-tiny-relu_edgetpu.tflite
tpu: 0
type: Apex (USB)
path: /sys/bus/usb/devices/2-2
Building model: /home/user/Downloads/yolo4/yolov4-tiny-relu_edgetpu.tflite

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by vadim-SX** [comment]
the lib I target is this one
libedgetpu//direct/k8/libedgetpu.so.1.0

**Comment by Namburger** [comment]
Humnn, that's odd, `SIGSEGV` is an ernno for bad memory access o_0
When you build `libtensorflow-lite.a`, was it from [this commit](https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5)? 
and can you share the `md5sum` of `libedgetpu//direct/k8/libedgetpu.so.1.0`?

**Comment by vadim-SX** [comment]
[k8.zip](https://github.com/google-coral/edgetpu/files/5225857/k8.zip)

**Comment by Namburger** [comment]
1) Can you also run this to make sure your linux user has permission for the `plugdev` group:
```
sudo usermod -aG plugdev $USER
```
2) Can you try running the model using my whole 
https://drive.google.com/file/d/18IO9d0glJwhkJh5zqftNuxRDM2_VVuzr/view?usp=sharing

**Comment by vadim-SX** [comment]
with your lib
it worked
can you tell me what commits you used at
edgetpu
and
tflite
thanks

**Comment by Namburger** [comment]
I believe I just used this: https://github.com/google-coral/libedgetpu/blob/master/bazel/WORKSPACE#L39
But there is a README in that should give the exact process (and the same commit I used):

1) make a directory to do everything
```
mkdir project && cd project
export PROJECT_DIR=$(pwd)
```

2) build libedgetpu
```
cd $PROJECT_DIR
git clone https://github.com/google-coral/libedgetpu && cd libedgetpu
make
```

3) Important, make a note of libedgetpu's tensorflow commit:
Example:
```
cat WORKSPACE| grep TENSORFLOW_COMMIT | head -n 1
TENSORFLOW_COMMIT = "f394a768719a55b5c351ed1ecab2ec6f16f99dd4";
```

4) build tensorflow using the same commit from step 2
```
cd $PROJECT_DIR
git clone https://github.com/tensorflow/tensorflow && cd tensorflow
git checkout f394a768719a55b5c351ed1ecab2ec6f16f99dd4
./tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/lite/tools/make/build_lib.sh
```

5) copy all libraries and include files
```
cd $PROJECT_DIR
mkdir $PROJECT_DIR/lib
cp $PROJECT_DIR/libedgetpu/out/direct/k8/* $PROJECT_DIR/lib
ln -s $PROJECT_DIR/lib/libedgetpu.so $PROJECT_DIR/lib/libedgetpu.so.1.0
cp $PROJECT_DIR/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/lib/* $PROJECT_DIR/lib
mkdir -p $PROJECT_DIR/include
cp $PROJECT_DIR/libedgetpu/tflite/public/* $PROJECT_DIR/include
cp -r $PROJECT_DIR/tensorflow/tensorflow/ $PROJECT_DIR/include
```

**Comment by Namburger** [comment]
I also saw that you are using cmake? 
Maybe this repo would be more relevant for your need: https://github.com/Namburger/edgetpu-minimal-example

Cheers

**Comment by vadim-SX** [comment]
I used your code and added the line:
  const auto& required_shape = coral::GetInputShape(*interpreter, 0);

and i get :Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by Namburger** [comment]
@vadim-SX more context?
Most likely a C++ pointer issue or even linker, try using gdb to debug, this is no longer related to edgetpu usage.
Suggestion: if you are just trying to get the input dimensions, this is working for me:
```
const auto* dims = interpreter->tensor(interpreter->inputs()[0])->dims;
std::vector<int> input_shape = {dims->data[0], dims->data[1], dims->data[2], dims->data[3]};
std::cout << "input shape: (" << input_shape[0] << "," << input_shape[1]
            << "," << input_shape[2] << "," << input_shape[3] << ")\n";
```

**Comment by vadim-SX** [comment]
@Namburger thanks for the big help.
I continued the work and now I get to 

at std::vector<float> RunInference
uint8_t* input = interpreter->typed_input_tensor<uint8_t>(0);

I get the input = NULL 
and then get SIGSEGV at the next line
std::memcpy(input, input_data.data(), input_data.size());

you have idea how can it be that the interpreter is build but the interpreter->typed_input_tensor<uint8_t>(0) is not?
thanks
