### ISSUE TITLE
Unable to install gasket-dkms

### ISSUE THREAD

**Issue by Harishrelysys** [google-coral/edgetpu#223]
I'm trying to install pcie drivers on my armv8 board which has yocto. I'm using Renesas G2M processor with 4.19 kernel. I installed dkms but now it is asking for linux-headers, which isn't there. Is there any other way to install gasket-dkms without apt-get ??

**Comment by Namburger** [comment]
@Harishrelysys the linux-hearders package is requires to do a dkms build. 
The source code is available here: https://coral.googlesource.com/linux-imx/+/refs/heads/release-day/drivers/staging/gasket
The only way I believe this could work is to add this to your kernel source and build but I'm not sure the exact procedure for this.
Keep in mind that currently we are only supporting debian: https://coral.ai/docs/m2/get-started#requirements

**Comment by Harishrelysys** [comment]
Hi Namburger,
              Thank you for the fast reply.We copied the source code from : https://coral.googlesource.com/linux-imx/+/refs/heads/release-day/drivers/staging/gasket and enabled the driver.We got /dev/apex_0 device.

But in dmesg we are getting error like

[    2.471002] apex 0000:01:00.0: Couldn't initialize interrupts: -22

Below is my pcie and apex log

dmesg | grep -i "pcie"
[    0.138955] rcar-pcie fe000000.pcie: host bridge /soc/pcie@fe000000 ranges:
[    0.138984] rcar-pcie fe000000.pcie:    IO 0xfe100000..0xfe1fffff -> 0x00000000
[    0.139001] rcar-pcie fe000000.pcie:   MEM 0xfe200000..0xfe3fffff -> 0xfe200000
[    0.139015] rcar-pcie fe000000.pcie:   MEM 0x30000000..0x37ffffff -> 0x30000000
[    0.139026] rcar-pcie fe000000.pcie:   MEM 0x38000000..0x3fffffff -> 0x38000000
[    0.153273] rcar-pcie fe000000.pcie: PCIe x1: link up
[    0.163424] rcar-pcie fe000000.pcie: Current link speed is 5 GT/s
[    0.163519] rcar-pcie fe000000.pcie: PCI host bridge to bus 0000:00
[    0.177358] pcieport 0000:00:00.0: enabling device (0000 -> 0002)
[    0.177447] pcieport 0000:00:00.0: Signaling PME with IRQ 220


dmesg | grep -i "apex"
[    2.462274] apex 0000:01:00.0: enabling device (0000 -> 0002)
[    2.468483] apex 0000:01:00.0: Couldn't initialize interrupts: -22

And also I have an sample application which works fine with usb coral tpu.But with pcie it is giving same initialize interrupts:-22 error.

Thanks and regards,
Harish

**Comment by Namburger** [comment]
Hey Harish - apologies for the issue, it seems that your CPU doesn't support MSI-X which is necessary for our pcie devices:
```
        Capabilities: [d0] MSI-X: Enable- Count=128 Masked-
```
I'll work with my team to get this documented

**Comment by Harishrelysys** [comment]
Hi Namburger,
                  Thanks for your inputs.Do you have any plan to support pcie with MSI interrupt in future.

Thanks and regards,
Harish

**Comment by Namburger** [comment]
@Harishrelysys unfortunately, we don't have a plan to support MSI on our side

**Comment by gavan-x** [comment]
> Hey Harish - apologies for the issue, it seems that your CPU doesn't support MSI-X which is necessary for our pcie devices:
> 
> ```
>         Capabilities: [d0] MSI-X: Enable- Count=128 Masked-
> ```
> 
> I'll work with my team to get this documented

@Namburger who is we? Are you part of the coral team? Could you elaborate on steps to take to verify if the Bananapi M4 supports MSI-X, unless you have a device in your lab. I can loop you in with Banana Pi’s team.

**Comment by Namburger** [comment]
@gavan1 with with coral team, our engs have a bananapi now but as I mentioned, msi-x is required at the moment for our gasket driver. It is now documented on the requirements part of our m.2 getting started page. There are on going work to make this possible but we are experiencing road blocks

**Comment by Namburger** [comment]
See here: https://github.com/google-coral/edgetpu/issues/280
