### ISSUE TITLE
different inference result in python and c++ edgetpu 

### ISSUE THREAD

**Issue by vadim-SX** [google-coral/edgetpu#224]
Hi,
I have done inference in both python and c++ 
and I see that the output is not the same.
I have saved the input to the inference from python as nparrray and loaded it to the cpp so the input is the same
but the output is not.
what can make this to happen?
is the input both python and cpp need to be the same or I need to make some process in the cpp?
thanks 

in cpp I used the minimal as starting point
the env on the python side

tensorboard | 2.3.0 | 2.3.0
-- | -- | --
tensorboard-plugin-wit | 1.7.0 | 1.7.0
tensorflow | 2.3.0 | 2.3.0
tensorflow-estimator | 2.3.0 | 2.3.0
termcolor | 1.1.0 | 1.1.0
tf | 1.12.1 | 1.0.0
tf-conversions | 1.12.1 |  
tf2-geometry-msgs | 0.6.5 |  
tf2-kdl | 0.6.5 |  
tf2-py | 0.6.5 |  
tf2-ros | 0.6.5 |  
tflite-runtime | 2.1.0.post1 |

**Comment by vadim-SX** [comment]
the main question is it right to enter the vector in c++ as the one in python?
i.e. if I load the input to edgetpu from python (that saves as numpy array) and pass it as is to the inference at cpp i shpuld get same result? or I need to do some changes? and if yes, what changes?
thanks

**Comment by vadim-SX** [comment]
I have just noticed that in python I use the tflite API vs the c++ that I use the edgetpu API is there a diffrence in the expected inputs?

**Comment by Namburger** [comment]
@vadim-SX If you are using our edgetpu c++ api, then the inputs should be a flat vector array. For instance, take a look at how we take an input from an image and feeding it to the interpreter here: https://github.com/google-coral/edgetpu/blob/master/src/cpp/examples/classify_image.cc#L26
You can see here to understand how we parse the outputs of the inference: https://github.com/google-coral/edgetpu/blob/master/src/cpp/basic/basic_engine_native.cc#L297

**Comment by vadim-SX** [comment]
thats what Im doing
```
  cv::Mat image=cv::imread(argv[2],CV_LOAD_IMAGE_UNCHANGED);
 std::vector<float> array;
  if (image.isContinuous()) {
    array.assign((float*)image.data, (float*)image.data + image.total()*image.channels());
  } else {
    for (int i = 0; i < image.rows; ++i) {
      array.insert(array.end(), image.ptr<float>(i), image.ptr<float>(i)+image.cols*image.channels());
    }
  }
```
and when I do break point at python and c++ I see that its the same input , but I see different output

**Comment by Namburger** [comment]
@vadim-SX are you sure the inputs for your model is float and not uint8? Also, doesn't the cv [image.data](https://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#a4d33bed1c850265370d2af0ff02e1564) returns a uchar*?
For example, this is how I set the inputs using opencv:
https://github.com/Namburger/edgetpu-detection-camera/blob/master/src/detection_camera.cc#L50-L55

**Comment by vadim-SX** [comment]
I doubt that's the issue;
the same input data taken from the Python version still doesn't work, so we can infer that it is not a preprocessing issue.

**Comment by Namburger** [comment]
I'm confused, I thought you were able to make this work with python?
More info on the model?

**Comment by vadim-SX** [comment]
I found the problem , I have done 
  std::memcpy(input, input_data.data(), input_data.size());
and that float so shpuld be
  std::memcpy(input, input_data.data(), input_data.size()*sizeof(float));

**Comment by Namburger** [comment]
@vadim-SX Ahh, yes, otherwise you're only feeding 1/4 of the pixels into the interpreter's input tensor :)

**Comment by awskhd** [comment]
@Namburger 
Hallo , 
i have done the inference on Coral board using c++ and Python and results say that inference time in C++ slower than Python , i find that is not true but i can not find the reasons for that, thanks very much
