### ISSUE TITLE
Didn't find op for builtin opcode 'RESHAPE' version '1'

### ISSUE THREAD

**Issue by LachlanDeGiorgio** [google-coral/edgetpu#226]
Hi, I'm trying to use the magic_wand example with my own gestures. The model builds and uploads fine however when I open the serial monitor I get the following error.

Didn't find op for builtin opcode 'RESHAPE' version '1'

Failed to get registration from op code d

If someone knows how to fix this it would be a HUGE help!

**Comment by Namburger** [comment]
Hello, could you give more info on the magic wand example?
