### ISSUE TITLE
Installing Mini PCIE EdgeTPU

### ISSUE THREAD

**Issue by Celt1967** [google-coral/edgetpu#232]
I have a Gigabyte Z370 Gaming 5 motherboard with Debian Buster 10 (AMD64).  I have used a wifi PCIE to Mini PCIE card to install the Mini PCIE EdgeTPU into the PCIE slot on my motherboard; but when i boot Debian the boot hangs with : 

"watchdog: BUG Soft lockup - CPU#2 stuck for 23s! [swapper/0:1]
rcu ; INFO: rcu_sched detected stalls on CPUs/tasks:
rcu: o2-....: (1024 ticks this GP) idle=c3a/1/0x4000000000000000 softirq=16/16 fqs=7279"

This repeats and the system never boots.  I have tried to Google the issue but i can seem to resolve the problem i have tried different PCIE slots, different Linux distros with the same results.

Windows seems to boot ok.

If anyone has any ideas that would be good as otherwise i have two mini PCIE EdgeTPU jsut sat here.

I have Debian on an I386 which does boot with the Mini PCIE EdgeTPU installed but i assume that being a 32bit system they will not work ?

Many thanks

Eifion

**Comment by Namburger** [comment]
Hi @Celt1967 
Could you share the outputs of these commands?
```
uname -a
lscpi -vvv
modinfo gasket
modinfo apex
```

**Comment by Celt1967** [comment]
uname -a gives:
Linux DESKTOP-K297L6M 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

The other commands are unknown.  I'm assuming they would not return anything of much help as i have to remove the PCIE card to allow Debian to boot and i have not installed the PCIE driver or apex.  I did on an earlier build with no changes.  The system would still hang with the soft lock bug.

**Comment by Namburger** [comment]
@Celt1967 oh, 
> i have not installed the PCIE driver or apex.

We do provide the apex/gasket driver to interact with our pcie card, so if you haven't installed anything, it may actually be the issue.

**Comment by Celt1967** [comment]
Though of that so i removed the card, installed the drivers etc as per the instructions and re-installed the card with the same effect ie. it hung with the soft lock.  I have installed the mini pcie card in my laptop which has a wifi mini pcie slot and it worked perfectly on Debian Buster.  I'm guessing its either an issue with my pcie slots on the motherboard (unlikely as everything else works e.g graphics card) or an issue with the adaptor cards i used to convert the mini pcie to pciex1.  I had assumed that they were just form factor changers but maybe not........I don't think its an issue with your hardware or software to be fair, just wondered if anyone had any ideas what could be the issue.  I'll keep digging.
PS on my laptop your commands yield:
Linux EF-LP 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
modinfo gasket
filename:       /lib/modules/4.19.0-8-amd64/updates/dkms/gasket.ko
author:         Rob Springer <rspringer@google.com>
license:        GPL v2
version:        1.1.3
description:    Google Gasket driver framework
srcversion:     5949A573FBF2024B08F577C
depends:        
retpoline:      Y
name:           gasket
vermagic:       4.19.0-8-amd64 SMP mod_unload modversions 
parm:           dma_bit_mask:int

modinfo apex
filename:       /lib/modules/4.19.0-8-amd64/updates/dkms/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.1
description:    Google Apex driver
srcversion:     3B3A1F9828855CB134088B2
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
retpoline:      Y
name:           apex
vermagic:       4.19.0-8-amd64 SMP mod_unload modversions 
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
parm:           trip_point0_temp:int
parm:           trip_point1_temp:int
parm:           trip_point2_temp:int
parm:           hw_temp_warn1:int
parm:           hw_temp_warn2:int
parm:           hw_temp_warn1_en:bool
parm:           hw_temp_warn2_en:bool
parm:           temp_poll_interval:int


Thank you

Eifion

**Comment by Celt1967** [comment]
Here is the card i bought to convert the Mini PCIE to PCIE X1:
https://www.amazon.co.uk/fenvi-Wireless-Network-Converter-Broadcom/dp/B01K4EASPI

**Comment by Namburger** [comment]
@Celt1967 Interesting, I don't think we've ever tested any adapter board, but I believe there were success stories. May I know what motherboard you are using? Just wanted to make sure the slot you use actually supports pcie and not just for wifi

**Comment by Celt1967** [comment]
Its a Gigabyte Z370 Gaming 5 motherboard, link:  https://www.gigabyte.com/uk/Motherboard/Z370-AORUS-Gaming-5-rev-10#kf
Its has three PCIE x1 slots and three full length slots.  I have removed my graphics card and tried the adaptor in each slot with the same results.  The interesting fact is that Windows 10 will boot and i can see the card with the right hardware id in device manager.
I should have just bought the M.2 version as i have two free slots and would not require an adaptor card.

**Comment by Namburger** [comment]
@Celt1967 I don't want to say that this is the case, I know we had success story in the past with it but I can't quite remember what adapter :/

**Comment by Celt1967** [comment]
@Namburger another update:  i had an old motherboard and CPU laying around so built a quick test rig and installed Debian Buster AMD64 and the adaptor cards work fine.  So on my Z370 motherboard with the same Debian build it will fail to boot at all.  I'm beginning to wonder if there is a setting in BIOS i could change or if there is some sort changes i need to make to the way Debian boots ?

**Comment by Namburger** [comment]
@Celt1967 I guess something we should look into is the full dmesg, could you attach that here?

**Comment by Celt1967** [comment]
@Namburger It does not create a dmesg log.  The boot stops on the flash screen that says loading ramdisk.....

**Comment by Namburger** [comment]
@Celt1967 wait I just realized that the answer you put here: https://github.com/google-coral/edgetpu/issues/232#issuecomment-707375405
Is for your laptop, we kind of need to know that your Desktop have the same apex/gasket driver

**Comment by Celt1967** [comment]
Hiya, below are the commands on my Desktop:

modinfo gasket
filename:       /lib/modules/4.19.0-12-amd64/updates/dkms/gasket.ko
author:         Rob Springer <rspringer@google.com>
license:        GPL v2
version:        1.1.3
description:    Google Gasket driver framework
srcversion:     EE63B2D1E7E5BEBAF51CEE1
depends:        
retpoline:      Y
name:           gasket
vermagic:       4.19.0-12-amd64 SMP mod_unload modversions 
parm:           dma_bit_mask:int

modinfo gasket
filename:       /lib/modules/4.19.0-12-amd64/updates/dkms/gasket.ko
author:         Rob Springer <rspringer@google.com>
license:        GPL v2
version:        1.1.3
description:    Google Gasket driver framework
srcversion:     EE63B2D1E7E5BEBAF51CEE1
depends:        
retpoline:      Y
name:           gasket
vermagic:       4.19.0-12-amd64 SMP mod_unload modversions 
parm:           dma_bit_mask:int
pi@DESKTOP-K297L6M:/sbin$ modinfo apex
filename:       /lib/modules/4.19.0-12-amd64/updates/dkms/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.1
description:    Google Apex driver
srcversion:     58E1862C107AD9271AA7ADA
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
retpoline:      Y
name:           apex
vermagic:       4.19.0-12-amd64 SMP mod_unload modversions 
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
parm:           trip_point0_temp:int
parm:           trip_point1_temp:int
parm:           trip_point2_temp:int
parm:           hw_temp_warn1:int
parm:           hw_temp_warn2:int
parm:           hw_temp_warn1_en:bool
parm:           hw_temp_warn2_en:bool
parm:           temp_poll_interval:int

**Comment by JoshuaABarnett** [comment]
Hi, 

I am also having issues with the Mini PCIE EdgeTPU and that same adapter in my setup. Maybe more information will help?

I have the mini PCIE accelerator plugged into an FV-101 mini PCIE to PCIE 1x adapter which is plugged into a PCIE x1 slot in my motherboard.  My motherboard is the Gigabyte Ultra Z390, my cpu is an i7-9700k @3.60Hz. The gpu is the Radeon Vega 56, the power supply is the CORSAIR RMX Series, RM850x, 850 Watt, 80+ Gold.  16 gb ram

When I plug the TPU into my motherboard and connect the power supply, the light indicating a cpu power error turns on and stays on.  The computer cycles on and off. The Bios Flash screen never comes up. Today, I have not been able to get past this point. Yesterday I was able to boot with the edge TPU into both Windows 10 and linux, which are on different hard drives. Both operating systems were able to recognize that the coral edge TPU was in the system. However, attempting to sleep or power off were not possible with the TPU in the system. They both led to the computer cycling on and off.

I have tried putting the TPU and adapter into different PCIE x1 slots but no change in behavior. I checked the cpu power cables are connected properly but no change. When I take out the TPU and adapter, my computer runs normally. The motherboard cpu indicator light, boot, sleep, restart, and power off issues go away.  When I have the adapter in without the TPU the motherboard's  cpu light turns on but goes away after a few seconds. The computer takes a little bit longer to get to the bios flash screen with the adapter in, but sleep, restart, and poweroff work normally. 

If you would like any more information about my system or output from running commands please let me know.

**Comment by Celt1967** [comment]
@Namburger Just a little more info:  Tried a different adaptor card with the same result.  Installed same Debian distro on a different motherboard and CPU etc and it works fine.  Works fine in my laptop with Debian 10.  Tried with just the adaptor card with no TPU and it works.  Placed a wireless Mini PCIE card, just as a test,  in the adaptor card and that works.  So the only combination that does nor work is GigaByte Z370 motherboard, EdgeTPU plus adaptor card (two tried) and Debian 10 with Kernel 4.19.0-12; but exactly the same system but dual booting ingto Windows10 and that works (so not hardware).  I have checked the dmesg and nothing there at all as it does not seem to boot to the point where it can dump the messages into a file.  Is there anything else i could try ?  Ohh yes i tried a Fedora LiveUSB stick with the same result is stopped at Loading Ramdisk.

**Comment by Namburger** [comment]
@Celt1967 I'm actually not sure as to what could happens and this is especially hard without dmesg :/

**Comment by Celt1967** [comment]
@Namburger Bit of a novice with all of this as you can probably tell, but is there a way to force Linux to provide more debug into at startup and its is loading the Ramdisk ?  If it reported to the terminal at least i could take a photo.

**Comment by Namburger** [comment]
@Celt1967 
When window booted, are you actually able to use the edgetpu or did it just boot?
A team mate asked if you would like to give [this card](https://www.amazon.com/Ableconn-PEX-MP117-Mini-PCI-Adapter/dp/B07JBCL1CJ) a try instead? The card you sent is only certified for wifi and we have success stories from the other card

**Comment by JoshuaABarnett** [comment]
@Namburger I got it working with the adapter you just posted, the Ableconn PEX-MP117 Mini PCI-E to PCI-E Adapter Card. Boot, sleep, restart etc work fine. I tested the edgetpu with the get started example and it worked. After following the setup instructions, I was able to get the reductions in inference time on the TPU for the test model. I am now convinced it was the adapter.

**Comment by Celt1967** [comment]
@Namburger that adaptor card is about $60, it would be cheaper to buy two more EdgeTPU that would fit my M.2 slots in my motherboard although i would be worried that they too may have an issue.  The adaptor card and EdgeTPU work in my other setup just not in my Z370 Debian setup so i'm assuming is some sort of setting either in the BIOS or the Kernel.  It all works fine in Windows10 and runs the example as well.

**Comment by martijndierckx** [comment]
Can anyone point me to a PCI-e x4 card that allows me to plug 4 mini PCI-e or M2 Coral TPUs?

**Comment by g30ba1** [comment]
Hi to all.

Has anyone tried to use an edgetpu (Different from the USB model, it is the one I own) with a Raspberry Pi?

I've been looking information/documentation about using the mini PCIe or M.2 variants with that little SBC.

I'm thinking on using the Raspberry's CM4 IO Board (Using its PCIe 2 Gen x1 socket) with the edgetpu mini PCIe accelerator, but I don´t know if that combination is possible.

**Comment by usbguru** [comment]
@g30ba1 
We have tested the CM4 with the edge TPU, and the CM4 does not provide MSI-X interrupt signaling.  That prevents the edge TPU from working.

@martijndierckx 
We have a couple of customers working on PCIe cards that will hold up to 8 or 16 edge TPUs in a single x16 PCIe slot.  Watch https://coral.ai/news for announcements when those products are for sale.

**Comment by Bomberski** [comment]
![Screenshot_20220819-020910_AliExpress](https://user-images.githubusercontent.com/51887282/186584149-e89528f6-539f-4133-ad37-2dc1be9d1ec9.jpg)

Tape works with this one...

**Comment by bazerned** [comment]
@Bomberski Can you confirm that what pin you have taped and why? Best I can tell, it is B side, Pin 8 (3.3v)

**Comment by StackOverBuffer** [comment]
You need to tape/cut pin B10 (3.3Vaux). Took me way to long to find [this](https://www.reddit.com/r/homeassistant/comments/vtckye/comment/ikpn42t/).

**Comment by bazerned** [comment]
@StackOverBuffer Perfect Thanks. Got it working!

**Comment by Leon-Sam** [comment]
I'd like to additionally confirm if you are using a mini PCI to PCIe adapter, with a Google Coral TPU Mini PCIe . It might boot loop. Meaning PSU repeatedly turns on then shuts off .

What is very odd. I installed the adapter a few months ago and it was completely fine. After disassembling my computer and reassembling it wont boot because of this. Taping Side B Pin 10 fixed the problem!

**Comment by DocSneider** [comment]
> You need to tape/cut pin B10 (3.3Vaux). Took me way to long to find [this](https://www.reddit.com/r/homeassistant/comments/vtckye/comment/ikpn42t/).

The same worked for me 👍🏻 

Any official reason for that, is it an issue caused by the adapter or by the coral pcb?

**Comment by AQUOSTICS** [comment]
I blocked B10 and my system managed to boot. But it seems like I was not able to detect that PCIe device at all. I installed the driver and rebooted, but `lspci -nn | grep 089a` showed nothing.
