### ISSUE TITLE
Error: device wlan0 is not a wifi device

### ISSUE THREAD

**Issue by kavinkumar912000** [google-coral/edgetpu#233]
Problem : I have 2 Coral Dev Boards . I followed the Installation Procedure and successfully setup Coral Dev Board .  I could connect through the WiFi interface (wlan0) and everything was going ok .Then suddenly wlan0 disappears from the ifconfig(in fact, ifconfig only displays eth0 and lo). Moreover, Ifconfig wlan0 up returns that there's no such device. I decided to reflash the os. But, I got the same problem again.

Then I started using another board. Initially the WIFI Worked and After some days, the same wifi problem occured in that board too. I was not able to connect wifi to both the boards.

Options I have Tried 
I use a Branded Power Adapter  ( 5 V 2.1 A ) and the Type C Cable, these adapter and cable are the same one i use for my smartphone. 
I have Tried Reinstalling the OS and i experienced the same Wifi Issue 

Does anyone experience the same?
or Is there any problem in hardware?

**Comment by Namburger** [comment]
Hello, this seems like a HW issue, I saw that you've already submit an issue in our email, will response to you there

**Comment by kavinkumar912000** [comment]
will i use this below mentioned wifi adapter to solve this problem?
[https://www.amazon.in/TP-Link-TL-WN725N-150Mbps-Wireless-Adapter/dp/B008IFXQFU](url)

**Comment by Namburger** [comment]
@kavinkumar912000 I think the issue is with the dev board and that should be address, I've responded to you email, did you get it?

**Comment by bhachauk** [comment]
One of my friend facing the same issue... Is any thing found to fix this ?

**Comment by Namburger** [comment]
@Bhanuchander210 can you send us an issue to coral-support@google.com?

**Comment by bhachauk** [comment]
@Namburger Thanks. That issue was resolved after flash. Due to other issues, we ran `mdt reboot-bootloader`.

**Comment by ajbolt69** [comment]
@bhachauk I was facing wifi issues on the coraldevboard as well , what exactly does the reboot -bootloader command do?

**Comment by bhachauk** [comment]
@ajbolt69 I done that few years ago.. i am not fully sure :(
