### ISSUE TITLE
Can not connect to mdt and ssh. Not visible on fastboot.

### ISSUE THREAD

**Issue by JamilHaidar** [google-coral/edgetpu#234]
I have been using the Google Coral Devboard in a project for a while.
Today, I am surprised to see that using ssh does not work. Something went wrong somewhere.
ssh mendel@192.168.0.111 gives
ssh: connect to host 192.168.0.111 port 22: Connection refused

I have checked the authorized_keys file and my own private keys and they match.

I can only connect to the devboard using Serial communication.
I wish to reflash the entire thing and reset the board. However, after using "sudo reboot-bootloader", "fastboot devices" sees nothing. I have tried 4 USB C cables. I have tried using "fastboot 0" from the Serial console immediately instead of letting the board boot up. Nothing shows up.

**Comment by Namburger** [comment]
@JamilHaidar That' odd, it maybe because the board disconnection from the network.
For the ssh/mdt issue, can you share this outputs:
```
$ nmcli connection show
```
Regarding fastboot issue, what if you try to initiate fastboot with an [sdcard like this](https://coral.ai/docs/dev-board/reflash/#flash-from-u-boot-on-an-sd-card)?

**Comment by JamilHaidar** [comment]
It would seem like the issue was simply a connection problem. I fixed it and re-flashed the google coral. One note of advice, do not try Windows, it's not worth the hassle of getting all drivers and connections set up. Instead, just run a bootable Linux image and do all initial setup there. Switch to Windows and append your ssh key to gain access.

**Comment by Namburger** [comment]
LOL yes, we do not recommend window, glad you fixed it!
