### ISSUE TITLE
Cannot Access Latest Mendel 5.0 Serial Console 

### ISSUE THREAD

**Issue by JamilHaidar** [google-coral/edgetpu#235]
After following the Google Devboard Getting started guide, I finally flashed the devboard with the latest enterprise-eagle-20200724205123 Mendel 5.0 OS. However, when accessing it from the console, I get this:
```
Cannot open access to console, the root account is locked.
See sulogin(8) man page for more details.
```
`mdt devices` does not recognize the board too.
How do I fix this?

**Comment by Namburger** [comment]
@JamilHaidar Looks like something went wrong during flash, could you try reflashing it again? with [these instructions](https://coral.ai/docs/dev-board/reflash/#flash-a-new-system-image)?

**Comment by JamilHaidar** [comment]
@Namburger I tried that and still got the same issue. I downgraded to Mendel 4.0 and that fixed it. Not really sure why that happened.

**Comment by PRK56249** [comment]
Same issue for me with enterprise-eagle:

Cannot open access to console, the root account is locked.
See sulogin(8) man page for more details.

**Comment by bogdannedelcu** [comment]
I had the same issue, orange led not turning green. 
I connected trough the serial pins, poweroff/poweron. Waited for the "Press enter" message and login with mendel. Then updated the board with

sudo apt-get update
sudo apt-get dist-upgrade
sudo reboot now

Board works fine after that.
