### ISSUE TITLE
Provide Schematic for Environmental Sensor Board

### ISSUE THREAD

**Issue by tbec** [google-coral/edgetpu#236]
Is the actual schematic for the [Coral Environmental Sensor Board](https://coral.ai/docs/enviro-board/datasheet/) available to download? I would like more specific information than what is listed on the site.

**Comment by Namburger** [comment]
@tbec Unfortunately the schematic for it is not available, are there any details that you'd like to have added?

**Comment by tbec** [comment]
I apologize for not responding earlier. Can you elaborate on the ADC? It is not explained in the datasheet.

**Comment by usbguru** [comment]
Hi Tom,
We are using the TLA2021IRUGT ADC.

https://www.ti.com/store/ti/en/p/product/?p=TLA2021IRUGT

What information are you looking for?

**Comment by tbec** [comment]
I was just looking for the name of the ADC, as I do not see it listed in the datasheet. Can this info be added to the datasheet? Would you like me to open a new issue?

**Comment by usbguru** [comment]
Thanks.

That is a good suggestion.   I will pass it along to our documentation team.
