### ISSUE TITLE
Compiler complains 'Model not quantized' on quantization-aware trained models

### ISSUE THREAD

**Issue by fandahao17** [google-coral/edgetpu#238]
Hi, there!

I'm trying to port MobileBERT to EdgeTPU. It's 26MB after quantization (originally 96MB), so I guess I may be able to run it on 4~5 EdgeTPUs. However, the `edgetpu_compiler` reports `Model not quantized` on my quantized model.

This is how I converted the model:

``` python
converter = tf.lite.TFLiteConverter.from_saved_model('.')
converter.optimizations = [tf.lite.Optimize.DEFAULT]

quantized_tflite_model = converter.convert()
open('model.tflite', 'wb')
```

I downloaded the model [here](https://github.com/google-research/google-research/tree/master/mobilebert#pre-trained-checkpoints). Since the model contains `FakeQuant` ops, I guess it's trained using quantization-aware training.

BTW, do you think it's possible to run BERT models on EdgeTPUs? I'm afraid it may contain some unspported ops.

Thanks!

**Comment by Namburger** [comment]
@fandahao17 
I don't know too much about mobilebert (or bert) so I can't immediately tell if it would be fully supports, unfortunately.
Also, I guess the FakeQuant does indicates quant aware training but I still see int32 and float ops, could you give post training quantization a go?

**Comment by fandahao17** [comment]
Thanks for your rapid reply!

I inspected the converted .tflite file and found that it indeed isn't fully quantized. Thus, I guess it's a MobileBERT or tflite issue. Thanks!
