### ISSUE TITLE
How to run several m2/pcie TPU modules in parallel

### ISSUE THREAD

**Issue by alexanderfrey** [google-coral/edgetpu#239]
Hi, 

I'm facing the problem to run 3 models on 3 different m2/pcie TPU modules. I'm loading the models with the tflite api:

`Interpreter(model_path=model_path,
                                            experimental_delegates=[load_delegate('libedgetpu.so.1.0', {})])`

The question I have is how can I specify the m2 module for each model ? With the usb TPU dongle I have the option to pass this string `{"device": "usb:0"}` but I can not find any documentation for the m2 modules.

Any help is very much appreciated.

Thanks,
Alexander

**Comment by alexanderfrey** [comment]
Found the answer here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api

**Comment by Namburger** [comment]
yep! For future reference for others:
`{"devide":"apex:0"}`
