### ISSUE TITLE
Operation Not Supported: TRANSPOSE

### ISSUE THREAD

**Issue by ofeknesher2** [google-coral/edgetpu#242]
after converting a custom model from Pytorch to tflite ( Pytorch -> ONNX -> savedModel -> tflite).
the converter added transpose nodes to overcome nhwc only support and now when compiling the tflite with edge tpu compiler 14, the compiler stop mapping to tpu after the first transpose (which is after the input node) due to Unsupported operation,
 
Edge TPU Compiler version 14.1.317412892
.
.
.
Operator                       Count      Status
TRANSPOSE                      42         Operation not supported

**Comment by Namburger** [comment]
Let's keep track of this via https://github.com/google-coral/edgetpu/issues/193
