### ISSUE TITLE
Running co-compiled models on one USB TPU

### ISSUE THREAD

**Issue by alexanderfrey** [google-coral/edgetpu#243]
Hi,

maybe I am not seeing the obvious but nowhere in the doc for co-compiling it is stated on how to run those n models on the same TPU, or is it ?

https://coral.ai/docs/edgetpu/compiler/#co-compiling-multiple-models
https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api

The thing is that I tried to specify the same device for both models like this:

`interpreter_1 = Interpreter(model_1_path,`
  `experimental_delegates=[load_delegate('libedgetpu.so.1', {"device": "usb:0"})])`

`interpreter_2 = Interpreter(model_2_path,`
 ` experimental_delegates=[load_delegate('libedgetpu.so.1', {"device": "usb:0"})])`

But it is failing. Should I leave out the whole device string part ?

Any help much appreciated.
Alexander

**Comment by Namburger** [comment]
@alexanderfrey it really should works, does it fails with some error messages? Although if you;re just using the same tpu, there isn't a need to specify the `{"device": "usb:0"}` part. Here is how I'd do it on my dev board:
```
import tflite_runtime.interpreter as tflite
import numpy as np

model_1_path = 'mobilenet_v2_1.0_224_quant_edgetpu.tflite' 
model_2_path = 'ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite' 

interpreter_1 = tflite.Interpreter(model_1_path,
  experimental_delegates=[tflite.load_delegate('libedgetpu.so.1', {"device": "pci:0"})])
interpreter_2 = tflite.Interpreter(model_2_path,
        experimental_delegates=[tflite.load_delegate('libedgetpu.so.1', {"device": "pci:0"})])

def set_random_inputs(interpreter):
  input_details = interpreter.get_input_details() 
  image = np.random.random(input_details[0]['shape']).astype(input_details[0]['dtype'])
  interpreter.set_tensor(input_details[0]['index'], image)

interpreter_1.allocate_tensors()
interpreter_2.allocate_tensors()

for i in range(10):
    set_random_inputs(interpreter_1)
    interpreter_1.invoke()
    set_random_inputs(interpreter_2)
    interpreter_1.invoke()
```

**Comment by alexanderfrey** [comment]
Thanks a lot - yes leaving out the device part seems to do the trick. 

Best,Alexander

ps Really looking forward to the new software release and any updates in general !!

**Comment by Namburger** [comment]
Expect it next week or week after :)
There's going to be quite changes, particularly you'll get to use a newer version of tensorflow, which I feel would benefits many.
