### ISSUE TITLE
Size problem after model quantification

### ISSUE THREAD

**Issue by LINYOUWEI0804** [google-coral/edgetpu#245]
I used keras to train a cat and dog identification model. The size of the cat and dog identification model was 80.0Mb. Then I used tensorflow Post-training integer quantization to quantize to INT8. The model size was 8.2MB. Finally, it was compiled into edgetpu.

Excuse me, if float32 is quantized to INT8, it should be reduced to 1/4, but mine is reduced to 1/10. What is the reason for this?

My model: https://drive.google.com/drive/folders/1Qqxt42sCA0c6gLI8zr_QXJUtOXypBc69?usp=sharing

**Comment by Namburger** [comment]
@LINYOUWEI0804 I believe there's more in quantization than just the size of the tensors. Particularly, the format of the file goes from `model.pb` which is a protocol buffer to `.tflite` which is a flatbuffer format. 
I wouldn't expect this to be a real issue unless you are actually spotting something. 
Anyhow, our team only works with the edgetpu API and compiler, so I would open issue at [tensorflow/issues](https://github.com/tensorflow/tensorflow/issues) for more appropriate answer
