### ISSUE TITLE
Fastboot cannot find devices.

### ISSUE THREAD

**Issue by jolloqui** [google-coral/edgetpu#247]
I am following the dev-board installation manual and I am not able to see the device in fastboot devices. I have tried with five different USB C cables, with various versions of fastboot (now I have 30.0.5). I have two Coral dev-board boards and it only happens to me on one. What can I do?

**Comment by manoj7410** [comment]
@jolloqui Which operating system are you working with and which version ?

**Comment by jolloqui** [comment]
On the host I have Ubuntu 20.04.

**Comment by Namburger** [comment]
@jolloqui Could you try reflashing the board again using the sdcard method?
https://coral.ai/docs/dev-board/reflash/#flash-from-u-boot-on-an-sd-card

**Comment by jolloqui** [comment]
Yes, I have tried it, but when launching "fastboot devices" it still comes out empty.

**Comment by Namburger** [comment]
@jolloqui humm
Can you share the outputs of `lsusb` on the dev board?
Also, one thing to try, instead of `mdt reboot-bootloader` could you try connecting to the board over serial console using the `screen /dev/ttyUSB[board-id]` and then reboot the board, within the first few seconds, tap any keys to enter uboot and then type "fastboot 0"

**Comment by jolloqui** [comment]
Hi, sorry about the delay but I haven't been able to try before.

I don't know how to run "lsusb" in u-boot since it is the only way I can connect to the dev-board.
From the host computer with the serial connected the output is:

usuario@HP:~$ lsusb
**Bus 002 Device 004: ID 10c4:ea70 Silicon Labs CP2105 Dual UART Bridge**
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 046d:c517 Logitech, Inc. LX710 Cordless Desktop Laser
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

From the host computer with the data port connected the output is:
usuario@HP:~$ lsusb
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 046d:c517 Logitech, Inc. LX710 Cordless Desktop Laser
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

As you can see it does not recognize any data USB.

I am not able to execute any "mdt" command since it cannot find the devices.

Thanks a lot

**Comment by Namburger** [comment]
@jolloqui sorry, I mean over serial, not u-boot:
```
$ screen /dev/ttyUSB{id}
```
Then turn on the dev board and it should boot & ask you for a username/password, which will both be "mendel".
Then you can run:
```
$ sudo apt install usbutils
$ lsusb
```

I suspect that somehow the board's usb port is having issues which is causing your host to not being able to see it as a fastboot device. Here is what a normal lsusb should looks like:
```
mendel@red-finch:~$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by jolloqui** [comment]
Hi @Namburger,

As you have indicated, I have started from the serial port with screem but when I start I get these characters. I do not know if it's normal.
![init_serial_characters](https://user-images.githubusercontent.com/6246664/98919772-8699f900-24cf-11eb-8545-564ee6629b51.png)

Once I have installed "usbutils" I get the following lines with "lsusb". Everything seems fine:
![lsusb](https://user-images.githubusercontent.com/6246664/98919806-90bbf780-24cf-11eb-9d87-2a7188fe8f03.png)

thank you!

**Comment by jolloqui** [comment]
Sorry I was wrong, I have tried with the dev-board that the installation worked for me and it already has mendel.
With the one that I don't have installed mendel doesn't start me on the serial port. I get a series of strange characters but there is no login.
![Captura de pantalla de 2020-11-12 11-52-48](https://user-images.githubusercontent.com/6246664/98931135-ef886d80-24dd-11eb-94e7-dfc1b368c29e.png)


I feel the mistake

**Comment by Namburger** [comment]
@jolloqui 
Sorry, the reason why you are getting garbage characters is because screen doesn't know what bitrate is being transferred, I forgot to mentioned:
```
screen /dev/ttyUSB{id} 115200
```

**Comment by jolloqui** [comment]
@Namburger 
Excuse my ignorance, I didn't know what the bitrate number was for.
I have a question, can a board on which a linux mendel has never been installed can show a mendel login from the screem console?
In which I managed to install it, I login without problem but in the other one u-boot it always runs.
There seems to be a problem with the USB but I don't know how to check it.

Thank you very much

**Comment by Namburger** [comment]
@jolloqui actually, I think I mis-understood the problem from the beginning, I thought you were trying to reflash a board without success, but it looks like one of the board just doesn't go into fastboot mode at all (and I suspect that is due to a faulty usb-c port).
To answer your question, if mendel haven't been installed,  you wouldn't be able to get a login screen, since u-boot is the only thing installed. Sorry for all of the confusion. The fact that you had one of the board flashed correctly and the second one just doesn't works tells me that there may be a HW issue. Could you shoot us an email to coral-support@google.com, we can issue you a replacement, sorry again for this

**Comment by jolloqui** [comment]
Don't worry, I don't think I have explained myself very well either.
I really appreciate your work.
I will write to the support email.
A greeting.

**Comment by Namburger** [comment]
@usbguru for awareness, expect an email from @jolloqui!
