### ISSUE TITLE
Convert Tensorflow model to TFLite model - problem with boxes after quantization

### ISSUE THREAD

**Issue by Rariusz** [google-coral/edgetpu#248]
Since this is my first post, congratulations on the project! Good job ! I have seen in the repository that there are many tensorflow models available for the coral device. I assume the authors are experts in this field. I want to covert tensorflow to TFLite. After a few tries and help, I got to the point where I do discretization, but I have a problem with boxes. Everything is described here https://github.com/tensorflow/tensorflow/issues/44610 I hope someone will be able to help me

**Comment by Namburger** [comment]
@Rariusz ahh, we actually do have issues with accuracy from the OD API with tensorflow2.x, we are actively working on this currently. I suggest that you check out the tensorflow 1.x OD API for now.
@Naveen-Dodda maybe you have some more info on the tf2.x OD API integration?

**Comment by Namburger** [comment]
@Rariusz Just took a look at your config, I'm not sure if tf2.x supports quantization aware training for OD yet, but could you try adding this to the config?
```
graph_rewriter {
  quantization {
    delay: 0
    weight_bits: 8
    activation_bits: 8
  }
}
```
With this you won't need to perform post training quantization.
tagging @usbguru as it is a good one for you to follow :)

[EDIT] ahh, scratch that, it looks like you are just quantizing an existing model as opposed to retraining it

**Comment by Rariusz** [comment]
@Namburger Thank you for your answer!!!. I am retraining it but for now, I want to prepare the code based on the ready model. I am trying to train the model, do conversions for almost two months. There is a lot of models in the repository after discretization. How was it done? I try and try and try and every time there is a problem with something. As you can see in my post on tensorflow, I am close to solving the problem, but it is a problem with boxes. I saw that there are no such problems on tensorflow 1.15

**Comment by Namburger** [comment]
@Rariusz I have here an end to end pipeline colab that may help as it gives you the exact steps: https://github.com/Namburger/edgetpu-ssdlite-mobiledet-retrain

**Comment by Rariusz** [comment]
@Namburger  I add 
```
graph_rewriter {
  quantization {
    delay: 0
    weight_bits: 8
    activation_bits: 8
  }
}
```
to config and we will see. Then I wil try Tensorflow 1.15. However, it is a bit strange that such a problem is with boxes after quantization

**Comment by Namburger** [comment]
@Rariusz with that config added, the training will be aware of quantization, meaning you won't need to quantized the model again after it is done training so your tflite model may get very similar outputs from your graph model. 

> it is a bit strange that such a problem is with boxes after quantization

Yes, it is. But as I mentioned, we are aware that there are issues with tf2.x and this is one of the issues that we are trying to tackle.

**Comment by Rariusz** [comment]
@Namburger  Thank you for the information. So far I can see that the loss is very big compared to the float model. For float model loss is 0.2. With quantization settings is 32. Interesting. I will wait until training is over and see the results.

Some time ago I worked with this repository https://github.com/guichristmann/edge-tpu-tiny-yolo?fbclid=IwAR0-OrnFUL-k9xXbTieLb4sJr3YS3xIdeLyfxGlaYWJu1rheyQoCUaM5iD4 I had the same problem with boxes. This was a reason why I start to work with Tensorflow.  So at this point it seems to me that the problem is with the new version of Tensorflow is:

> **Note**: The quantization of the RESIZE_NEAREST_NEIGHBOR op is only supported in Tensorflow 2.0 nightly packages as of now, so you need use that version for thconversion.

Maybe it will be helpful.

**Comment by Rariusz** [comment]
@Namburger I I trained the model according to your settings. The accuracy is not the same as during normal training, but this is due to the fact that I have little memory in the graphics card and the size of the bach is set to 5. I made a graph export
```
!python object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path "/content/ex_my_ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/pipeline.config" \
    --trained_checkpoint_dir "/content/ex_my_ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint"\
    --output_directory "/content/tflite_graph_ec"
```
and I convert the model to TFLite. The sie of model is 53MB and the accuracy is 0. It means that after fun detector there is no any boxes on the image. Moreover, the execution of detector is very very slow.

**Comment by Namburger** [comment]
@Rariusz sorry, I thought you followed my repo and stick with tf1.x,  as I mentioned we *know* about issues with tf2.x OD API and we are working on it. I don't have much progresses on it though
@Naveen-Dodda maybe you have more info on this one?

**Comment by Rariusz** [comment]
@Namburger I will follow tf1.x thank you for your help !! but now I try to run yolo model on google coral because I have models for my custom data set but I hev new problems.

**Comment by keesschollaart81** [comment]
@Namburger are these issues with TF2.x OD towards edgetpu tracked/documented somewhere?

**Comment by Rariusz** [comment]
@Namburger I follow you advice about tensorflow 1.x but now every time in the second iteration tensorflow return
```
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```
```
INFO:tensorflow:loss = 53.148666, step = 1
I1108 18:32:40.136973 140007662208832 basic_session_run_hooks.py:262] loss = 53.148666, step = 1
ERROR:tensorflow:Model diverged with loss = NaN.
E1108 18:33:17.851991 140007662208832 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
Traceback (most recent call last):
  File "model_main.py", line 108, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main.py", line 104, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1426, in run
    run_metadata=run_metadata))
  File "/home/ubuntu/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_core/python/training/basic_session_run_hooks.py", line 761, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```

**Comment by bartezz32** [comment]
@Rariusz Maybe there will be something useful [stackoverflow - Tensorflow NaN bug?](https://stackoverflow.com/questions/33712178/tensorflow-nan-bug/33713196#33713196)

**Comment by Naveen-Dodda** [comment]
Hello Rariusz, 

Are you able find a solution ?

**Comment by Rariusz** [comment]
@Naveen-Dodda No. I'm waiting for help and I try many combination. I has tried different approaches so far to no solution.

**Comment by Rariusz** [comment]
@Naveen-Dodda for now I increase the bach size and the problem is solved. But now I see that tensorflow 1.15 do not see GPU.

**Comment by Namburger** [comment]
@Rariusz you are running into a lot of system configuring issues, this isn't a bug. 
Different nvidia drivers is going to want different cudnn and it also depends on your OS, it's just not feasible for us to try trouble shoot this if it isn't our system. I suggest that you look up guides on how to install drivers and specifically for your system

**Comment by Rariusz** [comment]
@Namburger Thank you for your reply and sorry to bring up so many problems on one topic. I created a new virtual environment in conda and installed tensorflow-gpu == 1.15 and now the system can see the GPU. Currently, these are my training results:

```
Accumulating evaluation results...
DONE (t=0.23s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.018
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.021
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.021
INFO:tensorflow:Finished evaluation at 2020-11-10-15:44:16
I1110 15:44:16.615526 139870344779584 evaluation.py:275] Finished evaluation at 2020-11-10-15:44:16
INFO:tensorflow:Saving dict for global step 20079: DetectionBoxes_Precision/mAP = 0.0005632294, DetectionBoxes_Precision/mAP (large) = 0.00063241745, DetectionBoxes_Precision/mAP (medium) = 0.0, DetectionBoxes_Precision/mAP (small) = -1.0, DetectionBoxes_Precision/mAP@.50IOU = 0.002614157, DetectionBoxes_Precision/mAP@.75IOU = 3.612803e-05, DetectionBoxes_Recall/AR@1 = 0.0029432534, DetectionBoxes_Recall/AR@10 = 0.018439654, DetectionBoxes_Recall/AR@100 = 0.020597206, DetectionBoxes_Recall/AR@100 (large) = 0.020803029, DetectionBoxes_Recall/AR@100 (medium) = 0.0, DetectionBoxes_Recall/AR@100 (small) = -1.0, Loss/classification_loss = 2.1824276, Loss/localization_loss = 0.9238472, Loss/regularization_loss = 0.39788055, Loss/total_loss = 3.5041559, global_step = 20079, learning_rate = 0.7959339, loss = 3.5041559
I1110 15:44:16.615794 139870344779584 estimator.py:2049] Saving dict for global step 20079: DetectionBoxes_Precision/mAP = 0.0005632294, DetectionBoxes_Precision/mAP (large) = 0.00063241745, DetectionBoxes_Precision/mAP (medium) = 0.0, DetectionBoxes_Precision/mAP (small) = -1.0, DetectionBoxes_Precision/mAP@.50IOU = 0.002614157, DetectionBoxes_Precision/mAP@.75IOU = 3.612803e-05, DetectionBoxes_Recall/AR@1 = 0.0029432534, DetectionBoxes_Recall/AR@10 = 0.018439654, DetectionBoxes_Recall/AR@100 = 0.020597206, DetectionBoxes_Recall/AR@100 (large) = 0.020803029, DetectionBoxes_Recall/AR@100 (medium) = 0.0, DetectionBoxes_Recall/AR@100 (small) = -1.0, Loss/classification_loss = 2.1824276, Loss/localization_loss = 0.9238472, Loss/regularization_loss = 0.39788055, Loss/total_loss = 3.5041559, global_step = 20079, learning_rate = 0.7959339, loss = 3.5041559
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 20079: /tmp/tmpexgmzo1y/model.ckpt-20079
I1110 15:44:16.626856 139870344779584 estimator.py:2109] Saving 'checkpoint_path' summary for global step 20079: /tmp/tmpexgmzo1y/model.ckpt-20079
INFO:tensorflow:global_step/sec: 0.795129
I1110 15:44:28.857791 139870344779584 basic_session_run_hooks.py:692] global_step/sec: 0.795129
INFO:tensorflow:loss = 2.7421985, step = 20100 (125.766 sec)
I1110 15:44:28.859037 139870344779584 basic_session_run_hooks.py:260] loss = 2.7421985, step = 20100 (125.766 sec)
INFO:tensorflow:global_step/sec: 1.81966
I1110 15:45:23.813068 139870344779584 basic_session_run_hooks.py:692] global_step/sec: 1.81966
INFO:tensorflow:loss = 2.258185, step = 20200 (54.955 sec)
I1110 15:45:23.814354 139870344779584 basic_session_run_hooks.py:260] loss = 2.258185, step = 20200 (54.955 sec)
INFO:tensorflow:global_step/sec: 1.8216
I1110 15:46:18.709859 139870344779584 basic_session_run_hooks.py:692] global_step/sec: 1.8216
INFO:tensorflow:loss = 2.7436376, step = 20300 (54.897 sec)
I1110 15:46:18.710979 139870344779584 basic_session_run_hooks.py:260] loss = 2.7436376, step = 20300 (54.897 sec)
INFO:tensorflow:global_step/sec: 1.82342
I1110 15:47:13.551955 139870344779584 basic_session_run_hooks.py:692] global_step/sec: 1.82342
INFO:tensorflow:loss = 2.5829315, step = 20400 (54.842 sec)
I1110 15:47:13.553134 139870344779584 basic_session_run_hooks.py:260] loss = 2.5829315, step = 20400 (54.842 sec)
INFO:tensorflow:global_step/sec: 1.82512
I1110 15:48:08.342860 139870344779584 basic_session_run_hooks.py:692] global_step/sec: 1.82512
INFO:tensorflow:loss = 2.344097, step = 20500 (54.791 sec)
I1110 15:48:08.344019 139870344779584 basic_session_run_hooks.py:260] loss = 2.344097, step = 20500 (54.791 sec)
```
step is set to 400000. What do you think about these results at this moment?
