### ISSUE TITLE
Better Notice for Breaking Changes

### ISSUE THREAD

**Issue by gdj0nes** [google-coral/edgetpu#249]
I might not be going to the right place for information regarding deprecation and new releases but it was concerning to have all of my builds suddenly failing last night without notice because of the latest library changes.

**Comment by usbguru** [comment]
Hi Gareth,
What specifically broke?  Which hardware?  Are any of the public examples breaking for you?

**Comment by gdj0nes** [comment]
We had issues with debian package installation due to changes in `libedgetpu1-std` and `python3-edgetpu`

**Comment by Namburger** [comment]
@gdj0nes Apologies, here is the release, we just deprecated `python3-edgetpu` in favor of pycoral and libcoral. Although python3-edgetpu should still works if you didn't update `libedgetpu`. Our long term goal is to eventually continuous integration with better way to communicates about releases.

**Comment by gdj0nes** [comment]
I'm a little confused about the versioning with tflite-runtime too. How does a tflite-runtime release relate to the underlying Tensorflow version the model was created with. We've seen how important this given issues with Bilinear size operation between 2.2 and 2.3.

**Comment by Namburger** [comment]
@gdj0nes It is because `libedgetpu.so` depends on tensorflow, so we don't want to have users using a `tflite_runtime` version that was build on a different commits than `libedgetpu` which can have code changes that causes undefined behaviors

**Comment by gdj0nes** [comment]
Ok so the `libedgetpu.so`  and `tflite-runtime` are both built on which tensorflow version? The naming would imply version `2.5.0`

**Comment by Namburger** [comment]
@gdj0nes this commit: https://github.com/google-coral/libcoral/blob/master/WORKSPACE#L18

**Comment by gdj0nes** [comment]
So should be developing models by building off specific tf commits and not stable releases?

**Comment by Namburger** [comment]
You should be able to develop models on the latest release on most cases, however there maybe features missing on our runtime in some rare instances :/

**Comment by gdj0nes** [comment]
I feel like a lot of this would be simplified from a communication standpoint if the tflite version just matched the previous tf version with a suffix indicating the intermediate commit if that is a development requirement

**Comment by usbguru** [comment]
@gdj0nes 
Github does not have versions.  Specifically it has releases, tags, and commits.  As Nam suggested, the latest release will probably work for you.  Its just likely we have not tested that specific one.  By building with a specific commit, in a known-good docker, you will get the same exact file that we built and tested.
