### ISSUE TITLE
USB accelerator cannot run `edgetpu` model

### ISSUE THREAD

**Issue by DemolationPeter** [google-coral/edgetpu#250]
HI guys,

Yesterday I tried to get the USB accelerator to work on my Desktop PC with Ubuntu 18.04. Unfortunately I couldn't get python examples to run with the  'mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite'. The  'mobilenet_v2_1.0_224_inat_bird_quant.tflite'  model is working.
It seems that the Problem is similar to [#44](https://github.com/google-coral/edgetpu/issues/44) and [#214](https://github.com/google-coral/edgetpu/issues/214). I think I still miss something.

I get the following error message. 

![Bildschirmfoto vom 2020-11-11 09-31-56](https://user-images.githubusercontent.com/74291692/98789532-b3cca580-2402-11eb-8ec7-a6c82b12eb9a.png)

In the next Image are some System Information. Also I'm using the newest TFLITE_runtime version (2.5.0). I installed the current TFLITE_runtime wheel from the [Python quickstart](https://www.tensorflow.org/lite/guide/python). The TFLITE_runtime version is running in an miniconda3 environment.

![Bildschirmfoto vom 2020-11-11 09-48-32](https://user-images.githubusercontent.com/74291692/98791195-f7281380-2404-11eb-961e-88807aaf863b.png)
 
I tried different Python versions in the environment and the suitable TFLITE_runtime version according to the used Python version.

Maybe someone has an idea what else I can try.

Cheers Guys

**Comment by selrahc** [comment]
I ran into the similar issue and found some information from another thread: https://github.com/google-coral/pycoral/issues/1#issuecomment-724312390

**Comment by Namburger** [comment]
@DemolationPeter 
Hey, sorry about basically this is because tflite_runtime 2.5 doesn't match with libedgetpu 14.1. We did have it in our apt repo but needed to temporary rollback to make some changes, it should be re-release soon. For now, you can take a look at this to use the new version:
https://github.com/google-coral/pycoral/issues/1#issuecomment-724312390

**Comment by DemolationPeter** [comment]
@Namburger and @selrahc 
Thank you for the quick response. Know everything works like a charm.
