### ISSUE TITLE
TFlLite model changes through edgetpu_compiler

### ISSUE THREAD

**Issue by LINYOUWEI0804** [google-coral/edgetpu#251]
After the TFLite model (INT8) is successfully compiled by edgetpu_compiler, what will happen to the model?

.tflite --------->edgetpu.tflite What changes have been made to the model

**Comment by Namburger** [comment]
All of the compatible ops get wraps into a single edgetpu custom ops, you may use tools like [netron](https://github.com/lutzroeder/netron) to visualize it.

**Comment by LINYOUWEI0804** [comment]
When using netron to watch edgetpu model, only edgetpu-custom-op appears. What does edgetpu-custom-op mean?

**Comment by LINYOUWEI0804** [comment]
![edgetpu model](https://user-images.githubusercontent.com/58504153/99353449-7aeb6f80-28df-11eb-9661-71abbe54b35f.png)

**Comment by Namburger** [comment]
Thats the ops that the runtime knows to delegate to the edgetpu, if you look at the cpu model, itll contains all original ops

**Comment by LINYOUWEI0804** [comment]
So we have no way to know what changed in the tflite->edgetpu.tflite model, right?

**Comment by Namburger** [comment]
Well if you compare the 2 models, you would see what ops was converted to the edgetpu, if your model isn't fully compatible, you'll see a lot more cpu ops on the edgetpu model
