### ISSUE TITLE
Coral USB accelerator device periodically goes to inaccessible state

### ISSUE THREAD

**Issue by BalajiElumalai27** [google-coral/edgetpu#252]
Past few months i using Coral USB Accelerator in a Ubuntu 18.04 (Linux) Application for inferencing. I have noticed that the USB accelerator device periodically seems to go into inaccessible state, while our application is still running. When it gets in this state, the USB device does get not detected even after restarting the machine (Power Recycle). The only way is to fix this physically unplug and reinsert the USB device. Since our machine is hosted in a remote location, this is a major setback. I wants input from the Coral team on how to reset the USB Accelerator without human involvement. Please share comments which helps me a lot.

**Comment by Namburger** [comment]
@usbguru could you take a look at this one?

**Comment by usbguru** [comment]
Hi @BalajiElumalai27 
First, USB was never intended as an industrial/embedded component for long-term, hands-off operation.  PCIe would be better.  USB is meant for mice, memory sticks, and development systems.

That said, your question has been asked before.  Here is a possible answer: https://unix.stackexchange.com/questions/122234/is-it-possible-to-simulate-force-fake-an-usb-device-unplug-and-replug-on-linux

Physically removing power is another option: https://electronics.stackexchange.com/questions/393468/efficient-way-to-selectively-unpower-usb-ports   One of the answers points to a project that can force individual USB hub ports on and off for specific models of hub:  https://github.com/mvp/uhubctl

Hope that helps!
