### ISSUE TITLE
How to update edgetpu compiler from 14.1 to 15.0?

### ISSUE THREAD

**Issue by ZhouKai90** [google-coral/edgetpu#254]
I've tried uninstalling edgetpu compier and reinstalling, but I still get the 14.1 version。

**Comment by Namburger** [comment]
@ZhouKai90 hey, it is uploaded to the apt repo recently, have you tried a `sudo apt update`?

**Comment by ZhouKai90** [comment]
> @ZhouKai90 hey, it is uploaded to the apt repo recently, have you tried a `sudo apt update`?

Sure, Can you give me the .deb download link? like this https://packages.cloud.google.com/apt/pool/edgetpu-compiler_14.1_amd64_ef6eef29200270dcb941d2c1defa39c7d80e9c6f30cf7ced1c653a30bde0a502.deb

**Comment by ZhouKai90** [comment]
@Namburger Sure, Can you give me the .deb download link? like this https://packages.cloud.google.com/apt/pool/edgetpu-compiler_14.1_amd64_ef6eef29200270dcb941d2c1defa39c7d80e9c6f30cf7ced1c653a30bde0a502.deb

**Comment by Namburger** [comment]
Hello, here is the actual package, you can just extract and install:
[edgetpu-compiler_15.0_amd64.deb.tar.gz](https://github.com/google-coral/edgetpu/files/5546715/edgetpu-compiler_15.0_amd64.deb.tar.gz)
```
$ tar xvf edgetpu-compiler_15.0_amd64.deb.tar.gz
$ sudo dpkg -i edgetpu-compiler_15.0_amd64.deb
```

**Comment by ZhouKai90** [comment]
@Namburger ths a lot.

**Comment by Namburger** [comment]
No problems, although you should be able you get it now, could you try updating the apt repo and reinstall?

**Comment by ZhouKai90** [comment]
@Namburger when I use edgetpu-compiler_15.0 compile my tflite model , I still get the "RESIZE_NEAREST_NEIGHBOR Operation version not supported" error information. The newest version still hasn't fixed this problem?

**Comment by Namburger** [comment]
@ZhouKai90 I will contact our compiler team today to get more info, mean while can you please confirm that you can get the new compiler installed via apt-get as it should?
Also, can you attach your model?

**Comment by gdj0nes** [comment]
> @Namburger when I use edgetpu-compiler_15.0 compile my tflite model , I still get the "RESIZE_NEAREST_NEIGHBOR Operation version not supported" error information. The newest version still hasn't fixed this problem?

Nearest Neighbors should not be listed as a supported operation on the website until this has been resolved

**Comment by ZhouKai90** [comment]
> @ZhouKai90 I will contact our compiler team today to get more info, mean while can you please confirm that you can get the new compiler installed via apt-get as it should?
> Also, can you attach your model?
@Namburger  Thanks for your answer!!! I have been able to use via apt-get to  install the new compiler . Otherwise, here is my model.
[https://github.com/ZhouKai90/YOLO_Tensorflow2/blob/main/save/pedestrian/pedestrians_mobilenetv2_yolov3_540_960_uint8_MLIR.tflite](url)

**Comment by ZhouKai90** [comment]
> @ZhouKai90 I will contact our compiler team today to get more info, mean while can you please confirm that you can get the new compiler installed via apt-get as it should?
> Also, can you attach your model?
@Namburger Thanks for your answer!!! I have been able to use via apt-get to install the new compiler . Otherwise, here is my model.
[https://github.com/ZhouKai90/YOLO_Tensorflow2/blob/main/save/pedestrian/pedestrians_mobilenetv2_yolov3_540_960_uint8_MLIR.tflite](url)

**Comment by ZhouKai90** [comment]
> > @Namburger when I use edgetpu-compiler_15.0 compile my tflite model , I still get the "RESIZE_NEAREST_NEIGHBOR Operation version not supported" error information. The newest version still hasn't fixed this problem?
> 
> Nearest Neighbors should not be listed as a supported operation on the website until this has been resolved

I also tried with bilinear, but still produces too high tflite op version for the edgetpu compiler.

**Comment by ZhouKai90** [comment]
> @ZhouKai90 I will contact our compiler team today to get more info, mean while can you please confirm that you can get the new compiler installed via apt-get as it should?
> Also, can you attach your model?

@Namburger Thanks for your answer!!! I have been able to use via apt-get to install the new compiler . Otherwise, here is my model.
[pedestrians_mobilenetv2_yolov3_540_960_uint8_MLIR.tflite](https://drive.google.com/file/d/1eKHb14XXmeobDrDiePsh5u0Rbj6Z8VHJ/view?usp=sharing)

**Comment by ZhouKai90** [comment]
[de](https://drive.google.com/file/d/1eKHb14XXmeobDrDiePsh5u0Rbj6Z8VHJ/view?usp=sharing)

**Comment by Naveen-Dodda** [comment]
@ZhouKai90 which version of TensorFlow have you been using for training and quantization ?

**Comment by ZhouKai90** [comment]
> @ZhouKai90 which version of TensorFlow have you been using for training and quantization ?

@Naveen-Dodda  TensorFlow 2.3.0

**Comment by Naveen-Dodda** [comment]
Got it, the default version of "RESIZE_NEAREST_NEIGHBOR" in TF 2.3.0 is not supported by edgetpu_compiler yet. So I recommend you to export/quantize the model using TF1.x if possible for now.

**Comment by ZhouKai90** [comment]
> Got it, the default version of "RESIZE_NEAREST_NEIGHBOR" in TF 2.3.0 is not supported by edgetpu_compiler yet. So I recommend you to export/quantize the model using TF1.x if possible for now.
May I ask what's the plan to support RESIZE_NEAREST_NEIGHBOR V3 for edgetpu_compiler? It is inconvenient to use the  TF1.x version.

**Comment by ZhouKai90** [comment]
May I ask what's the plan to support RESIZE_NEAREST_NEIGHBOR V3 for edgetpu_compiler? It is inconvenient to use the TF1.x version.

**Comment by usbguru** [comment]
@ZhouKai90 
RESIZE_NEAREST_NEIGHBOR V3 is one of our top priories for the next release.  Watch https://coral.ai/news for the latest information
