### ISSUE TITLE
RuntimeError: Error in device opening (/dev/apex_0)!

### ISSUE THREAD

**Issue by jolloqui** [google-coral/edgetpu#255]
Hi,

I am following the execution instructions from the Coral posenet example.

When I try to run:

> python3 pose_camera.py

The output is:

> Loading model:  models/mobilenet/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite
> Traceback (most recent call last):
>   File "pose_camera.py", line 163, in <module>
>     main()
>   File "pose_camera.py", line 159, in main
>     run(run_inference, render_overlay)
>   File "pose_camera.py", line 115, in run
>     engine = PoseEngine(model)
>   File "/home/mendel/project-posenet/pose_engine.py", line 85, in __init__
>     BasicEngine.__init__(self, model_path)
>   File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 92, in __init__
>     self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
> RuntimeError: Error in device opening (/dev/apex_0)!

Any help would be appreciated.

EDIT:
After upgrade de distribution whit `sudo apt-get dist-upgrade` know the output is:

> Traceback (most recent call last):
>   File "pose_camera.py", line 26, in <module>
>     from pose_engine import PoseEngine
>   File "/home/mendel/project-posenet/pose_engine.py", line 20, in <module>
>     from edgetpu import __version__ as edgetpu_version
> ModuleNotFoundError: No module named 'edgetpu'

**Comment by Namburger** [comment]
@jolloqui our posenet repo is being updated as the edgetpu repo has been deprecated in favor of pycoral and libcoral, this should be fixed soon. However,
```
RuntimeError: Error in device opening (/dev/apex_0)!
```
Seems to be a different issue, can you share the outputs of these commands?
```
$ ls /dev/apex_0
$ lspci
```

**Comment by jolloqui** [comment]
@Namburger I have installed the system again to get the error. Because it only happens before the update.

```
$ ls /dev/apex_0 
/dev/apex_0
$ lspci
0000:00:00.0 PCI bridge: Synopsys, Inc. DWC_usb3 (rev 01)
0000:01:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
0001:00:00.0 PCI bridge: Synopsys, Inc. DWC_usb3 (rev 01)
0001:01:00.0 System peripheral: Device 1ac1:089a
 ```

**Comment by Namburger** [comment]
@jolloqui yes, posenet just won't works at the moment due to our new update, which deprecated [this import](https://github.com/google-coral/project-posenet/blob/master/pose_engine.py#L24)
we're working on it, however you should be able to run any other example, correct?

**Comment by jolloqui** [comment]
@Namburger yes, the other examples work fine!
Thank you very much!

**Comment by hjonnala** [comment]
Closing the issue as it got fixed with newer versions.
![Screenshot from 2021-07-07 10-19-43](https://user-images.githubusercontent.com/86132058/124802588-fc464f80-df0c-11eb-8c74-b1a9adf65c28.png)
