### ISSUE TITLE
edgetpu.dll Load Faild

### ISSUE THREAD

**Issue by staebchen0** [google-coral/edgetpu#257]
Hi,

When Loding `edgetpu.classification` I get the following error

Python Code: 
`from edgetpu.classification.engine import ClassificationEngine`

Error:
DLL load failed: The specified module was not found.

Install:
from (https://coral.ai/software#edgetpu-python-api)

- edgetpu (2.14.0)
- tflite-runtime (2.5.0)
- Python 3.7
- Windows10 PC

I cannot find the dll edgetpu.dll on the PC either. Perhaps an installation step is still missing?

**Comment by Namburger** [comment]
Hello, [edgetpu package is deprecated](https://coral.ai/news/updates-11-2020), I suggest using [pycoral](https://coral.ai/software#pycoral-api) instead. [Here](https://github.com/google-coral/pycoral/tree/master/examples) are some examples of pycoral in action, it is not much different than edgetpu. 

Make sure you also have the edgetpu.dll installed following [these steps](https://coral.ai/docs/accelerator/get-started/#1c-on-windows):
*  First, make sure you have the latest version of the Microsoft Visual C++ 2019 redistributable.
* Then download edgetpu_runtime_20201105.zip.
* Extract the ZIP files and double-click the install.bat file inside.
* A console opens to run the install script and it asks whether you want to enable the maximum operating frequency. Running at the maximum operating frequency increases the inferencing speed but also increases power consumption and causes the USB Accelerator to become very hot. If you're not certain your application requires increased performance, you should type "N" to use the reduced operating frequency.
* You can read more about the performance setting in the USB Accelerator datasheet.
* Now connect the USB Accelerator to your computer using the provided USB 3.0 cable.

**Comment by staebchen0** [comment]
Thanks for your help. It Works :-)

I still have a fundamental question:

I created a model in the h5 format for my project.

With the same database I created a model in tflite format.
(all about Teachable Machine, there you can save a trained model in different formats)

Now one would expect that the prediction results of the two models are the same! Unfortunately, this is not the case.
The tflite model achieved a poor result in my test with pictures.

Does anyone have any idea what that might mean?

**Comment by Namburger** [comment]
@staebchen0 There are too many things that can go wrong with post training quantization and compiler in the pipeline, I suggest that you open a new issue with more details, including your h5 to tflite conversion codes.
I can either look into it or assign someone to it for you!

Closing this one for now.
