### ISSUE TITLE
Unsupported data type in custom op handler

### ISSUE THREAD

**Issue by apieceofmou** [google-coral/edgetpu#259]
Get started with the M.2 or Mini PCIe Accelerator, follow the instructions, end to this:
    RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.

dpkg -l | grep edgetpu
ii  libedgetpu1-std:amd64                      15.0                                                                                         amd64        Support library for Edge TPU

>>> import tflite_runtime as tf
>>> tf.__version__
'2.1.0.post1'

**Comment by Namburger** [comment]
Hello, it looks like you somehow installed an older version of `tflite_runtime`, the version should have returned 2.5:
```
➜  ~ python3 -c 'print(__import__("tflite_runtime").__version__)'
2.5.0
➜  ~ python3 -c 'print(__import__("tflite_runtime").__git_version__)'
48c3bae94a8b324525b45f157d638dfd4e8c3be1
```
I suggest that you remove that package completely and reinstall form this link: https://www.tensorflow.org/lite/guide/python

**Comment by apieceofmou** [comment]
Thank you so much! After update tflite_runtime to 2.5.0, the problem has been solved. 
The Chinese language version of tflite_runtime link (https://www.tensorflow.org/lite/guide/python) is still 2.1.0, that's why I install the wrong version at first.

**Comment by MacherelR** [comment]
Hello, I had the same problem and tried removing python3-tflite-runtime and the reinstalling it from your link (image linked) but as you can see tflite_runtime is still on 2.1.0.post1 even if the downloaded version is 2.5.0..
Do you have an Idea what is wrong ? 
Thanks
![image_2021-03-12_144611](https://user-images.githubusercontent.com/64424331/110948485-afc57b80-8341-11eb-881d-67cffa27ba26.png)

**Comment by Namburger** [comment]
@MacherelR try pip uninstalling it?

**Comment by MacherelR** [comment]
pip uninstall python3-tflite-runtime gets me the following message :
 "WARNING: Skipping python3-tflite-runtime as it is not installed." 
 Even if i run sudo apt-get --purge remove python3-tflite-runtime it tells me that it is removed but if then I run command : python3 -c 'print(__import__("tflite_runtime").__version__)'
 It still tells me 2.1.0.post1 how is that possible even after deleting it ?

**Comment by Namburger** [comment]
@MacherelR how about do this:
```
$ python3 -c 'print(__import__("tflite_runtime").__path__)'
```

It'll tell you where it is installed, delete it manually

**Comment by MacherelR** [comment]
Okay I'll try this thank you !
But with the directory should I just use rm -r 'Path' to delete it or still sudo apt-get --purge remove 'Path' ?

Thanks for your help

**Comment by MacherelR** [comment]
Ok I now have the right version of tflite_runtime when running : python3 -c 'print(import("tflite_runtime").version)'
Thanks for your help guys !

**Comment by nonegom** [comment]
@Namburger 
Hi sir. I want use EdgTPU. 
My grep degetpu like that and my tensorflow version is 2.5.0.
but now I have a problem. What could I do?
![2](https://user-images.githubusercontent.com/71921002/114295719-001b2f00-9ae2-11eb-967b-22375889e540.PNG)

thank you!

---------------------------------
pi@raspberrypi:~ $ dpkg -l | grep edgetpu
ii  libedgetpu1-std:armhf                15.0                                armhf        Support library for Edge TPU

pi@raspberrypi:~ $ python3 -c 'print(__import__("tflite_runtime").__version__)'
2.5.0

**Comment by mikecamara** [comment]
Hey @Namburger  by any chance did you ever find a solution for this?

I'm also trying to implement the stop sign detection on the donkey car and got the very same error. 

> @Namburger Hi sir. I want use EdgTPU. My grep degetpu like that and my tensorflow version is 2.5.0. but now I have a problem. What could I do? ![2](https://user-images.githubusercontent.com/71921002/114295719-001b2f00-9ae2-11eb-967b-22375889e540.PNG)
> 
> thank you!
> 
> pi@raspberrypi:~ $ dpkg -l | grep edgetpu ii libedgetpu1-std:armhf 15.0 armhf Support library for Edge TPU
> 
> pi@raspberrypi:~ $ python3 -c 'print(**import**("tflite_runtime").**version**)' 2.5.0
