### ISSUE TITLE
about the APIs and call flow.

### ISSUE THREAD

**Issue by akioolin** [google-coral/edgetpu#26]
Hi, All:

Currently the APIs of Edge TPU support two approach. One is Python, which could be found in
https://github.com/google-coral/edgetpu/tree/master/edgetpu. The other is C++ API, which could be found in https://github.com/google-coral/edgetpu/tree/master/libedgetpu. 

The first problem is the Python interface is powered by the code in https://github.com/google-coral/edgetpu/tree/master/src/cpp or not?

The second problem is the code in https://github.com/google-coral/edgetpu/tree/master/src/cpp rely on libedgetpu.so directly or also need co-work with libtensorflow-lite.a ?

The path could be shown as followings.

1st case: Python API ==> C++ API ==> libtensorflow-lite.a ==> libedgetpu.so  ==> edgetpu driver.

2nd case: Python API ==> C++ API ==> libtensorflow-lite.a  \__
                                                          ==> libedgetpu.so         /---->>>> edgetpu driver.

could the following flow possible or not:

data / model ==> Pre-processed by libtensorflow-lite.a ==> C++ API ==> libedgetpu.so

why this usage flow, the major reason is for the API maintenance.

Thank you.

BR, Akio

**Comment by Namburger** [comment]
@akioolin Not sure if I can fully understand your whole queries here. But I'll try my best to answer,
> The first problem is the Python interface is powered by the code in https://github.com/google-coral/edgetpu/tree/master/src/cpp or not?

Yes, the edgetpu python API is a [swig](http://www.swig.org/) wrapper around the cpp api. However, you can also run inference using the [tflite_runtime api](https://github.com/google-coral/tflite) or just bare tensorflow lite api as documented [here](https://coral.withgoogle.com/docs/edgetpu/tflite-python/)

> The second problem is the code in https://github.com/google-coral/edgetpu/tree/master/src/cpp rely on libedgetpu.so directly or also need co-work with libtensorflow-lite.a ?

The ccp api will requires the tensorflow library, as all the provided engines are just wrapper around the tensorflow lite `interpreter` class. See [here](https://github.com/google-coral/edgetpu/blob/master/src/cpp/examples/minimal.cc#L13) for a minimal wrapper and [here](https://github.com/google-coral/edgetpu/blob/master/src/cpp/basic/basic_engine_native.h#L7) for a basic engine wrapper.

**Comment by akioolin** [comment]
@Namburger  Thank you very much. because I'm trying to build our own edgetpu C/C++ api wrapper for a portable application design. The call path and the components usage flow is very important to our work. after some trace the code in  https://github.com/google-coral/edgetpu/tree/master/src/cpp, I' found that the libedgetpu.so provided the real interface to edgetpu device, and libtensorflow-lite ( tensorflow lite library) provide the tensor wrapper / data pre-process related functions, like NCHW format conversion, etc. btw, there are also so called edgetpu utility classes / functions, like resource management, benchmark, etc. since tensroflow lite is changing very rapidly, compare with libedgetpu, the best way is found the direct usage to libedgetpu, and treat libtensor-lite.a as a companion function sets.

BR, Akio

**Comment by Namburger** [comment]
@akioolin I see, thank for clarifying.
Since you're building the tf lib staticly, I suggest using [this exact commit](https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5). It is the one that's most compatible with our libedgetpu.so runtime

**Comment by akioolin** [comment]
@Namburger  Thank you very much. I'm sorry for my poor explanation. BTW, I had try to build a shared so version of  libtensorflow-lite.a, but get the following message.

lib/libtensorflow-lite.so: undefined reference to `absl::Mutex::Unlock()'
lib/libtensorflow-lite.so: undefined reference to `rdft2d'
lib/libtensorflow-lite.so: undefined reference to `absl::Mutex::ReaderLock()'
lib/libtensorflow-lite.so: undefined reference to `absl::Mutex::Lock()'
lib/libtensorflow-lite.so: undefined reference to `absl::Mutex::~Mutex()'
lib/libtensorflow-lite.so: undefined reference to `absl::GetStackTrace(void**, int, int)'
lib/libtensorflow-lite.so: undefined reference to `absl::Mutex::ReaderUnlock()'

the main() redefinition is been removed. the above message is the remained.

the usage of the commit, could you do me a favour to show me how to use it?

Makefile is my familiar,  but for bazel building system is not.

Thank you very much.

BR, Akio

**Comment by Namburger** [comment]
@akioolin To build a separate lib tensorflow, you can just follow the guide as provided on their site here:
https://www.tensorflow.org/install/source

You can just clone the repo, `git checkout` the exact commit and follow the guide.

**Comment by akioolin** [comment]
@Namburger Thank you very much. I'll try my best to follow the guide.

BTW, I had done a version which extract the file which called in src/cpp from tensorflow lite. what I found is the tflite is more like a utility super set for edgetpu c++ API. Maybe I could put the tflite library and edgetpu c++ api related code as a libedgetpu_wrapper library. 

For the C++ application developer, just two library and edgetpu c++ headers, th tflite complexity could be hidden under this way.

BR, Akio

**Comment by dmitriykovalev** [comment]
It's probably better to link `libtensorflow-lite.a` statically instead of creating a shared version. 

Better representation of current architecture:
```
Python API => SWIG-wrapped shared library (.so) statically linked with libtensorflow-lite.a 
           => libedgetpu.so 
           => libusb.so 
           => Coral USB Accelerator
```

Technically you can use TensorFlow Lite library and integrate it directly with Edge TPU Runtime (libedgetpu.so) by using[`edgetpu.h`](https://github.com/google-coral/edgetpu/blob/master/libedgetpu/edgetpu.h) or [`edgetpu_c.h`](https://github.com/google-coral/edgetpu/blob/master/libedgetpu/edgetpu_c.h) headers. Check inline documentation in the header files for more details.

**Comment by akioolin** [comment]
@dmitriykovalev  Thanks for the suggestion. I'll think more for a better and flexible way to build our own wrapper.

BR, Akio

**Comment by arun-kumark** [comment]
Hi,

I am running the MLMark benchmarking
