### ISSUE TITLE
Windows: siganture errors installing driver

### ISSUE THREAD

**Issue by MSoegtropIMC** [google-coral/edgetpu#260]
Dear Coral Team,

I tried installing the Coral Windows driver from (https://dl.google.com/coral/edgetpu_api/edgetpu_runtime_20201105.zip).

I get these error messages when running the installer:
```
Adding driver package:  coral.inf
Driver package added successfully.
Published Name:         oem43.inf
Driver package installed.

Adding driver package:  Coral_USB_Accelerator.inf
Failed to add driver package: The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering.

Adding driver package:  Coral_USB_Accelerator_(DFU).inf
Failed to add driver package: The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering.

Total driver packages:  3
Added driver packages:  1
Installing performance counters
```
So two of the driver packages are not installed cause of signature errors. As a consequence the sample code does not run ("Failed to load delegate from edgetpu.dll").

**Comment by Namburger** [comment]
@MSoegtropIMC Thanks for reporting, we are looking into this now.

**Comment by Namburger** [comment]
For now, I suggest rolling back to the older driver:
https://dl.google.com/coral/edgetpu_api/edgetpu_runtime_20200728.zip

And you also need to remove your current tflite_runtime and downgrade it to an older version (make sure to change to the right python version):
```
pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp36-cp36m-win_amd64.whl
pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-win_amd64.whl
```

Apologies, we are working to get this fixed ASAP

**Comment by MSoegtropIMC** [comment]
Thanks!

Btw.: it might make sense to change the installer batch file such that it produces a more prominent error message and pauses in case of an error. If you run the batch file with a click from explorer, you likely won't see the error message(s), because the console just closes at the end. This might result in all sorts of hard to spot errors down the road. I did run the batch file from a console window to see the errors.

**Comment by Namburger** [comment]
@MSoegtropIMC thanks for the input, will also forward this to the team

**Comment by allisterb** [comment]
Can confirm uninstalling the new version and using the older driver works. Also Windows SmartScreen by default blocks unknown/unsigned scripts downloaded from the Internet that ask for admin privileges and you have to manually tell it to go ahead. If the work done in the install.bat script can be moved to the signed installer then it would be a better user experience.

**Comment by anemo-hypostasis** [comment]
I'm using Python 3.8 and unfortunately I can't find `tflite_runtime-2.1.0.post1-cp38-cp38m-win_amd64.whl` anywhere (@Namburger the link for the Python 3.8 library leads to a 404 page). I'm forced to use `tflite_runtime-2.5.0`, and I'm forced to use the newer 20201105 driver (can confirm 20200728 driver doesn't work with `tflite` 2.5.0)

It seems like the newer drivers aren't/are improperly signed. It does work and inferencing looks good, but I have to disable Driver Signature Enforcement as a workaround and deal with the warning below:

![image](https://user-images.githubusercontent.com/4461705/100251341-9c9cc480-2f79-11eb-9fcd-e97c38e41fe7.png)

**Comment by Namburger** [comment]
@pandalion98 ahh, that's true, I forgot that we did not have python38 supports in the previous release. 
We're working on the fix for the new release, including the signed share lib now, please expect this to be done in a few weeks, apologies.

**Comment by vvkuryshev** [comment]
I had same problem on Windows 10 and downgraded runtime version to edgetpu_runtime_20200728.zip and tflite_runtime to 2.1.0. I was able to install the drivers after that, but trying to run the test script again was unsuccessful. What could be the problem here?


`C:\coral\tflite\python\examples\classification>python classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\tflite_runtime\interpreter.py", line 162, in load_delegate
    delegate = Delegate(library, options)
  File "C:\Python\lib\site-packages\tflite_runtime\interpreter.py", line 121, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 99, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 73, in make_interpreter
    {'device': device[0]} if device else {})
  File "C:\Python\lib\site-packages\tflite_runtime\interpreter.py", line 165, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from edgetpu.dll`

**Comment by jimdinunzio** [comment]
Hi, I have a LattePanda windows mini board CPU and got the same error with the latest  driver installer: download edgetpu_runtime_20201204.zip. I had miniconda python 3.8 installed and tried the 1105 install as @pandalion98 did after disabling driver signature enforcement, but that made the install wonky and I still got the same error.  So I created a python 3.7 environment and went with the 0728 and that worked. 
Please let us know when a new fixed version is posted.
Thanks,
Jim

**Comment by manoj7410** [comment]
@MSoegtropIMC Is this issue still persistent ?

**Comment by MSoegtropIMC** [comment]
I didn't try any new version since then (I live with the rolled back version). If you did an updated which you expect to fix this, I will try that until next week.

**Comment by manoj7410** [comment]
Feel free to reopen if this issue still persists.
