### ISSUE TITLE
Using mPCIe TPU in qemu VM

### ISSUE THREAD

**Issue by Faoran** [google-coral/edgetpu#263]
I'm trying to use the mPCIe EdgeTPU, which works perfectly fine in the host system, in a qemu VM and I'm unable to get any of the examples working.

Host System: Ubuntu 20.04
Guest System: Fedora 33 with Python 3.8

I have installed the necessary drivers and tools (edgetpu) after some trial and error, setup the PCI passthrough from Host to Guest system and the Edge TPU device is listed in the Guest system as expected (/dev/apex_0 exists and Coral Edge TPU is listed in lspci call).

But when I'm trying to start one of the examples, I get the following error message:
`RuntimeError: Error in device opening (/dev/apex_0)!`
and dmesg lists the following errors:
```
RAM did not enable within timeout (12000 ms)
Error in device open cb: -110
```

Any help would be appreciated.

**Comment by Namburger** [comment]
@Faoran I can't say for certain since I've never used qemu, however, for most VMs, you'll need to set up passthrough for pcie devices. For instance, with docker, you need something like this (**--device /dev/apex_0:/dev/apex_0**: 
```
docker run -it --device /dev/apex_0:/dev/apex_0 coral /bin/bash
```
Here is a reference for qemu: https://unix.stackexchange.com/a/96613

**Comment by Faoran** [comment]
That's exactly how I set up the pcie passthrough (except I've bound the host device to vfio-pci, which is the modern version of pci-stub) and it sadly is not working.
I've already successfully used the passthrough to a docker container, so for me it seems strange that it won't work for qemu.

I've also tried it with an Ubuntu 20.04 guest system with the same results.
