### ISSUE TITLE
LEGO

### ISSUE THREAD

**Issue by akosb** [google-coral/edgetpu#264]
Hi Coral Team,

 not sure where stuff like this belongs to, but I've created an _article_ series around my board usage. [Part III.](https://vaew.io/coral03/index.html) for example describes how to take the board for a walk outside. Rest is about my LEGO character recognizer. 
 Would be nice to have some user stories sections somewhere, just like TFJS has some [GALLERY](https://github.com/tensorflow/tfjs/blob/master/GALLERY.md) for this, they also had [Community Show & Tell](https://www.youtube.com/watch?v=z05bjEEgVQc&ab_channel=JasonMayes) sessions ... 

 If you find this irrelevant, please feel free to remove/close issue ;)

Regards, Akos

**Comment by Namburger** [comment]
@akosb Kool project! 
@usbguru @Naveen-Dodda @mbrooksx What do you guys think?

**Comment by usbguru** [comment]
@akosb 
This is great.  

I will remind the marketing team that we need a place to highlight projects like this.

**Comment by hjonnala** [comment]
Though it has been considered, it is not possible to add user stories in near future as we just don't have a process to review  and validate them.
