### ISSUE TITLE
Internal compiler error. Aborting!

### ISSUE THREAD

**Issue by gaogzs** [google-coral/edgetpu#265]
The model I used was initially a [pytorch model](https://1drv.ms/u/s!AvZvArIp3xKtjm7YwhSgeJrjEtLB?e=FqTnI6) 
trained based on https://github.com/bubbliiiing/yolo3-pytorch
using [dataset](https://github.com/gaogzs/road-cam-yolo/tree/master/YOLO_DATA)
and being converted to a [tflite model](https://1drv.ms/u/s!AvZvArIp3xKtjm3pY2ikrYxAmYjp?e=XbvnIP)
by https://github.com/kuroko1t/nne (where nne/tflite.py line 53 is replaced by `converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model(tmp_pb_path)`)
At the last step, when the program uses `edgetpu_compiler` to compile the tflite model, the error on the title appears.
Please tell me if some mistake has been made, and which part has gone wrong.

**Comment by Namburger** [comment]
@gaogzs the steps you described are only converting a graph model to tflite and not a fully quantized integer quantization model. Either that or maybe you didnt provide enough info? 
Anyhow, on that repo has a edgetpu version, which looks to me fully quantized can you try that instead?

I also suggest checking this page: https://coral.ai/docs/edgetpu/pipeline/
And look at the ops compatibility table, unfortunately yolo architect wont works by default and will requires some tweaking
