### ISSUE TITLE
Upgrade release?

### ISSUE THREAD

**Issue by nibeh** [google-coral/edgetpu#266]
https://github.com/google-coral/edgetpu/blob/6d699665efdc5d84944b5233223c55fe5d3bd1a6/WORKSPACE#L5
and SHA should be upgraded according to libedgetpu https://github.com/google-coral/libedgetpu/blob/14eee1a076aa1af7ec1ae3c752be79ae2604a708/workspace.bzl#L8
```
TENSORFLOW_COMMIT = "f394a768719a55b5c351ed1ecab2ec6f16f99dd4"
TENSORFLOW_SHA256 = "cb286abee7ee9cf5c8701d85fcc88f0fd59e72492ec4f254156de486e3e905c1"
```
Otherwise execution with libedgetpu 15 from deb does not work.

**Comment by Namburger** [comment]
@nibeh Thanks for reporting, we actually deprecated this repo in favor of pycoral and libcoral so this is left likethis so that the edgetpu package is compatible with the older libedgetpu release

src: https://coral.ai/news/updates-11-2020
