### ISSUE TITLE
documentation updates

### ISSUE THREAD

**Issue by akosb** [google-coral/edgetpu#267]
Hi Coral Team,

 got a new 4GB board delivered today :) flashing and installing it now, and I would like to have the following comments:

**Issue 1)**
https://coral.ai/software/#debian-packages suggests _you must first add our package repo to your sources list_
 Don't think that it's necessary as the newly flashed Mendel image seems to have those package repos:
```
Hit:7 https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease
Hit:8 https://mendel-linux.org/apt/eagle-bsp-enterprise eagle InRelease 
Hit:9 https://mendel-linux.org/apt/eagle eagle InRelease
```

**Issue 2)**
https://coral.ai/software/#debian-packages lists the _edgetpu-compiler_ as an option, but as is it stated in the [Edge TPU Compiler, System Requirements ](https://coral.ai/docs/edgetpu/compiler/#system-requirements) section _The Edge TPU Compiler is no longer available for ARM64 systems (such as the Coral Dev Board), beginning with version 2.1._ Probably this should be mentioned in the package list table?

**Issue 3)**
My daily workstation is a Mac and I lately upgraded to 'macOS Big Sur'. On Macs the [CP210x VCP Mac OSX Driver
](https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers) is needed for serial, but as I learned the hard way: _With new version of macOS released which is macOS Big Sur 11.0.x, the latest version of our VCP driver for Macintosh OSX (v5.3.5) now becomes incompatible._  According to a forum [entry](https://www.silabs.com/community/interface/forum.topic.html/vcp_driver_for_macosbigsur110x-SWJK) they are working on the updated driver.

 Regards, Akos

**Comment by Namburger** [comment]
@akosb Thanks for the suggestions, @scottamain what do you think on 1 and 2?

On issue 3, that's kind of concerning, does this meaning you're unable to flash the board at all on Big Sur?

**Comment by akosb** [comment]
@Namburger if you're asking if you're _without serial_ on Big Sur until new driver comes? my answer is **yes** 
... for sure I had to fallback to a machine with linux, and it's there where initial key for ssh auth had to be fixed as well(!)

**Comment by Namburger** [comment]
@akosb yeah, I imagine there would be issues with getting the ssh key going. But kinda sucks that mac Big Sur user wouldnt be able to flash the board since serial driver wont come with it :/
Im not sure if we can do much about it though

**Comment by akosb** [comment]
@Namburger guess documentation could have some warning until it's supported again? Under [Install the udev rule or driver on your host computer.](https://coral.ai/docs/dev-board/get-started#11-initiate-fastboot-mode), in the section for Mac there is already a Caution box, it could be extended with some text, stating that Big Sur _currently_ not supported.

**Comment by emcfarlane** [comment]
Linking the issue on their forum for updating the VCP driver for Big Sur: https://www.silabs.com/community/interface/forum.topic.html/vcp_driver_for_macosbigsur110x-SWJK

**Comment by scottamain** [comment]
Sorry for my delay on this folks! I've clarified the debian package info. And it looks like SiLabs just released the driver update for Big Sur. Thank you for this feedback!
