### ISSUE TITLE
"For example, a fully-connected or softmax layer with 2D output" as the status

### ISSUE THREAD

**Issue by vmarkovtsev** [google-coral/edgetpu#27]
Similarly to #25 I engineered another artificial file: [bench_model_16.zip](https://github.com/google-coral/edgetpu/files/3875304/bench_model_16.zip)

It is a matrix multiplication with the second matrix constant. I hoped that it will successfully compile with `edgetpu_compiler`, but nope, bad luck again.

```
Number of operations that will run on Edge TPU: 0
Number of operations that will run on CPU: 1

Operator                       Count      Status

FULLY_CONNECTED                1          For example, a fully-connected or softmax layer with 2D output
```

Now that I believe that the file can be crazy, wrong, etc., but the status message is really puzzling.

**Comment by Namburger** [comment]
This is similar to #25 so we can keep the discussion there.
