### ISSUE TITLE
edgetpu_compiler compiles forever

### ISSUE THREAD

**Issue by gdebrecz** [google-coral/edgetpu#270]
Following the official deeplab tutorials, I've retrained:

`https//github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md`

i.e. the cityscape-pretrained quantized MobilnetEdgeTPU based Deeplabv3 network on my custom dataset having 2 classes only.

Training, model freeze, tflite export and inference (using the frozen graph pb) went without problem, however edgetpu_compiler cannot handle the task and it compiles since more that an hour....

`Edge TPU Compiler version 15.0.340273435`

I wanted to compile this model:

https://drive.google.com/file/d/1oW46uehnWO3vT8YqyIW0xNAH2474gGYg/view?usp=sharing

Can you please have a look at see what is wrong with the model/compiler ? 

Thanks a lot,
Gergely

Backround info:

Training in docker container: tensorflow/tensorflow:1.15.4-gpu-py3
Using TF version 1.15
Master of tensorflow/models
OS: Ubuntu 18.04
EdgeTPU complation on host machine (not in docker container) !
Edge TPU Compiler version 15.0.340273435

**Comment by Namburger** [comment]
Hey @Naveen-Dodda @usbguru could you guys take a look at this one?

**Comment by gdebrecz** [comment]
Hi !
 May you had the chance to have a look at this problem ? It would be quite important for us !
Thanks  a lot in advance !
Gergely

**Comment by Naveen-Dodda** [comment]
Hi Gergely, 

Thanks for your patience, It seems like you have used TF2.0 for training / quantization.  Have you tried to use TF1.x ? If you does the problem still exist ?

Can you please conform this helps us to narrow down the issue and resolve it quick.

**Comment by gdebrecz** [comment]
Hi Naveen !

First of all thanks for your reply, but as I mentioned in the original report I'm using tensorflow 1.15 (see above). In fact I'm using tensorflow's docker images tensorflow/tensorflow-1.15.4-gpu-py3.  

What else could be the reason ? 
Thanks for your quick help in advance !
Gergely

**Comment by Naveen-Dodda** [comment]
Hi Gergely, 

The compiler fails due to large reshape tensors that does not fit on the memory, this could be because it has fairly large input shape (640 x 640). Could you try to export a two model with sizes (320x320 and 512x512) and see if these models pass through compiler ?

Thanks, 
Naveen

**Comment by gdebrecz** [comment]
Hi !

Unfortunately, in the 512x512 case the compiler compiles forever (CPUs on 100%), while in the 320x320 case it return with the following error:

user@hpegpu:/data/shared/trained_models$ edgetpu_compiler -o /tmp/compile_dir ./deeplabv3_px320_quantized_frozen_graph.tflite 
Edge TPU Compiler version 15.0.340273435

Internal compiler error. Aborting! 


What other information should I give to make debugging more efficient ?
Thanks a lot,
Gergely

**Comment by gdebrecz** [comment]
To be very specific what I'm doing is:

1.)
Take: edgetpu-deeplab_2020_03_09.tar.gz
Downloaded from: http://download.tensorflow.org/models/edgetpu-deeplab_2020_03_09.tar.gz


2.) Train:

cwd=`pwd`
export PYTHONPATH=$PYTHONPATH:$cwd:$cwd/slim


PATH_TO_DATASET=/root/models/research/deeplab/datasets/test320/tfrecord
PATH_TO_TRAINED_FLOAT_MODEL=/root/edgetpu-deeplab/model.ckpt
PATH_TO_TRAIN_DIR=./traindir-edgetpu-test320

python3 deeplab/train.py \
    --logtostderr \
    --train_split="train" \
    --model_variant="mobilenet_edgetpu" \
    --decoder_output_stride='' \
    --aspp_convs_filters=256 \
    --quantize_delay_step=0 \
    --output_stride=16 \
    --train_crop_size="320,320" \
    --train_batch_size=4 \
    --initialize_last_layer=false \
    --training_number_of_steps=10 \
    --fine_tune_batch_norm=true \
    --tf_initial_checkpoint=${PATH_TO_TRAINED_FLOAT_MODEL} \
    --train_logdir=${PATH_TO_TRAIN_DIR} \
    --dataset_dir=${PATH_TO_DATASET} \
    --last_layers_contain_logits_only=False \
    --decoder_filter=2 \
    --num_classes=2 \
    --dataset="test320"

3.) Freeze the checkpoint:

cwd=`pwd`
export PYTHONPATH=$PYTHONPATH:$cwd:$cwd/slim

python3 deeplab/export_model.py \
    --logtostderr \
    --checkpoint_path=./traindir-edgetpu-test320/model.ckpt-10 \
    --export_path=./deeplabv3_test320_quantized_frozen_graph.pb \
    --quantize_delay_step=0 \
    --model_variant="mobilenet_edgetpu" \
    --num_classes=2 \
    --inference_scales=1.0 \
    --crop_size=320 \
    --crop_size=320

4.) Convert to TfLite

tflite_convert \
  --graph_def_file=./deeplabv3_test320_quantized_frozen_graph.pb \
  --output_file=./deeplabv3_test320_quantized_frozen_graph.tflite \
  --output_format=TFLITE \
  --input_shape=1,320,320,3 \
  --input_arrays="MobilenetEdgeTPU/MobilenetEdgeTPU/input" \
  --inference_type=QUANTIZED_UINT8 \
  --inference_input_type=QUANTIZED_UINT8 \
  --std_dev_values=128 \
  --mean_values=128 \
  --change_concat_input_ranges=true \
  --output_arrays="ArgMax"

5.) Compile to edgetpu:
edgetpu_compiler -o /tmp/compiled_model deeplabv3_test320_quantized_frozen_graph.tflite


Everything *seems* OK , but step 5 miserably fails with no meaningful error message.

Gergely

**Comment by gdebrecz** [comment]
I'm just wondering if you have a docker container with a properly working example ? That would help a lot in debugging the issues !
Thanks a lot in advance,
Gergely

**Comment by vaibhavolarm** [comment]
same problem ..any solution for deeplab?

**Comment by Aspirinkb** [comment]
same issue with edgetpu-deeplabv3 and 15.0.340273435 compiler.

**Comment by paul218** [comment]
**I used the next, 
tensorflow-gpu 1.15.3 to train mobilenet_edgetpu with pascal_voc_seg** 

python deeplab/train.py \
    --logtostderr \
    --training_number_of_steps="${NUM_ITERATIONS}" \
    --train_split="train" \
    --model_variant="mobilenet_edgetpu" \
    --output_stride=16 \
    --decoder_output_stride='' \
    --aspp_convs_filters=256 \
    --train_crop_size="513,513" \
    --train_batch_size=1 \
    --dataset="pascal_voc_seg" \
    --tf_initial_checkpoint=${PATH_TO_INITIAL_CHECKPOINT} \
    --train_logdir=${PATH_TO_TRAIN_DIR} \
    --dataset_dir=${PATH_TO_DATASET} \
    --initialize_last_layer=false \
    --last_layers_contain_logits_only=true

**to export:**

python deeplab/export_model.py \
  --logtostderr \
  --checkpoint_path="${CKPT_PATH}" \
  --export_path="${EXPORT_PATH}" \
  --model_variant="mobilenet_edgetpu" \
  --output_stride=16 \
  --decoder_output_stride='' \
  --num_classes=21 \
  --crop_size=513 \
  --crop_size=513 \
  --inference_scales=1.0 \

**to post-quantization i used TensorFlow-gpu 2.0**

import os
import tempfile
import numpy as np
import tensorflow as tf

def representative_dataset_gen():
    for _ in range(10):
        dummy_image = tf.random.uniform([1, 513, 513, 3], 0., 255., dtype=tf.float32)
        dummy_image = dummy_image / 127.5 - 1
        yield [dummy_image]
MODEL_FILE = "/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/export/frozen_inference_graph.pb"
output_file=/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/tflite/model8_seg.tflite'
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file = MODEL_FILE, 
    input_arrays = ['sub_2'], 
    output_arrays = ['ResizeBilinear_2']
)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8  
converter.inference_output_type =tf.uint8 
tflite_model = converter.convert()
tflite_model_size = open(output_file, 'wb').write(tflite_model)


**To compile into edge-tpu :**

`edgetpu_compiler /research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/tflite/model8_seg.tflite`

and its outputs:

Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 592 ms.

Input model: /home/paul/base/UPM/proyecto_robot/Coral/models/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/tflite/model8_seg.tflite
Input size: 3.97MiB
Output model: model8_seg_edgetpu.tflite
Output size: 4.27MiB
On-chip memory used for caching model parameters: 1.88MiB
On-chip memory remaining for caching model parameters: 4.92MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 101
Operation log: model8_seg_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.

Number of operations that will run on Edge TPU: 59
Number of operations that will run on CPU: 42
See the operation log file for individual operation details.



Why i run only 59 of 101 operation in tpu. ¿what is my mistake?
I saw quantization in deeplad page 

https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md

how is the correct way?

**Comment by paul218** [comment]
> To be very specific what I'm doing is:
> 
> 1.)
> Take: edgetpu-deeplab_2020_03_09.tar.gz
> Downloaded from: http://download.tensorflow.org/models/edgetpu-deeplab_2020_03_09.tar.gz
> 
> 2.) Train:
> 
> cwd=`pwd`
> export PYTHONPATH=$PYTHONPATH:$cwd:$cwd/slim
> 
> PATH_TO_DATASET=/root/models/research/deeplab/datasets/test320/tfrecord
> PATH_TO_TRAINED_FLOAT_MODEL=/root/edgetpu-deeplab/model.ckpt
> PATH_TO_TRAIN_DIR=./traindir-edgetpu-test320
> 
> python3 deeplab/train.py
> --logtostderr
> --train_split="train"
> --model_variant="mobilenet_edgetpu"
> --decoder_output_stride=''
> --aspp_convs_filters=256
> --quantize_delay_step=0
> --output_stride=16
> --train_crop_size="320,320"
> --train_batch_size=4
> --initialize_last_layer=false
> --training_number_of_steps=10
> --fine_tune_batch_norm=true
> --tf_initial_checkpoint=${PATH_TO_TRAINED_FLOAT_MODEL}
> --train_logdir=${PATH_TO_TRAIN_DIR}
> --dataset_dir=${PATH_TO_DATASET}
> --last_layers_contain_logits_only=False
> --decoder_filter=2
> --num_classes=2
> --dataset="test320"
> 
> 3.) Freeze the checkpoint:
> 
> cwd=`pwd`
> export PYTHONPATH=$PYTHONPATH:$cwd:$cwd/slim
> 
> python3 deeplab/export_model.py
> --logtostderr
> --checkpoint_path=./traindir-edgetpu-test320/model.ckpt-10
> --export_path=./deeplabv3_test320_quantized_frozen_graph.pb
> --quantize_delay_step=0
> --model_variant="mobilenet_edgetpu"
> --num_classes=2
> --inference_scales=1.0
> --crop_size=320
> --crop_size=320
> 
> 4.) Convert to TfLite
> 
> tflite_convert
> --graph_def_file=./deeplabv3_test320_quantized_frozen_graph.pb
> --output_file=./deeplabv3_test320_quantized_frozen_graph.tflite
> --output_format=TFLITE
> --input_shape=1,320,320,3
> --input_arrays="MobilenetEdgeTPU/MobilenetEdgeTPU/input"
> --inference_type=QUANTIZED_UINT8
> --inference_input_type=QUANTIZED_UINT8
> --std_dev_values=128
> --mean_values=128
> --change_concat_input_ranges=true
> --output_arrays="ArgMax"
> 
> 5.) Compile to edgetpu:
> edgetpu_compiler -o /tmp/compiled_model deeplabv3_test320_quantized_frozen_graph.tflite
> 
> Everything _seems_ OK , but step 5 miserably fails with no meaningful error message.
> 
> Gergely

you must perform post-quantization to your tensorflow-lite model

**Comment by jake-g** [comment]
> 
> you must perform post-quantization to your tensorflow-lite model

Is there a difference between 'post-quantization' and 'quantization aware training', as described in [quantize.md](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md)

I think Gergely did perform 'quantization aware training' by using `--quantize_delay_step=0`

Im having pretty much the exact same issue, but posted onto this issue: https://github.com/google-coral/edgetpu/issues/315
Still havnt figured out a solution

**Comment by pranavgundewar** [comment]
I have followed this thread and I am doing exactly as jake-g  to Gergely mentioned! I am facing similar issues and unable to convert any model using edgetpu compiler

**Comment by desmoteo** [comment]
I finally managed to make it compile, if I run training with the same flags and doing post-quantization as reported by @paul218  in #325 . But if I make changes to this configuration, e.g. change the crop size, compilation hangs again (even if the quantized tflite model seems well converged and is producing good results).
