### ISSUE TITLE
Rule is missing dependency declarations for the following files included by 'flatbuffers/src/flatc_main.cpp':

### ISSUE THREAD

**Issue by arun-kumark** [google-coral/edgetpu#271]
Dear all,

On my Google Coral device. I am facing the problem in building up the CPP packages.
When I compile with the following command, I faced the following logs errors. 

`bazel build --sandbox_debug --subcommands --experimental_repo_remote_exec --compilation_mode=opt --define darwinn_portable=1 --action_env PYTHON_BIN_PATH=/usr/bin/python3 --cpu=k8 --embed_label='TENSORFLOW_COMMIT=f394a768719a55b5c351ed1ecab2ec6f16f99dd4' --stamp --crosstool_top=@crosstool//:toolchains --compiler=gcc //tflite/public:libedgetpu_direct_all.so`

Could you let me know, what possibile go wrong ?

```
 ERROR: /root/.cache/bazel/_bazel_root/9433fbfc721f4a1cbf318e36d08e72c4/external/flatbuffers/src/BUILD:40:11: undeclared inclusion(s) in rule '@flatbuffers//src:flatc':
this rule is missing dependency declarations for the following files included by 'flatbuffers/src/flatc_main.cpp':
  '/usr/lib/gcc/aarch64-linux-gnu/10/include/stddef.h'
  '/usr/lib/gcc/aarch64-linux-gnu/10/include/stdarg.h'
  '/usr/lib/gcc/aarch64-linux-gnu/10/include/stdint.h'
1606495016.102742809: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1606495016.103021967: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1606495016.104219364: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 26445
1606495016.104645223: src/main/tools/linux-sandbox-pid1.cc:434: Pid1Main started
1606495016.105035537: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1606495016.106281030: src/main/tools/linux-sandbox-pid1.cc:176: working dir: /root/.cache/bazel/_bazel_root/9433fbfc721f4a1cbf318e36d08e72c4/sandbox/linux-sandbox/7/execroot/libedgetpu
1606495016.106442717: src/main/tools/linux-sandbox-pid1.cc:208: writable: /root/.cache/bazel/_bazel_root/9433fbfc721f4a1cbf318e36d08e72c4/sandbox/linux-sandbox/7/execroot/libedgetpu
1606495016.106493352: src/main/tools/linux-sandbox-pid1.cc:208: writable: /tmp
1606495016.106530588: src/main/tools/linux-sandbox-pid1.cc:208: writable: /dev/shm
1606495016.106884676: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /
1606495016.106953062: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev
1606495016.106998658: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /dev/shm
1606495016.107035653: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev/pts
1606495016.107070053: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev/hugepages
1606495016.107104474: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /dev/mqueue
1606495016.107141334: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys
1606495016.107180005: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/kernel/security
1606495016.107229045: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup
1606495016.107277721: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/unified
1606495016.107324331: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/systemd
1606495016.107370886: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/cpuset
1606495016.107411457: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/net_cls,net_prio
1606495016.107451942: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/freezer
1606495016.107618904: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/memory
1606495016.107674390: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/hugetlb
1606495016.107717970: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/cpu,cpuacct
1606495016.107762801: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/blkio
1606495016.107805441: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/devices
1606495016.107848056: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/pids
1606495016.107900687: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/fs/cgroup/perf_event
1606495016.107946207: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/kernel/debug
1606495016.107987598: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /sys/kernel/config
1606495016.108024938: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /proc
1606495016.108061894: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /run
1606495016.108104854: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /run/lock
1606495016.108143054: src/main/tools/linux-sandbox-pid1.cc:279: remount ro: /run/user/0
1606495016.108212115: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /root/.cache/bazel/_bazel_root/9433fbfc721f4a1cbf318e36d08e72c4/sandbox/linux-sandbox/7/execroot/libedgetpu
1606495016.108258786: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /root/.cache/bazel/_bazel_root/9433fbfc721f4a1cbf318e36d08e72c4/sandbox/linux-sandbox/7/execroot/libedgetpu
1606495016.108295021: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /tmp
1606495016.108327936: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /dev/shm
1606495016.108471473: src/main/tools/linux-sandbox-pid1.cc:363: calling fork...
1606495016.109281946: src/main/tools/linux-sandbox-pid1.cc:393: child started with PID 2
1606495037.652245081: src/main/tools/linux-sandbox-pid1.cc:410: wait returned pid=2, status=0x00
1606495037.652407947: src/main/tools/linux-sandbox-pid1.cc:428: child exited normally with code 0
1606495037.702402378: src/main/tools/linux-sandbox.cc:233: child exited normally with code 0
Target //tflite/public:libedgetpu_direct_all.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 23.925s, Critical Path: 22.02s
INFO: 7 processes: 7 internal.
FAILED: Build did NOT complete successfully
make: *** [Makefile:97: libedgetpu-direct] Error 1
```
Thank you
Kind Regards
Arun

**Comment by Namburger** [comment]
Hi @arun-kumark !
What target are you building (you can give the full command used for building) and 
> On my Google Coral device.

are you trying to build this on the dev board?

**Comment by arun-kumark** [comment]
Hi Namburger,

I am building on the following environment:

**Target processor:**
Texas Instruments ARM AM 6548 (+Secure Boot), 2 GB DDR4 RAM 
Quad Core processor (AM6548 HS)
2 GB RAM (DDR4)
16GB eMMc
included battery for RTC
preinstalled Simatic Industrial OS 2.0 (incl. License) on the eMMc

**OS**
It is based on Debian 9 (Long Term Support Kernel)

USB Google coral device is attached with the IOT device.

Kind Regards
Arun

**Comment by Namburger** [comment]
hi again - 
Sorry, what I meant to ask was which [binary target](https://github.com/google-coral/edgetpu/blob/master/Makefile#L100) are you building and on what platform are you building from?
The Makefile that we provided can only be built on an x86_64 machine and it can cross compiles for [these architectures](https://github.com/google-coral/edgetpu/blob/master/Makefile#L28).
you may want to use our provided docker image to ensure the environment has all required dependencies:
```
make DOCKER_IMAGE=debian:buster DOCKER_CPUS="k8 armv7a aarch64" DOCKER_TARGETS=tests docker-build
```

FYI, this repo is now deprecated in favor of pycoral and libcoral, it can still be made to work, but you'll have to use our egacy runtime package. Just making sure that you are aware of that?

**Comment by arun-kumark** [comment]
Thanks for the help Namburger.
I will check this once, and will update soon here.

**Comment by arun-kumark** [comment]
Hi Nam,
I am still doing it, 

Could you explan, what is "but you'll have to use our legacy runtime package". Is there disadvantage of using this package over building ourselves?

Also would like to understand "deprecated in favor of pycoral and libcoral," some of my team is using PyCoral, and it works well with EdgeTPU. It means, we should/shouldn't use pycoral?

Could you explan little more on this?

Kind Regards
Arun

**Comment by arun-kumark** [comment]
Hi Nam,
I am sorry to mix the question with already running one. You may direct me to some link for this.

I need one help in understanding the Google Coral device usages as a commerical product.

Could you point me some reference/document which can help me to understad the software components/packages, dependencies and libraries that require software licensing if we plan to sell it as a companion hardware.

Thank you
Kind Regards
Arun

**Comment by Namburger** [comment]
@arun-kumark Sorry, I mean that this repo is deprecated and you should pursuit pycoral (for python) and libcoral (for c++) intead of this repo entirely. Here is the full release notes: https://coral.ai/news/updates-11-2020


> I need one help in understanding the Google Coral device usages as a commerical product.
Could you point me some reference/document which can help me to understad the software components/packages, dependencies and libraries that require software licensing if we plan to sell it as a companion hardware.

@usbguru tag team on this one :)

**Comment by usbguru** [comment]
@arun-kumark 
When you buy a Coral device from Google, it is understood you are prototyping or shipping a commercial product.  The primary software libraries you will use are these:

https://github.com/google-coral/pycoral
https://github.com/google-coral/libcoral
https://github.com/google-coral/libedgetpu
https://github.com/tensorflow/tensorflow

Each of these are open source with the Apache 2.0 license.  Your legal team can determine if that license is suitable for your business model.

OpenCV is another library you may want to use: https://github.com/opencv/opencv this uses the Apache 2.0 license.
Gstreamer is another popular library: https://github.com/GStreamer/gstreamer this uses the GPL2 license.

**Comment by arun-kumark** [comment]
Thank you for listing the packages. I will take it forward with my legal team.

thanks again :)
