### ISSUE TITLE
Internal compiler error. Aborting! Tiny_YOLOV4

### ISSUE THREAD

**Issue by ZhouKai90** [google-coral/edgetpu#275]
Edge TPU Compiler version 14.1.317412892
TensorFlow 2.1.0
I used edgetpu_compiler to comiled my int8 integer only tfltite model and got the abotting error.Could you guys take a look at this model?
[tiny-yolov4.tflite](https://drive.google.com/file/d/16ciUjamnhHUp1OefWAs-0_G9MVxMgR0o/view?usp=sharing)

**Comment by Namburger** [comment]
@Naveen-Dodda could you take a look at this one?

**Comment by Naveen-Dodda** [comment]
Yolo5 can be mapped to edgetpu please find the [models here ](https://github.com/zye1996/Yolov5_EdgeTPU)
