### ISSUE TITLE
putting input layer as opposed to output layer on cpu

### ISSUE THREAD

**Issue by arccoxx** [google-coral/edgetpu#276]
Hello,

I would like to run universal sentence transformer models using edge tpu. I cannot think of a way to do this as the model accepts text only as input and the tpu can only accept numerical input. Can we load the input layer to the cpu so it can accept text preprocess etc and then shuttle the rest of the computation to the tpu? The output is numerical so I believe this should be possible.
 
If not can we work to develop a method to input text? I'd spend the time if its possible. 

Best,

Aidan Collins

**Comment by Naveen-Dodda** [comment]
Hello Aidan, 

Yes what you mentioned is right, you can perform all the pre processing task on cpu and feed numerical to the model which can be mapped to edgetpu. For instance you can encode the text data with numbers (save key:values in dict which can be used to decode). Now you can build your model with numerical input which can mapped to edgetpu with supported ops.

Hope this helps, 

Stay Safe, 
Naveen
