### ISSUE TITLE
[Future Request] EfficientDet D0 conversion support by EdgeTPU Compiler

### ISSUE THREAD

**Issue by PINTO0309** [google-coral/edgetpu#279]
## 1. Overview
I have succeeded in generating a .tflite of EfficientDet D0 for the Full Integer Quantization model. There seems to be no problem in the structure of the model, but when compiled with edgetpu_compiler, the process is aborted. If I can figure out what is causing the error, I will adjust the model.
![Screenshot 2020-12-11 00:49:40](https://user-images.githubusercontent.com/33194443/101797340-4325bf80-3b4d-11eb-9036-ad8cf24d14c9.png)

### 2-1. Environment
- Ubuntu 18.04
- Edge TPU Compiler version 15.0.340273435
- TensorFlow version tf-nightly==2.5.0-dev20201210
- EfficientDet D0 (Yet-Another-EfficientDet-Pytorch-Convert-ONNX-TVM)

### 2-2. EfficientDet repository of citations
https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch.git
https://github.com/murdockhou/Yet-Another-EfficientDet-Pytorch-Convert-ONNX-TVM.git

### 2-3. EfficientDet D0 Full Integer Quantization tflite
tflite: https://drive.google.com/file/d/1blXmW5FMuKJCbv7h6g5uzS-628FAfZ40/view?usp=sharing

<details><summary><b>Model structure diagram of EfficientDet D0 Full Integer Quantization tflite</b></summary><div>

![efficientdet_d0_512x512_full_integer_quant tflite_](https://user-images.githubusercontent.com/33194443/101796637-774cb080-3b4c-11eb-9234-209e3957a302.png)

</div></details>

## 3. Appendix
https://github.com/PINTO0309/PINTO_model_zoo/tree/master/018_EfficientDet/09_pytorch_efficientdet_d0

**Comment by PINTO0309** [comment]
I have narrowed down the patterns that fail to compile. It appears that the complexity of the model structure probably correlates with the high input resolution.

## 1. MIRNet (Model used for validation)
**https://github.com/sayakpaul/MIRNet-TFLite.git**

## 2. TFLite file - Full Integer Quantization
**https://drive.google.com/file/d/12Jo_9rmslWHJOzGtjUyDYQHz3qvztv6V/view?usp=sharing**

## 3. Structure of the model

<details><summary><b>Model structure diagram of MIRNet Full Integer Quantization tflite</b></summary><div>

![mirnet_128x128_full_integer_quant tflite](https://user-images.githubusercontent.com/33194443/102363195-89b96500-3ff8-11eb-8432-7f0a93132697.png)

</div></details>

## 4. Test pattern
1. 512x512 ... compilation failure
2. 416x416 ... compilation failure
3. 320x320 ... compilation failure
4. 256x256 ... compilation failure
5. 128x128 ... compilation failure
6. 64x64 ... compilation success

## 5. Consideration
This is just my guess, but it may be that the hardware characteristics of EdgeTPU do not allow complex, high resolution models to be compiled.

**Comment by zshn25** [comment]
> I have narrowed down the patterns that fail to compile. It appears that the complexity of the model structure probably correlates with the high input resolution.
> 
> ## 1. MIRNet (Model used for validation)
> **https://github.com/sayakpaul/MIRNet-TFLite.git**
> 
> ## 2. TFLite file - Full Integer Quantization
> **https://drive.google.com/file/d/12Jo_9rmslWHJOzGtjUyDYQHz3qvztv6V/view?usp=sharing**
> 
> ## 3. Structure of the model
> Model structure diagram of MIRNet Full Integer Quantization tflite
> ## 4. Test pattern
> 1. 512x512 ... compilation failure
> 2. 416x416 ... compilation failure
> 3. 320x320 ... compilation failure
> 4. 256x256 ... compilation failure
> 5. 128x128 ... compilation failure
> 6. 64x64 ... compilation success
> 
> ## 5. Consideration
> This is just my guess, but it may be that the hardware characteristics of EdgeTPU do not allow complex, high resolution models to be compiled.

+1 With lower resolution input, all operations are mapped on TPU but as resolution increases, less number of ops are mapped on TPU. At some point, it doesn't even compile anymore.

**Comment by PINTO0309** [comment]
I'm going to close it since I can't seem to get any response. Too much time has passed and it no longer makes sense, so I'm moving on to EfficientDet-lite.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/103_EfficientDet_lite
