### ISSUE TITLE
What are the constraints to make ResizeNearestNeighbor work on Edge TPU compiler

### ISSUE THREAD

**Issue by dtlam26** [google-coral/edgetpu#283]
Eventhough I have successed int8 quantization, I recently experience failing on ResizeNearestNeighbor in Edge TPU. In the coral official website, they state that ResizeNearestNeighbor is allowed. So why when I am checking the condition on graph, it fails?
![image](https://user-images.githubusercontent.com/27914179/102594647-cf417380-4159-11eb-8b13-0b6b81d5a50e.png)

Furthermore, when I check the frozen graph before tflite int8 conversion, it does not have Fake quantize node, is this the reason?
![image](https://user-images.githubusercontent.com/27914179/102594942-3e1ecc80-415a-11eb-9ed5-90733002aeee.png)

My edgecompiler cannot perform this and does not give any clue
```
Edge TPU Compiler version 14.1.317412892

Internal compiler error. Aborting! 
```
 My quantized model is stored here: [https://drive.google.com/drive/folders/14L4Yrsk_9rB6UOgJn8La7n1epanAFI0B?usp=sharing]

**Comment by Namburger** [comment]
Hello @dtlam26, is this still failing with the latest compiler release?

**Comment by dtlam26** [comment]
Yes, I have built from sources both 14.1.317412892 and 15.0.340273435 and still failed with no logging.
```
$ edgetpu_compiler retina.tflite 
Edge TPU Compiler version 15.0.340273435

Internal compiler error. Aborting! 
```
You can check my models I attached above to verify,

**Comment by Namburger** [comment]
@dtlam26 oh, sorry, I suggest trying it with the compiler from our apt repo, it is up to 15.x now, the edgetpu repo was deprecated, more info here:
https://coral.ai/news/updates-11-2020

**Comment by dtlam26** [comment]
What about the pycoral, without edgeTPU compiler, how can I compile my model to fit it edgeTPU configuration? By the pycoral compiler or sth?

As I attached above, I have try to compile with 15.0 version and it still failed. Is that the lastest version?. 

Can you give me some details instruction about which steps I should do to get the version you mention?

**Comment by dtlam26** [comment]
For the pycoral, I install it from wheel and got the missing in runtime as bellow:
```
ERROR: Could not find a version that satisfies the requirement tflite-runtime==2.5.0 (from pycoral==1.0.0) (from versions: none)
ERROR: No matching distribution found for tflite-runtime==2.5.0 (from pycoral==1.0.0)
```

**Comment by manoj7410** [comment]
@dtlam26 You can get the tflite-runtime whl at : https://www.tensorflow.org/lite/guide/python
and then try to install the pycoral.

**Comment by dtlam26** [comment]
> @dtlam26 You can get the tflite-runtime whl at : https://www.tensorflow.org/lite/guide/python
> and then try to install the pycoral.

appreciate, I got pycoral now. But the newest edge_compiler from apt still fails:
```
edgetpu_compiler retina.tflite
Edge TPU Compiler version 15.0.340273435

Internal compiler error. Aborting! 

```

**Comment by manoj7410** [comment]
@dtlam26 There is a compiler binary available at https://github.com/google-coral/edgetpu/tree/master/compiler/x86_64/edgetpu_compiler_bin , I am not sure about the version of this one since I am working on a Mac right now. Can you try this one and share the result ?

**Comment by dtlam26** [comment]
> @dtlam26 There is a compiler binary available at https://github.com/google-coral/edgetpu/tree/master/compiler/x86_64/edgetpu_compiler_bin , I am not sure about the version of this one since I am working on a Mac right now. Can you try this one and share the result ?

I have go to the location file, but can not execute with these errors:
```
figlet: relocation error: libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
dirname: relocation error: libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
dirname: relocation error: libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

However, I think that is the eel2 branch version, so I have checkout and compile, but still fails. You can verify with my model that I share in the drive above:

```
git checkout c48c888
./edgetpu_compiler retina.tflite 
Edge TPU Compiler version 14.1.317412892

Internal compiler error. Aborting! 
```

**Comment by Namburger** [comment]
@Naveen-Dodda could you check this one out?

**Comment by dtlam26** [comment]
> @Naveen-Dodda could you check this one out?

Yes, for clarify, I have tried to install with the `sudo apt install edge-compiler` at first. Then I go with the git compling method as shown above

**Comment by dtlam26** [comment]
From [this issue](https://github.com/google-coral/edgetpu/issues/31) with Upsampling module. Is it also because my model input for upsampling layer is too big to keep precision so that the compiler stop working?

**Comment by Naveen-Dodda** [comment]
@dtlam26 If you are using tf1.x and want to map ResizeNearestNeighbor ops to edgetpu you need to chnage config of resize ops as following.
half_pixel_centers=True
tf.compat.v1.image.resize_nearest_neighbor(
    images, size, align_corners=False, name=None, half_pixel_centers=True
)

If you train and export model with TF2.x 
half_pixel_centers=True is default in TF2.x so you edgeptu_compiler should map the ops
