### ISSUE TITLE
TFLite quantization of bias

### ISSUE THREAD

**Issue by johannes-do** [google-coral/edgetpu#284]
In the docu regarding quantization of models (https://coral.ai/docs/edgetpu/models-intro/#quantization) this page of the tflite docu is linked: https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only.

But the tflite quantization uses int32 for biases and I do believe there is no way around this. Is this going to be an issue with the edgetpu? In case it is a note within the edgetpu docu would be good.

**Comment by Namburger** [comment]
Bias should be okay with int32, do you have a broken model you would like for us to take a look?

**Comment by johannes-do** [comment]
I compared the output of the quantized TFLite model (on CPU) vs the compiled model on the EdgeTpu and they seem to have the same output. So that would support the claim that int32 should be ok.
I am just surprised this is working since the EdgeTpu states all tensors must be 8-bit quantized. Anyway, thanks for the offer, but I think this can be closed.
