### ISSUE TITLE
Cannot run inference on *_edgetpu.tflite model

### ISSUE THREAD

**Issue by hoangminhtoan** [google-coral/edgetpu#285]
My host computer: 
- ubuntu 18.04
- Edge TPU Compiler version 15.0.340273435

Google Coral Board
- Name: tflite-runtime version: 2.1.0.post1

I clone this repo: https://github.com/google-coral/example-object-tracker today. there is no problem when I run an inference with non-edgetpu tflite models. However, it shows an error even with the model which is downloaded from the above repo: 

`RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.`

I re-compile the model on my host computer. (e.g. mobilenet_ssd_v2_coco_quant_postprocess.tflite). and it shows in file log like below:

`Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 697 ms.

Input model: mobilenet_ssd_v2_coco_quant_postprocess.tflite
Input size: 5.89MiB
Output model: mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
Output size: 6.57MiB
On-chip memory used for caching model parameters: 6.35MiB
On-chip memory remaining for caching model parameters: 1.39MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 99
Operation log: mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 98
Number of operations that will run on CPU: 1
See the operation log file for individual operation details.`

![Screenshot from 2020-12-19 13-46-47](https://user-images.githubusercontent.com/1559257/102680965-ade79280-4200-11eb-87b3-099925787f0c.png)

How can I fix this problem! Thanks

**Comment by Namburger** [comment]
hello @hoangminhtoan the tflite_runtime package version should be 2.5.0 with the latest edgetpu release, please update from here:
https://www.tensorflow.org/lite/guide/python

Thanks

**Comment by hoangminhtoan** [comment]
> hello @hoangminhtoan the tflite_runtime package version should be 2.5.0 with the latest edgetpu release, please update from here:
> https://www.tensorflow.org/lite/guide/python
> 
> Thanks

Thanks, Nam,

However, I tried both the arm and linux_x86_64 version but both didn't work

![Screenshot from 2020-12-21 09-48-04](https://user-images.githubusercontent.com/1559257/102728914-a7c4f380-4371-11eb-8d69-04879c7ae1e3.png)

**Comment by hoangminhtoan** [comment]
Thanks, Nam

It works! so I'll close this topic
