### ISSUE TITLE
Internal compiler error on model with multiple inputs

### ISSUE THREAD

**Issue by markus-k** [google-coral/edgetpu#287]
I'm trying to compile a model that has multiple input tensors with the EdgeTPU compiler. I couldn't find any limitations about this in the [documentation on model requirements](https://coral.ai/docs/edgetpu/models-intro/#model-requirements).

This is my model. It's more of a test rather than anything thats supposed to give a meaningful output:
```python
# TensorFlow version 2.4.0
i1 = tf.keras.Input(shape=(240,320,3))
i2 = tf.keras.Input(shape=(3))

x = layers.Conv2D(8, (3, 3), activation='relu')(i1)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(16, (3, 3), activation='relu')(x)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(32, (3, 3), activation='relu')(x)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Flatten()(x)

x = layers.Concatenate()([x,i2])
x = layers.Dense(64, activation='relu')(x)
outputs = layers.Dense(1)(x)

model = tf.keras.Model(inputs=[i1, i2], outputs=outputs)
```

This model converts and quantizes fine using the `TFLiteConverter`:
```python
def representative_dataset():
    for _ in range(10):
        yield [tf.zeros((1,3)),
                tf.zeros((1,240,320,3))]
    
converter = tf.lite.TFLiteConverter.from_saved_model('test.tf')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()
```

The EdgeTPU Compiler fails though:
```
$ edgetpu_compiler -s test_quant.tflite 
Edge TPU Compiler version 15.0.340273435

Internal compiler error. Aborting!
```

The background on having multiple input tensors is supplying additional data for an input image to the network (e.g. sensor data).

Is this a (known) limitation of the EdgeTPU (compiler) or a bug?

**Comment by Namburger** [comment]
@Naveen-Dodda could you take a look at this one?

**Comment by Kuan-ChiehHsu** [comment]
I have similar issue.
I also tried multiple inputs with simple conv op for each of them and concatenate before output. But I get the error message instead:

**F tensorflow/lite/toco/graph_transformations/quantize.cc:606] Check failed: is_rnn_state_array
Aborted (core dumped)**

Which I don't think there is any rnn design is involved.

**Comment by Naveen-Dodda** [comment]
@jk78346 

If you are still facing this issue Can you share more details reproduce this issue. 

@markus-k  I have tried to convert your model but the tflite_convert fails to convert 

input->dims->size != 4 (2 != 4)Node number 0 (CONV_2D) failed to prepare.

Can you try to convert model form tf.lite.TFLiteConverter.from_keras_model instead of Saved_model

**Comment by hjonnala** [comment]
@markus-k  I am able to convert the multi input model and compile it with edgetpu compiler. Please check the attachment for details.

Thanks.

[edgetpu_287.tar.gz](https://github.com/google-coral/edgetpu/files/7288923/edgetpu_287.tar.gz)
