### ISSUE TITLE
The output result of the MUL operator is different between EdgeTPU and CPU.

### ISSUE THREAD

**Issue by nadongguri** [google-coral/edgetpu#288]
Dear coral support team,

if any of the users have similar experiences, I would like to get help, so I post an issue.

I made a simple model that takes an input of 1x3x3 and a mul operator with 3 weight parameters. (The parameter value is learned by quantization-aware training.)
When running this model with the cpu backend, the result is the same as calculated by hand.
However, the result of the edgetpu path is different except when the input is -20.
It looks as if the scale value for each weight is different.
The calculation formula was referred to the paper "Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference".
I'm really wondering why this result happens.

Edge TPU Compiler version 14.1.317412892 (though, I checked from version 2.0 and the same problem occurred.)
libedgetpu version : Frogfish
Attached models : mul_issue.tflite, mul_issue_edgetpu.tflite

Regards,
nadongguri.

![image](https://user-images.githubusercontent.com/23691318/103197367-3fee4a00-4929-11eb-8322-11378fc2bec4.png)

[models.zip](https://github.com/google-coral/edgetpu/files/5746261/models.zip)

**Comment by Namburger** [comment]
@nadongguri thank for submitting, this looks like a compiler issue, do you mind submitting your inference script for both model also?

**Comment by nadongguri** [comment]
Dear @Namburger ,

here's the script file and the simple usage. :-)
> $python inf_and_cmp_two_models.py --model mul_issue.tflite  --model2 mul_issue_edgetpu.tflite 
--model mul_issue.tflite
--model2 mul_issue_edgetpu.tflite
diff[0] : -31 vs -71
diff[1] : -17 vs -43
diff[2] : 14 vs -59
diff[3] : -31 vs -62
diff[4] : -43 vs -20
diff[5] : 4 vs -53
diff[6] : -31 vs 8
diff[7] : -55 vs -10
diff[8] : -33 vs -30
$python inf_and_cmp_two_models.py --model mul_issue.tflite  --model2 mul_issue.tflite 
--model mul_issue.tflite
--model2 mul_issue.tflite
the results are the same

[script.zip](https://github.com/google-coral/edgetpu/files/5748184/script.zip)

**Comment by manoj7410** [comment]
@nadongguri Were you able to fix this ?

**Comment by manoj7410** [comment]
Feel free to reopen if this issue still persists.
