### ISSUE TITLE
 edgetpu/test_data/coco_labels.txt missing some labels

### ISSUE THREAD

**Issue by robmarkcole** [google-coral/edgetpu#29]
There are [supposed to be 90 labels](https://coral.withgoogle.com/models/), but there are only 80. e.g. number `11` is missing below:
```
0  person
1  bicycle
2  car
3  motorcycle
4  airplane
5  bus
6  train
7  truck
8  boat
9  traffic light
10  fire hydrant
12  stop sign
```

**Comment by Namburger** [comment]
@robmarkcole 
There are actually types 91 from coco as mentioned [here](http://cocodataset.org/#home). However the other types are not used for object detection so it is not in this label file.
