### ISSUE TITLE
EdgeTPU Compiler - Same model but `Internal compiler error`

### ISSUE THREAD

**Issue by keesschollaart81** [google-coral/edgetpu#291]
As described [here](https://github.com/hhk7734/tensorflow-yolov4/issues/49#issuecomment-748857685) in more detail; I have trained a yolov4 model with my own data, conversion to TF Lite works fine all the time, however... The TF Lite models that I convert from weights early on in the training run can be converted to EdgeTPU but when the training run progresses, they cannot.

Looking at the TF Lite files with Netron there seems to be almost no difference. In the linked issue I included some images of the net to compare. Also the weights and TF Lite files to look at/test with can be downloaded [here](https://1drv.ms/u/s!AvX-n0DZ_wi2kcUpdYQml1Y2uW9wGA?e=UPBNLF). The TF Lite models seems to work fine. I guess this issue is either caused by the TF Lite Converter or caused by the Edge TPU Compiler but as only the latter gives a (very generic) error I'm reporting here first.

**Comment by Namburger** [comment]
@Naveen-Dodda could you take a look?

**Comment by djalusic** [comment]
@keesschollaart81 have you had any progress with this issue? I am encountering the same problem.

**Comment by keesschollaart81** [comment]
No, no, still no solution! I switched to Yolov5 which is now compatible with EdgeTPU and does compile... 

However, I'm still interested to hear why this yolov4 model cannot be converted by the edgetpu compiler which is why I did not close this issue.

**Comment by Naveen-Dodda** [comment]
Hello @keesschollaart81 

I have tired to run inference with both the tflite models. But aml-new-run-70.tflite model fails to run inference. Can you try to run inference on cpu model as well. 

It seems like the issue is with tflite_convert or yolo.save_as_tflite  rather than edgetpu_compiler.

**Comment by Naveen-Dodda** [comment]
Closing this issue due lack of activity. Please feel free to open if the issue persists
