### ISSUE TITLE
missing dependency to run example

### ISSUE THREAD

**Issue by dothebart** [google-coral/edgetpu#293]
Trying to run the examples referenced here:
https://coral.ai/docs/accelerator/get-started/#2-install-the-tensorflow-lite-library
in a debian buster chroot. Needed to add: 
```
apt-get install python3-imageio
```
in order to get the example running. Now its complaining: 
```
Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 97, in main
    labels = load_labels(args.labels) if args.labels else {}
  File "classify_image.py", line 55, in load_labels
    with open(path, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/inat_bird_labels.txt'
```

**Comment by Namburger** [comment]
Did you run the `bash install_requirements.sh`? It supposed to download the model for you

**Comment by dothebart** [comment]
hm, yes - I did that; though it downloaded something else when invoking it again now. Maybe it errored out beforehand? 
python3-imageio seems to be missing from `python3 -m pip install numpy Pillow` anyhow?

**Comment by dothebart** [comment]
hm, next try: 
```
Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 100, in main
    interpreter.allocate_tensors()
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Internal: Unsupported data type in custom op handler: 44383312Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.
```
re/plugging the Coral didn't help.

**Comment by Namburger** [comment]
@dothebart that means libedgetpu version isn't matching with tflite_runtime version. The installation steps on our coral.ai page should give you the exact version you need, some of the older tutorials I found online will only complicates things. Can you share the outputs of this command with me?

```
python3 -c 'print(__import__("tflite_runtime").__version__)'
dpkg -l | grep edgetpu
```

**Comment by dothebart** [comment]
Hi, 
due to python 3.9 not yet being supported I'm working with a buster chroot:
```
root@bithorizon:/home/willi/src/tf/tensorflow-lite-demo/od-api/models/research# python3 -c 'print(__import__("tflite_runtime").__version__)'
2.5.0
root@bithorizon:/home/willi/src/tf/tensorflow-lite-demo/od-api/models/research# dpkg -l | grep edgetpu
ii  libedgetpu1-legacy-std:amd64  15.0                         amd64        Support library for Edge TPU
rc  libedgetpu1-max:amd64         15.0                         amd64        Support library for Edge TPU
ii  python3-edgetpu               15.0                         amd64        Edge TPU Python API
```

**Comment by hjonnala** [comment]
@dothebart python3.9 is supported now. Please let us know if you are still facing any issues.
