### ISSUE TITLE
After connecting camera modul, device can not reboot

### ISSUE THREAD

**Issue by mpreach** [google-coral/edgetpu#298]
I tried to connect the camera module to a dev board mini, after connecting the board can not boot anymore. Reproducible. I had to do a "Force-boot into fastboot mode" to get the board up and running again.

Looks like the error is based on the looked root user account.
`
06:10:58.881 -> system logs, "systemctl reboot" to r
06:10:58.881 -> Cannot open access to console, the root account is locked.
06:10:58.881 -> See sulogin(8) man page for more details.
`
The boot process stops at:

`
06:11:01.725 -> [    9.990752] Bluetooth: hci0: unexpected event for opcode 0xfcd1
06:11:25.487 -> [   33.757745] usb0_vbus: disabling
06:11:25.487 -> [   33.760987] usb0_vbus_old: disabling
06:11:25.487 -> [   33.764602] backlight_vbus: disabling
06:11:25.487 -> [   33.768382] ldo_vm25: disabling
`

Mendel version: excelsior-eagle-20201210233645

Any suggestion or recommendations?

**Comment by Namburger** [comment]
Hello @mpreach I'm suspicious that something went wrong using the flash process which causes some missing configs. Although I wouldn't expect it to be booting until you install a camera though o_0
Could you try reflashing it again?

**Comment by mpreach** [comment]
Hello @Namburger. It tried to flash without the camera connected. Same result..... but when I flashed with camera connected, it worked. So fine now for me.
