### ISSUE TITLE
Running outside of docker

### ISSUE THREAD

**Issue by Arjuna197** [google-coral/edgetpu#3]
was running into "missing header file glibc_compat.h" when trying to run the makefile on an ubuntu desktop. 

found https://coral.googlesource.com/edgetpu-native/+/refs/heads/release-chef/tools/Dockerfile.16.04

sudo touch /usr/include/glibc_compat.h

Build successfully completes at this point, but I'm left wondering if creating an empty header file if needed for the build isn't something the build files could do themselves

**Comment by manoj7410** [comment]
Can you please share the link from where are you following the instructions to reproduce this issue?

**Comment by Namburger** [comment]
hi @Arjuna197 glibc_compat.h maybe you can copy it from here?
You can modify the main Makefile at line 39 (require sudo access):
```
 39 ifeq ("$(CPU)", "k8")
 40   ifeq ("$(wildcard $("/usr/include/glibc_compat.h"))","")
 41   GLIBC_COMPAT_PATH := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))docker/glibc_compat.h
 42   $(shell sudo cp -f ${GLIBC_COMPAT_PATH} /usr/include)
 43   endif
 44 BAZEL_BUILD_FLAGS += --copt=-includeglibc_compat.h

```

**Comment by dmitriykovalev** [comment]
@Arjuna197  You are right, we can improve that part of our build system.  Please do not use `edgetpu-native` repo, it was merged into this one. @Namburger pointed to the correct new location of `glibc_compat.h` file.
