### ISSUE TITLE
YOLOv4 compilation

### ISSUE THREAD

**Issue by parthjdoshi** [google-coral/edgetpu#301]
Hello,

I have been trying to convert YOLOv4 for the Coral USB Accelerator, but keep facing one issue after the other. Now, I am having trouble with the Exp and Log operators, which prevents my model from being quantized and therefore, compiled.
I have created an issue [here](https://github.com/tensorflow/tensorflow/issues/46395)

Can anyone help me with this? Has anyone successfully converted YOLOv4 for the Edge TPU?

**Comment by Namburger** [comment]
Hello Yolov4 definitely have some ops that isn't supported. Check [this table](https://coral.ai/docs/edgetpu/models-intro/#supported-operations) for reference.
The good new is there are ways to get around unsupported ops, which you can follow this thread for more info: https://github.com/google-coral/edgetpu/issues/272
