### ISSUE TITLE
Did I brick my coral dev mini?

### ISSUE THREAD

**Issue by jakowenko** [google-coral/edgetpu#302]
Just got a coral dev mini today and started to play around with it.

I was SSHed into it and was attempting to update it according to the documentation. I never rebooted it but when I looked back at the terminal window I was disconnected from the device. I can no longer see it via usb when I run `ls /dev/cu.usbmodem*`. Did I brick it somehow, or is there something I'm doing wrong that I can't see it listed as a usb modem anymore?

```
sudo apt-get update
sudo apt-get dist-upgrade
```

Could forcing my board into fastboot mode fix this using the following guide? https://coral.ai/docs/dev-board-mini/reflash/#force-boot-into-fastboot-mode

**Comment by Namburger** [comment]
@jakowenko Updating the board shouldn't break it at all, matter fact, I update it all the time and exclusively use ssh with my board. 
A couple of suggestions:
1) Could you try connecting the board form micro HDMI to a monitor to see if it boots up?
2) If you don't have one, you can also try reflashing it with the method you pointed out: https://coral.ai/docs/dev-board-mini/reflash/#force-boot-into-fastboot-mode

**Comment by jakowenko** [comment]
@Namburger thanks for the suggestions. I don't have a micro HDMI cable so I'll start with the reflash first and report back. I was just worried I somehow nuked my board, but the green light still turns on.

**Comment by jakowenko** [comment]
Force booting into fastboot and reflashing fixed the issue.

**Comment by Hazeline2018** [comment]
Hey guys, I have a dev mini board that doesn't work. So I'm trying to following the same forcing fastboot and reflashing procedure as you are doing. However, I tried using Ubuntu 20.04 installed on Win10, flashing failed. I'm wondering how exactly you did it and does it only work on true Linux machine as in the docs, it says the flashing procedure works for Mac and Linux only. Thanks for the help!

**Comment by spacebares** [comment]
hello, this is top result on google. Reboot did not help. I had to do a full powercycle to fix my stuck coral after some shenanigans.
