### ISSUE TITLE
Error building posenet.decoder.so

### ISSUE THREAD

**Issue by siddhantsahu** [google-coral/edgetpu#303]
The main issue I have is https://github.com/google-coral/project-posenet/issues/52 and I'm trying to build my own posenet.decoder.so using https://github.com/google-coral/edgetpu/issues/127#issuecomment-636036478 to solve that.

OS: Ubuntu 18.04
Tensorflow version: 1.14

Steps I followed:
- Install bazel, clone [project-posenet](https://github.com/google-coral/project-posenet) repo.
- Set env variable `LD_LIBRARY_PATH=/path/to/project-posenet/posenet_lib/x86_64/posenet.decoder.so`
- Clone [edgetpu](https://github.com/google-coral/edgetpu) repo and run `bazel build src/cpp/posenet/posenet_decoder.so`

This is causing the following error.
```INFO: Analyzed target //src/cpp/posenet:posenet_decoder.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/vilas/tpu/edgetpu/src/cpp/posenet/BUILD:91:10: Compiling src/cpp/posenet/posenet_decoder_tflite_plugin.cc failed: (Exit 1): gcc failed: error executing co
mmand /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 35 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 35 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
src/cpp/posenet/posenet_decoder_tflite_plugin.cc: In function 'TfLiteStatus {anonymous}::PrepareImpl(TfLiteContext*, TfLiteDelegate*)':
src/cpp/posenet/posenet_decoder_tflite_plugin.cc:103:10: error: 'unique_ptr' is not a member of 'std'
     std::unique_ptr<TfLiteIntArray, decltype(&TfLiteIntArrayFree)> nodes(
          ^~~~~~~~~~
src/cpp/posenet/posenet_decoder_tflite_plugin.cc:103:10: note: suggested alternative: 'unique_copy'
     std::unique_ptr<TfLiteIntArray, decltype(&TfLiteIntArrayFree)> nodes(
          ^~~~~~~~~~
          unique_copy
src/cpp/posenet/posenet_decoder_tflite_plugin.cc:103:35: error: expected primary-expression before ',' token
     std::unique_ptr<TfLiteIntArray, decltype(&TfLiteIntArrayFree)> nodes(
                                   ^
src/cpp/posenet/posenet_decoder_tflite_plugin.cc:103:37: error: expected primary-expression before 'decltype'
     std::unique_ptr<TfLiteIntArray, decltype(&TfLiteIntArrayFree)> nodes(
                                     ^~~~~~~~
src/cpp/posenet/posenet_decoder_tflite_plugin.cc:104:51: error: expected primary-expression before ')' token
         ConvertVectorToTfLiteIntArray({node_index}), TfLiteIntArrayFree);
                                                   ^
In file included from external/org_tensorflow/tensorflow/lite/context.h:19:0,
                 from ./src/cpp/posenet/posenet_decoder_op.h:4,
                 from src/cpp/posenet/posenet_decoder_tflite_plugin.cc:7:
src/cpp/posenet/posenet_decoder_tflite_plugin.cc:106:32: error: 'nodes' was not declared in this scope
         context, registration, nodes.get(), delegate));
                                ^
external/org_tensorflow/tensorflow/lite/c/common.h:169:10: note: in definition of macro 'TF_LITE_ENSURE_STATUS'
     if ((a) != kTfLiteOk) {      \
          ^
Target //src/cpp/posenet:posenet_decoder.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.525s, Critical Path: 0.37s
INFO: 13 processes: 13 internal.
FAILED: Build did NOT complete successfully
```

Any suggestions on how to solve this?

**Comment by Namburger** [comment]
ahh, all you need is an `#include <memory>` in `src/cpp/posenet/posenet_decoder_tflite_plugin.cc` LOL

**Comment by Namburger** [comment]
Also, this should already be fixed for posenet_decoder and I've prebuilt it in posenet decoder: https://github.com/google-coral/project-posenet/tree/master/posenet_lib

Lastly, this is what you want:
```
LD_LIBRARY_PATH=/path/to/project-posenet/posenet_lib/x86_64/
```

**Comment by siddhantsahu** [comment]
Thanks a lot @Namburger , now I can build the `posenet_decoder.so` and the `OSError: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29 not found (required by ./posenet_lib/x86_64/posenet_decoder.so)` issue seems resolved.

But, running `simple_pose.py` still brings another issue:
`RuntimeError: src/cpp/posenet/posenet_decoder_op.cc:128 (shorts->type == kTfLiteUInt8 || shorts->type == kTfLiteFloat32) was not true.Node number 3 (PosenetDelegateForCustomOp) failed to prepare.`
which is already described [here](https://github.com/google-coral/project-posenet/issues/52#issuecomment-759757914).

According to your [suggestion](https://github.com/google-coral/project-posenet/issues/52#issuecomment-760960888)
- I built `libedgetpu-std` using instructions in [libedgetpu](https://github.com/google-coral/libedgetpu) repo. Just ran `sudo make`.
- Copy `libedgetpu/out/throttled/k8/libedgetpu.so.1.0` to [edgetpu](https://github.com/google-coral/edgetpu) local repo, i.e. to `edgetpu/libedgetpu/throttled/k8/` because the install script references this location for installation.
- Install the edge tpu runtime using `./scripts/runtime/install.sh` in `edgetpu` repo.

Just to make sure that the install worked, I checked `/usr/lib/x86_64-linux-gnu/libedgetpu.so.1.0` which has the correct modified time. However, this still doesn't resolve the above `RuntimeError` issue when I run `simple_pose.py`. Would appreciate any thoughts on this or maybe I'm doing something incorrectly.

**Comment by siddhantsahu** [comment]
Update (with solution): Most likely the way I was building `posenet_decoder.so` was incorrect. The steps mentioned [here](https://github.com/google-coral/project-posenet/tree/posenet-decoder-build-instruction) worked:

- `git clone --recurse-submodules https://github.com/google-coral/libcoral`
- `cd libcoral`
- `bazel build --compilation_mode=opt --copt=-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION --verbose_failures --sandbox_debug --subcommands --define PY3_VER=38 --action_env PYTHON_BIN_PATH=/usr/bin/python3 --cpu=k8 --define darwinn_portable=1 --experimental_repo_remote_exec --crosstool_top=@crosstool//:toolchains --compiler=gcc --linkopt=-l:libusb-1.0.so --linkopt=-Wl,--strip-all //coral/posenet:posenet_decoder.so`

Copy `bazel-bin/coral/posenet/posenet_decoder.so` to `project-posenet/posenet_lib/x86_64` and run `simple_pose.py`

**Comment by yihsinhung** [comment]
> Update (with solution): Most likely the way I was building `posenet_decoder.so` was incorrect. The steps mentioned [here](https://github.com/google-coral/project-posenet/tree/posenet-decoder-build-instruction) worked:
> 
> * `git clone --recurse-submodules https://github.com/google-coral/libcoral`
> * `cd libcoral`
> * `bazel build --compilation_mode=opt --copt=-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION --verbose_failures --sandbox_debug --subcommands --define PY3_VER=38 --action_env PYTHON_BIN_PATH=/usr/bin/python3 --cpu=k8 --define darwinn_portable=1 --experimental_repo_remote_exec --crosstool_top=@crosstool//:toolchains --compiler=gcc --linkopt=-l:libusb-1.0.so --linkopt=-Wl,--strip-all //coral/posenet:posenet_decoder.so`
> 
> Copy `bazel-bin/coral/posenet/posenet_decoder.so` to `project-posenet/posenet_lib/x86_64` and run `simple_pose.py`
Hi siddhantsahu:
The ways can fix the issue after i test. Thank your information!
