### ISSUE TITLE
"Internal Compiler Issue" for Mobilenet SSD Edge TPU model - 16:9 aspect ratio

### ISSUE THREAD

**Issue by KushalHM** [google-coral/edgetpu#304]
Training a int_8 ssd_mobilenet_edgetpu object detection model at **480 x 270** image fixed size on a custom 1 class dataset (based on coco). Below is the pipeline.

[pipeline.txt](https://github.com/google-coral/edgetpu/files/5858467/pipeline.txt)

tflite conversion command:
tflite_convert   --output_file="edge_mobdet.tflite"   --graph_def_file="tflite_graph.pb"   --inference_type=QUANTIZED_UINT8   --input_arrays="normalized_input_image_tensor"   --output_arrays="TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3"   --mean_values=128   --std_dev_values=128   --input_shapes=1,270,480,3 --allow_custom_op

tflite conversion is successful, however edgetpu compiler fails:

**Edge TPU Compiler version 15.0.340273435

Internal compiler error. Aborting!** 

Same thing happening for different resolution (400 x 225, 432 x 243) of 16:9 aspect ratio.

Any idea if this is due to the non-square aspect ratio, if it so then how to train a 16:9 aspect ratio model to work on edge TPU?

**Comment by Namburger** [comment]
@Naveen-Dodda could you take a look at this one?

**Comment by Naveen-Dodda** [comment]
Hello Kushal, 

Non square aspect ratios should not be a problem. I have few questions to narrow down this issue, 
1. Which export script are using to export from checkpoint 
2. Are you using TF2.x object detection api for training or tflite_convert ?

**Comment by KushalHM** [comment]
> Hello Kushal,
> 
> Non square aspect ratios should not be a problem. I have few questions to narrow down this issue,
> 
> 1. Which export script are using to export from checkpoint
> 2. Are you using TF2.x object detection api for training or tflite_convert ?

Hi Naveen,
Thanks for the quick response.
 I am using object_detection/export_tflite_ssd_graph.py script to export and using TF1.15.0 version so TF1.x object detection api for training.

**Comment by KushalHM** [comment]
> Hello Kushal,
> 
> Non square aspect ratios should not be a problem. I have few questions to narrow down this issue,
> 
> 1. Which export script are using to export from checkpoint
> 2. Are you using TF2.x object detection api for training or tflite_convert ?

Hi @Naveen-Dodda , any update on this issue? 

Update from my side:
I was able to get a 16:9 aspect ratio work for a ssd_mobilenet_v2 feature extractor. However facing this same issue with ssd_mobilenet_edgetpu and ssd_mobiledet_edgetpu.

**Comment by Naveen-Dodda** [comment]
Hello Kushal, 

Are you able to compile a mobileDet with 16:9 aspect ratio or do you still have same issue
