### ISSUE TITLE
Problem in running test for 082_MediaPipe_Meet_Segementation

### ISSUE THREAD

**Issue by fransiskusyoga** [google-coral/edgetpu#306]
I tried to run test.py from this folder (082_MediaPipe_Meet_Segementation) and got error. If I use a model I downloaded from "sudo gdown --id 1qOlcK8iKki_aAi_OrxE2YLaw5EZvQn1S" , I get this error.
```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    interpreter.set_tensor(input_details, img)
  File "C:\Users\Fransiskus Yoga Esa\AppData\Local\Programs\Python\Python38\lib\site-packages\tflite_runtime\interpreter.py", line 423, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Dimension mismatch. Got 144 but expected 128 for dimension 1 of input 0.
PS D:\Users\Downloads\openCV\code\PINTO_model_zoo\082_MediaPipe_Meet_Segmentation>
```
if I use this model ( https://meet.google.com/_/rtcvidproc/release/336842817/segm_lite_v509.tflite ), I get this error
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    interpreter.allocate_tensors()
  File "C:\Users\Fransiskus Yoga Esa\AppData\Local\Programs\Python\Python38\lib\site-packages\tflite_runtime\interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Encountered unresolved custom op: Convolution2DTransposeBias.Node number 241 (Convolution2DTransposeBias) failed to prepare.
```

What model that I can use to run the test.py?

**Comment by Namburger** [comment]
Hello @fransiskusyoga 
Sorry but I don't know where to go from here. First I don't exactly know where you got the model or what test.py even have. 
From what I see:
1) For this issue:
```
ValueError: Cannot set tensor: Dimension mismatch. Got 144 but expected 128 for dimension 1 of input 0.
```
Means that your input shape is different than your the input tensor of the model that you're trying to feed the input in.
2) For this issue:
```
RuntimeError: Encountered unresolved custom op: Convolution2DTransposeBias.Node number 241 (Convolution2DTransposeBias) failed to prepare.
```
That's more like a tflite_runtime issue when initializing the model, which should be asked here: https://github.com/tensorflow/tensorflow/issues

**Comment by fransiskusyoga** [comment]
sorry, i did a wrong post
