### ISSUE TITLE
Illegal instruction when trying to use example

### ISSUE THREAD

**Issue by parhedberg** [google-coral/edgetpu#310]
Hi!

Just installed the Coral USB on my system. 

I am trying to use the examples found on [https://coral.ai/docs/accelerator/get-started/#1-install-the-edge-tpu-runtime](https://coral.ai/docs/accelerator/get-started/#1-install-the-edge-tpu-runtime) on my system that is running Debian 10, buster. 

I think i have installed everything, but when i try to run the image classifier i get this:

```
python3 examples/classify_image.py \
--model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels test_data/inat_bird_labels.txt \
--input test_data/parrot.jpg
Illegal instructions
```

... and then nothing more.

I run HomeAssistant  in a docker container at the same host and try to use Frigate for NVR system, but this system cant use the Coral as a detector either. So i am guessing that my host system is the problem?

The system is installed in an old Dell Optiplex 160 computer.

**Comment by Namburger** [comment]
@parhedberg ahh, that sounds like your CPU doesn't support some instructions that is required by the tensorflow package. Unfortunately, the only way to get it working on your HW is to build your own tflite package, you can follow this thread for more info: https://github.com/google-coral/edgetpu/issues/229

**Comment by hjonnala** [comment]
Feel free to reopen if issue still exists.
