### ISSUE TITLE
Compiler for ARM

### ISSUE THREAD

**Issue by CarMiranda** [google-coral/edgetpu#311]
Hi everyone,

I just wanted to have some clarity as to why the EdgeTPU compiler is no longer available for Arm architectures?
There are more and more capable, powerful devices powered by Arm (e.g. NVidia Jetson Xavier for embedded, Apple M1 SoC for desktop/laptop) so I don't get why:

![image](https://user-images.githubusercontent.com/24211207/107213877-5ea42e00-6a09-11eb-8a78-380d6f89ec5e.png)

Is it something permanent? Is it something the EdgeTPU modules require? Is it something that could be reintroduced in a near future?

**Comment by Namburger** [comment]
@CarMiranda hello, I believe we made the decision due to some limited capabilities of ARM chip back then. However I do understand your point, it seems ARM is the future :)
Let me bring it up to our team today to see what will we decide for the future. For now you can use an older version: https://github.com/google-coral/edgetpu/tree/657d2b654101540164af240eacb31440ff6f535d/compiler/aarch64

**Comment by CarMiranda** [comment]
Nice, thank you for the prompt and clear answer @Namburger !

Please do keep us posted when you have more info on the matter :)

**Comment by Namburger** [comment]
@CarMiranda Will bring it up with the team today, but also, FYI you can use colab to compile your model anywhere:
https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb

**Comment by Namburger** [comment]
@CarMiranda apologies, but unfortunately for now we decided t push back this feature until there is a well defined target machine thatwe can set  and test. The issue with the M.1 chip is that it's with MacOS, which we never had a compiler build fr in the first place :/

**Comment by schneider-mathias** [comment]
Is this feature considered to be reactivated in the near future? 

With the introduction of the Coral Dev Micro, a co-platform for re-training and flashing the system (e.g. NVIDIA Jetson Xavier/Orin) is an interesting option for complete decentralized updates of the Coral Micro application. However, without an updated edgetpu-compiler the model must be compiled on some central x86_64 platform to benefit from the latest compiler improvements  .

**Comment by hjonnala** [comment]
> Is this feature considered to be reactivated in the near future?

Unforutantley, No. The compiler is for x86_64 only.
