### ISSUE TITLE
Your terminal lacks the ability to clear the screen or position the cursor.

### ISSUE THREAD

**Issue by kalron90** [google-coral/edgetpu#312]
how to connect wifi on connected USB

OS : Windows 10 

1. not connect Lan

    mdt devices -> OK
    mdt shell -> OK 

    but, nmtui command is "Your terminal lacks the ability to clear the screen or position the cursor."
      - > WSL, Windows bash, cmd (same problem)
 
2. connected Lan 
  
    mdt devices -> not
    mdt shell -> not

    Also, USB connection is not possible when wired LAN is connected to the coral board.
      - > WSL, Windows bash, cmd (same problem)

**Comment by Namburger** [comment]
Humn, I haven't seen this one before. 
Would this happens over putty or ssh in WSL also?

**Comment by harrison0451** [comment]
Hi, 

I met similar problem while I use nmtui command to set up wifi. see picture:

![image](https://user-images.githubusercontent.com/81446036/112702497-e971a880-8e50-11eb-8fde-ea2ff5478d76.png)

It shows "Your terminal lacks the ability to clear the screen or position the cursor."

**Comment by manoj7410** [comment]
@harrison0451 Did you try to connect the board with any other host machine as well ?

**Comment by hjonnala** [comment]
@harrison0451  try this coomand: nmcli dev wifi connect <NETWORK_NAME> password <PASSWORD> ifname wlan0
and then check: nmcli connection show

@kalron90 please try to connect using serial console https://coral.ai/docs/dev-board/serial-console/

**Comment by zhanghp0451** [comment]
@manoj7410 using SSH WSL will solve this problem.

**Comment by manoj7410** [comment]
Feel free to reopen this issue if it still persists.
