### ISSUE TITLE
 Invalid model, Model not quantized (After post-training full int8 quantization)

### ISSUE THREAD

**Issue by lupitia1** [google-coral/edgetpu#313]
Tensorflow version: 2.4.1
Edge TPU Compiler version: 15.0.340273435

**Issue description:**
I'm Fine-tuning MobilenetV2 in _Google Colab_ and I'm able to convert to normal and quantized TFLite.

But when I try to execute:

`! edgetpu_compiler mobilenet_v2_1.0_224_quant.tflite`

I got the following error:
> Edge TPU Compiler version 15.0.340273435
> Invalid model: mobilenet_v2_1.0_224_quant.tflite
> Model not quantized
--------------------------------------------------------------------------------------------------------------

I'm using the following inputs and outputs:

- input: [1,224,224,3] (Images)
- output: [1,56,56,21] (Heatmaps)

--------------------------------------------------------------------------------------------------------------
I have tried converting from keras model and form saved model.

Here is the code I'm using to quantize. This code doesn't retrieve any errors and saves the model:
```

# A generator that provides a representative dataset
def representative_data_gen():
  dataset_list = training_mlab
  for i in range(100):
    image_path = next(iter(dataset_list[0][i][0]))
    path = os.path.join('/content/drive/MyDrive/',image_path)
    image = cv2.imread(path)
    images = tf.expand_dims(tf.cast(image, tf.float32), 0)
    images_resized = tf.compat.v1.image.resize_bilinear(images, [224, 224], align_corners=False)
    yield [images_resized]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# This sets the representative dataset for quantization
converter.representative_dataset = representative_data_gen
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# For full integer quantization, though supported types defaults to int8 only, we explicitly declare it for clarity.
converter.target_spec.supported_types = [tf.int8]
# These set the input and output tensors to uint8 (added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()

with open('mobilenet_v2_1.0_224_quant.tflite', 'wb') as f:
    f.write(tflite_model)

```

--------------------------------------------------------------------------------------------------------------
I'm also attaching
[mobilenet_v2_1.0_224_quant.zip](https://github.com/google-coral/edgetpu/files/5965349/mobilenet_v2_1.0_224_quant.zip)
the model (after full quantization) file in .zip format.
Any help would be greatly appreciated and if I need to post more information please let me know to update.

Thank you!

**Comment by johannes-do** [comment]
Unfortunately, it seems the compiler has two error messages it can output:
"Model not quantized" and "Internal compiler error" ; )

What I usually do if I run into this problem. I write a script that tries different inputs, weights, etc. and just reports which configurations worked and which didn't. So yeah, try and error.

Also sometimes it helps to set: `converter.experimental_new_converter = False`

**Comment by lupitia1** [comment]
> Also sometimes it helps to set: `converter.experimental_new_converter = False`

Thank you so much!! This solved the problem.
