### ISSUE TITLE
Suspend-To-Idle and Suspend-To-RAM for Google Coral Dev Board

### ISSUE THREAD

**Issue by murreletinnovation** [google-coral/edgetpu#314]
Hi there,

I'm interested in putting the Dev Board in the deepest sleep mode possible, to then be woken up by a USB event. Looking through "/sys/power/state" I see that freeze and mem are both available.

I run the following commands to try to enter Suspend-To-RAM:
sudo sh -c “echo enabled > /sys/class/tty/ttymxc0/power/wakeup” (enabling wakeup on UART1)
sudo sh -c “echo deep > /sys/power/mem_sleep" (set to Suspend-to-RAM)
sudo sh -c “echo mem > /sys/power/state” (enter Suspend-To-RAM)
I first noticed that the LEDs on the board are still on. I then attempt to press keys on my keyboard to wake the device from Suspend-To-RAM, but am unable to do so.

I see the same behavior when trying Suspend-to-Idle (freeze). 

Would you be able to help me understand why this is happening? I tried this same procedure to enter "Suspend-To-Idle" on a Jetson Nano and was able to properly enter/exit suspension.

Best,
Aadu

**Comment by Namburger** [comment]
@murreletinnovation 
UART1 may not be a valid wake source, could you take a look at page 2 on this doc and try to wake it with RTC to verify that it works?
https://github.com/mbrooksx/draft-coral-appnotes/blob/main/PowerSavings.pdf

**Comment by murreletinnovation** [comment]
@Namburger RTC wakeup seems to work fine. Wakes up after 20 seconds, but I can't seem to access the Mendel Desktop or CLI. The LED peripherals on the board were also still on. Is this normal?

I'd ideally want to move away from an RTC solution and toward an asynchronous event like USB activity.

**Comment by murreletinnovation** [comment]
@Namburger bumping this discussion.

**Comment by Namburger** [comment]
@mbrooksx could you take a look?

**Comment by mbrooksx** [comment]
This works fine for me. 

(verify deep sleep)
mendel@tuned-rabbit:~$ cat /sys/power/mem_sleep
s2idle [deep]

(verify mxc0 is a wake source)
mendel@tuned-rabbit:~$ sudo cat /sys/kernel/debug/wakeup_sources | grep -i tty
ttymxc0         0               0               0               0               0               0               0               236520          0

echo mem | sudo tee /sys/power/state
I then press a key on my serial console, on the console I see:

> [  904.274547] PM: suspend entry (deep)
> [  904.278200] PM: Syncing filesystems ... done.
> [  904.294641] Freezing user space processes ... (elapsed 0.002 seconds) done.
> [  904.304538] OOM killer disabled.
> [  904.307910] Freezing remaining freezable tasks ... (elapsed 0.014 seconds) done.
> [  904.329986] Suspending console(s) (use no_console_suspend to debug)
> [  904.423048] PM: suspend devices took 0.084 seconds
> [  904.429850] Disabling non-boot CPUs ...
> [  904.445847] CPU1: shutdown
> [  904.445851] psci: CPU1 killed.
> [  904.470110] IRQ 6: no longer affine to CPU2
> [  904.477836] CPU2: shutdown
> [  904.477839] psci: CPU2 killed.
> [  904.506466] CPU3: shutdown
> [  904.506469] psci: CPU3 killed.
> [  904.507107] Enabling non-boot CPUs ...
> [  904.507716] Detected VIPT I-cache on CPU1
> [  904.507735] GICv3: CPU1: found redistributor 1 region 0:0x00000000388a0000
> [  904.507764] CPU1: Booted secondary processor [410fd034]
> [  904.508314]  cache: parent cpu1 should not be sleeping
> [  904.508520] CPU1 is up
> [  904.509050] Detected VIPT I-cache on CPU2
> [  904.509061] GICv3: CPU2: found redistributor 2 region 0:0x00000000388c0000
> [  904.509076] CPU2: Booted secondary processor [410fd034]
> [  904.509441]  cache: parent cpu2 should not be sleeping
> [  904.509619] CPU2 is up
> [  904.510149] Detected VIPT I-cache on CPU3
> [  904.510161] GICv3: CPU3: found redistributor 3 region 0:0x00000000388e0000
> [  904.510176] CPU3: Booted secondary processor [410fd034]
> [  904.510592]  cache: parent cpu3 should not be sleeping
> [  904.510784] CPU3 is up
> [  904.515485] imx6q-pcie 33800000.pcie: pcie phy pll is locked.
> [  904.570145] imx6q-pcie 33c00000.pcie: pcie phy pll is locked.
> [  904.659484] PM: resume devices took 0.032 seconds
> [  904.781756] OOM killer enabled.
> [  904.784909] Restarting tasks ... done.
> [  904.790132] PM: suspend exit

MDT returns shortly after (two or three seconds).

**Comment by murreletinnovation** [comment]
@mbrooksx I just tried replicating the issue (verifying both deep sleep and mxc0 as a wake source) and did not see any activity on my console. 

In the Application Notes on Power Savings, it outlines a method for waking up via RTC. 
`echo +20 | sudo tee /sys/class/rtc/rtc0/wakealarm && echo mem | sudo tee /sys/power/state`

I went ahead and retried that and was able to enter suspend but not properly exit. The output is similar to yours but differs in the last line

> [229.709620] Restarting tasks ... done.
> [229.715264] galcore 38000000 .gpu: Hot alarm is canceled. GPU3D clock will return to 64/64

I don't see the "suspend exit"

**Comment by murreletinnovation** [comment]
Hi @mbrooksx I'm sorry to keep bugging, but I'm not able to replicate your output. Both from setting MXC0 as a wakesource or the RTC. See my above post for the behaviors

**Comment by mbrooksx** [comment]
Your wake source is working from your logs but you're hanging in the resume path somewhere. You'll need to see what you have attached to the board, likely one of them is preventing resume. Also note that the board in this case was overheating (hence the GPU warning) - perhaps that is causing an issue as well. I ran with a Dev Board running Mendel Eagle with nothing attached but the USB-micro serial port.

**Comment by murreletinnovation** [comment]
Thanks Michael, I'll try to replicate your setup exactly and see if the issue persists.

**Comment by murreletinnovation** [comment]
@mbrooksx Michael, I was able to wakeup from suspend through the serial console. Thanks for outlining your setup. I'm not sure what the issue was but I ended up re-flashing Mendel Eagle and things worked fine.

I'm wondering if you can educate me on how to replicate this process with a generic USB device? The eventual setup I want will require a wakeup from suspend on a USB event. For the moment, I'd like to replicate that behavior on a keyboard.

**Comment by mbrooksx** [comment]
It would depend on what USB event you want to wake (such as a plug event or a USB HID event like a USB keyboard press) but overall it should be possible. I'd recommend looking at the NXP forum discussions (keep in mind this is all just an iMX8M). These ones look relevant:

https://community.nxp.com/t5/i-MX-Processors/i-MX8-MCIMX8M-EVK-Wakeup-from-sleep-USB-Device-Mode/m-p/846124
https://community.nxp.com/t5/i-MX-Processors/How-to-configure-iMX6-Solo-to-power-resume-via-USB-HID-Touch/m-p/786937

You likely need to ensure that the device, its upstream hub, and the PHY all are configured for wakeup.

**Comment by murreletinnovation** [comment]
@mbrooksx Hoping you can help me out with some followups.

I received 2 patches from NXP to allow for a USB wakeup. I am trying to patch the kernel and ATF with the patches they gave and then build the source tree (instructions found here: https://coral.googlesource.com/docs/+/refs/heads/master/GettingStarted.md)

The build hangs at the step `"Building database of manual pages ... "`

After using CTRL+C, I see the following:

```
make: *** Deleting file '/rootdir/out/target/product/imx8m/phanbell/obj/ROOTFS/rootfs_arm64.raw.img'
make: *** Deleting file '/rootdir/cache/arm64-base.tgz'
dpkg: error processing package man-db (--configure):
 installed man-db package post-installation script subprocess was interrupted
```
The build continues for a bit and then shows

```
Errors were encountered while processing:
 man-db
 openssh-server
make: *** [/rootdir/build/rootfs.mk:94 /rootdir/out/target/product/imx8m_phanbell/obj/ROOTFS/rootfs_arm64.raw.img] Error 1
```

Any chance you can help me debug this?

**Comment by murreletinnovation** [comment]
Followup: I hit the same bottleneck when I do NOT apply the patches and follow the instructions here: https://coral.googlesource.com/docs/+/refs/heads/master/GettingStarted.md

**Comment by manoj7410** [comment]
@murreletinnovation which host OS version are you currently working with ?

**Comment by murreletinnovation** [comment]
Hi @manoj7410 I am using Ubuntu 16.04.1.

**Comment by manoj7410** [comment]
@murreletinnovation I recommend you to work with Ubuntu 20.04. 16.04 is bit older and many of the packages will fail to build on it.

**Comment by murreletinnovation** [comment]
@manoj7410 Thank you, this was the issue. @mbrooksx, NXP gave me patches to apply to the kernel source tree. I attempted to patch 3 files and found that they were already applied (roughly 1 year ago in both the ATF and Kernel).

**Comment by murreletinnovation** [comment]
@mbrooksx @Namburger @manoj7410 

NXP pointed me to the following solution which works on the Google Coral Dev Board.

echo enabled > /sys/devices/platform/usb@38200000/38200000.dwc3/xhci-hcd.0.auto/power/wakeup

Thanks for all your help!
