### ISSUE TITLE
How to overcome  `More than one subgraph is not supported`

### ISSUE THREAD

**Issue by e2r-htz** [google-coral/edgetpu#317]
Inference on Edge TPU is very slow if the operations are not mapped to TPU. One of the main reasons for not mapping on TPU is given to be `More than one subgraph is not supported`. For example, I am trying to convert a U-Net type architecture to TFLite. I noticed that the operations on the encoder are mapped on TPU but the ones on decoder are not.

```python
converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file("model.h5")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.int8
converter.inference_output_type = tf.int8  # or tf.int8
converter.quantized_input_stats = {'serving_default_input' : (0., 1.),
                                  'input' : (0., 1.),
                                  'input_0' : (0., 1.)}
# converter.allow_custom_ops = True
converter.experimental_new_converter = False
tflite_model = converter.convert()

with tf.io.gfile.GFile('resnet18.tflite', 'wb') as f:
    f.write(tflite_model)
```

compiling the above converted model gives 

```
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 2160 ms.

Input model: resnet18.tflite
Input size: 23.66MiB
Output model: resnet18_edgetpu.tflite
Output size: 23.57MiB
On-chip memory used for caching model parameters: 6.92MiB
On-chip memory remaining for caching model parameters: 3.50KiB
Off-chip memory used for streaming uncached model parameters: 13.46MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 126
Operation log: resnet18_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 90
Number of operations that will run on CPU: 36

Operator                       Count      Status

RESIZE_BILINEAR                5          Operation version not supported
ADD                            16         Mapped to Edge TPU
MAX_POOL_2D                    1          Mapped to Edge TPU
CONCATENATION                  4          More than one subgraph is not supported
PAD                            11         More than one subgraph is not supported
PAD                            34         Mapped to Edge TPU
LOGISTIC                       1          More than one subgraph is not supported
QUANTIZE                       4          More than one subgraph is not supported
QUANTIZE                       3          Mapped to Edge TPU
CONV_2D                        11         More than one subgraph is not supported
CONV_2D                        36         Mapped to Edge TPU
```

Why are some Conv2D mapped on TPU while others are not? What does `More than one subgraph is not supported` mean? How to avoid this to make most of the ops map on TPU?

**Comment by Namburger** [comment]
@e2r-htz There is an experimental feature with our compiler that you can try. Basically add a `-a` to your compiling command:
```
edgetpu_compiler -sa model.tflite
```

Although please keep in mind that this is still in the experimentation stage

**Comment by e2r-htz** [comment]
Damn! That worked! What does `-a` do?

```
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 1727 ms.

Input model: resnet18.tflite
Input size: 13.35MiB
Output model: resnet18_edgetpu.tflite
Output size: 13.54MiB
On-chip memory used for caching model parameters: 4.93MiB
On-chip memory remaining for caching model parameters: 256.00B
Off-chip memory used for streaming uncached model parameters: 8.26MiB
Number of Edge TPU subgraphs: 6
Total number of operations: 85
Operation log: resnet18_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 80
Number of operations that will run on CPU: 5

Operator                       Count      Status

MAX_POOL_2D                    1          Mapped to Edge TPU
MUL                            1          Mapped to Edge TPU
CONV_2D                        33         Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        5          Operation version not supported
PAD                            27         Mapped to Edge TPU
LOGISTIC                       1          Mapped to Edge TPU
ADD                            17         Mapped to Edge TPU
```

**Comment by e2r-htz** [comment]
The compiled tflite model still runs very slow on the TPU. Maybe it is because of `RESIZE_NEAREST_NEIGHBOR`. I'm now looking at how to map this on TPU. The docs say that it only works with 2D or 3D array. Anybody had any luck with this?

**Comment by shairoz-deci** [comment]
@e2r-htz did you resolve the issue? I've encountered the same problem. Without the -a flag, only two of the the 153 operations are mapped to TPU:

```
TRANSPOSE                      70         Operation not supported
PAD                            17         More than one subgraph is not supported
PAD                            1          Mapped to Edge TPU
FULLY_CONNECTED                1          More than one subgraph is not supported
ADD                            10         More than one subgraph is not supported
MEAN                           2          More than one subgraph is not supported
QUANTIZE                       1          Mapped to Edge TPU
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
DEPTHWISE_CONV_2D              17         More than one subgraph is not supported
CONV_2D                        35         More than one subgraph is not supported
```

With the -a flag, most operations are mapped to TPU but the model is much slower when running on TPU
```
`Number of operations that will run on Edge TPU: 85
Number of operations that will run on CPU: 70

Operator                       Count      Status

MEAN                           2          Mapped to Edge TPU
PAD                            18         Mapped to Edge TPU
TRANSPOSE                      70         Operation not supported
ADD                            10         Mapped to Edge TPU
FULLY_CONNECTED                1          Mapped to Edge TPU
QUANTIZE                       2          Mapped to Edge TPU
CONV_2D                        35         Mapped to Edge TPU
DEPTHWISE_CONV_2D              17         Mapped to Edge TPU`
```

**Comment by aviraljain99** [comment]
> @e2r-htz There is an experimental feature with our compiler that you can try. Basically add a -a to your compiling command:
> edgetpu_compiler -sa model.tflite
> Although please keep in mind that this is still in the experimentation stage

@Namburger I tried using the -a flag however I get an error saying:

`Internal compiler error. Aborting! `

I am trying to compile the ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8 from the [tensorflow object detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). I have trained this model on my own custom dataset and I have used the [export_tflite_graph_tf2.py](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_tf2.py) script to export my model. Without the -a flag, this is the compiler output that I get:

```
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 2045 ms.

Input model: ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8_full_integer.tflite
Input size: 4.17MiB
Output model: ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8_full_integer_edgetpu.tflite
Output size: 4.76MiB
On-chip memory used for caching model parameters: 3.21MiB
On-chip memory remaining for caching model parameters: 3.78MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 158
Operation log: ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8_full_integer_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 112
Number of operations that will run on CPU: 46

Operator                       Count      Status

PACK                           4          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
CONCATENATION                  2          More than one subgraph is not supported
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        3          More than one subgraph is not supported
RESHAPE                        6          Mapped to Edge TPU
LOGISTIC                       1          More than one subgraph is not supported
DEPTHWISE_CONV_2D              14         More than one subgraph is not supported
DEPTHWISE_CONV_2D              37         Mapped to Edge TPU
CONV_2D                        58         Mapped to Edge TPU
CONV_2D                        14         More than one subgraph is not supported
QUANTIZE                       1          Mapped to Edge TPU
DEQUANTIZE                     2          Operation is working on an unsupported data type
ADD                            10         Mapped to Edge TPU
ADD                            2          More than one subgraph is not supported
CUSTOM                         1          Operation is working on an unsupported data type
```

**Comment by manoj7410** [comment]
@aviraljain99 Can you share your CPU .tflite model ?

**Comment by aviraljain99** [comment]
Hi @manoj7410, this is the [.tflite file](https://drive.google.com/file/d/1tLqu_LJBPKSt97VZQf-RgYLhJUZD4Axn/view?usp=sharing) that I am passing to the edgetpu compiler. 

This was created using the following Python script:
<details>

<summary>Python Code to perform full-integer post-training quantization</summary>

```python
# For performing full or half way integer quantization
def representative_data_gen():
    dataset_list = tf.data.Dataset.list_files(train_img_dir + '/*')
    for i in range(1000):
        if (i % 100 == 0):
            print(i)
        image = next(iter(dataset_list))
        image = tf.io.read_file(image)
        image = tf.io.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [IMAGE_SIZE, IMAGE_SIZE])
        # Do the images need to be normalized?
        # image = tf.cast(image / 255., tf.float32)
        image = tf.expand_dims(image, 0)
        yield [image]

converter = tf.lite.TFLiteConverter.from_saved_model(os.path.join(args.model_dir, 'exported', 'saved_model'))

# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# This sets the representative dataset for quantization
converter.representative_dataset = representative_data_gen
converter.experimental_new_converter = True

print("Performing full quantization")
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

# For full integer quantization, though supported types defaults to int8 only, we explicitly declare it for clarity.
converter.target_spec.supported_types = [tf.int8]

# These set the input and output tensors to uint8 (added in r2.3)
converter.inference_input_type = tf.uint8
# converter.inference_output_type = tf.uint8

converter.allow_custom_ops = True

tflite_model = converter.convert()

with open(os.path.join(args.model_dir, args.quant_type, args.model_dir + "_"+ args.quant_type + ".tflite"), 'wb') as f:
    f.write(tflite_model)
```

</details>

Running the edgetpu model on the EdgeTPU is also performing inference very slowly. I am getting inference time of ~400ms with the model compiled using the EdgeTPU compiler.

This is the [.tflite model](https://drive.google.com/file/d/1z5R812u-LCa9ID658UIkQTQnYTkLOvJ7/view?usp=sharing) created **without** using any post-training quantization (using the code shown below):

<details>

<summary> TFLite Conversion without Post-training Quantization </summary>

```python
converter = tf.lite.TFLiteConverter.from_saved_model(os.path.join(args.model_dir, 'exported', 'saved_model'))
tflite_model = converter.convert()

with open(os.path.join(args.model_dir, args.quant_type, args.model_dir + "_"+ args.quant_type + ".tflite"), 'wb') as f:
    f.write(tflite_model)
```

</details>

Thanks a lot for your help!

**Comment by manoj7410** [comment]
@aviraljain99 I see that you have trained your model with size 640x640. 
Can you try with 320x320 and see if there is any improvement in the inference?

**Comment by aviraljain99** [comment]
@manoj7410 I have also tried the 320x320 model and that model gets compiled by the edgetpu. I am even getting fast inference with the 320x320 model. But I am trying to compare performance across different models and so I was hoping I could also compile the 640x640 model using the edgetpu compiler.

Do you know why the 640x640 model is not getting compiled by using the -a flag on the edgetpu compiler? Or any suggestions on how I can debug it? I can compile the 640x640 model using the edgetpu without the -a flag however the inference is very slow.

**Comment by mezdahun** [comment]
+1 as for the official [SSD MobileNet V2 FPNLite 640x640 ](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)does not compile with `-a` flag after fine tuning, exporting to tflite and post-training full-integer quantizing it all followed by the official guides.  (using tf 2.5.0 and edgetpu-compiler 1.5). Seemingly experiencing the same as @aviraljain99 

Doing the same with the 320x320 version yields good results after using the `-a` flag. Without this the compiler maps only partially to the TPU that leads to "slow" inference (the same as compiling the 640 version without this flag).

I know it is currently not in the [supported models](https://coral.ai/models/object-detection/) of Coral but any news on making the 640x640 version fully compiled?

**Comment by taloot** [comment]
> @manoj7410 I have also tried the 320x320 model and that model gets compiled by the edgetpu. I am even getting fast inference with the 320x320 model. But I am trying to compare performance across different models and so I was hoping I could also compile the 640x640 model using the edgetpu compiler.
> 
> Do you know why the 640x640 model is not getting compiled by using the -a flag on the edgetpu compiler? Or any suggestions on how I can debug it? I can compile the 640x640 model using the edgetpu without the -a flag however the inference is very slow.

i found solution for this,  its related to class number i manage to run yolov5s on 512x512
https://www.youtube.com/watch?v=D9IExho8pwo
keep the classes less than 7 and it works i been debugging this for a month till i found it

**Comment by mezdahun** [comment]
@taloot I don't know about @aviraljain99  but I have a single detection class and yet it is not getting compiled with the '-a' flag and therefore the inference is pretty slow. Have you tried compiling the 640x640 SSD Mobilenet v2 FPNLite instead of 512x512 Yolov5? It is good to know that Yolov5 is a possible option though. Is there any update on this @manoj7410 to know if it was possible at all?

**Comment by glenn-jocher** [comment]
@Namburger we've gotten a request to default YOLOv8 Edge TPU exports to use the -a flag. I don't this flag in the docs. Is this recommended by the Edge TPU team at this time?

See https://github.com/ultralytics/ultralytics/pull/1351

**Comment by hjonnala** [comment]
> @Namburger we've gotten a request to default YOLOv8 Edge TPU exports to use the -a flag. I don't this flag in the docs. Is this recommended by the Edge TPU team at this time?
> 
> See [ultralytics/ultralytics#1351](https://github.com/ultralytics/ultralytics/pull/1351)

Please evaluate the [inference time](https://github.com/hjonnala/snippets/blob/main/coral_inference.py) for the model with and without -a flag to determine whether to use it or not.. Thanks!!

**Comment by hamedgorji** [comment]
> > @Namburger we've gotten a request to default YOLOv8 Edge TPU exports to use the -a flag. I don't this flag in the docs. Is this recommended by the Edge TPU team at this time?
> > See [ultralytics/ultralytics#1351](https://github.com/ultralytics/ultralytics/pull/1351)
> 
> Please evaluate the inference time for the model with and without -a flag to determine whether to use it or not.. Thanks!!

Do you think this can solve the issue? Or do you have any other suggestions to solve the issue?

```
Input model: /content/drive/MyDrive/Yolo/best_saved_model/best_full_integer_quant.tflite
Input size: 2.98MiB
Output model: /content/drive/MyDrive/Yolo/best_saved_model/best_full_integer_quant_edgetpu.tflite
Output size: 3.34MiB
On-chip memory used for caching model parameters: 3.00MiB
On-chip memory remaining for caching model parameters: 3.87MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 256
Operation log: /content/drive/MyDrive/Yolo/best_saved_model/best_full_integer_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 231
Number of operations that will run on CPU: 25

Operator                       Count      Status

SOFTMAX                        1          More than one subgraph is not supported
MUL                            57         Mapped to Edge TPU
MUL                            2          More than one subgraph is not supported
SUB                            2          More than one subgraph is not supported
ADD                            6          Mapped to Edge TPU
ADD                            2          More than one subgraph is not supported
RESHAPE                        2          More than one subgraph is not supported
RESHAPE                        2          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        1          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
TRANSPOSE                      4          Operation is otherwise supported, but not mapped due to some unspecified limitation
TRANSPOSE                      1          Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
STRIDED_SLICE                  16         Mapped to Edge TPU
STRIDED_SLICE                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
STRIDED_SLICE                  2          More than one subgraph is not supported
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
QUANTIZE                       2          Mapped to Edge TPU
QUANTIZE                       1          More than one subgraph is not supported
CONV_2D                        63         Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
LOGISTIC                       57         Mapped to Edge TPU
LOGISTIC                       1          More than one subgraph is not supported
CONCATENATION                  16         Mapped to Edge TPU
CONCATENATION                  2          More than one subgraph is not supported
CONCATENATION                  1          Operation is otherwise supported, but not mapped due to some unspecified limitation
Compilation child process completed within timeout period.
Compilation succeeded! 
```

**Comment by glenn-jocher** [comment]
@hjonnala @hamedgorji in my tests in Google Colab adding the `-a` flag resulted in the failure of (an otherwise correctly compiling) YOLOv8n-seg model. 

Furthermore our existing benchmarks that run every 24 hours on all export formats show 100% Edge TPU mapping with the default export command `yolo export format=edgetpu`, so I see no reason to change our export code by adding the `-a` argument.

EDIT: Note this export is at `--imgsz 160`, larger image sizes may result in worse Edge TPU mapping.

https://github.com/ultralytics/ultralytics/actions/runs/4380005063
<img width="1677" alt="Screenshot 2023-03-10 at 04 03 50" src="https://user-images.githubusercontent.com/26833433/224212809-c8e9e1e5-46e7-43ae-b30d-b55349ae36aa.png">

**Comment by hamedgorji** [comment]
> @hjonnala @hamedgorji in my tests in Google Colab adding the `-a` flag resulted in the failure of (an otherwise correctly compiling) YOLOv8n-seg model.
> 
> Furthermore our existing benchmarks that run every 24 hours on all export formats show 100% Edge TPU mapping with the default export command `yolo export format=edgetpu`, so I see no reason to change our export code by adding the `-a` argument.
> 
> EDIT: Note this export is at `--imgsz 160`, larger image sizes may result in worse Edge TPU mapping.
> 
> https://github.com/ultralytics/ultralytics/actions/runs/4380005063 <img alt="Screenshot 2023-03-10 at 04 03 50" width="1677" src="https://user-images.githubusercontent.com/26833433/224212809-c8e9e1e5-46e7-43ae-b30d-b55349ae36aa.png">
Could you test it on detection mode too?

**Comment by taloot** [comment]
to tell you the truth i dropped TPU support and i relay on  openvino, as
accelerator,

**Comment by glenn-jocher** [comment]
> > @hjonnala @hamedgorji in my tests in Google Colab adding the `-a` flag resulted in the failure of (an otherwise correctly compiling) YOLOv8n-seg model.
> 
> > 
> 
> > Furthermore our existing benchmarks that run every 24 hours on all export formats show 100% Edge TPU mapping with the default export command `yolo export format=edgetpu`, so I see no reason to change our export code by adding the `-a` argument.
> 
> > 
> 
> > EDIT: Note this export is at `--imgsz 160`, larger image sizes may result in worse Edge TPU mapping.
> 
> > 
> 
> > https://github.com/ultralytics/ultralytics/actions/runs/4380005063 <img alt="Screenshot 2023-03-10 at 04 03 50" width="1677" src="https://user-images.githubusercontent.com/26833433/224212809-c8e9e1e5-46e7-43ae-b30d-b55349ae36aa.png">
> 
> Could you test it on detection mode too?

Detection and classification are part of Ultralytics benchmarks CI, click the link above to review.

**Comment by hamedgorji** [comment]
@hjonnala Update: 
Hi Glenn,
I retrained my model, and I changed the `imgsz `from 640 to 160. With an image size of 160, it seems everything is ok; I got the result same as you. Do you have any idea why with the image size of 640, I couldn't get that? 
```
Model compiled successfully in 2181 ms.

Input model: /content/drive/MyDrive/Yolo/best160_saved_model/best160_full_integer_quant.tflite
Input size: 2.96MiB
Output model: /content/drive/MyDrive/Yolo/best160_saved_model/best160_full_integer_quant_edgetpu.tflite
Output size: 4.92MiB
On-chip memory used for caching model parameters: 4.50MiB
On-chip memory remaining for caching model parameters: 3.08MiB
Off-chip memory used for streaming uncached model parameters: 9.31KiB
Number of Edge TPU subgraphs: 1
Total number of operations: 256
Operation log: /content/drive/MyDrive/Yolo/best160_saved_model/best160_full_integer_quant_edgetpu.log

Operator                       Count      Status

CONV_2D                        64         Mapped to Edge TPU
CONCATENATION                  19         Mapped to Edge TPU
SOFTMAX                        1          Mapped to Edge TPU
RESHAPE                        5          Mapped to Edge TPU
TRANSPOSE                      5          Mapped to Edge TPU
STRIDED_SLICE                  20         Mapped to Edge TPU
MUL                            59         Mapped to Edge TPU
SUB                            2          Mapped to Edge TPU
ADD                            8          Mapped to Edge TPU
LOGISTIC                       58         Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
QUANTIZE                       3          Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 
Edge TPU: export success ✅ 14.6s, saved as /content/drive/MyDrive/Yolo/best160_saved_model/best160_full_integer_quant_edgetpu.tflite (4.9 MB)

Export complete (73.2s)
Results saved to /content/drive/MyDrive/Yolo
Predict:         yolo predict task=detect model=/content/drive/MyDrive/Yolo/best160_saved_model/best160_full_integer_quant_edgetpu.tflite imgsz=160 
Validate:        yolo val task=detect model=/content/drive/MyDrive/Yolo/best160_saved_model/best160_full_integer_quant_edgetpu.tflite imgsz=160 data=Data/data.yaml 
Visualize:       https://netron.app/
```

**Comment by iaverypadberg** [comment]
I was struggling to get a 320x320 Yolov8n model fully compatible with the edgetpu and switched my input image size to 256x256. Fixed all of the edgetpu erros and inference time went from 29ms/image to 12ms/image. I'm thinking that this is due to a concat operation towards the end of the model being too large when the image size is > 256. 
![Screenshot from 2023-07-31 13-47-31](https://github.com/google-coral/edgetpu/assets/55753588/bc8b5200-df63-4515-8c84-b79070336cd1)
