### ISSUE TITLE
Noticing particular error in Raspberry pi 4 using coral usb accelerator

### ISSUE THREAD

**Issue by BalajiElumalai27** [google-coral/edgetpu#318]
Memory  :  16gb sd card
Edge Tpu compiler version:  14
Library : pre-build library in this git (arm 7a)
Tensorflow version:  1.15.2

        During inference the following is noticed in raspberry pi(Nuke OS). Following error

 **ERROR: Failed to execute request. Unable to find input for layer norm_lized_input_image_tensor.
ERROR: Node number 0 (edgetpu-custom-op) failed to invoke**

Appreciate if anyone could solve this issue .

**Comment by Namburger** [comment]
@BalajiElumalai27 I havent seen this before, which pi version and OS are you using?

**Comment by BalajiElumalai27** [comment]
**
Raspberry model =  Pi4
Ram = 8gb ram
OS = noobs

using command **cat /etc/os-release** it shows
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/&quot;
SUPPORT_URL="http://www.raspbian.org/RaspbianForums&quot;
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs&quot;**

     I have used for 6 months but currently this issue occurs in rasphberry but same code runs in desktop (x86) working fine. I glad you replied, please let me know how to solve. I debug line by line its show in  **tflite_wrapper.cc** file -> funtion(**TfLiteWrapper::RunInference**)->Line( **m_interpreter->Invoke()**)

**Comment by Namburger** [comment]
@BalajiElumalai27 What happen if you use the CPU model instead of the edgetpu, issue still occurs?

**Comment by BalajiElumalai27** [comment]
If i use cpu model it works fine. I worried because of that this issue occurs only when i using tpu model. I refer this link as source code  https://github.com/Namburger/edgetpu-detection-camera

**Comment by BalajiElumalai27** [comment]
Occasionally noticed this issue also  **malloc(): unsorted double linked list corrupted
Aborted**

**Comment by Namburger** [comment]
just to clarify, this is happening with the CPU model?

> Occasionally noticed this issue also malloc(): unsorted double linked list corrupted
Aborted

**Comment by BalajiElumalai27** [comment]
> 
> 
> just to clarify, this is happening with the CPU model?
> 
> > Occasionally noticed this issue also malloc(): unsorted double linked list corrupted
> > Aborted

Yes this happening with CPU model also.

**Comment by BalajiElumalai27** [comment]
> 
> 
> Memory : 16gb sd card
> Edge Tpu compiler version: 14
> Library : pre-build library in this git (arm 7a)
> Tensorflow version: 1.15.2
> 
> ```
>     During inference the following is noticed in raspberry pi(Nuke OS). Following error
> ```
> 
> **ERROR: Failed to execute request. Unable to find input for layer norm_lized_input_image_tensor. ERROR: Node number 0 (edgetpu-custom-op) failed to invoke**
> 
> Appreciate if anyone could solve this issue .

Is there any solution for this issue? Please let me know.

**Comment by Namburger** [comment]
@BalajiElumalai27 could you send a stack trace? just want to know the exact point where this error is happening. 
Jut run it in gdb until it fails:
```
$ gdb ./process_name
$ r
# FAILED
$ bt
```
Then post the outputs here. Thanks

**Comment by BalajiElumalai27** [comment]
I found the error came, it occurs when edgetpu library installed in system path and i referred in Libpath were different version.
When i remove edgetpu library in system path for  application works fine without this issue **malloc(): unsorted double linked list corrupted**

 And when i remove uuid preinstalled in system lib folder application works fine without this issue **ERROR: Failed to execute request. Unable to find input for layer norm_lized_input_image_tensor.
ERROR: Node number 0 (edgetpu-custom-op) failed to invoke**

Thanks for reply @Namburger

**Comment by manoj7410** [comment]
Looks like the issue has been fixed. Marking it closed. Feel free to reopen if the issue still persists.
