### ISSUE TITLE
USB cameras on dev board mini

### ISSUE THREAD

**Issue by kueblert** [google-coral/edgetpu#319]
Hi,
are there any plans to support USB cameras on the dev board mini? I noticed the getting started guide said people are working on it. It there a roadmap or sth.?

I am trying to connect three cameras on a USB 2.0 hub (bandwidth-wise this works fine on other platforms). But when I try it on the dev board mini, only one camera comes up at a time. Is there a known (hardware/driver) limitation to the USB port that prevents this?

Best,
Thomas

**Comment by Namburger** [comment]
@kueblert 
I believe the 3 cameras may just be under powered. I'll check with my team to see progresses on this, but do you see anything interesting in dmesg? 
Also, what usb cameras are you using?

[update] We haven't made much changes since MP, the mini board can only support the USB camera with VGA resolution and MJPEG format currently.

**Comment by kueblert** [comment]
Thank you for checking, @Namburger .
I tried connecting the cameras via a powered USB hub, but with the same effect.
The cameras are custom uvc cameras connected via a USB 2.0 hub.
They deliver up to 640x480 MJPEG @ 60fps each.

I'll provide a dmesg log later.

**Comment by kueblert** [comment]
Ok, so I am running the following GStreamer pipeline:
`gst-launch-1.0 v4l2src device="/dev/video1" ! image/jpeg, width=640, height=480, framerate=60/1 ! queue ! decodebin ! compositor name=comp ! videoconvert ! fakesink v4l2src device="/dev/video4" ! image/jpeg, width=640, height=480, framerate=60/1 ! queue ! decodebin ! comp.
`
and receive this output:
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Failed to allocate required memory.
Additional debug info:
gstv4l2src.c(660): gst_v4l2src_decide_allocation (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
Buffer pool activation failed
Execution ended after 0:00:00.167497906
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

`dmesg` returns:
[ 3506.160263] uvcvideo: Failed to query (GET_DEF) UVC control 13 on unit 1: -32 (exp. 8). 
[ 3506.182577] uvcvideo: Failed to query (GET_DEF) UVC control 13 on unit 1: -32 (exp. 8).                              
[ 3506.329979] musb-hdrc musb-hdrc.2.auto: iso hwep alloc failed for 3x280                                              
[ 3506.336819] uvcvideo: Failed to submit URB 0 (-28).

**Comment by kueblert** [comment]
[https://e2e.ti.com/support/processors/f/791/t/845765?AM3352-Multiple-USB-cameras](Here) it sounds like musb might be the limiting factor (however, this seems a bit beyond my expertise...). Is it possible to enable that xHCI-thing that those people talk about on Mendel OS and can anyone tell whether it will have the expected outcome?

**Comment by Namburger** [comment]
@kueblert wait, could you run this commands?
```
v4l2-ctl --list-devices
v4l2-ctl --device /dev/video1 --list-formats
```
I may be wrong, but I believe `/dev/video1` is reserved for our camera module

**Comment by kueblert** [comment]
@Namburger should be video0 and video2.
platform:mt8167 (platform:mt8167):                                                                                              
/dev/video0 
                                                                                                                                                                                                                            14001000.rdma (platform:mt8173):                                                                                                
/dev/video2     
                                                                                                                                                                                                                        RYS THREE: RYS THREE (usb-musb-hdrc.2.auto-1.2):                                                                                
/dev/video1                                                                                                            
/dev/video3       
                                                                                                                                                                                                                      RYS ONE: RYS ONE (usb-musb-hdrc.2.auto-1.3):                                                                                    
/dev/video4                                                                                                             
/dev/video5          
                                                                                                                                                                                                                   RYS TWO: RYS TWO (usb-musb-hdrc.2.auto-1.4):                                                                                    
/dev/video6                                                                                                             
/dev/video7                            


video1 formats:
ioctl: VIDIOC_ENUM_FMT                                                                                                          
Type: Video Capture                                                                                                                                                                                                                             [0]: 'MJPG' (Motion-JPEG, compressed)

**Comment by kueblert** [comment]
after enabling tracing on the uvc driver I got the following slightly more detailled log (of which I still cannot make much sense):

[ 33.757774] usb0_vbus_old: disabling
 [ 33.761344] backlight_vbus: disabling
[ 33.765106] ldo_vm25: disabling
 [ 56.782243] uvcvideo: Failed to query (GET_DEF) UVC control 13 on unit 1: -32 (exp. 8).
[ 56.859116] uvcvideo: Failed to query (GET_DEF) UVC control 13 on unit 1: -32 (exp. 8).
[ 57.020651] musb-hdrc musb-hdrc.2.auto: iso hwep alloc failed for 3x280
 [ 57.027350] uvcvideo: Failed to submit URB 0 (-28).
 [211.075916] uvcvideo: uvc_v4l2_open
[211.210291] uvcvideo: Resuming interface 0
[211.210306] uvcvideo: Resuming interface 1
[211.211574] uvcvideo: uvc_v4l2_release
[211.212801] uvcvideo: uvc_v4l2_open
[211.278443] uvcvideo: Resuming interface 0
[211.278458] uvcvideo: Resuming interface 1
[211.279735] uvcvideo: uvc_v4l2_release
[211.280969] uvcvideo: uvc_v4l2_open
[211.346249] uvcvideo: Resuming interface 0
[211.346265] uvcvideo: Resuming interface 1
[211.347535] uvcvideo: uvc_v4l2_release
[211.405118] uvcvideo: uvc_v4l2_open
[211.408522] uvcvideo: Failed to query (GET_DEF) UVC control 13 on unit 1: -32 (exp. 8).
[211.417013] uvcvideo: Control error 6
[211.426834] uvcvideo: uvc_v4l2_open
[211.430017] uvcvideo: Failed to query (GET_DEF) UVC control 13 on unit 1: -32 (exp. 8).
[211.438362] uvcvideo: Control error 6
[211.440717] uvcvideo: Trying format 0x47504a4d (MJPG): 640x480.
[211.440729] uvcvideo: Using default frame interval 16666.6 us (60.0 fps).
[211.441693] uvcvideo: Trying format 0x47504a4d (MJPG): 640x480.
[211.441704] uvcvideo: Using default frame interval 16666.6 us (60.0 fps).
[211.490024] uvcvideo: Setting frame interval to 1/60 (166666).
[211.495532] uvcvideo: Setting frame interval to 1/60 (166666).
[211.544356] uvcvideo: Control 0x00980927 not found.
 [211.550031] uvcvideo: Control 0x00980927 not found.
 [211.560957] uvcvideo: Control 0x00980927 not found.
 [211.560961] uvcvideo: Control 0x00980927 not found.
 [211.568968] uvcvideo: Device requested 320 B/frame bandwidth.
 [211.568980] uvcvideo: Selecting alternate setting 4 (840 B/frame bandwidth).
 [211.574527] uvcvideo: Device requested 320 B/frame bandwidth.
 [211.574543] uvcvideo: Selecting alternate setting 4 (840 B/frame bandwidth).
 [211.577174] uvcvideo: Allocated 5 URB buffers of 32x840 bytes each.
[211.577309] uvcvideo: Allocated 5 URB buffers of 32x840 bytes each.
[211.577339] uvcvideo: uvc_v4l2_poll
[211.577347] musb-hdrc musb-hdrc.2.auto: iso hwep alloc failed for 3x280
 [211.577382] uvcvideo: Failed to submit URB 0 (-28).
 [211.593006] uvcvideo: uvc_v4l2_poll
[211.593223] musb_host_rx 1895: Rx interrupt with no errors or packet!
 [211.603692] uvcvideo: uvc_v4l2_release
[211.604066] uvcvideo: uvc_v4l2_release

**Comment by Namburger** [comment]
Humn, so it looks like your cameras are showing up as 
/dev/video2,4, and 5. Could you run the pipeline over those devices?
```
$ gst-launch-1.0  glvideomixer name=m background=black \
      sink_0::xpos=0 sink_0::ypos=0   sink_0::zorder=1\
      ! glimagesink \
      v4l2src device=/dev/video0 ! video/x-raw,framerate=30/1,width=640,height=480 !  glupload ! glcolorconvert ! m.sink_0 
```

**Comment by kueblert** [comment]
Hi @Namburger , sorry for the delay over the weekend. I am pretty sure I got the camera devices right.
Video 0/2 are the built-in ones. Each of my cameras registers both a raw and a MJPG compressed stream. To be able to transfer all images simultaneously, I need to use the MJPG stream. Otherwise the bandwidth might be problematic.

The pipeline you wrote therefore fails. I modified it as follows, which runs just fine (but extending it to use two cameras results in the same error as before):
`gst-launch-1.0  glvideomixer name=m background=black sink_0::xpos=0 sink_0::ypos=0 sink_0::zorder=1 ! glimagesink v4l2src device=/dev/video6 ! image/jpeg,framerate=60/1,width=640,height=480 ! jpegdec ! glupload ! glcolorconvert ! m.sink_0`

Here is also the output of gst-device-monitor:
`Probing devices...


Device found:

	name  : RYS THREE: RYS THREE
	class : Video/Source
	caps  : image/jpeg, width=(int)640, height=(int)480, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)352, height=(int)288, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)320, height=(int)240, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)176, height=(int)144, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)160, height=(int)120, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	properties:
		udev-probed = true
		device.bus_path = platform-musb-hdrc.2.auto-usb-0:1.2:1.0
		sysfs.path = /sys/devices/platform/soc/11100000.usb/musb-hdrc.2.auto/usb1/1-1/1-1.2/1-1.2:1.0/video4linux/video1
		device.bus = usb
		device.subsystem = video4linux
		device.vendor.id = 1421
		device.vendor.name = "RYS\\x20Corp."
		device.product.id = 0806
		device.product.name = "RYS\ THREE:\ RYS\ THREE"
		device.serial = RYS_Corp._RYS_THREE
		device.capabilities = :capture:
		device.api = v4l2
		device.path = /dev/video1
		v4l2.device.driver = uvcvideo
		v4l2.device.card = "RYS\ THREE:\ RYS\ THREE"
		v4l2.device.bus_info = usb-musb-hdrc.2.auto-1.2
		v4l2.device.version = 267133 (0x0004137d)
		v4l2.device.capabilities = 2225078273 (0x84a00001)
		v4l2.device.device_caps = 69206017 (0x04200001)
	gst-launch-1.0 v4l2src device=/dev/video1 ! ...


Device found:

	name  : RYS ONE: RYS ONE
	class : Video/Source
	caps  : image/jpeg, width=(int)640, height=(int)480, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)352, height=(int)288, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)320, height=(int)240, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)176, height=(int)144, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)160, height=(int)120, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	properties:
		udev-probed = true
		device.bus_path = platform-musb-hdrc.2.auto-usb-0:1.3:1.0
		sysfs.path = /sys/devices/platform/soc/11100000.usb/musb-hdrc.2.auto/usb1/1-1/1-1.3/1-1.3:1.0/video4linux/video4
		device.bus = usb
		device.subsystem = video4linux
		device.vendor.id = 1421
		device.vendor.name = "RYS\\x20Corp."
		device.product.id = 0806
		device.product.name = "RYS\ ONE:\ RYS\ ONE"
		device.serial = RYS_Corp._RYS_ONE
		device.capabilities = :capture:
		device.api = v4l2
		device.path = /dev/video4
		v4l2.device.driver = uvcvideo
		v4l2.device.card = "RYS\ ONE:\ RYS\ ONE"
		v4l2.device.bus_info = usb-musb-hdrc.2.auto-1.3
		v4l2.device.version = 267133 (0x0004137d)
		v4l2.device.capabilities = 2225078273 (0x84a00001)
		v4l2.device.device_caps = 69206017 (0x04200001)
	gst-launch-1.0 v4l2src device=/dev/video4 ! ...


Device found:

	name  : RYS TWO: RYS TWO
	class : Video/Source
	caps  : image/jpeg, width=(int)640, height=(int)480, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)352, height=(int)288, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)320, height=(int)240, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)176, height=(int)144, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	        image/jpeg, width=(int)160, height=(int)120, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)60/1;
	properties:
		udev-probed = true
		device.bus_path = platform-musb-hdrc.2.auto-usb-0:1.4:1.0
		sysfs.path = /sys/devices/platform/soc/11100000.usb/musb-hdrc.2.auto/usb1/1-1/1-1.4/1-1.4:1.0/video4linux/video6
		device.bus = usb
		device.subsystem = video4linux
		device.vendor.id = 1421
		device.vendor.name = "RYS\\x20Corp."
		device.product.id = 0806
		device.product.name = "RYS\ TWO:\ RYS\ TWO"
		device.serial = RYS_Corp._RYS_TWO
		device.capabilities = :capture:
		device.api = v4l2
		device.path = /dev/video6
		v4l2.device.driver = uvcvideo
		v4l2.device.card = "RYS\ TWO:\ RYS\ TWO"
		v4l2.device.bus_info = usb-musb-hdrc.2.auto-1.4
		v4l2.device.version = 267133 (0x0004137d)
		v4l2.device.capabilities = 2225078273 (0x84a00001)
		v4l2.device.device_caps = 69206017 (0x04200001)
	gst-launch-1.0 v4l2src device=/dev/video6 ! ...

`

**Comment by kueblert** [comment]
Did the team provide any hint of why only VGA&MJPG is supported? Is it a hardware limitation of the USB/Soc or a driver thing?

**Comment by kueblert** [comment]
Anyone knows whether USB with the normal, full-scale dev board is any better?

**Comment by Namburger** [comment]
@kueblert allow me to check back with you regarding the dev board mini's usb camera issue, however the original dev board should be able to use the usb camera without issues

**Comment by kueblert** [comment]
@Namburger Your help is much appreciated. I'd be happy to get it working with the mini.

**Comment by mbrooksx** [comment]
Hi @kueblert ,

The limitation is USB. With the USB2.0 connection, we are limited to this input (when coming from USB) - we can't get pixels in and sent to the GPU fast enough. Theoretically a higher-resolution H264 camera could be used, but trying to decode that in streaming mode isn't very reliable on the MTK platform. These restrictions don't exist for MIPI Cameras on the Dev Board Mini or on the full size Dev Board (where the USB port is USB3.0 and it better handles moving USB frames).

**Comment by kueblert** [comment]
Thanks!

**Comment by kueblert** [comment]
For future reference, editing /sys/module/usbcore/parameters/usbfs_memory_mb at least canges the error message.
Still, only one camera at a time is recording. But gstreamer now does run three separate pipelines at the same time now and then.

alloc_contig_range is triggered multiple times with PFNs busy before the failure. Perhaps something related to CMU?


(Further notes to myself)
To show the full trace of uvc driver:
sudo nano /sys/module/uvcvideo/parameters/trace
0xffff

To disable the microphones on the cameras which are on the same usb controller (and might or might not reserve some bandwidth):
sudo nano /etc/udev/rules.d/90-blacklist-webcam-sound-rules.rules
SUBSYSTEM=="usb", DRIVER=="snd-usb-audio", ATTRS{idVendor}=="xxxx", ATTRS{idProduct}=="yyyy", ATTR{authorized}="0"



/etc/modprobe.d/uvcvideo.conf
options uvcvideo nodrop=1
sudo rmmod uvcvideo && sudo modprobe uvcvideo
