### ISSUE TITLE
Creating our own model to do the imprinting weight

### ISSUE THREAD

**Issue by Kao1126** [google-coral/edgetpu#32]
Hello, 
I try to create the model to do the imprinted weight, the model through quantization-aware training and compiler. However, Regardless of using  tf.keras.layers.LayerNormalization、tf.math.l2_normalize、tf.keras.backend.l2_normalize, edge TPU raised the Error: must have L2norm or RuntimeError: The last 5 operators should be L2Norm, Con2d, Mul, Reshape and Softmax when we are using imprinting_learning.py. 
Which function do we have to use is able to lead us to run the imprinting_learning.py successfully?

Thanks

**Comment by Namburger** [comment]
Hi, sorry not sure if I understand the query correctly, did you get a chance to check [here](https://coral.ai/docs/edgetpu/retrain-classification-ondevice/#build-a-different-model-for-imprintingengine)? Creating a model is a little outside of our support scope and it is advised that you checkout this [paper](https://github.com/google-coral/imprinting-training/blob/master/classification/mobilenet_v1_l2norm.py)
