### ISSUE TITLE
Edge tpu PCIe on 32-bit armv7 ?

### ISSUE THREAD

**Issue by TheSven73** [google-coral/edgetpu#320]
We are investigating if it would be possible to use the PCIe version of the Edge TPU on an armv7 system (32-bit arm).

We have already integrated your [out-of-tree gasket driver](https://coral.googlesource.com/linux-imx/+/refs/heads/release-day/drivers/staging/gasket) into our v5.9 mainline Linux kernel. The gasket driver cannot be built, because it depends on ARM64:
```text
 config STAGING_GASKET_FRAMEWORK
        tristate "Gasket framework"
        depends on PCI && (X86_64 || ARM64)
```
After removing the dependency, the driver still does not build, because it's using `readq/writeq`, functions which atomically read/write a quadword (64-bit) on the PCIe bus. These are not supported on 32-bit Linux.

Is there a fundamental reason why 32-bit is not supported? Would it be possible to add support by making modifications to the driver? For example. `readq/writeq` can be replaced by 2x `readl/writel`. Of course the operation is then no longer atomic.

Very grateful for any insights.

**Comment by Namburger** [comment]
@TheSven73 we currently don't plan on supporting 32 OS for the pcie module. Although other have open issues similar to this. You can take a look at this one for more info:
https://github.com/google-coral/edgetpu/issues/280#issuecomment-760907539
