### ISSUE TITLE
Compiler produce large output model

### ISSUE THREAD

**Issue by marcin-kamionowski** [google-coral/edgetpu#321]
Hi!
We have model that cause size problem:

> $ edgetpu_compiler -s -a yolo_no_fake_input.tflite 
> Edge TPU Compiler version 15.0.340273435
> 
> Model compiled successfully in 1487 ms.
> 
> Input model: yolo_no_fake_input.tflite
> Input size: 2.77MiB
> Output model: yolo_no_fake_input_edgetpu.tflite
> Output size: 31.90MiB
> On-chip memory used for caching model parameters: 2.71MiB
> On-chip memory remaining for caching model parameters: 5.02MiB
> Off-chip memory used for streaming uncached model parameters: 29.07MiB
> Number of Edge TPU subgraphs: 1
> Total number of operations: 68
> Operation log: yolo_no_fake_input_edgetpu.log
> 
> Operator                       Count      Status
> 
> DEPTHWISE_CONV_2D              17         Mapped to Edge TPU
> ADD                            10         Mapped to Edge TPU
> RESHAPE                        1          Mapped to Edge TPU
> CONV_2D                        36         Mapped to Edge TPU
> PAD                            4          Mapped to Edge TPU
I see in hex editor that there is lots of zeros.
The problem still occurs even if we split the model to multiple segments:

> $ edgetpu_compiler -s -n 5 yolo_no_fake_input.tflite 
> Edge TPU Compiler version 15.0.340273435
> Warning: For the given model, you're creating more segments than is necessary, which can increase inference latency.We instead recommend num_segments = 1
> 
> Model compiled successfully in 372 ms.
> 
> Input model: yolo_no_fake_input_segment_0_of_5.tflite
> Input size: 664.39KiB
> Output model: yolo_no_fake_input_segment_0_of_5_edgetpu.tflite
> Output size: 692.59KiB
> On-chip memory used for caching model parameters: 629.50KiB
> On-chip memory remaining for caching model parameters: 7.11MiB
> Off-chip memory used for streaming uncached model parameters: 0.00B
> Number of Edge TPU subgraphs: 1
> Total number of operations: 46
> Operation log: yolo_no_fake_input_segment_0_of_5_edgetpu.log
> 
> Operator                       Count      Status
> 
> PAD                            3          Mapped to Edge TPU
> DEPTHWISE_CONV_2D              12         Mapped to Edge TPU
> CONV_2D                        24         Mapped to Edge TPU
> ADD                            7          Mapped to Edge TPU
> 
> Model compiled successfully in 136 ms.
> ...
> Input model: yolo_no_fake_input_segment_4_of_5.tflite
> Input size: 828.06KiB
> Output model: yolo_no_fake_input_segment_4_of_5_edgetpu.tflite
> Output size: 29.91MiB
> On-chip memory used for caching model parameters: 799.50KiB
> On-chip memory remaining for caching model parameters: 7.04MiB
> Off-chip memory used for streaming uncached model parameters: 29.07MiB
> Number of Edge TPU subgraphs: 1
> Total number of operations: 4
> Operation log: yolo_no_fake_input_segment_4_of_5_edgetpu.log
> 
> Operator                       Count      Status
> 
> CONV_2D                        3          Mapped to Edge TPU
> RESHAPE                        1          Mapped to Edge TPU

The last output segment is always much larger so we decided to remove RESHAPE op just to check if it is causing this problem:

> $ edgetpu_compiler yolo_no_reshape.tflite -o 15.0/
> Edge TPU Compiler version 15.0.340273435
> 
> Model compiled successfully in 795 ms.
> 
> Input model: yolo_no_reshape.tflite
> Input size: 2.77MiB
> Output model: 15.0/yolo_no_reshape_edgetpu.tflite
> Output size: 2.81MiB
> On-chip memory used for caching model parameters: 2.71MiB
> On-chip memory remaining for caching model parameters: 5.02MiB
> Off-chip memory used for streaming uncached model parameters: 0.00B
> Number of Edge TPU subgraphs: 1
> Total number of operations: 67
> Operation log: 15.0/yolo_no_reshape_edgetpu.log
> See the operation log file for individual operation details.

The problem can be reproduced with [this file](https://drive.google.com/file/d/1wBBIPYATk4mMHai4CzQBgVGSLCeoOW9_/view?usp=sharing)

**Comment by Namburger** [comment]
@marcin-kamionowski can you give me access to that file?
It seems like it could be related to this bug: https://github.com/google-coral/edgetpu/issues/169
which should be fixed...

**Comment by Namburger** [comment]
@marcin-kamionowski it seems like you commented on that issue too, did you try compiling with 14.x?
if 14.x produces a small model, then it is likely that the bug still exist in some form :/

**Comment by Namburger** [comment]
Just got your model, also tried with 14.x and the model is still abnormally large, running in in our unreleased compiler got the model size down to 4MB. If you attach your whole model, I'll compile it for you, apologies for the issue

**Comment by hjonnala** [comment]
@marcin-kamionowski  can you please attach your full model.

**Comment by marcin-kamionowski** [comment]
@hjonnala:
[yolo_no_fake_input.zip](https://github.com/google-coral/edgetpu/files/6807764/yolo_no_fake_input.zip)

**Comment by hjonnala** [comment]
@marcin-kamionowski Thanks for sharing the full tflite model. I don't know the exact date of next release. This issue would be fixed in next release which is very soon.

**Comment by hjonnala** [comment]
@marcin-kamionowski producing large output model got resolved with the new release of edgetpu compiler

![image](https://user-images.githubusercontent.com/86132058/127181665-5837ca8c-b7b3-481c-b999-d173c075a296.png)
