### ISSUE TITLE
RuntimeError: tensorflow/lite/kernels/unidirectional_sequence_lstm.cc:938 num_intermediate_tensors == 5 was not true.Node number 0 (UNIDIRECTIONAL_SEQUENCE_LSTM) failed to prepare.

### ISSUE THREAD

**Issue by RobertChenKFC** [google-coral/edgetpu#323]
**System Information**
- OS: Ubuntu 18.04
- TensorFlow version: 2.5.0.dev20210225
- tflite-runtime version: 2.5.0
- edgetpu_compiler version: 15.0.340273435
- Device: Coral USB Accelerator

**Current Behavior**
I am trying to train a simple LSTM, perform post-training full integer quantization, and then run the quantized model on the edge TPU, but running the model resulted in the following error message:
```
Traceback (most recent call last):
  File "./run_lstm.py", line 29, in <module>
    interpreter.allocate_tensors()
  File "/local/robertchenkfc/tf-nightly/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 335, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/unidirectional_sequence_lstm.cc:938 num_intermediate_tensors == 5 was not true.Node number 0 (UNIDIRECTIONAL_SEQUENCE_LSTM) failed to prepare.
```
I have tried different models such as CNNs, and also tried to run the tflite model on the CPU (the model before being converted by the edgetpu compiler), and neither had any issues, so it seems to have something to do with running an LSTM on the edge TPU.

**Standalone Code to Reproduce the Issue**
The following are some links to the Jupyter Notebooks on Google Colab for creating and running the models (obviously, the model cannot be ran on Google Colab, the code is just uploaded there), as well as the trained model:
- [train and convert model](https://colab.research.google.com/drive/1z3s11iPkXVLyB7ZsAXsT3w5K7ZUMYaPA?usp=sharing)
- [run model](https://colab.research.google.com/drive/1rHp71oRF2fBnZFUILA4XbI-rcuO2lvQr?usp=sharing)
- [trained model](https://drive.google.com/file/d/1etui3ioPgNL2HJxJpMWWIC6myiCL5z8g/view?usp=sharing)

This is my first time submitting an issue on github, so feel free to tell me if some information should be added or made more clear. Thanks for the help in advance!

**Comment by Namburger** [comment]
@RobertChenKFC Thanks for checking in!
I believe this is due to the current released tflite_runtime version not able to handle the unidirectional lstm sequence yet. Could you also include the CPU tflite model?

**Comment by RobertChenKFC** [comment]
Sure, [here](https://drive.google.com/file/d/1be-B-bFNleN13irD58c84qa6wVVO5PXu/view?usp=sharing) it is. I also modified the code in the [Jupyter Notebook](https://colab.research.google.com/drive/1rHp71oRF2fBnZFUILA4XbI-rcuO2lvQr?usp=sharing) so that the CPU tflite model can be ran instead, and it seems to run without any errors.

**Comment by Namburger** [comment]
@RobertChenKFC just checked with my team mates, we are still experimenting with one directional LSTM model on the edgetpu runtime side, however, it should be working by next release!

**Comment by RobertChenKFC** [comment]
Ah okay, thanks for the update! Although I have a few questions:
- From the edgetpu_compiler output, it seems like the UNIDIRECTIONAL_SEQUENCE_LSTM operation is handled on the CPU (not mapped to the TPU), so I thought that at least for those operations, the behavior would be the same as those of the CPU tflite model's, but it seems like the error message is related to this operation that is handled on the CPU. Is there any reason why the same operation running on the CPU wouldn't work on the edge TPU model?
- Since this issue will be resolved by the next release, do I close the issue now? Or do I wait for the commit and make sure the issue is resolved before closing it?

**Comment by jdubz93** [comment]
when are you guys planning on providing a fix for this? I am also having the same issue. Is there any work around or must I not use edgetpu.

**Comment by hjonnala** [comment]
Hi @jdubz93 UNIDIRECTIONAL_SEQUENCE_LSTM support is added in the new compiler verison 16.0.384591198.
can you please share the files/scripts to reproduce the issue.

**Comment by RobertChenKFC** [comment]
There seems to be a new issue when running the same code but compiling with the new compiler instead:
```
Traceback (most recent call last):
  File "./run_lstm.py", line 32, in <module>
    interpreter.invoke()
  File "/home/robert/Programming/test/lstm_test/venv2/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 833, in invoke
    self._interpreter.Invoke()
RuntimeError: Failed to execute request. Executable 'model' must have fully deterministic DMA hints when DMA descriptors from device are disabled.Node number 1 (EdgeTpuDelegateForCustomOp) failed to invoke.
```
Here is my current environment:
* OS: Ubuntu 20.04
* TensorFlow version: 2.6.0
* tflite-runtime version: 2.5.0.post1
* edgetpu_compiler version: 16.0.384591198
* Device: Coral USB Accelerator

Looking at [this comment](https://github.com/google-coral/edgetpu/issues/156#issuecomment-891049265), it seems like I'm not the only one facing this issue, and that this problem only occurs on the USB accelerator. [Here](https://drive.google.com/file/d/1wnc8l1JYPV45vfnLW83HgjEc43U-ElYe/view?usp=sharing) is the CPU tflite model.

**Comment by hjonnala** [comment]
For LSTM model with USB accelerator please try the command below:

`USB_ENABLE_BULK_DESCRIPTORS_FROM_DEVICE=1 python3 run_lstm.py $PATH/weather_forecast_quant.tflite`.
You might experience high latency compared with CPU tflite model. So, it is recommended to use Dev board for LSTM models for better latency.

As a note, on Dev Board USB_ENABLE_BULK_DESCRIPTORS_FROM_DEVICE=1 is not required.

```
mendel@neat-snail:~$ python3 run_inference.py 
lstm_quant_edgetpu.tflite
2.25 ms
1.34 ms
1.29 ms
1.29 ms
1.28 ms
/home/mendel/lstm_quant_edgetpu.tflite 1
mendel@neat-snail:~$ vim run_inference.py 
mendel@neat-snail:~$ python3 run_inference.py 
lstm_quant.tflite
3.81 ms
0.89 ms
1.04 ms
1.35 ms
1.33 ms
/home/mendel/lstm_quant.tflite 1
```

**Comment by RobertChenKFC** [comment]
Thanks for the help. Setting `USB_ENABLE_BULK_DESCRIPTORS_FROM_DEVICE=1` did work. I guess I will close this issue.

**Comment by swarajbadhei** [comment]
Facing the same error. Tried the above solution. Did not seem to work.

**Conversion Parameters:**
fixed_input = tf.keras.layers.Input(
    shape=[100,42],
    batch_size=1,
    dtype=model.inputs[0].dtype,
    name="fixed_input"
)
    
fixed_output = model(fixed_input)
fixed_batch_model = tf.keras.models.Model(
        fixed_input,
        fixed_output
    )
converter = tf.lite.TFLiteConverter.from_keras_model(fixed_batch_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_types = [tf.int8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_quant_model = converter.convert()

**Getting the Error:**
RuntimeError: tensorflow/lite/kernels/unidirectional_sequence_lstm.cc:904 input_to_output_weights->dims->data[1] != n_input (24 != 0)Node number 2 (UNIDIRECTIONAL_SEQUENCE_LSTM) failed to prepare.

Please let me know if anybody made it work.

Thanks in Advance
