### ISSUE TITLE
Correct way to train mobilenet_edgetpu  and compile into edgetpu 

### ISSUE THREAD

**Issue by paul218** [google-coral/edgetpu#325]
I used the next,
tensorflow-gpu 1.15.3 to train mobilenet_edgetpu with pascal_voc_seg

python deeplab/train.py
--logtostderr
--training_number_of_steps="${NUM_ITERATIONS}"
--train_split="train"
--model_variant="mobilenet_edgetpu"
--output_stride=16
--decoder_output_stride=''
--aspp_convs_filters=256
--train_crop_size="513,513"
--train_batch_size=1
--dataset="pascal_voc_seg"
--tf_initial_checkpoint=${PATH_TO_INITIAL_CHECKPOINT}
--train_logdir=${PATH_TO_TRAIN_DIR}
--dataset_dir=${PATH_TO_DATASET}
--initialize_last_layer=false
--last_layers_contain_logits_only=true

to export:

python deeplab/export_model.py
--logtostderr
--checkpoint_path="${CKPT_PATH}"
--export_path="${EXPORT_PATH}"
--model_variant="mobilenet_edgetpu"
--output_stride=16
--decoder_output_stride=''
--num_classes=21
--crop_size=513
--crop_size=513
--inference_scales=1.0 \

to post-quantization i used TensorFlow-gpu 2.0

import os
import tempfile
import numpy as np
import tensorflow as tf

def representative_dataset_gen():
for _ in range(10):
dummy_image = tf.random.uniform([1, 513, 513, 3], 0., 255., dtype=tf.float32)
dummy_image = dummy_image / 127.5 - 1
yield [dummy_image]
MODEL_FILE = "/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/export/frozen_inference_graph.pb"
output_file=/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/tflite/model8_seg.tflite'
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
graph_def_file = MODEL_FILE,
input_arrays = ['sub_2'],
output_arrays = ['ResizeBilinear_2']
)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type =tf.uint8
tflite_model = converter.convert()
tflite_model_size = open(output_file, 'wb').write(tflite_model)

To compile into edge-tpu :

edgetpu_compiler /research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/tflite/model8_seg.tflite

and its outputs:

Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 592 ms.

Input model: /home/paul/base/UPM/proyecto_robot/Coral/models/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/tflite/model8_seg.tflite
Input size: 3.97MiB
Output model: model8_seg_edgetpu.tflite
Output size: 4.27MiB
On-chip memory used for caching model parameters: 1.88MiB
On-chip memory remaining for caching model parameters: 4.92MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 101
Operation log: model8_seg_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.

Number of operations that will run on Edge TPU: 59
Number of operations that will run on CPU: 42
See the operation log file for individual operation details.
Operator                       Count      Status

AVERAGE_POOL_2D                1          More than one subgraph is not supported
DEPTHWISE_CONV_2D              4          More than one subgraph is not supported
DEPTHWISE_CONV_2D              9          Mapped to Edge TPU
CONV_2D                        37         Mapped to Edge TPU
CONV_2D                        12         More than one subgraph is not supported
MUL                            4          More than one subgraph is not supported
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       1          Mapped to Edge TPU
QUANTIZE                       1          More than one subgraph is not supported
RESIZE_BILINEAR                1          Image-interpolation layer won't run precisely enough on Edge TPU
RESIZE_BILINEAR                1          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESIZE_BILINEAR                1          More than one subgraph is not supported
SPACE_TO_BATCH_ND              4          Operation not supported
ADD                            7          More than one subgraph is not supported
ADD                            12         Mapped to Edge TPU
BATCH_TO_SPACE_ND              4          Operation not supported
CONCATENATION                  1          More than one subgraph is not supported

Why i run only 59 of 101 operation in tpu. ¿what is my mistake?
I saw quantization in deeplad page

https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md

how is the correct way?

**Comment by Namburger** [comment]
@paul218 Could you include the model?

**Comment by paul218** [comment]
yes. 
the link of models.
https://drive.google.com/drive/folders/1TXLkiw-kZYfAzqMGS_Nv-i0PvRkzDMZY?usp=sharing

In the folder train, was the trained model with deeplab/train.py.

In the folder export, there are three models:

*frozen graph with deeplab/export_model.py: frozen_inference_graph.pb
*post-quantization model: model8_seg.tflite
*compile into edge-tpu: model8_seg_edgetpu.tflite

thanks for your help

**Comment by Naveen-Dodda** [comment]
Hello, 

Can you switch the post training quantization to Tf1.x. 
The complete model is not mapped due a unsupported Resize_bilinear variant op introduced by TF2.0

Can you conform if it works fine with TF1.x

Thanks

**Comment by paul218** [comment]
@Naveen-Dodda 
**I try with tensorflow-gpu 1.15.3,  python 3.6.9 the next code with some modifications.**

**import os
import tempfile
import numpy as np
import tensorflow as tf
print(tf.__version__)

def representative_dataset_gen():
    for _ in range(10):
        dummy_image = tf.random.uniform([1, 513, 513, 3], 0., 255., dtype=tf.float32)
        dummy_image = dummy_image / 127.5 - 1
        yield [dummy_image]

MODEL_FILE = "frozen_inference_graph.pb"
output_file='tflite/model8_seg.tflite'


converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file = MODEL_FILE, 
    input_arrays = ['MobilenetEdgeTPU/MobilenetEdgeTPU/input'],
    output_arrays = ['ArgMax']
)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8  # or tf.uint8
converter.inference_output_type = tf.uint8  # or tf.uint8


tflite_model = converter.convert()
tflite_model_size = open(output_file, 'wb').write(tflite_model)

tf_model_size = os.path.getsize(MODEL_FILE)
print('TensorFlow Model is  {} bytes'.format(tf_model_size))
print('TFLite Model is      {} bytes'.format(tflite_model_size))**

and there are the next errors:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-cf52f845769b> in <module>
     38 
     39 # Convert to TFLite Model
---> 40 tflite_model = converter.convert()
     41 
     42 tflite_model_size = open(output_file, 'wb').write(tflite_model)

~/base/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py in convert(self)
    991     if self._is_calibration_quantize():
    992       result = self._calibrate_quantize_model(result, inference_input_type,
--> 993                                               inference_output_type)
    994 
    995     return result

~/base/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py in _calibrate_quantize_model(self, result, inference_input_type, inference_output_type)
    237     return calibrate_quantize.calibrate_and_quantize(
    238         self.representative_dataset.input_gen, inference_input_type,
--> 239         inference_output_type, allow_float)
    240 
    241   def _get_base_converter_args(self):

~/base/lib/python3.6/site-packages/tensorflow_core/lite/python/optimize/calibrator.py in calibrate_and_quantize(self, dataset_gen, input_type, output_type, allow_float)
     73     self._calibrator.Prepare()
     74     for calibration_sample in dataset_gen():
---> 75       self._calibrator.FeedTensor(calibration_sample)
     76     return self._calibrator.QuantizeModel(
     77         np.dtype(input_type.as_numpy_dtype()).num,

~/base/lib/python3.6/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py in FeedTensor(self, input_value)
    110 
    111     def FeedTensor(self, input_value):
--> 112         return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_FeedTensor(self, input_value)
    113 
    114     def QuantizeModel(self, input_py_type, output_py_type, allow_float):

ValueError: Failed to convert value into readable tensor.
```

**Comment by paul218** [comment]
**I try the same code, but with tensorflow 2.3.0 and pyhton 3.6.9**

```
import os
import tempfile
import numpy as np
import tensorflow as tf
print(tf.version)

def representative_dataset_gen():
for _ in range(10):
dummy_image = tf.random.uniform([1, 513, 513, 3], 0., 255., dtype=tf.float32)
dummy_image = dummy_image / 127.5 - 1
yield [dummy_image]

MODEL_FILE = "frozen_inference_graph.pb"
output_file='tflite/model8_seg.tflite'

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
graph_def_file = MODEL_FILE,
input_arrays = ['MobilenetEdgeTPU/MobilenetEdgeTPU/input'],
output_arrays = ['ArgMax']
)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8 # or tf.uint8
converter.inference_output_type = tf.uint8 # or tf.uint8

tflite_model = converter.convert()
tflite_model_size = open(output_file, 'wb').write(tflite_model)

tf_model_size = os.path.getsize(MODEL_FILE)
print('TensorFlow Model is {} bytes'.format(tf_model_size))
print('TFLite Model is {} bytes'.format(tflite_model_size))

```

**And EURECA¡¡¡¡¡¡ the most layers are into edge-TPU**

```
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 1641 ms.

Input model: model8_seg.tflite
Input size: 4.14MiB
Output model: model8_seg_edgetpu.tflite
Output size: 4.67MiB
On-chip memory used for caching model parameters: 4.03MiB
On-chip memory remaining for caching model parameters: 2.76MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 85
Operation log: model8_seg_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 77
Number of operations that will run on CPU: 8

Operator                       Count      Status

CONCATENATION                  1          More than one subgraph is not supported
DEPTHWISE_CONV_2D              13         Mapped to Edge TPU
RESIZE_BILINEAR                1          Image-interpolation layer won't run precisely enough on Edge TPU
RESIZE_BILINEAR                2          More than one subgraph is not supported
AVERAGE_POOL_2D                1          Mapped to Edge TPU
CONV_2D                        47         Mapped to Edge TPU
CONV_2D                        2          More than one subgraph is not supported
QUANTIZE                       1          Mapped to Edge TPU
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
ARG_MAX                        1          Operation is working on an unsupported data type
ADD                            15         Mapped to Edge TPU
```

**Comment by Naveen-Dodda** [comment]
@paul218  Thanks for the Update. Glad that Tf2.3 solved the issue. 

Since you are able to solve the issue, I am closing the issue for now. Please feel free to reopen if you have any questions.

**Comment by JiashuGuo** [comment]
> CONCATENATION                  1          More than one subgraph is not supported
> DEPTHWISE_CONV_2D              13         Mapped to Edge TPU
> RESIZE_BILINEAR                1          Image-interpolation layer won't run precisely enough on Edge TPU
> RESIZE_BILINEAR                2          More than one subgraph is not supported
> AVERAGE_POOL_2D                1          Mapped to Edge TPU
> CONV_2D                        47         Mapped to Edge TPU
> CONV_2D                        2          More than one subgraph is not supported
> QUANTIZE                       1          Mapped to Edge TPU

I got similar results to this one, but when I run the model on Coral Edgetpu it was much slower than the model Coral published. Have you tried to run the compiled model?
