### ISSUE TITLE
How to investigate camera connection problems with Coral Mini

### ISSUE THREAD

**Issue by johannes-do** [google-coral/edgetpu#327]
Brand new hardware (coral camera, coral dev board mini). Followed the getting started guide without any problems.

But when connecting the coral camera, it does not show up when running `v4l2-ctl --list-devices` and `snapshot` complains it can not find any camera. Already tried reflashing. Same result.

Imho the most probable issue is the ribbon cable. I have had that more than once with raspberry pi cameras that switching out the cable resolved connection issues. But since the cable is different to the raspberry pi connection, it is kind of hard to test. I am honestly having a hard time finding a replacement cable on the internet. (Is [this](https://www.mouser.de/ProductDetail/Wurth-Elektronik/687624050002?qs=P%2FTEqz%252BQfndQFFKLalvVUA==) the correct one?).

Any other ideas that could be causing issues and what I could check? Yes, the cables are correctly plugged in :)

**Comment by Namburger** [comment]
@j-o-d-o 
humn, I don't know of any replacement cable, unfortunately :/
How have you confirm that the cable/camera is working? Have you had a chance to try plugging it back to the original dev board to see if it detects it?

**Comment by johannes-do** [comment]
No, I just have one Dev Board. I currently see no option for testing the camera other than getting another board and/or camera.

The ribbon cable is just a wild guess on my side. I opened the issue to maybe get some more creative ideas on how to further test the hardware and to make sure that I would buy the correct ribbon cable. (I just ordered it now, its really cheap)

But I understand that this issue is basically impossible to solve remotely from a github issue. Closing this.

**Comment by johannes-do** [comment]
Update, the replacement cables did not fix the issue.

And a word of advice, if you buy the cables from the link I posted, they have the blue coloring at the end of the cable flipped. Thus you will have one side different from what the official documentation shows. I had it the wrong way for the first time and afterwards the board wouldn't boot up anymore, had to force flash it again. Luckily it seems not more broken than before ; )

Next up, I will try to get my hands on another set of coral camera + coral dev board to check the hardware.

**Comment by johannes-do** [comment]
Update2: I got myself a new board and a new camera. Turns out the camera is just broken. That simple. The new one works fine on both boards.
