### ISSUE TITLE
Wifi device on coral dev board stopped working

### ISSUE THREAD

**Issue by dfm794** [google-coral/edgetpu#329]
A few days ago my coral board dropped off the network. After investigating a bit, I can connect to the board if I plug in an ethernet cable. nmtui-> 'edit a connection' shows the wifi setup is still present. However, no wlan0 shows up under activate a connection or via /sbin/ifconfig from the command line. I don't see anything that looks like a wifi device in the output from dmesg.

Any idea how to recover wifi?

**Comment by Namburger** [comment]
@dfm794 Thanks for reaching out!
Just for assurance, could you share the outputs of these commands?
```
$  nmcli connection show
$  ip addr
```

**Comment by dfm794** [comment]
> @dfm794 Thanks for reaching out!
> Just for assurance, could you share the outputs of these commands?
> 
> ```
> $  nmcli connection show
> $  ip addr
> ```

Sure...keep in mind I connected an ethernet cable to get a connection after wifi failed...
mendel@jumping-rabbit:~$ nmcli connection show
NAME                UUID                                  TYPE      DEVICE 
gadget0             a70367f2-3251-499f-ac16-cb47cbe91c49  ethernet  usb0   
gadget1             149b5035-0ead-4b65-b04e-ab7f116639d7  ethernet  usb1   
Wired connection 1  7e23bb82-30ec-3ef1-ad92-0e7afa69115c  ethernet  eth0   
ORBI26              3f4285f5-d741-4304-b1b3-b1b9b9a4f4f9  wifi      --     
mendel@jumping-rabbit:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether f4:f5:e8:51:fd:0c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.87/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 52266sec preferred_lft 52266sec
    inet6 fd62:f85d:6af4:1:55ff:eba6:ac66:86af/64 scope global dynamic noprefixroute 
       valid_lft 1629sec preferred_lft 1629sec
    inet6 fe80::4b3c:9fb9:4e1c:5276/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: usb0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 02:22:78:0d:f6:df brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.2/24 brd 192.168.100.255 scope global noprefixroute usb0
       valid_lft forever preferred_lft forever
    inet6 fe80::9d92:fd3d:f70a:9258/64 scope link tentative noprefixroute 
       valid_lft forever preferred_lft forever
4: usb1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 02:22:78:0d:f6:de brd ff:ff:ff:ff:ff:ff
    inet 192.168.101.2/24 brd 192.168.101.255 scope global noprefixroute usb1
       valid_lft forever preferred_lft forever
    inet6 fe80::cc2b:ec1d:af:b29b/64 scope link tentative noprefixroute 
       valid_lft forever preferred_lft forever
mendel@jumping-rabbit:~$

**Comment by dfm794** [comment]
hmmm. don't know why the editor decided to strikethrough the nmcli command, so here it is again
mendel@jumping-rabbit:~$ nmcli connection show
NAME                UUID                                  TYPE      DEVICE 
gadget0             a70367f2-3251-499f-ac16-cb47cbe91c49  ethernet  usb0   
gadget1             149b5035-0ead-4b65-b04e-ab7f116639d7  ethernet  usb1   
Wired connection 1  7e23bb82-30ec-3ef1-ad92-0e7afa69115c  ethernet  eth0   
ORBI26              3f4285f5-d741-4304-b1b3-b1b9b9a4f4f9  wifi      --

**Comment by mbrooksx** [comment]
Can you output the following dmesg command:
sudo dmesg | grep -iE 'wlan|pcie'

I have a feeling that the device is not enumerating.

**Comment by dfm794** [comment]
> Can you output the following dmesg command:
> sudo dmesg | grep -iE 'wlan|pcie'
> 
> I have a feeling that the device is not enumerating.

Sure...
mendel@jumping-rabbit:~$ sudo dmesg | grep -iE 'wlan|pcie'
[    0.000000] Kernel command line: console=ttymxc0,115200 console=tty0 earlycon=ec_imx6q,0x30860000,115200 root=PARTUUID=70672ec3-5eee-49ff-b3b1-eb1fbd406bf5 rootfstype=ext4 rw rootwait init=/sbin/init net.ifnames=0 pci=pcie_bus_perf
[    8.118979] imx6q-pcie 33800000.pcie: 33800000.pcie supply epdev_on not found, using dummy regulator
[    8.128567] OF: PCI: host bridge /pcie@0x33800000 ranges:
[    8.133985] OF: PCI:   No bus range found for /pcie@0x33800000, using [bus 00-ff]
[    8.155810] imx6q-pcie 33800000.pcie: pcie phy pll is locked.
[    8.405777] imx6q-pcie 33800000.pcie: phy link never came up
[    8.411461] imx6q-pcie 33800000.pcie: failed to initialize host
[    8.417394] imx6q-pcie 33800000.pcie: unable to add pcie port.
[    8.424056] imx6q-pcie: probe of 33800000.pcie failed with error -110
[    8.432336] imx6q-pcie 33c00000.pcie: 33c00000.pcie supply epdev_on not found, using dummy regulator
[    8.441840] OF: PCI: host bridge /pcie@0x33c00000 ranges:
[    8.447439] OF: PCI:   No bus range found for /pcie@0x33c00000, using [bus 00-ff]
[    8.470983] imx6q-pcie 33c00000.pcie: pcie phy pll is locked.
[    8.532223] imx6q-pcie 33c00000.pcie: Link up, Gen2
[    8.539900] imx6q-pcie 33c00000.pcie: PCI host bridge to bus 0000:00
[    8.645121] pcieport 0000:00:00.0: Signaling PME with IRQ 362
[    8.651055] pcieport 0000:00:00.0: AER enabled with IRQ 362
mendel@jumping-rabbit:~$

**Comment by dfm794** [comment]
Sure... here it is.
mendel@jumping-rabbit:$ sudo dmesg | grep -iE 'wlan|pcie'
[    0.000000] Kernel command line: console=ttymxc0,115200 console=tty0 earlycon=ec_imx6q,0x30860000,115200 root=PARTUUID=70672ec3-5eee-49ff-b3b1-eb1fbd406bf5 rootfstype=ext4 rw rootwait init=/sbin/init net.ifnames=0 pci=pcie_bus_perf
[    8.118979] imx6q-pcie 33800000.pcie: 33800000.pcie supply epdev_on not found, using dummy regulator
[    8.128567] OF: PCI: host bridge /pcie@0x33800000 ranges:
[    8.133985] OF: PCI:   No bus range found for /pcie@0x33800000, using [bus 00-ff]
[    8.155810] imx6q-pcie 33800000.pcie: pcie phy pll is locked.
[    8.405777] imx6q-pcie 33800000.pcie: phy link never came up
[    8.411461] imx6q-pcie 33800000.pcie: failed to initialize host
[    8.417394] imx6q-pcie 33800000.pcie: unable to add pcie port.
[    8.424056] imx6q-pcie: probe of 33800000.pcie failed with error -110
[    8.432336] imx6q-pcie 33c00000.pcie: 33c00000.pcie supply epdev_on not found, using dummy regulator
[    8.441840] OF: PCI: host bridge /pcie@0x33c00000 ranges:
[    8.447439] OF: PCI:   No bus range found for /pcie@0x33c00000, using [bus 00-ff]
[    8.470983] imx6q-pcie 33c00000.pcie: pcie phy pll is locked.
[    8.532223] imx6q-pcie 33c00000.pcie: Link up, Gen2
[    8.539900] imx6q-pcie 33c00000.pcie: PCI host bridge to bus 0000:00
[    8.645121] pcieport 0000:00:00.0: Signaling PME with IRQ 362
[    8.651055] pcieport 0000:00:00.0: AER enabled with IRQ 362
mendel@jumping-rabbit:$

**Comment by mbrooksx** [comment]
This looks like a PCIe failure. Please contact coral-support@google.com and link this thread, we may need to replace the board due to the faulty phy.
