### ISSUE TITLE
Potential memory corruption using C API and certain models

### ISSUE THREAD

**Issue by snowzach** [google-coral/edgetpu#33]
I have been developing Doods https://github.com/snowzach/doods which is a Go wrapper around tensorflow and tensorflow lite with edgetpu support. It performs object detection. It uses the C api and CGO to call it. 

When using models from the Coral EdgeTPU site it works great. I've run it days at a time with no issues. 

I have been trying now using a few other models and I get all kinds of strange issues. 
This model for the Pixel 4 from the model Zoo randomly returns strange results and sometimes even segfaults when running lots of times in a row: https://storage.cloud.google.com/mobilenet_edgetpu/checkpoints/ssdlite_mobilenet_edgetpu_coco_quant.tar.gz

One of my users provided me with this model that supposedly works fine in python: https://github.com/snowzach/doods/files/3923689/raccoon_edgetpu.tflite.zip
I understand it works fine with the python API. 

Since I pretty much just call the C API. I'm not sure how to debug.

**Comment by Namburger** [comment]
@snowzach Hi again :) checking this out now!
Could you provide some extra instructions on how to recreate the issue? Is this just something that happens after running a large number of invoke() iterations on those model?

**Comment by snowzach** [comment]
I am going to try to create a C program to do it rather than have Go calling C. It's pretty simple though in pseudocode:

SETUP:
1. model = TfLiteModelCreateFromFile
2. options = TfLiteInterpreterOptionsCreate
3. TfLiteInterpreterOptionsSetNumThreads(options)
4. TfLiteInterpreterOptionsAddDelegate(options, edgetpu_create_delegate)
5. interpreter = TfLiteInterpreterCreate(model, options)
6. TfLiteInterpreterAllocateTensors(interpreter)

LOOP:
1. tensor = TfLiteInterpreterGetInputTensor(interpreter, 0)
2. TfLiteTensorCopyFromBuffer(tensor, data, size) (Raw RGB image data)
3. TfLiteInterpreterInvoke(interpreter)
4. Deal with results

All the Object Detection Models from here seem to work fine: https://coral.ai/models/

**Comment by Namburger** [comment]
@snowzach I think that sounds good, separating the c api from the cgo calls to see if the issue can be reproduced. Something I'm trying right now is to just run our example's [minimal.cc](https://github.com/google-coral/edgetpu/blob/master/src/cpp/examples/minimal.cc) code with 1000000 RunInference iterations on your [ssdlite_mobilenet_edgetpu_coco_quant.tar.gz](https://storage.cloud.google.com/mobilenet_edgetpu/checkpoints/ssdlite_mobilenet_edgetpu_coco_quant.tar.gz). I'm at 55k iterations now without seeing much movement in memory usage.

**Comment by snowzach** [comment]
Okay, I am going back through this and I realized these models that I am having issues with are not the same as the other object detection models I am having issues with. I am used to having 4 output tensors with count, boxes, classes and scores. The racoon one just has one score and the other one has 12 outputs. 

At this point, I do not believe this is an edgeTPU issue. Sorry for the distraction.

**Comment by Namburger** [comment]
@snowzach Hope you get to see this. I have created something similar to your project over the weekend but in c++ :) 
Honorably mentioned your project on my [README.md](https://github.com/Namburger/restor/blob/master/README.md) for the idea!
