### ISSUE TITLE
Google Coral M.2 at mini PCIe not detected

### ISSUE THREAD

**Issue by arun-kumark** [google-coral/edgetpu#334]
Hi,

I am using the M.2 on Mini PCIe and facing issues.
I referred already open and closed issues for M.2 card but nothing worked so far.

I have a fresh installation of Ubuntu18.04 and am following the steps mentioned here:
https://coral.ai/docs/m2/get-started/#2a-on-linux

**But lspci -nn | grep 089a returns nothing.**

my dmesg is attached after reboot.
**dmesg.txt**

I don't see anything in ls /dev/apex_0

**uname -r**
Linux google 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**lspci -vvv**
attached as lspci.txt

**google@google:~$ modinfo gasket**
filename:       /lib/modules/5.4.0-66-generic/updates/dkms/gasket.ko
author:         Rob Springer <rspringer@google.com>
license:        GPL v2
version:        1.1.3
description:    Google Gasket driver framework
srcversion:     EE63B2D1E7E5BEBAF51CEE1
depends:        
retpoline:      Y
name:           gasket
vermagic:       5.4.0-66-generic SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4
parm:           dma_bit_mask:int

**google@google:~$ modinfo apex**
filename:       /lib/modules/5.4.0-66-generic/updates/dkms/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.1
description:    Google Apex driver
srcversion:     58E1862C107AD9271AA7ADA
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
retpoline:      Y
name:           apex
vermagic:       5.4.0-66-generic SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
parm:           trip_point0_temp:int
parm:           trip_point1_temp:int
parm:           trip_point2_temp:int
parm:           hw_temp_warn1:int
parm:           hw_temp_warn2:int
parm:           hw_temp_warn1_en:bool
parm:           hw_temp_warn2_en:bool
parm:           temp_poll_interval:int
[dmesg.txt](https://github.com/google-coral/edgetpu/files/6094978/dmesg.txt)
[lspci.txt](https://github.com/google-coral/edgetpu/files/6094981/lspci.txt)

Could you please help?
Thank you
Arun

**Comment by manoj7410** [comment]
@arun-kumark Which host machine are you working with? Can you share the output of 'lscpu' ? 
PS: Are you sure that your machine boots fine and you don't face any hang or lag. I see these errors in the BIOS: 

[    8.187455] ACPI BIOS Error (bug): AE_AML_PACKAGE_LIMIT, Index (0x0000000FF) is beyond end of object

**Comment by arun-kumark** [comment]
Yes, here it is:

google@google:~$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               150
Model name:          Genuine Intel(R) CPU 0000 @ 1.90GHz
Stepping:            1
CPU MHz:             739.421
CPU max MHz:         1900,0000
CPU min MHz:         800,0000
BogoMIPS:            3763.20
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1536K
L3 cache:            4096K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault epb cat_l2 cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms rdt_a rdseed smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip waitpkg gfni rdpid movdiri movdir64b md_clear flush_l1d arch_capabilities

**Comment by manoj7410** [comment]
@arun-kumark Can you please share the output of : 
lsmod | grep apex

**Comment by arun-kumark** [comment]
It returns nothing ... 

```
google@google:~$ lsmod | grep apex
google@google:~$
```

**Comment by manoj7410** [comment]
Are you sure that your machine boots fine and you don't face any hang or lag. I see these errors in the BIOS:

[ 8.187455] ACPI BIOS Error (bug): AE_AML_PACKAGE_LIMIT, Index (0x0000000FF) is beyond end of object

**Comment by arun-kumark** [comment]
Yes, the machine boots fine, I am able to do the normal work on the machine. do you see this could be the problem ?

**Comment by manoj7410** [comment]
@arun-kumark Can you also share the output of :

sudo lspci -vvv

**Comment by manoj7410** [comment]
Marking this as closed due to lack of activity. Feel free to reopen if this issue is still persistent.

**Comment by arun-kumark** [comment]
Sorry, it was a BIOS bug which was not binding the driver correctly, so the device just appeared at the time of boot and later disappeared. Now it has been solved with solving the BIOS bug. thanks for closing.

**Comment by bluearcher-bc** [comment]
EDIT: Disregard, problem solved - "Wireless" was disabled in the BIOS and this appears to shut down the M.2 slot entirely

**Comment by arun-kumark** [comment]
Thats great ! :)
