### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by akosb** [google-coral/edgetpu#335]
Hi,

 just noticed that a new version of Mendel Linux become available ([5.2 Eagle (Feb 2021) | enterprise-eagle-20210204152958.zip](https://coral.ai/software/#mendel-linux)). This was not mentioned in the '[Releases](https://coral.ai/news/#releases)' section, so it's hard to know what this upgrade contains?

Regards, Akos

PS: [here](https://vaew.io/coral07/index.html) is a short demo how to use Coral Board with Azure IoT Hub

**Comment by manoj7410** [comment]
@akosb Thank you for bringing this to our notice. Have filed a bug with our documentation team regarding this.

**Comment by mbrooksx** [comment]
The documentation for the release can be found here:  https://coral.googlesource.com/docs/+/refs/heads/master/Releases.md
