### ISSUE TITLE
Does edgetpu support EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8?

### ISSUE THREAD

**Issue by Kuan-ChiehHsu** [google-coral/edgetpu#338]
Hi,
I found the EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8 flag is an [experimental feature](https://www.tensorflow.org/lite/performance/post_training_integer_quant_16x8) and there is example code to convert model into tflite model. However, the example code seems only run the 16x8 model on CPU. I'm wondering if edgetpu can support the 16 bit activation feature?
After searching around, I found that only [certain tf version](https://github.com/google-coral/edgetpu/issues/168) can support this flag such as tf2.4 or tf-nightly. And there is no way for edgetpu _compiler to convert int16 enabled model. If I try to run tflite model (not converted by edgetpu_compiler one) on edgetpu, it shows the following message:
```
ERROR: external/org_tensorflow/tensorflow/lite/kernels/conv.cc:304 input_type == kTfLiteFloat32 || input_type == kTfLiteUInt8 || input_type == kTfLiteInt8 was not true.
ERROR: Node number 4 (CONV_2D) failed to prepare.
```
This happens when I try to give int16_t data for input pointer when using C++ .
```
int16_t* input = interpreter.get()->typed_input_tensor<int16_t>(0);
```

edgetpu_compiler version: 15.0.340273435

**Comment by Namburger** [comment]
@jk78346 We only accept int8 and float32 inputs at this time. 
For the float32 case, only input/output is allowed to be float, intermediate tensors should still be int8!

**Comment by Kuan-ChiehHsu** [comment]
Does this int16x8 experimental flag going to be any future feature of edgetpu?
Is edgetpu, the hardware itself, designed to be able to only process int8 data type, and not any other types (such as int16 activation)?

**Comment by Naveen-Dodda** [comment]
Yes, edgetpu V1, the hardware itself, designed to be able to only process int8 data type, and not any other types.
