### ISSUE TITLE
ERROR: Didn't find op for builtin opcode 'REVERSE_V2' version '3'

### ISSUE THREAD

**Issue by ghost** [google-coral/edgetpu#340]
Hi all!

When I try to compile a quantized tflite-model I get the following error message. Have I done something wrong when quantizing my model or does it simply contain something that is not supported by edgetpu?

```
Edge TPU Compiler version 15.0.340273435
ERROR: Didn't find op for builtin opcode 'REVERSE_V2' version '3'

ERROR: Registration failed.

Invalid model: /content/q8model.tflite
Model could not be parsed
```

**Comment by ghost** [comment]
[q8model.tflite.zip](https://github.com/google-coral/edgetpu/files/6166693/q8model.tflite.zip)

Model attached. The code used to quantize ->

```
model.input.set_shape((1,) + model.input.shape[1:])
print(model.input.shape)


def representative_dataset():
    for _ in range(100):
      data = np.random.rand(1, 20)
      yield [data.astype(np.int32)]
 

converter = tf.lite.TFLiteConverter.from_keras_model(model)
#converter = tf.lite.TFLiteConverter.from_saved_model(SAVE_PATH)
converter.experimental_new_converter = True
converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
tflite_model = converter.convert()

# Save the model.
with open('/content/q8model.tflite', 'wb') as f:
  f.write(tflite_model)
```

**Comment by Namburger** [comment]
@Haag-se This mostlikely means that the compiler doesn't support this op yet, but let me confirm!

**Comment by ghost** [comment]
Changing the LSTM layers from bidirectional to undirectional made it compile. However, in runtime I get the same error as in issue #323 

Seems like my initial error was from an unsupported op (REVERSE_V2). Case closed! 

Thank you for replying and helping me sorting this out.
