### ISSUE TITLE
'Internal compiler error. Aborting!', EfficientDet D0

### ISSUE THREAD

**Issue by masc-it** [google-coral/edgetpu#344]
Hello, I've successfully trained (with post training quantization, tf 2.4.1) EfficientDet-D0 512x512 and converted it to tflite.
As soon as I run `!edgetpu_compiler -s "export/model.tflite"` I get a way too generic: 'Internal compiler error. Aborting!'.

As I read in other issues, it's not about unsupported operations, maybe something about number of params. It would be great to have a more detailed message though.. 

In the end, can I do anything about this?

**Comment by manoj7410** [comment]
@masc-it Can you please share your model at coral-support@google.com ?

**Comment by masc-it** [comment]
@manoj7410 sure can! Sending it right now

**Comment by mbrooksx** [comment]
Hi @masc-it ,

EfficientDet won't directly compile to the EdgeTPU. We've been working with the team for EfficientDet-Lite: https://tfhub.dev/tensorflow/lite-model/efficientdet/lite0/int8/1. This model can be trained and compiled for the EdgeTPU. We are working to add Lite0-Lite4 onto our website as well as instructions for retraining using https://www.tensorflow.org/lite/guide/model_maker.

**Comment by masc-it** [comment]
@mbrooksx great! So we will be to train it using the classical model.pipeline and tf1 ? Just in case, if you're going to release some beta version of it I'd be available to test it (training or whatever). 
In general it would be great if you let the open source community test and, in case, help debugging new models (maybe a 'beta' section?)

**Comment by Naveen-Dodda** [comment]
@masc-it 

You can find more details in this page to train[ EfficientNetDet-lite](https://tfhub.dev/tensorflow/efficientdet/lite1/feature-vector/1). 

I shall keep you posted if come across any additional details about Det-lite
