### ISSUE TITLE
'clear' not working when remote access dev board

### ISSUE THREAD

**Issue by harrison0451** [google-coral/edgetpu#348]
hello,

I am using gitbash mingw64 and when I remote access google dev board, mdt shell works well,
but after typing in "clear", it does NOT clear the screen.

if run command "clear" locally, it does clear the screen. so i doubt my mendel system missing some file or I did not set up correctly?

**Comment by Namburger** [comment]
@harrison0451 I see, the problem could also be with git bash.. 
Does this happen if you ssh from a linux machine?

**Comment by harrison0451** [comment]
git bash may not set up well.
I am using window10 now and do you think  Xmanager (Xshell) a good SSH for edgetpu project development?
and how much do I need a linux machine? I mean should I switch to linux immediately?
thanks!

**Comment by harrison0451** [comment]
> @harrison0451 I see, the problem could also be with git bash..
> Does this happen if you ssh from a linux machine?

git bash may not set up well.
I am using window10 now and do you think Xmanager (Xshell) a good SSH for edgetpu project development?
and how much do I need a linux machine? I mean should I switch to linux immediately?
thanks!

**Comment by Namburger** [comment]
@harrison0451 linux is not extremely necessary, but recommended :)
I guess Xmanager is fine, I believe the issue is just with gitbash, you may even try with WSL

**Comment by harrison0451** [comment]
SSH using WSL will solve this issue. clear works, and vim editor working well at the same time.
thanks!
