### ISSUE TITLE
can not edit file using vim 

### ISSUE THREAD

**Issue by harrison0451** [google-coral/edgetpu#349]
hello,

I am using google dev board, mdt shell working well and I can run demo without any issue.
but when I try to edit .txt or .py file using vim, the output looks strange, see attachment.

![vim_edit](https://user-images.githubusercontent.com/81446036/112702295-37d27780-8e50-11eb-8072-b235d163701e.png)

how to set it up and make this work? Thanks!

**Comment by Namburger** [comment]
@harrison0451 this is quite odd as I'm able to use vim in mdt without issues, is this also a problem with ssh?

**Comment by harrison0451** [comment]
using WSL SSH will solve this issue.
