### ISSUE TITLE
Internal error on same model, different training

### ISSUE THREAD

**Issue by agjunyent** [google-coral/edgetpu#350]
Hi!

I'm getting a strange error when trying to compile a model that I've already compiled before with no problems. The error is just "Internal error", with no more information.

I attach here the two models, the one that works and the one that does not. They are based from the same keras model, just different training (different hyperparams and classes).

[models.zip](https://github.com/google-coral/edgetpu/files/6217789/models.zip)

The one named "model_OK.tflite" compiles fine.
The one named "model_KO.tflite" gives the internal error.

I've used Netron to visualize the tflite models and they look exact to me. I don't understand what is happening at all.

thanks

**Comment by masc-it** [comment]
@agjunyent try adding `-s -m 10` or `-s -m 11` flags when calling the compiler. Even though it didn't fix the problem in my case, at least it showed me some debugging info, apart the lame 'internal error'.

**Comment by Naveen-Dodda** [comment]
Hello, 

can you please cross and conform the models you have shared.

model_KO.tflite compiles fine to me 
model_OK.tflite fails 

But the primary reason for the failure is tflite quantization has set the factor to infinity in the model. Can you share more details about how you have quantized the models ?

**Comment by Naveen-Dodda** [comment]
Any updates here

**Comment by Naveen-Dodda** [comment]
Hello, 

Do you have nay updates here ?
