### ISSUE TITLE
Bluetooth firmware loader

### ISSUE THREAD

**Issue by vganjali** [google-coral/edgetpu#355]
Looking into _systemctl_ logs (`sudo systemctl --failed`), I realized a service called **btfw_loader.service** fails to load on my Coral Dev Board. btfw_loader.service executes `ExecStart=/usr/bin/hciattach /dev/ttymxc1 qca 1000000 flow -b -t 120` while there is no **hciattach** in my system. Was wondering if this an issue with my mendel installation or the Bluetooth service is not implemented for Coral Dev Board yet.
Currently I do not need Bluetooth connection, just wanted to report it!
_Kernel version: 4.14.98-imx_

**Comment by Namburger** [comment]
@vganjali I believe what's missing is that you'll need to enable this kernel option on the defconfig
```
CONFIG_BT_HCIUART_BCM=y
```
See here for how to do this: https://github.com/f0cal/google-coral/issues/56#issuecomment-632120325

**Comment by mbrooksx** [comment]
Thanks for the report @vganjali . Note that we do test hciattach specifically and include a package for bluez tools (https://coral.googlesource.com/bluez-imx-debian/) - perhaps there is something missing in your install.

**Comment by vganjali** [comment]
> 
> 
> @vganjali I believe what's missing is that you'll need to enable this kernel option on the defconfig
> 
> ```
> CONFIG_BT_HCIUART_BCM=y
> ```
> 
> See here for how to do this: [f0cal/google-coral#56 (comment)](https://github.com/f0cal/google-coral/issues/56#issuecomment-632120325)

@Namburger  thanks for the reply. I will check kernel options. It would be nicer to have a cmdline.txt to config Coral board during the boot time rather than compiling the kernel for each change (just like RPi).


> 
> 
> Thanks for the report @vganjali . Note that we do test hciattach specifically and include a package for bluez tools (https://coral.googlesource.com/bluez-imx-debian/) - perhaps there is something missing in your install.

Thanks @mbrooksx I hadn't heard of bluez tools before, that was very informative!

**Comment by manoj7410** [comment]
@vganjali Were you able to fix this problem ?

**Comment by manoj7410** [comment]
Feel free to reopen if the issue still persists.
