### ISSUE TITLE
Many operations not mapped and internal error when using -a flag on edgetpu_compiler

### ISSUE THREAD

**Issue by aviraljain99** [google-coral/edgetpu#356]
I am trying to compile the ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8 from the [tensorflow object detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). I have trained this model on my own custom dataset and I have used the [export_tflite_graph_tf2.py](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_tf2.py) script to export my model. Without the -a flag, this is the compiler output that I get:

```
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 2006 ms.

Input model: ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8_full_integer.tflite
Input size: 4.17MiB
Output model: ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8_full_integer_edgetpu.tflite
Output size: 4.75MiB
On-chip memory used for caching model parameters: 3.21MiB
On-chip memory remaining for caching model parameters: 3.78MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 161
Operation log: ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8_full_integer_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 111
Number of operations that will run on CPU: 50

Operator                       Count      Status

DEQUANTIZE                     2          Operation is working on an unsupported data type
QUANTIZE                       4          Operation is otherwise supported, but not mapped due to some unspecified limitation
DEPTHWISE_CONV_2D              14         More than one subgraph is not supported
DEPTHWISE_CONV_2D              37         Mapped to Edge TPU
CONV_2D                        14         More than one subgraph is not supported
CONV_2D                        58         Mapped to Edge TPU
LOGISTIC                       1          More than one subgraph is not supported
RESHAPE                        3          More than one subgraph is not supported
RESHAPE                        6          Mapped to Edge TPU
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  2          More than one subgraph is not supported
PACK                           4          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
ADD                            2          More than one subgraph is not supported
ADD                            10         Mapped to Edge TPU
CUSTOM                         1          Operation is working on an unsupported data type
```

The TFLite model was created using the following Python script:
<details>

<summary>Python Code to perform full-integer post-training quantization</summary>

```python
# For performing full or half way integer quantization
def representative_data_gen():
    dataset_list = tf.data.Dataset.list_files(train_img_dir + '/*')
    for i in range(1000):
        if (i % 100 == 0):
            print(i)
        image = next(iter(dataset_list))
        image = tf.io.read_file(image)
        image = tf.io.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [IMAGE_SIZE, IMAGE_SIZE])
        # Do the images need to be normalized?
        # image = tf.cast(image / 255., tf.float32)
        image = tf.expand_dims(image, 0)
        yield [image]

converter = tf.lite.TFLiteConverter.from_saved_model(os.path.join(args.model_dir, 'exported', 'saved_model'))

# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# This sets the representative dataset for quantization
converter.representative_dataset = representative_data_gen
converter.experimental_new_converter = True

print("Performing full quantization")
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

# For full integer quantization, though supported types defaults to int8 only, we explicitly declare it for clarity.
converter.target_spec.supported_types = [tf.int8]

# These set the input and output tensors to uint8 (added in r2.3)
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

converter.allow_custom_ops = True

tflite_model = converter.convert()

with open(os.path.join(args.model_dir, args.quant_type, args.model_dir + "_"+ args.quant_type + ".tflite"), 'wb') as f:
    f.write(tflite_model)
```

</details>

When I use the "-a" flag on the compiler to map more operations to the EdgeTPU, I get the following output:

`Internal compiler error. Aborting! `

Could I get some assistance with understanding how I could make more of the operations get mapped to the EdgeTPU? Or maybe some help with why the "-a" flag causes an internal error? 

This is my model that is converted using post-training quantization: [ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8](https://drive.google.com/file/d/1JSZk2ZF23EE9cW68Ze5yowLTdzWm5wms/view?usp=sharing)

This is my TFlite model that is converted without any post-training quantization;  [basic_tflite_model](https://drive.google.com/file/d/1IBBeeddZN_3VGk6_Qaj4uIn07G7_aASq/view?usp=sharing)

**Comment by Naveen-Dodda** [comment]
@aviraljain99 

-a flag has few limitation while it maps smaller sub graphs to edgetpu. It fails to create a sub graph if any activation doesn't fit on the memory. In this case reshape ops could be too large to fit on memory. 

I tried to dig more into your model ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8 but the model is no longer available

**Comment by aviraljain99** [comment]
@Naveen-Dodda

I see, that makes sense. Do you know where I could read more about these details to understand the conversion process better (and to help me debug and understand when I run into issues in the future)? I also wasn't able to find documentation on what the '-a' flag does - could you point me to the right documentation? 

Also, sorry about that, here is another link to the model converted using post-training quantization: [Full Integer model](https://drive.google.com/file/d/15Ms_CQdHuAQ1RX771JKTRgyPbQsCf1Z4/view?usp=sharing)

Here is a link to a TFLite model converted without any post-training quantization: [Basic TFLite Model](https://drive.google.com/file/d/1-F-t7mXX-PdA-OGIkx2MTYYEc7PJjp9_/view?usp=sharing)

Please let me know if those aren't accessible.

**Comment by Naveen-Dodda** [comment]
@aviraljain99 

As this is still a experimental flag we haven't published a detailed documentation about it. I will take this feedback to the team about improving feature and adding more documentation about -a flag. 

Coming back; edgetpu_compiler fails to compile as it fails to allocate memory for Reshape ops (such as 1x38400x4 ) with large size.
![image](https://user-images.githubusercontent.com/44787761/117557333-8d409d80-b026-11eb-9b9e-5fd694918e61.png)


![ssd_fpnlite](https://user-images.githubusercontent.com/44787761/117557262-fa9ffe80-b025-11eb-94e0-403616983307.png)

**Comment by aviraljain99** [comment]
@Naveen-Dodda 

Okay thank you for the information. So the problem is that the EdgeTPU can't allocate enough space to store the output of the Reshape Ops right? That does make sense I think. Although, if that is the case, why doesn't it just make the operation run on the CPU? (Just a note, I am not very knowledgeable about MCUs or hardware in general)

I also had another question. I am also trying to make a ResNet model (ssd_resnet50_v1_fpn_640x640_coco17_tpu-8 downloaded from the [TF2 Detection Model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)) run on the EdgeTPU and in this case, regardless of whether or not I use the '-a' flag or not, the conversion process fails. I am assuming this is because the ResNet model is simply too big to run on the EdgeTPU? Here is the [TFLite model with post-training quantization](https://drive.google.com/file/d/1DlKT-7QjMeRa_18yeTBTB9UJxMCNWfNY/view?usp=sharing)
