### ISSUE TITLE
AttributeError: 'Delegate' object has no attribute '_library'

### ISSUE THREAD

**Issue by Sunkian** [google-coral/edgetpu#357]
Hello @Namburger, I've been trying to run inference on my Coral dev board's TPU but without success. I hope you can help me out on this. 

### Setup :
I'm using a Google Coral Dev Board running on Mendel. The command ```uname -a``` gave me this :
```Linux fun-orange 4.14.98-imx #1 SMP PREEMPT Fri Nov 8 23:28:21 UTC 2019 aarch64 GNU/Linux```.
The model used is a facemask detection compiled for edgetpu that I found there : https://neuralet.com/article/a-practical-solution-to-real-world-face-mask-detection-part-2/#Face_mask_detection_on_edge (Section "Mask / no mask classifier")
I also tried this one : https://github.com/neuralet/models/tree/master/edge-tpu/face_mask_ssd_mobilenet_v1
If I understand correctly, both models are quantized with the edgetpu compiler. </br>
I also ran those :

- ```dpkg -l | grep libedgetpu``` : ```ii  libedgetpu1-std:arm64                15.0                        arm64        Support library for Edge TPU``` 

- ```python3 -c 'print(__import__("tflite_runtime").__version__)' ``` : ```2.5.0```
- ```python3 -c 'print(__import__("tflite_runtime").__git_version__)'``` : ```48c3bae94a8b324525b45f157d638dfd4e8c3be1```
- ```cat /etc/os-release``` : ```PRETTY_NAME="Mendel GNU/Linux 4 (Day)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.withgoogle.com/"
SUPPORT_URL="https://coral.withgoogle.com/"
BUG_REPORT_URL="https://coral.withgoogle.com/"
VERSION_CODENAME="day"```

### Code :
A part of my code looks like that : 
```
import tflite_runtime.interpreter as tflite

classes = ['got mask', 'no mask']
path = 'OFMClassifier_edgetpu.tflite'

interpreter = tflite.Interpreter(model_path=path, experimental_delegates=[tflite.load_delegate('libedgetpu.so.1')])
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
```
### Error :
I'm trying to compile my code thanks to a docker image. I'm getting this error : 
```
Traceback (most recent call last):
  File "main.py", line 274, in <module>
    detect(source, output, mqtt_address, mqtt_topic)
  File "main.py", line 179, in detect
    interpreter = tflite.Interpreter(model_path='OFMClassifier_edgetpu.tflite', experimental_delegates=[tflite.load_delegate('libedgetpu.so.1')]
  File "/usr/local/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 81, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libedgetpu.so.1: cannot open shared object file: No such file or directory
Exception ignored in: <function Delegate.__del__ at 0xffff8b103670>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 116, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'
FATAL: exception not rethrown
Aborted (core dumped)
```

Would you have an idea what is causing that ? Thanks a lot in advance !

**Comment by manoj7410** [comment]
@Sunkian First of all, it is recommended to install the latest version of the Mendel on your Dev board. You can reflash the board by following the instructions given at : https://coral.ai/docs/dev-board/reflash/#flash-a-new-system-image

**Comment by Sunkian** [comment]
Following your advice @manoj7410, I reflashed my board and I'm on this version now : 
```
$ cat /etc/os-release
PRETTY_NAME="Mendel GNU/Linux 5 (Eagle)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.ai/"
SUPPORT_URL="https://coral.ai/"
BUG_REPORT_URL="https://coral.ai/"
VERSION_CODENAME="eagle"
```

But I'm still getting my error. If I remove ```experimental_delegates=[tflite.load_delegate('libedgetpu.so.1```, and change the model to a non quantized .tflite one, everything works fine but on the CPU (turning at 1.3 fps). I got the quantized models on the official page https://github.com/neuralet/models/tree/master/edge-tpu/face_mask_ssd_mobilenet_v1 so I have no idea what is the issue.

**Comment by mbrooksx** [comment]
Are you able to run our default models (i.e. edgetpu_detect)? 

Can you verify:
```
sudo apt show python3-tflite-runtime
sudo dmesg | grep -iE 'apex|gasket|pcie'
```

**Comment by manoj7410** [comment]
@Sunkian Are you still facing this issue ?

**Comment by manoj7410** [comment]
Feel free to reopen this thread if the issue still persists.
