### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by marcin-kamionowski** [google-coral/edgetpu#358]
Hi!
```
$ edgetpu_compiler internal_err.tflite 
Edge TPU Compiler version 15.0.340273435

Internal compiler error. Aborting! 
```
[internal_err.zip](https://github.com/google-coral/edgetpu/files/6297562/internal_err.zip)
The same problem is present on compiler v14.1
On 2.1 i get: `Didn't find op for builtin opcode 'TRANSPOSE_CONV' version '3'`

**Comment by marcin-kamionowski** [comment]
Stdout is confusing when min runtime version is selected:
```
$ edgetpu_compiler internal_err.tflite -m 11
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 17 ms.

Input model: internal_err.tflite
Input size: 961.05KiB
Output model: internal_err_edgetpu.tflite
Output size: 882.13KiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 0
Total number of operations: 69
Operation log: internal_err_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 0
Number of operations that will run on CPU: 69
See the operation log file for individual operation details.
```
Status code is zero in this case. Output file has been created but it is invalid.

**Comment by mbrooksx** [comment]
Hi @marcin-kamionowski,

Can you provide the model that you're running (if you're uncomfortable on a public forum, please email to coral-support@google.com)?

Thanks!

**Comment by marcin-kamionowski** [comment]
Hi @mbrooksx 
Model is linked in the first comment. This is the link: https://github.com/google-coral/edgetpu/files/6297562/internal_err.zip
Thanks!

**Comment by Naveen-Dodda** [comment]
Hello Marcin, 

May I know which version of tensorflow you have used to train and quantize the model ?

**Comment by Naveen-Dodda** [comment]
Hello Marcin, 

Current version of compiler 15.0 does n't support 'TRANSPOSE_CONV' version '3'. But this support will be added in our next release. For now if you are still interested in using this ops you can train and convert the with TF1.x.

To answer this edgetpu_compiler internal_err.tflite -m 11
The output model of the compiler will completely run on cpu as you can see Number of Edge TPU subgraphs: 0. 

Let me know if you need any more help.
