### ISSUE TITLE
Jitter on UART with baurate >115200

### ISSUE THREAD

**Issue by kmr29499** [google-coral/edgetpu#360]
Hi, we have an issue using the UART1 & 3 as interface with SLCAN.
We're running the interfaces with 230400 kBaud and observed bits falling over, which leads to wrong data - in terms of SLCAN either wrong/short/long address or corrupted payload. When having traffic in both directions we can also see that transmitting gets stuck sooner or later.
It's easy to reproduce the behavior by just connecting TX UART1 (or TX UART3), connect to a receiver and measure the signal with a scope.

We simply set the baudrate and start sending in an endless loop:
```
$> sudo stty 230400 -F /dev/ttymxc0
$> sudo bash test_tty.sh
```

```
#!/bin/bash
while true
do
    echo "longttest" > /dev/ttymxc0
    sleep 0.1
done
```
[test_tty.zip](https://github.com/google-coral/edgetpu/files/6311597/test_tty.zip)

Signal with 115200 baud:
<img width="948" alt="coral_tx_output_default_dtb_115200" src="https://user-images.githubusercontent.com/51815636/114732206-9f3e6180-9d42-11eb-93e5-291121f7613a.png">

Signal with 230400 baud:
<img width="844" alt="coral_tx_output_default_dtb_230400" src="https://user-images.githubusercontent.com/51815636/114732386-c137e400-9d42-11eb-96de-56a095a99785.png">

Why is `busfreq` set to `disabled` in `fsl-imx8mq-phanbell.dts` whereas it is set to `okay` in the original NXP sources?
```
busfreq {                                                                                            
    status = "disabled";                                                                         
};
```

One more thing:
Enabling the `busfreq` leads to Linux hang during boot.

Screenshot scope
[coral_tx_problem.zip](https://github.com/google-coral/edgetpu/files/6311683/coral_tx_problem.zip)

**Comment by kmr29499** [comment]
Does anybody from Google care about these issues?

**Comment by mbrooksx** [comment]
Note this is purely a iMX8M question and will likely be better understood on a NXP forum. There are likely issues with baud rate generation of this value. With an input clock of 25 MHz to UART1:

```
mendel@tuned-rabbit:~$ sudo cat /sys/kernel/debug/clk/uart1/clk_rate
25000000
```

It is unclear that you'll be able to generate exactly 230400. You can read the baud rate values as described in the iMX reference manual.


As for the questions regarding busfreq, busfreq is disabled in the Mendel kernel deliberately. You can use busfreq by following the steps in this [app note](https://github.com/mbrooksx/draft-coral-appnotes/blob/main/PowerSavings.pdf). Note that disabling busfreq as is done in our code ensure the bus frequency never deviates from max so it is unlikely to cause clocking issues for the UART.
