### ISSUE TITLE
python3-pycoral doesn't install on Ubuntu 16.04

### ISSUE THREAD

**Issue by wb666greene** [google-coral/edgetpu#362]
Ubuntu 16.04 with all current updates as of last night. It had been running edgetpu-1.9.2

I ran the edgetpu_api/unistall.sh and started the PyCoral installation, which I have done successfully on Ubuntu 20.04.   I didn't the gasket,apex blacklist and /dev/apex_0 exists after the dkms build and system reboot.  Wasn't expecting problems but ...
`sudo apt-get install python3-pycoral
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-pycoral : Depends: python3-tflite-runtime (= 2.5.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`
Trying to install tflite:
`sudo apt install python3-tflite-runtime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-tflite-runtime : Depends: python3-numpy (>= 1:1.12.1) but 1:1.11.0-1ubuntu1 is to be installed
                          Depends: libstdc++6 (>= 6) but 5.4.0-6ubuntu1~16.04.12 is to be installed
E: Unable to correct problems, you have held broken packages.`

numpy-1.16.4 has been pip installed on this system.

In /usr/lib/x86_64-linux-gnu is libstdc++.so.6.0.21

Is something wrong with the pycoral dependencies for 16.04?

I've got newer 16.04 systems running using the  "legacy" python-edgetpu package, but I'm not at their location right now.   I can try again eventually, in case it was the old (pre repo) *.gz installations of OpenVINO or edgetpu_api that has messed up the apt install on this system.

For now, is there a pip install way of getting pycoral? I naievely tried pip3 install pycoral but it didn't find anything.

**Comment by Namburger** [comment]
@wb666greene you can try the package from here: https://github.com/google-coral/pycoral/releases

**Comment by wb666greene** [comment]
@Namburger Thanks, I sudo -H pip3 installed pycoral and tflite and I'm close but this step fails:

from pycoral.utils.edgetpu import make_interpreter, get_runtime_version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pycoral/utils/edgetpu.py", line 24, in <module>
    from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
ImportError: libedgetpu.so.1: cannot open shared object file: No such file or directory

These prior steps succeeded:
        from pycoral.adapters import common, detect
        from pycoral.utils.dataset import read_label_file

My reason for the update on this system is to use the MPCIe TPU module.

I then used synaptic to install libedgetpu1-max even though libedgetpu1-std appeared to be installed along with libedgetpu-dev,  after this it worked.  Seems to be some fragility in the installation instructions.

I'll follow-up as I eventually update my other systems if I encounter issues.  Obviously the apt install method is preferred, most are 16.04, but I think one is 18.04 and one other is 20.04.

**Comment by Namburger** [comment]
@wb666greene yes, the `apt install python3-pycoral` is a new thing that coral added recently, I guess what it allows is a one step install that includes all necessary libraries. However that failed for you (maybe because the OS is too old?) so I suggested installing the pip package instead and that pip package doesn't include the `so` => you needed an extra step to install the so.
I'm no longer with Coral team, btw, but I last remember that we're not really thinking about supporting older OS any more in the long run due to things like glibc incompatibilities. 

Maybe @dmitriykovalev and @scottamain can give more info here!

**Comment by wb666greene** [comment]
The getting started for the M.2 etc. modul page says under "Requirements":

A computer with one of the following operating systems:
Linux: 64-bit version of Debian 10 or Ubuntu 16.04 (or newer), and an x86-64 or ARMv8 system architecture
Windows: 64-bit version of Windows 10, and x86-64 system architecture
All systems require support for MSI-X as defined in the PCI 3.0 specification
At least one available Mini PCIe or M.2 module slot
Python 3.5-3.8

I'm willing to accept that having previously done *.tar.ga installs of edgetpu_api and OpenVINO may have messed something up, but then that probably means the edgetpu_api/uninstall.sh script didn't work right.

As I said its working fine since I installed libedgetpu1-max, but I've no explanation as to why it couldn't find libedgetpu1.so when libedgetpu1-std  was installed.  Maybe libedgetpu-dev was also a requirement.

I will be updating other systems eventually, but initially the instructions for Ubuntu 20.04 worked fine,  Windows 10 seems to have installed but the MPCIe driver doesn't start (see issue #361 although USB3 TPU works), and Ubuntu 16.04 worked after the pip installation of pycoral & tflite and the apt install of libedgetpu1-max & libedgetpu-dev.

One thing I notice is than using make_interpreter() with device="pci" starts up (loads the model?) much faster than using device="usb"

One fine print question, if both MPCIe and TPU devices are plugged in and I use device None, which will be used? of is it system dependent?   On this particular system, based on the quick start-up, it looks to be defaulting to using the MPCIe device if one is not specified in make_interpreter().

**Comment by wb666greene** [comment]
I repeated the pycoral installation instructions from here:  https://coral.ai/docs/m2/get-started/ on another Ubuntu 16.02 system that was running the 192*.tar.gz version of edgetpu_api.

This time I did:
sudo ./edgetpu_api/uninstall.sh
sudo apt update
sudo apt upgrade

There were a lot of 16.04 updates as it'd been running in "if it ain't broke, don't fix it" mode since early 2019 and doesn't accept any outside connections.

I then followed the instructions and everything went great until:
sudo apt-get install python3-pycoral

which failed as before:
`The following packages have unmet dependencies:
 python3-pycoral : Depends: python3-tflite-runtime (= 2.5.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

So there is something wrong with the Ubuntu 16.04 dependencies, the getting started page says 16.04 is "supported".

Next I did  pip3 install tflite -runtime & pycoral for the "wheels" downloaded from: https://github.com/google-coral/pycoral/releases:

sudo -H pip3 install tflite_runtime-2.5.0-cp35-cp35m-linux_x86_64.whl pycoral-1.0.1-cp35-cp35m-linux_x86_64.whl

After this the USP3 TPU edgetpu_api code that I ported to pycoral worked perfectly on the MPCIe module.

I think you just need to update the last installation step for 16.04 to install the "wheels" instead of using the apt-get install of python3-pycoral, or fix the 16.04 dependencies.

I think we can close this, but I'd appreciate if whoever was "assigned" it could look at issue #361 for why the MPCI driver doesn't start on Windows 10.  I need a lot more help with Windows issues than I do with Linux.

**Comment by Zetto12** [comment]
> Next I did pip3 install tflite -runtime & pycoral for the "wheels" downloaded from: https://github.com/google-coral/pycoral/releases:
> 
> sudo -H pip3 install tflite_runtime-2.5.0-cp35-cp35m-linux_x86_64.whl pycoral-1.0.1-cp35-cp35m-linux_x86_64.whl
> 
> After this the USP3 TPU edgetpu_api code that I ported to pycoral worked perfectly on the MPCIe module.

What exactly did you do here? I have the exact same problem and am kind of stuck
