### ISSUE TITLE
Failed to load delegate from libedgetpu.1.dylib

### ISSUE THREAD

**Issue by tyouritsugun** [google-coral/edgetpu#364]
Hi,

I stuck on a problem with the Coral Dev Board, here are my steps:
1, I finished the installation described in 
https://coral.ai/docs/dev-board/get-started/
2, I installed the run-time as below into my Mac with 10.15 :
https://coral.ai/software/#edgetpu-runtime
3, I installed the PyCoral as below into my Mac:
https://coral.ai/software/#pycoral-api
4, I have my Mac connected to the Coral Dev Board with a USB3 cable. 
5, I tried to run the script below, as I expected that the inference process in TPU will be triggered from Mac :
https://coral.ai/docs/edgetpu/tflite-python/#inferencing-example
I copied the necessary files such as .tflite, the parrot.jpeg, and imagenet_labels.txt to the Python script directory. But, Python complained that:
`ValueError: Failed to load delegate from libedgetpu.1.dylib`
I suspect that libedgetpu.1.dylib might not be installed correctly, so I ran
`otool -L /usr/local/lib/libedgetpu.1.dylib`
but the output of the command below seems right
```
/usr/local/lib/libedgetpu.1.dylib:
	@rpath/libedgetpu.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/opt/local/lib/libusb-1.0.0.dylib (compatibility version 3.0.0, current version 3.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1677.104.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
```
Am I missing something? Thank you in advance!

**Comment by manoj7410** [comment]
@tyouritsugun Can you share the detailed logs here including the command that you executed ?
Also, wanted to confirm that you are trying to perform the inference on the Dev Board and not on your Mac?

**Comment by tyouritsugun** [comment]
Thank you very much for your reply.
Here are parts of the run time installation message:
```
Would you like to enable the maximum operating frequency for your Coral USB device? Y/N
y
Using the maximum operating frequency for Coral USB devices.
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

Warning: libusb 1.0.24 is already installed and up-to-date.
To reinstall 1.0.24, run:
  brew reinstall libusb
Installing Edge TPU runtime library [/usr/local/lib]...
Installing Edge TPU runtime library symlink [/usr/local/lib]...
```
I ran
```
python3 -c "from ctypes.util import find_library; print(find_library(\"edgetpu\"))"
```
It replied `None`
I ran
```
ls /dev/cu.usbmodem*
```
It replied `/dev/cu.usbmodemzippy_apple1`
I wondered that the reason might be the device can not be found, but I do not know how to fix it.

Yes, I am trying to perform the inference on the Dev Board but not on my Mac. I expected that the Python script from Mac will call the inference in TPU via libedgetpu.1.dylib, am I misunderstanding the architecture?

**Comment by tyouritsugun** [comment]
**UPDATE**

I am still working on this problem, here is what I met.

1, I ran ctypes.pydll.LoadLibrary to load 'libedgetpu.1.0.dylib' from Python console, it says 
``` shell
>>> import ctypes
>>> print(ctypes.pydll.LoadLibrary('libedgetpu.1.0.dylib'))
<PyDLL 'libedgetpu.1.0.dylib', handle 7fa815e11480 at 0x108604490>
>>> print(ctypes.pydll.LoadLibrary('libedgetpu.1.dylib'))
<PyDLL 'libedgetpu.1.dylib', handle 7fa8179044e0 at 0x1086044d0>
```
From this message, I guess that the run-time should be installed correctly. 

2, I traced into the Python source, 'self._delegate_ptr' got angry because at 'interpreter.py', line 108:
```shell
    self._delegate_ptr = self._library.tflite_plugin_create_delegate(
        options_keys, options_values, len(options), error_capturer_cb)
    if self._delegate_ptr is None:
      raise ValueError(capture.message)
```
it got None from 'tflite_plugin_create_delegate', which be considered as an abnormality.

Hope that information can help you shoot my trouble quickly.

**Comment by Namburger** [comment]
@tyouritsugun just wanted some clarifications, are you using a USB Accelerator or a Coral Dev Board? 

If you are using a Coral Dev Board, you’ll need to run code on the board, not on your Mac since the tpu only exists on the board.

Installing the libedgepu dylib means that you are trying to run coral’s libraries which requires the edgetpu on the MAC itself, which means you need to have a USB Accelerator installed on it.

**Comment by Namburger** [comment]
Ahh, just saw this:
> Yes, I am trying to perform the inference on the Dev Board but not on my Mac. I expected that the Python script from Mac will call the inference in TPU via libedgetpu.1.dylib, am I misunderstanding the architecture?

In this case, what you should do instead is log into your board using our mdt tool or ssh, the board comes with an OS on it that allows you to log into it and run code!

Here are the instructions that you can follow: https://coral.ai/docs/dev-board/get-started/#connect-internet

**Comment by tyouritsugun** [comment]
Thank you, Namburger!

Now, I understand that I can not expect the Dev Board to work like that. It is necessary for the host computer to see the TPU as its own device, but Mac can not do that with the Dev Board. So I need a USB one. 

However, is it possible for Ubuntu to see the Dev Board as its device? I read the document below, 
https://coral.ai/docs/dev-board/mdt/#mdt-on-macos

It says that
```
Beginning with macOS Catalina (10.15), you cannot create an MDT (or other SSH) connection over USB. 
```
Is this a strong hint that Ubuntu can create a connection over USB with the Dev Board as long as I connect the Dev Board with a USB cord, then the Dev Board will be on Ubuntu's USB device list? For my situation, I guess that instead of the USB Accelerator, I prefer to buy a PC for Ubuntu to continue my research work, because I need to debug a lot on the reference board nearly the same architecture as the commercialized version board.
The other option might be, Raspberry Pi + USB Accelerator. Although it is not the same as the commercialized architecture,  I can debug on my PC and then launch my program in the Raspberry Pi.

In practice as your experience, what will be better, Mac+USB Accelerator, Ubuntu+Dev Board, or Mac+ Raspberry Pi+USB Accelerator?

**Comment by Namburger** [comment]
@tyouritsugun 
Even with Ubuntu, you’ll still have to connect to the board (although usb interface is unlocked meaning you don’t need networks).

On MAC you can actually still ssh to the board via wifi instead of usb (as long as both devices are in the same network). 
You can see here for a reference:
https://www.linkedin.com/pulse/tips-connecting-google-coral-edge-tpu-dev-board-macos-arthur

**Comment by tyouritsugun** [comment]
Thank you!
I connected to my MAC via wifi successfully, yet I will try to use Ubuntu to connect to my Dev Board to see if I can call the inference from U Ubuntu to the board because I am searching for a way to let the host PC can consider the Dev Board as one of its devices, such as the TPU inference can be triggered from the host PC. Alternatively, the USB Accelerator might be better since it is much cheaper than a host PC.
