### ISSUE TITLE
When using tf.keras.layers.Cropping2D or tf.slice, my Edge TPU Compiler shows: Internal compiler error. Aborting!

### ISSUE THREAD

**Issue by WKMan** [google-coral/edgetpu#365]
I am building two U Net Models for running on a Coral Dev. Board.

model A dose not use tf.keras.layers.Cropping2D layer and it compiled by Edge Tpu Compiler successfully and works fine on Coral Dev. Board.

The other model B used tf.keras.layers.Cropping2D but can not be compiled and only show the message: Internal compiler error. Aborting!

I tried to replace tf.keras.layers.Cropping2D with tf.slice but it still shows the same error message.

During .h5 to .tflite quantization in uint8 on pc,  model B is fine and dose not show any error message. That .tflite also can inference test data on PC.

My Platform info. is:

Tensorflow 2.3
Models code are build by tf.keras....
Edge Tpu Compiler version: 15.0.340273435

Here is my quantization code:

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = False
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_quant_model = converter.convert()

So the reason for my problems is that Coral TPU dose not support tf.keras.layers.Cropping2D or tf.slice?  or any other reason ?

How can I use tf.keras.layers.Cropping2D function like on Coral ?

Thanks for your help!

**Comment by Naveen-Dodda** [comment]
@WKMan 

Tf.slice is supported on edgetpu, To debug the issue further can you share .h5 and tflite versions of Model B ?

**Comment by hjonnala** [comment]
@WKMan are you able to compile the model?

**Comment by hjonnala** [comment]
@WKMan To debug the issue further can you share .h5 and tflite versions of Model B ?

**Comment by hjonnala** [comment]
Closing this for now due to inactivity.
