### ISSUE TITLE
Unable to flash Coral dev board

### ISSUE THREAD

**Issue by shaunmitchellve** [google-coral/edgetpu#368]
Hello,

I've been trying to re-flash my Coral.ai dev board (4GB) using the microSD card and  / or fastboot (bash flash.sh -H) methods. I've tried an older microSD card and even bought a brand new Samsung 128 GB card (as I've seen a previously reported issue like this and a new SSD card seemed to solve it). Both times I get stuck in an endless loop of booting. I then tried the fast boot using USB method and get the exact same issues.

I have been successful in the past with flashing the card but wanted to update to the latest build (enterprise-eagle-20210204152958).

The last few lines of the boot cycle are:

```
Normal Boot
Trying to boot from MMC1
hdr read sector 300, count=1


U-Boot 2019.04.1 (Jan 11 2021 - 20:43:00 +0000), Build: jenkins-enterprise.uboot-imx-1

CPU:   Freescale i.MX8MQ rev2.1 1500 MHz (running at 1000 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 34C
Reset cause: POR
Model: Freescale i.MX8MQ Phanbell
DRAM:  4 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... *** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial

 BuildInfo:
  - ATF
  - U-Boot 2019.04.1

flash target is MMC:0
Net:
Warning: ethernet@30be0000 using MAC address from ROM
eth0: ethernet@30be0000
Fastboot: Normal
Normal Boot
```

After this, the boot cycle goes to "Hit any key to stop autoboot:". This just continues endlessly.

**Comment by shaunmitchellve** [comment]
I've been able to get rid of the *** Warning - bad CRC, using default environment by interrupting the boot loop and saving the current u-boot working environment to disk by running:

```
saveenv
reset
```

Still stuck i the endless boot loop however. I think the CRC error is a red herring.

I'm not sure if there is relevance here but I noticed that the message states that it is trying to boot from MMC 1 which is the flash card when I do an MMC list:

```
FSL_SDHC: 0 (eMMC)
FSL_SDHC: 1
```
The eMMC switches are set to ON OFF OFF OFF (or Up Down Down Down)

printenv on  U-Boot shows that the bootcmd is set to

`ext2load mmc 0:1 ${loadaddr} boot.scr; source; boota mmc0 boot_a`

which is what made me look at the boot from MMC1 in the logs

OTHER NOTE:

The only error I see is when the boot first starts:

`## Error: "m4enabled" not defined`

**Comment by hjonnala** [comment]
@shaunmitchellve sorry for the delay, are you still facing the issue? if yes, please try to flash the board using SD card. 

Reference: https://coral.ai/docs/dev-board/get-started/#flash-the-board

**Comment by shaunmitchellve** [comment]
@hjonnala I am still facing this issue, I have yet to get past the booting loop.

I've tried to re-flash the board using the SD card method and the latest download enterprise-eagle-flashcard-20210518200035.

Once switching the eMMC switches back to ON OFF OFF OFF, the dev board continues to loop exactly as described in initial issue.

**Comment by hjonnala** [comment]
Can you please confirm the below steps

1. The board is fully unplugged
2. Inserted the SD card
3. eMMC switches are ON OFF ON ON 
4. Only USB-C power cable is attached to the board
3. Unplug the power only after  board shuts down and the red LED turns off.
4. Unplugged the power and removed sd card
5. Changed the switches back  ON OFF OFF OFF

**Comment by shaunmitchellve** [comment]
Yes, I can confirm that is the exact process I undertook. I just re-did it to make 100% sure and I left the serial port unplugged this time on first boot.

Now  the board fan kicks in (I assume during boot up process) but then it stops, the red power lights turns off for a split second and then everything start agains (fan spins up).

**Comment by manoj7410** [comment]
@shaunmitchellve What is the power source that you are using to boot the board ?

**Comment by shaunmitchellve** [comment]
@manoj7410 Good call out! I was using a phone charger that was providing  5V 2.5Amps. I switched over to a larger block that is providing 5V 3Amps and re-flashed the board.

That has seemed to resolve the boot cycle issue.

**Comment by miniman** [comment]
The last comment implies the current requirements are pretty stringent, and I will second that assertion. I have a USB-C block with three ports and provides "only" 5 amps. I cannot have three (e.g., 1 - 1GB DevBoard, 2 - 4GB DevBoard) running and successfully flash using the micro-SD card. I have to unplug at least one of the other DevBoards for the SD card flash to succeed and not receive the dreaded `Wrong image format for "source" command` error. Maybe more telling is the bad CRC prior to that error message. None the less, I can reliably flash a board with only two plugged into a 5A source.
