### ISSUE TITLE
Error 10049 using MDT on Windows 10

### ISSUE THREAD

**Issue by Gerfindel** [google-coral/edgetpu#370]
Hello,

I am trying to use a Coral Dev Board, so I followed the beginner tutorial : [https://coral.ai/docs/dev-board/get-started/](https://coral.ai/docs/dev-board/get-started/)

I am using Windows 10, I did all the steps until the part 4 without any problem, but when I try to use the `mdt devices` command, I always get a WinError 10049, here the output : 

```Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.254
4.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.254
4.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gerfindel\AppData\Local\Packages\PythonSoftwareFoundation.Pytho
n.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\mdt.exe\__main__.
py", line 7, in <module>
  File "C:\Users\Gerfindel\AppData\Local\Packages\PythonSoftwareFoundation.Pytho
n.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mdt\main.py
", line 162, in main
    exit(command.run(sys.argv[1:]))
  File "C:\Users\Gerfindel\AppData\Local\Packages\PythonSoftwareFoundation.Pytho
n.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mdt\devices
.py", line 43, in run
    self.discoverer.discover()
  File "C:\Users\Gerfindel\AppData\Local\Packages\PythonSoftwareFoundation.Pytho
n.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mdt\discove
rer.py", line 40, in discover
    self.zeroconf = Zeroconf()
  File "C:\Users\Gerfindel\AppData\Local\Packages\PythonSoftwareFoundation.Pytho
n.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zeroconf\__
init__.py", line 2508, in __init__
    self._listen_socket, self._respond_sockets = create_sockets(
  File "C:\Users\Gerfindel\AppData\Local\Packages\PythonSoftwareFoundation.Pytho
n.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zeroconf\__
init__.py", line 2343, in create_sockets
    respond_socket = new_respond_socket(i, apple_p2p=apple_p2p)
  File "C:\Users\Gerfindel\AppData\Local\Packages\PythonSoftwareFoundation.Pytho
n.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zeroconf\__
init__.py", line 2302, in new_respond_socket
    respond_socket = new_socket(
  File "C:\Users\Gerfindel\AppData\Local\Packages\PythonSoftwareFoundation.Pytho
n.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zeroconf\__
init__.py", line 2250, in new_socket
    s.bind((bind_addr[0], port, *bind_addr[1:]))
OSError: [WinError 10049] The requested address is not valid in its context
```

It occurs whether the Dev Board is plugged or not, and also the `mdt shell` command leads to the same error.

I looked for solutions on internet but I couldn't find any, so I don't know how to solve this. Maybe I just did something wrong but for the moment I don't see what (and actually I did the same tutorial on another computer with Windows 10 and got the same errors).
Does anyone have an idea on how to solve this? Thank you in advance!

**Comment by manoj7410** [comment]
@Gerfindel Is this issue still reproducible ?

**Comment by hjonnala** [comment]
@Gerfindel please try to Connect to the Dev Board's serial console

Please follow these steps:
1. download windows drivers from this link https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers for Silicon Labs Dual CP2105 USB to UART Bridge
2. follow these instruction https://coral.ai/docs/dev-board/serial-console/#connect-with-windows
3. once you login with putty try this nmcli dev wifi connect <NETWORK_NAME> password <PASSWORD> ifname wlan0
4. verify you are able to connect : nmcli connection show
5. run these commands. https://coral.ai/docs/dev-board/get-started/#run-pycoral

**Comment by hjonnala** [comment]
closing the issue due to inactivity. Fell free to open id issue still exist.
