### ISSUE TITLE
docker build failed, when was trying to rerun the benchmark tests

### ISSUE THREAD

**Issue by ernielikesapple** [google-coral/edgetpu#372]
Hi Dear Developers
I git clone https://github.com/google-coral/edgetpu this repo to my local 
I was trying to reproduce the benchmark test result on my Linux (WSL), inside https://coral.ai/docs/edgetpu/benchmarks/

under the "/edgetpu" directory I was running the in the read me,

"make DOCKER_IMAGE=debian:buster DOCKER_CPUS="k8 armv7a aarch64" DOCKER_TARGETS=tests docker-build"
"make DOCKER_IMAGE=ubuntu:18.04  DOCKER_CPUS="k8 armv7a aarch64" DOCKER_TARGETS=tests docker-build"

I switched the DOCKER_TARGETS to benchmarks,

then I got this error:

 make DOCKER_IMAGE=debian:buster DOCKER_CPUS="k8 armv7a aarch64" DOCKER_TARGETS=benchmarks docker-build

docker build  -t "coral-edgetpu-debian-buster" \
    --build-arg IMAGE=debian:buster /mnt/c/Users/ernie.cheng/Desktop/distech/mobilnet/edgeTpuCore3/edgetpu/docker
[+] Building 6.3s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                       0.0s
 => => transferring dockerfile: 38B                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/debian:buster                                                                                                           6.1s
 => [internal] load build context                                                                                                                                          0.0s
 => => transferring context: 39B                                                                                                                                           0.0s
 => [1/8] FROM docker.io/library/debian:buster@sha256:ba4a437377a0c450ac9bb634c3754a17b1f814ce6fa3157c0dc9eef431b29d1f                                                     0.0s
 => CACHED [2/8] COPY update_sources.sh /                                                                                                                                  0.0s
 => CACHED [3/8] RUN /update_sources.sh                                                                                                                                    0.0s
 => CACHED [4/8] RUN dpkg --add-architecture armhf                                                                                                                         0.0s
 => CACHED [5/8] RUN dpkg --add-architecture arm64                                                                                                                         0.0s
 => CACHED [6/8] RUN apt-get update     && DEBIAN_FRONTEND=noninteractive apt-get install -y       libc6-dev:arm64       libc6-dev:armhf     && DEBIAN_FRONTEND=nonintera  0.0s
 => CACHED [7/8] RUN git clone https://github.com/raspberrypi/tools.git &&     cd tools &&     git reset --hard 4a335520900ce55e251ac4f420f52bf0b2ab6b1f                   0.0s
 => CACHED [8/8] RUN wget -O /bazel https://github.com/bazelbuild/bazel/releases/download/2.1.0/bazel-2.1.0-installer-linux-x86_64.sh &&     bash /bazel &&     rm -f /ba  0.0s
 => exporting to image                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                    0.0s
 => => writing image sha256:99c99ff4e82b1055dd086f0689a0be1a11ba229f8dcf52b43237c94c68f62c66                                                                               0.0s
 => => naming to docker.io/library/coral-edgetpu-debian-buster                                                                                                             0.0s
docker run --rm -i --tty -v /mnt/c/Users/ernie.cheng/Desktop/distech/mobilnet/edgeTpuCore3/edgetpu:/workspace \
    "coral-edgetpu-debian-buster" /bin/bash -c "chmod a+w /; groupadd --gid 1000 ernie; useradd -m -e '' -s /bin/bash --gid 1000 --uid 1000 ernie; echo 'ernie ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers; su ernie -c 'for cpu in k8 armv7a aarch64; do make CPU=\${cpu} -C /workspace benchmarks || exit 1; done'"
make: Entering directory '/workspace'
make: *** No rule to make target 'benchmarks'.  Stop.
make: Leaving directory '/workspace'
make: *** [/mnt/c/Users/ernie.cheng/Desktop/mobilnet/edgeTpuCore3/edgetpu/docker/docker.mk:38: docker-build] Error 1

I also tried switch the dockerTarget back to tests, still the same error,

" make: *** No rule to make target 'tests'.  Stop."

I would like to know why, can someone help, thanks endlessly!!!

**Comment by mbrooksx** [comment]
Hello @ernielikesapple ,

Is there a particular reason you want to use edgetpu? This repo is deprecated (although I still would expect it to work. It has been replaced with [libcoral](https://github.com/google-coral/libcoral) for C++ or [pycoral](https://github.com/google-coral/pycoral) for Python.

**Comment by ernielikesapple** [comment]
> Hello @ernielikesapple ,
> 
> Is there a particular reason you want to use edgetpu? This repo is deprecated (although I still would expect it to work. It has been replaced with [libcoral](https://github.com/google-coral/libcoral) for C++ or [pycoral](https://github.com/google-coral/pycoral) for Python.


Hi @mbrooksx   I  was trying to reproduce the results under https://coral.ai/docs/edgetpu/benchmarks/ for Mobilnetssdv2
so even if with https://github.com/google-coral/libcoral

after I clone the project and cd to libcoral folder, I run
"make DOCKER_IMAGE=debian:buster DOCKER_CPUS="k8 armv7a aarch64" DOCKER_TARGETS=tests docker-build
" from read me

I got the same error


[+] Building 0.5s (16/16) FINISHED
 => [internal] load build definition from Dockerfile                                                                                      0.0s
 => => transferring dockerfile: 38B                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                         0.0s
 => => transferring context: 2B                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/debian:buster                                                                          0.4s
 => [internal] load build context                                                                                                         0.0s
 => => transferring context: 39B                                                                                                          0.0s
 => [ 1/11] FROM docker.io/library/debian:buster@sha256:ba4a437377a0c450ac9bb634c3754a17b1f814ce6fa3157c0dc9eef431b29d1f                  0.0s
 => CACHED [ 2/11] COPY update_sources.sh /                                                                                               0.0s
 => CACHED [ 3/11] RUN /update_sources.sh                                                                                                 0.0s
 => CACHED [ 4/11] RUN dpkg --add-architecture armhf                                                                                      0.0s
 => CACHED [ 5/11] RUN dpkg --add-architecture arm64                                                                                      0.0s
 => CACHED [ 6/11] RUN echo 'APT::Immediate-Configure false;' >> /etc/apt/apt.conf                                                        0.0s
 => CACHED [ 7/11] RUN apt-get update     && DEBIAN_FRONTEND=noninteractive apt-get install -y       libc6-dev:arm64       libc6-dev:arm  0.0s
 => CACHED [ 8/11] RUN mkdir /debs && chmod 0777 /debs && cd /debs && apt-get update && apt-get download   libglib2.0-0   libglib2.0-0:a  0.0s
 => CACHED [ 9/11] RUN for d in /debs/*.deb; do dpkg -x $d /usr/system_libs; done                                                         0.0s
 => CACHED [10/11] RUN git clone https://github.com/raspberrypi/tools.git &&     cd tools &&     git reset --hard 4a335520900ce55e251ac4  0.0s
 => CACHED [11/11] RUN wget -O /bazel https://github.com/bazelbuild/bazel/releases/download/3.2.0/bazel-3.2.0-installer-linux-x86_64.sh   0.0s
 => exporting to image                                                                                                                    0.0s
 => => exporting layers                                                                                                                   0.0s
 => => writing image sha256:d7d7ddff7f7a7f4a803ef81a3d5c05355d910bfce6535e17d8664b05a37070df                                              0.0s
 => => naming to docker.io/library/coral-edgetpu-debian-buster                                                                            0.0s
docker run --rm -i --tty -v /mnt/c/Users/ernie.cheng/Desktop/distech/mobilnet/edgeTpuCore1/libcoral/:/workspace \
    "coral-edgetpu-debian-buster" /bin/bash -c "chmod a+w /; groupadd --gid 1000 ernie; useradd -m -e '' -s /bin/bash --gid 1000 --uid 1000 ernie; echo 'ernie ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers; su ernie -c 'for cpu in k8 armv7a aarch64; do make CPU=\${cpu} COMPILATION_MODE=opt -C /workspace/ tests || exit 1; done'"
make: Entering directory '/workspace'
make: *** No rule to make target 'tests'.  Stop.
make: Leaving directory '/workspace'
make: *** [/mnt/c/Users/ernie.cheng/Desktop/distech/mobilnet/edgeTpuCore1/libcoral/docker/docker.mk:40: docker-build] Error 1

btw, I changed the DOCKER_TARGET to benchmarks, same error.
is there a reason for this, or the read.me needs to be updated?
thanks so so much!!!

**Comment by Naveen-Dodda** [comment]
@ernielikesapple 

Can you try docker-shell instead and see if you still have same error. Please try following 

cd libcoral
make docker-shell
make benchmarks     ( make inside the docker shell)

**Comment by hjonnala** [comment]
@ernielikesapple are you still facing the issue?

**Comment by hjonnala** [comment]
Feel free to reopen if issue still exists.
