### ISSUE TITLE
Yolov5 Transpose stops graph loading

### ISSUE THREAD

**Issue by BernardinD** [google-coral/edgetpu#375]
We created an edgetpu graph through the Openvino process and the [graph](https://drive.google.com/file/d/1S5hz2l-mrfR8_LKErRhO3IvjKsE_Rpqc/view?usp=sharing)  seemed to be converted successfully. We checked it in Netron and it seemed normal. But when we try to load the graph using the edgetpu library we get the error:

`RuntimeError: Internal: :213 batches * single_output_size != output->bytes (2028 != 105456)Node number 10 (EdgeTpuDelegateForCustomOp) failed to prepare.`

We suspect the issue has  to do with the Transpose operation not being supported for edgetpu but since it should be run on the CPU we're not sure what's stopping it from loading. 

Any advice? Thanks in advance.

*Netron image:*
![model_full_integer_quant_edgetpu tflite](https://user-images.githubusercontent.com/27456730/117508746-17213580-af57-11eb-910d-d83ef34a374b.png)

**Comment by Naveen-Dodda** [comment]
@BernardinD 

Yes, I can see that runtime fails at me end as well. Can you please share tflite version of the model and also source of the model if possible.

**Comment by BernardinD** [comment]
@Naveen-Dodda here is the [tflite](https://drive.google.com/file/d/19P5xIt_rxxXspqhyDjT-2HSdAvqY-8_R/view?usp=sharing), the source TF [model](https://drive.google.com/file/d/1sx_csuB8g4RBqsggtVaDGZrq5Bw7P9Sv/view?usp=sharing), and the [original pytorch](https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt) file

**Comment by Naveen-Dodda** [comment]
@BernardinD Thanks for sharing the models, tflite models work fine for cpu inference. 

I see that you have exported a frozen_graph.pb which uses a TF1.x converter to quantize the model. Is it possible to export a saved_model or keras from original pytorch file. My plan is to quantise the model with TF2.x exp_quantiser and see if that can fix the miss match of layers.

**Comment by BernardinD** [comment]
@Naveen-Dodda Sorry about that. I've updated the file to include the save_model

**Comment by Naveen-Dodda** [comment]
@BernardinD 

I tired to change few options in Tflite_convert and tested model on edgetpu_compiler. But I haven't seen any success. 

But I have found an interesting thing when referring to [yolov5 model from here  ](https://github.com/zye1996/Yolov5_EdgeTPU). The same model works fine on edgetpu. when I looked deeper, the only difference between your model and his is (ResizeNearestNeighbor align_corners =false, half_pixel_centers = true) operation. your model has same op with different config. 

Probably onnx -> tf has messed it up. Can you refer to following repos and see if onnx -> keras will fix the problem ?

https://github.com/zldrobit/yolov5
https://github.com/ultralytics/yolov5

**Comment by BernardinD** [comment]
@Naveen-Dodda The issue had to do with the unexpected 5 dimensional Transpose at the end of the graph. For some reason the edgetpu library was still compiling it even though it wasn't mapped to the TPU. Reshaping the data down to 4D fixed the issue.
