### ISSUE TITLE
Wrong inference results in half image after converting TFLite quantized model into TFLite EdgeTPU model

### ISSUE THREAD

**Issue by fjparrado** [google-coral/edgetpu#377]
Hi,

I have compiled my image segmentation quantized TFLite model for the EdgeTPU. 
Everything looks fine during compilation.

```
Edge TPU Compiler version 15.0.340273435
Input: bisenetv2_cityscapes_frozen_256x512.pbNOARGMAX.tflite
Output: bisenetv2_cityscapes_frozen_256x512.pbNOARGMAX_edgetpu.tflite

Operator                       Count      Status

MEAN                           1          Mapped to Edge TPU
QUANTIZE                       1          Mapped to Edge TPU
MUL                            3          Mapped to Edge TPU
AVERAGE_POOL_2D                1          Mapped to Edge TPU
DEPTHWISE_CONV_2D              16         Mapped to Edge TPU
LOGISTIC                       2          Mapped to Edge TPU
CONCATENATION                  1          Mapped to Edge TPU
MAX_POOL_2D                    1          Mapped to Edge TPU
ADD                            11         Mapped to Edge TPU
RESIZE_BILINEAR                2          Mapped to Edge TPU
CONV_2D                        40         Mapped to Edge TPU
```

In order to be able to map all the operators, I implement the last part of the graph (the last Resize Bilinear) in CPU. See TFLite model on the left and converted TFLite edgeTPU model on the right.

![image](https://user-images.githubusercontent.com/78713704/117614763-5f309a00-b19b-11eb-8936-74f7dc0f5c41.png)

However, during inference, the results for the TFLite model and the converted EdgeTPU model are different... in the right half of the image.

![image](https://user-images.githubusercontent.com/78713704/117615187-f4339300-b19b-11eb-8f00-081441544db7.png)

Now let's mirror the image and test again:

![image](https://user-images.githubusercontent.com/78713704/117615661-9bb0c580-b19c-11eb-9de4-f6374d3cdd4e.png)

Do you have any recommendation in order to solve the issue?
Thanks

**Comment by Naveen-Dodda** [comment]
@dragonvenenoso 

This hasn't been observed before in any other segmentation models with edgetpu. To reproduce this issue can you share following details in a zip file. 
1. Full Tf version of model (saved_model or kears.h5)
2. tflite_convert quantization script that you used to quantise
3. your inference and post processing script.

**Comment by fjparrado** [comment]
Thanks, please check:

https://drive.google.com/file/d/105uciZwuL_jYKVPBVD01MEIaakccQ-1Y/view?usp=sharing

That should be enough to reproduce the issue. Note that the representative dataset for quantization is not included.

**Comment by fjparrado** [comment]
Hello, 
Is there any update on this?

**Comment by Naveen-Dodda** [comment]
@dragonvenenoso, I was able to reproduce with the issue, with model. I am working on dataset setup for quantization, Will update more details in next 24hrs

**Comment by fjparrado** [comment]
Thanks Naveen

**Comment by Naveen-Dodda** [comment]
@dragonvenenoso I was able to reproduce the issue, before digging further deep into issue can you help me to get info below so that we can find a resolution. 

1. Is this frozen graph generated from onnx or pytorch by any chance 
2. Aren't you able to convert / compile the model with ArgMax tensor ?
3. if so do you see a similar issue ?
4. Have you seen similar behavior on different inputs.

**Comment by fjparrado** [comment]
Hi @Naveen-Dodda 
1) The model was defined, trained and frozen using TF1.15.5 
2) I will check and come back to you 
3) I will check and come back to you 
4) Yes, same behaviour with different inputs. I also trained the model using a different dataset (same input resolution) and same behavior was observed.

**Comment by Naveen-Dodda** [comment]
@dragonvenenoso Thanks for quick response. So you see this behavior only with 256x512 resolution ?

**Comment by fjparrado** [comment]
@Naveen-Dodda This is the log when converting the whole model (including ArgMax)

```
Edge TPU Compiler version 15.0.340273435
Input: bisenetv2_cityscapes_frozen_256x512.pb.tflite
Output: bisenetv2_cityscapes_frozen_256x512.pb_edgetpu.tflite

Operator                       Count      Status

LOGISTIC                       2          Mapped to Edge TPU
DEPTHWISE_CONV_2D              16         Mapped to Edge TPU
AVERAGE_POOL_2D                1          Mapped to Edge TPU
QUANTIZE                       1          Mapped to Edge TPU
MEAN                           1          Mapped to Edge TPU
SOFTMAX                        1          Max 16000 elements supported
RESIZE_BILINEAR                3          Mapped to Edge TPU
ADD                            11         Mapped to Edge TPU
MUL                            3          Mapped to Edge TPU
CONV_2D                        40         Mapped to Edge TPU
MAX_POOL_2D                    1          Mapped to Edge TPU
CONCATENATION                  1          Mapped to Edge TPU
ARG_MAX                        1          Operation is working on an unsupported data type
```
![image](https://user-images.githubusercontent.com/78713704/119072097-84d06580-ba1d-11eb-8a11-6572634fb3f5.png)

Getting same results as before:

![image](https://user-images.githubusercontent.com/78713704/119074020-d7f7e780-ba20-11eb-89e6-856c295104e1.png)

I only trained the model with 256x512 resolution. This is the resolution required to meet the needs of our project.

**Comment by Naveen-Dodda** [comment]
@dragonvenenoso Thanks for conformation 

If you have used TF to retarin have you used this repo https://github.com/MaybeShewill-CV/bisenetv2-tensorflow
to retrain ?

Can you point me to source of retraining.

**Comment by fjparrado** [comment]
@Naveen-Dodda yes, I did

**Comment by Naveen-Dodda** [comment]
@dragonvenenoso I was able to reproduce this on a fully compiled model as well. I report this internally share more feedback to you to fix this. 
I shall get back to you. 

Thanks for patience here.

**Comment by fjparrado** [comment]
Thanks Naveen!

**Comment by Naveen-Dodda** [comment]
@dragonvenenoso It seems like the error only occurs when the input size is 512x256. Models work fine with other resolutions like (320x640,320x320,512x512).

Can you cross check this on your end and conform. 

[test_models.tar.gz](https://github.com/google-coral/edgetpu/files/6550354/test_models.tar.gz)

**Comment by hjonnala** [comment]
@dragonvenenoso do you still have any issues?

**Comment by fjparrado** [comment]
I am very sorry for my late reply.

Unfortunately, the resolution of 512x256 was one of the internal requirements for the project so we decided to move forward using another device. 

I could not cross check that my trained model works fine using other resolutions.
