### ISSUE TITLE
Crazy stuff happening (e.g. overflows) with some tflite models

### ISSUE THREAD

**Issue by ricardodeazambuja** [google-coral/edgetpu#379]
Hi,

I deleted a comment three times in another issue because I thought, three times, it could be my fault instead of a bug in the compiler. Therefore, I decided to test it on my laptop, and the problem is still there :(

I tested [this face detection model](https://github.com/google-coral/edgetpu/blob/master/test_data/ssd_mobilenet_v2_face_quant_postprocess.tflite).
```
Edge TPU Compiler version 15.0.340273435
Input: ssd_mobilenet_v2_face_quant_postprocess.tflite
Output: ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite

Operator                       Count      Status

LOGISTIC                       1          Mapped to Edge TPU
DEPTHWISE_CONV_2D              17         Mapped to Edge TPU
DEQUANTIZE                     3          Operation is working on an unsupported data type
QUANTIZE                       10         Mapped to Edge TPU
CONV_2D                        55         Mapped to Edge TPU
ADD                            10         Mapped to Edge TPU
CUSTOM                         32         Operation is working on an unsupported data type
RESHAPE                        13         Mapped to Edge TPU
CONCATENATION                  2          Mapped to Edge TPU
PAD                            23         Mapped to Edge TPU

```
Using [this image](https://images.canadagoose.com/image/upload/w_1333,c_scale,f_auto,q_auto:best/v1601577550/product-image/5558U_1073.jpg) and the edgetpu (USB), the classes returned are these:
```
[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 1.1497215e+24 4.9594010e+33 7.9049203e+31 1.1637213e+24]
```
Yup, 1.1497215e+24 4.9594010e+33 7.9049203e+31 1.1637213e+24.

The original tflite model returns:
```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
```

And this is the tflite_runtime version:
```
__version__ = '2.5.0'
__git_version__ = '48c3bae94a8b324525b45f157d638dfd4e8c3be1'
```

If I use [the edgetpu version available on the same repo](https://github.com/google-coral/edgetpu/blob/master/test_data/ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite), same crazy results.

Using another model, the one that I was struggling last week, the array with scores was almost identical between the original tflite and the edgetpu compiled one, but the classes would not match (e.g. flipping from 3.0 to 2.0).

Now, if I get the ssd_mobilenet_v2_face_quant_postprocess model from [this repo](https://github.com/EscVM/Edge_TPU_Face_Mask_Detection/blob/main/models/ssd_mobilenet_v2_face_quant_postprocess.tflite) and compile it for edgetpu myself, it works perfectly  o.O

**Comment by ricardodeazambuja** [comment]
Ok, software bug on my side... sorry!

**Comment by ricardodeazambuja** [comment]
So, it seems to be a non-deterministic behaviour. If I switch from a ssdlite model to the ssd one (both compiled with edgetpu_compiler), after a random number of times the classes or scores start having crazy values (nan, inf,...). 
Using the tflite models (CPU), this problem doesn't seem to happen... what makes me think it's a problem on the edgetpu side of things.
Additionally, the problem seems only to affect the ssd model. The ssdlite model never generates those values.

**Comment by ricardodeazambuja** [comment]
Another oddity: I have a ssdlite tflite model that, after compiled for the edgetpu, gives me exactly the same first score to a certain input image, but the value for the class changes. I think it's too much of a coincidence the output array giving exactly the same score for the first item, but the class flipping one value down. It looks more like a bug (probably related to conversion between types).
The ssdlite tflite model was generated using [this notebook](https://colab.research.google.com/github/Namburger/edgetpu-ssdlite-mobiledet-retrain/blob/master/mask_detection.ipynb).

**Comment by ricardodeazambuja** [comment]
First time I load ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite, the scores from a certain image:
```
array([0.08203125, 0.01953125, 0.0078125 , 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ],
      dtype=float32)
```
If I delete the object and reload ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite, scores for the same image:
```
array([0.08203125, 0.01953125, 0.0078125 , 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.68472576, 0.6898302 ,
       0.29898265, 1.0133156 , 0.7977123 , 0.713838  , 0.46899194],
      dtype=float32)
```

Output (scores) from the original tflite model (the one used with edgetpu_compiler):
```
array([8.203125e-02, 3.906250e-02, 7.812500e-03, 7.812500e-03,
       3.906250e-03, 3.906250e-03, 3.906250e-03, 3.906250e-03,
       3.906250e-03, 3.906250e-03, 3.906250e-03, 3.906250e-03,
       3.906250e-03, 3.906250e-03, 3.906250e-03, 3.906250e-03,
       3.906250e-03, 3.906250e-03, 3.906250e-03, 3.906250e-03,
       3.906250e-03, 3.906250e-03, 3.906250e-03, 3.906250e-03,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       1.998140e-40, 9.183550e-40], dtype=float32)
```

Output (scores, same image) of ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite, but after I had loaded the ssdlite_edgetpu model once:
```
array([0.08203125, 0.01953125, 0.0078125 , 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
       0.00390625, 0.00390625, 0.00390625,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan],
      dtype=float32)
```

**Comment by Naveen-Dodda** [comment]
Hello, 

I tried to your notebook, but it seems like your dataset is large and take lots of time to train.

Please do remember that the output of the detection scores are Float32 and there could a small error due to quantization loss. 
You can solve this overshooting of scores by setting a threshold while you export the model with nms op 

https://github.com/tensorflow/models/blob/35f33abb8fa40053e8791b9144e894169e543869/research/object_detection/export_tflite_ssd_graph.py#L76

Can you try to export tflite graph with nms ?

**Comment by ricardodeazambuja** [comment]
HI @Naveen-Dodda,

Thanks for your feedback. Did you mean the score_threshold or iou_threshold?

However, the model that goes nuts is [the one from google](https://github.com/google-coral/edgetpu/blob/master/test_data/ssd_mobilenet_v2_face_quant_postprocess.tflite), not the one I trained. And this problem only happens if you reload the model using the same python interpreter process (you must reload inside the same script to reproduce the bug - try to reload the models 10x in sequence...).

I just tried to load [ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite](with https://github.com/google-coral/edgetpu/blob/master/test_data/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite) before the [ssd_mobilenet_v2_face_quant_postprocess](https://github.com/google-coral/edgetpu/blob/master/test_data/ssd_mobilenet_v2_face_quant_postprocess.tflite) and got the same crazy behaviour, but only for the ssd_mobilenet_v2_face_quant_postprocess. Both models were trained and compiled by google.

I was checking the other tensors besides the `TFLite_Detection_PostProcess*` and they don't have any crazy values. That makes me believe the custom op is not cleaning up after itself when the python object is garbage collected.

**Comment by ricardodeazambuja** [comment]
I tested the tensors received by the TFLite_Detection_PostProcess and they don't show the crazy behaviour. So, it must be a bug in the TFLite_Detection_PostProcess related to not cleaning after itself since it only happens when I load the model multiple times inside the same script (so the interpreter is not killed)...

**Comment by hjonnala** [comment]
@ricardodeazambuja can you please try with latest compiler and let us know if you are still facing the issue.
