### ISSUE TITLE
Small graph abnormally slow

### ISSUE THREAD

**Issue by BernardinD** [google-coral/edgetpu#380]
We have a edgetpu model that the log file says is mostly mapped to TPU, but when running the graph the speed is abnormally very slow.

Could you help or give some insight? Thanks in advance.

*Log output:*
```
Edge TPU Compiler version 15.0.340273435
Input: erf_converted_graphs/model_full_integer_quant.tflite
Output: erf_converted_graphs/model_full_integer_quant_edgetpu.tflite

Operator                       Count      Status

ADD                            22         Mapped to Edge TPU
TRANSPOSE                      2          Operation not supported
PAD                            72         Mapped to Edge TPU
FULLY_CONNECTED                2          Mapped to Edge TPU
LOGISTIC                       1          Mapped to Edge TPU
MUL                            3          Mapped to Edge TPU
CONV_2D                        73         Mapped to Edge TPU
TRANSPOSE_CONV                 3          Mapped to Edge TPU
RESHAPE                        3          Mapped to Edge TPU
MAX_POOL_2D                    4          Mapped to Edge TPU
CONCATENATION                  3          Mapped to Edge TPU
QUANTIZE                       5          Mapped to Edge TPU
SOFTMAX                        1          Mapped to Edge TPU
```

*Netron image:*
![model_full_integer_quant_edgetpu tflite](https://user-images.githubusercontent.com/27456730/117692177-c2fe9700-b18a-11eb-91f9-f27059fbd71c.png)

Graphs:

- [Edgetpu](https://drive.google.com/file/d/1vXmYwi3xe5RxRBt2ycxYM8h7Dmxou4XQ/view?usp=sharing) 
- [Tflite](https://drive.google.com/file/d/1UpPqgpBOOE2QVb1UpX4QFmHLjjCBlp9G/view?usp=sharing)
- [Source TF graph](https://drive.google.com/file/d/149sqmIgd1PODZDap7H477tv21BOMUlUy/view?usp=sharing)

**Comment by Naveen-Dodda** [comment]
@BernardinD the drive links you shared are not open public, can you share access or share them in a zip file thanks

**Comment by BernardinD** [comment]
@Naveen-Dodda they should be accessible now

**Comment by Naveen-Dodda** [comment]
@BernardinD 

Though EdgeTpu does it job to accelerate inference, there is huge to  I/O latency to transfer the operations back and forth between cpu and tpu. The Tensors to be transferred are exceptionally large (26x122x5). 

So the model is really slow due latency of i/o operations.

**Comment by BernardinD** [comment]
@Naveen-Dodda we were able to delete the Transpose operations and get the entire middle portion of the graph to map to the TPU and increase the speed of inference. But the speed is still slower than what we expected. 

We've also run the same architecture on Jetson Nano at a higher speed and we were expected even faster speed on EdgeTPU. Any suggestions?

**Comment by Naveen-Dodda** [comment]
@BernardinD 

can you share the new model here without transpose ops and may i know how you are calculating the latency (are you averaging it for 100 inputs ?)

**Comment by BernardinD** [comment]
@Naveen-Dodda  Sorry for the late response. Here is the [graph](https://drive.google.com/file/d/1rMP4LVbUJCBt7gAeAeilDvL-kdaM510r/view?usp=sharing) without Transposes. I am able to get the right output. Although it is still slower than we expected

**Comment by hjonnala** [comment]
@BernardinD  can you try with new Edge TPU Compiler version 16.0.384591198 (with a and d flags). I can see better inference time with new compiler.

```
['model_full_integer_quant_v15_edgetpu.tflite', 'model_full_integer_quant.tflite', 'model_full_integer_quant_edgetpu.tflite']
model_full_integer_quant_v15_edgetpu.tflite
94.95 ms
114.42 ms
109.51 ms
116.50 ms
129.66 ms
model_full_integer_quant.tflite
609.58 ms
589.63 ms
597.05 ms
592.36 ms
608.80 ms
model_full_integer_quant_edgetpu.tflite (new compiler)
67.25 ms
37.84 ms
35.99 ms
35.38 ms
36.18 ms
```

**Comment by hjonnala** [comment]
Feel free to reopen if you have any questions on this issue.
