### ISSUE TITLE
Can one boot from the SD card on the coral dev board mini?

### ISSUE THREAD

**Issue by dripp33** [google-coral/edgetpu#383]
Hi, this question was asked on issue #305, but I don't see that it was answered and I can't find an answer on the Web... With no dip-switches on the mini I wonder how/if SD card boot can be set.

Thanks much for any help,
--dave

**Comment by Naveen-Dodda** [comment]
@dripp33 Unfortunately you cannot boot dev board mini from a sd card

**Comment by dripp33** [comment]
That's too bad, but thanks for the info.
--dave

**Comment by nlublovary** [comment]
While it's not possible to boot directly from an SD card, it is possible to mount the entire root filesystem / (also /boot and /home) from an SD card. I think it's useful to have the entire root on an SD which allows for quick backups and recovery should the filesystem get messed up. 

It's pretty simple to achieve this with an **empty** SD card (at least 8GB), the trick is to either swap the SD cards' PARTUUID with the PARTUUID of the MMC (using **gpart**), or edit /etc/fstab and replace the MMC's PARTUUID of / with the SD card's PARTUUID (using **blkid**).

![putty_Vkatjy721P](https://user-images.githubusercontent.com/7830031/167471735-20602b20-d1c7-4289-9e81-5134e1dcdb68.png)

**Comment by jlpoolen** [comment]
For posterity, the current instructions for the Coral Dev Board (not Mini) have the DIP switch manipulations as follows:

https://coral.ai/docs/dev-board/get-started
Before flashing:

    While the card is being flashed, make sure your Dev Board is completely unplugged, and change the boot mode switches to boot from SD card, as shown in figure 1.

    Boot mode 	Switch 1 	Switch 2 	Switch 3 	Switch 4
    SD card 	ON 	        OFF 	        ON 	        ON
    Figure 1. Boot switches set to SD card mode

After completion of flashing:

    When the red LED turns off, unplug the power and remove the microSD card.

    Change the boot mode switches to eMMC mode, as shown in figure 4:

    Boot mode 	Switch 1 	Switch 2 	Switch 3 	Switch 4
    eMMC 	        ON 	        OFF 	         OFF 	        OFF
    Figure 4. Boot switches set to eMMC mode

Edit: changed to Coral Dev Board (not Mini) [Thank you nlublovary.]

**Comment by nlublovary** [comment]
> For posterity, the current instructions for the Dev Board have the DIP switch manipulations as follows:

Those instructions apply to the "Coral Dev Board" only. The "Coral Dev Board **Mini**" is a different hardware and it has no DIP switches. This discussion was about the mini.

![2022-05-13 20_13_30-Products _ Coral and 9 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/7830031/168325101-14a126d6-71d5-44c2-9e58-c682a17c24b9.png)

**Comment by Jerrym2051** [comment]
> While it's not possible to boot directly from an SD card, it is possible to mount the entire root filesystem / (also /boot and /home) from an SD card. I think it's useful to have the entire root on an SD which allows for quick backups and recovery should the filesystem get messed up.
> 
> It's pretty simple to achieve this with an **empty** SD card (at least 8GB), the trick is to either swap the SD cards' PARTUUID with the PARTUUID of the MMC (using **gpart**), or edit /etc/fstab and replace the MMC's PARTUUID of / with the SD card's PARTUUID (using **blkid**).
> 
> ![putty_Vkatjy721P](https://user-images.githubusercontent.com/7830031/167471735-20602b20-d1c7-4289-9e81-5134e1dcdb68.png)

Would it be possible for you to post a tutorial on how to do it?
