### ISSUE TITLE
No builtin opcode for RSQRT

### ISSUE THREAD

**Issue by rlee360** [google-coral/edgetpu#384]
Hello, I've been working on deploying a source separation neural network using a custom keras model and am having an issue getting the tflite to compile for the edgetpu. I was able to convert quantize my Keras functional mode to tflite using tf 2.5.0rc3, but when I try to compile for the EdgeTPU, I get:

```
Edge TPU Compiler version 15.0.340273435
ERROR: Didn't find op for builtin opcode 'RSQRT' version '2'

ERROR: Registration failed.
```

I tried creating the tflite with tf2.4.1, but it too seems to not support quantizing RSQRT, so there appears to be a recurring theme here. I know the Edge TPU only supports a subset of the operations I am using in my model anyway, but I was under the impression that even if not supported, the tflite model should still compile.

Am I missing something obvious or is there a workaround I can use? Thanks.

Zip contains the model code and the tflite model created with tf2.5.0rc3
[tfl.zip](https://github.com/google-coral/edgetpu/files/6471432/tfl.zip)

**Comment by hjonnala** [comment]
Please try with new compiler version 16.0.384591198. Also make sure you are able run the inference using [tflite Interpreter](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python) before compilation.

**Comment by hjonnala** [comment]
please try quantize_int8.py with  tensorflow==2.5.0 you would be able compile the model.

[conv_tasnet.tflite.tar.gz](https://github.com/google-coral/edgetpu/files/7304159/conv_tasnet.tflite.tar.gz)

![Screenshot from 2021-10-07 07-13-27](https://user-images.githubusercontent.com/86132058/136402458-6a9c026f-d4b7-44e5-8ec9-377f26b4d027.png)
