### ISSUE TITLE
https://mendel-linux.org no longer online

### ISSUE THREAD

**Issue by keslerm** [google-coral/edgetpu#385]
All links and package repos pointing to mendel-linux.org are no longer working.

Can't download the image to flash from the Getting Started page https://mendel-linux.org/images/enterprise/eagle/enterprise-eagle-flashcard-20210204152958.zip

**Comment by ngrutas** [comment]
The eng team is working on getting this resolved asap. Thanks for reporting.

**Comment by ngrutas** [comment]
The dev team has fixed this issue. Please try to download the image again.

**Comment by Namburger** [comment]
@ngrutas wootwoot

**Comment by keslerm** [comment]
Looks good now, thank you!
