### ISSUE TITLE
no builtin opcode for DepthToSpace operation

### ISSUE THREAD

**Issue by bultmann-s** [google-coral/edgetpu#386]
Hello, I have been working on converting a LidAR-Segmentation model (SalsaNext) depending on DepthToSpace operations (called pixel-shuffle in the original architecture)

Are there any plans to support the DepthToSpace operation on the EdgeTPU ?
The inverse operation -- SpaceToDepth -- is already part of the officially supported operations.

When trying to compile my model, quantized and converted to tflite with TensorFlow 2.5.0
I currently only receive the following error message:

```
Edge TPU Compiler version 15.0.340273435
ERROR: Didn't find op for builtin opcode 'DEPTH_TO_SPACE' version '2'

ERROR: Registration failed.
```

**Comment by Naveen-Dodda** [comment]
@bultmann-s We don't have any plans to support DepthToSpace operation on EdgeTPU
