### ISSUE TITLE
Recover parameters from EdgeTPU compiled model 

### ISSUE THREAD

**Issue by ferhatyaman** [google-coral/edgetpu#388]
Hi,
I somehow lost the original model and I have only tpu compiled tflite model. I want to recover model parameters and structure. I used Netron to see details of network. That did not work because it just says custom ops and no details about network other than input, output layers.

Any idea how to get details about the model?

Thanks

**Comment by Naveen-Dodda** [comment]
@ferhatyaman It is not possible to retrieve the structure of model one it is mapped to edgetpu. Even if you use tflite interpreter you can only get details of input and output of the model. 

Finding the tflite model is the only way that help you.
