### ISSUE TITLE
How many parameters and file size can the model executed by Edgetpu support?

### ISSUE THREAD

**Issue by LINYOUWEI0804** [google-coral/edgetpu#389]
How many parameters and file size can the model executed by Edgetpu support?

**Comment by manoj7410** [comment]
@LINYOUWEI0804 Detailed model requirements for TPU are mentioned at https://coral.ai/docs/edgetpu/models-intro/#model-requirements. It is recommended to walk through this link.

**Comment by LINYOUWEI0804** [comment]
Sorry, I still don’t know how many models and model sizes can be supported on the web page.

**Comment by manoj7410** [comment]
@LINYOUWEI0804 It will be helpful if you can elaborate your question. What exact information are you looking for ? 
What models can be executed or how many parallel models can be executed?

**Comment by LINYOUWEI0804** [comment]
Hi! What is the model size and model parameters greater than that can not be predicted on Edgetpu?

**Comment by Naveen-Dodda** [comment]
@LINYOUWEI0804 can you please elaborate your question. 

There is no limit for size of the model,

**Comment by LINYOUWEI0804** [comment]
I tried to use EfficientNetB0-B7 to train a cat and dog recognition model. B0-B3 can be successfully compiled into an edgetpu model, but B4-B7 cannot, so I was thinking that it might be because of too many parameters or too large model size.

**Comment by hjonnala** [comment]
can you please share B4-B7 tflite models to investigate further.

**Comment by hjonnala** [comment]
Feel free to reopen if issue still persists and share the B4-B7 tflite models to investigate further.
