### ISSUE TITLE
TensorFlow Lite C++ EdgeTPU: undefined reference to `rdft'

### ISSUE THREAD

**Issue by zlg9folira** [google-coral/edgetpu#390]
I am trying to use an edgeTPU USB accelerator with arm64 Pi4 using C++ API. I first tried to build TF/TFLite using [this commit](https://github.com/google-coral/edgetpu/blob/657d2b654101540164af240eacb31440ff6f535d/WORKSPACE#L5) as was suggested in several related issues ([here](https://github.com/mattn/go-tflite/issues/30) and more), it turned out that this commit causes `build` process to terminate with:
```
.../libedgetpu_engine.so: undefined reference to `tflite::optimize::sparsity::FormatConverter<float>::FormatConverter(std::vector<int, std::allocator<int> > const&, TfLiteSparsity const&)'
.../libedgetpu_engine.so: undefined reference to `tflite::optimize::sparsity::FormatConverter<signed char>::FormatConverter(std::vector<int, std::allocator<int> > const&, TfLiteSparsity const&)'
```
So, observing the same issue on my `arm64` device, based on [this reply](https://github.com/google-coral/edgetpu/issues/78#issuecomment-599678702) I tried to build TF based on commit version `72cd947f231950d7ecd1406b5a67388fef7133ea`.

Now, I am trying to use/load the edgeTPU in a code where `build` throws this error:
```
/usr/bin/ld: /home/.../libedgetpu_engine.so: undefined reference to `rdft'
```
Would appreciate any suggestion.

**Comment by manoj7410** [comment]
I see that you have already fixed this. For other's reference, here is the fix: https://github.com/tongtybj/edgetpu_roscpp/issues/5#issuecomment-846348726
