### ISSUE TITLE
Quantization aware training

### ISSUE THREAD

**Issue by ricardodeazambuja** [google-coral/edgetpu#391]
Hi,

I was trying to create a model using quantization aware training by following the official documentation:
https://www.tensorflow.org/model_optimization/guide/quantization/training_example

However, even though the notebook says, "After this, you have an actually quantized model with int8 weights and uint8 activations.", edgetpu compiler says, "Model not quantized". Setting ```converter.experimental_new_converter = False``` makes no difference (actually, it does seem to change the final tflite model, but the edgetpu compiler doesn't care)

So, what is the recommended way to create a quantized model without post-training quantization that actually works with edgetpu compiler?

Any feedback will be much appreciated, thank you!

**Comment by manoj7410** [comment]
@ricardodeazambuja Can you share the quantized CPU tflite model here?

**Comment by ricardodeazambuja** [comment]
I really just followed the colab notebook from the official documentation:
https://colab.research.google.com/github/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/g3doc/guide/quantization/training_example.ipynb

Anyway, here are the generated models:
[model_experimental_true.zip](https://github.com/google-coral/edgetpu/files/6531761/model_experimental_true.zip)
[model_experimental_false.zip](https://github.com/google-coral/edgetpu/files/6531762/model_experimental_false.zip)

**Comment by Naveen-Dodda** [comment]
@ricardodeazambuja 

QAT is supported right now.Can you refer the thread https://github.com/google-coral/edgetpu/issues/366

**Comment by ricardodeazambuja** [comment]
@Naveen-Dodda What do you mean by "right now"? Which versions of tf/edgetpu_compiler/etc do I need to make it work?

**Comment by Naveen-Dodda** [comment]
You need edgetpu_compiler 15.0 to compile a QAT model

**Comment by ricardodeazambuja** [comment]
The one I've been using: Edge TPU Compiler version 15.0.340273435

**Comment by Naveen-Dodda** [comment]
@ricardodeazambuja are you able to compile the QAT model ?

**Comment by ricardodeazambuja** [comment]
Not with Edge TPU Compiler version 15.0.340273435. Have you updated the compiler?

**Comment by Naveen-Dodda** [comment]
15.0 is the latest compiler aren't able to compile the model following this thread  #366

**Comment by caijinana** [comment]
i have a create a model with tf2.2, using QAT and got .tflite,but in some model which have BN , edgetpu_compiler shows model not quantization

**Comment by Johannes-vaki** [comment]
I had a problem with many of these tutorials, I think because they are not specifically aiming to be compatible for the edgetpu_compiler.
```
converter = tf.lite.TFLiteConverter.from_saved_model(args.saved_model_dir)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
                                        tf.lite.OpsSet.TFLITE_BUILTINS]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_data_gen
```
I've had to explicitly tell the converter to use only int8 and uint8 for input and outputs and that requires you to supply a representative data to the converter. This admittetly was not with quantization aware training but might work for that too.

**Comment by hjonnala** [comment]
In this [tutorial](https://www.tensorflow.org/model_optimization/guide/quantization/training_example) setting the model input shape would solve the edgetpu compilation error.
```
q_aware_model.input.set_shape((1,) + q_aware_model.input.shape[1:])
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

quantized_tflite_model = converter.convert()
```

```
model.input.set_shape((1,) + model.input.shape[1:])
float_converter = tf.lite.TFLiteConverter.from_keras_model(model)
float_tflite_model = float_converter.convert()
```
![image](https://user-images.githubusercontent.com/86132058/130648003-b7542151-477f-46d5-a169-9ab1988b0b51.png)

![image](https://user-images.githubusercontent.com/86132058/130647863-02cbe86e-6556-42a9-abb0-90d988f8d0ad.png)
