### ISSUE TITLE
Is there a document with the specification of bytecode / instructions for the Coral EdgeTPU?

### ISSUE THREAD

**Issue by ricardodeazambuja** [google-coral/edgetpu#392]
I was thinking about developing a hardware using the [Coral Accelerator Module](https://coral.ai/products/accelerator-module), but I would like to have access to the equivalent of an instruction set as I don't feel safe betting my few coins on a compiler that is not open source. Is this information available to little guys like me?

**Comment by Naveen-Dodda** [comment]
@ricardodeazambuja  Can you be specific on what kind of information you need ? Do you need info to choose a right host ?

**Comment by ricardodeazambuja** [comment]
@Naveen-Dodda I need info to be able to test what the edgetpu_compiler generates is not something buggy / crazy, or is the compiler open source and I didn't realize?

**Comment by Naveen-Dodda** [comment]
Compiler is not open sourced

**Comment by hjonnala** [comment]
There is no  document with the specification of bytecode / instructions for the Coral EdgeTPU as the compiler is not open sourced.

Please refer to this [page](https://coral.ai/docs/edgetpu/compiler/ )  which describes how to use the compiler and a bit about how it works.

**Comment by ricardodeazambuja** [comment]
That's my point! I may understand the reasons to keep the compiler source code as a commercial secret (considering Google is doing something really clever that is not based on some open source project...), but it doesn't make sense to hide the bytecode / instruction set because any educated person can generate as many tflite models as necessary (Mr. Random is your friend), pass them through the compiler and figure that out... a task easy to automate that can run in parallel using multiple processes.
By having the specification available I would trust the hardware much more than I do right now.
