### ISSUE TITLE
edge TPU compiler not mapping all ops to TPU

### ISSUE THREAD

**Issue by arya-yazdani** [google-coral/edgetpu#393]
Hi, 
I know many people have posted this issue but going through solutions I cannot get the compiler mapping all ops to TPU. I appreciate your advice.
Here is the log from compiler ( I run: edgetpu_compiler --out_dir ./EdgeTPU/ model.tflite)
here is the output:

Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 2644 ms.

Input model: model.tflite
Input size: 4.22MiB
Output model: ./EdgeTPU/model_edgetpu.tflite
Output size: 4.71MiB
On-chip memory used for caching model parameters: 3.21MiB
On-chip memory remaining for caching model parameters: 3.78MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 165
Operation log: ./EdgeTPU/model_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 117
Number of operations that will run on CPU: 48
See the operation log file for individual operation details.

here is the log: 

Edge TPU Compiler version 15.0.340273435
Input: model.tflite
Output: ./EdgeTPU/model_edgetpu.tflite

Operator                       Count      Status

QUANTIZE                       6          Mapped to Edge TPU
QUANTIZE                       2          More than one subgraph is not supported
DEPTHWISE_CONV_2D              14         More than one subgraph is not supported
DEPTHWISE_CONV_2D              37         Mapped to Edge TPU
CONV_2D                        14         More than one subgraph is not supported
CONV_2D                        58         Mapped to Edge TPU
LOGISTIC                       1          More than one subgraph is not supported
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        6          Mapped to Edge TPU
RESHAPE                        3          More than one subgraph is not supported
CONCATENATION                  2          More than one subgraph is not supported
PACK                           4          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
ADD                            10         Mapped to Edge TPU
ADD                            2          More than one subgraph is not supported
CUSTOM                         1          Operation is working on an unsupported data type
DEQUANTIZE                     2          Operation is working on an unsupported data type

when I run edgetpu_compiler -a model.tflite I get this:
Edge TPU Compiler version 15.0.340273435

Internal compiler error. Aborting! 

Can you please advise what I need to do now?
thanks

**Comment by manoj7410** [comment]
@arya-yazdani Can you share your CPU .tflite model here ?

**Comment by arya-yazdani** [comment]
@manoj7410 thanks for your response, I have attached it here, as I was reading about edge TPU compiler, I believe the pack op in my model is the reason for this issue. I appreciate your feedback on it and possibly how I can fix it? 


[model-3.tflite.zip](https://github.com/google-coral/edgetpu/files/6577191/model-3.tflite.zip)

**Comment by arya-yazdani** [comment]
@manoj7410  any idea what might be wrong?

**Comment by manoj7410** [comment]
@arya-yazdani pack operation is supported as long as there is no packing in batch dimension. I have seen this in the past with reshape operation however I'll get this checked with my teammate and will get back on this.

**Comment by arya-yazdani** [comment]
Thank you very much. I am looking forward to your update

**Comment by manoj7410** [comment]
@arya-yazdani Can you please share more details on how you have quantized the model? And can you also share the source of the model ?

**Comment by arya-yazdani** [comment]
hi thanks for your response. I used transfer learning by following instructions in following link:
https://medium.com/swlh/creating-your-own-custom-object-detector-using-transfer-learning-f26918697889
then exported the model for tflite generation purpose, then quantized and converted it to TFlite using following lines:

converter = tf.lite.TFLiteConverter.from_saved_model('.../Project/exported-model-tflite/all_0530/saved_model/')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
experimental_new_converter = True
converter.representative_dataset = representative_dataset
converter.target_spec.supported_types = [tf.int8]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
converter.post_training_quantize = True
tflite_quant_model = converter.convert()
TFLITE_FILE_PATH = '.../model.tflite'
with open(TFLITE_FILE_PATH, 'wb') as f:
  f.write(tflite_quant_model)

I gotta mention that my images are originally 720p but in order to train I used 640x640 in pipeline.config file. Also I didn't change batch size in pipeline.config and left it equal to 128.
Attached is the exported model used for TFlite conversion using following lines:

python3 export_tflite_graph_tf2.py \
    --pipeline_config_path .../pipeline.config \
    --trained_checkpoint_dir .../Project/models/model/ \
    --output_directory .../Project/exported-model-tflite/model


Please let me know if you have more questions 
thanks


[saved_model (4).zip](https://gith[saved_model (4).zip](https://github.com/google-coral/edgetpu/files/6613453/saved_model.4.zip)

**Comment by manoj7410** [comment]
Did you try with 'experimental_new_converter = False' as well ?

**Comment by arya-yazdani** [comment]
I just set 'experimental_new_converter ' to False and still get the same thing. I think the main issue is DepthWiseConv2D location 50 as stride of 2 for width and height which cause dimension mismatch at ad op location 68. this will need a reshape but mainly two pack ops before that have dimensions greater than 3 which breaks the compile loop. Is there a way I can change thesein the model? or should I train from scratch?
[image](https://user-images.githubusercontent.com/84946163/121608632-3eac6780-ca07-11eb-8391-0b53589640f0.png)

**Comment by manoj7410** [comment]
@arya-yazdani did you try to train the model from scratch ?

**Comment by arya-yazdani** [comment]
Hi,
No I tried another model with image size of 300x300 which does not have fpn
feature extractor. Fpn’s are not compatible with EdgeTPU
Thanks for the follow up

**Comment by manoj7410** [comment]
Coral has started supporting FPN now. Please checkout https://coral.ai/news/updates-07-2021.
