### ISSUE TITLE
RESIZE_BILINEAR failing to compile. Working before

### ISSUE THREAD

**Issue by agjunyent** [google-coral/edgetpu#396]
Hi,

I've been using the compiler for more than 6 months now, without problem. I've compiled several models, and made them work on the Coral.

Today I've tried to compile an already compiled model that worked before, and I'm getting:

RESIZE_BILINEAR                2          Operation version not supported

Nothing has changed in our side: the file is exactly the same that we compiled around 2 months ago (begining of April).

I've tried to use TF2.3, TF2.4, TF2.5, all of them give the same error. I'm using a Google Colab sheet to convert the models, and I've not changed a line on it: just upload the .hdf5 file, change the name of it in the tflite converted, and run all. It fails in the compiler.

Has the compiler changed since first month of April? I honestly don't know what else to do.

**Comment by Naveen-Dodda** [comment]
Compiler has not been updated recently. I assume you are using  edgetpu_compiler 15.0. 

May i know TF version  you have used for training ?

**Comment by agjunyent** [comment]
Hi, thanks for the comment.

I'm not using TF for training. I use darknet (https://github.com/AlexeyAB/darknet) to train and Yolov4 to convert to TF (https://github.com/hhk7734/tensorflow-yolov4)

The later has not been updated since February, so I don't think that's the problem. I have a converted model that works from late April.

As I say in the OP, I've tested Tensorflow 2.3 to 2.5, all versions (not rc), none of them work.

**Comment by Naveen-Dodda** [comment]
Have you tested with TF1.x ?

I am not sure why the model compiled fine in apr and not now while your environment has not changed

**Comment by tml444** [comment]
Hello,

I just tested this with the following simple keras model and have the same problems:

```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

input_layer = keras.Input(shape=(32, 32, 3))

x = layers.Conv2D(2, 2, padding = 'same')(input_layer) 
x = layers.Activation('relu')(x)   
x = layers.MaxPooling2D()(x) 
x = layers.Conv2D(2, 2, padding = 'same')(x)
x = layers.Activation('relu')(x) 
x = layers.UpSampling2D()(x) 
x = layers.Conv2D(2, 2, padding = 'same')(x)
output_layer  = layers.Activation('relu')(x) 

model = keras.Model(inputs = input_layer, outputs = output_layer)
model.compile()
model.summary()
model.save('test_model')
```

I used the current tf-nightly-gpu package (TF2.5) to generate the model, then int8-quantized with the following configuration:

```python
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_from_random
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.TFLITE_BUILTINS]
    converter.target_spec.supported_types = [tf.int8]
    converter.inference_input_type = tf.float32
    converter.inference_output_type = tf.float32
    converter.allow_custom_ops = True
```

Then I used the edgetpu compiler (version 15.0.340273435) and this is the result:

```
Edge TPU Compiler version 15.0.340273435
Input: model_int8.tflite
Output: model_int8_edgetpu.tflite

Operator                       Count      Status

RESIZE_NEAREST_NEIGHBOR        1          Operation version not supported
MAX_POOL_2D                    1          Mapped to Edge TPU
DEQUANTIZE                     1          Operation is working on an unsupported data type
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONV_2D                        2          Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
```

Shouldn't this code work and get compiled without problems? Or is there a problem with the keras function UpSampling2D maybe?

Best regards

**Comment by Naveen-Dodda** [comment]
Hello, 

Your example above is built on TF2.x, current external compiler doesn't support RESIZE_NEAREST_NEIGHBOR  exported from TF2.x. This specific op is supported if it is exported with TF1.x. 

So your previous code could be based on TF1. x.

**Comment by tml444** [comment]
Hello Naveen-Dodda,

thank you very much for the reply, you are right. Using tf1 tflite converter and disabling experimental_new_converter param worked for models exported with TF2.5 and also with TF1.15. Is there more support coming for TF2.x in the near future?

**Comment by agjunyent** [comment]
I've tried as @tml444 said using tf1, same error.

I'll do more debugging, but I'm running out of options :(

**Comment by Naveen-Dodda** [comment]
> Hello Naveen-Dodda,
> 
> thank you very much for the reply, you are right. Using tf1 tflite converter and disabling experimental_new_converter param worked for models exported with TF2.5 and also with TF1.15. Is there more support coming for TF2.x in the near future?

Yes the support for TF2.x resize_bilinear will be added in our next release.

**Comment by Johannes-vaki** [comment]
@Naveen-Dodda Do you know when your next release is. I am excited for this feature. Are they scheduled somewhere? I have searched the coral.ai website but not found any release schedule.

**Comment by hjonnala** [comment]
@Johannes-vaki new compiler version got released. @agjunyent please try with new compiler and let us know if you are facing any issues.

**Comment by agjunyent** [comment]
Hi! Sorry for the delay, vacations kicked in!

Will test as soon as I'm back to work. Thanks!

**Comment by hjonnala** [comment]
Feel free to reopen if issue still persists.
