### ISSUE TITLE
Edgetpu_compiler compiler error

### ISSUE THREAD

**Issue by NooLL** [google-coral/edgetpu#397]
```
Edge TPU Compiler version 15.0.340273435
loc("reshape_output"): error: 'tfl.reshape' op quantization parameters violate the same scale constraint: !quant.uniform<u8:f32, 0.21378526091575623:119> vs. !quant.uniform<u8:f32, 0.20749549567699432:119>

Internal compiler error. Aborting! 

```

The model I am trying to compile i from google cloud object detection tflite model. 

I saw a suggestion on stackoverflow with the same problem which suggest me to downgrade the version to 14.1. However, I can't seem to downgrade it. 
https://stackoverflow.com/questions/66998921/compile-automl-tflite-to-edge-tpu

**Comment by Naveen-Dodda** [comment]
Hello,

Current edgetpu compiler fails to compile models deployed by image object detection api. You can follow steps below to downgrade edgetpu compiler. 

git clone https://github.com/google-coral/edgetpu.git
cd edgetpu
sudo cp -r compiler/x86_64/* /usr/local/bin/


I am not sure about your application, if you interested you can try [video object detection.](https://cloud.google.com/video-intelligence/automl/object-tracking/docs/quickstart-console)
