### ISSUE TITLE
Hardware failure?

### ISSUE THREAD

**Issue by rizawise** [google-coral/edgetpu#398]
Hi, I have coral dev board mini and was able to run it. 
But somehow i accidentally unplug the power usbc, then i can not boot anymore and  i can not detect the usb on my linux host os. The led constantly red, i don't have jumper cable yet so i can't do the reflash.

can i fix this, or my board already bricked?

**Comment by manoj7410** [comment]
@rizawise Did you also try to connect your board to an HDMI screen ? Do you see anything on that ?

**Comment by rizawise** [comment]
@manoj7410 problem solved by following this https://coral.ai/docs/dev-board-mini/reflash/#force-boot-into-fastboot-mode
Thanks
