### ISSUE TITLE
converting .tflite model to edgetpu.tflite

### ISSUE THREAD

**Issue by ulrichMarco** [google-coral/edgetpu#399]
Hi,
im trying to convert a .tflite model to an edgetpu.tflite model. the tflite model works fine, but after converting using the edgetpu_compiler it results in relativly low detection scores and therefore just a few detection boxes.

tflite inference example 
![tmp3z8qnmha](https://user-images.githubusercontent.com/83692293/121020460-ab71f880-c7a0-11eb-8a69-ec914847a8ca.PNG)

edgetpu.tflite example (unsing the detect_image.py from examples)
![tmpygffw5th](https://user-images.githubusercontent.com/83692293/121020498-b3319d00-c7a0-11eb-8b04-42fbfcfe8d83.PNG)

command i used
`edgetpu_compiler model.tflite`
results in
```
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 1042 ms.

Input model: model.tflite
Input size: 4.18MiB
Output model: model_edgetpu.tflite
Output size: 4.77MiB
On-chip memory used for caching model parameters: 3.21MiB
On-chip memory remaining for caching model parameters: 3.78MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 158
Operation log: model_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 112
Number of operations that will run on CPU: 46
See the operation log file for individual operation details.
```
i see that not all ops are supported by the edgetpu runtime and are executed on the cpu but, but shouldn't be the output the same as the tflite one.

Models, scripts and resources to reproduce:
[tflite2edgetpu.zip](https://github.com/google-coral/edgetpu/files/6609185/tflite2edgetpu.zip)

to run tflite model
`python3 tflite_run.py`

to run edgetpu.tflite model (its the detect_image.py from the examples)
`python3 detect_image.py -m model_edgetpu.tflite -i A00147.png -o out.png -l labels.txt`

**Comment by manoj7410** [comment]
@ulrichMarco You are running this on the Dev board or on any other Coral device ?

**Comment by ulrichMarco** [comment]
@manoj7410 Running it seperately on 'Coral Usb Accellerator' and a 'Coral M.2 Accelerator with Dual Edge TPU' both produce similar outputs.

**Comment by ulrichMarco** [comment]
@manoj7410 
Addition:
To get a fully compatible edgetpu model i followed the steps from https://coral.ai/docs/edgetpu/retrain-detection/ with my dataset.
After computing the model i am facing still the same issue.

didnt train it the full 50k steps canceled at 41k to test it. 
the new models: [models.zip](https://github.com/google-coral/edgetpu/files/6632011/models.zip)
 
Correct me if im wrong, but because the tflite model is working fine: 
-The problem shouldn't be in my .record files or the scripts.
-And because I used two devices on different systems to test it, (Could you tell me if the problem is happening to you too) the problem shouldn't be in my hardware or drivers.
-So the last error spot i can imagine is the edgetpu_compiler

**Comment by ulrichMarco** [comment]
@manoj7410  
Anything new? 
Can you confirm that you get similar results?

**Comment by manoj7410** [comment]
@ulrichMarco Unfortunately, my linux laptop got crashed while training a model. I am yet to reproduce this issue at my end. Will get back to you soon on this.

**Comment by ulrichMarco** [comment]
@manoj7410 
sry i dont want to be too impatient, but the problem persists.

Were you able to reproduce the issue?
Can you suggest a solving strategy?

**Comment by manoj7410** [comment]
@ulrichMarco I was able to reproduce this and checking within the team regarding what can be the reason for this.

**Comment by Naveen-Dodda** [comment]
@ulrichMarco it seems like there is a mis match in the post processing steps of detect_image.py and tflite_run.py 

If you can change tflite_run.py and plug in edgetpu model you get same results for both the models.


print()

#interpreter = tflite.Interpreter('model.tflite')
interpreter = tflite.Interpreter('model_edgetpu.tflite', experimental_delegates =[tflite.load_delegate('libedgetpu.so.1')])
interpreter.allocate_tensors()


Can you try this and conform if the results of both models match ?

**Comment by ulrichMarco** [comment]
@Naveen-Dodda 
i can confirm that the results of both models match. In some cases the detection scores are off by a few percent or the detectionboxes are off by a few pixels, but this is ok for my use cases. 

Now i am just wonder why this problem is happening, because the detect_image.py is coming from the official detection example. And the example datasets are working fine with it, but as soon as i tried to use my custom dataset this error/problem occured. So maybe the example needs an update? I explicit used the example, because i am new object detection on edgetpu and wanted to make sure that some code i write isnt the problem

**Comment by manoj7410** [comment]
@ulrichMarco Are you still facing any issues while running models on the edgetpu ?

**Comment by ulrichMarco** [comment]
No, the models are working now.
