### ISSUE TITLE
Coral pcie install (gasket-dkms) fails on ROCK PI 4 

### ISSUE THREAD

**Issue by cnndabbler** [google-coral/edgetpu#40]
Hi,

Installing gasket-dkms fails.

Thanks for looking into it

pi@rockpi1: sudo apt install gasket-dkms fails with following information:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  gasket-dkms
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 44.7 kB of archives.
After this operation, 240 kB of additional disk space will be used.
Get:1 https://packages.cloud.google.com/apt coral-edgetpu-stable/main arm64 gasket-dkms all 1.0-10 [44.7 kB]
Fetched 44.7 kB in 1s (88.3 kB/s)
Selecting previously unselected package gasket-dkms.
(Reading database ... 96059 files and directories currently installed.)
Preparing to unpack .../gasket-dkms_1.0-10_all.deb ...
Unpacking gasket-dkms (1.0-10) ...
Setting up gasket-dkms (1.0-10) ...
Loading new gasket-1.0 DKMS files...
Building for 4.4.154-104-rockchip-g3037f71a0de7
Building initial module for 4.4.154-104-rockchip-g3037f71a0de7
Error! Bad return status for module build on kernel: 4.4.154-104-rockchip-g3037f71a0de7 (aarch64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.

pi@rockpi1:~$ cat /var/lib/dkms/gasket/1.0/build/make.log
DKMS make.log for gasket-1.0 for kernel 4.4.154-104-rockchip-g3037f71a0de7 (aarch64)
Sat Jan 11 20:19:56 UTC 2020
make: Entering directory '/usr/src/linux-headers-4.4.154-104-rockchip-g3037f71a0de7'
  LD      /var/lib/dkms/gasket/1.0/build/built-in.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_sysfs.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/apex_driver.o
/bin/sh: 1: ./scripts/recordmcount: Exec format error
scripts/Makefile.build:277: recipe for target '/var/lib/dkms/gasket/1.0/build/gasket_sysfs.o' failed
make[1]: *** [/var/lib/dkms/gasket/1.0/build/gasket_sysfs.o] Error 2
make[1]: *** Waiting for unfinished jobs....
/bin/sh: 1: ./scripts/recordmcount: Exec format error
scripts/Makefile.build:277: recipe for target '/var/lib/dkms/gasket/1.0/build/gasket_ioctl.o' failed
make[1]: *** [/var/lib/dkms/gasket/1.0/build/gasket_ioctl.o] Error 2
/bin/sh: 1: ./scripts/recordmcount: Exec format error
scripts/Makefile.build:277: recipe for target '/var/lib/dkms/gasket/1.0/build/gasket_interrupt.o' failed
make[1]: *** [/var/lib/dkms/gasket/1.0/build/gasket_interrupt.o] Error 2
/bin/sh: 1: ./scripts/recordmcount: Exec format error
scripts/Makefile.build:277: recipe for target '/var/lib/dkms/gasket/1.0/build/gasket_page_table.o' failed
make[1]: *** [/var/lib/dkms/gasket/1.0/build/gasket_page_table.o] Error 2
/bin/sh: 1: ./scripts/recordmcount: Exec format error
scripts/Makefile.build:277: recipe for target '/var/lib/dkms/gasket/1.0/build/gasket_core.o' failed
make[1]: *** [/var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 2
/bin/sh: 1: ./scripts/recordmcount: Exec format error
scripts/Makefile.build:277: recipe for target '/var/lib/dkms/gasket/1.0/build/apex_driver.o' failed
make[1]: *** [/var/lib/dkms/gasket/1.0/build/apex_driver.o] Error 2
Makefile:1474: recipe for target '_module_/var/lib/dkms/gasket/1.0/build' failed
make: *** [_module_/var/lib/dkms/gasket/1.0/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.4.154-104-rockchip-g3037f71a0de7'

pi@rockpi1:~$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  3
Socket(s):           2
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1800.0000
CPU min MHz:         408.0000
BogoMIPS:            48.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32

pi@rockpi1:~$ uname -r
4.4.154-104-rockchip-g3037f71a0de7

pi@rockpi1:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by Namburger** [comment]
@cnndabbler 
```
./scripts/recordmcount: Exec format error
```
is due to the file `recordmcount` in the linux-headers package for the Rock pi 4 was compiled for x86_64 platform which is not going to run on arm. Could you share the output of this:
```
$ file /usr/src/linux-headers-4.4.154-104-rockchip-g3037f71a0de7/scripts/recordmcount
```
According to [this](https://forum.radxa.com/t/dkms-building-error/307/4), you'll need to rebuilt some of the executables again for now, but it seems the Rock Pi4 team should already have a fix for this!
Hope this helps!

**Comment by cnndabbler** [comment]
@Namburger 
Thanks for the insight. 

file /usr/src/linux-headers-4.4.154-104-rockchip-g3037f71a0de7/scripts/recordmcount

/usr/src/linux-headers-4.4.154-104-rockchip-g3037f71a0de7/scripts/recordmcount: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=0c0026551b4441d0dbfeba03e5a30477195cd988, not stripped
