### ISSUE TITLE
Run Edge tpu  error

### ISSUE THREAD

**Issue by caijinana** [google-coral/edgetpu#401]
RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 0 (edgetpu-custom-op) failed to prepare.
Failed to allocate tensors.

**Comment by manoj7410** [comment]
@caijinana Is your model quantized ? Can you share your model here ?

**Comment by caijinana** [comment]
@manoj7410 i use the  Run a model using the PyCoral API in the edgetpu code

**Comment by manoj7410** [comment]
@caijinana Which model are you trying to run ? And on which device are you running it ?

**Comment by caijinana** [comment]
@manoj7410  i use mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite and run model in the  Devboard

**Comment by caijinana** [comment]
@manoj7410

**Comment by manoj7410** [comment]
@caijinana Can you share the output of below commands:
- ls /dev/*
- cat /etc/os-release

**Comment by caijinana** [comment]
/dev/apex_0           /dev/loop2               /dev/ptyp2      /dev/tty12  /dev/tty37  /dev/tty61    /dev/ttyS1
/dev/autofs           /dev/loop3               /dev/ptyp3      /dev/tty13  /dev/tty38  /dev/tty62    /dev/ttyS2
/dev/btrfs-control    /dev/loop4               /dev/ptyp4      /dev/tty14  /dev/tty39  /dev/tty63    /dev/ttyS3
/dev/cec0             /dev/loop5               /dev/ptyp5      /dev/tty15  /dev/tty4   /dev/tty7     /dev/ubi_ctrl
/dev/console          /dev/loop6               /dev/ptyp6      /dev/tty16  /dev/tty40  /dev/tty8     /dev/urandom
/dev/cpu_dma_latency  /dev/loop7               /dev/ptyp7      /dev/tty17  /dev/tty41  /dev/tty9     /dev/vcs
/dev/cuse             /dev/loop-control        /dev/ptyp8      /dev/tty18  /dev/tty42  /dev/ttyGS0   /dev/vcs1
/dev/fb0              /dev/mem                 /dev/ptyp9      /dev/tty19  /dev/tty43  /dev/ttymxc0  /dev/vcs2
/dev/full             /dev/memory_bandwidth    /dev/ptypa      /dev/tty2   /dev/tty44  /dev/ttymxc1  /dev/vcs3
/dev/fuse             /dev/mmcblk0             /dev/ptypb      /dev/tty20  /dev/tty45  /dev/ttymxc2  /dev/vcs4
/dev/galcore          /dev/mmcblk0boot0        /dev/ptypc      /dev/tty21  /dev/tty46  /dev/ttyp0    /dev/vcs5
/dev/gpiochip0        /dev/mmcblk0boot1        /dev/ptypd      /dev/tty22  /dev/tty47  /dev/ttyp1    /dev/vcs6
/dev/gpiochip1        /dev/mmcblk0p1           /dev/ptype      /dev/tty23  /dev/tty48  /dev/ttyp2    /dev/vcs7
/dev/gpiochip2        /dev/mmcblk0p2           /dev/ptypf      /dev/tty24  /dev/tty49  /dev/ttyp3    /dev/vcsa
/dev/gpiochip3        /dev/mmcblk0p3           /dev/random     /dev/tty25  /dev/tty5   /dev/ttyp4    /dev/vcsa1
/dev/gpiochip4        /dev/mmcblk0p4           /dev/rtc        /dev/tty26  /dev/tty50  /dev/ttyp5    /dev/vcsa2
/dev/hwrng            /dev/mmcblk0rpmb         /dev/rtc0       /dev/tty27  /dev/tty51  /dev/ttyp6    /dev/vcsa3
/dev/i2c-0            /dev/mxc_hantro          /dev/spidev0.0  /dev/tty28  /dev/tty52  /dev/ttyp7    /dev/vcsa4
/dev/i2c-1            /dev/network_latency     /dev/spidev0.1  /dev/tty29  /dev/tty53  /dev/ttyp8    /dev/vcsa5
/dev/i2c-2            /dev/network_throughput  /dev/stderr     /dev/tty3   /dev/tty54  /dev/ttyp9    /dev/vcsa6
/dev/initctl          /dev/null                /dev/stdin      /dev/tty30  /dev/tty55  /dev/ttypa    /dev/vcsa7
/dev/ion              /dev/port                /dev/stdout     /dev/tty31  /dev/tty56  /dev/ttypb    /dev/vga_arbiter
/dev/kmsg             /dev/pps0                /dev/tty        /dev/tty32  /dev/tty57  /dev/ttypc    /dev/vhci
/dev/kvm              /dev/ptmx                /dev/tty0       /dev/tty33  /dev/tty58  /dev/ttypd    /dev/video0
/dev/log              /dev/ptp0                /dev/tty1       /dev/tty34  /dev/tty59  /dev/ttype    /dev/watchdog
/dev/loop0            /dev/ptyp0               /dev/tty10      /dev/tty35  /dev/tty6   /dev/ttypf    /dev/watchdog0
/dev/loop1            /dev/ptyp1               /dev/tty11      /dev/tty36  /dev/tty60  /dev/ttyS0    /dev/zero

/dev/block:
179:0  179:1  179:2  179:3  179:32  179:4  179:64  179:96  7:0  7:1  7:2  7:3  7:4  7:5  7:6  7:7

/dev/bus:
usb

/dev/char:
10:130  10:59   116:24  13:66  189:128  2:10   237:0  254:0  29:0  3:2  4:1   4:18  4:26  4:34  4:42  4:50  4:59  4:67  7:128  7:3
10:137  10:60   116:32  13:67  189:3    2:11   238:0  254:1  3:0   3:3  4:10  4:19  4:27  4:35  4:43  4:51  4:6   4:7   7:129  7:4
10:183  10:61   116:33  1:4    1:9      2:12   2:4    254:2  3:1   3:4  4:11  4:2   4:28  4:36  4:44  4:52  4:60  4:8   7:130  7:5
10:200  10:62   116:48  1:5    199:0    2:13   246:0  254:3  3:10  3:5  4:12  4:20  4:29  4:37  4:45  4:53  4:61  4:9   7:131  7:6
10:232  10:63   116:56  153:0  2:0      2:14   248:0  254:4  3:11  3:6  4:13  4:21  4:3   4:38  4:46  4:54  4:62  5:0   7:132  7:7
10:235  1:1     120:0   153:1  207:16   2:15   249:0  2:6    3:12  3:7  4:14  4:22  4:30  4:39  4:47  4:55  4:63  5:1   7:133  81:0
10:237  1:11    1:3     1:7    207:17   2:2    2:5    2:7    3:13  3:8  4:15  4:23  4:31  4:4   4:48  4:56  4:64  5:2   7:134  89:0
10:57   116:0   13:64   1:8    207:18   226:0  250:0  2:8    3:14  3:9  4:16  4:24  4:32  4:40  4:49  4:57  4:65  7:0   7:135  89:1
10:58   116:16  13:65   189:0  2:1      2:3    252:0  2:9    3:15  4:0  4:17  4:25  4:33  4:41  4:5   4:58  4:66  7:1   7:2    89:2

/dev/disk:
by-id  by-partlabel  by-partuuid  by-path  by-uuid

/dev/dri:
by-path  card0

/dev/fd:
0  1  2  3

/dev/hugepages:

/dev/input:
by-id  by-path  event0  event1  event2  event3

/dev/mapper:
control

/dev/mqueue:

/dev/net:
tun

/dev/pts:
0  1  2  3  4  ptmx

/dev/shm:

/dev/snd:
by-path  controlC0  controlC1  pcmC0D0c  pcmC0D0p  pcmC1D0c  pcmC1D0p  timer

/dev/v4l:
by-path


















mendel@queen-xylophone:~$ cat /etc/os-release 
PRETTY_NAME="Mendel GNU/Linux 5 (Eagle)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.ai/"
SUPPORT_URL="https://coral.ai/"
BUG_REPORT_URL="https://coral.ai/"
VERSION_CODENAME="eagle"

**Comment by caijinana** [comment]
@manoj7410

**Comment by Namburger** [comment]
`/dev/apex_0` shows that the edgetpu is still present,
Next I'd check version of libedgetpu and the API that you're using, the 2 version must matches, other wise the ABI change between version can cause this issue.
```
$ dpkg -l | grep libedgetpu 
$ python3 -c 'print(__import__("pycoral").__version__)'
```

For reference, libedgetpu version 15.0 goes with pycoral 1.0.1:
```
{21-06-21 8:02}coder:~ nam% dpkg -l | grep libedgetpu
ii  libedgetpu-dev                             15.0                                amd64        Development files for libedgetpu
ii  libedgetpu1-max:amd64                      15.0                                amd64        Support library for Edge TPU
{21-06-21 8:03}coder:~ nam% python3 -c 'print(__import__("pycoral").__version__)'
1.0.1
```

**Comment by caijinana** [comment]
`mendel@queen-xylophone:~$ dpkg -l | grep edgetpu 
ii  edgetpudemo                          3-1                                 all          Edge TPU demo script
ii  libedgetpu1-std:arm64                15.0                                arm64        Support library for Edge TPU
ii  python3-edgetpuvision                7-1                                 arm64        EdgeTPU camera API
mendel@queen-xylophone:~$  python3 -c 'print(__import__("pycoral").__version__)'
1.0.0
`

**Comment by caijinana** [comment]
`
ii  edgetpudemo                          3-1                                 all          Edge TPU demo script
ii  libedgetpu1-std:arm64                15.0                                arm64        Support library for Edge TPU
ii  python3-edgetpuvision                7-1                                 arm64        EdgeTPU camera API
mendel@queen-xylophone:~$  python3 -c 'print(__import__("pycoral").__version__)'
1.0.0
`

**Comment by caijinana** [comment]
@manoj7410 @Namburger

**Comment by caijinana** [comment]
i have install the pycoral 1.01 but i still get the error
Internal: Unsupported data type in custom op handler: 0Node number 0 (edgetpu-custom-op) failed to prepare.
Failed to allocate tensors.

**Comment by manoj7410** [comment]
@caijinana  Can you install (via pip) https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.5.0-cp37-cp37m-linux_aarch64.whl (this link comes from https://www.tensorflow.org/lite/guide/python) 
Above link is for python3.7. You can install the compatible wheel from https://github.com/google-coral/pycoral/releases/

**Comment by caijinana** [comment]
i am a chinese student ,i can't connect to https://packages.cloud.google.com, i don't know what i should do
