### ISSUE TITLE
how to install edgetpu-compiler

### ISSUE THREAD

**Issue by caijinana** [google-coral/edgetpu#403]
i am a chinese student ,when i am try to do apt-get update, i am always met the error,The repository 'https://packages.cloud.google.com/apt coral-cloud-stable Release' does not have a Release file.,and i am also can't to install edgetpu-compiler,because i can't update

**Comment by hjonnala** [comment]
@caijinana
please try the below commands to install edgetpu-compiler:

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list

sudo apt-get update

sudo apt-get install edgetpu-compiler

requirements:
64-bit version of Debian 6.0 or higher, or any derivative thereof (such as Ubuntu 10.0+)
x86-64 system architecture

also refer to: https://coral.ai/docs/edgetpu/compiler/#system-requirements

**Comment by caijinana** [comment]
@hjonnala thank you very much , now i use web-based compiler using Google Colab. but i met another problem,i use the tensorflow 2.2,when i met the BN,i select jump the BN layer,but i met the following error: Model not quantized

**Comment by hjonnala** [comment]
@caijinana

please try this command:  
converter.experimental_new_converter = False

Reference:
https://github.com/google-coral/edgetpu/issues/168#issuecomment-656115637

if it's not working, please explain the steps  to reproduce the issue.

**Comment by caijinana** [comment]
i have one model passedgetpu-compiler,but i got the error:Mmap of 'test_data/converted_mlp-new_edgetpu.tflite' failed.

**Comment by caijinana** [comment]
@hjonnala

**Comment by hjonnala** [comment]
@caijinana can you please share your co lab notebook?

**Comment by caijinana** [comment]
Edge TPU Compiler version 15.0.340273435
Input: eval_graph3.tflite
Output: eval_graph3_edgetpu.tflite

Operator                       Count      Status

ADD                            4          Mapped to Edge TPU
RESHAPE                        2          Mapped to Edge TPU
MAX_POOL_2D                    2          Mapped to Edge TPU
DEPTHWISE_CONV_2D              1          Mapped to Edge TPU
MUL                            4          Mapped to Edge TPU
CONV_2D                        2          Mapped to Edge TPU
ARG_MAX                        1          Operation is working on an unsupported data type
FULLY_CONNECTED                2          Mapped to Edge TPU
@hjonnala

**Comment by hjonnala** [comment]
@caijinana  try adding the explicit path of the model rather than the directory where the model got saved.

reference: https://github.com/tensorflow/tensorflow/issues/40616

**Comment by caijinana** [comment]
i got the fllowing error:Operation is working on an unsupported data type，and edgetup_tflite is 0

**Comment by hjonnala** [comment]
If you don't mind please close this issue as it is not related to the original issue and create new issue with detailed error and the  the commands that you executed.

**Comment by hjonnala** [comment]
closing the issue as the original issue is resolved. And getting 0kb output issue can be found at https://github.com/google-coral/edgetpu/issues/409
