### ISSUE TITLE
How to run your EdgeTPU threaded example in camera loop

### ISSUE THREAD

**Issue by BernardinD** [google-coral/edgetpu#404]
Hi, 

We are using your template code for running [2 EdgeTPU in threads](https://github.com/google-coral/edgetpu/blob/master/src/cpp/examples/two_models_two_tpus_threaded.cc) and we're wondering if you have any suggestions on how to use this implementation with a camera loop. We are currently recreating  and joining the thread each iteration of the loop.

Thx in advance

**Comment by hjonnala** [comment]
@BernardinD can you please provide some more details on your implementation with a camera loop.
