### ISSUE TITLE
tflite convert to _edgetpu.tflite

### ISSUE THREAD

**Issue by caijinana** [google-coral/edgetpu#409]
Operator                       Count      Status

DEPTHWISE_CONV_2D              1          Mapped to Edge TPU
RESHAPE                        1          Mapped to Edge TPU
MAX_POOL_2D                    2          Mapped to Edge TPU
FULLY_CONNECTED                2          Mapped to Edge TPU
CONV_2D                        2          Mapped to Edge TPU
ARG_MAX                        1          Operation is working on an unsupported data type
and i got the .tflite file is 0kb

**Comment by hjonnala** [comment]
please share your input tflite and command executed.

**Comment by caijinana** [comment]
how to upload file?

**Comment by hjonnala** [comment]
Have it in google drive or any cloud based storage and share the link with us..

**Comment by caijinana** [comment]
i want to know, Operation is working on an unsupported data type,Does it affect the result?

**Comment by hjonnala** [comment]
please find the supported coral edgetpu operations https://coral.ai/docs/edgetpu/models-intro/#supported-operations . Any unsupported operation would run on  cpu instead of edgetpu processor.  No, it should not affect the result though the operation is mapped to cpu.

**Comment by caijinana** [comment]
May be it will cause the _edge.tflite file is 0kb?

**Comment by hjonnala** [comment]
yes, it might cause in getting 0kb output from edgetpu compiler.

**Comment by caijinana** [comment]
how to slove the edgetpu compiler unsupport arg.max()

**Comment by hjonnala** [comment]
To investigate further please share the model via attachment or email to coral-support@google.com. If they are any concerns regarding the model architecture, you can always send us fake architecture model as long as we can reproduce the same issue.

**Comment by hjonnala** [comment]
@caijinana are you still facing the issue?

**Comment by caijinana** [comment]
yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google-coral/edgetpu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月10日(星期六) 凌晨5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google-coral/edgetpu] tflite convert to _edgetpu.tflite (#409)





 
@caijinana are you still facing the issue?

**Comment by hjonnala** [comment]
Ok. Please share your uncompiled .tflite model.

**Comment by caijinana** [comment]
this is my convert code and the uncompiled .tflite model


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "google-coral/edgetpu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月10日(星期六) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google-coral/edgetpu] tflite convert to _edgetpu.tflite (#409)





 
Ok. Please share your uncompiled .tflite model.

**Comment by hjonnala** [comment]
Sorry, I don't find any attachments. Please resend them.

**Comment by caijinana** [comment]
ok this is my convert code and .tflite model


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google-coral/edgetpu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月10日(星期六) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google-coral/edgetpu] tflite convert to _edgetpu.tflite (#409)





 
Sorry, I don't find any attachments. Please resend them.

**Comment by caijinana** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google-coral/edgetpu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月10日(星期六) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google-coral/edgetpu] tflite convert to _edgetpu.tflite (#409)





 
Ok. Please share your uncompiled .tflite model.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

tflite.zip (4.06M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0761303304368c9a9b0d942c1e35014a5c5206010d060204150002030b1807530d031d520e020a485e0756570f0500500c050300383f33115e0d59475d1b490c48610d&t=exs_ftn_download&code=8a03853e

**Comment by hjonnala** [comment]
Hello,

I can see there is quantization problem for the tflite models. All the layers inputs/outputs of tflite need to be in int8 format.

please check these tutorial section **convert to TF Lite**
https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb#scrollTo=P0_StAtZwJ5p

aditional tutorials: https://github.com/google-coral/tutorials
model visualization tool: https://netron.app/

**Comment by caijinana** [comment]
my model is size is[1,784],but the image_classify.py need size_,width,heigh,_,and i don't know how to edit it
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google-coral/edgetpu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月12日(星期一) 中午11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google-coral/edgetpu] tflite convert to _edgetpu.tflite (#409)





 
Hello,
 
I can see there is quantization problem for the tflite models. All the layers inputs/outputs of tflite need to be in int8 format.
 
please check these tutorial section convert to TF Lite
 https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb#scrollTo=P0_StAtZwJ5p
 
aditional tutorials: https://github.com/google-coral/tutorials
 model visualization tool: https://netron.app/
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

XMLP_edgetpu.tflite (1.18M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7a633566cd1fd8c6910f917913330716540104565606040b1f545400061e01080a50185f00000314020201000c50500c0b500103352035617f2f65395057525c46134048415559504606355b&t=exs_ftn_download&code=2c5f5359

**Comment by hjonnala** [comment]
please change model input size when building model layers for training.

please refer to this tutorial section **Build the model**
https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb#scrollTo=P0_StAtZwJ5p

IMG_SHAPE = (IMAGE_SIZE, IMAGE_SIZE, 3)

**Comment by hjonnala** [comment]
@caijinana are you able to change the model input size?

**Comment by hjonnala** [comment]
Feel free to reopen if issue still exist.
