### ISSUE TITLE
Bench-marking at the op level

### ISSUE THREAD

**Issue by gitist** [google-coral/edgetpu#41]
Tensorflow lite provides benchmarking at the op level in their cpp example with --enable_op_profiling flag. 
How can this be done for models run on an edgetpu?

**Comment by Namburger** [comment]
@gitist The edgetpu lib currently only have a `get_inference_time` function that returns the inference time:
https://github.com/google-coral/edgetpu/blob/master/edgetpu/basic/basic_engine.py#L182
We also have some benchmarking scripts for references:
https://github.com/google-coral/edgetpu/tree/master/benchmarks

**Comment by jk78346** [comment]
How can we test the TOPS performance of edgetpu? According to this [table](https://coral.ai/docs/edgetpu/benchmarks/), the inference time are provided, however I didn't know how many ops they have for calculating TOPS. How do I know if my system actually runs at somewhere around 4TOPS as it claims?

**Comment by usbguru** [comment]
@jk78346 
There is no formal TOPs tool at this time.   To make a rough estimate, you can run an inference several times to measure the loading time vs. inference time.  Then compare that against the inference time of models with different sizes.  Use a neural network visualization tool to see how many operations of what size are done on the model, and you can estimate the number of operations that were executed in that inference time.  Each multiply and each add will count as a separate operation, and most TFlite instructions are dispatching huge numbers of multiply/add in parallel.   Give it a try.  Many people would be interested to see the results of your experiments.
