### ISSUE TITLE
tflite-runtime (2.5) needs GLIBC_2.29 with Python 3.8

### ISSUE THREAD

**Issue by brunovollmer** [google-coral/edgetpu#410]
Hey,

I'm not sure if this is the right place but I'm having problems with the tflite-runtime and python 3.8 on the coral dev board.
I've upgraded to python 3.8 due to some other requirements and installed tflite-runtime with version 2.5. 
Now when I try to import the runtime I get this error:
```
Python 3.8.0 (default, May 17 2021, 08:51:42) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflite_runtime.interpreter as tflite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mendel/env3.8/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 36, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/mendel/env3.8/lib/python3.8/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.cpython-38-aarch64-linux-gnu.so)
>>> 
```
Any suggestions how to fix this?

Bruno

**Comment by hjonnala** [comment]
@brunovollmer try this solution and let us know if it works or not.
https://forum.juce.com/t/solved-glibc-2-29-not-found-on-ubuntu-18-04/34960

**Comment by brunovollmer** [comment]
@hjonnala What exact solution do you mean? I'm not building tflite-runtime from source. I just installed it from the correct wheel. But might be that I'm missing something here

**Comment by brunovollmer** [comment]
I'm not building tflite-runtime from source. I just installed it from the correct wheel

**Comment by hjonnala** [comment]
@brunovollmer we have seen similar issue for others. They try to resolve the issue by lowering the python version to 3.6. As of now, we don't have solution for python 3.8.

**Comment by brunovollmer** [comment]
Due to some features I need python 3.8. Do you think that rebuilding it from source could solve the issue?

**Comment by gilescoope** [comment]
I'm having the same issue. I need both Python 3.8 (for multiprocessing with shared memory) and Tensorflow 2.5.0 (training with an RTX 30XX card).

**Comment by brunovollmer** [comment]
Any news/ideas on this?

**Comment by gilescoope** [comment]
The only solution I have is to train in Tensorflow 2.5, then copy the weights to a network built in Tensorflow 2.2 and convert and run on tflite_runtime 2.2. The interopability and support for newer Tensorflow versions with Coral hardware has been extremely disappointing to say the least.

**Comment by brunovollmer** [comment]
@hjonnala Is there no other way? Or anything planned on your side? I mean python 3.8 is not that new.

**Comment by brunovollmer** [comment]
So far I think the solution seems to be to built the tf lite wheel by yourself with the provided docker image. Will test if it works tomorrow.

**Comment by hjonnala** [comment]
Hello, @brunovollmer  @gilescoope  sorry for the delay. Yes, as you said built form wheel works.
wheels can be found here: https://github.com/google-coral/pycoral/releases
![Screenshot from 2021-07-09 09-51-39](https://user-images.githubusercontent.com/86132058/125111949-65f46400-e09b-11eb-8908-4b841272ddf0.png)

**Comment by brunovollmer** [comment]
I have been able to compile the tensorflow lite runtime with the provided docker image. Will test tomorrow if it solves the problem on the coral dev board!

**Comment by brunovollmer** [comment]
Sorry for the late reply. Everything works fine! Thanks for the help
