### ISSUE TITLE
Efficientdet-lite3 on TPU: compiler prints version and exits when using num_segments parameter

### ISSUE THREAD

**Issue by judahkshitij** [google-coral/edgetpu#411]
Hello,
   I am trying to compile an efficientdet-lite3 tflite model using TPU compiler but when using --num_segments or -n option, the compiler just prints the compiler version and exits without outputting anything. The command I am running is:

**edgetpu_compiler -s -n 2 int8-lite3.tflite**

I also tried commmand: **edgetpu_compiler int8-lite3.tflite --num_segments=2** but it did not help, same behavior. 

Can you please look into this and help me debug the issue?

Thanks!

**Comment by judahkshitij** [comment]
The int8-lite3.tflite model can be found [here](https://drive.google.com/drive/folders/1dig57pnZD5-XMB7nzF5NbiCk5eiKOx5X?usp=sharing)

**Comment by judahkshitij** [comment]
The only output I get from edge tpu compiler after running above command is:

**Edge TPU Compiler version 15.0.340273435**

**Comment by judahkshitij** [comment]
I also see similar behavior with int8-lite4.tflite model which is also located [here](https://drive.google.com/drive/folders/1dig57pnZD5-XMB7nzF5NbiCk5eiKOx5X?usp=sharing)

**Comment by judahkshitij** [comment]
Additional info: when I try to compile efficientdet-lite0, lite1 or lite2 models, i am able to compile successfully, although I dont get all operations mapped to TPU it seems.

**Comment by hjonnala** [comment]
Edgetpu compiler is not able to compile the given tflite models. If you remove -n 2, it can be observed error message: Internal compiler error. Aborting! . Ideally, you should be able to see same error message when used -n 2 also, so it is a bug in the code.

**Comment by judahkshitij** [comment]
Hello, thanks for the reply. While it is definitely a bug that the compiler did not output right error message when -n or --num_segments argument is passed to it, I think it is also a bug that the compiler is not able to compile Efficientdet-lite3 or lite 4 models, even when it is able to do so for lite0, lite1 and lite2. As per the this [tutorial](https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb) on training and running efficientdet lite models on TPU, lite3 and lite4 should be able to run on TPUs except we need to use model pipelining technique to run them on more than 1 TPUs. That is why I was trying to compile lite3 and lite4 using -n option but kept getting above behavior. 

Will it be also possible to look into why the compiler is not able to compile lite3 and lite4 models even with -n argument? Thanks so much.

**Comment by edumotya** [comment]
I have the same issue when compiling Efficientdet-lite2 with -n greater than 1. On the other, for -n equals 1 it works smoothly.

### 1 segment

I get the files model_edgetpu.tflite and model.tflite, and the following output for 1 segment:

```
$ edgetpu_compiler -n 1 model.tflite

Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 10471 ms.

Input model: model.tflite
Input size: 7.04MiB
Output model: model_edgetpu.tflite
Output size: 9.43MiB
On-chip memory used for caching model parameters: 7.26MiB
On-chip memory remaining for caching model parameters: 768.00B
Off-chip memory used for streaming uncached model parameters: 168.81KiB
Number of Edge TPU subgraphs: 1
Total number of operations: 357
Operation log: model_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 351
Number of operations that will run on CPU: 6
See the operation log file for individual operation details.
```
### 2 segments

I do not get any files, and the following output for 2 segments:
```
$ edgetpu_compiler -n 2 model.tflite

Edge TPU Compiler version 15.0.340273435
```

### 3 or more segments

I do not get any files, and the following output for 3 or more segments:
```
$ edgetpu_compiler -n 3 model.tflite

Edge TPU Compiler version 15.0.340273435
Warning: For the given model, you're creating more segmentsthan is necessary, which can increase inference latency.We instead recommend num_segments = 2
```

**Comment by hjonnala** [comment]
Issue got fixed in new edgetpu runtime release version.

![image](https://user-images.githubusercontent.com/86132058/127542445-fc309f21-685e-408a-8182-3c9bc9c2057f.png)
