### ISSUE TITLE
Failed to compile quantized model

### ISSUE THREAD

**Issue by dentigo** [google-coral/edgetpu#412]
Hi, I am trying to convert a frozen graph to a quantized model which is able to run on edge tpu.
And I tried several configurations, however, none of them worked.
Here are the details:

with tensorflow < 2.4.0:
unable to quantize

with tensorflow 2.4.0:
unable to quantize

error log:
```
Traceback (most recent call last):
  File "opt.py", line 20, in <module>
    tflite_quant_model = converter.convert()
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1947, in convert
    return super(TFLiteConverter, self).convert()
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1313, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 461, in _calibrate_quantize_model
    inference_output_type, allow_float, activations_type)
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 104, in calibrate_and_quantize
    np.dtype(activations_type.as_numpy_dtype()).num)
RuntimeError: Quantization not yet supported for op: 'SQRT'.
Quantization not yet supported for op: 'DIV'.
Quantization not yet supported for op: 'SQUARED_DIFFERENCE'.
Quantization not yet supported for op: 'DIV'.
Quantization not yet supported for op: 'DIV'.
Quantization not yet supported for op: 'DIV'.
Quantization not yet supported for op: 'DIV'.
Quantization not yet supported for op: 'DIV'.
Quantization not yet supported for op: 'DIV'.
Quantization not yet supported for op: 'DIV'.
Quantization not yet supported for op: 'DIV'.
```

with tensorflow 2.5.0 : 

able to quantize
unable to compile

error log:
```
Edge TPU Compiler version 15.0.340273435
Invalid model: tensorflow-2.5.0.tflite
Model not quantized
```

with tf-nightly-2.6.0.dev20210507:

able to quantize
unable to compile

error log:
```
Edge TPU Compiler version 15.0.340273435
Invalid model: tf-nightly-2.6.0.dev20210507.tflite
Model not quantized
```

with tf-nightly-2.7.0.dev20210705:

able to quantize
unable to compile
but the error log is slightly different.

```
Edge TPU Compiler version 15.0.340273435
ERROR: Didn't find op for builtin opcode 'SQUARED_DIFFERENCE' version '2'

ERROR: Registration failed.

Invalid model: tf-nightly-2.7.0.dev20210705.tflite
Model could not be parsed
```

And here are the frozen pb model, quantized models, and conversion script. Thanks
https://drive.google.com/file/d/1EDmfcATV6_37BO1NTpKU7lnX5fxCJ9NL/view?usp=sharing

**Comment by hjonnala** [comment]
@dentigo can you share your saved model? 

try to convert using one of the methods below:

1. tf.lite.TFLiteConverter.from_saved_model() (recommended): Converts a SavedModel.

2. tf.lite.TFLiteConverter.from_keras_model(): Converts a Keras model.

instead of tf.compat.v1.lite.TFLiteConverter.from_frozen_graph  method.

Reference: https://www.tensorflow.org/lite/convert

**Comment by dentigo** [comment]
> @dentigo can you share your saved model?
> 
> try to convert using one of the methods below:
> 
> 1. tf.lite.TFLiteConverter.from_saved_model() (recommended): Converts a SavedModel.
> 2. tf.lite.TFLiteConverter.from_keras_model(): Converts a Keras model.
> 
> instead of tf.compat.v1.lite.TFLiteConverter.from_frozen_graph method.
> 
> Reference: https://www.tensorflow.org/lite/convert

Actually, its a tensorflow 1.x model which can be only converted from frozen graph/session/saved_model (tf1 version).

**Comment by hjonnala** [comment]
@dentigo have you tried using tf1.x saved_model?

**Comment by hjonnala** [comment]
@dentigo please try with the new compiler. I am able to compile the tflite files with new compiler.
![image](https://user-images.githubusercontent.com/86132058/127709004-64f8a366-5a9c-4c60-aad5-9c74d216977a.png)
