### ISSUE TITLE
EfficientDet-lite3x Error: transfer on tag 1 failed. Abort. Deadline exceeded: USB transfer error 2

### ISSUE THREAD

**Issue by NobuoTsukamoto** [google-coral/edgetpu#413]
### System information
- Raspberry Pi 4 Model B Rev 1.2 4GB
- Coral USB Accelerator
- Raspberry Pi OS 32bit (Release date: May 7th 2021)
- libedgetpu version 15.0
- tensorflow lite 2.5.0

### Describe the current behavior
The following error occurs on the Edge TPU model of EfficientDet-lite3x.
```
F :859] transfer on tag 1 failed. Abort. Deadline exceeded: USB transfer error 2 [LibUsbDataOutCallback]
```
From the #11 and #70 issues, I thought it was a power problem and used a self-powered USB hub, but I get an error. libedgetpu1-std also gives the same error.
When an error occurs, the Coral USB Accelerator LED will stay blinking.

It occurs on EfficientDet-lite3x and not on EfficientDet-lite0, EfficientDet-lite1 and EfficientDet-lite2 models.
(EfficientDet-lite3 and EfficientDet-lite4 fail to convert Edge TPU model.)

The model is converted to a TensorFlow Lite model using the checkpoints published on [google/automl](https://github.com/google/automl/tree/master/efficientdet).

**Comment by manoj7410** [comment]
I would suggest you to change the log_level of libedgetpu at https://github.com/google-coral/libedgetpu/blob/master/port/default/port_from_tf/logging.cc#L171 and then rebuild this library by following the instructions given at https://github.com/google-coral/libedgetpu#building.

You can set the log_level value from 1 to 10 (10 being the most detailed) to get the detailed output of libedgetpu and then we can understand where exactly it is failing.

**Comment by NobuoTsukamoto** [comment]
@manoj7410 
Thank you for the information. The log when the `log_level` is set to 10 is attached.
It seems that the `LIBUSB_TRANSFER_TIMED_OUT` error is occurring repeatedly.

[error.txt](https://github.com/google-coral/edgetpu/files/6784282/error.txt)

**Comment by manoj7410** [comment]
> It occurs on EfficientDet-lite3x and not on EfficientDet-lite0, EfficientDet-lite1 and EfficientDet-lite2 models.
> (EfficientDet-lite3 and EfficientDet-lite4 fail to convert Edge TPU model.)
> 
> The model is converted to a TensorFlow Lite model using the checkpoints published on [google/automl](https://github.com/google/automl/tree/master/efficientdet).

The error that you are seeing is with a non-edgeTPU model or with an edgeTPU model ?
And does the inference run even once or it straight away gives the error?

**Comment by NobuoTsukamoto** [comment]
> The error that you are seeing is with a non-edgeTPU model or with an edgeTPU model ?

- It's Edge TPU Model (Edge TPU delegate).
- I am using the model converted in this notebook.  
  https://gist.github.com/NobuoTsukamoto/c47ed552c412db4dbfac97a8568f17f0
- The model used is as follows. EfficientDet-All models from Lite0 to Lite4 (FP32, FP16, INT8, Edge TPU) are available.   
  I am using efficientdet-lite3x_int8_edgetpu.tflite.
  https://drive.google.com/file/d/1h9jRfps3U_pskP2gtJB9ox5XbYqXHcSg/view?usp=sharing

> And does the inference run even once or it straight away gives the error?

it straight away gives the error.

**Comment by 35grain** [comment]
Facing the same issue with a custom YOLOv7 tiny model on a Raspberry Pi 4 Model B.
