### ISSUE TITLE
ModuleNotFoundError: No module named 'pycoral'

### ISSUE THREAD

**Issue by AkkiSony** [google-coral/edgetpu#415]
I am new to coral, and hence, I started to follow the official guidelines from https://coral.ai/docs/accelerator/get-started/#3-run-a-model-on-the-edge-tpu . I am getting an error as shown below. 

**(myvirtenv) learningtime@learningtime:~/coral-tpu/coral/pycoral1$ python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
Traceback (most recent call last):
  File "examples/classify_image.py", line 36, in <module>
    from pycoral.adapters import classify
ModuleNotFoundError: No module named 'pycoral**

Please help me solve this issue!

**Comment by manoj7410** [comment]
Please share the output of :

python3 --version

**Comment by hjonnala** [comment]
Hello, have you tried these steps: https://coral.ai/docs/accelerator/get-started/#2-install-the-pycoral-library

**Comment by AkkiSony** [comment]
@manoj7410  Python 3.6.9

**Comment by AkkiSony** [comment]
@hjonnala Yes, I followed all the steps mentioned. 
I even checked if pycoral is installed. 

When I did, "pycoral.__version__" , I got an output of '1.0.1'

**Comment by hjonnala** [comment]
can you try renaming pycoral1 to pycoral inside coral directory

**Comment by AkkiSony** [comment]
@hjonnala I tried it, yet could'nt solve the issue. 

(myvirtenv) learningtime@learningtime:~/coral-tpu/coral/pycoral$ python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
Traceback (most recent call last):
  File "examples/classify_image.py", line 36, in <module>
    from pycoral.adapters import classify
ModuleNotFoundError: No module named 'pycoral'

**Comment by hjonnala** [comment]
It seems virtual environment not able to recognize ..coral/pycoral/pycoral folder.. 

in classify_image.py  try adding these lines before import argparse:

import sys
sys.path.append(path of your coral directory)

**Comment by AkkiSony** [comment]
I added this in the classify_image.py file

**import sys
sys.path.append('/home/learningtime/coral-tpu/coral')**

Yet, I did not resolve the issue.

But, when I added the path to pycorla folder, like shown below:
**import sys
sys.path.append('/home/learningtime/coral-tpu/coral/pycoral')**

I am getting another new error.
**(myvirtenv) learningtime@learningtime:~/coral-tpu/coral/pycoral$ python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
Traceback (most recent call last):
  File "examples/classify_image.py", line 41, in <module>
    from pycoral.utils.edgetpu import make_interpreter
  File "/home/learningtime/coral-tpu/coral/pycoral/pycoral/utils/edgetpu.py", line 24, in <module>
    from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
ModuleNotFoundError: No module named 'pycoral.pybind'**

**Comment by hjonnala** [comment]
Please check if you have pybind folder inside  ../lib/site-packages/pycoral..

if you have adpaters, learn, pipeline and utils folders also in this folder try replace 

sys.path.append('/home/learningtime/coral-tpu/coral/pycoral')
with
sys.path.append(path to site-packages/pycoral)

**Comment by AkkiSony** [comment]
I cannot find this folder -  ../lib/site-packages/pycoral..
Can you please tell  me where is it located exactly, please??

**Comment by hjonnala** [comment]
Open python shell try the below snippet commands in results look for item which has site-packages (This is the place third party libraries would get installed in general): try both in virtual environment without virtual environment.
I guess pycoral installed outside virtual environment

```
import sys
sys.path
```
![Screenshot from 2021-07-09 05-16-00](https://user-images.githubusercontent.com/86132058/125076605-f8354180-e074-11eb-913d-d6fcdc197a3c.png)

**Comment by AkkiSony** [comment]
I tried the command inside and outside the environment. But I did not find the pycoral in both of them :/ 
I tried installing pycoral again, but it is already installed.

**(myvirtenv) learningtime@learningtime:~$ sudo apt-get install python3-pycoral
[sudo] password for learningtime: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pycoral is already the newest version (1.0.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.**

Please find the image outside virtual environment
![Pycoral-outside-env](https://user-images.githubusercontent.com/85996229/125086945-5fcaab80-e0cc-11eb-95f2-a10e7325bb48.PNG)

Please find the image inside virtual environment.
![Pycoral-inside-env](https://user-images.githubusercontent.com/85996229/125087011-6eb15e00-e0cc-11eb-88c8-72a20a8a67a5.PNG)

**Comment by hjonnala** [comment]
please confirm, you are using LINUX OS.

**Comment by AkkiSony** [comment]
I am working on PC - Virtal Machine - Ubuntu 18.04

**Comment by hjonnala** [comment]
what is your native OS? can you try on native OS once?

**Comment by AkkiSony** [comment]
Native is Windows. But, my requirement is to work on Ubuntu. Why would it not work on VM?

**Comment by hjonnala** [comment]
@AkkiSony please try to install using pip instead of sudo and try the code.

`python3 -m pip install --index-url https://google-coral.github.io/py-repo/ --extra-index-url=https://pypi.python.org/simple pycoral`

**Comment by hjonnala** [comment]
Unfortunately, we don't have official support for issues with edge devices on Virtual Machines as  errors on Virtual Machines are unpredictable and are out of our control. But, some users are successful in using edge devices on virtual machines.
