### ISSUE TITLE
Pipeline with flexible control of model segmentation [followed tutorial so we tried TOCO but does not work]

### ISSUE THREAD

**Issue by ycunxi** [google-coral/edgetpu#418]
[Test platform = USB Accelerator]
[EdgeTPU Compiler version = 15]

We are interested in pipeline the model using our own segmentation, instead of using EdgeTPU compiler with argument -n.

Specifically, we followed tutorial on https://coral.ai/docs/edgetpu/pipeline/#segment-a-model, where it indicates that "If you want complete control of where each segment is cut, you can instead manually cut your model into separate .tflite files using the TensorFlow toco_convert tool." 

Here is the flow we used:
1) Split a model into two using toco oncvert, namely model0 and model1, so {model0 -> model1} is the complete model.
2) compile model0 and model1 using EdgeTPU compiler, e.g., edgetpu_compiler model0.tflite; edgetpu_compiler model1.tflite; 
3) using model_pipelining_classify_image.py to load model0_edgetpu.tflite and model1_edgetpu.tflite as the two model segmentations for inference. It does not work. 
    for step 3), we confirmed that the two models generated using edgetpu_compiler -n 2 model.tflite works fine.

Can you please confirm whether our flow is correct? if not, what is the walk around solution to correctly use customized segmentation for pipeline.

**Comment by hjonnala** [comment]
Please try changing the file names to model_segment_1_of_2_edgetpu.tflite and model_segment_2_of_2_edgetpu.tflite. I mean the same way edgetpu_compiler -n 2 model.tflite  generate names. 

If it doesn't work please share the detail error message.

**Comment by ycunxi** [comment]
Please find the specific steps we performed below. 

1. We split the inceptionV3 model into one frozen graph 
2. Using toco converter to split it into two models and the two models are quantized using post-training quantization simultaneously. Then the models are saved in tflite format.
3. Compile the two tflite files using edge-tpu compiler.
4. Names are changed accordingly ( inception_v3_299_quant_segment_%d_of_2_edgetpu.tflite )
5. Execute the file model_pipelining_classify_image.py. See the execution log below.

====bug information starts here=======
**python3 examples/model_pipelining_classify_image.py   --models     test_data/pipeline/inception_v3_299_quant_segment_%d_of_2_edgetpu.tflite   --labels test_data/imagenet_labels.txt   --input test_data/parrot.jpg**
_Using devices:  ['usb:0', 'usb:1']
Using models:  ['test_data/pipeline/inception_v3_299_quant_segment_0_of_2_edgetpu.tflite', 'test_data/pipeline/inception_v3_299_quant_segment_1_of_2_edgetpu.tflite']
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20210713 14:07:19.849251 147741 pipelined_model_runner.cc:139] Thread: 140683673806592 receives empty request
I20210713 14:07:19.849268 147741 pipelined_model_runner.cc:198] Thread: 140683673806592 is shutting down the pipeline...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/jiaqi/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/jiaqi/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "examples/model_pipelining_classify_image.py", line 143, in consumer
    classes = classify.get_classes_from_scores(scores, args.top_k,
  File "/home/jiaqi/anaconda3/lib/python3.8/site-packages/pycoral/adapters/classify.py", line 84, in get_classes_from_scores
    classes = [
  File "/home/jiaqi/anaconda3/lib/python3.8/site-packages/pycoral/adapters/classify.py", line 87, in <listcomp>
    if scores[i] >= score_threshold
IndexError: index 5 is out of bounds for axis 0 with size 5
I20210713 14:07:20.063083 147741 pipelined_model_runner.cc:208] Thread: 140683673806592 Pipeline is off.
Average inference time (over 5 iterations): 42.9ms
I20210713 14:07:20.063266 147698 pipelined_model_runner.cc:139] Thread: 140684461700928 receives empty request
I20210713 14:07:20.063277 147698 pipelined_model_runner.cc:193] Thread: 140684461700928 Pipeline was turned off before.
WARNING: 4 unconsumed results in the pipeline during destruction!
I20210713 14:07:20.063334 147698 pipelined_model_runner.cc:193] Thread: 140684461700928 Pipeline was turned off before._

**Comment by hjonnala** [comment]
Please cross check output tensors with the edgetpu compiled models when passing -n 2 to versus TOCO generated indivdual compiled modes.

**Comment by hjonnala** [comment]
@ycunxi are you able to cross check the output tensors and fix the issue?

**Comment by ycunxi** [comment]
> @ycunxi are you able to cross check the output tensors and fix the issue?

thanks for following up. we have not checked the output tensors yet. we found that a certain models (included on CORAL website/github) have this issue, but simple models work fine (e.g., a simple 5-layer CNN). We also find that even this thread error (looks like the error comes from collecting output of the inference) does not stop the inference.  We will take a look at the output tensors.

**Comment by hjonnala** [comment]
can you please share the models that are not working, so that I can test them with new release versions.

Thanks

**Comment by ycunxi** [comment]
> can you please share the models that are not working, so that I can test them with new release versions.
> 
> Thanks

My student has prepared an example using MobileNetV2 (_model=tf.keras.applications.MobileNetV2(input_shape=IMG_SHAPE,include_top=False,weights='imagenet')_
). EdgeTPU itself can do it in 2-stage pipelining without any problem. 

We have prepared the models that are split into 2-stage using **toco** in this google drive (see a zip file), including original model (.pb), original model frozen graph (.pb), quantized and the split sub-models (tflite), and edgetpu compiled version of the two split sub-models. The edgeTPU compilation logs are included as well.
[mobilenetv2_split_pipeline_test.zip](https://github.com/google-coral/edgetpu/files/6897071/mobilenetv2_split_pipeline_test.zip)


BTW, here is the split point. 

segment0 input:{'Input_0': [None, 224, 224, 3]}
segment0 output:{'model_0_mobilenetv2_1.00_224/model_0_block_14_add/add': [None, 7, 7, 160]}
segment1 input:{'ipt': {'model_0_mobilenetv2_1.00_224/model_0_block_14_add/add': [None, 7, 7, 160]}
segment1 output:{'Identity': [None, 7, 7, 1280]}

**Comment by hjonnala** [comment]
HI, the code is breaking due to your output shape is not matching with expected output shape array.

example output shape:  array([   1, 1001], dtype=int32)

**Comment by hjonnala** [comment]
@ycunxi are you still having the issue?

**Comment by ycunxi** [comment]
> @ycunxi are you still having the issue?

@hjonnala thanks for following up. Yes the error is caused at the output layer. We have fixed that problem.

Another question, we find another limitation of existing TOCO+EdgeTPU compilation. It looks like the depended operators in the DNN execution graph have to be pipelined in two consecutive pipeline stages. For example, if node A's output is used for B and A is allocated at stage 1, B cannot be allocated at stage 3 and beyond. Is this a correct understanding for current edgeTPU setups? Thanks!

**Comment by hjonnala** [comment]
@ycunxi  yes, your understanding is correct. All the chunks need to pass in the same order.
