### ISSUE TITLE
Internal compiler error. Aborting!  with edgetpu_compiler

### ISSUE THREAD

**Issue by akanksharma** [google-coral/edgetpu#419]
We are getting the below mentioned error with  one of our quant models created with TF2.4.

```
# edgetpu_compiler ufs_128_quant.tflite
Edge TPU Compiler version 14.1.317412892

Internal compiler error. Aborting! 
```
We have tried to reduce the model size to around 5 MB only but the issue still exists.
We are however able to compile all other models except this one.
Unfortunately there are no logs available.

Any help to solve this issues is appreciated.

There is one more similar issue created about this but not sure if the actual cause is same.
https://github.com/google-coral/edgetpu/issues/189

Thanks in advance.

**Comment by hjonnala** [comment]
please try using new compiler version. If it won't work, please share the ufs_128_quant.tflite model.

**Comment by akanksharma** [comment]
I tried to upgrade but still I am getting the same error


[ufs_128_quant.tflite.zip](https://github.com/google-coral/edgetpu/files/6816412/ufs_128_quant.tflite.zip)

```
# edgetpu_compiler ufs_128_quant.tflite
Edge TPU Compiler version 15.0.340273435

Internal compiler error. Aborting!
```

Attached the quant model here.

**Comment by hjonnala** [comment]
The compiler is failing as there are  too many of transpose ops which are not supported. 

You can use https://netron.app/ to visualize the models.

please check all supported operations here: https://coral.ai/docs/edgetpu/models-intro/#supported-operations

**Comment by letdivedeep** [comment]
Hi @hjonnala 

I am trying to convert PyTorch model to tflite using this pipeline :
`Pytorch -> onnx -> saved_model -> tflite`

As we know Pytorch format is (NCHW) and the PB from is (NHWC), so when we convert using onnx2tf it adds lots of transpose to handle this 

do we have an alternative way to avoid it and make it run on edge tpu

**Comment by hjonnala** [comment]
@letdivedeep switching the model architecture might resolve the issue. 
Transpose operation could be supported be in future releases.

**Comment by hjonnala** [comment]
@ akanksharma are you able to modify the model that can compiled with edgetpu compiler?

**Comment by letdivedeep** [comment]
@hjonnala 

we were able to resolve the issue by having a workaround with openvino2tensorflow :

Pytorch -> onnx -> openViNO -> edge_tpu

https://github.com/PINTO0309/openvino2tensorflow

blog: https://qiita.com/PINTO/items/ed06e03eb5c007c2e102

**Comment by hjonnala** [comment]
@letdivedeep Thanks for sharing the workaround links.

**Comment by taloot** [comment]
> @hjonnala
> 
> we were able to resolve the issue by having a workaround with openvino2tensorflow :
> 
> Pytorch -> onnx -> openViNO -> edge_tpu
> 
> https://github.com/PINTO0309/openvino2tensorflow
> 
> blog: https://qiita.com/PINTO/items/ed06e03eb5c007c2e102

i try it but didnt work it gave me error
it give this error
 line 520, in _quantize
    return _mlir_quantize(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 218, in wrapper
    raise error from None  # Re-throws the exception.
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 208, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py", line 236, in mlir_quantize
    return wrap_toco.wrapped_experimental_mlir_quantize(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/wrap_toco.py", line 47, in wrapped_experimental_mlir_quantize
    return _pywrap_toco_api.ExperimentalMlirQuantizeModel(
RuntimeError: Failed to quantize:
