### ISSUE TITLE
Simpler model runs slower on edgetpu than a complex one

### ISSUE THREAD

**Issue by Drulludanni** [google-coral/edgetpu#424]
So, I'm quite stumped by this. So I had this model that I compiled for the edge tpu that runs an inference in about 0.017 seconds which is a tiny bit slow for me so I decided to simplify the model a little bit and I did this by reducing the number of filters in some convolutional layers, however after doing that the model takes 0.034 seconds which is 2x slower than before which doesn't really make any sense since the tflite versions of these two models run in 8 seconds and 5 seconds respectively which matches the changes I made. So somehow after compiling to the edgetpu the faster model becomes slower even though the architecture is the exact same with just fewer convolutional kernels in certain layers.

is there any logical explanation to this? I did some changes to the data like augmentations and such between the training of the networks but that shouldn't have any effect on the inference time as far as I'm aware.

I've added the 2 network architectures here to show that they are the exact same:
[small.txt](https://github.com/google-coral/edgetpu/files/6855041/small.txt)
[large.txt](https://github.com/google-coral/edgetpu/files/6855043/large.txt)

Edit: I retrained the large network with the exact same data and values as the small network and I'm getting the same result (0.017 inference time), I also trained an intermediate network that is halfway between the two and it is the slowest network of them all with an inference time of about 0.037

**Comment by hjonnala** [comment]
can you share your edgeptu compilation logs.

**Comment by Drulludanni** [comment]
sure, but they seem identical.
[large model](https://github.com/google-coral/edgetpu/files/6863469/test_unet-5ch-extradata-gauss-shuffled-1626868003_edgetpu.log)
[small model](https://github.com/google-coral/edgetpu/files/6863482/test_unet-5ch-extradata-gauss-shuffled-1626874190_edgetpu.log)

the only difference I see is in which order the operations are listed.

**Comment by hjonnala** [comment]
Thanks for sharing logs. 
Which coral device you are using to run the edgetpu inference?
If possible, please share the edgeptu models, uncompiled tflite models and examples to run to test the speed on my machine.

**Comment by Drulludanni** [comment]
Hi, I'm using the coral usb accelerator.

github wouldn't allow me to upload the files so I put them in this google drive: https://drive.google.com/drive/folders/1-u9GpNwRdbCAxtaMuAdDZazMWqeMIt_n

So, I'm not sure about my company's policy on sharing the models online so I made new basically untrained ones, however this small model seems faster than the trained one (only on the edgetpu, uncompiled model is exactly as fast). However it is still slower than the large one, the large one is exactly as fast as the trained one.

**Comment by hjonnala** [comment]
HI, Thanks for sharing models. I don't see much difference in inference time.
```

from pycoral.utils import edgetpu
import numpy as np
import time
import pandas as pd
models = ['large.tflite', 'small.tflite', 'large_edgetpu.tflite', 'small_edgetpu.tflite']

for model_path in models:
    print(model_path)
    interpreter = edgetpu.make_interpreter(model_path)
    interpreter.allocate_tensors()
    input_index = interpreter.get_input_details()[0]['index']
    output_index = interpreter.get_output_details()[0]['index']


    n_trials = 10
    total = 0
    x = np.zeros((1,256,256,3), dtype=np.uint8)

    # first call is usually slower so we skip it
    interpreter.set_tensor(input_index, x)
    interpreter.invoke()
    pred = interpreter.get_tensor(output_index)

    for i in range(n_trials):
        t =  time.perf_counter()
        interpreter.set_tensor(input_index, x)
        interpreter.invoke()
        pred = interpreter.get_tensor(output_index)
        delta =  time.perf_counter() - t
        print(delta)

        total += delta




    print("inference time:", total/n_trials)
```
large.tflite
0.1496358060030616
0.1485976780022611
0.1483854780017282
0.15367160199821228
0.14959113300574245
0.15088106799521483
0.15082832500047516
0.15193483600160107
0.15003243799583288
0.15038035700126784
inference time: 0.15039387210053973
small.tflite
0.11584167899854947
0.11599051600205712
0.11696850499720313
0.11443567500100471
0.11590510300447932
0.1147987629956333
0.11512054599734256
0.11563513799774228
0.11606638100056443
0.11551987900020322
inference time: 0.11562821849947795
large_edgetpu.tflite
0.010911001001659315
0.010716911994677503
0.01873325600172393
0.017669872999249492
0.011651765002170578
0.011231248994590715
0.01134348199411761
0.010859904999961145
0.011784821006585844
0.01084906199685065
inference time: 0.012575132599158679
small_edgetpu.tflite
0.012417456004186533
0.012403412998537533
0.01249544899474131
0.012908242002595216
0.012727078996249475
0.012460101999749895
0.013034809999226127
0.012755141993693542
0.01266762700106483
0.012434271993697621
inference time: 0.012630359198374208

**Comment by Drulludanni** [comment]
yeah, but what I don't get is why the smaller model runs slower than the larger one 😅 because the intention with the smaller model was to improve the speed, not make it worse. Because the smaller one has strictly fewer operations so I don't understand how it can possibly be slower. (note that the larger model is generally a bit faster except in the 2 seeming outliers that take 0.017 and 0.018)

**Comment by hjonnala** [comment]
Actually, there is no change in number of operations, which are 59 in both cases.

![image](https://user-images.githubusercontent.com/86132058/126898292-4b14367e-d22c-4142-a199-531c67d7fef5.png)

**Comment by Drulludanni** [comment]
yeah I know, but some of the convolution operations are twice as small in terms of the number of filters (and this is has a noticeable difference in performance on the uncompiled models) Why does the same not remain true for the compiled models?

**Comment by hjonnala** [comment]
The time difference coming from interpreter.invoke() line from this script ../lib/python3.8/site-packages/tflite_runtime/interpreter.py

**please check with tensor flow team** why `self._interpreter = (
          _interpreter_wrapper.CreateWrapperFromFile(
              model_path, custom_op_registerers_by_name,
              custom_op_registerers_by_func))`  line taking more time for small_edgetpu.tflite compared to large_edgetpu.tflite.

Additinal info : custom_op_registerers_by_name and  custom_op_registerers_by_func are empty lists in both cases.

![large_vs_small](https://user-images.githubusercontent.com/86132058/126919463-79e10a6c-fdda-488e-9965-db70ab319a85.jpg)


Thanks.

**Comment by hjonnala** [comment]
Hi, I have test for 1000 trails with new [release](https://coral.ai/software/#pycoral-api) versions of tflite_runtime and pycoral. With these smaller model performing better than large model.

![image](https://user-images.githubusercontent.com/86132058/127705254-01ad7dcd-5379-4fb2-b8a4-94eb93fc96c2.png)

**Comment by Drulludanni** [comment]
Oh, thanks for notifying me, I won't be able to take a look at it until Tuesday unfortunately, but if it works then I'll report back and close the issue.

**Comment by Drulludanni** [comment]
so, I ran the small model compiled with the new and old compiler and it turns out the new compiler yields a slower model which is the opposite of what I had hoped 😅

small_new_edgetpu.tflite
0.08563881000736728
0.08766582497628406
0.08628141297958791
0.08632072003092617
0.08548570895800367
0.08619482401991263
0.08511019399156794
0.08478117501363158
0.08991771098226309
0.08939678798196837
inference time: 0.08667931689415127

small_old_edgetpu.tflite
0.053022156993392855
0.053992910019587725
0.05386444297619164
0.0528649149928242
0.05276815500110388
0.052895523025654256
0.05274435499450192
0.052497925993520766
0.05312599800527096
0.05276688700541854
inference time: 0.05305432690074667

on another note: I seem to be unable to run the new model on my windows machine. It won't run unless I have edgetpu runtime 14, but whenever I try to install it I end up with the following error when running the code:

```
Traceback (most recent call last):
  File "C:\Users\Drulludanni\anaconda3\envs\tf37\lib\site-packages\tflite_runtime\interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "C:\Users\Drulludanni\anaconda3\envs\tf37\lib\site-packages\tflite_runtime\interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Drulludanni/Desktop/ht_training/training/evaluate_speed.py", line 9, in <module>
    interpreter = edgetpu.make_interpreter(model_path)
  File "C:\Users\Drulludanni\anaconda3\envs\tf37\lib\site-packages\pycoral\utils\edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "C:\Users\Drulludanni\anaconda3\envs\tf37\lib\site-packages\pycoral\utils\edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "C:\Users\Drulludanni\anaconda3\envs\tf37\lib\site-packages\tflite_runtime\interpreter.py", line 163, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from edgetpu.dll


Process finished with exit code 1
```

edit: it seems that UsbDk_1.0.22_x64.msi was not being installed properly, by manually installing it the code runs a bit more, however it crashes with exit code -1073741819 (0xC0000005) instead

**Comment by hjonnala** [comment]
Hi, I haven't test the same small model that is compiled with different versions. 

Regarding this error ValueError: Failed to load delegate from edgetpu.dll.. Could you please try with edgetpu_runtime_20210119.zip from this page https://coral.ai/software/#edgetpu-runtime

**Comment by Drulludanni** [comment]
yeah, edgetpu_runtime_20210119.zip is the one I was using before and that works fine, but it can't run the model compiled with the newest edgetpu_compiler cause it requires runtime version 14.

**Comment by hjonnala** [comment]
I am also facing issues with edgetpu runtime version 14 on windows. Will check with internal team on this issue.

**Comment by Drulludanni** [comment]
Any word from the internal team?

**Comment by hjonnala** [comment]
Hi, I don't have any updates regarding edgetpu runtime 14 on windows.

I think, you already know the workarounds for now are either compiling the models by specifying -m flag for edgetpu compiler 13 or work with coral dev board or with different operating system.

**Comment by hjonnala** [comment]
HI, regarding same model inference time with different version of edgeptu compiler, it is possible to get more inference time when compared to previous versions. As new compiler changes mostly focus on improving the accuracy for the existing operations and adding more support to additional operations.

**Comment by Drulludanni** [comment]
hmm, ok that is unfortunate for me 😅

**Comment by hjonnala** [comment]
Hi, are there any questions regarding small model vs large model. If not, please close the ticket.
