### ISSUE TITLE
RuntimeError: InvokeWithMemBuffer failed: Regular TensorFlow ops are not supported by this interpreter

### ISSUE THREAD

**Issue by ting3000** [google-coral/edgetpu#425]
Running inference on Coral Dev Board with the re-trained ssd_mobilenet_v2_320x320_coco17_tpu-8 model, I get "RuntimeError: InvokeWithMemBuffer failed: Regular TensorFlow ops are not supported by this interpreter" when running inference with the re-trained ssd_mobilenet_v2_320x320_coco17_tpu-8 model.

Here is the steps that I build this model, is something I missed? Thanks!
1. I trained the model with TensorFlow 2.5 from the pretrained model ssd_mobilenet_v2_320x320_coco17_tpu-8.
2. Then exported model to the SavedModel with exporter_main_v2.py.
3. Convert the SavedModel to tflite with the options
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
4. When I run inference with this tflite model on the Coral Dev Board, I get this error:
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 181, in run_inference
    expected_input_size)
RuntimeError: InvokeWithMemBuffer failed: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 11 (FlexStridedSlice) failed to prepare.
Node number 0 (WHILE) failed to invoke.
Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 11 (FlexStridedSlice) failed to prepare.
Node number 0 (WHILE) failed to invoke.

**Comment by manoj7410** [comment]
Have you compiled the model using edgetpu_compiler ? Can you share the compilation logs ?

**Comment by hjonnala** [comment]
It seems you have missed the quantization and edgetpu compilation steps.

Refer this tutorial section tf lite conversion: https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb#scrollTo=srOYhMYfx9XH

**Comment by ting3000** [comment]
@hjonnala Thanks! You are correct that I missed those two steps.

When I try to quantize the model, I got the following error:
_Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: ConcatV2, StridedSlice_

I tried to resolve it by using following code, then it gave another error "ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr"
```
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
    tf.lite.OpsSet.SELECT_TF_OPS
]
```

How do solve this error?
Thanks!

**Comment by hjonnala** [comment]
@ting3000 please share your model training script and quantization script.

**Comment by ting3000** [comment]
The model was re-trained with custom dataset and TensorFlow OD API, https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py.
The pre-trained model SSD ResNet101 V1 FPN 640x640 (RetinaNet101) was downloaded from TensorFlow 2 detection model zoo https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

The quantization script is similar to the Google tutorial, https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb.
```
import numpy as np
import os

from tflite_model_maker.config import ExportFormat
from tflite_model_maker import model_spec
from tflite_model_maker import object_detector

import tensorflow as tf
assert tf.__version__.startswith('2')


tf.get_logger().setLevel('ERROR')
from absl import logging
logging.set_verbosity(logging.ERROR)

saved_model_dir = "ssd_resnet101_v1_fpn_640x640_coco17_tpu-8/saved_model"
image_size = 640
tflite_model_name = "model_quant.tflite"

datasetset_dir = "images"
def representative_data_gen():
  dataset_list = tf.data.Dataset.list_files(datasetset_dir + '/*.jpg')
  for i in range(100):
    image = next(iter(dataset_list))
    image = tf.io.read_file(image)
    image = tf.io.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [image_size, image_size])
    image = tf.cast(image / 255., tf.float32)
    image = tf.expand_dims(image, 0)
    yield [image]

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# This sets the representative dataset for quantization
converter.representative_dataset = representative_data_gen
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
    tf.lite.OpsSet.SELECT_TF_OPS
]

# For full integer quantization, though supported types defaults to int8 only, we explicitly declare it for clarity.
converter.target_spec.supported_types = [tf.int8]
# These set the input and output tensors to uint8 (added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()

tflite_model = converter.convert()

# Save the model.
with open(tflite_model_name, 'wb') as f:
    f.write(tflite_model)

```
Thanks!

**Comment by hjonnala** [comment]
@ting3000 I am able to reproduce the issue. Unfortunately, I am not able to resolve it.  Please check with tensor flow team for any post integer quantization errors.

There is also an open issue for this error in tensorflow. https://github.com/tensorflow/tensorflow/issues/46821

**Comment by hjonnala** [comment]
Closing for now. Please check with tensor flow lit team on this error: ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr"
