### ISSUE TITLE
tflite Assertion Error  utils.same_input_image_sizes(interpreters) 

### ISSUE THREAD

**Issue by cappittall** [google-coral/edgetpu#426]
Hi,
I have created tflite model through colab demo : [Retrain EfficientDet-Lite detector for the Edge TPU (TF2)](https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb?authuser=1)

So far, .tflite model works very well. Before Compile for the Edge TPU. 
Here the log file of compile : 
Edge TPU Compiler version 15.0.340273435
Input: /content/drive/MyDrive/aidata/besas/models/besas-lite-model.tflite
Output: /content/drive/MyDrive/aidata/besas/models/besas-lite-model_edgetpu.tflite

```
Operator                           Count      Status

CONCATENATION               2          Mapped to Edge TPU
CUSTOM                              1          Operation is working on an unsupported data type
ADD                                   58         Mapped to Edge TPU
MAX_POOL_2D                 18         Mapped to Edge TPU
DEQUANTIZE                      2          Operation is working on an unsupported data type
QUANTIZE                          1          Mapped to Edge TPU
DEPTHWISE_CONV_2D   93         Mapped to Edge TPU
CONV_2D                        120        Mapped to Edge TPU
LOGISTIC                            1          Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        16         Mapped to Edge TPU
RESHAPE                        10         Mapped to Edge TPU
```
And in order to make quick test of Edgetpu , I deployed and replaced names of model, label and mp4 files in the folder **/usr/share/edgetpdemo**  
gives assert error for interpreters : assert utils.same_input_image_sizes(interpreters) 

When I debug, at utils.py file (as above error) original models gives 2 interpreter and both (300,300) input image size
but at my model gives (300,300) and (384,384) input image size. ( I do not know how happened this) 

I used as spec file  - EfficientDet-Lite1
and 
spec.config.tflite_max_detections = 50 (instead 25object from one class) 

I search around, maybe its simple problem but no one any iformation about. this. 

Coral Dev Board - 1 GB
computer : Linux aura 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Thanks in advance

**Comment by hjonnala** [comment]
can you share your uncompiled tflite model and command executed that raises the assert error.

**Comment by cappittall** [comment]
Hi, @hjonnala 

Thanks for quick reply. here the all files :

https://drive.google.com/drive/folders/1mz0X0E5bDsQUY3k-UCjAkI26iGvRE7WP?usp=sharing

I executed exactly the same file in **edgetpu_demo --stream** file (just changed the name of model, label, and mp4 video file.  (The demo comes with Coral Dev Board, which is [car detection at highway ](https://pixabay.com/videos/road-autobahn-motorway-highway-11018/))

**Comment by cappittall** [comment]
Sorry, I have shared wrong link. Here is the link which you can access : https://drive.google.com/drive/folders/1mz0X0E5bDsQUY3k-UCjAkI26iGvRE7WP?usp=sharing

**Comment by cappittall** [comment]
hello @hjonnala I updated the link which was wrong. Now no need autorisation.

As I  undertood, previous model input image size : (384,384) and after compile, its became (300,300) and this assortion error raise out.  So, 
- Those should be the same? 
-  And if it should be the same, how can switch this at the beginning of model creation?

**Comment by hjonnala** [comment]
Hi, I am able to get the files. Will get back you soon.

**Comment by hjonnala** [comment]
Hi, I am not able to reproduce the issue. Are you trying to do image detection? 

I have used the model, images and labels in the shared drive and run with pycoral detect_image.py.

python3 examples/detect_image.py \
  --model /home/mendel/models/besas-lite-model_edgetpu.tflite \
  --labels /home/mendel/models/besas-labels.txt  \
  --input /home/mendel/models/test.jpg \
  --output /home/mendel/models/result.jpg


Here are the results:

![result](https://user-images.githubusercontent.com/86132058/126811388-e1a1cf8f-b42a-4043-a4f7-7bf795c66913.jpg)

**Comment by cappittall** [comment]
Hi @hjonnala,

Thanks for your effors,  yes model works enouh good. My question was different, as above.  My question lite model should be the same input image size with copiled version or not as edgetpu_demo cheking that? I also uploaded a video for the test. But unable to run at  Coral board yet. However, I will find another way to test. Closing the issue.  
Thanks again.

**Comment by hjonnala** [comment]
Hi, I have added sample script to test the video. please check detect.py and recorder.MP4 files.

https://drive.google.com/drive/folders/170BsALyM9gnSBE7DSgnPUSf029ej19TD?usp=sharing

Thanks.

**Comment by cappittall** [comment]
Thanks @hjonnala 
As per many testing on coral dev board, I do not want to use external library like opencv. (It takes too long building time and cunsuming almost %92 or root momery) because of I tried to use installed libraries like gsreamer instead opencv. I have to ask that its working very nice at own installed video. But at my uploaded video; object detecting is working but video is black (as attached :)) ) this may couse from gstreamer pipline setups. I just wanted to know do you know why?  

![Screenshot (3)](https://user-images.githubusercontent.com/14778803/126893423-0874dafb-ed26-43f5-946f-da29a5218a2c.png)

**Comment by hjonnala** [comment]
Hi, I am not sure why  the background is black.

I am able to run the video demo using USB accelerator and dev board connected to monitor using gstreamer.

The script I have used: https://github.com/google-coral/examples-camera/blob/master/gstreamer/detect.py

changed this line: https://github.com/google-coral/examples-camera/blob/master/gstreamer/detect.py#L114
to **src_size=(640, 380)**

Here are the commands I have used:
WIth  USB accelerator: python3 detect.py --model /home/hemanthreddyj/Downloads/models/besas-lite-model_edgetpu.tflite --labels /home/hemanthreddyj/Downloads/models/besas-labels.txt --videosrc /home/hemanthreddyj/Downloads/models/faracaliB.mp4 --top_k 50

On Dev Board: python3 detect.py --model /home/mendel/models/besas-lite-model_edgetpu.tflite --labels /home/mendel/models/besas-labels.txt --videosrc /home/mendel/models/faracaliB.mp4 --top_k 50

**Comment by cappittall** [comment]
Thanks @hjonnala, I have changed the video size with web whatsapp sending utility. Its working good. Also when I run $ `edgetpu_demo --device`   on device with orginal video size (not on local .html server) its working also quite good too. Now need to implements another things. (like object trackings) So far, really I appretiated your honest effort and help. Thanks again.
