### ISSUE TITLE
What is the black magic behind "Off-chip memory used for streaming uncached model parameter"?

### ISSUE THREAD

**Issue by ricardodeazambuja** [google-coral/edgetpu#427]
What is the black magic behind "Off-chip memory used for streaming uncached model parameter"?
```
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 1379 ms.

Input model: model.tflite
Input size: 4.41MiB
Output model: model_edgetpu.tflite
Output size: 5.49MiB
On-chip memory used for caching model parameters: 1.92MiB
On-chip memory remaining for caching model parameters: 1.75KiB
Off-chip memory used for streaming uncached model parameters: 3.23MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 136
Operation log: model_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 135
Number of operations that will run on CPU: 1

Operator                       Count      Status

RESHAPE                        15         Mapped to Edge TPU
CONCATENATION                  3          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
ADD                            10         Mapped to Edge TPU
CUSTOM                         1          Operation is working on an unsupported data type
CONV_2D                        73         Mapped to Edge TPU
DEPTHWISE_CONV_2D              29         Mapped to Edge TPU
LOGISTIC                       2          Mapped to Edge TPU
```
Another curiosity. This model is made of two other tflite models in parallel (two inputs). However, if I compile the models for shared cache (using the original two tflite files), depending on the order it changes the amount of "Off-chip memory used for streaming uncached model parameters" assigned to each model.

**P.S.: when I compile the models individually, this is the result for any of the models:**
```
Off-chip memory used for streaming uncached model parameters: 0.00B
```

_Originally posted by @ricardodeazambuja in https://github.com/google-coral/edgetpu/issues/324#issuecomment-882107646_

**Comment by hjonnala** [comment]
Hi, please refer to this link : https://coral.ai/docs/edgetpu/compiler/#co-compiling-multiple-models

For example, consider if you co-compile two models as shown here:

**edgetpu_compiler model_A.tflite model_B.tflite**

In this case, cache space is first allocated to model A's data (as much as can fit). If space remains after that, cache is given to model B's data. If some of the model data cannot fit into the Edge TPU RAM, then it must instead be fetched from the external memory at run time.

**Comment by ricardodeazambuja** [comment]
Hi @hjonnala, 

Thank you for your reply, but I understand the compiler will off load stuff if there isn't enough memory. My problem is that I want to understand how to get the best of it. It seems the compiler has limits that go beyond simply "amount of memory", and the type / order / number of ops used will play a role as well. However, Google does NOT document these details making me think the EdgeTPU will follow other Google products and become vaporware sooner than later.

Could Google add a debug mode for the compiler that would give more details to allow the user to optimize / fix things????

**Comment by hjonnala** [comment]
Hi, Please check new compiler version. Changes have been made to help the users to know more about the errors.

**Comment by ricardodeazambuja** [comment]
I'm sorry, but that is not a reasonable answer. Which version of the compiler has improved error debugging????

**Comment by manoj7410** [comment]
@ricardodeazambuja Compiler version 16 has better error reporting. You can see the detailed changes at https://coral.ai/news/updates-07-2021.

**Comment by ricardodeazambuja** [comment]
@manoj7410, thank you for your reply. My problem is that I don't get an error, I just don't know how to improve / optimize the model. Is there a way to get more info about the "Off-chip memory" than what I get below?
```
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 1382 ms.

Input model: model.tflite
Input size: 4.41MiB
Output model: model_edgetpu.tflite
Output size: 5.47MiB
On-chip memory used for caching model parameters: 1.80MiB
On-chip memory remaining for caching model parameters: 512.00B
Off-chip memory used for streaming uncached model parameters: 3.39MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 135
Operation log: model_edgetpu.log

Operator                       Count      Status

LOGISTIC                       2          Mapped to Edge TPU
CONV_2D                        73         Mapped to Edge TPU
DEPTHWISE_CONV_2D              29         Mapped to Edge TPU
CONCATENATION                  3          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
RESHAPE                        15         Mapped to Edge TPU
ADD                            10         Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded!
```
[tflite_model.zip](https://github.com/google-coral/edgetpu/files/6923222/tflite_model.zip)
