### ISSUE TITLE
Conflict python3-edgetpu vs. python3-pycoral

### ISSUE THREAD

**Issue by ghost** [google-coral/edgetpu#428]
Hi, I have connected two Edge TPU accelerators to a Raspberry Pi 4. With this I want to run an object detection and secondly a bird classification. Each program works in itself. For this I would have to install "python3-edgetpu" and "python3-pycoral" in parallel. But only one of them works at a time. What can I do there.

**Comment by hjonnala** [comment]
python3-edgetpu is deprecated. please use python3-pycoal
