### ISSUE TITLE
Custom model fail to run on edgeTPU

### ISSUE THREAD

**Issue by fllay** [google-coral/edgetpu#435]
I follow custom object detection in this notebook 

https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_ssdlite_mobiledet_qat_tf1.ipynb

I got the model and download it. However, when I test the model, I got the following error.

detect_image.py \
  --model ssdlite_mobiledet_dog_vs_cat_edgetpu.tflite \
  --labels labels.txt \
  --input dog.jpg \
  --output dog_result.jpg

Traceback (most recent call last):
  File "/home/pi/coral/pycoral/examples/detect_image.py", line 108, in <module>
    main()
  File "/home/pi/coral/pycoral/examples/detect_image.py", line 74, in main
    interpreter.allocate_tensors()
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Failed to prepare for TPU. Failed precondition: Package requires runtime version (14), which is newer than this runtime version (13).Node number 2 (EdgeTpuDelegateForCustomOp) failed to prepare.

I have no idea what is wrong.

**Comment by hjonnala** [comment]
Hi, Please compile the model with runtime version 13 by specifying -m flag (https://coral.ai/docs/edgetpu/compiler/#usage)

`! edgetpu_compiler -s -m 13 ssdlite_mobiledet_dog_vs_cat.tflite`

or upgrade edgetpu runtime https://coral.ai/software/#edgetpu-runtime

**Comment by fllay** [comment]
thank you very much. it is working now.
