### ISSUE TITLE
Is there another way to install libedgetpu1-std

### ISSUE THREAD

**Issue by busyyang** [google-coral/edgetpu#436]
I have fond the way to install `libedgetpu1-std` on webpage `https://coral.ai/docs/accelerator/get-started/`. 
But we have no access to `packages.cloud.google.com`  since we are in China. Is there another way to install/download relative packages?

**Comment by hjonnala** [comment]
Hi, please download libedgetpu packages from here: https://coral.ai/software/#edgetpu-runtime

**Comment by busyyang** [comment]
@hjonnala Thanks for quick response. I would like to make sure if I am doing right.
 I have download the [edgetpu_runtime_20210119.zip](https://coral.ai/software/#edgetpu-runtime) and installed on my Raspiberry 3B.
and also install pycoral API by:
~~~bash
python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ pycoral
~~~
Then, it seemed that it could work when I try to type command as below without errors.
~~~bash
python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycoral
>>> from pycoral.adapters import common
>>> quit()
~~~

But when I run the sample code in [pycoral](https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py), the errors  occures......
~~~bash
cd pycoral
python3 examples/detect_image.py   --model test_data/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite   --labels test_data/coco_labels.txt   --input test_data/grace_hopper.bmp   --output ${HOME}/grace_hopper_processed.bmp
Traceback (most recent call last):
  File "examples/detect_image.py", line 39, in <module>
    from pycoral.adapters import common
ModuleNotFoundError: No module named 'pycoral.adapters'
~~~

I am not pretty sure if I finished the installation......

**Comment by hjonnala** [comment]
Hi, Something went wrong with pycoral installation.

can you please paste the output of this command:
`python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ pycoral`

The above command installs tflite_runtime and pycoral.

Alternatively, you can also try installing tflite_runtime and pycoral in the same order using .whl files from here:
https://coral.ai/software/#pycoral-api

**Comment by busyyang** [comment]
@hjonnala I just fond the version of pycoral is abnormal, which is 0.0.7, but the version of .whl files is 2.0.0. I uninstall them and re-install pycoral by .whl file. Now it works good. Thanks for your kindly support.
