### ISSUE TITLE
Running grad-cam with PyCoral API

### ISSUE THREAD

**Issue by publioelon** [google-coral/edgetpu#440]
Hi, I'd like to know if it's possible to run grad-cam using the PyCoral API, so far I was not able to find examples

**Comment by hjonnala** [comment]
Hi, if you have the model ready, you can try converting the model using post integer quantization to tflite and compile with edgetpu compiler. 

Please check this tutorial section tflite conversion: https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb#scrollTo=w9ydAmHGHUZl

**Comment by hjonnala** [comment]
Feel free to reopen if you have any questions.
