### ISSUE TITLE
code for retraining semantic segmentation model

### ISSUE THREAD

**Issue by goodboychan** [google-coral/edgetpu#441]
Hi, I'm trying to handle semantic segmentation on Edge TPU (w. coral dev board)

I found the example model for Pet/Object/Body segmentation [here](https://coral.ai/models/semantic-segmentation/), but I want to retrain the model for my purpose through same approach. (of course I have my datasets that consists on several polygon) 

Is there any place to get retraining code for these purpose?

Thanks in advance.

**Comment by manoj7410** [comment]
@goodboychan Code for retraining a semantic segmentation model hasn't been documented/published.

**Comment by goodboychan** [comment]
Thanks for the notice.

Actually, I found the [DeepLab](https://github.com/tensorflow/models/tree/master/research/deeplab) model from tensorflow repo. I just wonder that this model pipeline is the same as the pretrained model metioned on pages.

**Comment by bhack** [comment]
We have a request also on the official forum:

https://discuss.tensorflow.org/t/suggestion-for-choosing-a-model/4057

**Comment by manoj7410** [comment]
Helpful threads at https://github.com/google-coral/edgetpu/issues/315 and https://discuss.tensorflow.org/t/suggestion-for-choosing-a-model/4057/11
