### ISSUE TITLE
Automatically switching on Dev-Board Mini with power supplied over GPIO 5V

### ISSUE THREAD

**Issue by FHermisch** [google-coral/edgetpu#442]
Hi,

I provide power to the DevBoard-Mini from the GPIOs via our own custom-made PCB HAT (which additionally just features some LEDs and a Fan-Control for an industry-fair showcase).
I seams like I misunderstood 5.1.2 of the DevBoard-Mini technical manual - thinking it would power up automatically like having power supplied via USB OTG.

Is there any way to make the DevBoard-Mini boot automatically in this case? - like e.g. having some registers of some I2C chips updated, having a special firmware update (like the one with the 'orange' LED during bootup). 

Would be great if there is a software solution, as otherwise we have to reconstruct our casing to spare a hole for reaching that button.

Thanks,
Florian

**Comment by hjonnala** [comment]
Hi Florian,

This is not possible without hardware changes. There are two ways to boot the system, via the power button or via charger detection. If you look at page 5 of the schematic (https://github.com/google-coral/electricals/blob/master/dev_board_mini/Coral-Dev-Board-Mini-schematic.pdf) you'll see the detect signal (VCDT) is only sourced when the USB OTG 5V is applied (VBUS_TYPC). This would need to be reworked in order to tie VCDT to the VBUS on the GPIO connector.

Thanks

**Comment by FHermisch** [comment]
Hi Hemanth,
thank you. As you searched, I also had a look into the schematics. The VCDT you mentioned as well as the PWRKEY signal is connected to the MT6392 chip. The functionality of this chip is steered by a multitude of register settings via system drivers / device tree overlays. Sadly there is no open available documentation of that chip - it might feature some persistent registers which steer the functionality of the PWRKEY as well as the behaviour of "ON POWER" - like every regular PC bios has.
If you do have access on these documentations, it would be great if you have a short look. If it is a one-time-setting (like electronic fusing) - this would also be ok for me.
Greetings,
Florian

**Comment by hjonnala** [comment]
Hi Florain,

The documentation for MT6392 chip is not open sourced. I have checked with internal team got to know that even the documentation of chip won't help in this case. 

Thanks

**Comment by FHermisch** [comment]
Thanks a lot for checking this!
