### ISSUE TITLE
swiotlb buffer is full

### ISSUE THREAD

**Issue by dungcules** [google-coral/edgetpu#443]
I am working with 4GB coral development board and a Flir blackfly usb3 camera (BFS-U3-244S8C-C). The camera works fine with my Ubuntu laptop. I am developing an application with this camera and Coral development board. However, I got following error when trigger this camera:
```
[   85.538451] dwc3 38200000.dwc3: swiotlb buffer is full (sz: 16384 bytes)
[   85.545162] dwc3 38200000.dwc3: DMA: Out of SW-IOMMU space for 16384 bytes
[   85.552662] usb 2-1.2: usbfs: usb_submit_urb returned -11
```
I already increase the swiotlb buffer to 65535. My Kernel command line is as following:

`[    0.000000] Kernel command line: console=ttymxc0,115200 console=tty0 earlycon=ec_imx6q,0x30860000,115200 root=PARTUUID=70672ec3-5eee-49ff-b3b1-eb1fbd406bf5 rootfstype=ext4 rw rootwait init=/sbin/init net.ifnames=0 pci=pcie_bus_perf iommu=soft iommu.passthrough=1 swiotlb=65535 coherent_pool=8M`

The size of swiotlb buffer is also confirmed as 128MB when I retrieve it:

```
# dmesg | grep TLB
[    0.000000] software IO TLB: mapped [mem 0xf7fff000-0xfffff000] (128MB)
[    0.277158] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
```

Look like the driver of USB3 (dwc3) can use only 16384 bytes but I am not able to confirm it. Please let me know if you have any idea to solve this issue. Thanks a lot

**Comment by manoj7410** [comment]
@dungcules  Can you try the following method:

=> setenv othbootargs swiotlb=65536
=> printenv othbootargs
othbootargs=swiotlb=65536
=> saveenv

And is there a third party library or SDK that you are using here ?

**Comment by dungcules** [comment]
@manoj7410 I already set the environment as you suggest but the error still repeats

```
Hit any key to stop autoboot:  0
u-boot=> printenv
baudrate=115200
bootargs=swiotlb=65536
bootcmd=ext2load mmc 0:1 ${loadaddr} boot.scr; source; boota mmc0 boot_a
bootdelay=5
bootdev=0
ethaddr=7c:d9:5c:b1:97:2e
ethprime=FEC
fastboot.mmc_size=15678308352
fastboot_dev=mmc0
fdt_high=0xffffffffffffffff
fdtcontroladdr=ff931390
initrd_high=0xffffffffffffffff
loadaddr=0x40480000
m4boot=ext2load mmc ${bootdev}:1 ${m4loadaddr} ${m4image}; dcache flush; bootaux ${m4loadaddr}
m4image=m4_fw.bin
m4loadaddr=0x007E0000
othbootargs=swiotlb=65536
serial#=1a0e21d6f6c99eee
soc_type=imx8mq
splashpos=m,m
stderr=serial
stdin=serial
stdout=serial

Environment size: 582/4092 bytes
u-boot=> printenv othbootargs
othbootargs=swiotlb=65536
```

The SDK that I use has name of Spinnaker and it comes from the Camera manufacture. The link is below
https://www.flir.com/products/spinnaker-sdk/

**Comment by manoj7410** [comment]
@dungcules I have seen similar issue in the past where the third party lib was blocking the swiotlb buffer size. I would suggest you to check if the SDK that you are using has some soft spot which is causing this issue.

**Comment by dungcules** [comment]
@manoj7410 I send the SDK developing team an email for this issue. I will update as soon as I heard back from them.

**Comment by dungcules** [comment]
@manoj7410 Could you tell me the correct way to increase the USB-FS memory? This camera transfer captured data directly to host RAM. The installer increase value of `/sys/module/usbcore/parameters/usbfs_memory_mb` to 1000 (from 16). The error message from dwc3 driver also mentions 16MB only. Is that just a coincident?

**Comment by manoj7410** [comment]
You can see the usbfs_memory by the command:
 
cat /sys/module/usbcore/parameters/usbfs_memory_mb
And you can change it's value if you want:

echo 1000 > /sys/module/usbcore/parameters/usbfs_memory_mb

This would assign a maximum of 1000 MB to the USB stack.

**Comment by manoj7410** [comment]
Changing the value of /sys/module/usbcore/parameters/usbfs_memory_mb is the correct way I believe. But in your SDK's code as well there should be a buffer referring to swiotlb which is restricted to 16 MB or so.

**Comment by dungcules** [comment]
@manoj7410 I have talked to the SDK developing team and they confirmed that the SDK does not restrict the buffer size to 16MB. Is that any way that we can test the size of `usbfs_memory_mb` on a specific process?

The problem is solved when I reduce the image size to smaller size. This means the setting on `usbfs_memory_mb` is not adopted by the system.

**Comment by manoj7410** [comment]
What do you see in the output if you run :

cat /sys/module/usbcore/parameters/usbfs_memory_mb

**Comment by dungcules** [comment]
@manoj7410

It gives me 1000 MB:

```
# cat /sys/module/usbcore/parameters/usbfs_memory_mb
1000
```

I also modified /etc/rc.local as following:

```
# cat /etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

sh -c 'echo 1000 > /sys/module/usbcore/parameters/usbfs_memory_mb'

exit 0
```

**Comment by manoj7410** [comment]
> # cat /sys/module/usbcore/parameters/usbfs_memory_mb
1000

This must be displaying the correct value. I only know this method to change usbfs_memory_mb size.

**Comment by manoj7410** [comment]
Feel free to reopen if you are still facing this issue.
