### ISSUE TITLE
RuntimeError: Internal: Unsupported data type in custom op handler: 1302091184Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.

### ISSUE THREAD

**Issue by AkkiSony** [google-coral/edgetpu#445]
I converted my darknet model to tflite model using the follwing link. https://github.com/guichristmann/edge-tpu-tiny-yolo

After sucessfully converting the model into tflite, I tried to do inference on the image. During thsi process, I am getting the folwwing error. Please help me fix the issue. 

The link to my model and classes can be found in the below link. 
https://drive.google.com/drive/folders/181npG1SDJnMBBQOm_gXbL0XguSA4gGsy?usp=sharing

![coral-TPU-error-20](https://user-images.githubusercontent.com/85996229/130040075-10211ce6-3768-461a-af7b-74fa87b0f602.PNG)

**Comment by AkkiSony** [comment]
I added 'edgetpu.dll' in the path instead of .so file and hence, I could over come the previous error. Now, I have aniother error. Can you please help me with the same?

![coral-TPU-error-21](https://user-images.githubusercontent.com/85996229/130049809-bec4f8b3-e787-4951-8359-da6d11dbe1ad.PNG)

 Thanks in advance!

**Comment by hjonnala** [comment]
have you complied the model by specifying runtime version 13 with -m flag since you are using runtime 13?

**Comment by AkkiSony** [comment]
@hjonnala I would like to know if I have to install edgetpu_runtime in the new virtual environment created my me? Becasue, when I type the folllwing command, I get the follwing output.

------------------------------------------------------------------
(yolov3-tflite) C:\pycoral_venv\Scripts\coral\pycoral1>python
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflite_runtime.interpreter as tflite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tflite_runtime'

**Comment by AkkiSony** [comment]
As per the link(https://github.com/guichristmann/edge-tpu-tiny-yolo) followed, this requires me to install tensorflow 1.15.0 and opencv. Hence, I have installed them in the virtual environment. Apart from that, is there anything, I need to install for running inference on edge tpu? I also installed edgetpu_runtime for python version 3.7.11. 
tflite.__version__
'2.5.0.post1'
@hjonnala What needs to be done in order to overcome the error?

**Comment by AkkiSony** [comment]
> have you complied the model by specifying runtime version 13 with -m flag since you are using runtime 13?
 
Yes, I did compile it with version 13. Yet same output. :( @hjonnala

**Comment by hjonnala** [comment]
You are able to get the output details when using detect_image.py but it is failing while doing post processing since the model output details are different from expected ones. you can reference this [script](https://github.com/guichristmann/edge-tpu-tiny-yolo/blob/master/inference.py) how to do post processing of output details. or you can try same script with tensorflow2.5

**Comment by AkkiSony** [comment]
> You are able to get the output details when using detect_image.py but it is failing while doing post processing

Does this mean that, my model is working fine? Is there a way where I can check the inference of the tflite model first. If it works fine, I think I can try working on edgetpu.tflite model.

**Comment by AkkiSony** [comment]
When I upgraded tf to 2.5.0, I got the folllowing output. I am not sure why is it loading more than one .dll file.

![coral-TPU-error-22](https://user-images.githubusercontent.com/85996229/130079258-64676fea-febd-4fe8-99f5-3932b8ce0b8a.PNG)

**Comment by hjonnala** [comment]
You can use this script to check whether model is working fine or not for both tflite and edgetpu models.

```
import numpy as np
import tflite_runtime.interpreter as tflite
import os
# Load TFLite model and allocate tensors.
base_dir = os.path.dirname(os.path.abspath(__file__))
model_name = 'quant_model_edgetpu.tflite'

models = [model_name.replace('_edgetpu.tflite', '.tflite'), model_name]
for model_name in models:
    print(model_name)
    model_path = os.path.join(base_dir, 'models', model_name)
    if '_edgetpu.tflite' in model_name:
        interpreter = tflite.Interpreter(
            model_path=model_path, experimental_delegates=[tflite.load_delegate('libedgetpu.so.1',  {})])
    else:
        interpreter = tflite.Interpreter(model_path=model_path)
    interpreter.allocate_tensors()

    # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Test model on random input data.
    input_shape = input_details[0]['shape']
    input_data = np.array(np.random.random_sample(input_shape), dtype=np.uint8)
    interpreter.set_tensor(input_details[0]['index'], input_data)

    interpreter.invoke()

    # The function `get_tensor()` returns a copy of the tensor data.
    # Use `tensor()` in order to get a pointer to the tensor.
    output_data = interpreter.get_tensor(output_details[0]['index'])
    print(model_path, len(output_data))
```

**Comment by AkkiSony** [comment]
@hjonnala Thanks for your reply. 
After, I updated to tf 2.5.0, the code works without any error. But, there are no predicitions at all. 
1. Can you give me some tips where I can start debugging this code from? 
2. Or would you suggest me to use detect_image.py script and analyse the output_details? 
3. I have no good knowledge of post procesing. Is there any link which helps me learn how to write post processing?
Thank you so much for your help. :)

**Comment by hjonnala** [comment]
There are no predicitions at all. Are you referring to this [script](https://github.com/guichristmann/edge-tpu-tiny-yolo/blob/master/inference.py)?

**Comment by hjonnala** [comment]
you can reach out some folks here https://github.com/google-coral/edgetpu/issues/405 on help with running inference.

**Comment by AkkiSony** [comment]
> There are no predicitions at all. Are you referring to this [script](https://github.com/guichristmann/edge-tpu-tiny-yolo/blob/master/inference.py)?

Yes, this script! :/

**Comment by AkkiSony** [comment]
Do you have any idea of any software which helps us to visuzalize the output during debugging? I have heard of "Image Watch" which is used with visual studio. Is there any with PyCharm?

> 3\. I have no good knowledge of post procesing. Is there any link which helps me learn how to write post processing?

Do you have any info on these?

**Comment by AkkiSony** [comment]
When I trying inference with the above mentioned 

> You can use this script to check whether model is working fine or not for both tflite and edgetpu models.

script. 

I am getting the following output.
![coral-TPU-error-24](https://user-images.githubusercontent.com/85996229/130106298-dc9fda88-bbb3-4dc7-b669-8cb049d4cc37.PNG)

**Comment by hjonnala** [comment]
you might does not have models folder.

replace 
`model_path = os.path.join(base_dir, 'models', model_name)`

with
`model_path = os.path.join(base_dir, model_name)`

**Comment by AkkiSony** [comment]
I changed with      > model_path = os.path.join(base_dir, model_name)

However, I still have the same issue. I guess the issue is with libedgetpu.so or edgetpu.dll. Do I have to mention the path of edgetpu.dll as I am working with Windows.

**Comment by hjonnala** [comment]
please check the value error path and path to tflite is matching or not.. No need to mention the path of edgetpu.dll.

or you can directly pass edgetpu_tflite.path here: model_path = os.path.join(base_dir, 'models', model_name)

**Comment by AkkiSony** [comment]
I changed, yet no change in the output :/
![coral-TPU-error-25](https://user-images.githubusercontent.com/85996229/130143915-244b469b-7296-4176-9334-e17e7974b2e6.PNG)


> please check the value error path

I dint get this.

**Comment by hjonnala** [comment]
I can see a mismatch after pycoral1. Please use model_path = r'path to tflie'

**Comment by AkkiSony** [comment]
![coral-TPU-error-25](https://user-images.githubusercontent.com/85996229/130146011-5dd8712b-917b-4efe-9120-f40167f993c2.PNG)

What is this issue with numpy? Current version 1.21.2

When I try to update numpy, I get the followig:

(yolov3-tflite) C:\pycoral_venv\Scripts\coral\pycoral1>pip install -U numpy                                                                                             Requirement already satisfied: numpy in c:\users\akshayac\anaconda3\envs\yolov3-tflite\lib\site-packages (1.21.2)                                                       ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\users\\akshayac\\anaconda3\\envs\\yolov3-tflite\\lib\\site-packages\\numpy-1.21.2.dist-info\\METADATA'

**Comment by hjonnala** [comment]
Please install numpy==1.21.1

**Comment by AkkiSony** [comment]
@hjonnala  Thanks :) It worked! :) 
I visualized the output_data shape and found it to be (1, 13, 13, 30). How do I visualize the output? Is there a way where I can pass an image and check the output? How can I use this script to visualize the output image?

**Comment by hjonnala** [comment]
sorry, we don't have any sample inference scripts to visualize the images for yolov3 models.

**Comment by AkkiSony** [comment]
Okay thanks. But can you tell me what does this script do then? What does it indicate? Just curious to know what to do with this output.

**Comment by hjonnala** [comment]
it is just passing some random input based on input shape and checking the model can produce some inference or not..

**Comment by AkkiSony** [comment]
@hjonnala I have never written a post processing code. I have searched on google and could not find any useful resource. Could you please help me by acknowledging me how to write post processing code or could you share any useful link where I learn how to write them?
In this script, which is the post processing part? https://github.com/guichristmann/edge-tpu-tiny-yolo/blob/master/inference.py
Thanks in advance! :)

**Comment by AkkiSony** [comment]
Solution to the problem statement:
1. The following error could be over come following - google-coral/tflite#37 (comment).
2. By upgrading tf version.
