### ISSUE TITLE
Coral M.2 Accelerator with Dual Edge TPU Not detected

### ISSUE THREAD

**Issue by bennyryan** [google-coral/edgetpu#446]
Hi all,

Not sure if it a motherboard issue or a software issue but I cannot detect the "Coral M.2 Accelerator with Dual Edge TPU".
Might have to invest in a M.2 E Key adaptor. 

Details below:
Motherboard: https://www.asrock.com/MB/Intel/B560M%20Pro4/index.asp#Specification (updated to latest bios)
OS: Ubuntu 20.04.2 LTS

Command runs below:
$ uname -a
`Linux abc 5.10.0-1044-oem #46-Ubuntu SMP Wed Aug 11 09:50:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

$ dpkg -l | grep gasket
`ii  gasket-dkms                           1.0-17                                all          DKMS source for the gasket driver`

$ modinfo gasket
`
filename:       /lib/modules/5.10.0-1044-oem/updates/dkms/gasket.ko
author:         Rob Springer <rspringer@google.com>
license:        GPL v2
version:        1.1.4
description:    Google Gasket driver framework
srcversion:     69BBD6B15F498A5A90971DD
depends:
retpoline:      Y
name:           gasket
vermagic:       5.10.0-1044-oem SMP mod_unload modversions
sig_id:         PKCS#7
signer:         abc Secure Boot Module Signature key
sig_key:        13:B8:55:BF:FE:59:7B:58:6A:CC:9D:98:66:28:77:C6:51:B7:A1:70
sig_hashalgo:   sha512
signature:      09:73:32:05:A4:5C:38:79:88:A3:C6:21:32:94:E0:AE:4D:71:76:38:
		20:EB:D2:F6:32:75:4D:A3:51:6A:25:BF:FD:FC:E7:5D:6B:2F:AB:0C:
		9F:5E:BF:FF:9B:C2:0A:84:DE:C4:4F:E7:11:C6:DF:04:62:D4:AA:94:
		9D:1F:35:FD:4E:61:1F:94:D8:7B:08:3B:5C:2B:9B:30:17:C2:36:4D:
		60:35:06:D3:AA:85:49:D0:28:9C:F3:86:F3:7F:F8:6B:AA:DC:15:A8:
		2E:24:66:9F:4D:26:D8:28:DA:52:C3:DF:34:16:18:48:94:A4:FC:FC:
		F0:A3:6A:29:4A:96:78:6A:1A:B0:83:4A:D5:F1:23:75:54:0D:F4:83:
		94:4A:68:E7:7B:09:C6:22:53:B8:C7:68:EC:85:C3:8D:72:3E:FA:C9:
		B9:8E:28:BF:CB:B9:20:D7:C3:35:08:0C:D1:69:BA:DC:E3:94:BA:0C:
		6D:95:A0:F5:49:61:F0:EC:E8:62:4F:CE:73:62:C8:39:AD:88:EB:7E:
		60:02:D6:6F:EC:50:3B:06:56:99:88:10:E2:74:EA:17:A9:63:E1:84:
		1F:C9:A2:80:7A:0A:79:A3:37:04:49:B5:09:67:5F:62:65:79:9D:35:
		2E:5B:5D:03:B6:BA:69:54:14:13:75:77:7E:E0:24:4A
parm:           dma_bit_mask:int
`
$ modinfo apex
`
filename:       /lib/modules/5.10.0-1044-oem/updates/dkms/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.2
description:    Google Apex driver
srcversion:     700E8BBBE9CC23C6EC17712
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
retpoline:      Y
name:           apex
vermagic:       5.10.0-1044-oem SMP mod_unload modversions
sig_id:         PKCS#7
signer:         dino Secure Boot Module Signature key
sig_key:        13:B8:55:BF:FE:59:7B:58:6A:CC:9D:98:66:28:77:C6:51:B7:A1:70
sig_hashalgo:   sha512
signature:      9E:01:36:66:A2:72:8F:C2:30:F0:CE:73:85:9B:34:C8:82:DA:7F:96:
		9A:6D:46:5F:53:73:E5:69:86:17:4A:25:71:24:99:CF:87:EA:CC:9F:
		EA:0D:CB:A6:60:76:C3:14:21:46:68:DB:E8:1F:E4:0A:E8:2E:33:37:
		00:A1:29:82:13:C1:66:3C:08:B7:0D:A2:1D:C5:07:E7:97:22:78:95:
		D9:0E:23:B2:FA:88:CB:C0:13:CC:77:26:B8:8A:C9:D5:C9:78:6B:2E:
		D8:9D:30:E3:AE:DA:2D:1C:77:00:2F:D2:47:ED:E6:BD:69:0C:52:3E:
		8A:1A:C7:E8:75:6B:F3:83:2E:47:9F:D0:9C:B6:09:E5:22:8B:1C:19:
		FB:B7:E9:1E:FF:C3:D1:BA:DB:21:B2:C2:95:ED:31:D3:26:92:2A:6F:
		78:36:42:CA:3C:46:EA:58:E2:2D:2D:4A:FE:E0:14:DB:AC:D1:F8:B4:
		28:DC:74:D5:7C:78:A7:4F:1D:17:3E:A3:19:BA:E6:5A:82:A2:A1:C5:
		1F:22:01:51:38:1F:C2:D3:69:02:D7:2D:8C:1E:E4:80:F8:C2:CB:0F:
		08:B4:E4:CB:00:AB:B5:84:06:7F:91:82:07:56:98:BD:25:4D:CA:70:
		D1:54:FA:43:C7:82:90:2E:7A:42:76:99:E9:C4:57:63
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
parm:           trip_point0_temp:int
parm:           trip_point1_temp:int
parm:           trip_point2_temp:int
parm:           hw_temp_warn1:int
parm:           hw_temp_warn2:int
parm:           hw_temp_warn1_en:bool
parm:           hw_temp_warn2_en:bool
parm:           temp_poll_interval:int
`

**Comment by manoj7410** [comment]
@bennyryan Can you paste the output of :

- lspci -vvv

**Comment by bennyryan** [comment]
Thanks for the quick reply.

Results from: lspci -vvv
`00:00.0 Host bridge: Intel Corporation Device 9b63 (rev 03)
	Subsystem: ASRock Incorporation Device 9b63
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B+ ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort+ >SERR- <PERR- INTx-
	Latency: 0
	Capabilities: <access denied>
	Kernel driver in use: skl_uncore

00:02.0 VGA compatible controller: Intel Corporation Device 9bc8 (rev 03) (prog-if 00 [VGA controller])
	Subsystem: ASRock Incorporation Device 9bc8
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin A routed to IRQ 125
	Region 0: Memory at a0000000 (64-bit, non-prefetchable) [size=16M]
	Region 2: Memory at 90000000 (64-bit, prefetchable) [size=256M]
	Region 4: I/O ports at 3000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

00:14.0 USB controller: Intel Corporation Device 43ed (rev 11) (prog-if 30 [XHCI])
	Subsystem: ASRock Incorporation Device 43ed
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B+ ParErr- DEVSEL=medium >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 123
	Region 0: Memory at a1120000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci

00:14.2 RAM memory: Intel Corporation Device 43ef (rev 11)
	Control: I/O- Mem- BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Region 0: Memory at a1134000 (64-bit, non-prefetchable) [disabled] [size=16K]
	Region 2: Memory at a113e000 (64-bit, non-prefetchable) [disabled] [size=4K]
	Capabilities: <access denied>

00:16.0 Communication controller: Intel Corporation Device 43e0 (rev 11)
	Subsystem: ASRock Incorporation Device 43e0
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 126
	Region 0: Memory at a113d000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: mei_me
	Kernel modules: mei_me

00:17.0 SATA controller: Intel Corporation Device 43d2 (rev 11) (prog-if 01 [AHCI 1.0])
	Subsystem: ASRock Incorporation Device 43d2
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz+ UDF- FastB2B+ ParErr- DEVSEL=medium >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 122
	Region 0: Memory at a1138000 (32-bit, non-prefetchable) [size=8K]
	Region 1: Memory at a113c000 (32-bit, non-prefetchable) [size=256]
	Region 2: I/O ports at 3090 [size=8]
	Region 3: I/O ports at 3080 [size=4]
	Region 4: I/O ports at 3060 [size=32]
	Region 5: Memory at a113b000 (32-bit, non-prefetchable) [size=2K]
	Capabilities: <access denied>
	Kernel driver in use: ahci
	Kernel modules: ahci

00:1f.0 ISA bridge: Intel Corporation Device 4387 (rev 11)
	Subsystem: ASRock Incorporation Device 4387
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap- 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0

00:1f.3 Audio device: Intel Corporation Device f0c8 (rev 11)
	Subsystem: ASRock Incorporation Device 1897
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 32, Cache Line Size: 64 bytes
	Interrupt: pin A routed to IRQ 127
	Region 0: Memory at a1130000 (64-bit, non-prefetchable) [size=16K]
	Region 4: Memory at a1000000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

00:1f.4 SMBus: Intel Corporation Device 43a3 (rev 11)
	Subsystem: ASRock Incorporation Device 43a3
	Control: I/O+ Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap- 66MHz- UDF- FastB2B+ ParErr- DEVSEL=medium >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Interrupt: pin A routed to IRQ 16
	Region 0: Memory at a113a000 (64-bit, non-prefetchable) [size=256]
	Region 4: I/O ports at efa0 [size=32]
	Kernel driver in use: i801_smbus
	Kernel modules: i2c_i801

00:1f.5 Serial bus controller [0c80]: Intel Corporation Device 43a4 (rev 11)
	Subsystem: ASRock Incorporation Device 43a4
	Control: I/O- Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap- 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Region 0: Memory at 8f800000 (32-bit, non-prefetchable) [size=4K]

00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (11) I219-V (rev 11)
	Subsystem: ASRock Incorporation Ethernet Connection (11) I219-V
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 124
	Region 0: Memory at a1100000 (32-bit, non-prefetchable) [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: e1000e
	Kernel modules: e1000e`

**Comment by manoj7410** [comment]
I don't see any entry of Coral device in the output of lspci. Can you try to connect the device in some other PCIe port? You should see an entry with device ID : 089a

**Comment by bennyryan** [comment]
Yeah that is my issue. 
This is the M.2 E Key variant of Coral. So no other slot to plug it in to.

Guess I need to get an adaptor.

**Comment by magic-blue-smoke** [comment]
> Yeah that is my issue.
> This is the M.2 E Key variant of Coral. So no other slot to plug it in to.
> 
> Guess I need to get an adaptor.

@bennyryan behavior of your system is not what I'd expect, ie I don't believe motherboard doesn't have at least one PCIe interface on m.2 slot

Might be the case that m.2 slot is multiplexed with regular slot and disabled or auto-detection fails to detect m.2 card.

With given above, you should see at least one TPU core. Try to change UEFI settings first.

Getting passive m.2 E key to desktop PCIe adapter is not a solution, as it gives you only one TPU core. I'm working on active adapters that allow both TPUs https://github.com/magic-blue-smoke/Dual-Edge-TPU-Adapter

**Comment by bennyryan** [comment]
Thanks for your input @magic-blue-smoke.
Any specific UEFI settings I should be looking at?

Also let me know when you release your Adapter, I will be ordering!

**Comment by magic-blue-smoke** [comment]
@bennyryan in my UEFI: Advanced settings -> Onboard Devices Configuration -> M.2(WiFi)&PCIEX1_2 Select, where I have "Auto", but another options are "M.2(WiFi)" and "PCIEX1_2". All my PCIe slots are empty and UEFI switches PCIe to m.2 slot. In your case you might have something in PCIe slot, which "steals" bus from m.2 slot.

Thanks for your interest in adapter, I'll let you know, same time will announce release on GitHub and Twitter

**Comment by manoj7410** [comment]
@bennyryan Were you able to resolve this ?

**Comment by bennyryan** [comment]
Hey @manoj7410, no luck. I have ordered an adapter from Amazon (still not shipped). 
You can close this issue. 

Will also get @magic-blue-smoke proper adapter once it is out.

**Comment by biharitomi** [comment]
Hey @bennyryan,
Did the adapter work for you?
I am in the same situation with an AsRock DeskMini with H310M-STX motherboard and a dual Edge TPU. No detection either from BIOS or lspci side of Ubuntu.

**Comment by therealbenkrige** [comment]
@biharitomi I have the exact same ASRock Deskmini with H310M-STX motherboard and am having the same issue.  Did you manage to resolve it?

**Comment by therealbenkrige** [comment]
@biharitomi I think the slot on this motherboard only supports certain devices, and is not general. https://www.asrock.com/mb/Intel/H310M-STX/index.asp states "

> - 1 x M.2 Socket (Key E), supports type 2230 WiFi/BT PCIe WiFi module and [Intel® CNVi](https://download.asrock.com/TSD/20220415-TSDQA.pdf) (Integrated WiFi/BT)

**Comment by therealbenkrige** [comment]
@bennyryan which adapter did you order from Amazon?
