### ISSUE TITLE
Support TFDF (Decision Forests ML)

### ISSUE THREAD

**Issue by jdubz93** [google-coral/edgetpu#447]
### Description

Could we get edge tpu support for the tensorflow decision forest models?

### Issue Type

Feature Request

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

C++

**Comment by hjonnala** [comment]
Hi, So far Tflite hasn't started to support Decision Forests. Since edgetpu only support full int8 tflite models, Decision Forests/Trees cannot pass through edgetpu_compiler.

Ref: https://github.com/tensorflow/decision-forests/issues/20
https://github.com/tensorflow/decision-forests/issues/5
