### ISSUE TITLE
Cancelled Script when flashing

### ISSUE THREAD

**Issue by ryan-keswick** [google-coral/edgetpu#448]
### Description

When flashing the dev board I accidentally canceled the bash script (flash.sh) when running. This was the output up to the point of CTRL+C

Have I bricked the dev board?

<details><summary>Click to expand!</summary> 

### Issue Type

Build/Install, Support

### Operating System

Ubuntu

### Coral Device

Dev Board

### Relevant Log Output

```shell
Existing home partition detected, will not flash home (override with -H)
target reported max download size of 419430400 bytes
sending 'bootloader0' (1039 KB)...
OKAY [  0.062s]
writing 'bootloader0'...
OKAY [  0.194s]
finished. total time: 0.256s
rebooting into bootloader...
OKAY [  0.018s]
finished. total time: 0.119s
target reported max download size of 419430400 bytes
sending 'gpt' (33 KB)...
OKAY [  0.018s]
writing 'gpt'...
OKAY [  0.223s]
finished. total time: 0.241s
rebooting into bootloader...
OKAY [  0.016s]
finished. total time: 0.116s
erasing 'misc'...
OKAY [  0.043s]
finished. total time: 0.043s
target reported max download size of 419430400 bytes
sending 'boot' (131072 KB)...
OKAY [  6.093s]
writing 'boot'...
`OKAY [  6.244s]
finished. total time: 12.338s
`target reported max download size of 419430400 bytes
sending sparse 'rootfs' 1/4 (408709 KB)...
```
</details>

**Comment by manoj7410** [comment]
@ryan-keswick Can you try to flash the dev board with a SDCARD as instructed at https://coral.ai/docs/dev-board/get-started/#flash-the-board ?

**Comment by manoj7410** [comment]
@ryan-keswick Were you able to resolve this issue ?

**Comment by hjonnala** [comment]
Feel free to reopen if you have any issues with SDCARD flashing.
