### ISSUE TITLE
Didn't find op for builtin opcode 'RESIZE_BILINEAR' version '3'

### ISSUE THREAD

**Issue by hgaiser** [google-coral/edgetpu#45]
I was trying to compile a tflite model using the `edgetpu_compiler` tool, but got the following error:

```
Edge TPU Compiler version 2.0.267685300
ERROR: Didn't find op for builtin opcode 'RESIZE_BILINEAR' version '3'

ERROR: Registration failed.
```

This op is relatively new, it was fixed recently (https://github.com/tensorflow/tensorflow/issues/33691) and I am using it by installing `tf-nightly-gpu`. How can I make the EdgeTPU compiler aware of this new op? Can I compile against the latest version of tensorflow somehow?

**Comment by Namburger** [comment]
@hgaiser Unfortunately, it is not possible to link to the tf version with the compiler. As per our [compatibility overview](https://coral.ai/docs/edgetpu/models-intro/#compatibility-overview), we still suggest that tf1.15 is use for all training and tflite quantization conversions. The list of supported operations will always be hosted [here](https://coral.ai/docs/edgetpu/models-intro/#supported-operations)
The good new is that we are expecting a new compiler version to be coming out very soon, with this we'll see many bug fixes and tf2.0 compatibility. Stay tune in out [/news](coral.ai/news) page for updates.

**Comment by hgaiser** [comment]
@Namburger thank you for your quick response! Just to verify, when the new compiler comes out, should it support the new `RESIZE_BILINEAR` op? Or will it support ops from tensorflow 2.0 / 2.1 only?

Also, is the compiler the only way to run models on a TPU? What I'm asking is if you know a workaround while I'm waiting for the new compiler.

**Comment by Namburger** [comment]
@hgaiser new compiler is out since I last posted this, actually! 
The new version is 2.0.29* can you try to compiler your model first? I believe an apt upgrade will get you the new version. Unfortunately, despite much effort from our team, the new compiler is still new fully compatible with tf2.0 yet, but most new ops will pass through.

**Comment by hgaiser** [comment]
Awesome, thank you for the update :) It seems to work, I haven't tested it on the TPU yet, but the compiler succeeded without errors, so I'll close this issue.

:tada:

**Comment by bhack** [comment]
@hgaiser Is this a new MLIR based compiler?

**Comment by Namburger** [comment]
@bhack it's a compiler to map model operations to the tpu:
https://coral.ai/docs/edgetpu/compiler/

**Comment by bhack** [comment]
I meant if the new compiler was based on MLIR 
https://mlir.llvm.org/
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/mlir/lite

**Comment by hgaiser** [comment]
@bhack no this is the "standard" compiler found [here](https://github.com/google-coral/edgetpu/tree/master/compiler/x86_64).

**Comment by icoicqico** [comment]
Hello, I have the same problem, I have installed the latest compiler and switch between different versions of tf(1.14.0 , 1.15.0, 2.2.0, 2.4.0) still can't get this work, anyone know how to solve the problem? Thanks.
