### ISSUE TITLE
failed to convert yolov5 to edgeTPU due to img_size

### ISSUE THREAD

**Issue by sypark155** [google-coral/edgetpu#450]
### Description

Hello
I tried to convert yolov5 to edgeTPU model. 
(refer to https://github.com/zldrobit/yolov5/tree/tf-edgetpu)

First, I converted pytorch model to TFLite model. 
And then, converted TFLite model to Edge TPU. 

When I tried to convert with 320 for image size, there is no problem for converting. 
But I failed to convert when converting with bigger size than 320, (ex, 416, 608, 640)

The below is error message for converting TFLite model to Edge TPU.
I want to know it is possible to convert to Edge TPU with bigger than 320 and the way. 

Thanks in advance. 
![image](https://user-images.githubusercontent.com/89433634/130734921-41fdd5ec-75b7-4f11-b360-c2e20b13c2a1.png)

<details><summary>Click to expand!</summary> 

### Issue Type

Bug

### Operating System

Ubuntu

</details>

**Comment by manoj7410** [comment]
@sypark155 Can you walk through https://github.com/google-coral/edgetpu/issues/439 and see if there is anything helpful ?

**Comment by hjonnala** [comment]
@sypark155 try with -a -d flag and wait for the full execution. If it fails please share CPU tflite model

**Comment by ZhouKai90** [comment]
I have the same problem when I compile EfficientDet to edgetpu model. Here is the CPU tflite model.https://drive.google.com/file/d/1FwjEKZgOF6RQKyCBOqd1tkSQRKbAYJ9_/view?usp=sharing

**Comment by hjonnala** [comment]
@ZhouKai90 the model is failing due to reshape operation memory not fitting on Edge TPU

**Comment by hjonnala** [comment]
@ZhouKai90 please try the command below, you would be able to compile the model.

`!edgetpu_compiler -s -d E0_512_512.tflite`

**Comment by hjonnala** [comment]
@sypark155 feel free to reopen if issue still exists and share the tflite model.

Thanks.
