### ISSUE TITLE
yolov5s - inference on edgetpu - coral pi (32 bit)

### ISSUE THREAD

**Issue by NandhiniN85** [google-coral/edgetpu#452]
### Description

Reference Issue: https://github.com/google-coral/edgetpu/issues/449

@taloot @hjonnala The raspberry pi I am using is limited to 32 bits and thus restricts me from installing the torch version provided in the requirements(for using detect.py). Is there any workaround for making inference by using the edge compiled version, as the post-processing involves NMS that refers to the torch to finalise the bounding boxes. Any guidance is much appreciated. Thanks!

**Comment by NandhiniN85** [comment]
@hjonnala
Kindly close this issue, I have found a way for using arrays instead of tensors for NMS processing. Reference link - https://github.com/ZFTurbo/Weighted-Boxes-Fusion/tree/master/ensemble_boxes

Thanks!

**Comment by manoj7410** [comment]
@NandhiniN85 Thank you for sharing that link.
