### ISSUE TITLE
Google Dev Board / GPIO give user  'Mendel' permissions to access.

### ISSUE THREAD

**Issue by kiteklan** [google-coral/edgetpu#457]
### Description

I am trying to combine the environmental sensor and detect.py functions in one code.
I do not want use sudo on the start , how can I give GPIO noon root permissions.

```
 raise GPIOError(e.errno, "Setting GPIO direction: " + e.strerror)
periphery.gpio.GPIOError: [Errno 13] Setting GPIO direction: Permission denied
```

<details><summary>Click to expand!</summary> 

### Issue Type

Support

### Operating System

Mendel Linux

### Programming Language

Python 3.6

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "/home/mendel/google-coral/examples-camera/gstreamer/detect_1.py", line 145, in <module>
    main()
  File "/home/mendel/google-coral/examples-camera/gstreamer/detect_1.py", line 106, in main
    enviro = EnviroBoard()
  File "/usr/lib/python3/dist-packages/coral/enviro/board.py", line 69, in __init__
    self._display = ssd1306(serial_interface=spi(gpio=pGPIO(), port=port, device=0, gpio_DC=138, gpio_RST=140),
  File "/usr/lib/python3/dist-packages/luma/core/interface/serial.py", line 261, in __init__
    bitbang.__init__(self, gpio, transfer_size, DC=gpio_DC, RST=gpio_RST)
  File "/usr/lib/python3/dist-packages/luma/core/interface/serial.py", line 159, in __init__
    self._DC = self._configure(kwargs.get("DC"))
  File "/usr/lib/python3/dist-packages/luma/core/interface/serial.py", line 170, in _configure
    self._gpio.setup(pin, self._gpio.OUT)
  File "/usr/lib/python3/dist-packages/coral/enviro/rpi_gpio_periphery.py", line 33, in setup
    self._gpios[channels] = GPIO(channels, mode)
  File "/usr/lib/python3/dist-packages/periphery/gpio.py", line 43, in __init__
    self._open(pin, direction)
  File "/usr/lib/python3/dist-packages/periphery/gpio.py", line 91, in _open
    raise GPIOError(e.errno, "Setting GPIO direction: " + e.strerror)
periphery.gpio.GPIOError: [Errno 13] Setting GPIO direction: Permission denied
```

</details>

**Comment by manoj7410** [comment]
@kiteklan Did you try to change the udev rules for the GPIO ?

**Comment by kiteklan** [comment]
I did not tried it , I do not know what rules exactly I need write for the
environmental sensor.

Devadm info is as follows ,can you give me a ref to write this rule?


devadm info --path=/sys/class/gpio --attribute-walk


Udevadm info starts with the device specified by the devpath and then

walks up the chain of parent devices. It prints for every device

found, all possible attributes in the udev rules key format.

A rule to match, can be composed by the attributes of the device

and the attributes from one single parent device.


  looking at device '/class/gpio':

    KERNEL=="gpio"

    SUBSYSTEM=="subsystem"

    DRIVER==""


  looking at parent device '/class':

    KERNELS=="class"

    SUBSYSTEMS=="subsystem"

    DRIVERS==""

**Comment by kiteklan** [comment]
I had tried:
sudo nano /lib/udev/rules.d/60-rpi.gpio-common.rules

SUBSYSTEM=="bcm2835-gpiomem", KERNEL=="gpiomem", GROUP="dialout", MODE="0660"
SUBSYSTEM=="gpio", KERNEL=="gpiochip*", ACTION=="add", PROGRAM="/bin/sh -c 'chown root:dialout /sys/class/gpio/export /sys/class/gpio/unexport ; chmod 220 /sys/class/gpio/export /sys/class/g$
SUBSYSTEM=="gpio", KERNEL=="gpio*", ACTION=="add", PROGRAM="/bin/sh -c 'chown root:dialout /sys%p/active_low /sys%p/direction /sys%p/edge /sys%p/value ; chmod 660 /sys%p/active_

changed the root to Mendel

sudo udevadm control --reload-rules
sudo udevadm trigger --verbose
sudo /etc/init.d/udev restart

 and reboot  ,did not work.

seems like above commands + 

sudo chmod -R 777 /sys/class/gpio

it works , but can someone tell me a more elegant way.

**Comment by manoj7410** [comment]
@kiteklan One way is what you have mentioned. Other is mentioned here : https://stackoverflow.com/a/30940526/8321574 (This is for RPI but should also work for the Dev Board)

**Comment by kiteklan** [comment]
> @kiteklan One way is what you have mentioned. Other is mentioned here : https://stackoverflow.com/a/30940526/8321574 (This is for RPI but should also work for the Dev Board)

@manoj7410 thanks for the help, it looks better. I will try that too.

**Comment by manoj7410** [comment]
@kiteklan Did it work for you ? Let us know if we can close this ticket ?

**Comment by kiteklan** [comment]
Yes, it worked . Thanks for the support.

**Comment by manoj7410** [comment]
Thanks for confirming.
