### ISSUE TITLE
No binaries available for edgetpu_runtime for MacOS/Windows

### ISSUE THREAD

**Issue by feranick** [google-coral/edgetpu#46]
I am following the direction to install the edgetpu_runtime for MacOS in here:
https://coral.ai/docs/accelerator/get-started#on-mac

Yet, when I run:
`curl -O https://dl.google.com/coral/edgetpu_runtime_20200128.zip`

The file does not exist, it's just an empty 404 page. 

Following the link:
https://dl.google.com/coral/edgetpu_runtime_20200128.zip
leads to a Error 404 (not found).

**Comment by Namburger** [comment]
@feranick Sorry, a fix is in the work for this.
P.S. [related](https://github.com/google-coral/edgetpu-platforms/issues/19#issuecomment-580223884)

**Comment by Namburger** [comment]
Download link is [here](https://dl.google.com/coral/edgetpu_api/edgetpu_runtime_20200128.zip)!

**Comment by feranick** [comment]
All seems to be working perfectly. I am going to close this issue as completed.
