### ISSUE TITLE
New Compiler Yields Worse Performance Compared To Old Compiler

### ISSUE THREAD

**Issue by RobertChenKFC** [google-coral/edgetpu#466]
### Problem
I found out that a simple LeNet model performs worse when the model is compiled with the new compiler (version `16.0.384591198`) compared to when it is compiled with the old compiler (version `15.0.340273435`).  Here are the results of running the models compiled with the two compilers:
* `edgetpu_compiler` version `16.0.384591198`
```
accuracy: 0.982200026512146, time: 6.373909355024807 sec
accuracy: 0.982200026512146, time: 6.374022708972916 sec
accuracy: 0.982200026512146, time: 6.310401931987144 sec
accuracy: 0.982200026512146, time: 6.2700589230516925 sec
accuracy: 0.982200026512146, time: 6.276442887960002 sec
```
* `edgetpu_compiler` version `15.0.340273435`
```
accuracy: 0.982200026512146, time: 2.758575175073929 sec
accuracy: 0.982200026512146, time: 2.755294234957546 sec
accuracy: 0.982200026512146, time: 2.757836734992452 sec
accuracy: 0.982200026512146, time: 2.7426600340986624 sec
accuracy: 0.982200026512146, time: 2.759073080960661 sec
```
I ran the model on the MNIST test dataset 5 times to ensure that the times are consistent.

### Steps to Reproduce

1. Download [main.py](https://drive.google.com/file/d/1yXhj1Kdb6ZIEF19-LrJJKIE52VnepYs_/view?usp=sharing).
2. Install the new compiler (version `16.0.384591198`) and put the old compiler (version `15.0.340273435`) under a directory named `compiler`. In short, the directory structure should look like this:
```
├── compiler
│   ├── edgetpu_compiler
│   └── edgetpu_compiler_bin
│       ├── edgetpu_compiler
│       ├── ld-linux-x86-64.so.2
│       ├── libc++abi.so.1
│       ├── libc++.so.1
│       ├── libc.so.6
│       ├── libdl.so.2
│       ├── libm.so.6
│       ├── libpthread.so.0
│       ├── libresolv.so.2
│       └── NOTICE
└── main.py
```
3. Run `main.py` to train, convert, compile and run the model.
```
python main.py --train
python main.py            # new compiler
python main.py --old      # old compiler
```
[Here](https://drive.google.com/file/d/1oYJrvuyO-NMTAqsP_I2Gb1a0pb12zezq/view?usp=sharing) is the CPU tflite model. You can put it under a directory named `saved_model` to skip the training step and directly compile then run the model.

<details><summary>Click to expand!</summary>

### Issue Type

Performance

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

</details>

**Comment by hjonnala** [comment]
@RobertChenKFC can you please share old compiler edgetpu tflite file.

Thanks

**Comment by RobertChenKFC** [comment]
[Here](https://drive.google.com/file/d/1k2SSTJnXPOW_9RwNH6srULXziq26ZFCE/view?usp=sharing) is the model compiled with `edgetpu_compiler` version `15.0.340273435`.

**Comment by hjonnala** [comment]
Thanks for sharing the model. I can see the difference in inference time with old compiler  15.0.340273435 vs new compiler 16.0.384591198.

Unfortunately, I don't have` edgetpu_compiler `version `15.0.340273435`. Could you please share the binary so that I can test some other models to see if its the same thing with other models.

Please note that, If its the same thing for other models too, there won't be any fix for it as new compiler has lot of changes compared to old compiler.

**Comment by RobertChenKFC** [comment]
[Here](https://drive.google.com/file/d/1iRU7LYmLkALTGMpVr8M14KDC51YhHA9H/view?usp=sharing) is the `edgetpu_compiler` version `15.0.340273435`.

**Comment by hjonnala** [comment]
Hi @RobertChenKFC there are some changes happened to fully connected layer in the latest compiler. please check [this page](https://coral.ai/news/updates-07-2021/) for the updates. 

I have tried changing `model.add(tf.keras.layers.Dense(500, activation="relu"))` in main.py  with 100, 500, 1000, 1500. 

From results we can see after some point(for sizes with 1000, 1500) compiler 16 is giving better results than compiler 15.
```
v16 is with new compiler and v15 with old compiler. 
model.add(tf.keras.layers.Dense(100, activation="relu")) --> quant_model_100_edgetpu.tflite
model.add(tf.keras.layers.Dense(500, activation="relu")) --> quant_model_500_edgetpu.tflite


v16/quant_model_100_edgetpu.tflite
accuracy: 0.9782000184059143, time: 10.76969771401491 sec
v15/quant_model_100_edgetpu.tflite
accuracy: 0.9782000184059143, time: 2.846390360966325 sec
v16/quant_model_500_edgetpu.tflite
accuracy: 0.98089998960495, time: 10.885899387998506 sec
v15/quant_model_500_edgetpu.tflite
accuracy: 0.98089998960495, time: 3.39231375802774 sec
v16/quant_model_1000_edgetpu.tflite
accuracy: 0.9811000227928162, time: 10.531844380078837 sec
v15/quant_model_1000_edgetpu.tflite
accuracy: 0.9811000227928162, time: 67.16546348808333 sec
v16/quant_model_1500_edgetpu.tflite
accuracy: 0.9853000044822693, time: 10.357483166037127 sec
v15/quant_model_1500_edgetpu.tflite
accuracy: 0.9853000044822693, time: 93.86356512107886 sec
```

**Comment by hjonnala** [comment]
@RobertChenKFC please let us know if you have any more questions. If no questions, please close this issue.

Thanks

**Comment by RobertChenKFC** [comment]
@hjonnala Thanks for the help. I did some more experiments, and did discover the same phenomenon. However, I think that `edgetpu_compiler` version 15 still yields better performance, it's just that `edgetpu_compiler` version 16 produces a smaller model compared to `edgetpu_compiler` version 15. Please take a look at the results:
|units|new time (seconds)|old time (seconds)|CPU tflite size (MiB)|new TPU tflite size (MiB)|old TPU tflite size (MiB)|
|-----|------------------|------------------|---------------------|-------------------------|-------------------------|
|100  |6.243882366514299 |2.408482079015812 |0.2646942138671875   |1.7857666015625          |6.488822937011719        |
|200  |6.25467771050171  |2.4730497714917874|0.4996795654296875   |2.0865478515625          |6.789604187011719        |
|300  |6.353818561998196 |2.6587035655102227|0.7346649169921875   |2.2388916015625          |6.941947937011719        |
|400  |6.298276123998221 |2.7017273355158977|0.9696502685546875   |2.5396728515625          |7.246635437011719        |
|500  |6.272041838979931 |2.8733562079869444|1.2046356201171875   |2.6920166015625          |7.395072937011719        |
|600  |6.292480324511416 |37.58624592750857 |1.4396209716796875   |2.9967041015625          |7.699760437011719        |
|700  |6.30112204348552  |40.66145575149858 |1.6746063232421875   |3.1490478515625          |7.848197937011719        |
|800  |6.349519859519205 |47.40543129599246 |1.9095916748046875   |3.4498291015625          |8.152885437011719        |
|900  |6.440772537505836 |54.49139946499781 |2.1445770263671875   |3.7506103515625          |8.453666687011719        |
|1000 |6.5246084184909705|58.03899314350565 |2.3795623779296875   |3.9029541015625          |8.606010437011719        |
|1100 |6.634530679002637 |65.47824105800828 |2.6145477294921875   |4.1998291015625          |8.906791687011719        |
|1200 |6.562657013986609 |69.09330165601568 |2.8495330810546875   |4.3521728515625          |9.055229187011719        |
|1300 |6.503491541501717 |75.50310037849704 |3.0845184326171875   |4.6529541015625          |9.356010437011719        |
|1400 |6.5882061470038025|79.43094612000277 |3.3195037841796875   |4.8052978515625          |9.508354187011719        |
|1500 |6.650288957505836 |85.95130925400008 |3.5544891357421875   |5.1060791015625          |9.809135437011719        |
|1600 |6.6542518729984295|89.26617522198649 |3.7894744873046875   |5.2584228515625          |9.965385437011719        |
|1700 |6.621608280998771 |96.50864923300105 |4.0244598388671875   |5.5592041015625          |10.266166687011719       |
|1800 |6.6967593885201495|103.42981577799947|4.2594451904296875   |5.8599853515625          |10.566947937011719       |
|1900 |6.658734096999979 |107.68480410150369|4.4944305419921875   |6.0123291015625          |10.719291687011719       |
|2000 |6.756547453987878 |114.52934511851345|4.7294158935546875   |6.3170166015625          |11.020072937011719       |
|2100 |6.759006426989799 |117.494808771502  |4.9644012451171875   |6.4654541015625          |11.172416687011719       |
|2200 |6.737854531995254 |124.05990027749795|5.1993865966796875   |6.7662353515625          |11.469291687011719       |
|2300 |6.795098106988007 |127.69035165698733|5.4343719482421875   |6.9146728515625          |11.621635437011719       |
|2400 |6.768527749503846 |135.63098461201298|5.6693572998046875   |7.2193603515625          |11.926322937011719       |
|2500 |8.302506153500872 |141.74991896100983|5.9043426513671875   |7.5240478515625          |12.227104187011719       |
|2600 |13.412755152981845|145.89987568248762|6.1393280029296875   |7.6724853515625          |12.379447937011719       |
|2700 |19.581623586505884|152.77522941748612|6.3743133544921875   |7.9771728515625          |12.680229187011719       |
|2800 |25.8653238019906  |156.49362252249557|6.6092987060546875   |8.1256103515625          |12.828666687011719       |
|2900 |32.47178736051137 |163.30025002200273|6.8442840576171875   |8.4302978515625          |13.133354187011719       |
|3000 |170.51879365750938|166.59719396999571|7.0792694091796875   |8.5787353515625          |13.285697937011719       |

The only reason `edgetpu_compiler` version 16's performance is better than `edgetpu_compiler` version 15 when the number of units is between 600 and 2900 is because `edgetpu_compiler` version 16 produced a smaller model size that allows its on-chip memory usage to not exceed the 8MiB provided on the edge TPU, while `edgetpu_compiler` version 15 produced a model size that is too big, exceeding the amount of provided on-chip memory. However, if we look at when both `edgetpu_compiler`s are within the on-chip memory limits (ie. when the number of units are between 100 and 500), or when both `edgetpu_compiler`s exceed the on-chip memory limits (ie. when the number of units equals 3000), we can see that `edgetpu_compiler` version 15's performance is better than that of `edgetpu_compiler` version 16. This suggests to me that the new compiler has (significantly) worse FullyConnected performance than the old compiler. Please let me know if this performance issue is intended or not. Thank you.

On a side note, you mentioned that there were changes to the `edgetpu_compiler` related to FullyConnected layers mentioned on [this page](https://coral.ai/news/updates-07-2021/), but I couldn't find the related changes other than the new `split-fc` tools, which looks like a new tool rather than a changed applied to the `edgetpu_compiler`. Can you tell me which changes you were referring to? Thanks.

**Comment by RobertChenKFC** [comment]
@hjonnala I would like to know if there is any update on this, thanks.

**Comment by hjonnala** [comment]
Hi, from the results it is clear that inference time for `your model `compiled with compiler 15 are better than compiler 16 in some cases.

In general, it's not a great idea to compare inference time with different compiler versions. Instead, its better to test speed with different CPU architectures and different TPU devices similar to how [benchmarks](https://coral.ai/docs/edgetpu/benchmarks/) are calculated.

Thanks

**Comment by Drulludanni** [comment]
Why is that a better way to test the speed? We know the CPU's and TPU's on our devices and may not easily be able to change them, but compiling the models is very easy with different compiler versions and that is what we the end users want: the best performance we can get given the hardware we have.
