### ISSUE TITLE
Why some Coral products don't sell or ship to Canada?

### ISSUE THREAD

**Issue by ricardodeazambuja** [google-coral/edgetpu#467]
### Description

Hi,

Some friends in Canada are saying they can't buy Coral Dev Mini or Coral USB because nobody sends these products to Canada. Would someone know the reason for Canada to be excluded from only some of the products?

In the UK and I can buy any of the Coral products (when they are in stock, of course).

Cheers,
Ricardo

<details><summary>Click to expand!</summary> 

### Issue Type

Others

### Coral Device

USB Accelerator, Dev Board Mini

</details>

**Comment by ngrutas** [comment]
@ricardodeazambuja Those Coral products aren't certified to be sold in Canada. The only products that are available for the Canadian market are the Accelerator module and PCIe accelerators.

**Comment by beltrame** [comment]
Will they ever be certified? Oddly enough, they also don't ship to France, but they do ship to the rest of the EU.

**Comment by hjonnala** [comment]
Our team is actively working on obtaining certifications for as many markets as possible. Products datasheets would be updated if there is any progress.

Please check the datasheets from time to time for information on where the products can be sold. 

 For example --> https://coral.ai/docs/dev-board/datasheet/#certifications.  
Another example for USB Accelerator --> https://coral.ai/products/accelerator#tech-specs
