### ISSUE TITLE
Coral USB and edgetpu runtime v14 on windows10

### ISSUE THREAD

**Issue by ksp7518** [google-coral/edgetpu#468]
Hello, I use coral USB accelerator on windows10 with conda
After installing edgetpu runtime v14, the following error occurs when running the program, so I had to install v13 and used. Therefore, compiling is also given an option to be compatible with v13..  
`Process finished with exit code -1073741819 (0xC0000005)`
![image](https://user-images.githubusercontent.com/60207605/133231786-27da6258-129a-4848-bd20-86c3d2c7d261.png)

When debugging, an error occurs at the following location.
![image](https://user-images.githubusercontent.com/60207605/133232617-43361736-723c-4638-9851-a22baa607d33.png)
![image](https://user-images.githubusercontent.com/60207605/133232636-b0679b81-0da8-4ba1-ad15-b7add0f9b9aa.png)

What's the problem, how do I fix it? 
Thank you

**Comment by manoj7410** [comment]
@ksp7518 your query is not clear. Are you facing an execution related issue or compilation related issue ?

**Comment by ksp7518** [comment]
@manoj7410  I'm sorry for the lack of explanation.
I'm testing the yolov3,v5 detection model. 
I installed edgetpu runtime v14 and compilation is fine.
However, when I try to run the detection model, the above error occurs.
So, I re-install edgetpu runtime V13 and give V13 compatibility option when compiling to create a model, it runs fine.
Why does an error occur when running the detection model after installing edgetpu runtime v14?

**Comment by manoj7410** [comment]
@ksp7518 There is an issue with the runtime version 14 on Windows. engineering team is working on to resolve this but we don't have a timeline available.

**Comment by hjonnala** [comment]
This issue has been fixed. Please try with the updated [runtime](https://coral.ai/software/#edgetpu-runtime).
