### ISSUE TITLE
Can't run test model / installation issues on UbuntuVM in Proxmox

### ISSUE THREAD

**Issue by FlexxFR** [google-coral/edgetpu#469]
### Description

I believed to have successfully installed the **M.2 with Dual Edge TPU** on a Proxmox ubuntuVM.
I used this guide https://www.reddit.com/r/Proxmox/comments/n34f8q/proxmox_vm_ubuntu_2004_frigate_2x_google_coral_tpu/ and made some small adjustments to make it work. (https://www.reddit.com/r/Proxmox/comments/n34f8q/proxmox_vm_ubuntu_2004_frigate_2x_google_coral_tpu/hcll9wz/?utm_source=reddit&utm_medium=web2x&context=3)

Anyhow, from within Ubuntu everything seems fine.

**Lspci -nnk**
01:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
        Subsystem: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
        Kernel driver in use: apex
        Kernel modules: apex

 **lsmod | grep apex**
apex                   28672  5
gasket                114688  6 apex

**Edgetpu packages**
dpkg -l | grep edgetpu
ii  libedgetpu1-std:amd64                      16.0                                  amd64        Support library for Edge TPU

**gasket-dkms**
sudo apt install gasket-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
gasket-dkms is already the newest version (**1.0-17**).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**libedgetpu1-std**
sudo apt-get install libedgetpu1-std
Reading package lists... Done
Building dependency tree
Reading state information... Done
libedgetpu1-std is already the newest version (**16.0**).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Phyton3 version**
python3 --version
Python 3.8.10

**Tflite_runtime version**
 python3 -c 'print(__import__("tflite_runtime").__version__)'
2.5.0.post1

* I followed all "get started" steps
* blacklisted gasket/apex before updating
* Followed all installation steps 2a step 1, 2 and 3
* Removed blacklist
* reboot,
* After reboot, checks are successfull
* next PyCoral and model are downloaded, etc
* **However, when I run the model it crashes.....OR is stuck**
(Sometimes, after first clean reinstall/boot it's stuck. After that any subsequent run crashes)

Crash:
```
python3 examples/classify_image.py \
> --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
> --labels test_data/inat_bird_labels.txt \
> --input test_data/parrot.jpg
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/classify_image.py", line 121, in <module>
    main()
  File "examples/classify_image.py", line 71, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

Stuck forever:
```
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
....
```

After lots of troubleshooting I can't see where it goes wrong. 

### Issue Type

Build/Install

### Operating System

Ubuntu

### Coral Device

M.2 Accelerator with dual Edge TPU

### Programming Language

Python 3.8

### Relevant Log Output

```shell
:~/coral/pycoral$ dmesg | grep gasket
[    2.853379] gasket: loading out-of-tree module taints kernel.
[    2.853470] gasket: module verification failed: signature and/or required key missing - tainting kernel

:~/coral/pycoral$ dmesg | grep apex
[  377.367488] apex 0000:01:00.0: Process 1992 is opening a node held by 1977.
[  474.394312] apex 0000:01:00.0: entry 6144 is not free
[ 1026.199885] apex 0000:01:00.0: entry 6144 is not free

:~/coral/pycoral$ dmesg | grep 089a
[    0.282360] pci 0000:01:00.0: [1ac1:089a] type 00 class 0x0000ff
```

**Comment by hjonnala** [comment]
Hi, can you please paste the output of below commnad:

`python3 -c 'from pycoral.utils.edgetpu import get_runtime_version; print(get_runtime_version())'`

**Comment by FlexxFR** [comment]
Ofcourse, 
BuildLabel(COMPILER=6.3.0 20170516,DATE=redacted,TIME=redacted), RuntimeVersion(14)


As the command had some reference to pycoral I also executed the same command from ~/coral/pycoral$ but then it crashes.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/frank/coral/pycoral/pycoral/utils/edgetpu.py", line 24, in <module>
    from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
ModuleNotFoundError: No module named 'pycoral.pybind'

**Comment by hjonnala** [comment]
`ModuleNotFoundError: No module named 'pycoral.pybind' ` is expected when running from  ~/coral/pycoral$  as pycoral library is loading from `/home/frank/coral/pycoral/pycoral/` instead of `/lib/site-packages/pycoral`

We haven't tested the Coral devices on Virtual Machines. Can you please try on native operating system first?

**Comment by FlexxFR** [comment]
Ok, I was able to execute all getting starting steps on the proxmox/debian hypervisor itself and it succeeded.
So, at least the hardware is working!

One strange message about an inappropriate ioctl. Does this mean anything?

```
driver/beagle/beagle_kernel_top_level_handler.cc:131] Could not set performance expectation : 4 (Inappropriate ioctl for device)
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
17.0ms
7.7ms
7.7ms
7.7ms
7.7ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.75781
```

But what about the next steps to use this in a VM? I know it's not supported but also many have it working using PCIe passthrough. Anything about it being a dual edge TPU? Or the inappropriate ioctl?

**Comment by hjonnala** [comment]
Can you try with USB accelerator or dev board with ubuntuVM if you have them to check if its working for single edge tpu?

**Comment by FlexxFR** [comment]
Unfortunately I don't have those to test.

What about this message:
driver/beagle/beagle_kernel_top_level_handler.cc:131] Could not set performance expectation : 4 (Inappropriate ioctl for device)

**Comment by FlexxFR** [comment]
Found another solution! I'm using a LXC container within proxmox. TPU is working in this container :)
So, no need for the UbuntuVM anymore

**Comment by hjonnala** [comment]
Awesome. Can you please share the Hardware details. It would benefit others, who want to use `M.2 Accelerator with dual Edge TPU`.

Thanks

**Comment by FlexxFR** [comment]
PC Hardware is a "Medion Akoya S30003 MD 34902" where I removed the Wifi/Bluetooth card and installed the  Coral M.2 Accelerator with Dual Edge TPU. Unfortunately  I don't have much info about the motherboard.
![image](https://user-images.githubusercontent.com/65705235/133806321-00574fc8-070e-4069-bd7f-abce7e97e7b2.png)
![image](https://user-images.githubusercontent.com/65705235/133806552-d5d9d1a0-174d-4c48-a6be-ed0cdf1100b9.png)

It's running ProxMox version  6.4-13.


But another question, as this is a dual Edge TPU, I do I know both are used? Is it operating as a single TPU twice as fast or do I address them as two single TPU's?  I'm not sure if both are working as it requires 2 PCIe lanes to be active on the port but I'm not sure if that is the case?

**Comment by hjonnala** [comment]
Thanks for sharing hardware details!

can share the output of below command.

```
hemanth@hemanth-glaptop:~$ python3
Python 3.9.7 (default, Sep  3 2021, 06:18:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycoral.pybind._pywrap_coral import ListEdgeTpus as list_edge_tpus
>>> list_edge_tpus()
[{'type': 'usb', 'path': '/sys/bus/usb/devices/2-1'}]
>>> 
```

**Comment by FlexxFR** [comment]
```
root@frigatelxc ~# python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycoral.pybind._pywrap_coral import ListEdgeTpus as list_edge_tpus
>>> list_edge_tpus()
[{'type': 'pci', 'path': '/dev/apex_0'}]
```

**Comment by hjonnala** [comment]
It seems only one tpu is being used. You can also cross check number of  device ID with 089a in `lspci -vvv`. You should have two of them to use two edge tpus.

**Comment by FlexxFR** [comment]
Ok, good to know.
Currently there is only one listed.

```
root@pve:~# lspci -vvv | grep 089a
02:00.0 System peripheral: Device 1ac1:089a (prog-if ff)
        Subsystem: Device 1ac1:089a
```

Maybe due to the fact this PCIe slot only has one lane available or enabled. There is not much to find on this specific motherboard and in the BIOS I can't find any setting related this PCIe slot. That was a gamble anyway. I'm glad it's working at least in half capacity (probably enough anyway).

But to be sure: If both PCIe lanes would be enabled the dual TPU should be listed twice in lspci -vvv, right?
Would is also be listed as /dev/apex_1 ?

**Comment by hjonnala** [comment]
yes, you will see another device listed as /dev/apex_1

Ref: https://github.com/magic-blue-smoke/Dual-Edge-TPU-Adapter/issues/3#issuecomment-885755446
