### ISSUE TITLE
Internal compiler error. Aborting!

### ISSUE THREAD

**Issue by gasgallo** [google-coral/edgetpu#47]
Hi,

I'm trying to compile my model to edgeTPU but I get the following error:
```bash
Edge TPU Compiler version 2.0.291256449

Internal compiler error. Aborting!
```

I've realized that the compiler is very "picky" about the model structure and sometimes is very difficult to figure out what's wrong.
How can I properly debug this kind of error?

I/O are still in `float32`, but that's not an issue. I'm already using other models with same I/O and they can compile and run. Moreover, I'm specifying the right data type during conversion to tflite:
```python
import os

import tensorflow as tf
import numpy as np
from PIL import Image


model = 'model'
input_size = 160

dataset = []
directory_images = './models/' + model + '/data_test'
directory_saved = './models/' + model
for img in os.listdir(directory_images):
	data = Image.open(os.path.join(directory_images,img)).resize((input_size, input_size))
	data = np.asarray(data, dtype=np.float32)[np.newaxis, :]
	dataset.append((data-127.5)/128)

def representative_dataset_gen():
    for input_value in tuple(dataset):
        yield [input_value]

converter = tf.lite.TFLiteConverter.from_saved_model(directory_saved + "/saved")
#converter.allow_custom_ops=True
#converter.post_training_quantize=True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_model = converter.convert()

name = directory_saved + "/" + model
open(name + ".tflite", "wb").write(tflite_model)
```

Here's my model: [link](https://drive.google.com/file/d/16zXwcCA-LDu9EVK6VsHOxSb4pzAQcaav/view?usp=sharing)

**Comment by Namburger** [comment]
@gasgallo What tensorflow version are you using? We still suggest using tf1.15 for training/quantization for now.
Compiler currently doesn't tell much when it abort on a model currently, but we are working on making the error message better. Model requirements are hosted [here](https://coral.ai/docs/edgetpu/models-intro/#model-requirements).
You can use the tflite visualize tool for debugging the model: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/visualize.py

**Comment by gasgallo** [comment]
@Namburger I'm using tf2.1 because tf1.x doesn't support conversion to tflite of my models. This shouldn't be a big problem though, I've already used this pipeline with other models and it works fine.

I've checked model requirements and my model should be fine.

I'm visualizing my model with `netron`, unfortunately I cannot build `visualize` tool. Everything looks ok, the only different thing compared to other models that get compiled is more `quantize` nodes after `depthwise_conv2d` ops in the middle of the graph (previously I only had one after the input node). So maybe something is wrong with this?

Whenever you guys will have a little spare time, it would be great to debug this issue.

**Comment by Namburger** [comment]
@gasgallo my apologies, it has been a very busy week for me. I reserved sometimes to debug this model with a teammate tomorrow, I'll keep you updated on this.

**Comment by gasgallo** [comment]
@Namburger no worries, thanks for your time!

**Comment by Namburger** [comment]
@gasgallo I've generated the `model.html` from the tflite/visualize tool, I'm attaching it here.
[model.html.zip](https://github.com/google-coral/edgetpu/files/4172439/model.html.zip)
If you look at this line:
```
2489	mobilenet0_conv1_fwd_5	INT8	[1, 80, 80, 1]	3441	{'quantized_dimension': 0, 'scale': [4.6099e-41], 'min': [0.0], 'max': [1.1754944e-38], 'details_type': 0, 'zero_point': [-128], 'details': None}
```
the scale seems abnormally small at `4.6099e-41` causing some error. Can I ask if you were able to run inference with your tensorflow model (before quantization) as well as tflite model and see if it give you the result you want?

**Comment by gasgallo** [comment]
@Namburger thanks for the hint. My TF model works fine, but I didn't validate the TFLite model outputs. I'll double-check that and report eventual anomalies here.

**Comment by Namburger** [comment]
@gasgallo I see, let me know the result. This seems like a bug during Post Training Quantization to me if the tensorflow model runs fine.

**Comment by Namburger** [comment]
@gasgallo were you able to test your tflite(CPU) model before compiling to run with edgetpu?

**Comment by gasgallo** [comment]
@Namburger I'm very sorry for not having followed up this issue! Actually I had other issues when trying to validate the `tflite` model (actually issues during conversion) and I had to put this task on hold to complete other higher priority tasks.

I'll update as soon as I'll get over this task again.

**Comment by Namburger** [comment]
@gasgallo no worries!

**Comment by Namburger** [comment]
@gasgallo I believe this is a tflite conversion issue since the scale became very small and was rejected by the compiler. My suggestion is to open in issue [here](https://github.com/tensorflow/tensorflow/issues) if still need helps. 
Feel free to reference this issue.
