### ISSUE TITLE
edgetpu.swig.edgetpu_cpp_wrapper

### ISSUE THREAD

**Issue by arun-kumark** [google-coral/edgetpu#470]
### Description

Hi,

I am running the MLMark benchmarking scripts on my system on Windows 10. 
More details about the system are in the header of the script below. The parrot example runs fine on the machine.
But when I run the MLMark scripts,  I am getting the following error
**ModuleNotFoundError: No module named 'edgetpu.swig.edgetpu_cpp_wrapper'**

```
$ harness/mlmark.py -c config/tflite-tpu-mobilenet-int8-*
-INFO- -------------------------------------------------------------------------
-------
-INFO- Welcome to the EEMBC MLMark(tm) Benchmark!
-INFO- -------------------------------------------------------------------------
-------
-INFO- MLMark Version       : 1.0.3
-INFO- Python Version       : 3.8
-INFO- CPU Name             : Intel(R) Core(TM) i5-6442EQ CPU @ 1.90GHz
-INFO- Total Memory (MiB)   : 48.828125
-INFO- # of Logical CPUs    : 4
-INFO- Instruction Set      : AMD64
-INFO- OS Platform          : Windows-10-10.0.17763-SP0
-INFO- -------------------------------------------------------------------------
-------
-INFO- Models in this release:
-INFO-     resnet50       : ResNet-50 v1.0 [ILSVRC2012]
-INFO-     mobilenet      : MobileNet v1.0 [ILSVRC2012]
-INFO-     ssdmobilenet   : SSD-MobileNet v1.0 [COCO2017]
-INFO- -------------------------------------------------------------------------
-------
-INFO- Parsing config file config/tflite-tpu-mobilenet-int8-accuracy.json
Traceback (most recent call last):
  File "harness/mlmark.py", line 154, in <module>
    begin(args)
  File "harness/mlmark.py", line 129, in begin
    parseConfig(config)
  File "harness/mlmark.py", line 104, in parseConfig
    finalParams, results = runTask(task)
  File "harness/mlmark.py", line 62, in runTask
    pkg = __import__(task['workload'])
  File "D:\mlmark\targets\google_tpu\workloads\mobilenet\__init__.py", line 18,
in <module>
    from .Net import MobileNet
  File "D:\mlmark\targets\google_tpu\workloads\mobilenet\Net.py", line 13, in <m
odule>
    from edgetpu.basic.basic_engine import BasicEngine
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\edgetpu\__i
nit__.py", line 15, in <module>
    import edgetpu.basic.edgetpu_utils as utils
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\edgetpu\bas
ic\edgetpu_utils.py", line 15, in <module>
    import edgetpu.swig.edgetpu_cpp_wrapper as wrapper
ModuleNotFoundError: No module named 'edgetpu.swig.edgetpu_cpp_wrapper'
```

Could you help me in debugging this issue.

Kind Regards
Arun

<details><summary>Click to expand!</summary>

### Issue Type

Support

### Operating System

Windows 10

### Coral Device

M.2 Accelerator B+M

### Programming Language

Python 3.8

</details>

**Comment by hjonnala** [comment]
HI @arun-kumark edgetpu api is deprecated. It has been modified to libcoral api for c++ and pycoral api for python.

However, you can try installing edgetpu api form with this [whl](https://dl.google.com/coral/edgetpu_api/edgetpu-2.12.1-py3-none-any.whl) from [software](https://coral.ai/software/#alternative-packages) page. After installing please check if you have edgetpu_cpp_warraper.py in `Lib/site-packages/edgetpu/swig`

**Comment by arun-kumark** [comment]
Hi,
I did the installation of whl from the link.
The error somewhat changed as below:


```
chris@DESKTOP-N4KQOP6 MINGW64 /d/mlmark (main)
$ harness/mlmark.py -c config/tflite-tpu-mobilenet-int8-*
    pkg = __import__(task['workload'])
  File "D:\mlmark\targets\google_tpu\workloads\mobilenet\__init__.py", line 18, in <module>
    from .Net import MobileNet
  File "D:\mlmark\targets\google_tpu\workloads\mobilenet\Net.py", line 13, in <module>
    from edgetpu.basic.basic_engine import BasicEngine
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\edgetpu\basic\basic_engine.py", line 17, in <module>
    from edgetpu.swig.edgetpu_cpp_wrapper import BasicEnginePythonWrapper
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\edgetpu\swig\edgetpu_cpp_wrapper.py", line 28, in <module>
    _edgetpu_cpp_wrapper = swig_import_helper()
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\edgetpu\swig\edgetpu_cpp_wrapper.py", line 20, in swig_import_helper
    import _edgetpu_cpp_wrapper
ModuleNotFoundError: No module named '_edgetpu_cpp_wrapper'
```


_But there is no swig inside site-packages still._

Kind Regards
Arun

**Comment by hjonnala** [comment]
It seems edgetpu api does not work with windows. You can try with linux or MacOS with` python 3.5, 3,6 or 3.7`.

As edgetpu api deprecated you can use libcoral api for c++ and/or pycoral api for python. 

If you are trying to run benchmarks you can try [inference_benchmarks.py](https://github.com/google-coral/pycoral/blob/master/benchmarks/inference_benchmarks.py). You might have to change this [line](https://github.com/google-coral/pycoral/blob/master/benchmarks/inference_benchmarks.py#L62) with these [architectures](https://github.com/google-coral/pycoral/tree/master/benchmarks/reference).
ex:`machine = 'aarch64'` or` machine='x86_64'`.

Pleas note that, here you are comparing benchmarks  with different CPU architectures.

Thanks


![Screenshot from 2021-09-17 15-11-39](https://user-images.githubusercontent.com/86132058/133859363-e3c6a046-4e2f-4706-9856-a5fb74637a98.png)

**Comment by hjonnala** [comment]
Closing this issue as edgeptu is deprecated and not supported for windows.
