### ISSUE TITLE
M.2 Dual Edge TPU Not Showing up

### ISSUE THREAD

**Issue by MrAnonymous722** [google-coral/edgetpu#472]
### Description

Using a Lenovo M910Q. I was hoping to see at least one coral device, but I don't see either. I see that MSI-X is enabled on my M.2 Drive, but this is a B+M key'd slot so I cannot try to use my coral there. I didn't get any errors while going through the installation steps outlined [here](https://coral.ai/docs/m2/get-started/). But when running `lspci -nn | grep 089a` there is no output and `ls /dev/apex*` returns `No such file or directory`
I have disabled secure boot. This is using a native A+E key slot on my motherboard that was previously occupied by a WiFi + Bluetooth chip. When running `lspci -vv` and checking this chip's capabilities I see `MSI: Enable+`, but I suspect this is just because this chip doesn't use MSI-X. Any help would be so greatly appreciated as I would love to use this module and not try to find another that works with my computer.

<details><summary>Click to expand!</summary>

### Issue Type

Support

### Operating System

Ubuntu

### Coral Device

M.2 Accelerator with dual Edge TPU

</details>

edit: fixed link

**Comment by hjonnala** [comment]
can you share the output of below commands:

- dmesg
- lspci -vvv

**Comment by MrAnonymous722** [comment]
[dmesg.txt](https://pastebin.pl/view/73fd6dbf)
[lspci.txt](https://pastebin.pl/view/b0607504)
edit: links to readable files instead of download only

**Comment by hjonnala** [comment]
Thanks.. please share the output of below commands also.

- modinfo gasket
- modinfo apex

**Comment by MrAnonymous722** [comment]
[gasket.txt](https://pastebin.pl/view/0da98cdb)
[apex.txt](https://pastebin.pl/view/ce9ef0cd)

**Comment by manoj7410** [comment]
@MrAnonymous722 I am not able to see the Device ID 089a in any of these logs. Is the device connected properly ?

**Comment by manoj7410** [comment]
@MrAnonymous722 Are you still facing the same issue ?
