### ISSUE TITLE
Inference on TFLite Model Gets Stuck In An Infinite Loop

### ISSUE THREAD

**Issue by RobertChenKFC** [google-coral/edgetpu#476]
### Problem
I'm trying to run inference on a model on the edge TPU, but there seems to be some issues. When I run the model without setting any environment variables, I get this error:
```
F driver/usb/usb_driver.cc:857] transfer on tag 1 failed. Abort. Deadline exceeded: USB transfer error 2 [LibUsbDataOutCallback]
Aborted (core dumped)
```
and the lights on the edge TPU USB accelerator gets stuck blinking. I have to unplug then replug the USB cable to get it working again. However, when I set the environment variable `USB_ENABLE_BULK_DESCRIPTORS_FROM_DEVICE=1` and then run the model, I no longer receive that error, but inference gets stuck in an infinite loop and never terminates.

### Steps to Reproduce
1. Download these files:
* [main.py](https://drive.google.com/file/d/17BZ0kY-3cDn112tsFlZDhJFWKfeVejJf/view?usp=sharing)
* [quant_model_edgetpu_new.tflite](https://drive.google.com/file/d/1btA-XPE0hugj-srzf4p6OmfAu7PEBAng/view?usp=sharing) (compiled with `edgetpu_compiler` version `16.0.384591198`)
2. Run inference on the tflite model with `main.py`
```
python main.py quant_model_edgetpu_new.tflite
```

### Notes
I googled the first error, and found two related issues. One of the issues is related to power draw, so I made sure that I installed `libedgetpu1-std` instead of `libedgetpu1-max`, and that the USB cable is directly connected to a USB port on my PC, instead of going through a USB hub. The other issue is related to big input/output tensor sizes, which seems to be related to my issue, because I can successfully run inference on the same model with smaller input/output sizes.

However, if I compile the CPU tflite model with `edgetpu_compiler` version `15.0.340273435` instead of version `16.0.384591198`, even though all the same operations are mapped to the TPU, I can now run inference on the model without any problems, so this issue seems to only appear with the latest version of the `edgetpu_compiler`. Here are the related files for your reference:
* [quant_model.tflite](https://drive.google.com/file/d/1aAUTOvo1v6o27egKi2LmO2I7-COAKFiU/view?usp=sharing) (CPU)
* [quant_model_edgetpu.tflite](https://drive.google.com/file/d/1r4T8xHv3-NF5apyfbOe6k52s0-oDig47/view?usp=sharing) (compiled with `edgetpu_compiler` version `15.0.340273435`)

You can run
```
python main.py quant_model_edgetpu.tflite
```
to try inference on the model compiled with `edgetpu_compiler` version `15.0.340273435`.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, With the latest changes it is expected to get the below error to avoid overheating of USB accelerator.
```
F driver/usb/usb_driver.cc:857] transfer on tag 1 failed. Abort. Deadline exceeded: USB transfer error 2 [LibUsbDataOutCallback]
Aborted (core dumped)
```

**Comment by RobertChenKFC** [comment]
@hjonnala Thanks for the information. So it is expected behavior that the CPU tflite model compiled with `edgetpu_compiler` version `15.0.340273435` can be run successfully on the edge TPU USB accelerator, but the same CPU tflite model compiled with `edgetpu_compiler` version `16.0.384591198` cannot be successfully run because of potential overheating issues? Does this mean that if the CPU tflite model is compiled with `edgetpu_compiler` version `15.0.340273435`, it is possible that the USB accelerator will overheat without warning?

**Comment by hjonnala** [comment]
Hi, With USB accelerator for models with  15.0 thermal throttling is controlled at runtime level. But the inference shuts off when the temp raises.

with 16.0 such model are not allowed in first place.
