### ISSUE TITLE
Anchor free on edgetpu

### ISSUE THREAD

**Issue by bhack** [google-coral/edgetpu#48]
As ancor free One stage object detection and kpts regression are going to be more and more popular can you add some kind of example on how to standardize ti handle these kind of models without using any Google/Coral team "canned solution"?

Generally all these research papers prefer pythorch code relase so It would be really useful to know to handle these models in Coral with an optimized pieline.

Also point 2 at [coral-posenet](https://github.com/google-coral/project-posenet/blob/master/README.md#how-does-it-work-) mention some optimized custom ops for heatmap handling that instead It could be useful in general for anchor-free models.

See also:
https://github.com/tensorflow/hub/issues/424
https://github.com/google-coral/tutorials/issues/1
https://github.com/google-coral/project-posenet/issues/16

**Comment by mtyka** [comment]
Currently we only support model conversion from tflite/tf though we hope to broaden support eventually. However assuming these models use supported ops there's no reason they couldn't be compiled for the edgetpu.
As for point 2, the posenet decoder (heatmaps->keypoints) is here: 
https://github.com/google-coral/edgetpu/blob/master/src/cpp/posenet/posenet_decoder.cc
We typically build this right into the graph as a custom op but you certainly don't have to - you could take this as a standalone decoder library and call it with any heatmaps/offsets/displacements.

**Comment by bhack** [comment]
So why you don't document or try any of the anchor-free model as an example so you will see if you can see if there is any tflite/tf bottleneck in the conversion?

Or is it just that Coral team don't find anchor free model enough interesting for the coral platform?

**Comment by bhack** [comment]
Also, I meant as a team you can just take one of this model, check with tflite/tf, and try to expand some helper objects API so that we can support kypts or kypts + bbox outputs instead of bbox only:
https://github.com/google-coral/edgetpu/blob/master/edgetpu/detection/engine.py#L24

**Comment by mtyka** [comment]
Hi, thanks for suggesting some alternative models. They're definitely interesting as are many other models. Unfortunately, given the small size of our team, we're able to test only a limited number of models, and this one is currently not a priority.
All the tools necessary to convert and compile models are available publicly, so we encourage you to experiment with different model architectures.

**Comment by bhack** [comment]
@mtyka At least could you plan expand class/bbox to support also arbitrary keypoints regression in support classes?
https://github.com/google-coral/edgetpu/blob/master/edgetpu/detection/engine.py#L24

**Comment by bhack** [comment]
Ok the new ticket on this specific subtopic is at https://github.com/google-coral/edgetpu/issues/51
