### ISSUE TITLE
Is there a way to download older compiler version?

### ISSUE THREAD

**Issue by xadrianzetx** [google-coral/edgetpu#480]
### Description

I'm having some problems with compiler version `16.0` (described in #453), and was wondering if it's possible to grab previous version of `edgetpu-compiler`. Running

```
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
sudo apt-get update
apt-cache madison edgetpu-compiler
```
shows that no other version is available, but maybe I'm just looking in the wrong place.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
[Here](https://github.com/google-coral/edgetpu/files/7278734/compiler.zip)  is the edgetpu_compiler version 15.0.340273435.

**Comment by xadrianzetx** [comment]
Thank you! Is it hosted anywhere public? I would need it to run as part of my CI job, but quick glance at the license tells me that I'm not really allowed to keep it in the public repo.

**Comment by hjonnala** [comment]
Currently we are not maintaing legacy compiler versions. However, We have Edge TPU Compiler version 14.1.317412892 hosted public [here](https://github.com/google-coral/edgetpu/tree/master/compiler/x86_64). I will pass this to the internal team as feature request.

Thanks

**Comment by xadrianzetx** [comment]
Sounds great, thanks!

**Comment by Lagree007** [comment]
> [Here](https://github.com/google-coral/edgetpu/files/7278734/compiler.zip) is the edgetpu_compiler version 15.0.340273435.

How is this supposed to be inatalled. It has no .sh file

**Comment by hjonnala** [comment]
Hi @Lagree007 no need of any installation. Just extract the zip folder and run the edgetpu_compiler command.

Please make sure your system has these requirements: https://coral.ai/docs/edgetpu/compiler/#system-requirements

```
hemanth@hemanth-glaptop:~$ ./Downloads/compiler/edgetpu_compiler -s test_data/mobilenet_v1_0.5_160_quant.tflite
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 405 ms.

Input model: test_data/mobilenet_v1_0.5_160_quant.tflite
Input size: 1.33MiB
Output model: mobilenet_v1_0.5_160_quant_edgetpu.tflite
Output size: 1.54MiB
On-chip memory used for caching model parameters: 1.48MiB
On-chip memory remaining for caching model parameters: 6.22MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 31
Operation log: mobilenet_v1_0.5_160_quant_edgetpu.log

Operator                       Count      Status

CONV_2D                        15         Mapped to Edge TPU
SOFTMAX                        1          Mapped to Edge TPU
DEPTHWISE_CONV_2D              13         Mapped to Edge TPU
AVERAGE_POOL_2D                1          Mapped to Edge TPU
RESHAPE                        1          Mapped to Edge TPU
```
