### ISSUE TITLE
Segmentation Fault When Compiling EfficientNet Lite0 INT8 Model

### ISSUE THREAD

**Issue by SunAriesCN** [google-coral/edgetpu#482]
### Description

When I compile my [efficientnet-lite0-int8.tflite](https://github.com/SunAriesCN/image-classifier/blob/master/models/efficientnet-lite0-int8.tflite) with the [Web IPython Scripts](https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb) your team supported, I get the following Segmentation Fault Error.
```
Edge TPU Compiler version 16.0.384591198
/usr/bin/edgetpu_compiler: line 3:  1657 Segmentation fault      (core dumped) ${d}/edgetpu_compiler_bin/ld-linux-x86-64.so.2 --library-path ${d}/edgetpu_compiler_bin ${d}/edgetpu_compiler_bin/edgetpu_compiler "$@"
```

Please tell me how to solve this problem.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Mac OS

### Coral Device

Dev Board

### Programming Language

C++, Other

### Relevant Log Output

```shell
Edge TPU Compiler version 16.0.384591198
/usr/bin/edgetpu_compiler: line 3:  1657 Segmentation fault      (core dumped) ${d}/edgetpu_compiler_bin/ld-linux-x86-64.so.2 --library-path ${d}/edgetpu_compiler_bin ${d}/edgetpu_compiler_bin/edgetpu_compiler "$@"
```
</details>

**Comment by hjonnala** [comment]
Hi, upload the file to co lab and run the command below. You would be able to compile the model.

`! edgetpu_compiler -s /content/efficientnet-lite0-int8.tflite`

Thanks.

**Comment by SunAriesCN** [comment]
Thx
