### ISSUE TITLE
HIB Error using Dual TPU, USB works OK (Windows 10)

### ISSUE THREAD

**Issue by mattncsu** [google-coral/edgetpu#484]
### Description

I recently got a dual TPU board and tried running the demo code and I get a HIB error:
```
C:\Users\Matt\Desktop\smartcam\coral\pycoral>python examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000000010, hib_first_error_status = 0000000000000010
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000000010, hib_first_error_status = 0000000000000010
```

If I disable the cards in device manager and leave only the USB TPU plugged in, the code works as expected. I am running the latest v13 (202110119) since I read in other issues that v14 is not compatible with Window 10.  I can see both devices in the device manager and using this script I found in another issue I was reading.

C:\Users\Matt\Desktop\edgetpu_runtime_202110119>python lstpu.py
0 USB /sys/bus/usb/devices/4-4
1 PCI \\?\ApexDevice0
2 PCI \\?\ApexDevice1

Aside from ditching Windows (working on setting up dual boot), any advice for resolving the HIB error?

Edit: Setup dual boot with Ubuntu and test case works as expected there using dual tpu. Confirms it could be a Windows only problem.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug, Support

### Operating System

Windows 10

### Coral Device

M.2 Accelerator with dual Edge TPU

### Programming Language

Python 3.9

### Relevant Log Output

```shell
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000000010, hib_first_error_status = 0000000000000010
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000000010, hib_first_error_status = 0000000000000010
```
</details>

**Comment by hjonnala** [comment]
Glad to know it's working with Ubuntu. Can you please share your hardware details that would help others to know this hardware works with dual edge tpu.

Thanks

**Comment by mattncsu** [comment]
@hjonnala I'm using a pre-production adapter board made by @magic-blue-smoke (based on a PCIe switch) and an m.2 NVME to PCIe adapter board, photos and more info in this issue:https://github.com/magic-blue-smoke/Dual-Edge-TPU-Adapter/issues/3#issuecomment-889455901

**Comment by muxamilian** [comment]
Got the exact same error when running on Linux on x86-64. Restarting the device didn't help but powering it off and on again (physically disabling the power supply) and then restarting it fixed the error.
