### ISSUE TITLE
pose classification example doesn't get the test data

### ISSUE THREAD

**Issue by cku239** [google-coral/edgetpu#486]
### Description

I'm trying to run the movenet_pose_estimation.py example.

It fails saying the tflite file is missing  and yes it is.

I ran the bash command to get the files for movenet pose estimation example and it fails.

I ran the bash command without specifying a file to retrieve all the files for all the examples.
This retrieves the files for the other examples but not for pose classification example.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

```shell
"bash examples/install_requirements.sh movenet_pose_estimation.py
Usage:
  install_requirements.sh [filename]

  Provide the name of an example file in this directory to
  download only the files required for that example.
  If no filename provided, it downloads all example files.
  All files go into the pycoral/test_data/ directory."
```
</details>

**Comment by manoj7410** [comment]
@cku239 Can you please paste the complete error to take a look on ? Please mention the project or repo from which you are following the instructions.

**Comment by hjonnala** [comment]
@cku239 we need to update [install_requirements.sh](https://github.com/google-coral/pycoral/blob/master/examples/install_requirements.sh). Meanwhile you can get `test_data/movenet_single_pose_lightning_ptq_edgetpu.tflite` and` test_data/squat.bmp` form this [test_data_repo](https://github.com/google-coral/test_data).

**Comment by manoj7410** [comment]
@cku239 This has been fixed. Please try to run the demo again.
