### ISSUE TITLE
Internal compiler error. Aborting!

### ISSUE THREAD

**Issue by JiatianWu** [google-coral/edgetpu#49]
_Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
 
 **System information**
 
 * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
 * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
 * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
 * TensorFlow installed from (source or binary): Docker image latest-gpu-py3
 * TensorFlow version (use command below): 1.15.0
 * Python version: 3.6
 * Bazel version (if compiling from source): -
 * GCC/Compiler version (if compiling from source): -
 * CUDA/cuDNN version: 10.2
 * GPU model and memory: TITAN Xp / 12 GB
 
 I have created a fully-quantized tf lite model from a saved model. But trying to compile it with the edgetpu_compiler, I get an error:
 
 ```
(venv) jiatian@desktop:~/tmp$ edgetpu_compiler saved_model_quant.tflite 
Edge TPU Compiler version 2.0.267685300

Internal compiler error. Aborting! 

 ```
Also tried the latest compiler, got same error:

```
Edge TPU Compiler version 2.0.291256449

Internal compiler error. Aborting! 
```

Below is the how I did quantize the tflite file from saved model:

```
    def generate_datasets(self):
        num_calibration_steps = 10
        for _ in range(num_calibration_steps):
            input = np.random.random_sample((1, self.img_height, self.img_width, 3))
            yield [np.array(input, dtype='float32')]

    def convert_savedModel_quant_tflite(self, savedModel_dir):
        converter = tf.lite.TFLiteConverter.from_saved_model(savedModel_dir)
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = self.generate_datasets
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.float32
        converter.inference_output_type = tf.float32
        tflite_quant_model = converter.convert()
        save_tflite_path = savedModel_dir + '/saved_model_quant.tflite'
        open(save_tflite_path, "wb").write(tflite_quant_model)
```

The tflite file is linked (14.5MB):
[saved_model_quant.zip](https://github.com/google-coral/edgetpu/files/4150765/saved_model_quant.zip)

**Comment by Namburger** [comment]
Hi @JiatianWu 
It seems the model is hitting a HW limit on the TPU's memory. Could you try syncing the model?
I've forwarded your model to our team for review.

**Comment by JiatianWu** [comment]
@Namburger How to sync the model? Thanks.

**Comment by Namburger** [comment]
I'm sorry, that was a typo, `shrink` is the word I meant to say.

**Comment by Naveen-Dodda** [comment]
Hello Jaitian,

It's is not possible to reproduce the issue with the data you have provided. Could you please provide additional details about your model ? Also did you apply visulaize.py to see if there are any unsupported ops https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/visualize.py. 

Thanks

**Comment by JiatianWu** [comment]
I shrink the model size and it can compile now. Gonna close this issue and thanks for the help.

**Comment by Namburger** [comment]
@JiatianWu 
As it turned out, we found a bug in our compiler that was causing this issue, you're original model should works fine. We've since fixed it and your model is compiling fine. Unfortunately, we can't give out details on the next compiler release, but please stay tuned to our [news](https://coral.ai/news) page for the next release!

**Comment by JiatianWu** [comment]
Thanks for sharing this info. Excited to try the next version compiler.
