### ISSUE TITLE
tflite model maker object detection generated model can't compile

### ISSUE THREAD

**Issue by davidgressett** [google-coral/edgetpu#490]
### Description

Following along with the model maker object detection tutorial here:
https://www.tensorflow.org/lite/tutorials/model_maker_object_detection

I have a custom training set with just 9 classes, recognizing cars, trucks, pedestrians, etc. 

And this all works just fine for using EfficientDet-Lite1 as the model. I can compile and run that model and it works. 

However, I need something more performant, so after doing transfer learning from my dataset for effecientdet-lite0, with the exact same steps as in the tutorial, I go to compile the exported tflite model, and encounter an error:

**Compilation failed: Compilation failed due to large activation tensors in the model.** 

Compiling from ubuntu using version 16.0.384591198. 

Therefore, can't produce a tpu compatible model from efficientdet-lite0. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
can you try with this command ` !edgetpu_compiler  -s -d model.tflite`. If it fails please share the tflite model.

**Comment by davidgressett** [comment]
Thanks for the direction. 

Using those parameters, the model does compile, but given the percentage of operations done on the CPU, not sure we can call this "success". 

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 136
Number of operations that will run on CPU: 131

Operator                       Count      Status

DEPTHWISE_CONV_2D              32         Mapped to Edge TPU
DEPTHWISE_CONV_2D              48         More than one subgraph is not supported
QUANTIZE                       1          Mapped to Edge TPU
CONV_2D                        54         Mapped to Edge TPU
CONV_2D                        48         More than one subgraph is not supported
DEQUANTIZE                     2          Operation is working on an unsupported data type
CUSTOM                         1          Operation is working on an unsupported data type
ADD                            11         More than one subgraph is not supported
ADD                            31         Mapped to Edge TPU
MAX_POOL_2D                    10         Mapped to Edge TPU
MAX_POOL_2D                    4          More than one subgraph is not supported
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  2          More than one subgraph is not supported
RESHAPE                        10         More than one subgraph is not supported
RESIZE_NEAREST_NEIGHBOR        4          More than one subgraph is not supported
RESIZE_NEAREST_NEIGHBOR        8          Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 

Attached the log.
[detector_edgetpu.log](https://github.com/google-coral/edgetpu/files/7341883/detector_edgetpu.log)

**Comment by hjonnala** [comment]
you can try this `!edgetpu_compiler -s -a -d model.tflite`

**Comment by davidgressett** [comment]
This completely fails, with the final step looking like this:

ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 1 ops
Intermediate tensors: tfl.quantize
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Error: search for valid delegate failed. Can not compile model for Edge TPU.

**Comment by davidgressett** [comment]
Since a google provided tflite model maker created model can't compile with the tpu compiler, with fewer classes than the original, in the smallest possible size, this sure seems like a bug IMO. 

The parameters we've tried so far haven't produced anything usable. Please say we aren't concluding that the tpu compiler doesn't support efficientdetlite0. Are there any other tricks worth trying?

**Comment by hjonnala** [comment]
can you please share your tflite model?

Thanks

**Comment by davidgressett** [comment]
[tfmmeffdetl0.zip](https://github.com/google-coral/edgetpu/files/7355689/tfmmeffdetl0.zip)

Please see the attached model that exhibits this behavior.

**Comment by hjonnala** [comment]
Please try the command below to map more number of operations to edgetpu.

`!edgetpu_compiler -s -i "class_net/class-predict/BiasAdd;class_net/class-predict/separable_conv2d_4;class_net/class-predict/separable_conv2d;class_net/class-predict/bias"  "detector.tflite"`
```

Number of Edge TPU subgraphs: 1
Total number of operations: 267
Operation log: detector_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 261
Number of operations that will run on CPU: 6

Operator                       Count      Status

DEQUANTIZE                     2          Operation is working on an unsupported data type
DEPTHWISE_CONV_2D              80         Mapped to Edge TPU
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  1          Mapped to Edge TPU
CONCATENATION                  1          More than one subgraph is not supported
MAX_POOL_2D                    14         Mapped to Edge TPU
RESHAPE                        9          Mapped to Edge TPU
RESHAPE                        1          More than one subgraph is not supported
CUSTOM                         1          Operation is working on an unsupported data type
ADD                            42         Mapped to Edge TPU
CONV_2D                        102        Mapped to Edge TPU
QUANTIZE                       1          Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        12         Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 
```

**Comment by davidgressett** [comment]
Using the given parameters produced the same results. :) :)

**Comment by hjonnala** [comment]
Max operations can be mapped to edgetpu for the given model are 261. Are you getting the same ?

**Comment by davidgressett** [comment]
Exactly the same.

**Comment by 1treu1** [comment]
> Please try the command below to map more number of operations to edgetpu.
> 
> `!edgetpu_compiler -s -i "class_net/class-predict/BiasAdd;class_net/class-predict/separable_conv2d_4;class_net/class-predict/separable_conv2d;class_net/class-predict/bias" "detector.tflite"`
> 
> ```
> 
> Number of Edge TPU subgraphs: 1
> Total number of operations: 267
> Operation log: detector_edgetpu.log
> 
> Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
> Number of operations that will run on Edge TPU: 261
> Number of operations that will run on CPU: 6
> 
> Operator                       Count      Status
> 
> DEQUANTIZE                     2          Operation is working on an unsupported data type
> DEPTHWISE_CONV_2D              80         Mapped to Edge TPU
> LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
> CONCATENATION                  1          Mapped to Edge TPU
> CONCATENATION                  1          More than one subgraph is not supported
> MAX_POOL_2D                    14         Mapped to Edge TPU
> RESHAPE                        9          Mapped to Edge TPU
> RESHAPE                        1          More than one subgraph is not supported
> CUSTOM                         1          Operation is working on an unsupported data type
> ADD                            42         Mapped to Edge TPU
> CONV_2D                        102        Mapped to Edge TPU
> QUANTIZE                       1          Mapped to Edge TPU
> RESIZE_NEAREST_NEIGHBOR        12         Mapped to Edge TPU
> Compilation child process completed within timeout period.
> Compilation succeeded! 
> ```

This doesn't work for me xc
