### ISSUE TITLE
bulk out for header failed. Abort. Unknown: USB transfer error 1 [LibUsbDataOutCallback]

### ISSUE THREAD

**Issue by lolouk44** [google-coral/edgetpu#494]
### Description

Error message when trying to use Coral USB. (works fine when using CPU instead of TPU in config)
Frigate running on docker container.
In case it makes a difference, I have previously tried to run the M.2 Accelerator via a PCIe Adapter but my motherboard is PCIe 2.0, not 3.0. I had installed the relevant drivers as per the [Coral Instructions](https://coral.ai/docs/m2/get-started/#2-install-the-pcie-driver-and-edge-tpu-runtime)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug, Support

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

```shell
[2021-10-19 21:42:33] frigate.app                    INFO    : Starting Frigate (0.9.1-800f33e),
[2021-10-19 21:42:33] frigate.app                    WARNING : Camera back has rtmp enabled, but rtmp is not assigned to an input.,
[2021-10-19 21:42:33] frigate.app                    WARNING : Camera front has rtmp enabled, but rtmp is not assigned to an input.,
[2021-10-19 21:42:33] frigate.app                    WARNING : Camera side has rtmp enabled, but rtmp is not assigned to an input.,
Starting migrations,
[2021-10-19 21:42:33] peewee_migrate                 INFO    : Starting migrations,
There is nothing to migrate,
[2021-10-19 21:42:33] peewee_migrate                 INFO    : There is nothing to migrate,
[2021-10-19 21:42:33] frigate.mqtt                   INFO    : MQTT connected,
[2021-10-19 21:42:33] detector.coral                 INFO    : Starting detection process: 225,
[2021-10-19 21:42:33] frigate.app                    INFO    : Output process started: 227,
[2021-10-19 21:42:33] ws4py                          INFO    : Using epoll,
[2021-10-19 21:42:33] frigate.edgetpu                INFO    : Attempting to load TPU as usb,
[2021-10-19 21:42:33] frigate.app                    INFO    : Camera processor started for back: 232,
[2021-10-19 21:42:36] frigate.edgetpu                INFO    : TPU found,
[2021-10-19 21:42:33] frigate.app                    INFO    : Camera processor started for front: 235,
[2021-10-19 21:42:33] frigate.app                    INFO    : Camera processor started for garage: 237,
[2021-10-19 21:42:33] frigate.app                    INFO    : Camera processor started for side: 238,
[2021-10-19 21:42:33] frigate.app                    INFO    : Capture process started for back: 241,
[2021-10-19 21:42:33] frigate.app                    INFO    : Capture process started for front: 242,
[2021-10-19 21:42:33] frigate.app                    INFO    : Capture process started for garage: 248,
[2021-10-19 21:42:33] frigate.app                    INFO    : Capture process started for side: 252,
[2021-10-19 21:42:33] ws4py                          INFO    : Using epoll,
F driver/usb/usb_driver.cc:802] [0-0] bulk out for header failed. Abort. Unknown: USB transfer error 1 [LibUsbDataOutCallback],
Fatal Python error: Aborted,
,
Thread 0x00007f2afb21b700 (most recent call first):,
  File "/usr/lib/python3.8/threading.py", line 302 in wait,
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 227 in _feed,
  File "/usr/lib/python3.8/threading.py", line 870 in run,
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner,
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap,
,
Thread 0x00007f2b03418740 (most recent call first):,
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 833 in invoke,
  File "/opt/frigate/frigate/edgetpu.py", line 104 in detect_raw,
  File "/opt/frigate/frigate/edgetpu.py", line 180 in run_detector,
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108 in run,
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap,
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch,
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__,
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen,
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen,
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start,
  File "/opt/frigate/frigate/edgetpu.py", line 241 in start_or_restart,
  File "/opt/frigate/frigate/edgetpu.py", line 210 in __init__,
  File "/opt/frigate/frigate/app.py", line 209 in start_detectors,
  File "/opt/frigate/frigate/app.py", line 337 in start,
  File "/opt/frigate/frigate/__main__.py", line 17 in <module>,
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code,
  File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
```
</details>

**Comment by hjonnala** [comment]
Are you able to run it locally without docker container? Can you please share the standalone script to reproduce the issue?

**Comment by lolouk44** [comment]
Thanks. I have not tried running without the container.
I've just checked the doc and Docker is the recommended install method, and there isn't any method listed for manual install so not too sure how to do this.

> Can you please share the standalone script to reproduce the issue?

What do you mean by this? all I do is docker-compose up and the container eventually shuts down, logs provided were from the container.

In case it helps, here is my docker-compose:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yaml:/config/config.yml:ro
      - ./media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "[redacted]"
```

`lsusb` returns this:
```
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 013 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 012 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 011 Device 003: ID 18d1:9302 Google Inc. 
Bus 011 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 010 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 009 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 008 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
So it looks like the accelerator is recognised, however I'm sure if I should see a USB device listed in `/dev/`? I don't have a single device listed under ttyusbxx...

**Comment by hjonnala** [comment]
Thanks for the details. Can you please share the model you are trying to run. or try to run the inference with below script.

```
from tflite_runtime import interpreter as tflite
import numpy as np

model_path = 'model.tflite'

interpreter = tflite.Interpreter(
            model_path=model_path, experimental_delegates=[tflite.load_delegate('libedgetpu.so.1',  {})])
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=input_details[0]['dtype'])
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```

**Comment by lolouk44** [comment]
Thanks. Am I supposed to run this in a specific location?
Should frigate be running?
I've tried to run it from within the docker container and here is what I'm seeing:
```
root@d443798a5955:/media/frigate# python3 test.py 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    interpreter = tflite.Interpreter(
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
ValueError: Could not open 'model.tflite'.
```
The model I'm using is the default provided one, I've not amended anything.
Would a copy of my config help?

**Comment by lolouk44** [comment]
Thought I'd share my config anyway before I head off to bed
```
############################################################################
# MQTT                                                                      #
#############################################################################
mqtt:
  host: 192.168.0.24
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: [redacted]
  password: [redacted]
  stats_interval: 60

#############################################################################
# Cameras                                                                   #
#############################################################################
cameras:

### Back ###
  back:
    ffmpeg:
      inputs:
        - path: rtsp://[redacted]@192.168.9.35/Streaming/Channels/2
          roles:
            - detect
            - record
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
    objects:
      track:
        - person
    zones:
      alert_zone:
        coordinates: 0,720,0,524,245,479,973,492,1083,553,1280,598,1280,720

### Front ###
  front:
    ffmpeg:
      inputs:
        - path: rtsp://[redacted]@192.168.9.31/Streaming/Channels/2
          roles:
            - detect
            - record
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
    objects:
      track:
        - person
        - cat
        - dog
    zones:
      alert_zone:
        coordinates: 697,462,466,418,230,386,0,405,0,592,336,672,767,699,1056,691,1280,640,1280,565,1174,572

### Garage ###
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://[redacted]@192.168.9.30/live.sdp
          roles:
            - detect
            - record
            - rtmp
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: True
    timestamp_style:
      format: "%Y-%m-%d %H:%M:%S"
      thickness: 1
    objects:
      track:
        - person
    zones:
      alert_zone:
        coordinates: 0,117,1280,115,1280,720,0,720

### Side ###
  side:
    ffmpeg:
      inputs:
        - path: rtsp://[redacted]@192.168.9.34/Streaming/Channels/2
          roles:
            - detect
            - record
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
    objects:
      track:
        - person
    zones:
      alert_zone:
        coordinates: 1280,720,1042,324,751,309,661,425,364,720

#############################################################################
# Detectors                                                                 #
#############################################################################
detectors:
  coral:
    type: edgetpu
    device: usb
  # cpu1:
    # type: cpu
  # cpu2:
    # type: cpu
  # cpu3:
    # type: cpu
  # cpu4:
    # type: cpu
  # cpu5:
    # type: cpu
  # cpu6:
    # type: cpu
  # cpu7:
    # type: cpu
  # cpu8:
    # type: cpu
```
I've only just received my accelerator yesterday so for the time being I'm using CPU detectors until I can fix the accelerator issue

**Comment by hjonnala** [comment]
please share your tflite model also.

Thanks

**Comment by lolouk44** [comment]
Where do I find it pls?

**Comment by hjonnala** [comment]
please check in your deployment folder with .tflite extension. Or please zip all the files you have  and share it as attachment.

**Comment by lolouk44** [comment]
Thanks. Like I said this is what come with the container.
[edgetpu_model.zip](https://github.com/google-coral/edgetpu/files/7384077/edgetpu_model.zip)

**Comment by hjonnala** [comment]
The model works fine locally. Can you please provide all the files/python scripts inside docker container?

Thanks

**Comment by lolouk44** [comment]
Apologies I've been away, and also realised that for some reason I thought I was raising an issue on the frigate repo from [blakeblackshear](https://github.com/blakeblackshear/frigate)

Trying to go back to basics / start.
I'm following the [Run a model on the Edge TPU](https://coral.ai/docs/accelerator/get-started/#3-run-a-model-on-the-edge-tpu) instructions
Having downloaded the required data from step 2, I run step 3:
```
python3 examples/classify_image.py \
> --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
> --labels test_data/inat_bird_labels.txt \
> --input test_data/parrot.jpg
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
F driver/usb/usb_driver.cc:802] [0-0] bulk out for header failed. Abort. Unknown: USB transfer error 1 [LibUsbDataOutCallback]
Aborted (core dumped)
```
The Accelerator is connected directly on a USB3 Socket on the motherboard (ASRock Fatal1ty 990FX Professional (AMD 990FX))
This should provide enough power.
How can I confirm the drivers are loaded correctly?
Any idea what else I could try?

**Comment by lolouk44** [comment]
Something interesting: I rebooted my computer and tried to run the above sript. It works for a few times (managed 3):
```
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
17.2ms
4.7ms
4.9ms
4.9ms
4.8ms
```
Before returning the error in the previous post.
Could it be that the drivers get overwritten? Or maybe the script works until some drivers get finally loaded and then it no longer works?

**Comment by lolouk44** [comment]
Something else:
I can run the classify_image.py script about twice before it fails. When it does, the accelerators's white led flashes quickly.
If I unplug the accelerator and plug it back, the LED returns to Solid on and the script will work another couple of times.
Can you confirm what the quick flashing means ? From the doc I can only see `On (Solid)` and `Pulse (Breathe)`

**Comment by hjonnala** [comment]
The below error happens when the USB accelerator can't run the model. Are you trying to run same `mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite` model or a different model. If its a different model can you please share the model.

Also can you try the model with max operating frequency (`sudo apt-get install libedgetpu1-max`).. Thanks!
```
F driver/usb/usb_driver.cc:802] [0-0] bulk out for header failed. Abort. Unknown: USB transfer error 1 [LibUsbDataOutCallback]
Aborted (core dumped)
```

**Comment by lolouk44** [comment]
Thanks for coming back.

> The below error happens when the USB accelerator can't run the model. Are you trying to run same `mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite` model or a different model. If its a different model can you please share the model.

I tried the model that comes with instructions [here](https://coral.ai/docs/accelerator/get-started/#3-run-a-model-on-the-edge-tpu) so the one from your repo: [mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite](https://github.com/google-coral/test_data/blob/104342d2d3480b3e66203073dac24f4e2dbb4c41/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite)


> Also can you try the model with max operating frequency (`sudo apt-get install libedgetpu1-max`)

Thanks I've tried and managed to run the script about 5-6 times before the issue occurred. (error message and white LED flashing rapidly)
This happens only while using a USB3 port. When using a USB2 port, it works.
Do you know what this LED mode means?
I've seen several reports of issues due to an underpower USB socket so I've ordered a powered USB Hub to see if it makes a difference...

**Comment by hjonnala** [comment]
can you try this  
```
USB_ENABLE_BULK_DESCRIPTORS_FROM_DEVICE=1 python3 examples/classify_image.py \
--model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels test_data/inat_bird_labels.txt \
--input test_data/parrot.jpg
```

**Comment by lolouk44** [comment]
> USB_ENABLE_BULK_DESCRIPTORS_FROM_DEVICE=1 python3 examples/classify_image.py \
> --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
> --labels test_data/inat_bird_labels.txt \
> --input test_data/parrot.jpg

Same issue. Works twice then fails.

**Comment by hjonnala** [comment]
can you please try with other machines/laptops if you have them?

**Comment by lolouk44** [comment]
> can you please try with other machines/laptops if you have them?

I'm afraid I don't have a space machine with a USB 3.0 that I can use.
I've also received the power USB Hub and I experience the same issue. It works 2-3 times and then the same errors shows and and the accelerator start flashing like crazy.
Can you please find out what that flashing mode means so we can move forward?

**Comment by hjonnala** [comment]
The crazy flashing mode indicates that there is no chance USB accelerator can make inference further. The more reasonable next step would be resetting the device.

**Comment by lolouk44** [comment]
Thanks. Do you know if this is triggered by software or hardware?
I'm just trying to confirm if the issue is hardware to go claim a replacement before the device is too old.
If it's software it would be great if we could find out what triggers it. I'm more than happy trying to run some debugs with you to that end.
Thanks for your help thus far and have a great weekend

**Comment by hjonnala** [comment]
It is triggered by software. I would suggest to test with another machine to check if there is some issue with USB 3.0 port as it is working fine with USB2.0 port.

**Comment by lolouk44** [comment]
Thanks, Iike I said I don't have another machine available with a USB3 to test. It's working on a USB2.0 port so for now I'm "happy".
If you're able to share any details on what part of the software might trigger this I'll see if I can invetigate further, but for now I'll close this issue.

**Comment by hjonnala** [comment]
Please refer to this script: https://github.com/google-coral/libedgetpu/blob/master/driver/usb/usb_driver.cc#L802

Thanks
```
F driver/usb/usb_driver.cc:802] [0-0] bulk out for header failed. Abort. Unknown: USB transfer error 1 [LibUsbDataOutCallback]
Aborted (core dumped)
```

**Comment by kevin1024** [comment]
This was happening to me, and moving the coral USB device to a powered USB hub seems to have resolved the issue.
