### ISSUE TITLE
running yolov3 on edge TPU 

### ISSUE THREAD

**Issue by anuragkarwa001** [google-coral/edgetpu#496]
### Description

I have tried running yolov3 tiny and its working fine but now I want to test yolov3 on edge TPU can anyone help me regarding that 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Operating System

Ubuntu

### Coral Device

Mini PCIe

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @anuragkarwa001 please convert tflite model to edgetpu model using [this tutorial](https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb).

we don't have example script to run the inference for yolov3 model on edge TPU. But, you can try this [yolov4 model](https://github.com/google-coral/edgetpu/issues/460#issue-987611983) as a reference.

Thanks
