### ISSUE TITLE
Devboard Mini Inference Times

### ISSUE THREAD

**Issue by lachlants** [google-coral/edgetpu#497]
### Description

Hello, 
I'm getting lower than expected performance on the Coral Devboard Mini running the "Getting Started" PyCoral example. e.g. Running the command: `python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg`

With the Mini I get an inference time of ~18.6ms and ~1.5 W  power draw.
With the original devboard (1GB) I get an inference time of ~3.0ms and ~4.8 W power draw. 

Do these devices share the same 4 TOPs edgeTPU? Is there anything else that could be causing this discrepancy? 

Cheers, 
Lachlan

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Programming Language

Python 3.7

### Relevant Log Output

```shell
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
159.9ms
18.6ms
18.6ms
18.6ms
18.5ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.75781
```
</details>

**Comment by hjonnala** [comment]
Hi @lachlants the extra latency is  due to `dev board mini` Uses `USB 2.0 interface` with the MT8167s SoC, whereas `dev board` Uses `PCIe  interface` with the iMX 8M SoC.

**Comment by lachlants** [comment]
Okay, that makes sense... bit of a shame though.  

Is there anyway to hide the increased latency and maintain throughput? e.g. via batching, etc.

**Comment by hjonnala** [comment]
Unfortunately, we haven't explored any such options. Thanks!
