### ISSUE TITLE
Parameters missing in apex_0

### ISSUE THREAD

**Issue by OzSpots-Wireless** [google-coral/edgetpu#498]
### Description

The page https://coral.ai/docs/pcie-parameters/#using-the-parameters-on-linux shows the temp can be read.

Other posts show something like "cat /sys/class/apex/apex_0/temp"

I can't find anything to do with temp anywhere.

This is on Debian 11 using m.2 a+e accelerator in a pcie card:

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Operating System

Linux, Ubuntu

### Coral Device

M.2 Accelerator A+E

### Relevant Log Output

```shell
> root@frigate:/sys# ls /sys/class/apex/apex_0
> 0000:02:00.0
> dev
> device_type
> interrupt_counts
> node_0_page_table_entries
> power
> status
> user_mem_ranges
> bar_offsets
> device
> driver_version
> is_device_owned
> node_0_simple_page_table_entries
> reset_count
> subsystem
> write_open_count
> bar_sizes
> device_owner
> framework_version
> node_0_num_mapped_pages
> pci_address
> revision
> uevent''
```
</details>

**Comment by manoj7410** [comment]
@ozrouter Are you able to run the demos using Coral device ?

**Comment by OzSpots-Wireless** [comment]
hi, it runs fine in the Frigate docker app. The CPU is old with no AVX - don't know how to rebuild the demo's to try.

**Comment by manoj7410** [comment]
@ozrouter Which host OS are you working with ? 
Any detailed steps to reproduce this on another machine ?

**Comment by OzSpots-Wireless** [comment]
Debian 11
brand new install using the a+e instructions - all worked perfectly and the coral works.. 

does the a+e m.2 actually provide a temperature?

```
root@pve:~# modinfo apex
filename:       /lib/modules/5.4.143-1-pve/kernel/drivers/staging/gasket/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.0
description:    Google Apex driver
srcversion:     0FAE5FC08566DD27355C966
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
staging:        Y
retpoline:      Y
intree:         Y
name:           apex
vermagic:       5.4.143-1-pve SMP mod_unload modversions
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
```

**Comment by manoj7410** [comment]
@ozrouter Please share the output of:

- uname -r

Did you blacklist the pre-installed Apex driver ?

**Comment by OzSpots-Wireless** [comment]
uname -r is above.

Yes, I blacklisted the driver. Installed the new one and un blacklisted as per instructions.
On default Debian 11 it looks to be the same driver...

**Comment by OzSpots-Wireless** [comment]
this was caused by using a pcie adaptor (a+e wifi)

even though it worked the parameter's weren't loaded
