### ISSUE TITLE
Exit DFU mode?

### ISSUE THREAD

**Issue by msaeedm** [google-coral/edgetpu#499]
### Description

Hello,

I am using coral usb accelerator on a remote computer that recently had a power outage. When the computer restarted, I noticed the coral usb device is now listed under Windows device manager as "Coral USB accelerator (DFU)". When that happened before I simply removed the coral device and inserted it again and that restored the normal mode. The problem is that the machine is remote and I would like to know if it is possible to remotely do something like removal/reinsertion without me physically doing that? Is there is a command I can run that will exit DFU mode?

Thanks

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Windows 10

### Coral Device

USB Accelerator

### Programming Language

Python 3.7

### Relevant Log Output

```shell
No relevant output
```
</details>

**Comment by hjonnala** [comment]
Hi @msaeedm  I think this is the default state when you plug in USB accelerator.

Can you please check the state after running at least one inference.

libedgetpu checks if USB accelerator is in DFU mode and then uploads the firmware, i.e. switches to normal working mode

**Comment by msaeedm** [comment]
@hjonnala well that worked just like you said. The state changed from DFU to normal working mode.

Thank you

**Comment by rthokala2** [comment]
Hey 

Where could i  find firmware as the downloaded firmware shown to be invalid.
