### ISSUE TITLE
Request for static libedgetpu.a

### ISSUE THREAD

**Issue by powderluv** [google-coral/edgetpu#5]
Would it be possible to remove the explicit dependency on libc++.so.1 and  libc++.so.1 . Those are old libraries from older Debian releases which I think the official build process uses. This prevents us from using libedgetpu.so on newer AARCH64 releases like 64 bit Gentoo on RPi4 (https://github.com/sakaki-/gentoo-on-rpi-64bit) . 

Or alternatively please package the libc++ deps too, or better yet just open source libedgetpu.so :) 

After fighting bazel on ARM64 and cross compiling etc. I have a simple CMake based CPP EdgeTPU example here: https://github.com/powderluv/etdemo

**Comment by dmitriykovalev** [comment]
There is no dependency on these libraries in the latest `libedgetpu.so` in this repo:

```
$ curl -OL https://raw.githubusercontent.com/google-coral/edgetpu/master/libedgetpu/direct/aarch64/libedgetpu.so.1.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  773k  100  773k    0     0  1796k      0 --:--:-- --:--:-- --:--:-- 1795k

$ readelf -d libedgetpu.so.1.0  | grep Shared
 0x0000000000000001 (NEEDED)             Shared library: [libusb-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-aarch64.so.1] 
```

**Comment by powderluv** [comment]
great to know. I had an older version in the system path

powderluv@pi64 ~/github/etdemo/b $ ldd /usr/lib64/libedgetpu.so.1
        linux-vdso.so.1 (0x0000007f9baac000)
        libusb-1.0.so.0 => /lib64/libusb-1.0.so.0 (0x0000007f9b989000)
        libgcc_s.so.1 => /usr/lib/gcc/aarch64-unknown-linux-gnu/9.2.0/libgcc_s.so.1 (0x0000007f9b965000)
        libc++.so.1 => not found
        libc++abi.so.1 => not found
        libm.so.6 => /lib64/libm.so.6 (0x0000007f9b8b6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000007f9b885000)
        libc.so.6 => /lib64/libc.so.6 (0x0000007f9b706000)
        /lib64/ld-linux-aarch64.so.1 (0x0000007f9ba7e000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x0000007f9b6df000)
        libudev.so.1 => /lib64/libudev.so.1 (0x0000007f9b6a8000)

BTW - any chance this lib will be available in source form ? Just makes compilation in newer architectures easy (Gentoo / RISC-v etc)
Thanks

**Comment by powderluv** [comment]
also any chance it could be a static lib.  
EDIT title for static request

**Comment by Namburger** [comment]
@powderluv we have something coming for you soon and you'll enjoy it :)

**Comment by powderluv** [comment]
Can't wait for it 🤪

**Comment by Namburger** [comment]
@powderluv 
FYI :) https://github.com/google-coral/libedgetpu

**Comment by powderluv** [comment]
More teasing :)

Can't wait for the sources. I only see the license and readme.

**Comment by Namburger** [comment]
Done!
