### ISSUE TITLE
about two usb camera in one program

### ISSUE THREAD

**Issue by akioolin** [google-coral/edgetpu#50]
Hi All:

after some try and error, I found using two USB camera by plug into one USB hub, and the USB hub is plugged into edgetpu dev-board's USB type-A connector. the USB hub is 3.1 compliant.  

run the my c++ test program by using opencv will show the following message.
this seems come from kernel / uvc driver's complain.

[ 9079.026742] usb 1-1.1.2: new high-speed USB device number 13 using xhci-hcd
[ 9079.236013] uvcvideo: Found UVC 1.00 device Webcam C170 (046d:082b)
[ 9079.250905] uvcvideo 1-1.1.2:1.0: Entity type for entity Processing 2 was not initialized!
[ 9079.259206] uvcvideo 1-1.1.2:1.0: Entity type for entity Extension 6 was not initialized!
[ 9079.267570] uvcvideo 1-1.1.2:1.0: Entity type for entity Camera 1 was not initialized!
[ 9079.276133] input: Webcam C170: Webcam C170 as /devices/platform/usb@38200000/38200000.dwc3/xhci-hcd.0.auto/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0/input/input12
[ 9079.396470] usbcore: registered new interface driver snd-usb-audio
[ 9085.682685] usb 1-1.1.1: new high-speed USB device number 14 using xhci-hcd
[ 9085.827077] uvcvideo: Found UVC 1.00 device HD USB Camera (05a3:9520)
[ 9085.967116] uvcvideo 1-1.1.1:1.0: Entity type for entity Extension 2 was not initialized!
[ 9085.975423] uvcvideo 1-1.1.1:1.0: Entity type for entity Processing 3 was not initialized!
[ 9085.983912] uvcvideo 1-1.1.1:1.0: Entity type for entity Camera 1 was not initialized!
[ 9085.993012] input: HD USB Camera as /devices/platform/usb@38200000/38200000.dwc3/xhci-hcd.0.auto/usb1/1-1/1-1.1/1-1.1.1/1-1.1.1:1.0/input/input13
[ 9090.402334] usb 1-1.1.2: reset high-speed USB device number 13 using xhci-hcd
[ 9091.861684] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9091.868956] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9091.924090] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9091.930953] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9091.992355] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9091.999306] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.059786] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.066558] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.128033] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.134871] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.193329] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.199936] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.261640] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.268426] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.332729] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.339572] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.396418] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.403007] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.460239] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.466923] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.656892] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.663589] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.679862] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.686257] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.697201] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.704174] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.726696] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.733531] usb 1-1.1.1: Not enough bandwidth for altsetting 1
[ 9092.799419] usb 1-1.1.1: Not enough bandwidth for new device state.
[ 9092.805925] usb 1-1.1.1: Not enough bandwidth for altsetting 1

if using one USB camera, the c++ test program works very well. but not ok in two USB camera case. 

for one camera, the setting of camera  could reach to 1920x1080@15fps. 

for two camera case, both of them are all 640x480@30fps, even downgrade to 320x240@15fps., still show out the above messages.

where is the limitation? the TYPE-A USB port on edgetpu dev-board? the USB hub?

is there any possible way to solve this problem? 

BR, Akio

**Comment by Namburger** [comment]
@akioolin 
Hi, could you check whether if your USB hub supports 3.0? This is most-likely due to USB bandwidth. We haven't tested out using 2 USB cameras, but here are a few concerns:

* Bandwidth issues which you are experiencing, especially while using a single USB port. 
* While inference are sped up by the TPU, image processing is still being done on the CPU. The Arm Cortex-A53 may slow the application down significantly unless you're threading the image processing, but also keep in mind that `invoke()` shouldn't be run in parallel
* Power issue. I suggest that you are using a USB hub that also supplies power to the cameras. 

As for using 2 cameras, I have successfully used 2 cameras, one is our own coral's cameras and a usb [hp camera](https://www.logitech.com/en-us/product/c930e-webcam) but we haven't tried 2 usb cameras yet. I'll get another USB camera tomorrow and test this, I'll keep you updated!

**Comment by akioolin** [comment]
@Namburger  

Thank you very detail suggestion. The usage of edgetpu will be interleaved, which means camera 1's image send into edgetpu, next is camera 2's image into edgetpu, and so on. The image pre-processing will be next major issue for performance optimization. 

As my past experience, using hw image pre-processing unit is the best way. but after check the architecture block of i.MX8M, this AP seems has no hw scaler, color space conversion embedded. 
For what you mention about threading, this will be the optimization phase. BTW, is there any example talking about using GPU for image processing in BSP?

For USB bandwidth, I'll check the usb hub working mode and make sure using a real usb 3.0 hub. 

For power issue, the usb hub is forced to using external power supply.

For uvcvideo kernel module's bandwidth issue, I found some threads talking about it. Please check the below URLs.

https://forum.odroid.com/viewtopic.php?t=33707
https://stackoverflow.com/questions/25619309/how-do-i-enable-the-uvc-quirk-fix-bandwidth-quirk-in-linux-uvc-driver

Could you do me a favor while testing two usb camera with quirks option setting? if the bandwidth problem occurred, try the setting option "quirks". Although, I can get the BSP source code, like imx-uboot, imx-linuxk-kernel, etc. But I don't know how to make my own boot image and flash into dev-board. Is there any documents talking about boot-image customization of dev-board ?

I think, this issue may also be seen on dev-board mini, which using MTK 8167s AP. May be you can use the same test device on dev-board mini to see what happens. 

BR, Akio

**Comment by Namburger** [comment]
Hi @akioolin 
So I just quickly put this script together to reproduce the issue:  https://gist.github.com/Namburger/9a4fb9b7c092541654a38f4dc7de067f

To my surprise, it works without errors. The weird thing is that my USB hub only supports USB 2.0 standard with no power supply so maybe the the cameras I used does uses much power/data transfer? 
Here are the cameras I'm using:
https://www.logitech.com/en-us/product/c930e-webcam
Here is the usb hub I'm using:
https://www.amazon.com/C2G-Cables-27402-4-Port-Inches/dp/B000LWX6U8

I can even use 3 cameras after modifying the script a little bit.

**Comment by Namburger** [comment]
Also, documentation for Mendel OS are here: https://coral.googlesource.com/docs/+/refs/heads/master/ReadMe.md

**Comment by mbrooksx** [comment]
Hi @akioolin 

Here's a minimal gstreamer example: https://gist.github.com/mbrooksx/2bb6dfa1bdc74512688d7ffd588dc832

Note you need to install gstreamer1.0-tools

I have two versions in the script, one that takes raw frames at VGA resolution and one that has higher res which I then decode. I'm not sure how you're receiving frames in your version but I wouldn't expect hires raw frames to work. 

Thanks,
Michael

**Comment by akioolin** [comment]
@Namburger  

Thank you for your detail reply. I got the same result with my tested camera testbed. After using lsusb to exams the capability of used usb camera, I found there are all USB 2.0 device, nnd the usb hub is USB 3.0.  This means I have to check more detail about the camera which issued bandwidth not enough.

If I got any progress, I'll report what I got.

BR, Akio

**Comment by akioolin** [comment]
@mbrooksx  

Thank you. I use my own code to test. which you can found in github.com
https://github.com/akioolin/edgetpu_demo/tree/master/edgetpu_demo

this is one channel version, and I build a two channel version based on this project.

BR, Akio

**Comment by Namburger** [comment]
@mbrooksx @akioolin I believe the problem here maybe cameras dependent. I'm able to also execute the gstreamer script with no issue over my USB2.0 hub. With the higher res there is this warning:
```
There may be a timestamping problem, or this computer is too slow.
```
Other than that, no issues.

**Comment by akioolin** [comment]
@Namburger  @mbrooksx 

I just tested the cameras which have this problem. Using the same test code, the problem is the same. The current solution is using two hub, one is connected to the TYPE-A and the other is connected to OTG. The bandwidth problem is gone. 

AS @Namburger  siad, it is hardware device dependent problem. 

BTW, from SoM pin assignment, the SoM has two usb port. in dev-board, one is type-a, one is otg. is the usb all used?

BR, Akio

**Comment by LINYOUWEI0804** [comment]
Hello, I tried to open 2 usb cameras according to this sample program [https://gist.github.com/Namburger/9a4fb9b7c092541654a38f4dc7de067f] but this error occurs, what is the problem?

error: VIDIOC_QUERYCTRL: No such device

The coral example can be successfully executed 
[https://coral.ai/docs/dev-board/camera/#using-an-hdmi-monitor]
, so I don't think it's a USB camera problem, so I don't think it's a USB camera problem

**Comment by Namburger** [comment]
> error: VIDIOC_QUERYCTRL: No such device

May means that your camera was not detected at index 0 and 1 when initializing it. Can you show the outputs of 
```
ls /dev/video*
```

**Comment by akioolin** [comment]
> Hello, I tried to open 2 usb cameras according to this sample program [https://gist.github.com/Namburger/9a4fb9b7c092541654a38f4dc7de067f] but this error occurs, what is the problem?
> 
> error: VIDIOC_QUERYCTRL: No such device
> 
> The coral example can be successfully executed
> [https://coral.ai/docs/dev-board/camera/#using-an-hdmi-monitor]
> , so I don't think it's a USB camera problem, so I don't think it's a USB camera problem

@LINYOUWEI0804 

Basically, I suggest you do something check about the system configuration, like @Namburger mentioned check. the other is using "v4l2-ctl --list-formats-ext" to check the capability of usb camera which you used.

BR, Akio

**Comment by LINYOUWEI0804** [comment]
Some information,
「ls /dev/video*」  :  
/dev/video0  /dev/video1  /dev/video2

「v4l2-ctl --list-formats-ext」  :  
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

Use the 「v4l2-ctl --list-formats-ext --device /dev/video1」 command to find the camera：
	[1]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 1280x720
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
...............
「v4l2-ctl --list-formats-ext --device /dev/video2」:
[0]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
...........

**Comment by LINYOUWEI0804** [comment]
Solved, thank you. Need to change these 2 parameters： 
 cap = cv2.VideoCapture(0)   ,  cap2 = cv2.VideoCapture(1)
Change to  cap = cv2.VideoCapture(1)   ,  cap2 = cv2.VideoCapture(2 )and it will work successfully
