### ISSUE TITLE
H264 hardware decoding 

### ISSUE THREAD

**Issue by mostafaayesh** [google-coral/edgetpu#500]
### Description

Has anyone been able to decode H264 video using the hardware decoder on the Coral dev mini? I'm trying to decode RTSP streams using the hardware decoder but ffmpeg doesn't seem to work with `h264_v4l2m2m` and produces the following output: 
```
[h264_v4l2m2m @ 0x5591620870] driver 'mtk-mdp' on card '14001000.rdma'
[h264_v4l2m2m @ 0x5591620870] driver 'mtk-vcodec-dec' on card 'platform:mt8167'
[h264_v4l2m2m @ 0x5591620870] Could not find a valid device
[h264_v4l2m2m @ 0x5591620870] can't configure decoder

```
The specsheet mentions the hardware is capable of decoding 1280x720 30 fps H264 video but I can't find a way to utilize it. Any help with this would be appreciated.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Relevant Log Output

_No response_</details>

**Comment by manoj7410** [comment]
@mostafaayesh You can take reference from https://github.com/google-coral/examples-camera/blob/master/gstreamer/gstreamer.py regarding how decodebin is being used.

**Comment by mostafaayesh** [comment]
@manoj7410 Thanks, I'll give that a try. But is it only possible with gstreamer and not ffmpeg?

**Comment by manoj7410** [comment]
@mostafaayesh Gstreamer is what we have tried with. Not really sure how to do this with ffmpeg. But if you get some other way then you can paste that here so that other users may get help from that.

**Comment by mostafaayesh** [comment]
Thank you @manoj7410. I'm thinking about modifying the project to support GStreamer. For ffmpeg, I think it needs low level support for it to work which is more complicated. Feel free to close this issue if there is no one else who has a comment on this.
