### ISSUE TITLE
Input Size and Inference Speed

### ISSUE THREAD

**Issue by Ouwen** [google-coral/edgetpu#502]
### Description

I've been playing with different input size and inference speed for a simple Unet model on the USB accelerator.

For 128x128 input, I get around the benchmarked 3.3ms. However, for shapes like (1152x128) it takes around 250-300ms. It seems like it would be better to chunk the work into 9 (128x128) chunks to get an overall faster runtime. I'm curious what happens under the hood that this is the case.

Is there potentially an issue with busing data, and is there anyway to profile the run on a single edge TPU?

Much appreciated.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance, Support

### Operating System

Mac OS

### Coral Device

USB Accelerator

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, @Ouwen can you please share compiler logs with s flag for 128x128 and 1152x128 inputs. (!edgetpu_compiler -s model.tflite)

**Comment by Ouwen** [comment]
All operations map to edge TPU, let me see if I can upload two as an example

**Comment by Ouwen** [comment]
(larger input 896x208)
https://drive.google.com/file/d/1y8Sm0AlFaj-NXJNbCu4nXpvOuYAfX1PB/view?usp=sharing
250ms inference for a 896x208 image

(smaller input 208x208)
https://drive.google.com/file/d/1LovsCvsFp7M2CV2emvXZ0ET5OHGeZBNa/view?usp=sharing
45ms inference for a 896x208 equivalent image via padded patches

Insight as to why there is such a performance difference would be greatly appreciated. Also would be great to have some profiling tooling to inspect why this behavior exists.

**Comment by hjonnala** [comment]
Hi, Inference time would depends on operations mapped to edgetpu, operation involved and  model size etc.. 

For your model the performance difference is due to total number of compute operations, which increase with increase in model input size. 

Unfortunately, we don't have any profiling tool to check computation time for individual operation. 

Thanks.

**Comment by Ouwen** [comment]
> For your model the performance difference is due to total number of compute operations, which increase with increase in model input size.

I see, so even if it is the same number of tflite operations, just by virtue of increased input size the compiler will use more or less ops under the hood.

In that case, is it a simple matter of trial and error to discover what the most optimal input size will be? Or is there a better way to explore this.

**Comment by hjonnala** [comment]
Optimal model input size would vary from model to model.

Yes, Depending on the inference and accuracy requirements you can experiment with different input sizes.
