### ISSUE TITLE
Coral Dev mini board forcing fastboot mode and reflashing failed

### ISSUE THREAD

**Issue by Hazeline2018** [google-coral/edgetpu#505]
### Description

I have a dev mini board that doesn't work. So I'm trying forcing fastboot and reflashing procedure as instructed. However, I tried using Ubuntu 20.04 installed on Win10, flashing failed. I'm wondering how exactly it should be done and does it only work on true Linux machine? as in the docs, it says the flashing procedure works for Mac and Linux only. Thanks for the help!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Ubuntu

### Coral Device

Dev Board Mini

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, Here are some log details with Linux Machine.

```
bash enable_lk_fastboot.sh
**********************************************************************
Unable to connect to debug board, check connection or manually toggle GPIO.
**********************************************************************
/tmp/tmp.A2frymb1B7 ~/Downloads/excelsior-eagle-20201210233645
INFO: pySerial version: (3.5)
INFO: Use config file: /tmp/tmp.A2frymb1B7/dl_addr.ini
INFO: Waiting to connect platform...
```

- At this point, please use a wire to connect the KPCOL0 test point to ground, as shown in figure 2. Ideally, use a female-to-male jumper wire, with the female end attached to pin 39 on the GPIO header (ground), and then hold the male end firmly on the test point.

-  While maintaining a firm connection with the jumper wire, carefully connect the USB data cable to the board's USB OTG port.

```
INFO: Got /dev/ttyACM0
INFO: Connect brom
INFO: Loading file: lk.bin
INFO: Send lk.bin
INFO: Jump da
~/Downloads/excelsior-eagle-20201210233645
```
If everything goes well, you should be able to see above logs and please follow the rest of the steps as described in the [docs](https://coral.ai/docs/dev-board-mini/reflash/#force-boot-into-fastboot-mode).

**Comment by Hazeline2018** [comment]
Thanks for the prompt reply. I was actually asking if the reflashing process MUST be done on true Linux machine. Anyway, I tried it on a Linux machine, and it worked. So I'm good for now. Please close this thread. Thanks!
