### ISSUE TITLE
SRAM hierarchy description

### ISSUE THREAD

**Issue by flyingdorothia** [google-coral/edgetpu#506]
### Description

Maybe I missed the point of this bug issue thread. But I think this is the only way to get communications with you.
1. I am looking for a detailed description of the memory hierarchy of the edge TPU. Where could I find it?
2. To change the RTL of the TPU, could I use this repository to build my own RTL? 
Thanks

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @lucyfan7266 

> 1. I am looking for a detailed description of the memory hierarchy of the edge TPU. Where could I find it?

Memory management is handled by the runtime/compiler. Please find an overview here: https://coral.ai/docs/edgetpu/compiler/#performance-considerations

> 2. To change the RTL of the TPU, could I use this repository to build my own RTL?

As the TPU is not a FPGA, the RTL can not be programmed/changed.

Thanks.

**Comment by flyingdorothia** [comment]
yes
