### ISSUE TITLE
HIB Error on Coral Dev Board

### ISSUE THREAD

**Issue by RobertChenKFC** [google-coral/edgetpu#507]
### Problem
I was running a TFLite model on the PCIe Edge TPU of the Coral Dev Board, but encountered this error:
```
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000000008, hib_first_error_status = 0000000000000008
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000000008, hib_first_error_status = 0000000000000008
```
I did follow the instructions from [here](https://coral.ai/docs/m2/get-started/#troubleshooting-on-linux) to modify the kernel command line arguments to include `gasket.dma_bit_mask=32`, but it didn't help. Here is the output of `cat /proc/cmdline` after the modification, which, unless I'm mistaken, shows that the kernel command line arguments were successfully modified:
```
console=ttymxc0,115200 console=tty0 earlycon=ec_imx6q,0x30860000,115200 root=PARTUUID=70672ec3-5eee-49ff-b3b1-eb1fbd406bf5 rootfstype=ext4 rw rootwait init=/sbin/init net.ifnames=0 pci=pcie_bus_perf gasket.dma_bit_mask=32
```
The error codes didn't match the ones shown in the instructions, so I'm not entirely sure if that modification helped.

I also looked at other issues mentioning this HIB error, but I didn't really find anything useful.

### Steps to Reproduce
Here are the files required to reproduce this bug:
- [tflite_bench.py](https://drive.google.com/file/d/1AJhnpY375sjYmzNJGqEBPaHwnQIPNfi8/view?usp=sharing )
- [quant_model_edgetpu.tflite](https://drive.google.com/file/d/14-KYG-GyaKhtWHhke4jyIeWDyHr_u9hV/view?usp=sharing)
- [quant_model.tflite](https://drive.google.com/file/d/1UkvNKPY1QDh6x9SzbSTPu2zwsGvMlNzO/view?usp=sharing) (CPU TFLite model for reference)
1. Run the model on the Coral Dev Board's PCIe Edge TPU
```
./tflite_bench.py quant_model_edgetpu.tflite --num 5000
```
2. (Optional) Run the model on a USB Accelerator attached to the Coral Dev Board
```
./tflite_bench.py quant_model_edgetpu.tflite --num 5000 --cpu
```
Running step 1 should result in the HIB error, while running step 2 should be totally fine, and you should see something like this:
```
Total: 5948.823753066052 seconds
Average: 1.1897647506132103 seconds
```
Unfortunately, we have to run inference on the model many times (the commands above performs 5000 inference runs) for the error to (almost) definitely appear, because sometimes the error takes only 1000 or more inferences to appear, but sometimes it takes many more runs.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @RobertChenKFC I am not able to reproduce it on coral dev board. Can you please try with any other coral dev board?

![image](https://user-images.githubusercontent.com/86132058/142672407-fda36aff-fcc4-4788-a543-b5968422a3ce.png)

**Comment by RobertChenKFC** [comment]
@hjonnala Huh, that's weird. I just ran it again on my Coral Dev Board and the HIB error still popped up. Unfortunately, I don't have another Coral Dev Board to test with. I guess I will close the issue and reopen it later when there is a more reliable method to reproduce this error.

**Comment by ArturZurawski** [comment]
For me this error was caused by powerscale governor
