### ISSUE TITLE
Can not successfully compile tflite model for Edge TPU

### ISSUE THREAD

**Issue by Tigran98** [google-coral/edgetpu#508]
### Description

I am trying to compile depth estimation .tflite model for Coral Dev Board. My goal is to map all operations to Edge TPU.
Initially my model contained ELU operations, and those where the only operations that could not be converted after using compilers' -sa flags. I've replaced ELU operations with PReLU to be able to use only Edge TPU.  But now I encounter an error:

**Compilation failed: Compilation failed due to large activation tensors in model.**

After adding -d flag I was able to compile the model, but 3 operations (which are supported on TPU) are still mapped to CPU.

Compiling from ubuntu using version 16.0.384591198.

[prelu_test_640x192.zip](https://github.com/google-coral/edgetpu/files/7582511/prelu_test_640x192.zip)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Windows 10, Ubuntu

### Coral Device

Dev Board

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @Tigran98 if you have multiple TPUs please try to segment the model to fully map to edgetpu and [pipeline](https://coral.ai/docs/edgetpu/pipeline/#run-a-segmented-model-in-a-pipeline) the model with multiple Edge TPUs.

`!edgetpu_compiler -s -n 2 prelu_test_640x192.tflite`

or please try to reduce the model input size and  compile it.

**Comment by Tigran98** [comment]
Hi @hjonnala . Thank you for your answer, I will try to reduce the input size.
BTW is there any method to measure the highest allowed input size or should I find it by experiments?
I want to use the highest values, because reducing much input size may degrade the accuracy.

**Comment by hjonnala** [comment]
Unfortunately, we have to find the highest allowed input size by experiments only as it varies from model to model.

**Comment by hjonnala** [comment]
Feel free to reopen if you have any questions. Thanks!
