### ISSUE TITLE
GPIO pull-up to 3.3V at boot + after halt

### ISSUE THREAD

**Issue by jirkulka** [google-coral/edgetpu#510]
### Description

Hello,

I would like to make following pin go to 3.3V at boot and after linux halt, while controlling it freely through /sys/class/gpio/ in between boot and shutdown - just like RPI3 does it on some pins.

GPIO_P22 | /sys/class/gpio/gpio140 | chip: 4, line: 12

Required behavior: Coral Boot -> PIN HIGH -> app running, toggle PIN OFF -> Shutdown -> PIN HIGHT automatically -> halt -> power off.

from the  docs:
_All I/O pins have a 90k pull-down resistor inside the iMX 8M SoC that is used by default during bootup, except for the I2C pins, which instead have a pull-up to 3.3 V on the SoM. _However, **these can all be changed with a device tree overlay**_ that loads after bootup._

Can you give me a hint on how to create DT overlay file to make that happen, please?

Found usefull comment: https://github.com/google-coral/edgetpu/issues/175#issuecomment-661985170

Thank you for your help,
Jiri

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Other Devices

Raspberry Pi 3

### Programming Language

C++, Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
@jirkulka  are you able to make PIN HIGH during boot (Coral Boot -> PIN HIGH -> app running) with these instructions: https://github.com/google-coral/edgetpu/issues/175#issuecomment-661985170

**Comment by jirkulka** [comment]
@hjonnala the script #175 mentions device tree overlay which was helpful in the end. 

What I did was to add external pull-up resistor of 820 Ohm and add the device tree overlay that modifies the strength of the pin to 40 Ohms, according to "iMX 8M Dual,8M QuadLite,8M Quad Applications Processors Reference Manual", page number 1618.

```
DT Overlay:
	compatible = "fsl,imx8mq-phanbell", "fsl,imx8mq";
	fragment@0 {
		target-path = "/iomuxc@30330000";
		__overlay__ {
			imx8mq-phanbell {
				pinctrl_gpio: gpio_ctrlgrp {
					fsl,pins = < 
						0x40 0x2a8 0x00 0x00 0x00 0x19 /* 0x76  open drain, pull up */
						0x44 0x2ac 0x00 0x00 0x00 0x19 /* 0x76  open drain, pull up */ 
						0x48 0x2b0 0x00 0x00 0x00 0x19 /* 0x76  open drain, pull up */ 
						0x118 0x380 0x00 0x05 0x00 0x19 
						0x128 0x390 0x00 0x05 0x00 0x19 
						0x134 0x39c 0x00 0x05 0x00 0x19 
						0x138 0x3a0 0x00 0x05 0x00 0x19 
						0x204 0x46c 0x00 0x05 0x00 0x19 
						0x20c 0x474 0x00 0x05 0x00 **0x1f** /* MX8MQ_IOMUXC_ECSPI2_MISO_GPIO5_IO12 */ 
						0x210 0x478 0x00 0x05 0x00 0x19 >;
					};
			};
		};
	};
```

My original thought was to disable pull-down resistor, which does not seem to be possible by iMX8.

The problem is resolved. Thank you.
