### ISSUE TITLE
M.2 Google Coral Dual TPU in VirtualBox ?

### ISSUE THREAD

**Issue by jeremypsl** [google-coral/edgetpu#511]
Hello

i am wondering if it is possible to passtrough a M.2 Google Coral Dual TPU in VirtualBox ?

Thanks

**Comment by manoj7410** [comment]
@jeremypsl Few users have successfully accessed Coral devices on Virtual Box but I do not have the exact instructions available to do that. I'll check with the team here and will update this thread if there is a solution available. Meanwhile, let us see if any other Coral user provides a solution here.

**Comment by hjonnala** [comment]
Hi @jeremypsl  I think it is possible to pass through M.2 Google Coral Dual TPU in virtualbox. Please share the details if you are able to do it.  Here are some examples: https://www.reddit.com/r/Proxmox/comments/n34f8q/proxmox_vm_ubuntu_2004_frigate_2x_google_coral_tpu/

Please feel free to reopen if you are getting into any issues while pass through M.2 Dual Edge TPU in Virtual Box.

Good luck!
