### ISSUE TITLE
Yolov5s Edge TPU Compilation - Operation is otherwise supported, but not mapped due to some unspecified limitation

### ISSUE THREAD

**Issue by phodgers** [google-coral/edgetpu#512]
### Description

Hello,

The work at https://github.com/zldrobit/yolov5/tree/tf-edgetpu has progressed and compilation with edge tpu compiler v16 maps nearly all operations onto edge tpu but it reports a couple of operations where 'Operation is otherwise supported, but not mapped due to some unspecified limitation'. Is this a bug/limitation in the compiler? It seems it is very close to being able to compile everything onto edge tpu!

Here is a colab notebook for exporting the yolov5s-int8_edgetpu.tflite model.

```
# Install the Compiler
! curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
! echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
! sudo apt-get update
! sudo apt-get install edgetpu-compiler	

# Install Branch https://github.com/zldrobit/yolov5/tree/tf-edgetpu 
!git clone https://github.com/zldrobit/yolov5.git
%cd yolov5
!git checkout tf-edgetpu
%pip install -qr requirements.txt
from yolov5 import utils
display = utils.notebook_init()  # checks

# Export file Compiled for Coral Edge TPU
%pip install --upgrade flatbuffers==1.12 # downgrade from v2 to v1.12
!python export.py --weights yolov5s.pt --include edgetpu --img 320 --data data/coco128.yaml
```

This results in an export, with below information.

> Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
> Edge TPU Compiler version 16.0.384591198
> Started a compilation timeout timer of 180 seconds.
> 
> Model compiled successfully in 2499 ms.
> 
> Input model: yolov5s-int8.tflite
> Input size: 7.31MiB
> Output model: yolov5s-int8_edgetpu.tflite
> Output size: 7.78MiB
> On-chip memory used for caching model parameters: 7.02MiB
> On-chip memory remaining for caching model parameters: 512.00B
> Off-chip memory used for streaming uncached model parameters: 434.62KiB
> Number of Edge TPU subgraphs: 1
> Total number of operations: 229
> Operation log: yolov5s-int8_edgetpu.log
> 
> Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
> Number of operations that will run on Edge TPU: 225
> Number of operations that will run on CPU: 4
> 
> Operator Count Status
> 
> MAX_POOL_2D 3 Mapped to Edge TPU
> RESHAPE 3 Mapped to Edge TPU
> ADD 7 Mapped to Edge TPU
> LOGISTIC 57 Mapped to Edge TPU
> CONV_2D 60 Mapped to Edge TPU
> QUANTIZE 15 Mapped to Edge TPU
> QUANTIZE 2 Operation is otherwise supported, but not mapped due to some unspecified limitation
> MUL 57 Mapped to Edge TPU
> RESIZE_NEAREST_NEIGHBOR 2 Mapped to Edge TPU
> TRANSPOSE 2 Operation is otherwise supported, but not mapped due to some unspecified limitation
> TRANSPOSE 1 Mapped to Edge TPU
> CONCATENATION 13 Mapped to Edge TPU
> PAD 7 Mapped to Edge TPU
> Compilation child process completed within timeout period.
> Compilation succeeded!
> Edge TPU: export success, saved as yolov5s-int8_edgetpu.tflite (8.2 MB)

There are only 4 operations that will not be loaded on the tpu, even though they would be supported. The model, as rendered via netron.app, shown below.

![image](https://user-images.githubusercontent.com/35833843/143683505-a5fc6c8e-6b70-4f53-86e2-184a46f7a57b.png)

Is this an issue with the complier?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Linux

### Coral Device

USB Accelerator

### Relevant Log Output

_No response_</details>

**Comment by phodgers** [comment]
Here is the exported yolov5s-int8_edgetpu.tflite if that is useful.

[yolov5s-int8_edgetpu.tflite.gz](https://github.com/google-coral/edgetpu/files/7611822/yolov5s-int8_edgetpu.tflite.gz)

**Comment by hjonnala** [comment]
@phodgers It is due to transpose operations size they won't be able to map to edgetpu. Please try with the reduced model input size. Also, please share the uncompiled tflite model. Thanks!

**Comment by phodgers** [comment]
@hjonnala thanks for the reply. The img size is set to 320, so not that large. When I try different img sizes I get different results, sometimes 2 operations not mapped and also the operation differs, it can be transpose, or quantize or reshape. I have also tried the smaller yolov5n (compiles to 2.5 MB, but also the same results in terms of 4 operations not mapped at 320 image size). So it leads me to think there is something else going on with the compiler, it doesn't seem to be a consistent issue. I attach the TFLITE file also generated from a 320 image size. Hopefully it help further.

[yolov5s-int8.tflite.gz](https://github.com/google-coral/edgetpu/files/7619882/yolov5s-int8.tflite.gz)

**Comment by hjonnala** [comment]
Hmm..For yolo5s-int8.tflite transpose operations [(1, 400, 3, 85),(1, 1600, 3, 85)] are too big for edgetpu. I hope reducing the input size would reduce the transpose operations size so that they can be mapped to edge TPU. Can you please share the tflite file, which reshape operation is not mapped. Thanks!

**Comment by phodgers** [comment]
Here are some selected results, I'll post each .tflite and its log output in following posts for reference.
img 224 - **2** operations not mapped due to some unspecified limitation
img 256 - **4** operations not mapped due to some unspecified limitation
img 352 - Compilation **failed**: Compilation failed due to large activation tensors in model.
img 384 - **5** operations (including **RESHAPE**) not mapped due to some unspecified limitation.
img 480 - Compilation **failed**: Compilation failed due to large activation tensors in model.
img 512- **7** operations (including **RESHAPE**) not mapped due to some unspecified limitation.

**Comment by phodgers** [comment]
img 224

[yolov5s-int8.zip](https://github.com/google-coral/edgetpu/files/7625305/yolov5s-int8.zip)

> TensorFlow Lite: export success, saved as yolov5s-int8.tflite (7.7 MB)
> 
> Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
> Edge TPU Compiler version 16.0.384591198
> Started a compilation timeout timer of 180 seconds.
> 
> Model compiled successfully in 2653 ms.
> 
> Input model: yolov5s-int8.tflite
> Input size: 7.31MiB
> Output model: yolov5s-int8_edgetpu.tflite
> Output size: 8.14MiB
> On-chip memory used for caching model parameters: 7.41MiB
> On-chip memory remaining for caching model parameters: 512.00B
> Off-chip memory used for streaming uncached model parameters: 289.12KiB
> Number of Edge TPU subgraphs: 1
> Total number of operations: 230
> Operation log: yolov5s-int8_edgetpu.log
> 
> Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
> Number of operations that will run on Edge TPU: 228
> Number of operations that will run on CPU: 2
> 
> Operator                       Count      Status
> 
> ADD                            7          Mapped to Edge TPU
> MAX_POOL_2D                    3          Mapped to Edge TPU
> PAD                            7          Mapped to Edge TPU
> CONCATENATION                  13         Mapped to Edge TPU
> RESHAPE                        3          Mapped to Edge TPU
> TRANSPOSE                      1          Operation is otherwise supported, but not mapped due to some unspecified limitation
> TRANSPOSE                      2          Mapped to Edge TPU
> LOGISTIC                       57         Mapped to Edge TPU
> RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
> MUL                            57         Mapped to Edge TPU
> QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
> QUANTIZE                       17         Mapped to Edge TPU
> CONV_2D                        60         Mapped to Edge TPU
> Compilation child process completed within timeout period.
> Compilation succeeded! 
> Edge TPU: export success, saved as yolov5s-int8_edgetpu.tflite (8.5 MB)

**Comment by phodgers** [comment]
img 256

[yolov5s-int8.zip](https://github.com/google-coral/edgetpu/files/7625311/yolov5s-int8.zip)

> TensorFlow Lite: export success, saved as yolov5s-int8.tflite (7.7 MB)
> 
> Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
> Edge TPU Compiler version 16.0.384591198
> Started a compilation timeout timer of 180 seconds.
> 
> Model compiled successfully in 2469 ms.
> 
> Input model: yolov5s-int8.tflite
> Input size: 7.31MiB
> Output model: yolov5s-int8_edgetpu.tflite
> Output size: 7.69MiB
> On-chip memory used for caching model parameters: 7.16MiB
> On-chip memory remaining for caching model parameters: 0.00B
> Off-chip memory used for streaming uncached model parameters: 293.12KiB
> Number of Edge TPU subgraphs: 1
> Total number of operations: 229
> Operation log: yolov5s-int8_edgetpu.log
> 
> Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
> Number of operations that will run on Edge TPU: 225
> Number of operations that will run on CPU: 4
> 
> Operator                       Count      Status
> 
> QUANTIZE                       2          Operation is otherwise supported, but not mapped due to some unspecified limitation
> QUANTIZE                       15         Mapped to Edge TPU
> MUL                            57         Mapped to Edge TPU
> CONV_2D                        60         Mapped to Edge TPU
> RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
> RESHAPE                        3          Mapped to Edge TPU
> TRANSPOSE                      1          Mapped to Edge TPU
> TRANSPOSE                      2          Operation is otherwise supported, but not mapped due to some unspecified limitation
> CONCATENATION                  13         Mapped to Edge TPU
> PAD                            7          Mapped to Edge TPU
> LOGISTIC                       57         Mapped to Edge TPU
> ADD                            7          Mapped to Edge TPU
> MAX_POOL_2D                    3          Mapped to Edge TPU
> Compilation child process completed within timeout period.
> Compilation succeeded! 
> Edge TPU: export success, saved as yolov5s-int8_edgetpu.tflite (8.1 MB)

**Comment by phodgers** [comment]
img 352

[yolov5s-int8.zip](https://github.com/google-coral/edgetpu/files/7625320/yolov5s-int8.zip)

> TensorFlow Lite: export success, saved as yolov5s-int8.tflite (7.7 MB)
> 
> Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
> Edge TPU Compiler version 16.0.384591198
> Started a compilation timeout timer of 180 seconds.
> ERROR: Restored original execution plan after delegate application failure.
> Compilation failed: Compilation failed due to large activation tensors in model.
> Compilation child process completed within timeout period.
> Compilation failed! 
> 
> Edge TPU: export failure: Command 'edgetpu_compiler -s -a yolov5s-int8.tflite' returned non-zero exit status 1.

**Comment by phodgers** [comment]
img 384

[yolov5s-int8.zip](https://github.com/google-coral/edgetpu/files/7625328/yolov5s-int8.zip)

> TensorFlow Lite: export success, saved as yolov5s-int8.tflite (7.7 MB)
> 
> Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
> Edge TPU Compiler version 16.0.384591198
> Started a compilation timeout timer of 180 seconds.
> 
> Model compiled successfully in 2876 ms.
> 
> Input model: yolov5s-int8.tflite
> Input size: 7.31MiB
> Output model: yolov5s-int8_edgetpu.tflite
> Output size: 7.75MiB
> On-chip memory used for caching model parameters: 7.11MiB
> On-chip memory remaining for caching model parameters: 256.00B
> Off-chip memory used for streaming uncached model parameters: 342.75KiB
> Number of Edge TPU subgraphs: 1
> Total number of operations: 229
> Operation log: yolov5s-int8_edgetpu.log
> 
> Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
> Number of operations that will run on Edge TPU: 224
> Number of operations that will run on CPU: 5
> 
> Operator                       Count      Status
> 
> TRANSPOSE                      1          Mapped to Edge TPU
> TRANSPOSE                      2          Operation is otherwise supported, but not mapped due to some unspecified limitation
> CONCATENATION                  13         Mapped to Edge TPU
> PAD                            7          Mapped to Edge TPU
> RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
> QUANTIZE                       2          Operation is otherwise supported, but not mapped due to some unspecified limitation
> QUANTIZE                       15         Mapped to Edge TPU
> MUL                            57         Mapped to Edge TPU
> CONV_2D                        60         Mapped to Edge TPU
> LOGISTIC                       57         Mapped to Edge TPU
> ADD                            7          Mapped to Edge TPU
> MAX_POOL_2D                    3          Mapped to Edge TPU
> RESHAPE                        1          Operation is otherwise supported, but not mapped due to some unspecified limitation
> RESHAPE                        2          Mapped to Edge TPU
> Compilation child process completed within timeout period.
> Compilation succeeded! 
> Edge TPU: export success, saved as yolov5s-int8_edgetpu.tflite (8.1 MB)

**Comment by phodgers** [comment]
img 480

[yolov5s-int8.zip](https://github.com/google-coral/edgetpu/files/7625339/yolov5s-int8.zip)

> TensorFlow Lite: export success, saved as yolov5s-int8.tflite (7.7 MB)
> 
> Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
> Edge TPU Compiler version 16.0.384591198
> Started a compilation timeout timer of 180 seconds.
> ERROR: Restored original execution plan after delegate application failure.
> Compilation failed: Compilation failed due to large activation tensors in model.
> Compilation child process completed within timeout period.
> Compilation failed! 
> 
> Edge TPU: export failure: Command 'edgetpu_compiler -s -a yolov5s-int8.tflite' returned non-zero exit status 1.

**Comment by phodgers** [comment]
img 512

[yolov5s-int8.zip](https://github.com/google-coral/edgetpu/files/7625345/yolov5s-int8.zip)

> TensorFlow Lite: export success, saved as yolov5s-int8.tflite (7.7 MB)
> 
> Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
> Edge TPU Compiler version 16.0.384591198
> Started a compilation timeout timer of 180 seconds.
> 
> Model compiled successfully in 3438 ms.
> 
> Input model: yolov5s-int8.tflite
> Input size: 7.31MiB
> Output model: yolov5s-int8_edgetpu.tflite
> Output size: 7.52MiB
> On-chip memory used for caching model parameters: 6.89MiB
> On-chip memory remaining for caching model parameters: 1.00KiB
> Off-chip memory used for streaming uncached model parameters: 175.00KiB
> Number of Edge TPU subgraphs: 1
> Total number of operations: 229
> Operation log: yolov5s-int8_edgetpu.log
> 
> Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
> Number of operations that will run on Edge TPU: 222
> Number of operations that will run on CPU: 7
> 
> Operator                       Count      Status
> 
> CONCATENATION                  13         Mapped to Edge TPU
> PAD                            7          Mapped to Edge TPU
> TRANSPOSE                      3          Operation is otherwise supported, but not mapped due to some unspecified limitation
> ADD                            7          Mapped to Edge TPU
> MAX_POOL_2D                    3          Mapped to Edge TPU
> MUL                            57         Mapped to Edge TPU
> QUANTIZE                       14         Mapped to Edge TPU
> QUANTIZE                       3          Operation is otherwise supported, but not mapped due to some unspecified limitation
> LOGISTIC                       57         Mapped to Edge TPU
> CONV_2D                        60         Mapped to Edge TPU
> RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
> RESHAPE                        2          Mapped to Edge TPU
> RESHAPE                        1          Operation is otherwise supported, but not mapped due to some unspecified limitation
> Compilation child process completed within timeout period.
> Compilation succeeded! 
> Edge TPU: export success, saved as yolov5s-int8_edgetpu.tflite (7.9 MB)

**Comment by hjonnala** [comment]
> img 480
> 
> [yolov5s-int8.zip](https://github.com/google-coral/edgetpu/files/7625339/yolov5s-int8.zip)

please try the command below for this model (image 480):
`!edgetpu_compiler -s  -i "model/tf_detect/Reshape_2/shape_1"  yolov5s-int8_480.tflite `

and for (image 352):
`edgetpu_compiler -s  -i "model/tf_detect/Reshape/shape_1"  yolov5s-int8_352.tflite`

In all  cases operations are not mapped due to edge TPU **compiler limitations** with the operation sizes.. Thanks!

**Comment by phodgers** [comment]
@hjonnala Yes I can see using above options, that the 352 and 420 can now both also compile, with some more unsupported operations.

Do you have a feeling for whether the TPU compiler limitations are something that could be overcome with future release of compiler, or is it an issue that is unlikely to be possible for technical reasons?

Thanks,

**Comment by hjonnala** [comment]
I am not sure, most likely it is not possible map the large size operations especially  transpose and reshape operations.
