### ISSUE TITLE
How to feed image/jpeg format into edgetpuvision demo. 

### ISSUE THREAD

**Issue by cappittall** [google-coral/edgetpu#513]
### Description

Hi, 
First of all thank you for all.
I have maybe very sipmle problem but so far some trial not able to fix the issue. 
with the command of `v4l2-ctl --list-formats-ext --device /dev/video1`
```
	[0]: 'MJPG' (Motion-JPEG, compressed)
		Size: Discrete 1920x1080
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x800
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.050s (20.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 800x600
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.050s (20.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.050s (20.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 320x240
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.050s (20.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
	[1]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 1920x1080
			Interval: Discrete 0.200s (5.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 1280x800
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 800x600
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.050s (20.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 320x240
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.050s (20.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.200s (5.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
```
I am tring to use camera at 30 fps with high resulution. And  YUY2 formats have only low resulutions. 

at the Coral's site mentioned only[ YUY2 format supported.](https://coral.ai/docs/dev-board/camera/#:~:text=Note%3A%20Be%20sure%20that%20your%20list%20includes%20Pixel%20Format%3A%20%27YUYV%27.%20Currently%2C%20YUYV%20is%20the%20only%20format%20supported.%20But%20the%20commands%20below%20refer%20to%20this%20format%20with%20the%20name%20YUY2%2C%20which%20is%20just%20a%20different%20name%20for%20the%20same%20thing.) 

But Even I tried to to feed like --source /dev/video1:MJPEG:1920x1080:30/1 etc. But no luck. 

But at my notbook I can run this format so, feeling should work also at Coral device. When I digg on codes seams pipeline prepared only video/x-row mode [link](https://github.com/cappittall/edgetpuvisionVa/blob/0c7169c9482677a0a70dfe3ead97ab545fd4e0a1/pipelines.py#L23)

I wanted to be sure wheather I can not use this format or I can in Coral's demo `edgetpu_demo --device `? 
if yes, your example will be very much appretiated, thanks in advance.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux, Linux

### Coral Device

Dev Board

### Programming Language

Python 3.7, Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
> But at my notbook I can run this format so, feeling should work also at Coral device. When I digg on codes seams pipeline prepared only video/x-row mode [link](https://github.com/cappittall/edgetpuvisionVa/blob/0c7169c9482677a0a70dfe3ead97ab545fd4e0a1/pipelines.py#L23)
> 
Can you please share the notebook that you are able to run in this format?

> I wanted to be sure wheather I can not use this format or I can in Coral's demo `edgetpu_demo --device `? if yes, your example will be very much appretiated, thanks in advance.

 Yes, you cannot use image/jpeg format in Coral demo` edgetpu_demo --device`.

**Comment by cappittall** [comment]
Thanks @hjonnala,

regarding to this [issue](https://github.com/google-coral/edgetpu/issues/319#:~:text=gst%2Dlaunch%2D1.0%20glvideomixer%20name%3Dm%20background%3Dblack%20sink_0%3A%3Axpos%3D0%20sink_0%3A%3Aypos%3D0%20sink_0%3A%3Azorder%3D1%20!%20glimagesink%20v4l2src%20device%3D/dev/video6%20!%20image/jpeg%2Cframerate%3D60/1%2Cwidth%3D640%2Cheight%3D480%20!%20jpegdec%20!%20glupload%20!%20glcolorconvert%20!%20m.sink_0)  

I meaned that this command in notbook, video streaming very nice: with image/jpeg format. So the same streaming can not send to the device input with proper pipeline? : 

`gst-launch-1.0 glvideomixer name=m background=black sink_0::xpos=0 sink_0::ypos=0 sink_0::zorder=-1 ! glimagesink v4l2src device=/dev/video2 ! image/jpeg,framerate=30/1,width=1920,height=1080 ! jpegdec ! glupload ! glcolorconvert ! m.sink_0
`

Actually my aim is: I have implemented object tracker from edgetpu_demo (edgetpuvision). And object tracker uses Kalman Filter. Due to some searchs, low `fps` not working good at Kalman Filter base tracker. Minimum 30 fps and high resulotion (~ 1080 px) For this purpose I have purchased some cameras :) Becase It's writen on prospect 30 & 60 fps but I find out that this fps are in image/jpeg formats. YUY2 formats always lower fps. Now I am tring to solve this problem.  
Thanks in advance

**Comment by hjonnala** [comment]
@cappittall  we don't have any planned updates to edgetpuvision repo in the near future, please refer to [examples-camera](https://github.com/google-coral/examples-camera/blob/master/gstreamer/gstreamer.py#L214) repo for image/jpeg implemenation. 

![image](https://user-images.githubusercontent.com/86132058/144138009-aff1ef7e-5f6e-47a8-b139-135e0060fb84.png)

**Comment by cappittall** [comment]
Thanks @hjonnala , So, i can use image/jpeg format at coral device in proper pipeline. At your first comment i got wrong you that i can not use this option at device.

**Comment by cappittall** [comment]
Hı @hjonnala, thank you very much ;  i implemented the code as you directed. Works fine but at output (screen) significantly slow.  Have any suggestion?  `gst_base_sink_is_too_late`

EDİT: 
Coral type ('mt8167' **NOT** in coral:)  I added `sync=false` to pipeline, then seams fixed this problem!

**Comment by cappittall** [comment]
Hello @hjonnala , i am very sorry to disturb again:

At the end i executed examples-camera at coral device which is **freescale i.MX8MQ Phanbell** 

But can't be faster than 8 fps. And i need min 30fps for correct tracking. Looking for solutions.

- image/jpeg:1280x720:60:1

- Camera Logitech c922


I retrained my model with efident0 in order to make lighter size.

model link: https://drive.google.com/drive/folders/1mz0X0E5bDsQUY3k-UCjAkI26iGvRE7WP?usp=sharing


![20211203_151437](https://user-images.githubusercontent.com/14778803/144602725-1e119225-2e87-4dde-a3f3-b088f34577fe.jpg)

**Comment by hjonnala** [comment]
@cappittall since all operations are not mapped to edgeTPU the model is taking more time on CPU. Please try with USB accelerator or with some other [object detection](https://coral.ai/models/object-detection/#trained-models) models. 

Dev Board
```
mendel@tuned-rabbit:~$ ./single_model_benchmark -model besas-lite-model-efdet0_edgetpu.tflite 
2021-12-03 15:43:45
Running ./single_model_benchmark
Run on (4 X 1500 MHz CPU s)
Load Average: 0.28, 0.08, 0.02
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_Model          105 ms         88.9 ms            8 besas-lite-model-efdet0_edgetpu.tflite
mendel@tuned-rabbit:~$
```
USB accelerator:
```
hemanth@hemanth-glaptop:~/libcoral/out/k8/benchmarks/coral$ ./single_model_benchmark -model besas-lite-model-efdet0_edgetpu.tflite
2021-12-03 07:41:41
Running ./single_model_benchmark
Run on (4 X 3900 MHz CPU s)
CPU Caches:
  L1 Data 32K (x2)
  L1 Instruction 32K (x2)
  L2 Unified 256K (x2)
  L3 Unified 4096K (x1)
Load Average: 1.47, 1.88, 1.53
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_Model         21.9 ms         11.8 ms           66 besas-lite-model-efdet0_edgetpu.tflite
```

**Comment by cappittall** [comment]
hi @hjonnala , Thank you very much and sorry still keeping you busy . For now usb acceleration not available in the country. Will take time to import, same as I did for coral dev board before. 

However, I have re-build the model at colab file which you provided at your website. [link](https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb)
If you think I can use other object detection models,  you pointed above, is there any tutorial how to use other model as spec like easyly used to loaded EfficientDetLite's specs like : 

```
spec=spec = object_detector.EfficientDetLite0Spec()
spec.config.tflite_max_detections = 50
```
[mycolab](https://colab.research.google.com/drive/1TxG3Na7titjWV0LhSgvdSdYCvT_Zv5KS?usp=sharing)

here the sample what I am trying to do: [counting bread video](https://photos.app.goo.gl/HZircbDwbFXnj3S68)

![image](https://user-images.githubusercontent.com/14778803/144649082-0e7876aa-e545-4c69-8af6-7520cf5af8f0.png)

**Comment by hjonnala** [comment]
we have only tutorials with tf1 to retrain moblenet object detection model but not with tf2: https://github.com/google-coral/tutorials

Please check this comment to try with tf2: https://github.com/google-coral/tutorials/issues/16#issuecomment-916290558

**Comment by cappittall** [comment]
Hello @hjonnala, 

I have tried to create new model since your above recomendation. But unfortunately, I could not able to create faster and at least same accurancy. My question is: USB acceletator is better then coral device? as I need more device to count for this project. (Bread counting) And if yes, this USB accelerator should be used at coral dev board device or any lightweight device like raspberry pi?

**Comment by hjonnala** [comment]
Hello @cappittall I think, you have to use USB accelerator with a machine, which has high CPU. You might get same results if you use the USB accelerator with coral Dev Board or Raspberry Pi because of low CPU power with the existing model.

**Comment by cappittall** [comment]
Thanks @hjonnala for very valuable information. İ just remember to check original model which came with device "mobilenet_ssd_v1_coco_quant_postprocess_edgetpu.tflite" which works quite fast as good as camera frame. (İnf. rate 16ms- 60 fps) Now i need to find the way how this model created. Even mine is just one class (bread)  

So device is ok for now.

**Comment by cappittall** [comment]
![20211224_135214](https://user-images.githubusercontent.com/14778803/147346953-b3229a58-cf5f-45db-98b2-29af5fb0ce15.jpg)
