### ISSUE TITLE
Different Classification results in Python and C++ on EdgeTPU

### ISSUE THREAD

**Issue by ibrahimsoliman97** [google-coral/edgetpu#514]
### Description

By running examples/classify_image.py with parrot.jpg image and mobilenetv2 model, i am getting exact classification restults as reported on the [documentation ](https://coral.ai/docs/m2/get-started/#4-run-a-model-on-the-edge-tpu) 
Ara macao (Scarlet Macaw): 0.75781

But when i use the EdgTPU C++ API with same image and model, i am getting:
Ara macao (Scarlet Macaw): 0.703125
For C++ code, i am using the code in [this file ](https://github.com/google-coral/tflite/blob/master/cpp/examples/classification/classify.cc) with changing loading image from bmp to load by OpenCV:
```
cv::Mat cv_selected_image = cv::imread(image_file, cv::IMREAD_COLOR);
cv::cvtColor(cv_selected_image, cv_selected_image, cv::COLOR_BGR2RGB);
cv::resize(cv_selected_image, cv_selected_image, cv::Size(224, 224));
std::copy(cv_selected_image.data, cv_selected_image.data+cv_selected_image.total()*cv_selected_image.channels(),interpreter->typed_input_tensor<uint8_t>(0));
```

We should expect exact same inference results using Python or C++. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Windows 10

### Coral Device

M.2 Accelerator with dual Edge TPU

### Programming Language

C++, Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @ibrahimsoliman97 EdgTPU C++ API is deprecated. Can you please try with [libcoral](https://github.com/google-coral/libcoral) C++ API.

**Comment by ibrahimsoliman97** [comment]
Hi @hjonnala Actually I am using the API in [this link](https://coral.ai/docs/reference/cpp/edgetpu/) with TensorFlow Lite, I link both of them dynamically to my C++ Application.
For the Python side, i am using the libcoral API.
I just want to confirm with you again that EdgeTPU C++ API is deprecated. 
My issue with using Libcoral C++ API, it is required to compile the library with my project using Bazel. But for my case, i am not using Bazel for my solution, so i would prefer the EdgeTPU with TensorFlow Lite Directly. 
From this [docs](https://coral.ai/docs/edgetpu/tflite-cpp/), i can see that Libcoral is optional. is this info outdated ?

**Comment by ibrahimsoliman97** [comment]
And one last question: what is the TF commit in [this docs](https://coral.ai/docs/edgetpu/tflite-cpp/#build-your-project-with-libedgetpu) for dynamic linking that used to build edgetpu_runtime_20210726.zip, because i cannot see any  TENSORFLOW_COMMIT in this [workspace](https://github.com/google-coral/libcoral/blob/master/WORKSPACE)?

**Comment by manoj7410** [comment]
@ibrahimsoliman97 I believe the TF version is being fetched from https://github.com/google-coral/libedgetpu/blob/master/workspace.bzl#L9. 

libedgetpu_dependencies() is being called at https://github.com/google-coral/libcoral/blob/master/WORKSPACE#L25.

**Comment by ibrahimsoliman97** [comment]
Thanks for your reply @manoj7410 . I have tried TF Lite 2.5.0. and the issue still exist.
I have tried to build libcoral for C++. But i think Build for windows is not supported. am i right? @hjonnala

**Comment by ibrahimsoliman97** [comment]
Ok, I got some updates, the results differences are due to Python using PIL library while in C++ i am using OpenCV.
when I use OpenCV in Python, i am getting exactly same inference output. I believe it is due to the resize implementation on each library.

To summarize my questions in a single comment:
1- Does this method >> [linking libedgetpu.lib and dll with my tflite project](https://coral.ai/docs/edgetpu/tflite-cpp/#build-your-project-with-libedgetpu) << already deprecated?
2- According to the documentation, libcoral is optional, but if method in Q1 is deprecated, How to build libcoral on my Windows application?
3- Does method in Q1 can load single model on multiple TPU device as segments, according to this [documentation](https://coral.ai/docs/edgetpu/pipeline/#run-a-pipeline-with-c), it seems libcoral is required to achieve this.

Thanks.

**Comment by hjonnala** [comment]
> To summarize my questions in a single comment: 1- Does this method >> [linking libedgetpu.lib and dll with my tflite project](https://coral.ai/docs/edgetpu/tflite-cpp/#build-your-project-with-libedgetpu) << already deprecated?

Sorry, I thought you are using [edgetpu repo](https://github.com/google-coral/edgetpu/blob/master/libedgetpu/edgetpu_c.h). Edge TPU Runtime library ([libedgetpu](https://github.com/google-coral/libedgetpu/blob/master/tflite/public/edgetpu.h)) API is not deprecated. You can use libedgetpu repo to build your project.

> 2- According to the documentation, libcoral is optional, but if method in Q1 is deprecated, How to build libcoral on my Windows application? 

Can you try to build libcoral using [build.bat](https://github.com/google-coral/libcoral/blob/master/scripts/windows/build.bat) form libcoral

>3- Does method in Q1 can load single model on multiple TPU device as segments, according to this [documentation](https://coral.ai/docs/edgetpu/pipeline/#run-a-pipeline-with-c), it seems libcoral is required to achieve this.

yes, libcoral api is required to achieve this.

Thanks!

**Comment by ibrahimsoliman97** [comment]
Thanks for you confirmation on Q1. 

When i am trying to build libcoral on windows, I am getting these errors
![image](https://user-images.githubusercontent.com/30038478/144979030-9554551f-ca49-4fee-8277-dbc1acd9d03f.png)

Any reason why libcoral is not built as a shared library?

**Comment by hjonnala** [comment]
> Any reason why libcoral is not built as a shared library?

@ibrahimsoliman97  yes, libcoral is a source-only library, there are many non-trivial issues in distributing and maintaining shared C++ library. It makes more sense for C language, not C++.

**Comment by ibrahimsoliman97** [comment]
I will be closing this issue, because the problem originally is inference differences between Python & C++ API which caused by PIL vs OpenCV Resize method. I will be using the TensorFlow Lite with libedgetpu for now. 
Thanks for your support. However I want to write my feedback/suggestion about Coral Chip, 
"From our testing with single TPU chip, we are impressed by how powerful the TPU is, compared to Intel(VPU) and NVidia(Jetson). But once the model get bigger than 8MB, the TPU is not preforming so well compared to Intel(VPU). The idea of 'segment' looks fine, but we didn't test it and we feel the idea of recompiling the model each time we want to change the number of TPUs, is not a **production friendly**.
To conclude, The TPU **hardware is the most powerful** in the market currently based on our benchmarking, but the **software layer and limited memory** are a real disadvantages compare to [**HDDL Plugin**](https://docs.openvino.ai/latest/openvino_docs_IE_DG_supported_plugins_HDDL.html) and 128MB memory size for Inetl (VPU).
We hope to have a software layer that can synchronize and automate the distributions of models on available TPUs automatically.
