### ISSUE TITLE
Does the TFLite_Detection_PostProcess Op runs on the TPU or the CPU

### ISSUE THREAD

**Issue by gj-raza** [google-coral/edgetpu#515]
### Description

I've been experimenting with ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite model on an edge tpu, and from the edge tpu compiler doc, the compiler wraps all the tpu supported ops in one custom op mapped to tpu  and non supported ops as seperate nodes mapped to cpu, by looking in netron, the post process op  apprears as a seperat node, does that mean it is mapped and runs on the cpu?

![ssd_edgetpu](https://user-images.githubusercontent.com/59055565/145566912-52f3593d-f3ef-4d77-a7d1-d8977b81c6f9.png)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Coral Device

Dev Board

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @gi-raza  yes, the TFLite_Detection_PostProcess Op runs on the CPU.

**Comment by gj-raza** [comment]
> Hi @gi-raza yes, the TFLite_Detection_PostProcess Op runs on the CPU.

Got it. Thanks!
