### ISSUE TITLE
Power usage on Coral Dev board

### ISSUE THREAD

**Issue by Tigran98** [google-coral/edgetpu#516]
### Description

Hi,

How can I measure/monitor the power usage on Coral Dev Board?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Relevant Log Output

_No response_</details>

**Comment by manoj7410** [comment]
@Tigran98 Coral Dev Team hasn't developed any power measuring utility. However, you can try to run general Linux tools on the Mendel and see if that works for you. Few tools are:
- upower
- acpi
- powertop

**Comment by Tigran98** [comment]
Hi @manoj7410 . Could you please help to run powertop on Coral Dev Board?
It gives errors now.
![coral_powertop](https://user-images.githubusercontent.com/47828848/146692621-a62b53e2-b467-4aee-831d-2bdd1adb7492.PNG)

**Comment by manoj7410** [comment]
Here is what I am getting in the output:

![Screenshot from 2021-12-20 09-18-30](https://user-images.githubusercontent.com/2090835/146709146-6c98ef8d-3229-4b43-9f17-809da136187e.png)
![Screenshot from 2021-12-20 09-18-11](https://user-images.githubusercontent.com/2090835/146709164-4994ed42-2da7-4813-ae18-62b5c94c9ebe.png)
![Screenshot from 2021-12-20 09-17-52](https://user-images.githubusercontent.com/2090835/146709181-26f1b4d7-d43f-48a1-8af2-6bf26fe8b839.png)

After quitting from the powertop, I see what you are getting on the terminal.

**Comment by Tigran98** [comment]
@manoj7410, Yes, I am also getting such an output, but there is no information about power consumption. Also, the summary row has no useful information, there are nan values only. Here is the output on ubuntu virtual machine (there is power estimation column). How can I get such an output on Coral?
![ubuntu_powertop](https://user-images.githubusercontent.com/47828848/146722410-dde24e70-044e-44f9-aea1-0751a47d937e.PNG)
?

**Comment by manoj7410** [comment]
Looks like the tool is not working on the Dev Board as expected. Apologies, but these are the only tools that I aware of.

**Comment by hjonnala** [comment]
@Tigran98 here are some resources that might help you:

- https://github.com/mbrooksx/draft-coral-appnotes/blob/main/PowerSavings.pdf
- power consumption section in [SOM datasheet](https://coral.ai/static/files/Coral-SoM-datasheet.pdf) page 11.

Also, please explore usb adapter type hardware tools to connect to the board to monitor the power consumption. Thanks!
