### ISSUE TITLE
Changing the order of co-compiling multiple models behaves differently on single EdgeTPU.

### ISSUE THREAD

**Issue by r06922090** [google-coral/edgetpu#518]
### Description

I tried to co-compile multiple models (a CNN and a RNN) running on an EdgeTPU. The iteration number of  RNN is set to 5. Since the SRAM size of EdgeTPU is only 8MB, some parameters load in off-chip memory.

Here is the co-compiled result of caching the CNN in the SRAM first.
Edge TPU Compiler version 15.0.340273435
Models compiled successfully in 2988 ms.
Input model: cnn.tflite
Input size: 8.00MiB
Output model: cnn_edgetpu.tflite
Output size: 9.30MiB
On-chip memory used for caching model parameters: 7.16MiB
On-chip memory remaining for caching model parameters: 2.25KiB
Off-chip memory used for streaming uncached model parameters: 2.95MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 313
Operation log: cnn_edgetpu.log
See the operation log file for individual operation details.
Input model: rnn.tflite
Input size: 2.97MiB
Output model: rnn_edgetpu.tflite
Output size: 4.74MiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 2.25KiB
Off-chip memory used for streaming uncached model parameters: 4.53MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 78
Operation log: rnn_edgetpu.log
See the operation log file for individual operation details.
The total size of parameters in off-chip memory is 7.48MB.

Then, here is the co-compiled result of caching the RNN in the SRAM first.
Edge TPU Compiler version 15.0.340273435
Models compiled successfully in 2937 ms.
Input model: tail5.tflite
Input size: 2.97MiB
Output model: tail5_edgetpu.tflite
Output size: 4.75MiB
On-chip memory used for caching model parameters: 5.54MiB
On-chip memory remaining for caching model parameters: 1.62MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 78
Operation log: tail5_edgetpu.log
See the operation log file for individual operation details.
Input model: densenet_edge.tflite
Input size: 8.00MiB
Output model: densenet_edge_edgetpu.tflite
Output size: 9.32MiB
On-chip memory used for caching model parameters: 1.61MiB
On-chip memory remaining for caching model parameters: 3.75KiB
Off-chip memory used for streaming uncached model parameters: 7.11MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 313
Operation log: densenet_edge_edgetpu.log
See the operation log file for individual operation details.
The total size of parameters in off-chip memory is 7.11MB.

The difference of off-chip memory usage between caching the CNN in the SRAM first (7.48MB)  and caching the RNN in the SRAM first (7.11MB) is less than 0.5MB. The table below shows the execution time of multiple models with two co-compiled methods.
|                      | CNN | RNN |
| ------------- | ------------- | ------------- |
| CNN first fit| 10.466ms  | 21.119ms  |
| RNN first fit| 19.219ms  | 1.148ms  |

We observe that the total execution time of caching the CNN in the SRAM first (31.585ms) is 1.55 times longer than caching the RNN in the SRAM first (20.367ms). Even the  RNN execution time of caching the CNN in the SRAM first (21.119ms) is 18.3 times longer than caching the RNN in the SRAM first (1.148ms). 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Linux

### Coral Device

Dev Board

### Programming Language

Python 3.6

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @r06922090 It looks like you are using old compiler version.  Can you please share the results with new `Edge TPU Compiler version 16.0.384591198`. Also please compare the combined execution time when the models co compiled and when the models compiled individually.

**Comment by r06922090** [comment]
I tried to co-compile multiple models running with new Edge TPU Compiler version.
Here is the co-compiled result of caching the CNN in the SRAM first.
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
Models compiled successfully in 3498 ms.
Input model: cnn_first_edge.tflite
Input size: 8.00MiB
Output model: cnn_first_edgetpu.tflite
Output size: 9.31MiB
On-chip memory used for caching model parameters: 1.75MiB
On-chip memory remaining for caching model parameters: 3.75KiB
Off-chip memory used for streaming uncached model parameters: 6.97MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 313
Operation log: cnn_first_edgetpu.log
See the operation log file for individual operation details.
Input model: rnn_second.tflite
Input size: 2.97MiB
Output model: rnn_second_edgetpu.tflite
Output size: 4.79MiB
On-chip memory used for caching model parameters: 5.29MiB
On-chip memory remaining for caching model parameters: 3.75KiB
Off-chip memory used for streaming uncached model parameters: 158.06KiB
Number of Edge TPU subgraphs: 1
Total number of operations: 78
Operation log: rnn_second_edgetpu.log
See the operation log file for individual operation details.
Compilation child process completed within timeout period.

Then, here is the co-compiled result of caching the RNN in the SRAM first.
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
Models compiled successfully in 3316 ms.
Input model: rnn_first.tflite
Input size: 2.97MiB
Output model: rnn_first_edgetpu.tflite
Output size: 4.79MiB
On-chip memory used for caching model parameters: 5.29MiB
On-chip memory remaining for caching model parameters: 3.75KiB
Off-chip memory used for streaming uncached model parameters: 158.06KiB
Number of Edge TPU subgraphs: 1
Total number of operations: 78
Operation log: rnn_first_edgetpu.log
See the operation log file for individual operation details.
Input model: cnn_second.tflite
Input size: 8.00MiB
Output model: cnn_second_edgetpu.tflite
Output size: 9.31MiB
On-chip memory used for caching model parameters: 1.75MiB
On-chip memory remaining for caching model parameters: 3.75KiB
Off-chip memory used for streaming uncached model parameters: 6.97MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 313
Operation log: cnn_second_edgetpu.log
See the operation log file for individual operation details.
Compilation child process completed within timeout period.

The table below shows the execution time of multiple models with two co-compiled methods and the models compiled individually.
 |                      | CNN | RNN |
| ------------- | ------------- | ------------- |
| w/o co-compiled| 23.584ms  | 11.754ms  |
| CNN first fit| 18.971ms  | 1.441ms  |
| RNN first fit| 19.02ms  | 1.283ms  |

**Comment by hjonnala** [comment]
@r06922090 Thanks for sharing the details. Please let us know if you have any questions now. Thanks!

**Comment by r06922090** [comment]
Now I  try to co-compile multiple models running with Edge TPU Compiler version 15.0.340273435. At this time, the iteration number of RNN is set to 1.

Here is the co-compiled result of caching the CNN in the SRAM first.
Edge TPU Compiler version 15.0.340273435
Models compiled successfully in 2704 ms.
Input model: cnn_first.tflite
Input size: 8.00MiB
Output model: cnn_first_edgetpu.tflite
Output size: 9.30MiB
On-chip memory used for caching model parameters: 7.16MiB
On-chip memory remaining for caching model parameters: 2.25KiB
Off-chip memory used for streaming uncached model parameters: 2.95MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 313
Operation log: cnn_first_edgetpu.log
See the operation log file for individual operation details.
Input model: rnn_second.tflite
Input size: 2.71MiB
Output model: rnn_second.tflite
Output size: 3.09MiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 2.25KiB
Off-chip memory used for streaming uncached model parameters: 2.99MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 17
Operation log: rnn_second.log
See the operation log file for individual operation details.
The total size of parameters in off-chip memory is 5.94MB.

Then, here is the co-compiled result of caching the RNN in the SRAM first.
Edge TPU Compiler version 15.0.340273435
Models compiled successfully in 2774 ms.
Input model: rnn_first.tflite
Input size: 2.71MiB
Output model: rnn_first.tflite
Output size: 3.11MiB
On-chip memory used for caching model parameters: 3.82MiB
On-chip memory remaining for caching model parameters: 3.34MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 17
Operation log: rnn_first.log
See the operation log file for individual operation details.
Input model: cnn_second.tflite
Input size: 8.00MiB
Output model: cnn_second_edgetpu.tflite
Output size: 9.31MiB
On-chip memory used for caching model parameters: 3.34MiB
On-chip memory remaining for caching model parameters: 2.25KiB
Off-chip memory used for streaming uncached model parameters: 5.38MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 313
Operation log: cnn_second_edgetpu.log
See the operation log file for individual operation details.
The total size of parameters in off-chip memory is 5.38MB.

The off-chip memory usage of both co-compiled methods becomes smaller by reducing the number of iterations. The table below shows the execution time of multiple models with two co-compiled methods.
|                      | CNN | RNN |
| ------------- | ------------- | ------------- |
| CNN first fit| 10.439ms  | 7.64ms  |
| RNN first fit| 15.406ms  | 0.741ms  |

In the results of caching the RNN in the SRAM first, we observe that the execution time of RNN with one iteration (0.741ms) is less than the RNN with five iterations (1.148ms) since the RNN with five iterations must run additional RNN execution. Compared to the results of caching the CNN in the SRAM first, we observe that the execution time of RNN with one iteration (7.64ms) is significant shorter than the RNN with five iterations (21.119ms). Is the reason that the RNN needs to load its parameters from off-chip memory to SRAM repeatedly?

**Comment by hjonnala** [comment]
> Compared to the results of caching the CNN in the SRAM first, we observe that the execution time of RNN with one iteration (7.64ms) is significant shorter than the RNN with five iterations (21.119ms). Is the reason that the RNN needs to load its parameters from off-chip memory to SRAM repeatedly?

I think execution time significantly  shorter for RNN model with one iteration due  to small output size(3.11MiB vs 4.79MiB) and reduction in number of operations(17 vs 78) to be performed.

**Comment by r06922090** [comment]
> > Compared to the results of caching the CNN in the SRAM first, we observe that the execution time of RNN with one iteration (7.64ms) is significant shorter than the RNN with five iterations (21.119ms). Is the reason that the RNN needs to load its parameters from off-chip memory to SRAM repeatedly?
> 
> I think execution time significantly shorter for RNN model with one iteration due to small output size(3.11MiB vs 4.79MiB) and reduction in number of operations(17 vs 78) to be performed.

The RNNs of caching the CNN in the SRAM first and caching the RNN in the SRAM first have the same output size and operations. The execution of caching the CNN in the SRAM first must load the RNN parameters in SRAM, but caching the RNN in the SRAM first does not need to load any RNN parameter from off-chip memory. For caching the RNN in the SRAM first, the difference of RNN's execution time  between five iterations (1.148ms) and one iteration (0.764ms) is less than 0.5ms.

**Comment by r06922090** [comment]
> > Compared to the results of caching the CNN in the SRAM first, we observe that the execution time of RNN with one iteration (7.64ms) is significant shorter than the RNN with five iterations (21.119ms). Is the reason that the RNN needs to load its parameters from off-chip memory to SRAM repeatedly?
> 
> I think execution time significantly shorter for RNN model with one iteration due to small output size(3.11MiB vs 4.79MiB) and reduction in number of operations(17 vs 78) to be performed.

The total parameters of RNN is the same for different number of iterations. Does the increasing operations require more executable space that makes the file size become larger?

**Comment by hjonnala** [comment]
@r06922090 Feel free to reopen if you have any questions. Thanks!
