### ISSUE TITLE
OPs of the Edge TPU model

### ISSUE THREAD

**Issue by Tigran98** [google-coral/edgetpu#519]
### Description

Hi,

How can I measure the number of OPs of a .tflite model compiled with Edge TPU Compiler?
By OPs I mean the number of operations, similar to FLOPs of floating point models.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Relevant Log Output

_No response_</details>

**Comment by Tigran98** [comment]
Is there any profiler for Edge TPU models?

**Comment by hjonnala** [comment]
> Is there any profiler for Edge TPU models?

Individual operation level profiling is not available for Edge TPU models.

Please refer to this link to compile the models based on profiling: https://coral.ai/docs/edgetpu/compiler/#profiling-partitioner
