### ISSUE TITLE
AttributeError: 'glVertexAttribPointer' object has no attribute 'baseFunction' when running edgetpu_demo --stream

### ISSUE THREAD

**Issue by ronnnald** [google-coral/edgetpu#52]
After flashing the image on Coral dev board, when trying to run edgetpu_demo --stream and using my browser to see the demo, following error throws out:
------
Traceback (most recent call last):
  File "/usr/lib/aarch64-linux-gnu/gstreamer-1.0/python/glbox.py", line 203, in do_gl_start
    glVertexAttribPointer.baseFunction(a_position, 2, GL_FLOAT, GL_FALSE, 0, None)
AttributeError: 'glVertexAttribPointer' object has no attribute 'baseFunction'
Error: gst-library-error-quark: Subclass failed to initialize. (3): gstglbasefilter.c(402): gst_gl_base_filter_decide_allocation (): /GstPipeline:pipeline0/GstGLFilterBin:glfilterbin0/glbox+GlBox:filter
-------

Have tried installing gstreamer again on the board but still the same error throws out, any thoughts?

**Comment by Namburger** [comment]
@ronnnald 
Could you share output of:
* $ uname -a
* $ cat /etc/os-release

**Comment by ronnnald** [comment]
Here you go:

$ uname -a
Linux silly-wasp 4.14.98-imx #1 SMP PREEMPT Fri Nov 8 23:28:21 UTC 2019 aarch64 GNU/Linux

$ cat /etc/os-release
PRETTY_NAME="Mendel GNU/Linux 4 (Day)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.withgoogle.com/"
SUPPORT_URL="https://coral.withgoogle.com/"
BUG_REPORT_URL="https://coral.withgoogle.com/"
VERSION_CODENAME="day"

**Comment by Namburger** [comment]
@ronnnald Humnn, very weird as I've never run into this issue. `glVertexAttribPointer` is a OpenGL class so I'm not sure how this all happened. Can you try reflashing your board?
https://coral.ai/docs/dev-board/reflash/#flash-a-new-system-image

**Comment by ronnnald** [comment]
I have reflashed the board and the same result replicated.

I noticed that in Chef release glbox.py is not used at all, it doesn’t look
like a necessary feature to run inference, is there a way to get rid of the
OpenGL class in Day?

**Comment by Namburger** [comment]
OpenGL is needed for streaming the video. 
Did you also do a full apt update and apt upgrade after reflashing the board?

**Comment by ronnnald** [comment]
Hi Nam,

apt *update* was done after the reflash.

However after removing OpenGL and using apt *upgrade*, now the streaming is
working for for both edgetpu_demo and other models although the error
("INFO:OpenGL.acceleratesupport:No
OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'")
still persists.

**Comment by Namburger** [comment]
@ronnnald I'm sorry, very confused by this. Looks like a OpenGL module plugin for accelerated support is missing, but you have flashed the same exact image as us.

**Comment by ronnnald** [comment]
Yes, exactly, OpenGL is missing after reflashing and a subsequent apt-get
update. And after a subsequent manual install of OpenGL triggered the error
mentioned in this issue.

**Comment by DimaK-tracxpoint** [comment]
Confirming the above.
1. Streaming works after [re]flashing - but ("INFO:OpenGL.acceleratesupport:No
OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'") warning is displayed
2. Installation of PyOpenGL-accelerate causes black screen + the error
