### ISSUE TITLE
Problems running demo example in documentation

### ISSUE THREAD

**Issue by alexisc67** [google-coral/edgetpu#521]
Hi,

I am working with the development board and are trying to run some examples.

I am following the instructions here
https://coral.ai/docs/dev-board/get-started/#update-mendel
and all seems to be well. 

However:

On step 7. 
Running 
edgetpu_demo --stream

Gives the error:
-bash: /usr/bin/edgetpu_demo: No such file or directory

On Step 8. After following the instructions to download and install the example.

The following command:
python3 examples/classify_image.py \
--model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels test_data/inat_bird_labels.txt \
--input test_data/parrot.jpg

Produces this:
mendel@wishful-xylophone:~/coral/pycoral$ python3 examples/classify_image.py \
> --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
> --labels test_data/inat_bird_labels.txt \
> --input test_data/parrot.jpg
Traceback (most recent call last):
  File "examples/classify_image.py", line 37, in <module>
    from pycoral.adapters import classify
ModuleNotFoundError: No module named 'pycoral'

My setup is:
Mac OS
Coral Dev Board
Connected via wi-fi

**Comment by hjonnala** [comment]
Hi @alexisc67 can you please share the output of `nmcli connection show`

If the device is connected to the internet please try to run the below commands on dev board:

```
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list

echo "deb https://packages.cloud.google.com/apt coral-cloud-stable main" | sudo tee /etc/apt/sources.list.d/coral-cloud.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

sudo apt-get update 

sudo apt-get dist-upgrade

sudo reboot now
```

If there is any issue with  pycoral examples please install python3-pycoral:
`sudo apt-get install python3-pycoral`

**Comment by alexisc67** [comment]
Hi,

This the output for `nmcli connection show`

```
NAME                 UUID                                  TYPE      DEVICE 
gadget0              53f2438a-886f-434c-b889-816ed8885943  ethernet  usb0   
gadget1              7028f8c9-0404-4e79-b294-6dc8bfff523c  ethernet  usb1   
NETGEAR13            263cf35f-101d-45fb-b243-d9fd2322328a  wifi      wlan0  
sjc303-2             218711f2-7bf8-420b-8292-d3f2d7ec9822  wifi      --     
Telenor0638bil-5GHz  a71733ec-f4c1-44a2-979e-0de4d6347390  wifi      --     
Wired connection 1   6d09a29a-8d9f-30b5-bbf8-126625570e35  ethernet  --     
```

I will try your instructions now.

Alexis

**Comment by alexisc67** [comment]
Hi,

I followed the instructions. 

For the first example.
The command `edgetpu_demo --stream` still gives the same error.
`-bash: edgetpu_demo: command not found`

For the second example. Installing `python3-pycoral` fixed. I just had to remove an old version of tflite-runtime and install with apt as explained here.
https://www.tensorflow.org/lite/guide/python

Thanks,
Alexis

**Comment by hjonnala** [comment]
Okay, can you please share the output of following command:
```
mendel@orange-horse:~$ cat /etc/mendel_version
5.3
mendel@orange-horse:~$ uname -r
4.14.98-imx
mendel@orange-horse:~$ ls /usr/bin/edge*
/usr/bin/edgetpu_classify  /usr/bin/edgetpu_classify_server  /usr/bin/edgetpu_demo  /usr/bin/edgetpu_detect  /usr/bin/edgetpu_detect_server

```

**Comment by alexisc67** [comment]
Hi,

Here it is:

```
mendel@wishful-xylophone:~/demo_files$ cat /etc/mendel_version
5.3
mendel@wishful-xylophone:~/demo_files$ uname -r
4.14.98-imx
mendel@wishful-xylophone:~/demo_files$ ls /usr/bin/edge*
ls: cannot access '/usr/bin/edge*': No such file or directory
mendel@wishful-xylophone:~/demo_files$ 
```

**Comment by hjonnala** [comment]
Hi, Thanks for the info. Have you flash the board using sd card before. Can you please try to [reflash the board](https://coral.ai/docs/dev-board/get-started/#flash-the-board) using the sd card most probably that would fix the issue. Thanks!

**Comment by alexisc67** [comment]
Hi,

Ok, I will. I don't have a sd card now. 

Alexis

**Comment by hjonnala** [comment]
Meanwhile feel free to try the gstreamer camera examples: https://github.com/google-coral/examples-camera/tree/master/gstreamer

**Comment by alexisc67** [comment]
Hi,

The demo example works now after a new flash. 

I will try other examples now.

Thanks for your help.

Alexis
