### ISSUE TITLE
Coral TPU Accelerator Module for ARMv7 32-bit A83T

### ISSUE THREAD

**Issue by ghost** [google-coral/edgetpu#524]
### Description

I was looking into the Coral TPU Accelerator Datasheet, and I realized that the module only supports ARMv8 64bit. But I am only planning on using the USB2.0 drivers for the module. Is it possible to write drivers for the Allwinner A83T? I know there was a very similar post on this but they was planning on using the PCIe. I will not be using a usual linux operating system but a bare bones Linux kernel, with my own program.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

Accelerator Module

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
I think, Coral TPU accelerator works with armv7a 64 bit architecture also. As we have [projects](https://github.com/google-coral/project-posenet/tree/master/posenet_lib) that work on armv7 architecture. Thanks!
