### ISSUE TITLE
QAT with Concatenate Layers

### ISSUE THREAD

**Issue by cdrose** [google-coral/edgetpu#525]
### Description

I am trying to do QAT on a model with Concatenate layers and get the following error:

`RuntimeError: Layer concatenate:<class 'keras.layers.merge.Concatenate'> is not supported. You can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.`

Plenty of the precompiled models for the Edge TPU use Concatenate layers and it is listed as supported but I cant find an example of how to use the quantize_annotate_layer to achieve this. Any hints?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Windows 10

### Coral Device

M.2 Accelerator with dual Edge TPU

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @cdrose  please check the model in this [comment](https://github.com/google-coral/edgetpu/issues/420#issuecomment-887706210) and let us know if it helps fix the issue. Thanks!

**Comment by cdrose** [comment]
@hjonnala Thanks, you got me on the right track. Heres my solution:

```python
class NoOpQuantizeConfig(tfmot.quantization.keras.QuantizeConfig):
    def get_weights_and_quantizers(self, layer):
        return []
    def get_activations_and_quantizers(self, layer):
        return []
    def set_quantize_weights(self, layer, quantize_weights):
        pass
    def set_quantize_activations(self, layer, quantize_activations):
        pass
    def get_output_quantizers(self, layer):
        return []
    def get_config(self):
        return {}

no_op_config = NoOpQuantizeConfig()

def apply_quantization(layer):
  if isinstance(layer, tf.keras.layers.Concatenate):
    return tfmot.quantization.keras.quantize_annotate_layer(layer, no_op_config)
  else:
    return tfmot.quantization.keras.quantize_annotate_layer(layer)

with tfmot.quantization.keras.quantize_scope():
    model_annot = keras.models.clone_model(model, clone_function=apply_quantization)
    model_quant = tfmot.quantization.keras.quantize_apply(model_annot)
```

**Comment by cdrose** [comment]
I have now tested this and the code above does work and does allow QAT and compilation to tflite. The compiled model will run fully on edge TPU and works as expected. Closing =)
