### ISSUE TITLE
Coral multicamera compatibility

### ISSUE THREAD

**Issue by Victor-Martinez-Pozos** [google-coral/edgetpu#526]
Is it posible to use an arducam adapter/hat to conect multiple cameras to a dev mini board mipi-csi connector?

**Comment by hjonnala** [comment]
We haven't tested this. It may not work, as per the [product description](https://www.arducam.com/product/multi-camera-v2-1-adapter-raspberry-pi/) it works only with below products:

- 5MP OV5647 (V1.3) for Raspberry Pi
- 8MP IMX219 (V2.1)  for Raspberry Pi
- 12MP IMX477 (HQ) for Raspberry Pi

Whereas [coral camera](https://coral.ai/static/files/Coral-Camera-datasheet.pdf) uses OV5645 camera connector.

**Comment by Victor-Martinez-Pozos** [comment]
I have been searching for an alternative to connect multiple cameras, I thought that the easiest way of doing this is by using usb cameras and an adapter 
but I found here https://github.com/google-coral/edgetpu/issues/319 that it is not possible due to usb 2 limitations, I also search between the multi cam adapter but I couldn't find any of them suitable for the coral, finally I found this alternative trying to build by their own adapter for the raspberry/jetson connector but without any success nether updates https://github.com/google-coral/edgetpu/issues/535.

So, is there any plan to provide at some point some coral mipi multi cam adapter?

**Comment by charbull** [comment]
Hi @Victor-Martinez-Pozos,

I bumped into your post here, was curious if you managed to connect any raspberry pi camera?

It seems that the Coral Camera for the Coral Dev Board is out of stock: https://coral.ai/products/camera/
Was curious if someone plugged a raspberry pi camera instead on a coral dev board?

Cheers
Charbull

**Comment by Ryan-py** [comment]
Hi @charbull  any progress with this I am also facing the same problem.

**Comment by charbull** [comment]
Hi Ryan
I didn't try connecting another camera

Cheers

**Comment by nassimus26** [comment]
The coral camera is super expensive right now, is there any alternative to test the AI vision of the board ?

**Comment by Ryan-py** [comment]
@nassimus26  I would recommend the groove vision AI V2 by seeed studio. It's quite affordable [check it out](https://www.seeedstudio.com/Grove-Vision-AI-V2-Kit-p-5852.html?srsltid=AfmBOoodRFLChW_JB5MaB-DjDuqmlqx-SzzW7aZkYt-J4hkf35vm04dN)

**Comment by nassimus26** [comment]
Thank you Ryan, but it seems they don't sell the camera alone, and are you sure it's compatible with Coral dev board ? is there other alternatives ?

**Comment by nassimus26** [comment]
Is it enough to search for the reference **OV5645** like this one below 
[cheap OV5645 camera]( https://fr.aliexpress.com/item/1005003709936187.html?spm=a2g0o.productlist.main.1.68d64d2dwZaJqs&algo_pvid=e7a07a9b-14b7-4cb7-9fad-172ff0bbd0f7&algo_exp_id=e7a07a9b-14b7-4cb7-9fad-172ff0bbd0f7-0&pdp_npi=4%40dis%21EUR%2115.59%2115.59%21%21%2116.57%2116.57%21%402103956b17304469690914773e03e0%2112000026890491879%21sea%21FR%212673832176%21X&curPageLogUid=HVSMnIwwnmSD&utparam-url=scene%3Asearch%7Cquery_from%3A)

**Comment by nassimus26** [comment]
Hi, doses someone already tried to connect the OV5647 Caméra like this ones :

[OV5647 Caméra](https://fr.aliexpress.com/item/1005004549580517.html?src=google&pdp_npi=4%40dis%21EUR%214.64%214.09%21%21%21%21%21%40%2112000040694359625%21ppc%21%21%21&src=google&albch=shopping&acnt=248-630-5778&isdl=y&slnk=&plac=&mtctp=&albbt=Google_7_shopping&aff_platform=google&aff_short_key=UneMJZVf&gclsrc=aw.ds&&albagn=888888&&ds_e_adid=&ds_e_matchtype=&ds_e_device=c&ds_e_network=x&ds_e_product_group_id=&ds_e_product_id=fr1005004549580517&ds_e_product_merchant_id=551749738&ds_e_product_country=FR&ds_e_product_language=fr&ds_e_product_channel=online&ds_e_product_store_id=&ds_url_v=2&albcp=20180143335&albag=&isSmbAutoCall=false&needSmbHouyi=false&gad_source=1&gclid=Cj0KCQiAi_G5BhDXARIsAN5SX7od2HZ7q1a1q9N8ax9nOUIusIXR9ivs16J7nZCIW7JYDrJ7YMjHx5MaApDyEALw_wcB)
