### ISSUE TITLE
Unplug power cable while device is running - coral dev mini

### ISSUE THREAD

**Issue by oriyaish** [google-coral/edgetpu#527]
### Description

Hello,
When I'm using excelsior-eagle-20201210233645 image(mendel version: 5.0) , I have no problem to unplug the board while it is running.

**but** when I build mendel for the coral dev board mini by this tutorial:
https://coral.googlesource.com/docs/+/refs/heads/master/GettingStarted.md
(mendel version : 5.3)
every thing is fine , **until** I unplug the board.
when I unplug the power cable(ungraceful shut down), The system image is damaged  and the device stuck with red/yellow spot while booting so I need to reflash the board.

Thanks,
Ori

 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @oriyaish it is expected that the system image could get corrupted if you unplug it when it is running.

https://coral.ai/docs/dev-board-mini/get-started/#8-safely-shut-down-the-board

**Comment by oriyaish** [comment]
@hjonnala 
I guess it's a software issue because it's depends on version/update.

**Comment by hcindyl** [comment]
The file system emergency mode is expected if you don't shutdown the board properly, and the board needs to check the integrity of the file system. If you have the UART debug console linked to the 40-pin header, you can recover the board from the emergency mode without reflashing the board.

**Comment by Path-A** [comment]
@hcindyl @hjonnala  Is there a way to disable emergency mode? Our board will be placed in a location that is almost always unreachable and we would like it to attempt booting after a power failure.

**Comment by LukaBanovic** [comment]
@hjonnala @hcindyl I know it's written in the instruction manual but still...how is it possible for this to happen so easily? Many people are using Coral boards in the same way they are using raspberry pi, which hasn't got this issue.. It's really inconvenient.

**Comment by PeterMalkin** [comment]
@LukaBanovic Raspberry pi has exactly same issue. Even worse. If you unplug it during a write operation is in progress, the filesystem gets corrupt and the system becomes unbootable. At least with the Coral board you can recover using the emergency mode. No such option for raspberry pi, unless you repartition the sdcard and mount the root filesystem as readonly, like in this article: https://medium.com/@andreas.schallwig/how-to-make-your-raspberry-pi-file-system-read-only-raspbian-stretch-80c0f7be7353

**Comment by pmankow** [comment]
This is not true, my pihole runs fine after power outages. The coral corrupts if you even look at it funny. Even incorporating an option to shutdown safely if the primary supply is lost would be useful. It is funny because this device is intended for the 'edge' but it cannot survive the conditions of any real edge application where power is flaky in the best of circumstances.

**Comment by Path-A** [comment]
> This is not true, my pihole runs fine after power outages. The coral corrupts if you even look at it funny. Even incorporating an option to shutdown safely if the primary supply is lost would be useful. It is funny because this device is intended for the 'edge' but it cannot survive the conditions of any real edge application where power is flaky in the best of circumstances.

We've since dropped our efforts to use the edgetpu. It's an awesome piece of hardware, but it's simply not robust enough for real edge applications.

**Comment by beltrame** [comment]
The solution would simply be to use a journaled filesystem for the boot partition. Is there any reason why it is ext2?
