### ISSUE TITLE
Booting SoM on Custom Board

### ISSUE THREAD

**Issue by murreletinnovation** [google-coral/edgetpu#529]
### Description

Hi Google Coral Team,

I am working on a custom board that makes use of the Google SoM, but unfortunately it is failing to boot. I have written a startup script that flashes an LED (GPIO 6) after the SoM has booted, and I have confirmed its functionality when working off of the Dev Board. When I move the SoM to the custom board, I am unfortunately not seeing this behavior.

I was hoping you could help me understand the most common issues that I could be facing. From my understanding there are several things I need for a proper (internal) boot sequence:

1. BOOT_MODE0=0 and BOOT_MODE1=1 
2. Not latching any of the SAI1_RX or SAI1_TX lines
3. Not latching SAI5_RXD1, SAI5_RXD3, and SAI5_RXFS 

I understand that there are a fair number of issues that can arise from building a custom board, but I was wondering if there are any other notes in the datasheet/application notes that I have missed regarding the boot process.

Thank you!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Operating System

Mendel Linux

### Coral Device

SoM

### Programming Language

Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi BOOT_MODE0=0 and BOOT_MODE1=1 is for serial downloader boot type. Can you please let us know which type of boot  are you trying to perform? Thanks!

https://coral.ai/static/files/Coral-SoM-datasheet.pdf

**Comment by murreletinnovation** [comment]
I believe we're trying to perform an internal boot. Am I misunderstanding what BOOT_MODE[1:0]=10 means? I thought that would imply that the 0-index bit is 0 and the 1-index bit is 1.

**Comment by hjonnala** [comment]
> I believe we're trying to perform an internal boot. Am I misunderstanding what BOOT_MODE[1:0]=10 means? I thought that would imply that the 0-index bit is 0 and the 1-index bit is 1.

Sorry, I misunderstood it. 

Unfortunately, we don't have resources to  review the custom baseboard design. Please check the dev board schematics below and compare it with the custom board. Thanks!

https://github.com/google-coral/electricals/tree/master/dev_board

**Comment by alcandelario** [comment]
Hi @hjonnala , the original poster (and myself now) are asking for confirmation of the required bootmode 1:0 settings for an emmc based boot, and if there are any other core signals that must be in known states for emmc boot to work as intended. 

The official coral schematic shows 00 as "boot from fuses" which was assumed how emmc boot was achieved but even if not this page seems to suggest 1:0 is for what is needed for emmc boot: https://coral.ai/docs/som/get-started/#flash-the-board

Do you have any possible insight into what we're missing in terms of interpreting the docs? We are also not able to boot the SOM on a custom carrier board but the same SOM boots from emmc while mounted on the dev board.

Thank you for any help you may be able to provide!

**Comment by hjonnala** [comment]
Hi @alcandelario the default configuration to boot SOM from eMMC is
BOOT_MODE0=0,  BOOT_MODE1=1, SAI1_TXD4 =0 and SAI1_TXD5=1
