### ISSUE TITLE
Failing to connect M.2 to Jetson Nano DevKit

### ISSUE THREAD

**Issue by samsterckval** [google-coral/edgetpu#53]
Hi,

I am having issues connecting the M.2 accelerator to the Jetson Nano DevKit.
I followed each instruction, here is the output for some commands : 

**lspci**
0:02.0 PCI bridge: NVIDIA Corporation Device 0faf (rev a1)
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)

**lsusb** (not really relevant, but hey, more info is better right?)
Bus 002 Device 002: ID 0bda:0411 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 046a:000c Cherry GmbH 
Bus 001 Device 003: ID 046d:c31c Logitech, Inc. Keyboard K120
Bus 001 Device 002: ID 0bda:5411 Realtek Semiconductor Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**lsmod**
Module Size Used by
bnep 16562 2
fuse 103841 2
overlay 48691 0
zram 26166 4
spidev 13282 0
nvgpu 1575721 18
bluedroid_pm 13912 0
ip_tables 19441 0
x_tables 28951 1 ip_tables

**modinfo gasket**
filename: /lib/modules/4.9.140-tegra/updates/dkms/gasket.ko
author: Rob Springer <rspringer@google.com>
license: GPL v2
version: 1.1.3
description: Google Gasket driver framework
srcversion: 069B6D0F6AE12073F4EAF5D
depends: 
vermagic: 4.9.140-tegra SMP preempt mod_unload modversions aarch64
parm: dma_bit_mask:int

**modinfo apex**
filename: /lib/modules/4.9.140-tegra/updates/dkms/apex.ko
author: John Joseph <jnjoseph@google.com>
license: GPL v2
version: 1.1
description: Google Apex driver
srcversion: 508A8A34D57322CEA287D17
alias: pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends: gasket
vermagic: 4.9.140-tegra SMP preempt mod_unload modversions aarch64
parm: allow_power_save:int
parm: allow_sw_clock_gating:int
parm: allow_hw_clock_gating:int
parm: bypass_top_level:int
parm: trip_point0_temp:int
parm: trip_point1_temp:int
parm: trip_point2_temp:int
parm: hw_temp_warn1:int
parm: hw_temp_warn2:int
parm: hw_temp_warn1_en:bool
parm: hw_temp_warn2_en:bool
parm: temp_poll_interval:int

**dpkg -l | grep gasket**
ii gasket-dkms 1.0-10 all DKMS source for the gasket driver

**uname -a**
Linux jetson-desktop 4.9.140-tegra #1 SMP PREEMPT Mon Dec 9 22:47:42 PST 2019 aarch64 aarch64 aarch64 GNU/Linux

**dmesg | grep pci**
[ 0.967687] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.3, lane = pcie-0, function = pcie-x1
[ 0.967783] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.4, lane = pcie-1, function = pcie-x4
[ 0.967870] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.5, lane = pcie-2, function = pcie-x4
[ 0.967967] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.6, lane = pcie-3, function = pcie-x4
[ 0.968054] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.7, lane = pcie-4, function = pcie-x4
[ 0.968142] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.8, lane = pcie-5, function = xusb
[ 0.968225] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.9, lane = pcie-6, function = xusb
[ 0.977971] tegra-pcie 1003000.pcie: 4x1, 1x1 configuration
[ 0.979254] tegra-pcie 1003000.pcie: PCIE: Enable power rails
[ 0.979641] tegra-pcie 1003000.pcie: probing port 0, using 4 lanes
[ 0.983636] tegra-pcie 1003000.pcie: probing port 1, using 1 lanes
[ 1.071883] ehci-pci: EHCI PCI platform driver
[ 1.071939] ohci-pci: OHCI PCI platform driver
[ 1.406312] tegra-pcie 1003000.pcie: link 0 down, retrying
[ 1.818326] tegra-pcie 1003000.pcie: link 0 down, retrying
[ 2.231469] tegra-pcie 1003000.pcie: link 0 down, retrying
[ 2.233537] tegra-pcie 1003000.pcie: link 0 down, ignoring
[ 2.337986] tegra-pcie 1003000.pcie: PCI host bridge to bus 0000:00
[ 2.337992] pci_bus 0000:00: root bus resource [io 0x0000-0xffff]
[ 2.337995] pci_bus 0000:00: root bus resource [mem 0x13000000-0x1fffffff]
[ 2.337999] pci_bus 0000:00: root bus resource [mem 0x20000000-0x3fffffff pref]
[ 2.338003] pci_bus 0000:00: root bus resource [bus 00-ff]
[ 2.338023] pci 0000:00:02.0: [10de:0faf] type 01 class 0x060400
[ 2.338085] pci 0000:00:02.0: PME# supported from D0 D1 D2 D3hot D3cold
[ 2.338227] pci 0000:00:02.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[ 2.338328] pci 0000:01:00.0: [10ec:8168] type 00 class 0x020000
[ 2.338351] pci 0000:01:00.0: reg 0x10: [io 0x0000-0x00ff]
[ 2.338381] pci 0000:01:00.0: reg 0x18: [mem 0x00000000-0x00000fff 64bit]
[ 2.338401] pci 0000:01:00.0: reg 0x20: [mem 0x00000000-0x00003fff 64bit]
[ 2.338532] pci 0000:01:00.0: supports D1 D2
[ 2.338535] pci 0000:01:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[ 2.349910] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[ 2.349936] pci 0000:00:02.0: BAR 14: assigned [mem 0x13000000-0x130fffff]
[ 2.349940] pci 0000:00:02.0: BAR 13: assigned [io 0x1000-0x1fff]
[ 2.349946] pci 0000:01:00.0: BAR 4: assigned [mem 0x13000000-0x13003fff 64bit]
[ 2.349963] pci 0000:01:00.0: BAR 2: assigned [mem 0x13004000-0x13004fff 64bit]
[ 2.349979] pci 0000:01:00.0: BAR 0: assigned [io 0x1000-0x10ff]
[ 2.349987] pci 0000:00:02.0: PCI bridge to [bus 01]
[ 2.349990] pci 0000:00:02.0: bridge window [io 0x1000-0x1fff]
[ 2.349996] pci 0000:00:02.0: bridge window [mem 0x13000000-0x130fffff]
[ 2.350212] pcieport 0000:00:02.0: Signaling PME through PCIe PME interrupt
[ 2.350215] pci 0000:01:00.0: Signaling PME through PCIe PME interrupt
[ 2.350220] pcie_pme 0000:00:02.0:pcie001: service driver pcie_pme loaded
[ 2.350299] aer 0000:00:02.0:pcie002: service driver aer loaded

**dmesg | grep gasket** yields nothing...

Does anyone have any idea how I could resolve this? Seems the EdgeTPU is not even powered up...

**Comment by Namburger** [comment]
@samsterckval does `ls /dev/apex_0` shows anything? 
Seems that the PCIe from the jetson nano doesn't support NVME and only SATA from reading [this post](https://devtalk.nvidia.com/default/topic/1049706/jetson-nano/can-this-board-use-m-2-ssd-nvme/). Could you confirm with the jetson nano team?

**Comment by samsterckval** [comment]
ls /dev/apex_0 gives the “no such directory” error.
Some people have got it working on Jetson Nano DevKit already, so I posted it on their forum as well.

(Sorry for shitty formatting, posting on mobile)

**Comment by Namburger** [comment]
@samsterckval No worries about the formatting. 
Looking at [this thread](https://devtalk.nvidia.com/default/topic/1068260/jetson-nano/m-2-pcie-google-coral-in-ubuntu-/post/5419410/#5419410), I suggest you do the same as the latest comment. Maybe supply more power, only plug in what you need and try again?

**Comment by samsterckval** [comment]
Yes, that is actually the thread I posted it in.
I will do so tomorrow and supply this thread with the outcome aswell.

**Comment by samsterckval** [comment]
Problem has been solved.  It seems there was a problem with the Seeed Studio carrier board itself.
After swapping carrier boards, the accelerator worked like a charm.

**Comment by Namburger** [comment]
Awesome!

**Comment by Sayyam-Jain** [comment]
> Problem has been solved. It seems there was a problem with the Seeed Studio carrier board itself.
> After swapping carrier boards, the accelerator worked like a charm.

Hello Sir. I just got Jetson nano (B01). I want to use Coral TPU (M.2 A+E key) with it. Is it compatible with Jetson's M.2 E Port?
I'm a total noob. Can you please guide me on how to do so?

Thank you

**Comment by Namburger** [comment]
@Sayyam-Jain as you could see from above, we got it working!

**Comment by apayne19** [comment]
@samsterckval which carrier board did you switch to? Having similar issues on the B01 carrier board

**Comment by samsterckval** [comment]
Same carrier board, but a new one.  It seems a power related issues, the previous carriers seems to fail every time we connected both a coral m.2 and a CSI camera.  Haven't tried if the B01 version fixed it, but apparently it didn't :-(

**Comment by ricardodeazambuja** [comment]
I've notice nobody here mentioned heat. Edgetpus may get quite hot and, in the Jetson Nano carrier board, the slot is located under the hottest part (GPU/CPU) without much space for air to circulate or a place to give away heat. Convection, with the carrier board laying flat, will just make things worse. I'm wondering if the problems mentioned here were heat related. Have anyone checked whether the problems were related to overheating (or driver/software not turning on the throttle automatically)?
