### ISSUE TITLE
Model has multiple output

### ISSUE THREAD

**Issue by vikashpatel1985** [google-coral/edgetpu#530]
### Description

Hi Google Coral Team,

I am converting a quant model to EdgeTPU model using edgetpu compiler version 14.1.317412892. Quant model has multiple output (3 output), when I am trying to convert it to edgeTPU model using command "edgetpu_compiler -i outputname *.tflite", multiple outputs are not generated, only single output is generating. Can you please help me on how to convert quant model with multiple output to EdgeTPU model with same number of output.

Thank you.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

Python 3.6

### Relevant Log Output

```shell
EdgeTPU Model is generated successfully with single output, expected was multiple output.

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 13
Number of operations that will run on CPU: 21
See the operation log file for individual operation details.
```
</details>

**Comment by hjonnala** [comment]
Hi @vikashpatel1985  please try with latest `compiler version 16.0.384591198`

https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb

**Comment by hjonnala** [comment]
Feel free to reopen if issue still exists. Thanks!
