### ISSUE TITLE
How to train SSD_MobiletNetV2 using Tensorflow2

### ISSUE THREAD

**Issue by corvitacvision** [google-coral/edgetpu#533]
Recently, SSD_MobileNet V2 was added in the list of [https://coral.ai/models/object-detection/](url). 

- Can I get information how it trained using Tensorflow version 2 specifically? 
- Is it trained using Tensorflow Object Detection API with Tensorflow2 version?
- Is it possible to do quantize aware training with Tensorflow version 2 (with Tensorlfow Object Detection API)?
- 
Thank you very much for your time. If I get answer to these questions, it will be very helpful.

**Comment by hjonnala** [comment]
Hello @corvitacvision  SSD_MobileNet V2 was trained with TF 1.x version. 

The [quantization-aware training API with TF2](https://www.tensorflow.org/model_optimization/guide/quantization/training) is not compatible with the object detection API; it is compatible with image classification models only. For more compatibility, including with the object detection API, you may use [quantization-aware training with TF1](https://github.com/tensorflow/tensorflow/tree/r1.15/tensorflow/contrib/quantize#quantization-aware-training) or use post-training quantization with TF2.

We will update the info here if anything changes in future: https://coral.ai/docs/edgetpu/models-intro/#quantization

Thanks
