### ISSUE TITLE
Which optimizations parameters can be tuned to get better performances?

### ISSUE THREAD

**Issue by colab999** [google-coral/edgetpu#534]
### Description

Hello everyone! 
I've been working with a Google Coral Dev Board Mini and converted different models (most of them based on mobilenet). They compiled successfully, but I was wondering if there are any parameters or options to be set in order to further optimize the models. For example, the edge tpu supports only 8bit quantization, so trying to quantize on 16bit is out of the list. One option is to quantize also input and output layers to reduce the load on cpu (I have to check the impact of this operation though), but I'm curious if I've missed something.

By reading the [TFLite docs](https://www.tensorflow.org/lite/performance/model_optimization?hl=en#types_of_optimization), I found out that it is possible to perform operations such as:

1. [Quantization Aware Training](https://www.tensorflow.org/model_optimization/guide/quantization/training)
2. [Weights pruning](https://www.tensorflow.org/model_optimization/guide/pruning) 
3. [Weights clustering](https://www.tensorflow.org/model_optimization/guide/clustering)

Regarding the first point, it is written in the coral docs that it is not supported on tf2 (at least for detectors), but I cannot find this information in the TF doc. **Is quantization aware training unsupported or something is wrong in the docs?**

Regarding points 2 and 3, my main concern is that none of those operations is mentioned in the coral docs or elsewhere on the internet! So I'm wondering if they are compatible, if it is worth it trying or if the edgetpucompiler already performs some of these optimizations. From what I understand pruning and clustering should help reduce the memory requirements (especially pruning should help with the low memory of tpu if I understood it correctly).

I've also read some papers where they found out that smaller (or bigger, due to low on-chip ram) models run better on cpu than tpu.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support, Documentation Feature Request, Others

### Coral Device

Dev Board Mini

### Programming Language

C++, Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @colab999 

Yes,The [quantization-aware training API with TF2](https://www.tensorflow.org/model_optimization/guide/quantization/training) is not compatible with the object detection API; it is compatible with image classification models only. For more compatibility, including with the object detection API, you may use [quantization-aware training with TF1](https://github.com/tensorflow/tensorflow/tree/r1.15/tensorflow/contrib/quantize#quantization-aware-training) or use post-training quantization with TF2.

We will update the info here if anything changes in future: https://coral.ai/docs/edgetpu/models-intro/#quantization

AFAIK, pruning and clustering are not compatible with Coral. Edgetpucompiler does not perform either pruning or clustering optimization.

Thanks!
