### ISSUE TITLE
TPU Edge performance on RPI 4

### ISSUE THREAD

**Issue by cl3m3nt** [google-coral/edgetpu#537]
### Description

Hi, 

I am trying to leverage TPU Edge HW on Raspberry Pi 4 Model B.
I trained an SSD Mobilenet 320x320 object detection model to run inference on RPI with TPU Edge.
I got better performance using XNNPACK CPU delegate (RPI default) than TPU Edge delegate on same tflite model.
Full code code without TPU and TPU + Data sample here: https://drive.google.com/drive/folders/1ZDCHHNGWd7shBYpRMsjeXmUvxWstB5xA?usp=sharing
I appreciate your help.

code example:

import csv
import os
from logzero import logger
import numpy as np
import pandas as pd
import tensorflow as tf
from datetime import datetime, timedelta
from numpy import asarray
from PIL import Image
from pathlib import Path
from pycoral.utils import edgetpu
from pycoral.adapters import common

# Parameters
DIR_PATH = Path(__file__).parent.resolve()
DATA_FOLDER = './data_tbshoot/'
#MODEL_FILE = 'model.tflite'
MODEL_FILE = 'model_full_int.tflite'

  
# Load  TFLite model and allocate tensors.
def load_tflite_model(model_path):
  """helper function to load the tflite object detection model
  Returns:
      interpreter: the actual tflite interpreter/model
  """
  tflite_model_path  = model_path
  interpreter = edgetpu.make_interpreter(tflite_model_path)
  #interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
  interpreter.allocate_tensors()
  return interpreter

def get_pad_resized_img(size,img_tensor):
  """resize a tensor image to model expected input shape
  Args:
      size (int): size to rescale tensor to width and heigth
      img_tensor (tf.tensor): tf tensor to be rescaled
  Returns:
      resized_img: resized image tensor
  """
  resized_img = tf.image.resize_with_pad(
        img_tensor, size,size,
        antialias=False
    )
  #resized_img = tf.cast(resized_img,dtype=tf.uint8)
  return resized_img

def get_tflite_prepared_image(image_name):
  """[summary]
  Args:
      image_name ([type]): [description]
  Returns:
      [type]: [description]
  """
  image_file = image_name + '.jpg'
  img_pil = Image.open(DATA_FOLDER+image_file)
  img_np = asarray(img_pil)
  img_tensor = tf.expand_dims(tf.convert_to_tensor(
    img_np, dtype=tf.float32), axis=0)
  preprocessed_img =  get_pad_resized_img(320,img_tensor)
  return preprocessed_img
  

def get_tflite_predictions(image_name,tflite_interpreter):
  """create prediction on image using tflite interpreter/model
  Args:
      image_name ([type]): [description]
      tflite_interpreter (tflite interpreter: tflite interpreter/model for object detection
  Returns:
      boxes,classes,scores (tuple): model prediction on image 
  """
  # Prepare image
  preprocessed_img = get_tflite_prepared_image(image_name)
  input_tensor = preprocessed_img
  input_tensor = tf.cast(input_tensor,dtype=tf.int8)
  #input_tensor = tf.cast(input_tensor,dtype=tf.float32)
  image_tflite_np = input_tensor.numpy()

  # Interpreter/Model settings
  input_details = tflite_interpreter.get_input_details()
  output_details = tflite_interpreter.get_output_details() 
  input_shape = input_details[0]['shape'] 
  input_data = image_tflite_np.reshape(input_shape)
  tflite_interpreter.set_tensor(input_details[0]['index'], input_data)
  tflite_interpreter.invoke()

  # Data from tflite inference: boxes, classes, scores
  boxes = tflite_interpreter.get_tensor(output_details[1]['index'])
  classes = tflite_interpreter.get_tensor(output_details[3]['index'])
  scores = tflite_interpreter.get_tensor(output_details[0]['index'])

  logger.info(f'Inference successful for {image_name}')

  return boxes, classes, scores

# Main function definition
def main():
  # Starting Experiment
  start_time = datetime.now()
  logger.info(f'Starting experiment at {start_time.strftime("%Y-%m-%d %H:%M:%S")}')

  # Simulated images
  files = os.listdir(DATA_FOLDER)
  images_name = [os.path.splitext(file)[0] for file in files if os.path.splitext(file)[1] != '.xml']
  images_name.sort()

  # Loading TFLite model
  interpreter = load_tflite_model(str(DIR_PATH)+'/'+MODEL_FILE)

  # Doing Prediction
  for img in images_name:
      tflite_prediction = get_tflite_predictions(img,interpreter)  

  # End of experiment
  end_time = datetime.now()
  logger.info(f'Finishing experiment at {end_time.strftime("%Y-%m-%d %H:%M:%S")}')
  experiment_time = end_time - start_time
  logger.info(f'experiment run time {experiment_time}')

# Main execution
if __name__ == '__main__':
    main()

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Linux, Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @cl3m3nt  can you please share the following details:
- edgetpu compiler logs (edgetpu_compiler -s model.tflite)
- output of the below script with cpu tflite and edgeptu tflite model : https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py

Thanks!

**Comment by cl3m3nt** [comment]
Hi Hemant, thanks for your feedback.
Please find below output from edgetpu complier logs as well as pycoral detect_image.py example script:

- edgetpu compiler logs: 
Edge TPU Compiler version 16.0.384591198
Input: tflite_quant_model.tflite
Output: tflite_quant_model_edgetpu.tflite

Operator                       Count      Status

RESHAPE                                    6          Mapped to Edge TPU
RESHAPE                                    4          More than one subgraph is not supported
RESHAPE                                    2          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
LOGISTIC                                    1          More than one subgraph is not supported
DEPTHWISE_CONV_2D             37         Mapped to Edge TPU
DEPTHWISE_CONV_2D             14         More than one subgraph is not supported
QUANTIZE                                   4          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONV_2D                                    14         More than one subgraph is not supported
CONV_2D                                    58         Mapped to Edge TPU
DEQUANTIZE                              2          Operation is working on an unsupported data type
CUSTOM                                     1          Operation is working on an unsupported data type
ADD                                             10         Mapped to Edge TPU
ADD                                             2          More than one subgraph is not supported
CONCATENATION                      2          More than one subgraph is not supported
PACK                                           4          Tensor has unsupported rank (up to 3 innermost dimensions mapped)


- detect_image.py logs:
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
42.53 ms
18.95 ms
18.52 ms
18.44 ms
18.46 ms
-------RESULTS--------
tie
  id:     31
  score:  0.83984375
  bbox:   BBox(xmin=227, ymin=419, xmax=292, ymax=541)
person
  id:     0
  score:  0.8046875
  bbox:   BBox(xmin=2, ymin=4, xmax=513, ymax=595)
option parsing failed: Cannot open display: 


I appreciate your feedback.

**Comment by hjonnala** [comment]
Hello @cl3m3nt  seems to be most the operations are not mapped to TPU. Please try to compile wit -a flag. ((edgetpu_compiler -s -a  model.tflite) and share the inference time results for both tflite_quant_model.tflite and tflite_quant_model_edgetpu.tflite models. 

Thanks!
