### ISSUE TITLE
Run MAC operation on Edge TPU

### ISSUE THREAD

**Issue by Yin-Jiaqi** [google-coral/edgetpu#538]
### Description

We are trying to run MAC operations on Edge TPU with the self-defined matrix. But the results are not correct.

The model is a simple Dense layer. I defined the kernel is a [2], input is [3]. So basically it's a simple 2*3 multiplication. But the Edge TPU result is 3. As a comparison, I run it on CPU, it got the correct results 6. I also build a self-defined dense layer. The results are still not correct.

The full code are attached in here:
https://colab.research.google.com/drive/1mYCvhXoVXS4gl0m5LTryqoAGXH8_mFgg?usp=sharing

I appreciate your help.

- **Model definition:**

```
input_size=1;initializers=2;unit=1
dense_model=tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(1, input_size)),
  tf.keras.layers.Dense(unit,kernel_initializer=tf.keras.initializers.Constant(initializers),bias_initializer=tf.zeros_initializer(), activation=None)
])
```

- **Quantization**

```
class data:
    def __init__(self, shape):
        self.shape = shape
   
    def data_set(self):
        for _ in range(50):
            data=[]
            for s in self.shape:
                data.append(np.random.rand(*s).astype(np.float32))
            yield data
            
input_shape=[[1,1,input_size]]
datas=data(input_shape)
converter = tf.lite.TFLiteConverter.from_keras_model(dense_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset =datas.data_set
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_types = [tf.int8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()
with open('dense_model_quant.tflite', 'wb') as f:
    f.write(tflite_model)
```

- **Run inference**
```
input_value=3
dense_model_file = os.path.join('dense_model_quant_edgetpu.tflite')
dense_interpreter = edgetpu.make_interpreter(dense_model_file)
dense_interpreter.allocate_tensors()
data=np.ones(input_size,dtype=np.uint8)*input_value
edgetpu.run_inference(dense_interpreter, data)
ipt=[input_value for _ in range(input_size)]
kernal=[initializers for _ in range(input_size)]
print('custom:',ipt,'*',kernal,'CPU:',custom_model(np.ones((1,1,input_size))*input_value),'TPU:',common.output_tensor(custom_interpreter,0))
```

- **Output**

`custom: [3] * [2] CPU: tf.Tensor([[6.]], shape=(1, 1), dtype=float32) TPU: [[3]]`

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @jiaqiyin1995  can you please check with tflite team as cpu tflite model result itself is 3. Thanks

<details>
<summary>code</summary>

import tflite_runtime.interpreter as tflite
import os
import numpy as np
import tensorflow as tf


input_size=1;initializers=2;unit=1;input_value=3


class LinearLayer(tf.keras.layers.Layer):
    def __init__(self, units):
        super().__init__()
        self.units = units

    def build(self, input_shape):
        self.w = self.add_weight(name='w',
                                 shape=[input_shape[-1], self.units], initializer=tf.keras.initializers.Constant(
                initializers))  # initializer=tf.random_normal_initializer()
        self.b = self.add_weight(name='b',
                                 shape=[self.units], initializer=tf.zeros_initializer())

    def call(self, inputs):
        y_pred = tf.linalg.matmul(inputs, self.w) + self.b
        return y_pred


custom_model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(1, input_size)),
    LinearLayer(unit)
    # tf.keras.layers.Dense(1,kernel_initializer=tf.keras.initializers.Constant(100),bias_initializer='zeros', activation='relu')(input_1)
])

dense_model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(1, input_size)),
    tf.keras.layers.Dense(unit, kernel_initializer=tf.keras.initializers.Constant(initializers),
                          bias_initializer=tf.zeros_initializer(), activation=None)
])


base_dir = '/home/Downloads/'
models = ['custom_model_quant_edgetpu.tflite', 'custom_model_quant.tflite', 'dense_model_quant.tflite', 'dense_model_quant_edgetpu.tflite']
for model in models:
    print(model)
    model_path = os.path.join(base_dir, model)
    if 'edgetpu' in model:
        interpreter = tflite.Interpreter(
            model_path=model_path, experimental_delegates=[tflite.load_delegate('libedgetpu.so.1', {})])
    else:
        interpreter = tflite.Interpreter(model_path=model_path)

    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    interpreter.set_tensor(input_details[0]['index'], np.ones((1,1,input_size), dtype=np.uint8)*input_value)
    interpreter.invoke()
    ipt=[input_value for _ in range(input_size)]
    kernal=[initializers for _ in range(input_size)]
    if 'custom' in model:
        print('custom:',ipt,'*',kernal,'CPU:',custom_model(np.ones((1,1,input_size))*input_value),'TPU:', interpreter.get_tensor(output_details[0]['index']))
    else:
        print('custom:', ipt, '*', kernal, 'CPU:', dense_model(np.ones((1, 1, input_size)) * input_value),
              'TPU:', interpreter.get_tensor(output_details[0]['index']))

</details>

output:
custom_model_quant_edgetpu.tflite
custom: [3] * [2] CPU: tf.Tensor([[6.]], shape=(1, 1), dtype=float32) TPU: [[3]]
custom_model_quant.tflite
custom: [3] * [2] CPU: tf.Tensor([[6.]], shape=(1, 1), dtype=float32) TPU: [[3]]
dense_model_quant.tflite
custom: [3] * [2] CPU: tf.Tensor([[6.]], shape=(1, 1), dtype=float32) TPU: [[3]]
dense_model_quant_edgetpu.tflite
custom: [3] * [2] CPU: tf.Tensor([[6.]], shape=(1, 1), dtype=float32) TPU: [[3]]
