### ISSUE TITLE
Installing CORAL on x86-64bit DEBIAN ....

### ISSUE THREAD

**Issue by ZXRobotum** [google-coral/edgetpu#541]
Good evening,
I no longer understand anything about your software. I followed your instructions to install a PCIe card in my x86 system. Now I get another ERROR, although it is a normal computer with DEBIAN.

I get the following error message in the LOG (/var/lib/dkms/gasket/1.0/build/make.log):

DKMS make.log for gasket-1.0 for kernel 5.16.0-1-amd64 (x86_64)
Fri Feb 18 10:26:47 PM CET 2022
make: Entering directory '/usr/src/linux-headers-5.16.0-1-amd64'
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_sysfs.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/apex_driver.o
  LD [M]  /var/lib/dkms/gasket/1.0/build/apex.o
  LD [M]  /var/lib/dkms/gasket/1.0/build/gasket.o
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
  MODPOST /var/lib/dkms/gasket/1.0/build/Module.symvers
ERROR: modpost: module gasket uses symbol dma_buf_detach from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_put from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_get from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_unmap_attachment from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_map_attachment from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_attach from namespace DMA_BUF, but does not import it.
make[1]: *** [/usr/src/linux-headers-5.16.0-1-common/scripts/Makefile.modpost:134: /var/lib/dkms/gasket/1.0/build/Module.symvers] Error 1
make[1]: *** Deleting file '/var/lib/dkms/gasket/1.0/build/Module.symvers'
make: *** [/usr/src/linux-headers-5.16.0-1-common/Makefile:1785: modules] Error 2
make: Leaving directory '/usr/src/linux-headers-5.16.0-1-amd64'

Would you like to tell me, what is here now wrong?
Best regards

Z. Matthias

**Comment by hjonnala** [comment]
Hello @ZXRobotum could you please share the complete installations logs to investigate the issue. Thanks!

**Comment by ZXRobotum** [comment]
Hey @hjonnala, what do you mean with "installation" log file? I sent the LOG in my message. Best regards Z. Matthias

**Comment by mbrooksx** [comment]
Both the source (https://github.com/google/gasket-driver) and the gasket-dkms package have been updated with support for >= 5.16.

**Comment by ZXRobotum** [comment]
With your new Version of package it's work now. Thank you.
