### ISSUE TITLE
Installing CORAL M.2 - Board under x86 with DEBIAN 

### ISSUE THREAD

**Issue by ZXRobotum** [google-coral/edgetpu#543]
Good day,
I completely rebuilt my 2nd server today with the latest Debian OS installed.
The computer has the M.2 module on board.

Unfortunately, the installation of "gasket-dkms" did not go through here either. Here is the complete output of the LOG file (/var/lib/dkms/gasket/1.0/build/make.log)

DKMS make.log for gasket-1.0 for kernel 5.16.0-1-amd64 (x86_64)
Sat Feb 19 01:29:13 PM CET 2022
make: Entering directory '/usr/src/linux-headers-5.16.0-1-amd64'
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_sysfs.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/apex_driver.o
  LD [M]  /var/lib/dkms/gasket/1.0/build/apex.o
  LD [M]  /var/lib/dkms/gasket/1.0/build/gasket.o
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-1-common/scripts/pahole-flags.sh: not found
  MODPOST /var/lib/dkms/gasket/1.0/build/Module.symvers
ERROR: modpost: module gasket uses symbol dma_buf_detach from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_put from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_get from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_unmap_attachment from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_map_attachment from namespace DMA_BUF, but does not import it.
ERROR: modpost: module gasket uses symbol dma_buf_attach from namespace DMA_BUF, but does not import it.
make[1]: *** [/usr/src/linux-headers-5.16.0-1-common/scripts/Makefile.modpost:134: /var/lib/dkms/gasket/1.0/build/Module.symvers] Error 1
make[1]: *** Deleting file '/var/lib/dkms/gasket/1.0/build/Module.symvers'
make: *** [/usr/src/linux-headers-5.16.0-1-common/Makefile:1785: modules] Error 2
make: Leaving directory '/usr/src/linux-headers-5.16.0-1-amd64'

**Comment by mbrooksx** [comment]
Both the source (https://github.com/google/gasket-driver) and the gasket-dkms package have been updated with support for >= 5.16.

**Comment by ZXRobotum** [comment]
With your new Package, I can solved my problem. Thanks....
