### ISSUE TITLE
Distinguish between regular and Edge TPU model

### ISSUE THREAD

**Issue by paradigmn** [google-coral/edgetpu#546]
### Description

This issue is concerned with the distinction of TFLite models before and after the Edge TPU Compiler. Both share the same file extension (.tflite) but are fundamental different in terms of execution. A regular model will not utilize the TPU, even though it is loaded with the libedgetpu delegate. On the other hand, a TPU model can not be executed on the CPU, if it contains at least one EdgeTPU op.

Is it possible to determine whether a model was compiled by the Edge TPU Compiler during runtime? I am using the tflite-runtime Python package to load and execute a model. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
@paradigmn if you are using linux machine you can use the compiler log to determine whether it is already compiled for edgetpu or not during runtime.

```
import subprocess
proc = subprocess.Popen(f""" {compiler_path}  -s  "{model_path}" -o {base_dir} """, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
output = [line.decode('utf-8') for line in proc.communicate()]
print(output)
```

**Comment by paradigmn** [comment]
@hjonnala this workaround does not feel satisfactory to me. It should not be necessary to ship the compiler log alongside the model for deployment. Basically, I am looking for a method to identify whether an external model, I just know the interface about (input/output), is TPU bound or not. The whole crux of this issue is that all models share the same file extension, regardless of their given assignment. If I interpret the [TF Docs Example](https://tensorflow.google.cn/lite/api_docs/python/tf/lite/experimental/load_delegate?hl=zh-cn) correctly, the idea of delegates was originally intended to execute a generic model on different hardware (similar to onnx+onnxruntime). As this clearly not works for EdgeTPU execution, should there not be a different file extension and/or meta information in the model which states the compiler version?

**Comment by hjonnala** [comment]
@paradigmn please try to get ops using `interpreter._get_ops_details()`. With this output you can determine the tflite model has edgetpu-custom-op or not.

**Comment by paradigmn** [comment]
@hjonnala I think I can work with that, thank you. A code snipped for everyone with the same issue: 
```
import tflite_runtime.interpreter as tflite

session = tflite.Interpreter('model.tflite')
'edgetpu-custom-op' in [op['op_name'] for op in session._get_ops_details()]
```
Another question in this regard: Is it possible to inject the delegate after the session was created? So the workflow would be: create session from model file -> check for EdgeTPU ops -> load libedgetpu if op is in model

**Comment by hjonnala** [comment]
I think, its not possible to load libedgetpu after the session got created. You have to recreate the session with the experimental delegates.

```
import platform
import tflite_runtime.interpreter as tflite

_EDGETPU_SHARED_LIB = {
  'Linux': 'libedgetpu.so.1',
  'Darwin': 'libedgetpu.1.dylib',
  'Windows': 'edgetpu.dll'
}[platform.system()]

interpreter = tflite.Interpreter(model_path=model_path)
if 'edgetpu-custom-op' in [op['op_name'] for op in  interpreter._get_ops_details()]:
    interpreter = tflite.Interpreter(
        model_path=model_path, experimental_delegates=[tflite.load_delegate(_EDGETPU_SHARED_LIB, {})])
interpreter.allocate_tensors()
```

**Comment by paradigmn** [comment]
Alright, this changes the workflow to: test for edgetpu -> if available load with libedgetpu delegate -> allocate tensors.

Thank you, that answers my questions.
