### ISSUE TITLE
Detection problem with custom Yolov5 model

### ISSUE THREAD

**Issue by constantinfite** [google-coral/edgetpu#548]
### Description

I want to run my custom yolov5 model on the coral dev board. 
I follow this tutoriel for this : https://github.com/jveitchmichaelis/edgetpu-yolo.
I exported my yolov5s.pt model into a tflite file with the official repository of yolov5.
Then I used the edgetpu_compiler on my tflite file. (log in copy)
I try to run my edgetpu yolov5 model in my coral. It runs but the detection is very slow (0.36s for one frame) and the bounding box occupies the entire image.
Like this : 
![image](https://user-images.githubusercontent.com/57963890/155331217-5ce9ea0b-080b-4018-8fd0-f647695dbae9.png)

I try with the default model of yolov5s. The bounding boxe surround the objects well and the speed is much faster 0.026s for the same frame.

My custom model was train on the yolov5-3.1, it's maybe outdated ..
I can transfer you my model if it is easier.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Relevant Log Output

```shell
Edge TPU Compiler version 16.0.384591198
Input: best-shark-yolov5s-int8.tflite
Output: best-shark-yolov5s-int8_edgetpu.tflite

Operator                       Count      Status

QUANTIZE                       24         More than one subgraph is not supported
QUANTIZE                       1          Mapped to Edge TPU
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONV_2D                        69         More than one subgraph is not supported
CONV_2D                        1          Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          More than one subgraph is not supported
CONCATENATION                  1          Mapped to Edge TPU
CONCATENATION                  17         More than one subgraph is not supported
RESHAPE                        6          More than one subgraph is not supported
TRANSPOSE                      3          More than one subgraph is not supported
MUL                            29         More than one subgraph is not supported
STRIDED_SLICE                  9          More than one subgraph is not supported
STRIDED_SLICE                  4          Mapped to Edge TPU
LOGISTIC                       3          More than one subgraph is not supported
SUB                            3          More than one subgraph is not supported
PAD                            6          More than one subgraph is not supported
LEAKY_RELU                     59         Operation not supported
ADD                            18         More than one subgraph is not supported
MAX_POOL_2D                    3          More than one subgraph is not supported
```
</details>

**Comment by hjonnala** [comment]
Hello @constantinfite  can you try with relu or relu6 instead of LEAKY_RELU as this operation is not [supported](https://coral.ai/docs/edgetpu/models-intro/#supported-operations) on TPU.

**Comment by constantinfite** [comment]
Hi @hjonnala thanks ! 
I saw that after the yolov5-4.0 version this relu was replaced. But I can't retrain my model with another version. Do you have some explanations on how to replace this relu ?

**Comment by paradigmn** [comment]
@constantinfite replacing the activation functions without retraining the weights will most likely render the model useless as the error introduced will add up from operation to operation.

**Comment by constantinfite** [comment]
@paradigmn So what's the best option in your opinion?

**Comment by paradigmn** [comment]
@constantinfite if you require the EdgeTPU, you have to train the model again, either with a modified YOLOv5-4.0 without leaky-relu or better with the newest version 6.1. If the accelerator type is not set, you could export your current model to Tensorflow/ONNX and run it on GPU.

**Comment by constantinfite** [comment]
Ok @paradigmn , I need to run it on the Coral dev Board, so it is only EdgeTPU no ? It doesn't have GPU on it ?

**Comment by paradigmn** [comment]
In theory the Coral Board has an embedded ARM GPU, though I do not think there is any easy way to utilize it. You could try running it CPU only, but that will result in poor performance.

**Comment by constantinfite** [comment]
@paradigmn ok so I need to retrain it ^^
Thanks !
