### ISSUE TITLE
Request Posenet *.tflite file (not compilied with edge_tpu_compiler yet) for co-complie purpose

### ISSUE THREAD

**Issue by AlexTraan** [google-coral/edgetpu#55]
Hi Team,
Currently, this repository only contained *_edgetpu.tflite file for posenet. I would like to request *.tflite file (not compilied with edge_tpu_compiler yet) for co-compile 2 model with edgetpu_compilier purpose.

Can you please help me?

**Comment by mtyka** [comment]
Uploaded. :)

**Comment by AlexTraan** [comment]
@mtyka @dmitriykovalev For co-compile posenet purpose, i lack of tflite file with only PosenetDecoderOp, can you help to upload it?

Thank you in advance

**Comment by mtyka** [comment]
Apologies for the late reply, I've been travelling the last weeks. I can
upload a network fragment when I return next week.

-- sent from my phone
