### ISSUE TITLE
Run ocr model on edgetpu

### ISSUE THREAD

**Issue by abucka** [google-coral/edgetpu#553]
### Description

Hello,

I try to convert ocr tfilte model to edgetpu model using edgetpu_compiler, unfortunately I get an error.

The model I try to convert is available here:
https://tfhub.dev/tulasiram58827/lite-model/keras-ocr/dr/2. 

The error can be found below.

Should I use some additional parameters to convert it or it is just not possible to convert this type of model?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Relevant Log Output

```shell
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
ERROR: Node number 106 (FlexCTCGreedyDecoder) failed to prepare.

Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter.
Compilation child process completed within timeout period.
Compilation failed!
```
</details>

**Comment by hjonnala** [comment]
Hello @abucka this model is not compatible with edgetpu due to FlexCTCGreedyDecoder operation. I have tried another OCR ful_int8 model(https://tfhub.dev/tulasiram58827/lite-model/rosetta/dr/1). Unfortunately, this model is also not fully compatible with edgetpu due to padv2 and large Transpose operations.

**Comment by abucka** [comment]
Hello @hjonnala, thank you for the information. Does it mean it's not possible to run the rest of the model on edgetpu and unsupported operations on CPU?

**Comment by hjonnala** [comment]
The first check would be to test the inference with tflite-runtime-2.5.0post1. As [inference](https://github.com/hjonnala/snippets/blob/main/coral_inference.py) with tflite-runtime is not possible for this model(https://tfhub.dev/tulasiram58827/lite-model/keras-ocr/dr/2), it won't be able to compile with edgetpu compiler.
