### ISSUE TITLE
Mediapipe

### ISSUE THREAD

**Issue by paulnegz** [google-coral/edgetpu#555]
Mediapipe is an open sourced ML library by google. It might be helpful to have a repo that has examples using the python APIs the library. Im currently trying to download the mediapipe python library using pip3 but it's not compatible with an ARM CPU.

**Comment by manoj7410** [comment]
@paulnegz Here is one demo https://github.com/manoj7410/trackerSortAndMediaPipe that uses MediaPipe. This was never published on the main repo due to the performance issues.
