### ISSUE TITLE
Can not segment efficientdet_lite3_512_ptq.tflite 

### ISSUE THREAD

**Issue by tyouritsugun** [google-coral/edgetpu#557]
Hi, 

Although others like `efficientdet_lite2_448_ptq.tflite` works well, I met a trouble when I tried to segment  `efficientdet_lite3_512_ptq.tflite` that grabbed from 

https://github.com/google-coral/test_data.git

When I ran the command below to segment the model, 

```
edgetpu_compiler --num_segments=2 efficientdet_lite3_512_ptq.tflite 
```
I got the error below
```
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 1857 ms.

Input model: efficientdet_lite3_512_ptq_segment_0_of_2.tflite
Input size: 5.20MiB
Output model: efficientdet_lite3_512_ptq_segment_0_of_2_edgetpu.tflite
Output size: 6.51MiB
On-chip memory used for caching model parameters: 6.02MiB
On-chip memory remaining for caching model parameters: 1.02MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 84
Operation log: efficientdet_lite3_512_ptq_segment_0_of_2_edgetpu.log
See the operation log file for individual operation details.
Compilation child process completed within timeout period.
Compilation succeeded! 
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Error: fail to compile model segment 1
```

Could anyone kindly tell me how to fix this?

Thank you in advance.

Tyouritsugun

**Comment by hjonnala** [comment]
@tyouritsugun efficientdet_lite3_512_ptq.tflite  can be compiled with intermediate tensor flag only. Since it can be compiled with -i flag only, we can't pass --num_segments commands to the compiler. https://coral.ai/docs/edgetpu/compiler/#usage
 

`edgetpu_compiler -s  -i "box_net/box-predict/BiasAdd;box_net/box-predict/separable_conv2d_4;box_net/box-predict/separable_conv2d;box_net/box-predict/bias"  efficientdet_lite3_512_ptq.tflite`

**Comment by tyouritsugun** [comment]
Thank you for your kindly reply.

Does this mean that I can not pipeline `efficientdet_lite3_512_ptq`?

Another question, the parameters of `box_net/box-predict/BiasAdd;box_net/box-predict/separable_conv2d_4;box_net/box-predict/separable_conv2d;box_net/box-predict/bias` are arcane to me, where can I find the documents to help me configure the correct parameters?

Tyouritsugun

**Comment by hjonnala** [comment]
Yes, you can't pipeline efficientdet_lite3_512_ptq.tflite model. 

The parameters to pass for [-i flag](https://coral.ai/docs/edgetpu/compiler/#usage) are the operation names. You can find these visualizing the model using https://netron.app/

![image](https://user-images.githubusercontent.com/86132058/158683224-af38cc00-29f2-4c26-8e59-4c5d814da8f1.png)

**Comment by tyouritsugun** [comment]
Thank you!

I think that I've met you somewhere else in github, you help me a lot!

Tyouritsugun
