### ISSUE TITLE
wlan0 MAC address spoofing

### ISSUE THREAD

**Issue by dimigaro** [google-coral/edgetpu#558]
### Description

I have a Coral Dev Board 4gb. 
I am booting from a 32gb SD card where I store the source code of my product and all the relevant results. 
I need to make another board run the same code so I created an image from the SD card of Coral Dev Board A and placed it 
into another SD carg of 32gb for Coral Dev Board B. Now both A and B have the same wlan0 MAC address which makes it impossible for them to work under the same network at the same time. 

I have install macchanger and run it with success changing the MAC address but no success making the ip link up again so board B with a new wlan0 MAC address does not have connection to internet. 

I have tried modifiying in /etc/NetworkManager/ the following files: 
- conf.d/wifi.scan-rand-mac-address.conf setting 
     wifi.scan-rand-mac-addres=yes
- NetworkManager.conf setting: 
     [connection]
     match-device=interface-name:wlan0
     wifi.cloned-mac-address=random
- system-connections/MYNETWORK.nmconnection setting:
     [wifi] 
     cloned-mac-address=random
     (deleting mac-address=ORIGINAL_MAC_ADDRESS)

I have also tried with nmcli with the following:
$ nmcli connection show
$ nmcli connection show "MYNETWORK"
$ nmcli connection modify "MYNETWORK" wifi.cloned-mac-address random
$ nmcli connection up "MYNETWORK" -> generates error that says "Error: Connection activation failed: Secrets were required but not provided"

Is there something I am missing or any other way I can do this MAC address change to allow both boards to work at the same time? The Raspberry Pi 4B assings by default different MAC addresses for wlan0. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support, Feature Request

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
To generate a new MAC address with `cloned SD cards` please run the below command `once` on each new device:

`sudo /etc/runonce.d/10-set-mac-addresses`

This script (as the pathname suggests) typically runs only once on first boot up and sets the wlan mac address relative (+1) to the fused eth0 mac address. The wlan mac address is written to the filesystem ( /lib/firmware/wlan/wlan_mac.bin).

To `swap the SD cards` around between different devices, please run the above command on each boot-up and thus overwrite the existing file containing the wlan mac address. Thanks!
