### ISSUE TITLE
colab retrained mobilenet_v2 model won't run on raspberry pi - requires runtime version (14)

### ISSUE THREAD

**Issue by johncblacker** [google-coral/edgetpu#561]
I used google colab tutorial for retraining a mobilenet v2 model (flowers) but used my own image datasets (2 categories).  I then downloaded the model: mobilenet_v2_1.0_224_quant_edgetpu.tflite to my raspberry pi along with the "critters_labels.txt" file.  As a test, I first verified that the "classify_image.py" script would run (in coral.pycoral/examples/classify_image.py) using the "mobilenet_v2_2.1.0_224_inat_bird_quant_edgetpu.tflite" model and the "inat_bird_labels.txt" labels file feeding it the bird.bmp image and it ran fine.
Next, I downloaded my model file and labels file into the coral.pycoral/test_data dir (where the other models and labels files are kept), changed the command line parameters to reflect the use of my model built on colab and it fails with the following output:
______________________________________________________________________________________________________________________
(coral) pi@raspberrypi:~/ml-projects/coral/pycoral $ python3 examples/classify_image.py  --model test_data/mobilenet_v2_1.0_224_quant_edgetpu.tflite  --labels test_data/critter_labels.txt  --input test_data/bird.tmp
Traceback (most recent call last):
  File "examples/classify_image.py", line 121, in <module>
    main()
  File "examples/classify_image.py", line 72, in main
    interpreter.allocate_tensors()
  File "/home/pi/.virtualenvs/coral/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 408, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Failed to prepare for TPU. Failed precondition: Package requires runtime version (14), which is newer than this runtime version (13).Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.
---------------------------------------------------------------------------------------------------------------------------
My "coral" environment has:
pycoral 2.0.0
tensorflow 1.13.1
tflite-runtime 2.5.0.post1

I see from an strace that the interpreter.py is coming from the site-packages in my "coral" environment.  
I also traced the working execution but I don't know what to look for in the trace output files to see where the error is being produced and I need help.

**Comment by hjonnala** [comment]
@johncblacker please verify the runtime version using the command below and upgrade to` edgetpu runtime 14` (libedgetpu1-std or libedgetpu1-max)  using instructions at:  https://coral.ai/software/#debian-packages.  Thanks!

```
mog@random:~$ python3 -c 'from pycoral.utils.edgetpu import get_runtime_version; print(get_runtime_version())'
BuildLabel(COMPILER=6.3.0 20170516,DATE=redacted,TIME=redacted), RuntimeVersion(14)
```

**Comment by johncblacker** [comment]
Thank you.  The command verified version 13 was installed.  Followed the directions and installed v14 libedgetpu1-std and successfully executed my model!
