### ISSUE TITLE
get_runtime_version() fails

### ISSUE THREAD

**Issue by johncblacker** [google-coral/edgetpu#563]
Trying to get the runtime version of the libedgetpu module and get failure:
ModuleNotFoundError: No module named 'pycoral.pybind'
Followed instructions from issue: 561

**Comment by johncblacker** [comment]
Just a FYI, this error did not occur when I had runtime version 13 installed, but after I installed runtime version 14, it fails with the above error!

**Comment by hjonnala** [comment]
You probably trying pycoral as base directory.. Please try from any other directory.

```
hemanth@hemanth-glaptop:~/coral/pycoral$ python3 -c 'from pycoral.utils.edgetpu import get_runtime_version; print(get_runtime_version())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hemanth/coral/pycoral/pycoral/utils/edgetpu.py", line 24, in <module>
    from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
ModuleNotFoundError: No module named 'pycoral.pybind'
hemanth@hemanth-glaptop:~/coral/pycoral$ cd ..
hemanth@hemanth-glaptop:~/coral$ python3 -c 'from pycoral.utils.edgetpu import get_runtime_version; print(get_runtime_version())'
BuildLabel(COMPILER=6.3.0 20170516,DATE=redacted,TIME=redacted), RuntimeVersion(14)
```

**Comment by johncblacker** [comment]
Yes, that was the problem.  No problem, now that I know that it won't work if I'm in the pycoral directory when I issue command...

**Comment by johncblacker** [comment]
As suggested got out of the pycoral directory...command worked.
