### ISSUE TITLE
Developing a motherboard for Coral System-on-Chip (SOM)

### ISSUE THREAD

**Issue by DevelopingElectronics** [google-coral/edgetpu#564]
### Description

Hello everyone,

I want to develop my own motherboard for Coral SOM for an audio application. I want to route my own PCB for an specific purpose. I will like to know where I can find more information about this issue, in order to help me in this task of creating a motherboard for the SOM (apart from the schematics files you can download from Coral's Guide). Any example would be welcome too.

Thanks a lot!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Mendel Linux

### Coral Device

Dev Board, SoM

### Programming Language

Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
@DevelopingElectronics  can you try reaching out to the NXP community: https://community.nxp.com/

Fell free to refer to the coral dev board baseboard design at:
https://github.com/google-coral/electricals/tree/master/dev_board
https://github.com/google-coral/mechanicals/tree/master/dev_board

**Comment by hjonnala** [comment]
For others, please check this link for reference or contributions: https://community.nxp.com/t5/i-MX-Processors/iMX-8M-SoC-Developing-a-motherboard-for-Google-s-Coral-System-on/m-p/1435274.

Thanks!
