### ISSUE TITLE
Programming the SoC in Coral System-on-Chip (SOM)

### ISSUE THREAD

**Issue by DevelopingElectronics** [google-coral/edgetpu#565]
### Description

Hello everyone, 

I would like to know how to programme the microprocessors (the two ARM Cortex) inside the SoC in Coral SOM. I want to use the System-on-Chip with my own motherboard and I need to know if it is necessary to add a new system (like Rapsberry) or microprocessor (another ARM to control the SOM) or if I can just use the two ARM Cortex that are included in the SoC, and how to do that.

Thank you.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Mendel Linux

### Coral Device

Dev Board, SoM

### Other Devices

Raspberry Pi 3

### Programming Language

Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
For others, please check this link for reference or contributions: https://community.nxp.com/t5/i-MX-Processors/Programming-the-iMX-8M-SoC-in-Google-s-Coral-System-on-Chip-SOM/m-p/1435277. 

Thanks!
