### ISSUE TITLE
semantic_segmetation.py misspelling

### ISSUE THREAD

**Issue by zewelor** [google-coral/edgetpu#57]
Hi

I think there is misspelling in https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py filename, missing "n". Also comment inside file states different file name ( comment seems to use proper filename ). https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py#L18

**Comment by Namburger** [comment]
@zewelor ahh, you are correct, thanks for pointing that out, will get this fixed along with next release.
