### ISSUE TITLE
Use of Coral Dev Board as USB Accelerator (also for "Multiple TPU Scenarios")

### ISSUE THREAD

**Issue by vleonn** [google-coral/edgetpu#570]
### Description

Hello, I have two (associated) questions regarding the Coral Dev Board.

1) Is it possible to use it like USB accelerator, i.e., attach it to a host PC (with MDT, TFlite runtime, libedgetpu.so.1, etc.), bypass the ARM and inference directly on the TPU ASIC?

2) I have seen that it is possible to attach "USB" and "PCI" TPUs on a host PC to run multiple models / pipeline a model with multiple TPUs. The question is if you can do it with multiple Dev Boards (recognize them as "USB" - they are already recognized by MDT).

I have not seen something official on the Coral guides and documentations (that probably answers the questions), but, in any case, I would like to confirm it.
 
Thank you in advance. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Operating System

Ubuntu

### Coral Device

Dev Board, USB Accelerator, Dev Board Mini

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @vleonn 

> 1. Is it possible to use it like USB accelerator, i.e., attach it to a host PC (with MDT, TFlite runtime, libedgetpu.so.1, etc.), bypass the ARM and inference directly on the TPU ASIC?

It is not possible to use dev board like USB accelerator.


> 2\. I have seen that it is possible to attach "USB" and "PCI" TPUs on a host PC to run multiple models / pipeline a model with multiple TPUs. The question is if you can do it with multiple Dev Boards (recognize them as "USB" - they are already recognized by MDT).

It is not possible.

Thanks!
