### ISSUE TITLE
Coral dev board with camera IP

### ISSUE THREAD

**Issue by constantinfite** [google-coral/edgetpu#575]
### Description

I am working with a Coral development board. Am I wondering with the Coral board can support IP camera with rstp protocol ? I only saw that it can support Coral Camera or a USB camera. Thanks

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Feature Request

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Can you please try the gstreamer example from exampels-camera repo with rtsp source. https://github.com/google-coral/examples-camera/blob/master/gstreamer/gstreamer.py#L221. Thanks!

**Comment by constantinfite** [comment]
Ok I will try thanks,
Do you if nvcompositor works on coral dev board ?

**Comment by hjonnala** [comment]
> Do you if nvcompositor works on coral dev board ?

nvcompositor does not work with coral dev board. I think it only works with NVIDIA products.

```
mendel@neat-yarn:~/examples-camera/gstreamer$ gst-inspect-1.0 nvcompositor
No such element or plugin 'nvcompositor'
```

**Comment by constantinfite** [comment]
@hjonnala Do you know if there is a replacement of nvcompositor working on google coral ?
