### ISSUE TITLE
Recurrent Convolution Model : how to get past the tensor dimension limit ?

### ISSUE THREAD

**Issue by mathieugalle** [google-coral/edgetpu#576]
### Description

Hi,

With my company, Vitirover, we have a mower robot navigating on a vineyard. We trained some convolutional models for obstacle detection, and it is working great. The input is an image, and the output are classes of obstacles (or no obstacles)
However, our robot sometimes hits obstacles that are invisible now (not in the immediate detection field), but were visible a few seconds ago. So we would like to use a recurrent convolutional model to do this

My model input shape would be [ Sequence of images, Height, Width, Channels  ], which needs 4 dimensions.
But the [documentation](https://coral.ai/docs/edgetpu/models-intro/#model-requirements) says _Tensors are either 1-, 2-, or 3-dimensional_. 

So my questions are : 

- Is it possible that on the future, more than 3 dimensions could be allowed ? Is this a software limitation or a hardware one ?

 - Does the new **append_recurrent_links** utility help here by allowing us to input only one image at a time (only three dimensions) and saving the "state" part internally ? Even if theoretically the model itself would still be 4-dimensionnal ?
 
 - Does the dimension limitation apply only to inputs, or any tensor inside the edge tpu ?

 - Is there any known clever way to get around the problem ? For example, we could use three different model inputs for [red, green, blue], using the "saved" dimension for the "Sequence" part ?

 - Could it work by splitting our model into two model : the first one would take one image and outputs a flattened 1-D vector. The second one takes a sequence of these 1D vector, and outputs what we want ? Is this case, there would be a useless round-trip to and from the CPU. 

Thanks a lot !

 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support, Feature Request

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

C++, Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @mathieugalle 
> * Is it possible that on the future, more than 3 dimensions could be allowed ? Is this a software limitation or a hardware one ?

No, we aren't planning to support higher dimensions in future. For now this is a software limitation ( we may not disclose complete info about limitation) 



> * Does the new **append_recurrent_links** utility help here by allowing us to input only one image at a time (only three dimensions) and saving the "state" part internally ? Even if theoretically the model itself would still be 4-dimensionnal ?

Yes, the model would be 4d if input is 3d. This can be applicable for 2d inputs, where model can be 3d.  

> * Does the dimension limitation apply only to inputs, or any tensor inside the edge tpu ?

 it applies to every tensor executable on edgetpu
 
 

> * Is there any known clever way to get around the problem ? For example, we could use three different model inputs for [red, green, blue], using the "saved" dimension for the "Sequence" part ?

Not exactly sure about work around can you try with gray scale images first. 



> Could it work by splitting our model into two model : the first one would take one image and outputs a flattened 1-D vector. The second one takes a sequence of these 1D vector, and outputs what we want ? Is this case, there would be a useless round-trip to and from the CPU.

I am not confident about how this model would work. Training a model like this could also be challenging.

Thanks!
