### ISSUE TITLE
Modify trip_point_*_temp permanently

### ISSUE THREAD

**Issue by eungiHong** [google-coral/edgetpu#578]
### Description

Hello,

I am using Coral Dev Board.

I succeeded to change trip_point_*_temp in -
/sys/class/thermal/thermal_zone0
or
/sys/devices/virtual/thermal/thermal_zone0

However, after reboot, the modified trip points are set to default.

Is there any way to change them permanently?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Relevant Log Output

```shell
cat /sys/class/thermal/thermal_zone0/trip_point_*_temp

75000
80000
85000
90000
65000
```
</details>

**Comment by hjonnala** [comment]
Hello @eungiHong please refer to this link and let me know if its solves the issue: https://forum.manjaro.org/t/persisting-change-to-sys-class-thermal-thermal-zone-mode/53556

Thanks!

**Comment by eungiHong** [comment]
Hello @hjonnala your link solved the problem perfectly!
Thank you so much!
