### ISSUE TITLE
Using Coral Dev Board as accelerator

### ISSUE THREAD

**Issue by yieniggu** [google-coral/edgetpu#58]
Hello, is there a way to use the dev board as accelerator. I'm trying to run a tpu model on my laptop but using the tpu module of the dev board.

I've configured it properly and ran some models on it. But when I try to use it from my laptop it outputs:

`Error: No tpu devices detected!`

Thanks in advance for any help!

**Comment by Namburger** [comment]
@yieniggu 
Unfortunately, you'll have to move your code to the devboard and execute it there.
Or you can use a USB Accelerator or PCIe module to use the EdgeTPU on your laptop.
Well, there is also an option of creating a server on the dev board and send data there for inference, but then you'll be hitting network bottle necks

**Comment by yieniggu** [comment]
Thanks for your reply! Do you have some links on how to create a server?

**Comment by Namburger** [comment]
@yieniggu Glad you asked :)
It's actually a personal project of mine:
https://github.com/namburger/restor

**Comment by Namburger** [comment]
There's also this one:
https://github.com/snowzach/doods
