### ISSUE TITLE
Coral-dev-Board support for OS

### ISSUE THREAD

**Issue by vaishnavils97** [google-coral/edgetpu#580]
Hi, Please give a list of Operating System or Linux Distribution For the Coral Development Board

**Comment by hjonnala** [comment]
Hi, we only support [Mendel Linux](https://coral.googlesource.com/docs/+/refs/heads/master/ReadMe.md) for the Coral Dev Board.

**Comment by synaption** [comment]
belanaOS and yocto are also publicly available.

**Comment by GavinBeattie** [comment]
BalenaOS seems good to me but there is an issue after v2.48.0+rev5 on the 4GB dev board stopping SD install. @synaption were you able to get Ubuntu up and running on the Coral Dev Board?
