### ISSUE TITLE
Any method to get serial number by pycoral or linux command?

### ISSUE THREAD

**Issue by ykhorzon** [google-coral/edgetpu#582]
### Description

How can I get  a unique serial number by pycoral or linux command?
https://coral.ai/legal/pcie-m2/#regulatory-information-eu

I found that only pycoral can list_edge_tpus() but it does not have serial number
```
[{'type': 'pci', 'path': '/dev/apex_2'}, {'type': 'pci', 'path': '/dev/apex_0'}, {'type': 'pci', 'path': '/dev/apex_3'}, {'type': 'pci', 'path': '/dev/apex_1'}]
```
Thanks

 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Operating System

Ubuntu

### Coral Device

Mini PCIe

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by david128kim** [comment]
I find a way to get "unique_id". But i' m not sure. ```cat /sys/class/apex/apex_0/unique_id```

**Comment by hjonnala** [comment]
Hello @ykhorzon we don't have any method to get the serial number by pycoral. The [solution](https://github.com/google-coral/edgetpu/issues/582#issuecomment-1110746055) provided by @david128kim is correct to get the serail number using linux coomand. 

One can find this info on dev board too by updating/installing gasket-dkms driver. Thanks!
