### ISSUE TITLE
Training a new segmentation model for the Coral

### ISSUE THREAD

**Issue by bsteiner-dandy** [google-coral/edgetpu#585]
Hi, do you have any resources on how to train a new segmentation model to run on the Coral? (something like the Colab training tutorials?) I see the pre-trained models here https://coral.ai/models/semantic-segmentation/#examples and inference code here https://github.com/google-coral/pycoral/blob/master/examples/semantic_segmentation.py but I am not sure how to train a new segmentation model in a way that can be converted to tensorflowlite and compiled for the edge tpu. Is there any guidance or resource you can give? Thanks!

**Comment by hjonnala** [comment]
@bsteiner-dandy Unfortunately, we don't have any scripts or support to train a segmentation model. Please check helpful threads at https://github.com/google-coral/edgetpu/issues/315 and https://discuss.tensorflow.org/t/suggestion-for-choosing-a-model/4057/11. Thanks!
