### ISSUE TITLE
Pycoral 1.0.1

### ISSUE THREAD

**Issue by Yin-Jiaqi** [google-coral/edgetpu#590]
### Description

I'm trying to install pycoral 1.0.1.

But I found all possible version is 2.0.0. Is there methods to install 1.0.1?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
@jiaqiyin1995 Please try to install using wheel files at: https://github.com/google-coral/pycoral/releases. Thanks!
