### ISSUE TITLE
dev board mini power through header requires button press

### ISSUE THREAD

**Issue by davidallenmann** [google-coral/edgetpu#595]
### Description

We are powering a Dev Board Mini through the power header.
It appears that the firmware currently requires a power button press to turn on the Dev Board Mini.

The desired behavior is that if power comes through the header the board should automatically turn on (like it does if powered through the USB OTG connector).

We are operating in a location where it needs to power on automatically without human interaction.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Coral Device

Dev Board Mini

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @davidallenmann Unfortunately, this is an unsupported configuration.  Thanks!

**Comment by kckemper** [comment]
I'm sure the original poster moved on but a hack I've done to get around this is to short SW1 (the power button) to ground. I checked through the schematics and this is the best I could come up with. It doesn't require any software changes - linux doesn't see the press as anything as far as I can tell. Specifically I short the test pad just behind SW1 to the ground-plane nearby.

**Comment by ya-smolin** [comment]
> I'm sure the original poster moved on but a hack I've done to get around this is to short SW1 (the power button) to ground. I checked through the schematics and this is the best I could come up with. It doesn't require any software changes - linux doesn't see the press as anything as far as I can tell. Specifically I short the test pad just behind SW1 to the ground-plane nearby.

I have the same issue, looking on the schematics didn't help me)
Can you show me on the picture where is the "test pad just behind SW1" and the "ground-plane nearby"?
![image](https://github.com/google-coral/edgetpu/assets/5637631/c845efec-5e5b-4fda-99d9-691c6e9d1f7e)

**Comment by kckemper** [comment]
The little pad just above the power button (SW1). You'll have to scrape the solder mask away and bridge that little pad to the ground-plane around it or tack a wire from it to any one of the USB housing pads. The red arrow is the pad and the left-most green arrow is where I'd tack a wire down to the USB port and the right-most green arrow is the ground plane (that whole region of copper under the solder mask).

![image](https://github.com/google-coral/edgetpu/assets/4730618/2743d43f-95a1-468f-83e9-5c04994d474e)

**Comment by ya-smolin** [comment]
@kckemper Thanks a lot for your great answer! This is what I need. Hopefully I will not brick my coral. Will write about results)
