### ISSUE TITLE
model with pure keras layer convert to int8 tflite well, but kernel crash when interpreter.allocate_tensors() and edgetpu_compiler compile the tflite file failed, without any hint,just failed

### ISSUE THREAD

**Issue by fjzhangcr** [google-coral/edgetpu#596]
### Description

use lots of tricks learned from here to make a int8 tflite file successfully, but edgetpu_compiler compile failed.
by the way the converter.covert() line, runs about 40 minutes, is that too long?
i am pretty sure there are no dynamic-sized tensor, no dimention more than 1 in the innermost 3 dimention~~~
anything wrong?~~~

the model initialized and set static shape:
```
input_layer = tf.keras.layers.Input([NN_INPUT_H, NN_INPUT_W, 3])
model_bb = tf.keras.Model(input_layer,
                                YOLO(input_layer, CFG.NUM_CLASS, CFG.MODEL, CFG.IS_TINY))
utils.load_weights(model_bb, weights_file=CFG.WEIGHTS, model_name=CFG.MODEL, is_tiny=CFG.IS_TINY)
model_bb.input.set_shape((1,) + model_bb.input.shape[1:])
```

prepare the converter using some tricks learned from here:
```
converter = tf.lite.TFLiteConverter.from_keras_model(model_bb)
SWITCH_TO = "SWITCH_TO_INT8"
if SWITCH_TO=="SWITCH_TO_INT8":
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    def representative_dataset():
        for _ in range(300):
            data = np.random.rand(1, 512, 512, 3)
            yield [data.astype(np.float32)]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_types = [tf.int8]
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
        # tf.lite.OpsSet.SELECT_TF_OPS,
        ]
    # converter.experimental_new_converter = True
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
print('start  converter.convert() !')
t1=time.time()
tflite_model = converter.convert() # runs about 46 minutes!! TOO MUCH TIME! is it common?
t2=time.time()
print((t2-t1)/60)
with open(tflite_model_filename, 'wb') as f:
    f.write(tflite_model)
```

By disable and enable the lien [# converter.experimental_new_converter = True],get two tflite file:
**yolov4_NO_experimental_new_converter.tflite
yolov4_True_experimental_new_converter.tflite**
download from here
**[two lite file](https://drive.google.com/drive/folders/1iKYYj4Mjp0T4JxaS9zSWY5oa2pEtm4PJ?usp=sharing)**
time consuming is 40 MINUTES~~~ 

then  switch to ubuntu, edgetpu_compiler it~~~ then got error without any hint~~~~:
```
indeed@indeed-virtual-machine:~/Desktop/tflite$ edgetpu_compiler failed/yolov4_NO_experimental_new_converter.tflite  -s -a
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
^[[ACompilation child process completed within timeout period.
Compilation failed! 
indeed@indeed-virtual-machine:~/Desktop/tflite$ edgetpu_compiler failed/yolov4_True_experimental_new_converter.tflite  -s -a
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
Compilation child process completed within timeout period.
Compilation failed! 
```

please give me some hint or at least some information~~~~helpless feeling~~~
Thank you

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Windows 10, Ubuntu

### Coral Device

Dev Board

### Programming Language

Python 3.7

### Relevant Log Output

```shell
the model initialized and set static shape:
input_layer = tf.keras.layers.Input([NN_INPUT_H, NN_INPUT_W, 3])
model_bb = tf.keras.Model(input_layer,
                                YOLO(input_layer, CFG.NUM_CLASS, CFG.MODEL, CFG.IS_TINY))
utils.load_weights(model_bb, weights_file=CFG.WEIGHTS, model_name=CFG.MODEL, is_tiny=CFG.IS_TINY)
model_bb.input.set_shape((1,) + model_bb.input.shape[1:])

![image](https://user-images.githubusercontent.com/102020341/170772880-5e67c2a5-224c-4906-8ee9-b5dd04349dc2.png)


prepare the converter using some tricks learned from here:
converter = tf.lite.TFLiteConverter.from_keras_model(model_bb)
SWITCH_TO = "SWITCH_TO_INT8"
if SWITCH_TO=="SWITCH_TO_INT8":
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    def representative_dataset():
        for _ in range(300):
            data = np.random.rand(1, 512, 512, 3)
            yield [data.astype(np.float32)]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_types = [tf.int8]
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
        # tf.lite.OpsSet.SELECT_TF_OPS,
        ]
    # converter.experimental_new_converter = True
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
print('start  converter.convert() !')
t1=time.time()
tflite_model = converter.convert() # runs about 46 minutes!! TOO MUCH TIME! is it common?
t2=time.time()
print((t2-t1)/60)

By disable and enable the lien [# converter.experimental_new_converter = True],get two tflite file:
yolov4_NO_experimental_new_converter.tflite
yolov4_True_experimental_new_converter.tflite

then  switch to ubuntu, edgetpu_compiler it~~~ then got error without any hint~~~~:
indeed@indeed-virtual-machine:~/Desktop/tflite$ edgetpu_compiler failed/yolov4_NO_experimental_new_converter.tflite  -s -a
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
^[[ACompilation child process completed within timeout period.
Compilation failed! 
indeed@indeed-virtual-machine:~/Desktop/tflite$ edgetpu_compiler failed/yolov4_True_experimental_new_converter.tflite  -s -a
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
Compilation child process completed within timeout period.
Compilation failed! 

please give me some hint or at least some information~~~~helpless feeling~~~
Thank you
```
</details>

**Comment by fjzhangcr** [comment]
i update my issue and take screenshots about the model architechture, and make a colab to reproduce the kernel crash when interpreter.allocate_tensors()~~

**Comment by hjonnala** [comment]
This model won't be able to compile to edgeTPU as It has lot of float operations in between and has  leaky Relu..

![image](https://user-images.githubusercontent.com/86132058/170771658-36f0ead4-2d72-43a2-be0f-df70e620c91f.png)

**Comment by fjzhangcr** [comment]
let me update  again~~ i just updated a colab, but the content i edited all gone~~~
https://colab.research.google.com/drive/1lZRxp8DCLKFQ4wSWPTTzgOQV6Q1xhDzo?usp=sharing

**Comment by fjzhangcr** [comment]
do you mean all layer are regular and shapes are ok.
here is my layers shape and layers type:
```
all_output_shape=list(set([str(_.output_shape) for _ in model_bb.layers]))
all_layer_type=list(set([str(type(_)) for _ in model_bb.layers]))
```


![image](https://user-images.githubusercontent.com/102020341/170773362-54813dee-6203-4eee-955b-81bd76aed1ca.png)
![image](https://user-images.githubusercontent.com/102020341/170773387-241423bf-bbc5-4c39-9d51-851b534250c6.png)

**Comment by hjonnala** [comment]
Regarding kernel crash with uncompiled tflite model please check with [tflite support team](https://github.com/tensorflow/tflite-support). And please check the model in https://netron.app/ it has lot of [exp](https://www.tensorflow.org/api_docs/python/tf/math/exp), [log](https://www.tensorflow.org/api_docs/python/tf/math/log) and Leaky Relu operations which are not supported with EdgeTPU.

Btw, please make sure to run sample [inference test](https://github.com/hjonnala/snippets/blob/main/coral_inference.py) on uncomplied tflite model before compiling the model with edgeptu compiler. Thanks!

**Comment by fjzhangcr** [comment]
my issue is a big and complex problem including:
1, unsupport ops such as exp log and mish activation (unsolved)
2, matrix dimention greater than 1 outside the innermost 3 dims ( re-coding fixes my problem)
3, unsupport leakyReLU activation function~~(Replacing with PReLU fixes my problem)
4, other problem about edgetpu_compiler ( will be solved sooner or later~~ :) )
This issue should be closed. i will post issues seperately, thank you~~~
