### ISSUE TITLE
Where can I buy "M.2 Accelerator with Dual Edge TPU"?

### ISSUE THREAD

**Issue by vukitoso** [google-coral/edgetpu#599]
### Description

Hello.
I can not find "M.2 Accelerator with Dual Edge TPU" for sale anywhere on the Internet. Please tell me where can I buy?
Thank you.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Currently the product is out of stock. Please check the [product available countries](https://coral.ai/products/m2-accelerator-dual-edgetpu#tech-specs) and place your pre order with any one of the retailers listed on the [Coral website](https://coral.ai/products/m2-accelerator-dual-edgetpu), such as Mouser, Pi3g, OKdo, etc. Thanks!

**Comment by mjemv** [comment]
On which board can this card be used, how to use it with raspberry pi, please advice

**Comment by hjonnala** [comment]
please check the host requirements at: https://coral.ai/docs/m2/get-started/#requirements. It doesn't work with RPi. Please try the [USB accelerator](https://coral.ai/docs/accelerator/get-started/) with RPi.

**Comment by vukitoso** [comment]
@mjemv
> On which board can this card be used, how to use it with raspberry pi, please advice

[Alftel 12x PCI Express M.2 Carrier Board](https://pipci.jeffgeerling.com/cards_m2/alftel-12x-pcie-m2-carrier-board.html)
[Raspberry Pi PCIe Devices](https://pipci.jeffgeerling.com/)
12 PCI Express M.2 Slots on a Raspberry Pi!? - https://www.youtube.com/watch?v=Ozwyh_Pfe6g
I built the world's TINIEST NVMe SSD RAID array! - https://www.youtube.com/watch?v=AoNxDe1a-X8

also ROCK 3A supports installation of Coral edge tpu module - https://wiki.radxa.com/Rock3/dev/install-coral-pcie-driver-and_edge_tpu-runtime-packages
