### ISSUE TITLE
coral::GetInputFromImage is missing in c++ examples

### ISSUE THREAD

**Issue by powderluv** [google-coral/edgetpu#6]
Looks like  edgetpu/cpp/basic/inference_utils.cc | .h were not migrated over to the new repo so examples such as classify_image (c++) fail.  Is there a new home for these utils ? 

classify_image.cc:27: undefined reference to `coral::GetInputFromImage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::array<int, 3ul> const&)'

**Comment by Namburger** [comment]
@powderluv did you build the example cpp code correctly using our provided make file?

`GetInputFromImage` is defined in test_utils.h and implemented in test_utils.cc:
https://github.com/google-coral/edgetpu/blob/master/src/cpp/test_utils.cc#L230

Which was included in classify_image.cc:
https://github.com/google-coral/edgetpu/blob/master/src/cpp/examples/classify_image.cc#L7

**Comment by powderluv** [comment]
Good point. Don't know how I missed test_utils. Will rework my patch with it. 

Thanks

**Comment by powderluv** [comment]
Updated the CMakelists.txt PR https://github.com/google-coral/edgetpu/pull/7

**Comment by Namburger** [comment]
@powderluv Just wanted to say thankyou for your CMakeLists.txt file, I based [this one](https://github.com/Namburger/edgetpu-minimal-example) on it.
Currently we just have a lots of issue processing PRs due to the internal process of how this repo works. I can't provides much details, but we are working diligently to  make this better.

**Comment by powderluv** [comment]
Great to hear it was useful. We integrate edgetpu as part of our larger build system which is cmake based and can't use bazel since there are so many dependent projects that are cmake based. 

The minimal example looks great. Hopefully your example can be part of the main repo.

**Comment by Namburger** [comment]
@powderluv it was actually based on our minimal example!
I also just published this: https://github.com/Namburger/edgetpu-detection-camera
