### ISSUE TITLE
most ops mapto edgetpu, except a few supported ops(concatenation conv2d pad) not , shows More than one subgraph is not supported

### ISSUE THREAD

**Issue by fjzhangcr** [google-coral/edgetpu#601]
### Description

i am compiling yolov4 model to edgetpu.
i have replace leakyrelu with prelu successfully, replace all mish activation with prelu too.
although now most of ops map to edgetpu, the procedure is weird.
my python code give me a tflite file : yolov4_bb.tflite
then i switch to ubuntu to edgetpu_compiler it~~

At first, i type in -s -a flag:
```
indeed@indeed-virtual-machine:~/Desktop/tflite$ edgetpu_compiler -s -a yolov4_bb.tflite 
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
```
then i found some issue about the -d flag(searching something i dont understand but the problem solved), then i tyep in -s -a -d flag:
```
indeed@indeed-virtual-machine:~/Desktop/tflite$ edgetpu_compiler -s -a -d  yolov4_bb.tflite 
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 1
Try to compile segment with 266 ops
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 265 ops
Intermediate tensors: StatefulPartitionedCall:2,StatefulPartitionedCall:1,StatefulPartitionedCall:01
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
...............
..............
Try to compile segment with 214 ops
Intermediate tensors: model_2/UpSample2/resize/ResizeNearestNeighbor,model_2/batch_normalization_300/FusedBatchNormV3;model_2/conv2d_311/Conv2D;model_2/conv2d_306/Conv2D1,model_2/p_re_lu_228/add;model_2/p_re_lu_228/Relu;model_2/p_re_lu_228/Neg_1;model_2/p_re_lu_228/Relu_1;model_2/p_re_lu_228/mul,model_2/p_re_lu_221/add;model_2/p_re_lu_221/Relu;model_2/p_re_lu_221/Neg_1;model_2/p_re_lu_221/Relu_1;model_2/p_re_lu_221/mul
Started a compilation timeout timer of 180 seconds.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 213 ops
Intermediate tensors: model_2/p_re_lu_181/add;model_2/p_re_lu_181/Relu;model_2/p_re_lu_181/Neg_1;model_2/p_re_lu_181/Relu_1;model_2/p_re_lu_181/mul,model_2/p_re_lu_221/add;model_2/p_re_lu_221/Relu;model_2/p_re_lu_221/Neg_1;model_2/p_re_lu_221/Relu_1;model_2/p_re_lu_221/mul,model_2/p_re_lu_228/add;model_2/p_re_lu_228/Relu;model_2/p_re_lu_228/Neg_1;model_2/p_re_lu_228/Relu_1;model_2/p_re_lu_228/mul,model_2/UpSample2/resize/ResizeNearestNeighbor
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 30105 ms.

Input model: yolov4_bb.tflite
Input size: 62.32MiB
Output model: yolov4_bb_edgetpu.tflite
Output size: 64.43MiB
On-chip memory used for caching model parameters: 4.12MiB
On-chip memory remaining for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 57.40MiB
Number of Edge TPU subgraphs: 7
Total number of operations: 266
Operation log: yolov4_bb_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 259
Number of operations that will run on CPU: 7

Operator                       Count      Status

CONCATENATION                  3          More than one subgraph is not supported
CONCATENATION                  7          Mapped to Edge TPU
PAD                            6          Mapped to Edge TPU
PAD                            1          More than one subgraph is not supported
MAX_POOL_2D                    3          Mapped to Edge TPU
PRELU                          107        Mapped to Edge TPU
ADD                            23         Mapped to Edge TPU
CONV_2D                        3          More than one subgraph is not supported
CONV_2D                        107        Mapped to Edge TPU
QUANTIZE                       4          Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 
```
i netron the yolov4_bb_edgetpu.tflite file generated by edgetpu_compiler. 
i found the compiler segment the graph at the edge of a conv2d layer and zeropadding layer with input shape 64*64*256.
![image](https://user-images.githubusercontent.com/102020341/171005617-71da6c7f-9a57-471f-bbea-f8fcefc815eb.png)
i am pretty sure conv2d and zeropadding layer both are supported at this input shape
That is what make it wired~~~

my question:
1, why compile failed with -s -a flag, but succeed with -s -a -d flag.  what problem did the -d flag solve?
2, why the conv2d layer with not too big size is not compiled?~~~

the python code convert.conver() generate [yolov4_bb.tflite]  and  the edgetpu_compiler generate [yolov4_bb_edgetpu.tflite] and the logs can be found here:
https://drive.google.com/drive/folders/1gwlu00vOaRQiuN8M5MHPx0xNazpEtHiz?usp=sharing

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Windows 10, Ubuntu

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @fjzhangcr 

 Please check this page for compiler flags and their usage: https://coral.ai/docs/edgetpu/compiler/#usage

-d search_delegate tries to compile the model with intermediate tensors. In your case the intermediate tensors (you can get the input names with help of netron visualizer) are used are: 

`model_2/p_re_lu_181/add;model_2/p_re_lu_181/Relu;model_2/p_re_lu_181/Neg_1;model_2/p_re_lu_181/Relu_1;model_2/p_re_lu_181/mul,model_2/p_re_lu_221/add;model_2/p_re_lu_221/Relu;model_2/p_re_lu_221/Neg_1;model_2/p_re_lu_221/Relu_1;model_2/p_re_lu_221/mul,model_2/p_re_lu_228/add;model_2/p_re_lu_228/Relu;model_2/p_re_lu_228/Neg_1;model_2/p_re_lu_228/Relu_1;model_2/p_re_lu_228/mul,model_2/UpSample2/resize/ResizeNearestNeighbor`.

Due to the above intermediate tensors conv2d and other layers are not mapped to TPU.

You can compile the your model with the below options as well.
1. edgetpu_compiler -s -a -i "model_2/p_re_lu_181/add;model_2/p_re_lu_181/Relu;model_2/p_re_lu_181/Neg_1;model_2/p_re_lu_181/Relu_1;model_2/p_re_lu_181/mul" yolov4_bb.tflite 

This would compile the model mapping all operations to TPU except 1 conv2d and 1 pad layer.

2. edgetpu_compiler -s -n 2  yolov4_bb.tflite  (This option would map all operations to TPU. But you would need more TPUs to run the model. Please check this link for details on model pipe lining: https://coral.ai/docs/edgetpu/pipeline/#overview). 

Thanks!

**Comment by fjzhangcr** [comment]
what do you mean by intermediate tensors ? there are 4 intermediate tensors,~~~ am i right?
my question:
1, why do you attatch only the first intermediate tensors( number 181) to the -i flag, withou other 3 intermediate tensors?
2, what is so special for  the tensors? i have check my code, they are all short-cuts~~ but i have many other short cuts, why only these tensors are intermediate tensors. was something wrong with my coding?

intermediate tensors Quote as below :

```
`model_2/p_re_lu_181/add;model_2/p_re_lu_181/Relu;model_2/p_re_lu_181/Neg_1;model_2/p_re_lu_181/Relu_1;model_2/p_re_lu_181/mul,

model_2/p_re_lu_221/add;model_2/p_re_lu_221/Relu;model_2/p_re_lu_221/Neg_1;model_2/p_re_lu_221/Relu_1;model_2/p_re_lu_221/mul,

model_2/p_re_lu_228/add;model_2/p_re_lu_228/Relu;model_2/p_re_lu_228/Neg_1;model_2/p_re_lu_228/Relu_1;model_2/p_re_lu_228/mul,

model_2/UpSample2/resize/ResizeNearestNeighbor`
```

 thank you

**Comment by fjzhangcr** [comment]
update:  excellent solution!~~~ just one conv2d and a pad layer runs on cpu~~~
but i still confused by your solution~~ 
1, why you only add the 181 intermediate tensor to the i flag, not the others
2, what is the cause? My guess is  because the 181 short-cut requires too much(more than 8Mb) cache?
looking forward for your explanation~~thank you
```

indeed@indeed-virtual-machine:~/Desktop/tflite/yolo_bb_all_prelu$ edgetpu_compiler -s -a -i "model_2/p_re_lu_181/add;model_2/p_re_lu_181/Relu;model_2/p_re_lu_181/Neg_1;model_2/p_re_lu_181/Relu_1;model_2/p_re_lu_181/mul" yolov4_bb.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 45490 ms.

Input model: yolov4_bb.tflite
Input size: 62.32MiB
Output model: yolov4_bb_edgetpu.tflite
Output size: 64.28MiB
On-chip memory used for caching model parameters: 4.12MiB
On-chip memory remaining for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 57.56MiB
Number of Edge TPU subgraphs: 2
Total number of operations: 266
Operation log: yolov4_bb_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 264
Number of operations that will run on CPU: 2

Operator                       Count      Status

QUANTIZE                       4          Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
CONV_2D                        109        Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
CONCATENATION                  10         Mapped to Edge TPU
PAD                            6          Mapped to Edge TPU
PAD                            1          More than one subgraph is not supported
PRELU                          107        Mapped to Edge TPU
ADD                            23         Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 
```

**Comment by fjzhangcr** [comment]
i have a further try with your help. i make another model, which attatch a decode network after the backbone network.
the backbone netword is what i post at first **[yolov4_bb.tflite]**,.
https://drive.google.com/drive/folders/1gwlu00vOaRQiuN8M5MHPx0xNazpEtHiz?usp=sharing
the new network attatched a decode network named **[yolov4_Decode_Collect_390.tflite]**.
https://drive.google.com/drive/folders/1qQDm7ZmBLFTkLqJvZ91rqof2FJzx2WJB?usp=sharing


the tail of yolov4_Decode_Collect_390.tflite is a decode network with reshape ops and concat ops and some exp ops, as the figure show:
![image](https://user-images.githubusercontent.com/102020341/171160428-fb17574b-e2fb-4d80-9d36-d6fa3080f8b3.png)

so i try -asd flag to found intermediate tensors as shown below: 
```
indeed@indeed-virtual-machine:~/Desktop/tflite/model_Decode_Collect_390$ edgetpu_compiler -s -a -d yolov4_Decode_Collect_390.tflite 
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 1
Try to compile segment with 500 ops
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 499 ops
Intermediate tensors: StatefulPartitionedCall:01,StatefulPartitionedCall:1
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 498 ops
Intermediate tensors: StatefulPartitionedCall:11,StatefulPartitionedCall:01
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 497 ops
Intermediate tensors: StatefulPartitionedCall:01,model_7/tf.concat_22/concat,model_7/tf.concat_23/concat
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 496 ops
Intermediate tensors: StatefulPartitionedCall:01,model_7/tf.reshape_41/Reshape,model_7/tf.reshape_42/Reshape,model_7/tf.concat_23/concat,model_7/tf.reshape_43/Reshape,model_7/tf.reshape_38/Reshape,model_7/tf.reshape_40/Reshape,model_7/tf.reshape_39/Reshape,model_7/tf.reshape_37/Reshape,model_7/tf.reshape_36/Reshape,model_7/tf.reshape_44/Reshape1
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 495 ops
Intermediate tensors: model_7/tf.reshape_37/Reshape,model_7/tf.reshape_42/Reshape,model_7/tf.reshape_44/Reshape1,model_7/tf.reshape_39/Reshape,model_7/tf.split_11/split;model_7/tf.split_11/split1;model_7/tf.split_11/split2;model_7/tf.split_11/split3;model_7/tf.split_11/split4;model_7/tf.split_11/split5;model_7/tf.split_11/split6;model_7/tf.split_11/split7;model_7/tf.split_11/split812,model_7/tf.reshape_36/Reshape,model_7/tf.reshape_41/Reshape,StatefulPartitionedCall:01,model_7/tf.reshape_38/Reshape,model_7/tf.reshape_40/Reshape,model_7/tf.concat_23/concat
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 494 ops
```
the log shows the  intermediate tensors are->
```
model_7/tf.reshape_37/Reshape,
model_7/tf.reshape_42/Reshape,
model_7/tf.reshape_44/Reshape1,
model_7/tf.reshape_39/Reshape,
model_7/tf.split_11/split;model_7/tf.split_11/split1;model_7/tf.split_11/split2;model_7/tf.split_11/split3;model_7/tf.split_11/split4;model_7/tf.split_11/split5;model_7/tf.split_11/split6;model_7/tf.split_11/split7;model_7/tf.split_11/split812,
model_7/tf.reshape_36/Reshape,
model_7/tf.reshape_41/Reshape,
StatefulPartitionedCall:01,
model_7/tf.reshape_38/Reshape,
model_7/tf.reshape_40/Reshape,
model_7/tf.concat_23/concat
```
may i use -i flag to compile the model?~~~ which connection should I use with the -i flag and why?~~~

btw, the intermediate tensorf with yolov4_bb.tflite
`model_2/p_re_lu_181/add;model_2/p_re_lu_181/Relu;model_2/p_re_lu_181/Neg_1;model_2/p_re_lu_181/Relu_1;model_2/p_re_lu_181/mul`
 is now named 
`model_7/p_re_lu_502/add;model_7/p_re_lu_502/Relu;model_7/p_re_lu_502/Neg_1;model_7/p_re_lu_502/Relu_1;model_7/p_re_lu_502/mul` in my new model of  yolov4_Decode_Collect_390.tflite, as  figure below shown
![image](https://user-images.githubusercontent.com/102020341/171161311-142e67bd-51d6-4510-ab46-4540340223a7.png)

the 181 or 502 intermediate tensor not yet shown in my new model compilation logs , it is no longer a problem or will shown sooner or later?

by the way, i have already try the edgetpu_compiler command with -i flag which no longer works i guess :
`edgetpu_compiler -s -a -i "model_7/p_re_lu_502/add;model_7/p_re_lu_502/Relu;model_7/p_re_lu_502/Neg_1;model_7/p_re_lu_502/Relu_1;model_7/p_re_lu_502/mul"  yolov4_Decode_Collect_390.tflite`
it faild without any information as below:
```
indeed@indeed-virtual-machine:~/Desktop/tflite/model_Decode_Collect_390$ edgetpu_compiler -s -a -i "model_7/p_re_lu_502/add;model_7/p_re_lu_502/Relu;model_7/p_re_lu_502/Neg_1;model_7/p_re_lu_502/Relu_1;model_7/p_re_lu_502/mul"  yolov4_Decode_Collect_390.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
Compilation child process completed within timeout period.
Compilation failed! 
```

**Comment by hjonnala** [comment]
> edgetpu_compiler -s -a -i "model_7/p_re_lu_502/add;model_7/p_re_lu_502/Relu;model_7/p_re_lu_502/Neg_1;model_7/p_re_lu_502/Relu_1;model_7/p_re_lu_502/mul" yolov4_Decode_Collect_390.tflite

I am able to compile the model with the above command. I am not sure why you are not able to compile. Please try this colab: https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb

![image](https://user-images.githubusercontent.com/86132058/171254223-724749b9-05c3-4381-a5f0-0d4370fd6837.png)



> 1, why you only add the 181 intermediate tensor to the i flag, not the others

I just chose this one as this is the first operation which is not able to map to TPU when you tried with -a -d flags.

**Comment by fjzhangcr** [comment]
i succeed in colab then i fail agian in ubuntu, but after i delete the tflite and re-copy it, it compiler successful in ubuntu...the reason i failed last time seems a mistery...
anyway,i remain confused..
the correct connection passed to -i flag is "model_7/p_re_lu_502...". 502 connection is  derived manually from the first compilation failure, in which 181 connection jump out.
according to your answer ,the connections in the logs which -d flag gave  are:
```
**model_7/tf.reshape_37/Reshape,
model_7/tf.reshape_42/Reshape,
model_7/tf.reshape_44/Reshape1,
model_7/tf.reshape_39/Reshape,
model_7/tf.split_11/split;model_7/tf.split_11/split1;model_7/tf.split_11/split2;model_7/tf.split_11/split3;model_7/tf.split_11/split4;model_7/tf.split_11/split5;model_7/tf.split_11/split6;model_7/tf.split_11/split7;model_7/tf.split_11/split812,
model_7/tf.reshape_36/Reshape,
model_7/tf.reshape_41/Reshape,
StatefulPartitionedCall:01,
model_7/tf.reshape_38/Reshape,
model_7/tf.reshape_40/Reshape,
model_7/tf.concat_23/concat**
```
thisi  logs which -d flags gave never includes 502 connection which is the corect content passed with -i flag~~

So~~~

> 1, why you only add the 181 intermediate tensor to the i flag, not the others
> 
> I just chose this one as this is the first operation which is not able to map to TPU when you tried with -a -d flags.

seems do not stand~~~ the first operaton which is not able to map to TPU is
**`model_7/tf.reshape_37/Reshape`**

can you explain exactly about your solution~~~~ thanks~~

**Comment by hjonnala** [comment]
For yolov4_bb.tflite, I have chosen the first operation from the logs which is not able to map to TPU when you tried with -a -d flags and the model is able to compile successfully. https://drive.google.com/file/d/1-eWHt9hLFka_NzZOPI5gxHHn0n4lhdK3/view?usp=sharing

For yolov4_Decode_Collect_390.tflite, I haven't taken it form logs. I just tried with the intermediate tensors from your comment: https://github.com/google-coral/edgetpu/issues/601#issuecomment-1142026565.

**Comment by fjzhangcr** [comment]
use all keras layer and use some clip_by_value ops to limit the dynamic range solve the accuracy problem~~~suggest this issue clossed~~thanks
