### ISSUE TITLE
Dev Board Mini periphery library permission error

### ISSUE THREAD

**Issue by Path-A** [google-coral/edgetpu#603]
### Description

I'm getting an ```Operation not permitted``` error trying to turn on an LED using the Coral Dev Board Mini. Here is a simple python script as an example:

```
from periphery import GPIO
import time

if __name__=="__main__":
    gpio0 = GPIO("/dev/gpiochip0", 0, "in")
    gpio0.write(True)
    gpio0.close()
```

I've attempted to modify my ```udev``` rules (seen in #457), but I can't seem to get it to work as either sudo or user.

This issue does not occur when using the Adafruit-blinka library and I am able to turn on an LED. Relevant log output is below,

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Programming Language

Python 3.7

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/periphery/gpio.py", line 683, in write
    fcntl.ioctl(self._line_fd, CdevGPIO._GPIOHANDLE_SET_LINE_VALUES_IOCTL, data)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mendel/pin_test.py", line 6, in <module>
    gpio0.write(True)
  File "/usr/local/lib/python3.7/dist-packages/periphery/gpio.py", line 685, in write
    raise GPIOError(e.errno, "Setting line value: " + e.strerror)
periphery.gpio.GPIOError: [Errno 1] Setting line value: Operation not permitted
```
</details>

**Comment by hjonnala** [comment]
Hi @Path-A can you try with the below GPIO sample code: https://coral.ai/docs/dev-board-mini/gpio/#gpio

```
from periphery import GPIO

led = GPIO("/dev/gpiochip0", 39, "out")  # pin 40
button = GPIO("/dev/gpiochip0", 13, "in")  # pin 36

try:
  while True:
    led.write(button.read())
finally:
  led.write(False)
  led.close()
  button.close()
```

**Comment by Path-A** [comment]
Thanks! That worked. I see that I made a simple mistake and used a write command to a pin set to "in".
