### ISSUE TITLE
intermediate tensor problem or large activation tensors problem

### ISSUE THREAD

**Issue by fjzhangcr** [google-coral/edgetpu#608]
### Description

i have a tflite model which have [1,16128,4] and [1,16128,80] output.
https://drive.google.com/file/d/1rQzAIlU2nCbAgn2Xd9br6pqj8kK0dAiD/view?usp=sharing

at the very beginning, i use the command of edgetpu_compiler with -a -s -d flag, got the following print:
```
indeed@indeed-virtual-machine:~/Desktop/tflite/yolo$ edgetpu_compiler -s -a -d  yolov4_realds200_clip5.tflite 
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 1
Try to compile segment with 534 ops
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 533 ops
Intermediate tensors: StatefulPartitionedCall:11,StatefulPartitionedCall:0
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 532 ops
Intermediate tensors: StatefulPartitionedCall:11,StatefulPartitionedCall:01
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 531 ops
Intermediate tensors: StatefulPartitionedCall:01,model/pred_cls_prob/concat,model/pred_objectness/concat
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 530 ops
Intermediate tensors: model/pred_cls_prob_0_low_res/Reshape,model/pred_cls_prob_1_med_res/Reshape,model/pred_cls_prob_1_hi_res/Reshape,model/pred_cls_prob_1_low_res/Reshape,model/pred_cls_prob_2_low_res/Reshape,model/pred_cls_prob_2_med_res/Reshape,model/pred_objectness/concat,model/pred_cls_prob_0_hi_res/Reshape,model/pred_cls_prob_2_hi_res/Reshape1,model/pred_cls_prob_0_med_res/Reshape,StatefulPartitionedCall:01
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 529 ops
Intermediate tensors: model/pred_cls_prob_0_med_res/Reshape,model/pred_cls_prob_1_hi_res/Reshape,model/pred_cls_prob_1_med_res/Reshape,model/pred_cls_prob_1_low_res/Reshape,StatefulPartitionedCall:01,model/pred_objectness/concat,model/pred_cls_prob_2_med_res/Reshape,model/pred_cls_prob_2_low_res/Reshape,model/tf.split_2/split;model/tf.split_2/split1;model/tf.split_2/split2;model/tf.split_2/split3;model/tf.split_2/split4;model/tf.split_2/split5;model/tf.split_2/split6;model/tf.split_2/split7;model/tf.split_2/split810,model/pred_cls_prob_2_hi_res/Reshape1,model/pred_cls_prob_0_low_res/Reshape
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 528 ops
```
i have no idea which intermedia tensor can be added with -i flag.
i have try ` -i model/pred_cls_prob/concat`
i have try  `-i model/pred_objectness/concat`
i have try  `-i model/pred_cls_prob_0_med_res/Reshape`
they all end up with compilation failure
```
indeed@indeed-virtual-machine:~/Desktop/tflite/yolo$ edgetpu_compiler -s -a -i "model/pred_objectness/concat"  yolov4_realds200_clip5.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
indeed@indeed-virtual-machine:~/Desktop/tflite/yolo$ edgetpu_compiler -s -a -i "model/pred_objectness/concat" -i "model/pred_cls_prob/concat"  yolov4_realds200_clip5.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
indeed@indeed-virtual-machine:~/Desktop/tflite/yolo$ edgetpu_compiler -s -a -i "model/pred_cls_prob_0_med_res/Reshape"  yolov4_realds200_clip5.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
```

any thing wrong? or what intermediate tensor should i type in with -i flag?

thanks

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

Dev Board

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Please try with this -i flag: model/p_re_lu_74/add;model/p_re_lu_74/Relu;model/p_re_lu_74/Neg_1;model/p_re_lu_74/Relu_1;model/p_re_lu_74/mul

If you are not sure which -i flag to use and not able to compile with -d flag, please try to get the layer names with the below snippet and pass it to the compiler. Thanks!

```
import tflite_runtime.interpreter as tflite
interpreter = tflite.Interpreter(model_path=model_path)
all_layers_details = interpreter.get_tensor_details()
for layer in all_layers_details:
    print(layer['name'])
```

**Comment by fjzhangcr** [comment]
> Please try with this -i flag: model/p_re_lu_74/add;model/p_re_lu_74/Relu;model/p_re_lu_74/Neg_1;model/p_re_lu_74/Relu_1;model/p_re_lu_74/mul
> 
> If you are not sure which -i flag to use and not able to compile with -d flag, please try to get the layer names with the below snippet and pass it to the compiler. Thanks!
> 
> ```
> import tflite_runtime.interpreter as tflite
> interpreter = tflite.Interpreter(model_path=model_path)
> all_layers_details = interpreter.get_tensor_details()
> for layer in all_layers_details:
>     print(layer['name'])
> ```

i know how to get all tensor names, only different is i use the interpreter in the tensorflow full package.
and get the following name. my confusion is how to identify the correct intermediate tensor in all these tensor names.
the edgetpu_compiler did not give any intermediate tensor names matching the intermediate tensor name you mention below
![image](https://user-images.githubusercontent.com/102020341/172995832-ee395019-3d50-4d9c-91f4-a7396b8a4e5b.png)

**Comment by hjonnala** [comment]
> my confusion is how to identify the correct intermediate tensor in all these tensor names.
- edgetpu_compiler -s  -d model.tflite (This should give first intermediate tensor that is not able to map to EdgeTPU when the model got compiled successfully. For any reason if its not working please reach out to [coral-support@google.com](mailto:coral-support@google.com). When you do, please share the TensorFlow Lite model that you're trying to compile so we can debug the issue (we don’t need the fully trained model—one with randomly initialized parameters should be fine). 

https://coral.ai/docs/edgetpu/compiler/#help

Thanks!

**Comment by fjzhangcr** [comment]
thank you, i am afraid i am the second condition. the log do not give any useful information.
May i mail directly to the email of [coral-support@google.com](mailto:coral-support@google.com)
or should i post an issue here
which is prior?

**Comment by hjonnala** [comment]
> or should i post an issue here
> which is prior?

If there are no concerns to share the model please post it on GitHub, otherwise please reach out to [coral-support@google.com](mailto:coral-support@google.com).

For the model linked in this issue you can use this [i flag](https://github.com/google-coral/edgetpu/issues/608#issuecomment-1151714602) to compile. Thanks!
 
![image](https://user-images.githubusercontent.com/86132058/173111766-f2f4a4d2-6922-4873-9511-f91e343faae8.png)

**Comment by tingggggg** [comment]
> > or should i post an issue here
> > which is prior?
> 
> If there are no concerns to share the model please post it on GitHub, otherwise please reach out to [coral-support@google.com](mailto:coral-support@google.com).
> 
> For the model linked in this issue you can use this [i flag](https://github.com/google-coral/edgetpu/issues/608#issuecomment-1151714602) to compile. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/86132058/173111766-f2f4a4d2-6922-4873-9511-f91e343faae8.png)

Hi @hjonnala ,

I meet the same issue when I compile my tflite model to tpu format. 
```
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed!
```

I want to know how to find out which output that be set at `-i "flag"`  so that i can successfully complie my model to tpu format.
Is there a right way to find out?

thanks

**Comment by hjonnala** [comment]
@tingggggg you may try to compile the model for [each intermediate tensor](https://github.com/google-coral/edgetpu/issues/608#issuecomment-1151714602) and find the one which can map most operations to TPU. Here is an example on how to do it: https://github.com/hjonnala/snippets/blob/main/compiler/intermediate_serach_compilation.ipynb

Thanks!

**Comment by tingggggg** [comment]
Hi @hjonnala ,
Thank for your example.
I ran your example with my model, but still can not successfully converte my model(got `Compilation failed: Compilation failed due to large activation tensors in model.` on each intermediate tensor).
Do you have any ideas?

**Comment by hjonnala** [comment]
@tingggggg please share you model to debug the issue. You model input size op itself might be too big. Please try reducing the model input size. Thanks!

**Comment by tingggggg** [comment]
[model.zip](https://github.com/google-coral/edgetpu/files/9129056/model.zip)
@hjonnala this is my model(fcn architecture).
I will try your hint about model input size. Thanks!
