### ISSUE TITLE
zero operations running on Edge TPU

### ISSUE THREAD

**Issue by Shubham-23Joshi** [google-coral/edgetpu#609]
### Description

hello, I have a simple handwriting recognition model which I've saved and converted it into tflite including default optimizations (for quantization). The model gets compiled; however, no operations run on the Edge TPU. 
The log shows 'Operation is working on an unsupported data type' for all the operations, although all the operators in the model are supported by Edge TPU.
Kindly guide me into resolving this issue. 
Thank you very much in advance.

Model code>
[handwriting_model_sample.zip](https://github.com/google-coral/edgetpu/files/8885949/handwriting_model_sample.zip)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug, Build/Install, Performance

### Operating System

Windows 10, Mendel Linux

### Coral Device

Dev Board

### Programming Language

Python 3.9

### Relevant Log Output

```shell
Input model: handwriting_model_quant.tflite
Input size: 12.88KiB
Output model: handwriting_model_quant_edgetpu.tflite
Output size: 12.19KiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 0
Total number of operations: 7
Operation log: handwriting_model_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 0
Number of operations that will run on CPU: 7

Operator                       Count      Status

MAX_POOL_2D                    2          Operation is working on an unsupported data type
SOFTMAX                        1          Operation is working on an unsupported data type
FULLY_CONNECTED                1          Operation is working on an unsupported data type
CONV_2D                        2          Operation is working on an unsupported data type
RESHAPE                        1          Operation is working on an unsupported data type
Compilation child process completed within timeout period.
Compilation succeeded!
```
</details>

**Comment by hjonnala** [comment]
Hello @Shubham-23Joshi  please go through this issue: https://github.com/google-coral/edgetpu/issues/594#issuecomment-1138880149.. Thanks!
