### ISSUE TITLE
Maximum Output Of Detected Objects Is 10 with MobileNetV2

### ISSUE THREAD

**Issue by huyhieu2135** [google-coral/edgetpu#61]
Hi!
I trained my custom dataset object detection model with **MobileNetV2_quantized**. 
And used this command line for converting my model to tflite by **this command line**:

**python export_tflite_ssd_graph.py \
  --pipeline_config_path="ckpt/pipeline.config" \
  --trained_checkpoint_prefix="train/model.ckpt-${ckpt_number}" \
  --output_directory="${OUTPUT_DIR}" \
  --add_postprocessing_op=true

tflite_convert \
  --output_file="${OUTPUT_DIR}/test_ssd.tflite" \
  --graph_def_file="${OUTPUT_DIR}/tflite_graph.pb" \
  --inference_type=QUANTIZED_UINT8 \
  --input_arrays="${INPUT_TENSORS}" \
  --output_arrays="${OUTPUT_TENSORS}" \
  --mean_values=128 \
  --std_dev_values=128 \
  --input_shapes=1,300,300,3 \
  --change_concat_input_ranges=false \
  --allow_custom_ops**

And then I tested the Tflite model with and without compiling with EdgeTPU, but no matter what I do (change top_k,...) It still displayed **maximum 10 outputs of detected object (10 boxes).**
So I tried the model "**mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite**" from this repo "**https://github.com/google-coral/tflite/tree/master/python/examples/detection**" and it worked well, **predicted more than 10 boxes**.
Can you guys help me, pls?
Thank you!

**Comment by Namburger** [comment]
@huyhieu2135 to clarify, are you using our [edgetpu.detection.engine](https://github.com/google-coral/edgetpu/blob/master/edgetpu/detection/engine.py) to run inference?
If so, there are 2 constraint: threshold, and top_k. If the score of result is under the threshold, it may [get droped](https://github.com/google-coral/edgetpu/blob/master/src/cpp/detection/engine.cc#L35). You can try passing `threshold=0.0` to take off that constraint.

**Comment by huyhieu2135** [comment]
Hello @Namburger !
Thank for answering!
I used both edgetpu.detection.engine and Tensorflow Lite API, and verified threshold and top_k, it's still 10 boxes for maximum. At the beginning, I thought it was the limitation of engine but it seems tobe converting problem, i think. Do you have any idea?

**Comment by huyhieu2135** [comment]
![image](https://user-images.githubusercontent.com/44475399/75003695-0d272a00-54ac-11ea-954a-335b79113a71.png)

Hi!
I just found this problem when checking the graph of my model compiled with edgetpu. You can see the yellow highlights in the image. The model is limited up to 10 output. How can I fix this?

**Comment by huyhieu2135** [comment]
Ah nevermind! I found the problem, it was my mistake while exporting the model!
Thanks for your help, really appreciate!

**Comment by Namburger** [comment]
@huyhieu2135 ahhhhhhh
I initially thought that you used [this](https://github.com/google-coral/tflite/tree/master/python/examples/detection) demo and got a different result, didn't realized you used that model on the same demo and compared results to yours (sorry it was the end of the day lol).
Any how, was it a tweak in one of the parameter? Would you mind sharing the fix for future reference?

**Comment by bkurianAIML** [comment]
> @huyhieu2135 ahhhhhhh I initially thought that you used [this](https://github.com/google-coral/tflite/tree/master/python/examples/detection) demo and got a different result, didn't realized you used that model on the same demo and compared results to yours (sorry it was the end of the day lol). Any how, was it a tweak in one of the parameter? Would you mind sharing the fix for future reference?


I am facing the same issue. Can you share the fix?

**Comment by nithya-rize** [comment]
Im facing the issue too. Can you please share the fix?
