### ISSUE TITLE
Why is pycoral faster than libedgetpu (c API)?

### ISSUE THREAD

**Issue by kampff** [google-coral/edgetpu#613]
I am benchmarking MoveNet (Lightning) performance on a Raspberry Pi 4b (32-bit buster, 4Gb RAM, overlocked to 2 GHz, USB Accelerator) with "libedgetpu1-max" runtime installed.

I have compared inference performance (latency) using pycoral and libedgetpu's c API using the following minimal programs (attached, renamed as txt files...because...GitHub):

[benchmark_movenet_pycoral.py.txt](https://github.com/google-coral/edgetpu/files/8923218/benchmark_movenet_pycoral.py.txt)
[benchmark_movenet_c_api.c.txt](https://github.com/google-coral/edgetpu/files/8923219/benchmark_movenet_c_api.c.txt)
[build_benchmark_movenet_c_api.sh.txt](https://github.com/google-coral/edgetpu/files/8923220/build_benchmark_movenet_c_api.sh.txt)

I get an average latency of ***16 ms*** for pycoral and ***21 ms*** for libedgetpu c API. ***Why is this?***

Also, why are these both significantly longer than the benchmarks reported [here](https://coral.ai/models/pose-estimation/).

You can test these programs by copying them into a new sub-folder of your "pycoral" root (on a Raspberry Pi running 32-bit RPiOS "buster", probably also works with bullseye). *Note:* the benchmark_movenet_c_api.c program can be built with the attached bash script. However, you first have to build libtensorflow_c.so and libedgetpu.so (direct) following the instructions [here](https://coral.ai/docs/notes/build-coral/) and "install" the relevant headers. Please get in touch if you have problems, I am happy to help.

I have also inspected the semi-detailed (verbosity=5) logs generated by each (pycoral and c API) program, and, well, they look quite similar.

[c_api_log.txt](https://github.com/google-coral/edgetpu/files/8923205/c_api_log.txt)
[pycoral_log.txt](https://github.com/google-coral/edgetpu/files/8923206/pycoral_log.txt)

On another, seperate *but equally confusing note*, why does there seem to be USB transfers (according to the verbose debug output) after the first inference? The model is already loaded, the inputs are set, and only inference is being invoked on the second run. What data has to pass over USB?

The second inference starts at line 329 in the c_api log and 330 in the pycoral log. These are then followed by many lines such as this: "I driver/usb/usb_driver.cc:1138] bulk in 1024 bytes from buffer index [?])". *What is going on here?*

Thanks in advance!

**Comment by hjonnala** [comment]
> I get an average latency of _**16 ms**_ for pycoral and _**21 ms**_ for libedgetpu c API. _**Why is this?**_

Please compare average latency for at least 1000 inferences. And please check these issues it is expected that for some models  python API is faster than C API. https://github.com/tensorflow/tensorflow/issues/29746, https://github.com/tensorflow/tensorflow/issues/15552#issuecomment-396573076

> Also, why are these both significantly longer than the benchmarks reported [here](https://coral.ai/models/pose-estimation/).

MoveNet (Lightning)  has some operations running on CPU. The latency difference is due to difference between benchmark Desktop CPU and RPI CPU.


> On another, seperate _but equally confusing note_, why does there seem to be USB transfers (according to the verbose debug output) after the first inference? The model is already loaded, the inputs are set, and only inference is being invoked on the second run. What data has to pass over USB?
> 
> The second inference starts at line 329 in the c_api log and 330 in the pycoral log. These are then followed by many lines such as this: "I driver/usb/usb_driver.cc:1138] bulk in 1024 bytes from buffer index [?])". _What is going on here?_

These are data  transfers logs from TPU to CPU for each inference. The only difference for first inference and rest of the inferences for same model is loading the model into Edge TPU memory.

**Comment by kampff** [comment]
> Please compare average latency for at least 1000 inferences. And please check these issues it is expected that for some models python API is faster than C API. [tensorflow/tensorflow#29746](https://github.com/tensorflow/tensorflow/issues/29746), [tensorflow/tensorflow#15552 (comment)](https://github.com/tensorflow/tensorflow/issues/15552#issuecomment-396573076)

The benchmarks reported were run with 1000 iterations. Thanks for linking to the other issues. However, in my case, I discovered that I had compiled libtensorflow_c.so without XNNPACK, and given your insight that MoveNet uses many CPU-only OPS, this explains the performance difference.

Having rebuilt libtensorflow, I now achieve ***11 ms*** latency using the C API. All good, you can close the issue.

Thanks for the help!
 
> > Also, why are these both significantly longer than the benchmarks reported [here](https://coral.ai/models/pose-estimation/). 

> MoveNet (Lightning) has some operations running on CPU. The latency difference is due to difference between benchmark Desktop CPU and RPI CPU.

Again, this was a key insight for me. Thanks!
 
> > On another, seperate _but equally confusing note_, why does there seem to be USB transfers (according to the verbose debug output) after the first inference? The model is already loaded, the inputs are set, and only inference is being invoked on the second run. What data has to pass over USB?

Given that the results of CPU ops need to be transferred to the EdgeTPU, then, obviously, we expect USB traffic.
