### ISSUE TITLE
how to set a .sh command file auto run at mendel start?

### ISSUE THREAD

**Issue by fjzhangcr** [google-coral/edgetpu#614]
### Description

i have make a .sh file which contains the scrips to run a python file...
but how can i make it autorun the moment coral devboard boot?
i have try rename it as rc.local and chmod +x and put it in /etc/ ,but it fail to autorun at system reboot~~
pls tell me how, thank you 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

Other

### Relevant Log Output

```shell
i have make a .sh file which contains the scrips to run a python file...
but how can i make it autorun the moment coral devboard boot?
i have try rename it as rc.local and chmod +x and put it in /etc/ ,but it fail to autorun at system reboot~~
pls tell me how, thank you
```
</details>

**Comment by hjonnala** [comment]
Please try the steps mentioned at: https://stackoverflow.com/questions/57302900/how-do-i-run-a-python-script-on-boot-on-google-coral
 
Thanks!

**Comment by fjzhangcr** [comment]
excellent solution！！thank you！
