### ISSUE TITLE
Lock the Screen on Startup - Coral Dev Board

### ISSUE THREAD

**Issue by bsteiner-dandy** [google-coral/edgetpu#617]
How can I lock the screen at startup? Right now it automatically logs in if there is a keyboard and monitor attached. I am looking to add some basic security. Thanks!

**Comment by hjonnala** [comment]
Unfortunately, Security features are not supported with Mendel OS as Coral development is primarily focused on embedded ML inference on the edge TPU. You may please try the solution provided here: https://stackoverflow.com/a/65240554/16660336. Thanks!
