### ISSUE TITLE
How to Use Security Features on Coral for Encryption

### ISSUE THREAD

**Issue by bsteiner-dandy** [google-coral/edgetpu#618]
### Description

The documentation lists multiple security features that are included with the Coral:

Resource Domain Controller (RDC) supports four domains and up to eight regions
Arm TrustZone (TZ) architecture
On-chip RAM (OCRAM) secure region protection using OCRAM controller
High Assurance Boot (HAB)
Cryptographic acceleration and assurance (CAAM) module
Secure non-volatile storage (SNVS): Secure real-time clock (RTC)
Secure JTAG controller (SJC)

How can I use one of these features to encrypt my code and model and decrypt it when it runs without manually entering a password?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Feature Request

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
We don't directly support the security features for the imx8m, but we have used the crytographic processor to store security keys.
You can check the [coral cloud repo](https://coral.googlesource.com/coral-cloud/+/refs/heads/master).This enables using the [ecc608](https://coral.googlesource.com/coral-cloud/+/refs/heads/master/python/coral-cloudiot/coral/cloudiot/ecc608.py) for communicating with Google Cloud IoT Core. It includes the [cryptoauthlib sdk](https://github.com/MicrochipTech/cryptoauthlib) for interacting with the cryptographic co processor.

Our suggestion is to reach out to [NXP's community page](https://community.nxp.com/) directly for help regarding these security features as they are features on the [imx8m](https://www.nxp.com/products/processors-and-microcontrollers/arm-processors/i-mx-applications-processors/i-mx-8-processors/i-mx-8m-family-armcortex-a53-cortex-m4-audio-voice-video:i.MX8M) by NXP.

All the best!
