### ISSUE TITLE
2 Dev Boards on Windows10 PC (Problem: same IP)

### ISSUE THREAD

**Issue by vleonn** [google-coral/edgetpu#619]
### Description

Hello,

I am on Windows 10 and I have successfully installed the MDT tool and flashed 2 Dev Boards.

When I connect only one of the Dev Boards, it takes the IP 192.168.101.2, and I can successfully log in either via "ssh" or "mdt shell".

The problem is when I connect both of them.

As you can see, they take the same IP:
$ mdt devices
neat-valet       (192.168.101.2)
neat-mole       (192.168.101.2)

In this case, I always log in to the one that was inserted first, even if I explicitly define the name (which is expected, considering that they have the same IP).

Is there a solution on this? How can they take a different IP? I will need to have both of them connected at the same time, and choose where to log in.

Thank you in advance. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Windows 10

### Coral Device

Dev Board

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Please check the  **/etc/NetworkManager/system-connections/** folder,  there will be **gadget0.nmconnection** and **gadget1.nmconnection**. In that file, you can set a static ip address (for instance 192.168.101.3) that stays static with the board on the next reboot.

```
mendel@red-apple:~$ sudo cat /etc/NetworkManager/system-connections/gadget1.nmconnection
[connection]
id=gadget1
uuid=0918c486-cb57-48f0-9797-a1513d58794d
type=ethernet
interface-name=usb1
permissions=

[ethernet]
mac-address-blacklist=

[ipv4]
address1=192.168.101.2/24
dns-search=
method=manual

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
method=auto
mendel@red-apple:~$ 

```

**Comment by vleonn** [comment]
Thank you for the answer.

I changed in "gadget1", and then in both "gadget0" and "gadget1", the address1 to 192.168.101.3/24 (from 101.2). 
However, it is still recognized as 192.168.101.2 in the host PC.

Update: Now I cannot even log in to the device via mdt shell.

**Comment by hjonnala** [comment]
> $ mdt devices
> neat-valet (192.168.101.2)
> neat-mole (192.168.101.2)


Please try to connect with [serial console](https://coral.ai/docs/dev-board/serial-console/#connect-with-windows) to revert the changes and change only one gadget(gadget0 or gadget1) which says 192.168.101.2 previously and reboot the device.

If you are not able to connect with serial console please [reflash](https://coral.ai/docs/dev-board/get-started/#flash-the-board) the board. Thanks!

**Comment by vleonn** [comment]
Hello, 

I just found the problem: 
when I change the IP to 101.3 (only in gadget1, i.e., where it was 101.2), it is saved, but when I reboot it is reverted back to 101.2.

**Comment by hjonnala** [comment]
Okay.. please try the below steps I am assuming Dev board is recognized with USB1 gadget:

1. **sudo vim /etc/dnsmasq.d/02-usb-gadget**

change this line as below: https://coral.googlesource.com/usb-gadget/+/refs/heads/master/etc/dnsmasq.d/02-usb-gadget#7

`dhcp-range=usb1,192.168.102.50,192.168.102.99,255.255.255.0,12h`

2. **sudo vim /usr/bin/usb-gadget-start.sh**

Change the logic here as below: https://coral.googlesource.com/usb-gadget/+/refs/heads/master/usr/bin/usb-gadget-start.sh#117

```
configure_network() { 
        GADGET_CON_NAME="gadget${1}" 
        INTERFACE_NAME="usb${1}" 
        $(nmcli con show | grep -q "${GADGET_CON_NAME}") 
        mendel_conn_exist=$? 
        if [[ "$mendel_conn_exist" -eq 0 ]]; then 
          echo "${GADGET_CON_NAME} connection already exists" 
         
        elif [ "${1}" -eq "1" ]; then 
          nmcli con add con-name "${GADGET_CON_NAME}" ifname "${INTERFACE_NAME}" type ethernet ip4 "192.168.102.2/24" 
        else 
          nmcli con add con-name "${GADGET_CON_NAME}" ifname "${INTERFACE_NAME}" type ethernet ip4 "192.168.10${1}.2/24" 
        fi 
        nmcli con up id "${GADGET_CON_NAME}" 
} 
 
```
 
3. **sudo reboot now**

4. Verify the changes:
```

mendel@red-apple:~$ sudo netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.7.1     0.0.0.0         UG        0 0          0 wlan0
192.168.7.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan0
192.168.100.0   0.0.0.0         255.255.255.0   U         0 0          0 usb0
192.168.102.0   0.0.0.0         255.255.255.0   U         0 0          0 usb1
 



```

**Comment by vleonn** [comment]
Hello, thanks for the help!
It worked.

Now, I am going to setup a 3rd device. 

I will add in the respective files:

`dhcp-range=usb1,192.168.103.50,192.168.103.99,255.255.255.0,12h`

```
elif [ "${1}" -eq "1" ]; then 
          nmcli con add con-name "${GADGET_CON_NAME}" ifname "${INTERFACE_NAME}" type ethernet ip4 "192.168.103.2/24"
```

First attempt didn't work, but I will check it again.

**Comment by hjonnala** [comment]
Feel free to reopen if you are still having issues here. Thanks!
