### ISSUE TITLE
High (x20) inference time with converted ssd mobilenet v2 quant model.

### ISSUE THREAD

**Issue by larrylart** [google-coral/edgetpu#62]
With the provided/compiled  graph mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite I am getting inference time around 10ms. 
However, when I convert/compile I am getting an inference time of around 270ms, I am using the following quant trained model : http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz
With, 
tflite_convert \
  --output_file="${OUTPUT_DIR}/output_tflite_graph.tflite" \
  --graph_def_file="${OUTPUT_DIR}/tflite_graph.pb" \
  --inference_type=QUANTIZED_UINT8 \
  --input_arrays="${INPUT_TENSORS}" \
  --output_arrays="${OUTPUT_TENSORS}" \
  --mean_values=128 \
  --std_dev_values=128 \
  --input_shapes=1,300,300,3 \
  --change_concat_input_ranges=false \
  --allow_nudging_weights_to_use_fast_gemm_kernel=true \
  --allow_custom_ops

And then compiled with:

Edge TPU Compiler version 2.0.291256449
Input: output_tflite_graph.tflite
Output: output_tflite_graph_edgetpu.tflite

Operator                       Count      Status

CUSTOM                         1          Operation is working on an unsupported data type
ADD                            10         Mapped to Edge TPU
CONCATENATION                  2          Mapped to Edge TPU
CONV_2D                        55         Mapped to Edge TPU
DEPTHWISE_CONV_2D              17         Mapped to Edge TPU
RESHAPE                        13         Mapped to Edge TPU
LOGISTIC                       1          Mapped to Edge TPU

I tried to export the frozen graph from checkpoint with the same results.  Am I missing something in the compilation/conversion procedure?

**Comment by Namburger** [comment]
@larrylart This is possibly due to the CUSTOM 1 op being an unsupported datatype? 
What tensorflow version and your parameters for `INPUT_TENSORS` and `OUTPUT_TENSORS`?

**Comment by larrylart** [comment]
@Namburger Is the version from the docker container 1.12 from tutorial - https://coral.ai/docs/edgetpu/retrain-detection/

INPUT_TENSORS='normalized_input_image_tensor'
OUTPUT_TENSORS='TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3'

**Comment by larrylart** [comment]
@Namburger I thought that CUSTOM op to be the issue, however I don't know how to identify it? Ans it's part of the official ssd mobilenet v2 checkpoint so I was hopping to reproduce the same performance as Coral's team mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
I just tried different versions of tensorflow (14/15) same issue. I have a vague recollection of some optimization that needed to be done for quantization, I think in openvino, but might not be related.

**Comment by larrylart** [comment]
@Namburger Well, I found the problem after trying everything from different versions of tensorflow to older versions of edgetpu compiler and all possible conversions options (btw the CUSTOM op is added by export_tflite_ssd_graph.py --add_postprocessing_op=true), was done to a typo in my conversion script ... I was copying over/inferring against  the original tflite  instead of the compiler generated one.  Once I got the right file in place inference time now is down to 9ms.

**Comment by Namburger** [comment]
@larrylart sorry, I got totally confused and thought you just downloaded the model and converted it, didn't realized you were doing the retrain with our tutorial (it was the end of the day :) ). 
Any ways, I'm really glad you caught that because otherwise I wouldn't have caught that you were using the the wrong model... (which you may be able to caught with some strace). 
Thanks for closing and cheers
