### ISSUE TITLE
Coral.ai Edge TPU support with Jax + Flax? 

### ISSUE THREAD

**Issue by rosikand** [google-coral/edgetpu#621]
### Description

Would coral.ai's edge tpu support Jax + Flax neural network models? 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
We don't have official support for Jax+Flax models. But, these models can be run on Edge TPU if they can be converted to [full int8 tflite models](https://www.tensorflow.org/lite/performance/post_training_integer_quant) and can be compiled with [Edge TPU compiler](https://coral.ai/docs/edgetpu/compiler/).

Please check the Edge TPU model requirements and supported operations at: https://coral.ai/docs/edgetpu/models-intro/#compatibility-overview.

**Comment by rvalitov** [comment]
It would be awesome if supported. With popularity of Stable Diffusion and similar AI image generators, the Coral could be a great tool.

**Comment by ricardodeazambuja** [comment]
Apparently, there should be a way, but the notebook supplied miserably crashes. At first, because it asks to install tf-nightly and it's incompatible with the installed numpy. Then, because the conversion needs a GPU. Finally, some ugly flatbuffer related error :laughing: 
```
tf.__version__, jax.__version__, np.__version__
# ('2.9.2', '0.3.25', '1.21.6')
```
https://www.tensorflow.org/lite/examples/jax_conversion/overview

**Comment by fedecompa** [comment]
No, it would give you this error: "RuntimeError: Unable to initialize backend 'tpu': UNIMPLEMENTED: LoadPjrtPlugin is not implemented on windows yet." on windows or this error on linux: "warning: could not determine tpu accelerator type. set env var tpu_accelerator_type to set manually. tpu runtime may not be properly initialized."

You have to use the pycoral.utils.edgetpu library.

**Comment by markusheimerl** [comment]
I second, that support for Jax would be amazing.

**Comment by Laurence-Cullen** [comment]
I would also love to use JAX with a Coral board, for audio and image classification problems.

**Comment by richjames0** [comment]
+1. I'd love to build with this but lack of JAX is a dealbreaker for me

**Comment by jusevitch** [comment]
I'm also interested in JAX support for Coral boards. This would make the boards a more modern and competitive option.

**Comment by boredcoder411** [comment]
for now, my coral board is sitting on a shelf because I can't do anything of much value without jax, so +1 on this issue

**Comment by thefl0yd** [comment]
> for now, my coral board is sitting on a shelf because I can't do anything of much value without jax, so +1 on this issue

This hardware is google abandonware so you’re not ever going to see this (closed anyway) feature.

**Comment by fedecompa** [comment]
Maybe you can convert to a tflite model with openvino: 

https://huggingface.co/docs/transformers/en/tflite
