### ISSUE TITLE
Push MDT key for new user on Coral Dev Board

### ISSUE THREAD

**Issue by bsteiner-dandy** [google-coral/edgetpu#624]
### Description

I have created a new user and I would like to be able to `mdt shell` to connect as that user. However when I try to push the key I get `Unable to push keys to the device: Authentication failed.` What should I be doing differently?

This is the process I am using so far:
```
mdt set username mendel
mdt set password mendel
mdt exec "sudo useradd -m newuser"
mdt exec "echo -e 'newpassword\nnewpassword' | sudo passwd newuser"
mdt exec "sudo adduser newuser sudo"
mdt exec "sudo cp -a /home/mendel/. /home/newuser/"
mdt exec "echo 'newuser ALL=(ALL:ALL) NOPASSWD: ALL' | sudo tee /etc/sudoers.d/newuser"
mdt exec "sudo rm /home/mendel/.ssh/authorized_keys"
mdt resetkeys 192.168.100.2
mdt set username newuser
mdt set password newpassword
mdt pushkey
```

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
@bsteiner-dandy Please try the below steps:

```
mendel@deft-goose:~$ sudo adduser test
Adding user `test' ...
Adding new group `test' (1004) ...
Adding new user `test' (1001) with group `test' ...
Creating home directory `/home/test' ...
Copying files from `/etc/skel' ...
New password: 
Retype new password: 
passwd: password updated successfully
Changing the user information for test
Enter the new value, or press ENTER for the default
        Full Name []: 
        Room Number []: 
        Work Phone []: 
        Home Phone []: 
        Other []: 
Is the information correct? [Y/n] y
```

`mendel@deft-goose:~$ sudo vim /etc/passwd`
modify the test user line as : `test:x:1000:1000:,,,:/home/mendel:/bin/bash`

mendel@deft-goose:~$ sudo vim /etc/ssh/sshd_config
Add the below line at the end of /etc/ssh/sshd_config file:
`AllowUsers test`

`mendel@deft-goose:~$ sudo reboot now`

```
mdt set username test
mdt set password test
mdt shell
```

**Comment by bsteiner-dandy** [comment]
I tried this process, but in the mdt shell, I ran `whoami` and it reports "mendel"

**Comment by hjonnala** [comment]
Please try echo "$USER". The output of the whoami command is slightly different from $USER because whoami outputs the username that the user is working under, whereas $USER outputs the username that was used to log in

```
mendel@deft-goose:~$ echo "$USER"
test
mendel@deft-goose:~$ whoami
mendel
```
https://en.wikipedia.org/wiki/Whoami#:~:text=On%20Unix%2Dlike%20operating%20systems,was%20used%20to%20log%20in.

**Comment by bsteiner-dandy** [comment]
I see, thank you
