### ISSUE TITLE
Distinguish edge tpu models from regular tflite models

### ISSUE THREAD

**Issue by lokesh-0706** [google-coral/edgetpu#625]
### Description

While visualising several edge tpu models using netron I found 'edgetpu-custom-op' in all of them. Do all edge tpu models and only edge tpu models contain 'edgetpu-custom-op'? Can we use this 'edgetpu-custom-op' to differentiate edgetpu models from regular tflite models?
(I tried to get ops using interpreter._get_ops_details() in python )

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

C++, Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
yes, you can use the edgetpu-custom-op to differentiate edgetpu models from regular tflite models: https://github.com/google-coral/edgetpu/issues/546#issuecomment-1050665727. Thanks!
