### ISSUE TITLE
problems on downloading required library 

### ISSUE THREAD

**Issue by KyawSawLIN** [google-coral/edgetpu#626]
### Description

I am trying to make use of GPIO pins of google coral dev board and I needed to download python peripheral library. But the problem occurs at downloading python library using command "python3 -m pip install python-periphery ". But the following error prompts and I cannot proceed anymore. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Relevant Log Output

```shell
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/python-periphery/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/python-periphery/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/python-periphery/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/python-periphery/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/python-periphery/
  Could not find a version that satisfies the requirement python-periphery (from versions: )
No matching distribution found for python-periphery
```
</details>

**Comment by hjonnala** [comment]
> ```shell
> Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/python-periphery/
> ```
@KyawSawLIN  please try the below command. Thanks!

`python3 -m pip install --trusted-host files.pythonhosted.org python-periphery`

**Comment by KyawSawLIN** [comment]
Thanks for your reply. That command still prompts the exact same error. Do you have any other ideas how to resolve?

**Comment by hjonnala** [comment]
[The issue](https://python-forum.io/thread-12634.html) might be due to a corporate proxy/firewall/mitm-box is not allowing traffic to pypi.org and/or files.pythonhosted.org. Have you connected to the board with any restricted wifi network? 

Can you try to install it with whl file: https://pypi.org/project/python-periphery/#files 

python3 -m pip install https://files.pythonhosted.org/packages/00/2c/39f674e6cefd3ff8f2825d37efbb4f763eb0504ccb4405d05a498026845e/python_periphery-2.3.0-py2.py3-none-any.whl

**Comment by KyawSawLIN** [comment]
Thanks for your feedback. It works when I changed the network.
