### ISSUE TITLE
Runtime profile tool for edgetpu models

### ISSUE THREAD

**Issue by corvitacvision** [google-coral/edgetpu#627]
### Description

Hello Google-Coral team, I would like to know that if there is any tool/api available to profile the runtime of edge tpu model. It would be great to have such tool which can be very helpful for model optimization.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Operating System

Ubuntu

### Coral Device

USB Accelerator, M.2 Accelerator A+E, M.2 Accelerator B+M

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Individual operation level profiling is not available for Edge TPU models.

Please refer to this link to compile the models based on profiling: https://coral.ai/docs/edgetpu/compiler/#profiling-partitioner

Thanks!
