### ISSUE TITLE
New Coral Dev Board reboots on edgetpu_demo --device

### ISSUE THREAD

**Issue by bantar76** [google-coral/edgetpu#628]
This is my 2nd Coral Dev Board, and I also have a Dev Board Mini.  Neither of those have had any issues like this.  Right now, after a fresh flash, the board is rebooting when I run  "edgetpu_demo --device".  "edgetpu_demo --stream" seems to work ok.  Before previous flashes I've had it reboot on any attempt to run edgetpu_demo --device or --stream, and it also went into a boot loop after one flash.  Is this board defective?

**Comment by bantar76** [comment]
Hello again, I just plugged in a known good USB webcam and it fell into the boot loop again (immediately on plug in of the webcam).  Now, even with USB webcam removed, the boot loop remains.  I connected via serial console and captured console messages during boot loop.  Please advise. 
[putty.log](https://github.com/google-coral/edgetpu/files/9098622/putty.log) 

<edited> I tried flashing one more time via the instructions (5th time today).  "edgetpu_demo --device" sent it into the boot loop again :(.

**Comment by hjonnala** [comment]
Hello @bantar76 , Can you please confirm that you are using 5V/3A power supply to the board and this power supply is working for the other Dev Board.

**Comment by bantar76** [comment]
That was it, a bad power supply.  Many thanks!
