### ISSUE TITLE
ResizeBilinear incorrect

### ISSUE THREAD

**Issue by hgaiser** [google-coral/edgetpu#63]
There was an issue in tflite regarding the ResizeBilinear op (see https://github.com/tensorflow/tensorflow/issues/33691 for more info). The effect, in my case, is that my semantic segmentation has an offset to the top left by some pixels (~20 pixels). This has since been fixed in https://github.com/tensorflow/tensorflow/commit/d855adfc5a0195788bf5f92c3c7352e638aa1109 .

Coincidentally, this is also the version used by `tflite_runtime` according to https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5 , as mentioned by (@Namburger](https://github.com/google-coral/edgetpu/issues/44#issuecomment-589170013).

Still though, when I run the model using an EdgeTPU USB device, I see the same offset in my semantic segmentation.

To summarize, this is what I have done:

1. Trained using tensorflow.
2. Tested using tensorflow, results are **good**.
3. Converted to tflite using a nightly version of tensorflow with `tf.lite.TFLiteConverter.from_keras_model` and quantization.
4. Tested using `tflite_runtime.interpreter.Interpreter` from [here](https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter), results are **good**.
5. Compiled model to an edgetpu device using the [provided compiler](https://github.com/google-coral/edgetpu/tree/master/compiler/x86_64). Output for this step is shown below.
6. Tested using the same `tflite_runtime` as before, but with delegation to the TPU device. Results are computed, but have an **offset**, similarly as was the case with tensorflow _before_ the fix from https://github.com/tensorflow/tensorflow/commit/d855adfc5a0195788bf5f92c3c7352e638aa1109 .
7. Tried to run tflite_runtime with a new version of tensorflow, but I get the following error: `RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.`, presumably because of incompatibility with the newer version of tensorflow and libedgetpu.

My guess is that the TPU ops need to be adjusted to be "compatible" with the fix applied to tensorflow / tflite, but I'm not familiar enough with TPU to know if this is the case and/or how to proceed.

Output for the compile step:
```shell
Edge TPU Compiler version 2.0.291256449

Model compiled successfully in 637 ms.

Input model: quantized.tflite
Input size: 2.80MiB
Output model: quantized_edgetpu.tflite
Output size: 2.94MiB
On-chip memory available for caching model parameters: 7.05MiB
On-chip memory used for caching model parameters: 2.63MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 73
Operation log: quantized_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 67
Number of operations that will run on CPU: 6

Operator                       Count      Status

LOGISTIC                       1          More than one subgraph is not supported
ADD                            10         Mapped to Edge TPU
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
PAD                            5          Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
CONV_2D                        35         Mapped to Edge TPU
DEPTHWISE_CONV_2D              17         Mapped to Edge TPU
DEQUANTIZE                     1          Operation is working on an unsupported data type
RESIZE_BILINEAR                1          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESIZE_BILINEAR                1          Image-interpolation layer won't run precisely enough on Edge TPU
```

**Comment by Namburger** [comment]
@hgaiser seems to me like the issue is caused by the compiler not taking this tensorflow fix into account. since the compiler is not open source, I can't give too much details :/
Is it ok if I ask you to submit your tflite model before compiling and the test run script?

**Comment by hgaiser** [comment]
@Namburger thank you that would be very kind. I will try to make a minimum example of how it goes wrong. Can I send it to you privately somehow?

**Comment by hgaiser** [comment]
I've made a minimum example, then I don't need to send it privately. I trained a very simple model using mobilenet on a black image with a square in the middle. 

![input](https://user-images.githubusercontent.com/716138/75331215-9c548900-5882-11ea-85f4-f3d649f84639.png)

Then trained it without any special tricks (I can share the training script but I don't think it is relevant here?). Then tested it with the following script:

```python
import sys
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

if __name__=='__main__':
    if len(sys.argv) != 2:
        raise Exception(f"Usage: {sys.argv[0]} <model>")

    model = tf.keras.models.load_model(sys.argv[1])

    # Create a black on white square.
    input_image = np.zeros((500, 500, 3), dtype=np.float32)
    input_image[200:300, 200:300, :] = 50

    # Run the network.
    outputs = model.predict(input_image[np.newaxis, ...])

    # Threshold the output and draw it gray.
    visualization = 127 * (outputs[0, :, :, 0] > 0.5).astype(np.uint8)

    # Draw a small border to show where the ground truth was.
    visualization[199:202, 200:300] = 255
    visualization[299:302, 200:300] = 255
    visualization[200:300, 199:202] = 255
    visualization[200:300, 299:302] = 255

    # Show the output.
    plt.imshow(visualization)
    plt.show()
```

Which gives the following output:

![test](https://user-images.githubusercontent.com/716138/75331431-fa816c00-5882-11ea-80b7-a79b23180150.png)

Then converting from `.h5` to `.tflite`:
```python
import sys
import tensorflow as tf
import numpy as np

if __name__=='__main__':
    if len(sys.argv) != 3:
        raise Exception(f"Usage: {sys.argv[0]} <model> <out_model>")

    model = tf.keras.models.load_model(sys.argv[1])

    def representative_dataset():
        # Create a gray square on black background.
        input_image = np.zeros((500, 500, 3), dtype=np.float32)
        input_image[200:300, 200:300, :] = 50

        for i in range(50):
            yield [input_image[np.newaxis, ...]]

    # Convert to tflite.
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    tflite_model = converter.convert()

    # Save the model.
    with open(sys.argv[2], 'wb') as output_model:
        output_model.write(tflite_model)
```

And testing with the following script:

```python
import sys
import numpy as np
import matplotlib.pyplot as plt

import tflite_runtime.interpreter

if __name__=='__main__':
    if len(sys.argv) != 3:
        raise Exception(f"Usage: {sys.argv[0]} <model> <tpu>")

    tpu = sys.argv[2] == 'true'
    if tpu:
        print("Using TPU delegation...")

    # Load the tflite model.
    interpreter = tflite_runtime.interpreter.Interpreter(
        model_path=sys.argv[1],
        experimental_delegates=[tflite_runtime.interpreter.load_delegate('libedgetpu.so.1')] if tpu else None
    )
    interpreter.allocate_tensors()

    # Get input and output tensors.
    input_details  = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Create a gray square on black background.
    input_image = np.zeros((500, 500, 3), dtype=np.float32)
    input_image[200:300, 200:300, :] = 50

    # Set the input data.
    interpreter.set_tensor(input_details[0]['index'], input_image[np.newaxis, ...])

    # Run the tflite network.
    interpreter.invoke()
    outputs = interpreter.get_tensor(output_details[0]['index'])

    # Threshold the output and draw it gray.
    visualization = 127 * (outputs[0, :, :, 0] > 0.5).astype(np.uint8)

    # Draw a small border to show where the ground truth was.
    visualization[199:202, 200:300] = 255
    visualization[299:302, 200:300] = 255
    visualization[200:300, 199:202] = 255
    visualization[200:300, 299:302] = 255

    # Show the output.
    plt.imshow(visualization)
    plt.show()
```

Note that this script allows to use either with TPU or without TPU.

Without TPU the results are:

![no_tpu](https://user-images.githubusercontent.com/716138/75331544-30beeb80-5883-11ea-9415-ecad44d8e58b.png)

Then compiling it using the latest compiler, gives the following output:

```shell
Edge TPU Compiler version 2.0.291256449

Model compiled successfully in 643 ms.

Input model: simple_segmentation.tflite
Input size: 2.72MiB
Output model: simple_segmentation_edgetpu.tflite
Output size: 2.85MiB
On-chip memory available for caching model parameters: 7.05MiB
On-chip memory used for caching model parameters: 2.63MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 73
Operation log: simple_segmentation_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 67
Number of operations that will run on CPU: 6
See the operation log file for individual operation details.
```

And the results of this model using the script above gives:

![with_tpu](https://user-images.githubusercontent.com/716138/75331665-65cb3e00-5883-11ea-8b3a-53acd5d397e0.png)

You can see a shift in the resulting segmentation, which as far as I'm aware comes from the change in ResizeBilinear.

Attached is the tflite model.

[simple_segmentation.zip](https://github.com/google-coral/edgetpu/files/4254668/simple_segmentation.zip)

**Comment by Namburger** [comment]
@hgaiser sorry, I'm getting a really high volume of issues recently, thank you so much for all the details. I just realized this while compiling (and then I saw it on your log):
```
RESIZE_BILINEAR                1          Image-interpolation layer won't run precisely enough on Edge TPU
```
you are definitely correct this is the issue. Looks like the compiler is aware of it, but have not had the fixed for this release, I'm not exactly sure what's the plan for this fix, let me file a bug on this and I'll give you some updates!

**Comment by Tridet** [comment]
any news on this issue?

**Comment by Namburger** [comment]
@Tridet 
not at the moment, but it is actively in the work!

**Comment by Namburger** [comment]
@Tridet @hgaiser 
This is fixed, you guys can follow our [news](https://coral.ai/news) page for updates on the new compiler release!

**Comment by hgaiser** [comment]
@Namburger any idea when it will be released? Alternatively, is there some workaround that I can apply, or beta version of the compiler?

**Comment by Namburger** [comment]
@hgaiser I do, and it's soon, at least for now! but I can't disclosed much else, sorry :/

**Comment by hgaiser** [comment]
I see a new compiler is released, I will check this issue tomorrow to see if it is resolved :+1:

**Comment by hgaiser** [comment]
The issue is resolved, thank you @Namburger :tada:
