### ISSUE TITLE
ERROR: Didn't find op for builtin opcode 'CONV_2D' version '6'

### ISSUE THREAD

**Issue by motilal76** [google-coral/edgetpu#631]
Tensorflow 2.9.1, edgetpu_compiler 16.0

ERROR: Didn't find op for builtin opcode 'CONV_2D' version '6'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?

ERROR: Registration failed.

**Comment by hjonnala** [comment]
@motilal76  please try with Tensorflow version 2.8.2. Thanks!

**Comment by motilal76** [comment]
for 2.8.2 it throws an error 

/usr/local/lib/python3.8/dist-packages/keraslayers/convolutional.py:233 Error 'tf.Conv2D' op is neither a custom op nor a flex op

**Comment by motilal76** [comment]
Thanks Hemanth,
for 2.8.2 it throws an error

/usr/local/lib/python3.8/dist-packages/keraslayers/convolutional.py:233 Error 'tf.Conv2D' op is neither a custom op nor a flex op


    On Tuesday, July 26, 2022, 10:50:18 AM PDT, Hemanth-Jonnala ***@***.***> wrote:  
 
 


@motilal76 please try with Tensorflow version 2.8.2. Thanks!

**Comment by hjonnala** [comment]
> /usr/local/lib/python3.8/dist-packages/keraslayers/convolutional.py:233 Error 'tf.Conv2D' op is neither a custom op nor a flex op

Does this error occur during tflite conversion, if so please check with tflite support team at: https://github.com/tensorflow/tflite-support

**Comment by motilal76** [comment]
Yes thats for conversion. What is the issue with 2.9.1 though? Seems like conversion goes through smoothly with that version but edgetpu_compiler bombs outMoti

    On Tuesday, July 26, 2022, 01:16:23 PM PDT, Hemanth-Jonnala ***@***.***> wrote:  
 
 



/usr/local/lib/python3.8/dist-packages/keraslayers/convolutional.py:233 Error 'tf.Conv2D' op is neither a custom op nor a flex op


Does this error occur during tflite conversion, if so please check with tflite support team at: https://github.com/tensorflow/tflite-support

**Comment by hjonnala** [comment]
> ERROR: Didn't find op for builtin opcode 'CONV_2D' version '6'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?

Current compiler uses [tflite runtime 2.5.0 post1](https://github.com/google-coral/py-repo). Please check if your tflite model is able to run [inference](https://github.com/hjonnala/snippets/blob/main/coral_inference.py) with this runtime. If not then you may try with lower version of tensorflow (e.g, 2.8, 2.7, 2.6, 2.5).
