### ISSUE TITLE
Tpu mpcie-version is not showing up

### ISSUE THREAD

**Issue by joriham** [google-coral/edgetpu#632]
### Description

I've a confirmed working Coral TPU, with Windows 11 and mpcie=>pcie adapter I can use the TPU for example to recognize the Parrot. So I think hardware is fine.

When I swap the same TPU to mini-pc with mini pci-e slot coral plugs in fine to physical port, but on Debian 11 OS with lspci -nn I cannot see any trace of 089a-device, nor in dmesg looking for PCI. 

Mini-PC is topton pfsense 6xlan firewall-model with AMI-bios. At BIOS VT-d is enabled and mini-pc with proxmox nicely sees other PCIe-devices like 6xLAN adapters and IOMMU-forwards to VM (Opnsense).

But for some reason this Coral TPU is not visible in host os (under proxmox). Like mPCIE is powered down as no trace of card at OS-level. Is there a BIOS setting or way to diagnose or fix the issue? I tried "wireless/bt wake-on LAN" enabled on BIOS if that powers it up but no success.

Topton-aliexpress -site says on product highlight: 
-1xSIM slot, 1xMPCIE wireless slot, support WiFi/3G/4G(3 choose 1) connection.

I know this is a long shot to write here on github if there is someone having similar problem and resolved it. As I see other similar type of issues here but with Coral dual TPU. And it seems that Toptop as manufactor of mini-pc does not know how to help, and AMI does not seem to have consumer support channel.

Image of my MB, showing Coral and bus marking MPCIE..
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/90329114/182121226-5f4ab348-da08-4b5b-ba27-7034fb5a9d18.png)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

Mini PCIe

### Relevant Log Output

```shell
# lspci -nn | grep -i 089a
#
```
</details>

**Comment by joriham** [comment]
Ok, via server the home -site I found manufactor changwang.com and there is some documentation of the motherboard. Naturally in Mandarin. With Google Lens I was able to make something out of it.

Basically it says:
Expansion slots:
1*Mini-PCIE slot support WIFI, 3G, 4G modules
1xM.2 slot, support PCIE signal, SSD hard disk module

**Note: MINIPE is USB signal, only supports USB signal module**

So is there anything doable about this USB-signal? Does Coral support it? How?

**Comment by joriham** [comment]
By anything I mean CoralTPU firmware upgrade etc

**Comment by magic-blue-smoke** [comment]
> Ok, via server the home -site I found manufactor changwang.com and there is some documentation of the motherboard. Naturally in Mandarin. With Google Lens I was able to make something out of it.
> 
> Basically it says: Expansion slots: 1*Mini-PCIE slot support WIFI, 3G, 4G modules 1xM.2 slot, support PCIE signal, SSD hard disk module
> 
> **Note: MINIPE is USB signal, only supports USB signal module**
> 
> So is there anything doable about this USB-signal? Does Coral support it? How?

@joriham 
mPCIe slot has USB interface on pins 36/38 and it's not multiplexed with PCIe signals. From [Mini PCIe Accelerator pictures](https://coral.ai/products/pcie-accelerator) I see that USB pins are physically missing
This means that slot is missing PCIe interface, Coral card is missing USB interface.
If you're not using m.2 slot, try to find adapter from m.2 to mPCIe, however with quick search I can only see those with m.2 E key, while you'd need B or M key

**Comment by joriham** [comment]
Thank you @magic-blue-smoke for full answer, so it is missing pins.

So I just wonder why the bus is not named separately, like "mpci-e" vs "mpci-usb" as if bus does not contain pci-express signals. Now it fools normal consumers.

Unfortunately M.2 is already occupied with MVNE drive so it cannot be used. So the mini pci-e was only free port on MB.
