### ISSUE TITLE
USB Accelerator not showing up

### ISSUE THREAD

**Issue by basilfx** [google-coral/edgetpu#633]
### Description

I just received my Coral USB Accelerator, but it does not seem to work.

When I plug it in, I don't see any `dmesg` or `lsusb` messages. Tried different cables (USB-C -> USB-C, USB-C -> USB3) and different systems (Linux, MacBook Pro, Raspberry Pi3). The on-board led also does not light up.

Did I receive a defective device? Is there anything else I can try?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux, Mac OS

### Coral Device

USB Accelerator

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @basilfx  If there is no issue with the USB cable and USB port then the device is defective. Please reach out to the original place of purchase to get this product replaced. Thanks!

**Comment by basilfx** [comment]
OK, thanks for your response. Was hoping for something I could try/did wrong, but I'll contact the seller and get it replaced.
