### ISSUE TITLE
Hi, Here are some log details with Linux Machine.

### ISSUE THREAD

**Issue by Boppel11** [google-coral/edgetpu#638]
Hi, Here are some log details with Linux Machine.

```
bash enable_lk_fastboot.sh
**********************************************************************
Unable to connect to debug board, check connection or manually toggle GPIO.
**********************************************************************
/tmp/tmp.A2frymb1B7 ~/Downloads/excelsior-eagle-20201210233645
INFO: pySerial version: (3.5)
INFO: Use config file: /tmp/tmp.A2frymb1B7/dl_addr.ini
INFO: Waiting to connect platform...
```

- At this point, please use a wire to connect the KPCOL0 test point to ground, as shown in figure 2. Ideally, use a female-to-male jumper wire, with the female end attached to pin 39 on the GPIO header (ground), and then hold the male end firmly on the test point.

-  While maintaining a firm connection with the jumper wire, carefully connect the USB data cable to the board's USB OTG port.

```
INFO: Got /dev/ttyACM0
INFO: Connect brom
INFO: Loading file: lk.bin
INFO: Send lk.bin
INFO: Jump da
~/Downloads/excelsior-eagle-20201210233645
```
If everything goes well, you should be able to see above logs and please follow the rest of the steps as described in the [docs](https://coral.ai/docs/dev-board-mini/reflash/#force-boot-into-fastboot-mode).

_Originally posted by @hjonnala in https://github.com/google-coral/edgetpu/issues/505#issuecomment-972943815_

So I'm trying to do this as well, but am not able to... It all works as hjonnala has written, but if I try to move on in the script, I can't. I already tried to connect to the serial console, but I can't get any information out of it...

Maybe someone has an idea to help me, I'm already chatting with the Coral Support, but I'm feeling like he can't help me... : (

**Comment by hjonnala** [comment]
Hello @Boppel11 have you tried with either LInux or MacOS host machine?

**Comment by Boppel11** [comment]
Thanks for your reply,
First I only tried with Win10 but dint come anywhere so I tried it with
MacOS, wich didnt work out as well so I've finally installed Linix Ubuntu,
and in it I can come to the point has benn described in your post.

Hemanth-Jonnala ***@***.***> schrieb am Fr. 5. Aug. 2022 um
15:55:

**Comment by Boppel11** [comment]
![image](https://user-images.githubusercontent.com/71565754/183108294-4c629bb1-a0c3-415b-bce5-dceb43f5c46d.png)
This is what was going on in the terminal, it just doesn't work the way described on the coral.ai website...

**Comment by hjonnala** [comment]
It seems fastboot is not installed. Please complete the first time setup: https://coral.ai/docs/dev-board-mini/reflash/#first-time-setup

**Comment by Boppel11** [comment]
![Screenshot from 2022-08-05 17-24-04](https://user-images.githubusercontent.com/71565754/183109672-9a9ba176-f4a9-400c-8eae-f1213d1cd032.png)
fastboot 28.0.2- debian is and was installed when trying... can I get another version of it?

**Comment by hjonnala** [comment]
Have you reload the udev rules, added your user name (florian) to the dialout and plugdev group and **[reboot](https://coral.ai/docs/dev-board-mini/reflash/#first-time-setup)** the machine?

```
sudo udevadm control --reload-rules && sudo udevadm trigger
sudo usermod -aG plugdev,dialout florian
```

**Comment by Boppel11** [comment]
I'm not sure if I had, but the top one definitely not... Now I have, but sadly I can't spot a single difference to before...

**Comment by hjonnala** [comment]
Please remove the fastboot and try the entire setup from scratch.

- sudo apt-get purge fastboot
- https://coral.ai/docs/dev-board-mini/reflash/#first-time-setup
- https://coral.ai/docs/dev-board-mini/reflash/#force-boot-into-fastboot-mode

**Comment by Boppel11** [comment]
Update: I have done:
sudo apt-get purge fastboot
sudo apt-get install fastboot
sudo udevadm control --reload-rules && sudo udevadm trigger
sudo usermod -aG plugdev,dialout florian

then checked if all Python packages are still installed so:
python3 -m pip install pyftdi pyserial
python3 -m pip install --user mendel-development-tool

and then I rebooted and tried to force into fastboot mode as I always did but I can't see a difference...

**Comment by hjonnala** [comment]
I have seen users having issues to fastboot with Ubuntu. Which Ubuntu version are you using? Are you trying to do fastboot on native LInux host Machine or on a virtual machine installed on win 10?

https://github.com/google-coral/edgetpu/issues/620
https://github.com/google-coral/edgetpu/issues/505#issue-1056967225

**Comment by Boppel11** [comment]
I'm using Ubuntu 20.04 installed beside my Win10, but not virtual machine...  Can you recommend another version of Linux? I'm only using it for that one project...

**Comment by hjonnala** [comment]
I have the below OS on my Linux machine.

$ uname -a
Linux  5.17.11-1rodete2-amd64 #1 SMP PREEMPT Debian 5.17.11-1rodete2 (2022-06-09) x86_64 GNU/Linux

**Comment by Boppel11** [comment]
I couldn't find the version 5.17.11, so I'm now installing debian version-11.4.0 let's hope it works, thanks for the recommandation!

**Comment by Boppel11** [comment]
Debian version-11.4.0 is now installed, and I've done the first time setup again, installed the python packages, and tried to forceboot, but no success again...

**Comment by hjonnala** [comment]
Wondering if you have [Raspberry pI 4b](https://www.raspberrypi.com/products/raspberry-pi-4-model-b/) as I am able to forceboot Dev Board Mini with this device also.
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
```

**Comment by Boppel11** [comment]
Thank you so much hjonnala for your help, a friend of mine was able to help me and the board is now running as expected.
