### ISSUE TITLE
Power Coral Dev Board Mini over GPIO Pins

### ISSUE THREAD

**Issue by Boppel11** [google-coral/edgetpu#640]
### Description

I'm not sure if I can power the board over the board over the GPIO Pins...

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install, Feature Request

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Programming Language

Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Yes, You can power the Dev Board Mini by connecting a DC power supply to the 5 V pins on the GPIO header. Please check page 13 for board operation at: https://coral.ai/static/files/Coral-Dev-Board-Mini-datasheet.pdf
