### ISSUE TITLE
Environmental Sensor Board Inaccurate Readings

### ISSUE THREAD

**Issue by Abdol** [google-coral/edgetpu#642]
Hello,

I’d like to report strange reading taken from the Environmental Sensor Board attached to the Coral Dev Board. Using the official sample code provided, the temperature, humidity and luminosity readings were significantly less accurate than reported in the tech specs. 

Below is a table of comparison between the Environmental Sensor Board and reference meters. I haven’t tested barometric pressure. I have also attached a photo of the setup.

![IMG_9486 copy](https://user-images.githubusercontent.com/365168/184621596-e85abd1d-50b4-45cb-98a8-d02bbb40afe2.jpg)

I layout the steps I took to produce the error, following normal procedure of operating the CORAL Environmental Sensor Board:

1. Followed this guide: https://coral.ai/docs/enviro-board/get-started/ (steps 1, 2, and 3)
2. Placed the CORAL Environmental Sensor Board using header extenders (see attached photo)
3. Modified the code to send readings to Firebase Database ([link to code](https://github.com/Abdol/firebase-test/blob/main/firebase_test_coral.py))
4. Ran the code continuously for more than 24 hours in an office environment
5. Obtained the below validation results with respect to reference meters [ThermoPro TP52](https://www.amazon.co.uk/gp/product/B07TW3NL2M/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1) and 
6. ‎[V·RESOURCING W-U113](https://www.amazon.co.uk/gp/product/B07NRWCSB6/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1) using the following equation: relative error = | (reference value - measured value) / reference value | * 100:

- Parameter	CORAL Sensor Accuracy
- Temperature	±26.57%
- Humidity	±11.85%
- Ambient Light Level	±57.3%

As you can see, the light level sensor gives almost twice as high as the reference value. 

I have [linked here](https://www.dropbox.com/s/no12ofzfbrfafjt/energy-lab-1-default-rtdb-coral_dmu-export.json?dl=0) the data as a Firebase Database JSON file, where it sorted by a UNIX timestamp key. This file shows data collected and displayed on the CORAL.

I have tested the Environmental Board on 3 different locations (i.e. two labs and an apartment). Moreover, I have verified the values with a thermocouple as well as the mentioned ThermoPro TP52. In all settings, the Environmental Board showed non-minimal discrepancies as discussed in the previous email.

I'd appreciate your assistance in identifying the issue at hand (hardware/software) and resolve it. I'm using the above setup for a research project.

**Comment by hjonnala** [comment]
Hello @Abdol , temp inaccuracy could be due to the Enviro sensor board is above the heat sink. Can you please try to check the accuracy by connecting the sensor board via ribbon cable. Thanks!

Ribbon cable: https://www.amazon.com/dp/B07D991KMR?psc=1&ref=ppx_yo2ov_dt_b_product_details

![20220823_133006](https://user-images.githubusercontent.com/86132058/186277902-5eb726fc-df91-4487-b84c-ce4419a89834.jpg)

**Comment by Abdol** [comment]
Thanks @hjonnala for the suggestion. I'll update you once I get my hands on a ribbon cable.

**Comment by hjonnala** [comment]
Feel free to reopen if you still have any questions here. Thanks!

**Comment by Abdol** [comment]
Thanks @hjonnala. Using the ribbon cable improved the readings' accuracy. Having tested this on two Environmental Sensor Boards, one of the boards worked fine and the other continued displaying faulty readings. 

I would suggest including this tip, i.e., _connecting the Environmental Sensor Boards to a ribbon cable to mitigate board heating effect rather than a header_, in the sensor's [getting started page](https://coral.ai/docs/dev-board/get-started) page.  It may help others troubleshoot such issues.
