### ISSUE TITLE
Edge TPU Compilation Error

### ISSUE THREAD

**Issue by sairaghava7** [google-coral/edgetpu#643]
I'm trying to compile a tifle model so that I can use it on an edge device, which is the error I'm getting. Does anyone know anything about it?

Edge TPU Compiler version 16.0.384591198
/usr/bin/edgetpu_compiler: line 3:  1531 Segmentation fault      (core dumped) ${d}/edgetpu_compiler_bin/ld-linux-x86-64.so.2 --library-path ${d}/edgetpu_compiler_bin ${d}/edgetpu_compiler_bin/edgetpu_compiler "$@"

**Comment by hjonnala** [comment]
Please try to compile the tflite model with this colab: https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb

**Comment by hjonnala** [comment]
Hi @sairaghava7  are you still having the issue with the compiler?

**Comment by sairaghava7** [comment]
The issue has been resolved. Thanks!

**Comment by imanring** [comment]
I tried using the Colab notebook provided and got the same problem.

```Edge TPU Compiler version 16.0.384591198
/usr/bin/edgetpu_compiler: line 3:  7056 Segmentation fault      (core dumped) ${d}/edgetpu_compiler_bin/ld-linux-x86-64.so.2 --library-path ${d}/edgetpu_compiler_bin ${d}/edgetpu_compiler_bin/edgetpu_compiler "$@"```

**Comment by bkurianAIML** [comment]
**Segmentation Fault When Compiling Quantized TFLite File with Edge TPU Compiler**

I am encountering a segmentation fault error when trying to compile a quantized TFLite file using the Edge TPU Compiler
(collab : https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb#scrollTo=joxrIB0I3cdi) 

**Here are the details of the error message:**

**_Edge TPU Compiler version 16.0.384591198
/usr/bin/edgetpu_compiler: line 3:  2227 Segmentation fault      (core dumped) ${d}/edgetpu_compiler_bin/ld-linux-x86-64.so.2 --library-path ${d}/edgetpu_compiler_bin ${d}/edgetpu_compiler_bin/edgetpu_compiler "$@"_**


**Troubleshooting Steps Taken:**

I have tried refreshing the page and reloading the TFLite file.
I ran the notebook again, which has resolved similar issues in the past, but the segmentation fault persists this time.

Thank you for your assistance!

**UPDATE ON SEGMENTATION FAULT**:
**Solution**:
I was able to successfully run the compiler by waiting for the TFLite file to fully load before attempting to compile it. Here’s what worked for me:

1. **Upload the TFLite file**: Click the upload button and wait for the blue loading symbol to finish.
2. **Avoid refreshing prematurely**: Initially, I would refresh the page to see the file, but this time I waited until the upload was fully completed.
3. **Compile the file**: After ensuring the file was fully loaded, I changed the file name(example) and ran all cells in the notebook.

This approach resolved the segmentation fault, and the compilation was successful. I don't know whether that was the issue, but this time that solved my problem.

![all](https://github.com/google-coral/edgetpu/assets/170564695/25510822-20ac-417f-a614-fed7eed1c260)
