### ISSUE TITLE
Allowing multiple users use a single loaded model on CORAL TPU

### ISSUE THREAD

**Issue by aslanpour** [google-coral/edgetpu#645]
Hi, I just ran an object detection using the prebuilt SSD Mobilenet v1 model on the CORAL TPU device. It is working perfectly as a python code in a Flask framework.
Then, I turned the code into containers. Once the container runs, it loads the model to the TPU device and sets an interpreter variable. That is also fine and just needs some access to USB and stuff.
However, I would like to run multiple replicas of my container and all of them can send images to the model loaded in the TPU device because all of them need the same model. I tried running the second container exactly, and once it runs, it gets access to the TPU device and sets its interpreter variable, and ready to go. However, this causes the previous container to fail with this error
```
2022/08/17 23:49:51 stderr: F driver/usb/usb_driver.cc:1148] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]
2022/08/17 23:49:51 Forked function has terminated: signal: aborted (core dumped)
```

It seems only one process can access the TPU device. I am wondering how I can let the second container use the TPU without kicking the senior one off. At least, I would like a solution for the senior container to tolerate this failure and not crash. I mean I need a way to catch this error so the senior container does not fail.

**Comment by dmitriykovalev** [comment]
Hi @aslanpour, TPU device is not designed to be (easily) shared between several processes or containers. As an option you can try to implement client/server architecture, i.e. server owns the TPU device and handles inference requests from multiple clients. Otherwise you need some mechanism to implement mutual exclusion between containers (e.g. you could try file system locks).
