### ISSUE TITLE
Coral Dev Board + Raspberry Pi "Build Hat" (Lego)

### ISSUE THREAD

**Issue by MrGibbage** [google-coral/edgetpu#648]
### Description

I am trying to use the "Raspberry Pi Build Hat"
https://www.raspberrypi.com/documentation/accessories/build-hat.html
with my dev board. This build hat has ports for connecting lego motors and sensors. The problem is, when I have the hat mounted on the dev board, it doesn't boot up. The fan comes on, the red LED comes on, but I can't mdt in to the board and nothing comes out of the hdmi port. I have tried powering it from the hat and from the dev board, and  neither worked.

Anyway, from the hat docs it says this:
The following pins are used by the Build HAT itself and you should not connect anything to them.

        GPIO    | Use      | Status
       ---------|----------|---------
        GPIO0/1 | ID prom  |  
        GPIO4   | Reset    |  
        GPIO14  | Tx       |  
        GPIO15  | Rx       |  
        GPIO16  | RTS      | unused
        GPIO17  | CTS      | unused

So before I go cutting pins (not a big deal since I have to use a header extension anyway), I would like to know if that truly is what I need to do. I want to be able to control some lego motors with the hat, and if I cut all of those pins, I don't think I'll be able to do that. Correct? Thoughts?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

Other

### Relevant Log Output

```shell
Could not get any logs because the board won't boot up when I have the build hat installed.
```
</details>

**Comment by hjonnala** [comment]
We don't think RPI PI hat is supported because Dev Board pins doesn't really match with the pi hat. Please check with RPI community also if he anyone has tried it: https://forums.raspberrypi.com/search.php?keywords=coral
