### ISSUE TITLE
Compile Errors EfficientDet Lite 3 and EfficientDet Lite 4: Compilation failed due to large activation tensors in model

### ISSUE THREAD

**Issue by ghbn8** [google-coral/edgetpu#651]
### Description

I am attempting to compile Tensorflow Hub EfficientDet Lite models [https://tfhub.dev/s?deployment-format=lite&module-type=image-object-detection&tf-version=tf2](url) using the Google Colab notebook provided by Google [https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb](url) -- and I am receiving the following error from the Colab notebook when attempting to convert EfficientDet Lite 3 and EfficientDet Lite 4 models:

_Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed!_

It's my impression that EfficientDet Lite 3 and 4 models are designed to run on the Google Coral Edge TPU (after compiling), am I incorrect?

These are the models directly from the TF Hub website with no modifications at all. This error ONLY happens for EfficientDet Lite 3 and 4 models, EfficientDet Lite 0, 1, 2 compile without an issue.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Windows 10

### Coral Device

USB Accelerator

### Other Devices

Raspberry Pi 3

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @ghbn8 please try to compile the models with -d and -a flags.

`edgetpu_compiler -s -d -a  lite-model_efficientdet_lite3_detection_metadata_1.tflite `

**Comment by ghbn8** [comment]
@hjonnala thanks for the rapid response. The model successfully compiled with the recommended flags, and it runs on the raspi without error. 

What are these flags doing? It appears that the command is reducing the number of operations (ops) to be performed on the TPU until it successfully compiles -- it took four attempts to compile (removing four ops)?

**Here is the output for reference:**
_Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 1
Try to compile segment with 424 ops
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 423 ops
Intermediate tensors: tfl.dequantize,Sigmoid1
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 422 ops
Intermediate tensors: concat_1,Sigmoid1
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 421 ops
Intermediate tensors: Reshape_1,Reshape_5,Reshape_9,Reshape_3,Reshape_7,Sigmoid1
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 420 ops
Intermediate tensors: box_net/box-predict/BiasAdd;box_net/box-predict/separable_conv2d_4;box_net/box-predict/separable_conv2d;box_net/box-predict/bias,Reshape_9,Reshape_5,Reshape_7,Reshape_3,Sigmoid1
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 6961 ms.

Input model: efficientdet_lite3.tflite
Input size: 11.40MiB
Output model: efficientdet_lite3_edgetpu.tflite
Output size: 14.39MiB
On-chip memory used for caching model parameters: 7.04MiB
On-chip memory remaining for caching model parameters: 2.25KiB
Off-chip memory used for streaming uncached model parameters: 5.43MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 424
Operation log: efficientdet_lite3_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 414
Number of operations that will run on CPU: 10

Operator                       Count      Status

RESHAPE                        1          More than one subgraph is not supported
RESHAPE                        6          Mapped to Edge TPU
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  1          More than one subgraph is not supported
CONCATENATION                  1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CUSTOM                         1          Operation is working on an unsupported data type
ADD                            83         Mapped to Edge TPU
MAX_POOL_2D                    26         Mapped to Edge TPU
DEQUANTIZE                     2          Operation is working on an unsupported data type
QUANTIZE                       1          Mapped to Edge TPU
CONV_2D                        152        Mapped to Edge TPU
DEPTHWISE_CONV_2D              122        Mapped to Edge TPU
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESIZE_NEAREST_NEIGHBOR        24         Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded!_

**Comment by hjonnala** [comment]
> What are these flags doing? It appears that the command is reducing the number of operations (ops) to be performed on the TPU until it successfully compiles -- it took four attempts to compile (removing four ops)?

yes, your understanding is correct. Please check the detailed usage of flags at: https://coral.ai/docs/edgetpu/compiler/#usage

-a flag is not listed there as it is an experimental flag. It enables multiple subgrpahs (Mutiple `edgetpu-custom-op` in edgetpu model if required, and you can visualize the model using https://netron.app/).

**Comment by Plessen** [comment]
Ran into this exact same issue. I see @ghbn8 compiled it for a single edge tpu, even though the minimum required for efficientdet3 and 4 is 2 edges. This solution does not hold for --num_segments = 2. @hjonnala

**Comment by Arslan-Mehmood1** [comment]
@hjonnala  Hi , could you please share the inference speed after your model was compiled successfully for EdgeTpu..?
