### ISSUE TITLE
Quantization and conversion from an LSTM model

### ISSUE THREAD

**Issue by johannesheid** [google-coral/edgetpu#654]
hey, i'm working on a model to predict a sensor signal. The last 50 values are used to predict the next 15.

I want to run this model on a TPU from Coral, but I get the following error message from the coverter after the INT8 qunatization of the model:

```
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter.
Compilation child process completed within timeout period.
Compilation failed!
```

But I don't know where these dynamic tensors should be included and how I can eliminate them. Before the qunatization I set the batch size to 1 to prevent dynamic tensors, but it seems that this is not enough.
![summary_sensorvalues](https://user-images.githubusercontent.com/49682611/188659597-c273eab1-0170-4836-87f5-3c594f48c291.PNG)

I have followed the weather forecasting example a lot and there it works without problems. I don't know where the difference to my model would be, except for the input and output. I insert here the model levels of the two models.
![weather_forecasting](https://user-images.githubusercontent.com/49682611/188661337-b8392c65-87e9-48cb-b0f1-0053fa24d12e.png)

![own_sensor_model](https://user-images.githubusercontent.com/49682611/188649071-6d30737d-5a38-4f4c-aa70-a374ad50f03b.png)

why is the LSTM layer broken into such subsets and is that the problem with the conversion?

Now the code from the creation of the model and the quantization:

```
inputs=keras.layers.Input(shape=(train_x.shape[1], train_x.shape[2]))
lstm_out= keras.layers.LSTM(50, activation='relu')(inputs)
dense1_out= keras.layers.Dense(50, activation='relu')(lstm_out)
outputs = keras.layers.Dense(num_Label)(dense1_out)

model = keras.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='adam', loss='mae')
model.summary()

history = model.fit(train_x, train_Y_arr, epochs=10, batch_size=128, 
                    validation_data=(test_x, test_Y_arr),verbose=1,
                    shuffle = False)

#plot history
plt.plot(history.history['loss'], label='train')
plt.plot(history.history['val_loss'], label='test')
plt.legend()
plt.show()
```

```
#ouputshape = (1,50,1)
def rep_data_set():
  for i in range(len(train_x[:1000,0,0])):           #the first 1000 because it runs too long
    input_data = train_x[i].reshape(1, -1, 1)
    input_data = tf.cast(input_data, dtype=tf.float32)
    yield [input_data]

batch_model = load_model('/content/drive/MyDrive/ColabNotebooks/my50in15out_TPU_test1.h5')
batch_size=1
batch_model.input.set_shape((batch_size,)+batch_model.input.shape[1:])

batch_model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(batch_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = rep_data_set
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS, tf.lite.OpsSet.TFLITE_BUILTINS_INT8] 
converter.target_spec.supported_types = [tf.int8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
quant_model = converter.convert()
```
another problem I noticed is that depending on how much data I use for the representative dataset, the prediction of my model changes completely. How can I avoid or work around this?

I hope I have shared all the relevant info and someone can help me.

I worked all the time with google colab

**Comment by hjonnala** [comment]
Hi @johannesheid  can you please share the tflite model that you are trying to compile. Thanks!

**Comment by johannesheid** [comment]
of course
here is the initial model and the tflite model with quantization
[sensor_models.zip](https://github.com/google-coral/edgetpu/files/9500669/sensor_models.zip)

**Comment by hjonnala** [comment]
> ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

Your model has a while loop (dynamic sized tensor), because of that compiler is failing to compile.

> lstm_out= keras.layers.LSTM(50, activation='relu')(inputs)

can you  try with tanh activation layer here.

**Comment by johannesheid** [comment]
yes, it helped to quantize the lstm layer as desired, however the conversion with the edgetpu compiler still does not succeed:
![new_quant_model](https://user-images.githubusercontent.com/49682611/188858807-7fac9aea-a33f-47e1-bcc8-96e11e492580.PNG)


```
! edgetpu_compiler /content/drive/MyDrive/ColabNotebooks/tanh_50in15out_quant_fulldata.tflite
```
```
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
Compilation child process completed within timeout period.
Compilation failed!
```
[sensor_model_tanh.zip](https://github.com/google-coral/edgetpu/files/9505426/sensor_model_tanh.zip)

now i don't understand at all why it doesn't compile. There is not even reasonable error message

is there a reason why the conversion of a lstm layer with relu activation does not work?

by the way thanks for the quick response

**Comment by hjonnala** [comment]
> is there a reason why the conversion of a lstm layer with relu activation does not work?

I suggested to try with tanh as its the default one as per the documentation: https://keras.io/api/layers/recurrent_layers/lstm/. Regarding quantization and conversion issues please check with tflite support team at: https://github.com/tensorflow/tflite-support

> now i don't understand at all why it doesn't compile. There is not even reasonable error message

LSTM layers has limitations with input shape and/or the number of units. We don't find  any concrete limits to document these limitations. I am able to compile your model changing number units to 60.

```
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import numpy as np


# inputs=keras.layers.Input(shape=(inputs.shape[1], inputs.shape[2]))
shape = (50, 1)
inputs=keras.layers.Input(shape=(shape[0], shape[1]))
lstm_out= keras.layers.LSTM(60, activation='tanh')(inputs)
dense1_out= keras.layers.Dense(50, activation='relu')(lstm_out)
outputs = keras.layers.Dense(15)(dense1_out)

model = keras.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='adam', loss='mae')
model.input.set_shape((1,) + model.input.shape[1:])
print(model.summary())

def representative_data_gen():
    for i in range(10):
        yield [np.random.random((1, shape[0], shape[1])).astype(np.float32)]
converter = tf.lite.TFLiteConverter.from_keras_model(model)
# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# This sets the representative dataset for quantization
converter.representative_dataset = representative_data_gen
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# For full integer quantization, though supported types defaults to int8 only, we explicitly declare it for clarity
converter.target_spec.supported_types = [tf.int8]
# These set the input and output tensors to int8
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model_quant = converter.convert()

with open('weather_forecast_quant.tflite', 'wb') as f:
  f.write(tflite_model_quant)
```

**Comment by johannesheid** [comment]
ok with 60 layer it worked. Then I have to see what number of layers is best for my case and can be compiled too. Thank you very much for the help. I will first see myself if I can control the influence of the representative dataset. If not, i will contact tflite-support.
