### ISSUE TITLE
Compiled version of EfficientDetLite 1 too slow

### ISSUE THREAD

**Issue by caiomapzer** [google-coral/edgetpu#656]
### Description

Hello :)

I tried to follow the [colab tutorial](https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb) to retrain the EfficientDet Lite 1 detector.

I just changed the following line of code:
```spec = object_detector.EfficientDetLite0Spec()```
to
```spec = object_detector.EfficientDetLite1Spec()```

After trying to compile the model with the follow `-d` argument:
!edgetpu_compiler $TFLITE_FILENAME -d --num_segments=1

I get:
```
Try to compile segment with 295 ops
Intermediate tensors: Reshape_5,Reshape,cell_2/fnode7/op_after_combine12/bn/FusedBatchNormV3;cell_2/fnode7/op_after_combine12/bn/FusedBatchNormV3;fpn_cells/cell_2/fnode7/op_after_combine12/conv/bias;cell_2/fnode7/op_after_combine12/conv/BiasAdd;cell_2/fnode7/op_after_combine12/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_2/fnode7/op_after_combine12/conv/separable_conv2d;cell_2/fnode7/op_after_combine12/conv/separable_conv2d,Reshape_4,Reshape_3,Reshape_7,Reshape_2,Reshape_6,Reshape_1,cell_3/fnode7/resample_1_11_12/max_pooling2d_15/MaxPool;cell_3/fnode7/resample_1_11_12/max_pooling2d_15/MaxPool
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 2671 ms.

Input model: efficientdet-lite-salad.tflite
Input size: 5.67MiB
Output model: efficientdet-lite-salad_edgetpu.tflite
Output size: 6.55MiB
On-chip memory used for caching model parameters: 5.21MiB
On-chip memory remaining for caching model parameters: 2.29MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 322
Operation log: efficientdet-lite-salad_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 191
Number of operations that will run on CPU: 131
See the operation log file for individual operation details.
Compilation child process completed within timeout period.
Compilation succeeded! 
```

The problem is that the model is taking more than 600ms per inference by using an image with 384x307 resolution.

I noticed by using [Netron](https://netron.app/) that the Efficient Det Lite 1 Coral model available [here](https://coral.ai/models/object-detection/) has a different architecture if compared to the compiled model using the command `!edgetpu_compiler $TFLITE_FILENAME -d --num_segments=1`.

What would be the process to analyze the model's architecture to avoid this number of operations being transferred to the CPU?
I'm following the same colab tutorial available on the site. There is something wrong?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance, Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Relevant Log Output

```shell
Try to compile segment with 295 ops
Intermediate tensors: Reshape_5,Reshape,cell_2/fnode7/op_after_combine12/bn/FusedBatchNormV3;cell_2/fnode7/op_after_combine12/bn/FusedBatchNormV3;fpn_cells/cell_2/fnode7/op_after_combine12/conv/bias;cell_2/fnode7/op_after_combine12/conv/BiasAdd;cell_2/fnode7/op_after_combine12/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_2/fnode7/op_after_combine12/conv/separable_conv2d;cell_2/fnode7/op_after_combine12/conv/separable_conv2d,Reshape_4,Reshape_3,Reshape_7,Reshape_2,Reshape_6,Reshape_1,cell_3/fnode7/resample_1_11_12/max_pooling2d_15/MaxPool;cell_3/fnode7/resample_1_11_12/max_pooling2d_15/MaxPool
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 2671 ms.

Input model: efficientdet-lite-salad.tflite
Input size: 5.67MiB
Output model: efficientdet-lite-salad_edgetpu.tflite
Output size: 6.55MiB
On-chip memory used for caching model parameters: 5.21MiB
On-chip memory remaining for caching model parameters: 2.29MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 322
Operation log: efficientdet-lite-salad_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 191
Number of operations that will run on CPU: 131
See the operation log file for individual operation details.
Compilation child process completed within timeout period.
Compilation succeeded!
```
</details>

**Comment by hjonnala** [comment]
Compiler fails to compile due to large activation tensors mostly due to transpose and/or reshape operations. At that time please try to visualize the tflite model with netron and pass the name of reshape (with max input shape) as [intermediate tensor](https://coral.ai/docs/edgetpu/compiler/#usage) to the compiler. 

Please try the command below to map max operations to edgeTPU. 

`!edgetpu_compiler  -i "class_net/class-predict/BiasAdd;class_net/class-predict/separable_conv2d_4;class_net/class-predict/separable_conv2d;class_net/class-predict/bias" efficientdet-lite-salad.tflite`

![image](https://user-images.githubusercontent.com/86132058/189434194-a27905b9-1be6-4fd2-9ce2-01ba7d14e9e3.png)

![image](https://user-images.githubusercontent.com/86132058/189434841-a76b41c1-3848-4b53-a189-f08855caf8ed.png)

**Comment by caiomapzer** [comment]
Hello @hjonnala, thank you for answering :)

How do I know that these intermediate tensors are the ones I need to pass to the compiler in order to compile successfully?
"class_net/class-predict/BiasAdd;class_net/class-predict/separable_conv2d_4;class_net/class-predict/separable_conv2d;class_net/class-predict/bias"

The reason is that this is the largest operation (1x20736x90)?

**Comment by hjonnala** [comment]
> How do I know that these intermediate tensors are the ones I need to pass to the compiler in order to compile successfully? "class_net/class-predict/BiasAdd;class_net/class-predict/separable_conv2d_4;class_net/class-predict/separable_conv2d;class_net/class-predict/bias"
> 
> The reason is that this is the largest operation (1x20736x90)?

This script might help you to choose the intermediate tensors: https://github.com/hjonnala/snippets/blob/main/compiler/intermediate_serach_compilation.ipynb. In future, if it doesn't help please create a github issue. Thanks!
