### ISSUE TITLE
which IP address to use to view demo?

### ISSUE THREAD

**Issue by ilonadem** [google-coral/edgetpu#658]
### Description

I am connecting to the google coral from my Mac computer via a micro usb and connecting the coral itself to a power source (note: NOT using mdt). 

I'm trying to run the demo app as in step 7 of https://coral.ai/docs/dev-board/get-started/, and when I run `edgetpu_demo --stream`, I see: 

```Press 'q' to quit.
Press 'n' to switch between models.
INFO:edgetpuvision.streaming.server:Listening on ports tcp: 4665, web: 4664, annexb: 4666
```

The instructions on the google coral website I linked above say "Then on your desktop (that's connected to the Dev Board)—if you're connected to the board [using MDT over USB](https://coral.ai/products/dev-board/#2-connect-to-the-boards-shell-via-mdt)—open [192.168.100.2:4664](http://192.168.100.2:4664/) in a browser. If you're instead connected to the board by other means (such as SSH over LAN or with an Ethernet cable), type the appropriate IP address into your browser with port 4664."
Is there somewhere I can find which IP address to use to connect to see the demo? Or do I need to connect the board to a monitor to see anything? 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install, Support, Documentation Bug

### Operating System

Mendel Linux, Mac OS

### Coral Device

Dev Board

### Relevant Log Output

```shell
Press 'q' to quit.
Press 'n' to switch between models.
INFO:edgetpuvision.streaming.server:Listening on ports tcp: 4665, web: 4664, annexb: 4666
```
</details>

**Comment by hjonnala** [comment]
please get the ip address with the below command:

- ip addr | grep wlan

**Comment by ilonadem** [comment]
Which of these would say the IP address?
```
mendel@arid-quill:~/coral/project-posenet$ ip addr | grep wlan
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 3000
```

**Comment by hjonnala** [comment]
Please try connecting to the [wifi](https://coral.ai/docs/dev-board/get-started/#connect-internet) first and then try to get the ip address.

mendel@arid-pig:~$ ip addr | grep wlan
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
    inet **192.168.7.160**/24 brd 192.168.7.255 scope global dynamic noprefixroute wlan0lan0
    
 In the above output 192.168.7.160 is the ip address of the board,

**Comment by ilonadem** [comment]
Having my device connected to wifi I get: 

```
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
    inet 172.20.10.9/28 brd 172.20.10.15 scope global dynamic noprefixroute wlan0
```

So if my IP address is 172.20.10.15, and when I run the edgetpu demo I get the output "INFO:edgetpuvision.streaming.server:Listening on ports tcp: 4665, web: 4664, annexb: 4666", is 172.20.10.15:4664 the right website to put into the chrome browser? When I do, chrome cannot load the page saying 
<img width="810" alt="Screen Shot 2022-09-16 at 10 55 32 AM" src="https://user-images.githubusercontent.com/69218138/190668730-c658df48-a4ae-4a2e-82e2-e1dbdf18ad95.png">

Also, does the device need to be on the same network as the computer, generally? (right now they are on the same network).

**Comment by hjonnala** [comment]
yes, the device and and the computer has to be on the same network..Please try 172.20.10.9:4664

**Comment by ilonadem** [comment]
Got it! Thank you so much :) 

If I want to run a standard python program and have my computer be the monitor, is all I need to do just append "--stream" to whichever bash script or python file that I run?

**Comment by hjonnala** [comment]
> If I want to run a standard python program and have my computer be the monitor, is all I need to do just append "--stream" to whichever bash script or python file that I run?

Unfortunately, I don't understand the ask here. Please try what you are trying to do and let us know if you are facing any issues with it.

**Comment by ilonadem** [comment]
No worries!

The idea is to be able to run a script (for example https://github.com/google-coral/project-posenet/blob/master/pose_camera.py) and view what is normally on the monitor without the monitor, as a link I could put into chrome. Right now I have an HDMI cable connecting the coral to a separate monitor. Would it be possible to do something like in the edgetpu_demo and view the visual output on an IP address in the browser?  

I haven't been able to figure out a way to send what is sent to the monitor to an IP address instead.

**Comment by hjonnala** [comment]
Please check the source code of edgetpuvision at :https://coral.googlesource.com/edgetpuvision/ and make the necessary changes to your script to send the video to an IP address.. Thanks!

**Comment by ilonadem** [comment]
I'm a little new to gstreamer, so would I just have to change the address of where the video is being sent? So for example if I wanted to modify this demo (https://github.com/google-coral/project-posenet/blob/master/pose_camera.py) to be able to view it on a streaming server, would I have to add a different argument into gstreamer.run_pipeline in line 122? Or would this change have to be executed elsewhere?

**Comment by ilonadem** [comment]
or alternatively, should I write a bash script that calls pose_camera.py followed by a line that sets up a web server stream? e.g. something like 
```
SERVER_INDEX_HTML="${TEST_DATA}/index.html" edgetpu_detect_server \
      --source "${VIDEO_STREAM_FILE}" \
      --model "${TPU_MODEL_FILE},${CPU_MODEL_FILE}" \
      --labels "${LABELS_FILE}" \
      --filter car,truck \
      --max_area 0.1 \
      --color white \
      --loop
```
at least as far as I understand this is how the edgetpu_detect demo (https://coral.googlesource.com/edgetpudemo/) does it.

**Comment by hjonnala** [comment]
closing the issue here. As we have another issue opened for the same at: https://github.com/google-coral/project-posenet/issues/88
