### ISSUE TITLE
Does coral work with 2 cameras on Raspberry Pi

### ISSUE THREAD

**Issue by kahlenberg** [google-coral/edgetpu#662]
Hi,
Because it is very difficult to get help from coral (you have to fill a long form on google docs) I want to ask here:
Does coral support two cameras for stereo vision?
If I connect 2 cameras to CM4IO board and coral to USB3, does it work?

**Comment by hjonnala** [comment]
Hi @kahlenberg could you please elaborate your use case for stereo vision with Coral? Do you have any tflite model that works with the current setup?

**Comment by kahlenberg** [comment]
Hi,
I don't have any setup yet. I want to make a project with stereo camera for depth estimation.
I wonder if it is possible with coral and two raspberry cameras.

**Comment by hjonnala** [comment]
I think, its possible if your your project uses int8 tflite model as [Coral USB accelerator](https://coral.ai/docs/accelerator/get-started/) used to  run [edgeTPU models](https://coral.ai/docs/edgetpu/models-intro/#model-requirements)  ([int8 tflite models](https://www.tensorflow.org/lite/performance/post_training_integer_quant) that are compiled with [compiler](https://coral.ai/docs/edgetpu/compiler/)) for high-speed machine learning inferencing.
