### ISSUE TITLE
Edge TPU performance for various models on dev board

### ISSUE THREAD

**Issue by gsirocco** [google-coral/edgetpu#663]
### Description

I have a simple model that I've been able to run on the deb board that utilizes the edge TPU and have benchmarked it's performance running it 1000 times and averaging. It's getting ~300us/Invoke. I have a more complicated model that has some operations that are able to be mapped to the edge TPU but not all. Its average is ~74ms/Invoke. I was looking to make this more along the lines of ~1-2ms/Invoke if possible and wanted any advice on what could be done either model or hw wise to better the performance. It's not clear if the bottleneck would be data transfer between the cpu and tpu, or the amount of operations being done on the cpu, something else, or a combination of these. Any help or suggestions are greatly appreciated. Thanks!

**I have put the simple and complicated model compiler conversion and TFLite model analyzer output in the output log section**

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

C++

### Relevant Log Output

```shell
Here is the simple model compiler conversion and TFLite model analyzer output:
==============================================================================

'$ edgetpu_compiler -s testmodel.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 79 ms.

Input model: testmodel.tflite
Input size: 1.03KiB
Output model: testmodel_edgetpu.tflite
Output size: 20.59KiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 8.12MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 1
Operation log: testmodel_edgetpu.log

Operator                       Count      Status

ADD                            1          Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded!'

'
=== TFLite ModelAnalyzer ===

Your TFLite model has '1' subgraph(s). In the subgraph description below,
T# represents the Tensor numbers. For example, in Subgraph#0, the ADD op takes
tensor #0 and tensor #1 as input and produces tensor #2 as output.

Subgraph#0 main(T#0) -> [T#2]
  Op#0 ADD(T#0, T#1) -> [T#2]

Tensors of Subgraph#0
  T#0(serving_default_dummy_input:0) shape_signature:[-1, 32], type:INT8
  T#1(model/tf.math.add/Add/y) shape:[], type:INT8 RO 1 bytes
  T#2(PartitionedCall:0) shape_signature:[-1, 32], type:INT8


Your model looks compatibile with GPU delegate with TFLite runtime version 2.9.1.
But it doesn't guarantee that your model works well with GPU delegate.
There could be some runtime incompatibililty happen.
---------------------------------------------------------------
Your TFLite model has ‘1’ signature_def(s).

Signature#0 key: 'serving_default'
- Subgraph: Subgraph#0
- Inputs:
    'dummy_input' : T#0
- Outputs:
    'tf.math.add' : T#2

---------------------------------------------------------------
              Model size:       1056 bytes
    Non-data buffer size:        951 bytes (90.06 %)
  Total data buffer size:        105 bytes (09.94 %)
    (Zero value buffers):          0 bytes (00.00 %)

* Buffers of TFLite model are mostly used for constant tensors.
  And zero value buffers are buffers filled with zeros.
  Non-data buffers area are used to store operators, subgraphs and etc.
  You can find more details from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs
'

Here is the more complicated model compiler conversion and TFLite model analyzer output:
=========================================================================================

'$ edgetpu_compiler -s testmodel.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 2466 ms.

Input model: testmodel.tflite
Input size: 24.72MiB
Output model: testmodel_edgetpu.tflite
Output size: 25.60MiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 7.66MiB
Off-chip memory used for streaming uncached model parameters: 25.49MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 6
Operation log: testmodel_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 3
Number of operations that will run on CPU: 3

Operator                       Count      Status

DEQUANTIZE                     1          Operation is working on an unsupported data type
FULLY_CONNECTED                1          Mapped to Edge TPU
CONCATENATION                  1          Mapped to Edge TPU
RESHAPE                        1          Mapped to Edge TPU
FLOOR_MOD                      1          Operation is working on an unsupported data type
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
Compilation child process completed within timeout period.
Compilation succeeded!'

'=== TFLite ModelAnalyzer ===

Your TFLite model has '1' subgraph(s). In the subgraph description below,
T# represents the Tensor numbers. For example, in Subgraph#0, the RESHAPE op takes
tensor #0 and tensor #2 as input and produces tensor #4 as output.

Subgraph#0 main(T#0) -> [T#9]
  Op#0 RESHAPE(T#0, T#2[-1, 14400]) -> [T#4]
  Op#1 FULLY_CONNECTED(T#4, T#3[], T#-1) -> [T#5]
  Op#2 CONCATENATION(T#4, T#5) -> [T#6]
  Op#3 DEQUANTIZE(T#6) -> [T#7]
  Op#4 FLOOR_MOD(T#7, T#1[]) -> [T#8]
  Op#5 QUANTIZE(T#8) -> [T#9]

Tensors of Subgraph#0
  T#0(serving_default_ldpc_enc_input:0) shape_signature:[-1, 14400], type:INT8
  T#1(model/tf.math.floormod/FloorMod/y) shape:[], type:FLOAT32 RO 4 bytes, data:[]
  T#2(model/tf.reshape/Reshape/shape) shape:[2], type:INT32 RO 8 bytes, data:[-1, 14400]
  T#3(model/tf.linalg.matmul/MatMul1) shape:[1800, 14400], type:INT8 RO 25920000 bytes, data:[]
  T#4(model/tf.reshape/Reshape) shape_signature:[-1, 14400], type:INT8
  T#5(model/tf.linalg.matmul/MatMul2) shape_signature:[-1, 1800], type:INT8
  T#6(model/tf.concat/concat) shape_signature:[-1, 16200], type:INT8
  T#7(tfl.dequantize) shape_signature:[-1, 16200], type:FLOAT32
  T#8(PartitionedCall:01) shape_signature:[-1, 16200], type:FLOAT32
  T#9(PartitionedCall:0) shape_signature:[-1, 16200], type:INT8


Your model looks compatibile with GPU delegate with TFLite runtime version 2.10.0.
But it doesn't guarantee that your model works well with GPU delegate.
There could be some runtime incompatibililty happen.
---------------------------------------------------------------
Your TFLite model has '1' signature_def(s).

Signature#0 key: 'serving_default'
- Subgraph: Subgraph#0
- Inputs:
    'ldpc_enc_input' : T#0
- Outputs:
    'tf.math.floormod' : T#9

---------------------------------------------------------------
              Model size:   25922272 bytes
    Non-data buffer size:       2156 bytes (00.01 %)
  Total data buffer size:   25920116 bytes (99.99 %)
    (Zero value buffers):          0 bytes (00.00 %)

* Buffers of TFLite model are mostly used for constant tensors.
  And zero value buffers are buffers filled with zeros.
  Non-data buffers area are used to store operators, subgraphs and etc.
  You can find more details from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs'
```
</details>

**Comment by hjonnala** [comment]
Hello @gsirocco if your model has some operations not mapped to TPU then please try to modify them in a way those can be mapped to TPU. If that's not possible please use Coral USB accelerator with HIGH CPU machine to reduce the inference time.
And feel to check [single_model_benchmark](https://github.com/google-coral/libcoral/blob/master/coral/single_model_benchmark.cc) tool, by building libcoral for benchmarks,  to get to know the total time spend on CPU. Thanks!

```
git clone --recurse-submodules https://github.com/google-coral/libcoral
cd libcoral
make docker-shell
make CPU=aarch64 benchmarks
```

```
hemanthr@hemanth-glaptop:~/libcoral/out/k8/benchmarks/coral$ ./single_model_benchmark -model ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
2021-12-10 08:30:12
Running ./single_model_benchmark
Run on (4 X 3900 MHz CPU s)
CPU Caches:
  L1 Data 32K (x2)
  L1 Instruction 32K (x2)
  L2 Unified 256K (x2)
  L3 Unified 4096K (x1)
Load Average: 1.07, 1.04, 1.00
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_Model         11.7 ms         4.16 ms          131 ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
```

**Comment by gsirocco** [comment]
### Thanks!! This looks really good to try, however when I build on my VM running Ubuntu Linux on Win PC, I seem to be getting the same error as before when trying to build the examples where it can't seem to create the output file in the docker. I found much earlier in the build that it for some reason cannot create symbolic links because operation not permitted?

'WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':
  cannot create symbolic link bazel-bin -> /home/gsosnow/.cache/bazel/_bazel_gsosnow/eab0d61a99b6696edb3d2aff87b585e8/execroot/libcoral/bazel-out/aarch64-opt/bin:  /workspace/bazel-bin (Operation not permitted)
  cannot create symbolic link bazel-testlogs -> /home/gsosnow/.cache/bazel/_bazel_gsosnow/eab0d61a99b6696edb3d2aff87b585e8/execroot/libcoral/bazel-out/aarch64-opt/testlogs:  /workspace/bazel-testlogs (Operation not permitted)
  cannot create symbolic link bazel-out -> /home/gsosnow/.cache/bazel/_bazel_gsosnow/eab0d61a99b6696edb3d2aff87b585e8/execroot/libcoral/bazel-out:  /workspace/bazel-out (Operation not permitted)
  cannot create symbolic link bazel-workspace -> /home/gsosnow/.cache/bazel/_bazel_gsosnow/eab0d61a99b6696edb3d2aff87b585e8/execroot/libcoral:  /workspace/bazel-workspace (Operation not permitted)
        :
        :
INFO: Elapsed time: 604.601s, Critical Path: 27.31s
INFO: 1172 processes: 372 internal, 800 processwrapper-sandbox.
INFO: Build completed successfully, 1172 total actions
pushd /workspace/bazel-out/aarch64-opt/bin; for f in `find . -name "*_benchmark" -type f`; do mkdir -p /workspace/out/aarch64/benchmarks/`dirname $f`; cp -f /workspace/bazel-out/aarch64-opt/bin/$f /workspace/out/aarch64/benchmarks/$f; done; popd
/bin/bash: line 0: pushd: /workspace/bazel-out/aarch64-opt/bin: No such file or directory
/bin/bash: line 0: popd: directory stack empty
Makefile:79: recipe for target 'benchmarks' failed
make: *** [benchmarks] Error 1'

### So I am trying to build in colab, as I had done for the examples, but with the target being benchmarks instead of examples, I am getting the following error. It's looking for some models in the test_data directory? It looks like the test_data directory is empty, there is no BUILD file that it is looking for.

'Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
bazel build --compilation_mode=opt --cpu=aarch64 --copt=-ffp-contract=off //coral:cocompiled_models_benchmark //coral:lstm_models_benchmark //coral:models_benchmark //coral:single_model_benchmark //coral/learn/backprop:softmax_regression_model_benchmark //coral/pose_estimation:models_benchmark //coral/tools:automl_rnn_models_benchmark
Loading: 0 packages loaded
ERROR: /content/libcoral/WORKSPACE:68:21: fetching new_local_repository rule //external:test_data: the 'build_file' attribute does not specify an existing file (/content/libcoral/test_data/BUILD does not exist)
Analyzing: 7 targets (0 packages loaded, 0 targets configured)
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
Analyzing: 7 targets (0 packages loaded, 0 targets configured)
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /content/libcoral/WORKSPACE:37:14: in <toplevel>
  /root/.cache/bazel/_bazel_root/db282089ccf9ceac8a40bd53ba7e80db/external/org_tensorflow/tensorflow/workspace0.bzl:105:34: in workspace
  /root/.cache/bazel/_bazel_root/db282089ccf9ceac8a40bd53ba7e80db/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/db282089ccf9ceac8a40bd53ba7e80db/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
Analyzing: 7 targets (0 packages loaded, 0 targets configured)
ERROR: /content/libcoral/coral/BUILD:247:10: //coral:cocompiled_models_benchmark depends on @test_data//cocompilation:models in repository @test_data which failed to fetch. no such package '@test_data//cocompilation': the 'build_file' attribute does not specify an existing file (/content/libcoral/test_data/BUILD does not exist)
Analyzing: 7 targets (0 packages loaded, 0 targets configured)
ERROR: Analysis of target '//coral:cocompiled_models_benchmark' failed; build aborted: Analysis failed
Analyzing: 7 targets (0 packages loaded, 0 targets configured)
INFO: Elapsed time: 0.324s
Analyzing: 7 targets (0 packages loaded, 0 targets configured)
INFO: 0 processes.
Analyzing: 7 targets (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)
    currently loading: @com_github_google_benchmark//
Makefile:79: recipe for target 'benchmarks' failed
make: *** [benchmarks] Error 1'

**Comment by hjonnala** [comment]
Please replace` ! git submodule init && git submodule update libedgetpu ` to `! git submodule init && git submodule update` to build for benchmarks.

An download the file using the below snippet. Thanks!
```
from google.colab import files
files.download('out/aarch64/benchmarks/coral/single_model_benchmark')
```

**Comment by gsirocco** [comment]
Thanks, I am trying the build as I write this. One clarification on the output of the benchmark, the Time is the total time the model runs on cpu and tpu, while CPU is the time it spends on cpu only, so if you subtract the two this would be the time run on the TPU? Is that the correct interpretation?

**Comment by hjonnala** [comment]
> Thanks, I am trying the build as I write this. One clarification on the output of the benchmark, the Time is the total time the model runs on cpu and tpu, while CPU is the time it spends on cpu only, so if you subtract the two this would be the time run on the TPU? Is that the correct interpretation?

yes, the interpretation is correct.

**Comment by gsirocco** [comment]
I did find a useful utility that shows how the flow of the model is divided between cpu and tpu: [visualize.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/visualize.py)
I have also found the experimental option for the tpu compiler -a to enable multiple subgraphs.
Also, it's good to know that:
 Note: Currently, the Edge TPU compiler cannot partition the model more than once, so as soon as an unsupported operation occurs, that operation and everything after it executes on the CPU, even if supported operations occur later.
![image](https://user-images.githubusercontent.com/112350229/192657050-c2f6579c-4299-42cf-a4a8-fd28b7e7bf4f.png)

**Comment by gsirocco** [comment]
I've been able to run the benchmark and to my surprise, it seems the processing is majority TPU from the output:

```
$ ./single_model_benchmark -model testmodel_edgetpu.tflite
2022-09-28 02:38:03
Running ./single_model_benchmark
Run on (4 X 1500 MHz CPU s)
Load Average: 0.00, 0.01, 0.00
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_Model         74.4 ms         6.54 ms           97 testmodel_edgetpu.tflite

```

Here is the visual of the model, is the ~68ms TPU time just a factor of the data size and operation or transfer in this case? Or just the operations being performed and number of them, or a combination of all or something else? I have also included the model analyzer output and compiler output below. Thanks!!!

![testmodel_edgetpu](https://user-images.githubusercontent.com/112350229/192677669-ef6b00d7-4d38-4d3a-a335-c03ca14d06d7.jpg)

![image](https://user-images.githubusercontent.com/112350229/192677844-c7f251e1-9bb4-415a-a5c6-e0fd04d51a07.png)

```$ edgetpu_compiler -s testmodel.tflite
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 2466 ms.

Input model: testmodel.tflite
Input size: 24.72MiB
Output model: testmodel_edgetpu.tflite
Output size: 25.60MiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 7.66MiB
Off-chip memory used for streaming uncached model parameters: 25.49MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 6
Operation log: testmodel_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 3
Number of operations that will run on CPU: 3

Operator                       Count      Status

DEQUANTIZE                     1          Operation is working on an unsupported data type
FULLY_CONNECTED                1          Mapped to Edge TPU
CONCATENATION                  1          Mapped to Edge TPU
RESHAPE                        1          Mapped to Edge TPU
FLOOR_MOD                      1          Operation is working on an unsupported data type
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
Compilation child process completed within timeout period.
Compilation succeeded!'

'=== TFLite ModelAnalyzer ===

Your TFLite model has '1' subgraph(s). In the subgraph description below,
T# represents the Tensor numbers. For example, in Subgraph#0, the RESHAPE op takes
tensor #0 and tensor #2 as input and produces tensor #4 as output.

Subgraph#0 main(T#0) -> [T#9]
  Op#0 RESHAPE(T#0, T#2[-1, 14400]) -> [T#4]
  Op#1 FULLY_CONNECTED(T#4, T#3[], T#-1) -> [T#5]
  Op#2 CONCATENATION(T#4, T#5) -> [T#6]
  Op#3 DEQUANTIZE(T#6) -> [T#7]
  Op#4 FLOOR_MOD(T#7, T#1[]) -> [T#8]
  Op#5 QUANTIZE(T#8) -> [T#9]

Tensors of Subgraph#0
  T#0(serving_default_ldpc_enc_input:0) shape_signature:[-1, 14400], type:INT8
  T#1(model/tf.math.floormod/FloorMod/y) shape:[], type:FLOAT32 RO 4 bytes, data:[]
  T#2(model/tf.reshape/Reshape/shape) shape:[2], type:INT32 RO 8 bytes, data:[-1, 14400]
  T#3(model/tf.linalg.matmul/MatMul1) shape:[1800, 14400], type:INT8 RO 25920000 bytes, data:[]
  T#4(model/tf.reshape/Reshape) shape_signature:[-1, 14400], type:INT8
  T#5(model/tf.linalg.matmul/MatMul2) shape_signature:[-1, 1800], type:INT8
  T#6(model/tf.concat/concat) shape_signature:[-1, 16200], type:INT8
  T#7(tfl.dequantize) shape_signature:[-1, 16200], type:FLOAT32
  T#8(PartitionedCall:01) shape_signature:[-1, 16200], type:FLOAT32
  T#9(PartitionedCall:0) shape_signature:[-1, 16200], type:INT8


Your model looks compatibile with GPU delegate with TFLite runtime version 2.10.0.
But it doesn't guarantee that your model works well with GPU delegate.
There could be some runtime incompatibililty happen.
---------------------------------------------------------------
Your TFLite model has '1' signature_def(s).

Signature#0 key: 'serving_default'
- Subgraph: Subgraph#0
- Inputs:
    'ldpc_enc_input' : T#0
- Outputs:
    'tf.math.floormod' : T#9

---------------------------------------------------------------
              Model size:   25922272 bytes
    Non-data buffer size:       2156 bytes (00.01 %)
  Total data buffer size:   25920116 bytes (99.99 %)
    (Zero value buffers):          0 bytes (00.00 %)

* Buffers of TFLite model are mostly used for constant tensors.
  And zero value buffers are buffers filled with zeros.
  Non-data buffers area are used to store operators, subgraphs and etc.
  You can find more details from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs
```

**Comment by gsirocco** [comment]
One possibility for speed up that we were thinking would be to use multiple TPUs in parallel for this model, but before doing that it would be good to get an understanding of what the limiting factors are currently. Thanks for any pointers or suggestions on this. You've been very helpful just to get things to this point.

**Comment by hjonnala** [comment]
Hello @gsirocco 

> I did find a useful utility that shows how the flow of the model is divided between cpu and tpu: [visualize.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/visualize.py)

Good to know about this. You can also use the https://netron.app/ to visualize the model.



> Note: Currently, the Edge TPU compiler cannot partition the model more than once, so as soon as an unsupported operation occurs, that operation and everything after it executes on the CPU, even if supported operations occur later.

Yes, it is true without -a flag. with -a flag you can map all the supported operations to EdgeTPU unless they have some limitations.



> Input model: testmodel.tflite
> Input size: 24.72MiB
> Output model: testmodel_edgetpu.tflite
> Output size: 25.60MiB

As your model is larger(>>8MB) than the EdgeTPU SRAM, you can try to compile the model --num_segments flag to make the inference faster. Please check the documentation for more details at: https://coral.ai/docs/edgetpu/pipeline/#overview

Thanks!

**Comment by gsirocco** [comment]
> As your model is larger(>>8MB) than the EdgeTPU SRAM, you can try to compile the model --num_segments flag to make the inference faster. Please check the documentation for more details at: https://coral.ai/docs/edgetpu/pipeline/#overview

Just to clarify regarding this comment for compiling with --num_segments flag to make inference faster, would require having as many TPUs as given in the number provided to this flag? I'm assuming no speed up will be obtained for a single TPU on the dev board by doing this, correct?

**Comment by hjonnala** [comment]
> > As your model is larger(>>8MB) than the EdgeTPU SRAM, you can try to compile the model --num_segments flag to make the inference faster. Please check the documentation for more details at: https://coral.ai/docs/edgetpu/pipeline/#overview
> 
> Just to clarify regarding this comment for compiling with --num_segments flag to make inference faster, would require having as many TPUs as given in the number provided to this flag? I'm assuming no speed up will be obtained for a single TPU on the dev board by doing this, correct?

Yes, that's correct.

**Comment by gsirocco** [comment]
If we have 8 TPUs, then the compiler can divide the model into 8 separate ones regardless of the model architecture (operations, data, etc.) by setting --num_segments to 8? Although if the cache can hold 8MB then 3 or 4 TPUs may be the sweet spot for performance gain with a size of ~25MB?

**Comment by hjonnala** [comment]
> If we have 8 TPUs, then the compiler can divide the model into 8 separate ones regardless of the model architecture (operations, data, etc.) by setting --num_segments to 8? Although if the cache can hold 8MB then 3 or 4 TPUs may be the sweet spot for performance gain with a size of ~25MB?

3 TPU's would be enough for your model.

**Comment by gsirocco** [comment]
This would serialize the model in a pipeline as explained in the link.
Would this reduce the end to end latency from ~68ms significantly? If so
any estimate by how much (most likely from using the tpu sram)? Or is the
only real gain in pipelining multiple invocations of the model with minimal
latency impact?

**Comment by hjonnala** [comment]
> This would serialize the model in a pipeline as explained in the link. Would this reduce the end to end latency from ~68ms significantly? If so any estimate by how much (most likely from using the tpu sram)? Or is the only real gain in pipelining multiple invocations of the model with minimal latency impact?

Unfortunately, we won't be able to tell the performance gain/loss when pipe lining the model as it varies from model to model.

**Comment by gsirocco** [comment]
I think this should work, but am getting a core dump when I try to segment my model. If I compile my model without --num_segments it compiles fine. Btw, I tried this on colab and am getting the segmentation fault as well. Is it because it has an unsupported operation that is a mapped to the CPU in addition to 3 that are mapped to TPU?

`$ edgetpu_compiler --num_segments=5 testmodel.tflite
Edge TPU Compiler version 16.0.384591198
/usr/bin/edgetpu_compiler: line 3: 21453 Segmentation fault      (core dumped) ${d}/edgetpu_compiler_bin/ld-linux-x86-64.so.2 --library-path ${d}/edgetpu_compiler_bin ${d}/edgetpu_compiler_bin/edgetpu_compiler "$@"
`

**Comment by hjonnala** [comment]
> `$ edgetpu_compiler --num_segments=5 testmodel.tflite Edge TPU Compiler version 16.0.384591198 /usr/bin/edgetpu_compiler: line 3: 21453 Segmentation fault (core dumped) ${d}/edgetpu_compiler_bin/ld-linux-x86-64.so.2 --library-path ${d}/edgetpu_compiler_bin ${d}/edgetpu_compiler_bin/edgetpu_compiler "$@" `

please share your uncompiled tflite model here..Thanks!

**Comment by gsirocco** [comment]
sure, here it is, added .txt suffix to be able to upload. Please let me know if there is any trouble downloading the model. Thanks!
[testmodel.tflite.txt](https://github.com/google-coral/edgetpu/files/9689492/testmodel.tflite.txt)

**Comment by gsirocco** [comment]
We were thinking of other possible optimizations for space. One was to use tf.sparse.SparseTensor, however I didn't notice if the Edge TPU would support it, as there is no mention of it in the compatibility page. Thanks!!

**Comment by gsirocco** [comment]
One other thing we are trying is a reduced test case where our matrix size is 1/8 what we would normally use, in order to see the performance increase of trying to have everything on the TPU memory wise. However, in trying to compile the model, I notice that even though the memory size is indeed reduced, the compiler says that no memory on-chip is used and it is all external. Not sure why this is so because it is only ~2.5MB, maybe because there is a CPU based operation in addition to the 3 TPU based ones?

> $ edgetpu_compiler -s testmodel_trimmed.tflite
> Edge TPU Compiler version 16.0.384591198
> Started a compilation timeout timer of 180 seconds.
> 
> Model compiled successfully in 520 ms.
> 
> Input model: testmodel_trimmed.tflite
> Input size: 2.47MiB
> Output model: testmodel_trimmed_edgetpu.tflite
> Output size: 2.67MiB
> On-chip memory used for caching model parameters: 0.00B
> On-chip memory remaining for caching model parameters: 7.66MiB
> Off-chip memory used for streaming uncached model parameters: 2.64MiB
> Number of Edge TPU subgraphs: 1
> Total number of operations: 6
> Operation log: testmodel_trimmed_edgetpu.log
> 
> Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
> Number of operations that will run on Edge TPU: 3
> Number of operations that will run on CPU: 3
> 
> Operator                       Count      Status
> 
> FLOOR_MOD                      1          Operation is working on an unsupported data type
> QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
> DEQUANTIZE                     1          Operation is working on an unsupported data type
> CONCATENATION                  1          Mapped to Edge TPU
> RESHAPE                        1          Mapped to Edge TPU
> FULLY_CONNECTED                1          Mapped to Edge TPU
> Compilation child process completed within timeout period.
> Compilation succeeded!

**Comment by hjonnala** [comment]
> One other thing we are trying is a reduced test case where our matrix size is 1/8 what we would normally use, in order to see the performance increase of trying to have everything on the TPU memory wise. However, in trying to compile the model, I notice that even though the memory size is indeed reduced, the compiler says that no memory on-chip is used and it is all external. Not sure why this is so because it is only ~2.5MB, maybe because there is a CPU based operation in addition to the 3 TPU based ones?

could you please share the code snippet to generate the tflite model here. Thanks!

**Comment by gsirocco** [comment]
Just to clarify, do you want the code to generate the TF model itself, or the code to convert the TF model to TFLite?

**Comment by hjonnala** [comment]
> Just to clarify, do you want the code to generate the TF model itself, or the code to convert the TF model to TFLite?

The code to generate the TF model please..

**Comment by gsirocco** [comment]
Here's the code to generate the TF model. Thanks!!!

> gen_matrix = np.random.randint(0, 2, (14400, 180))
> 
> generator = tf.convert_to_tensor(gen_matrix, dtype=tf.float32)  # 14400 x 180
> 
> foo_input = keras.Input(shape=(14400,), name="foo_input")
> generator_input = tf.reshape(foo_input, shape=(-1, 14400))  # 1 x 14400
> 
> generator_output = tf.concat(
>     [
>         generator_input,
>         tf.matmul(generator_input, generator)
>     ],
>     axis=1
> )
> 
> foo_output = tf.math.floormod(generator_output, 2) # modulo 2 for binary
> 
> foo_model = keras.Model(inputs=foo_input, outputs=foo_output)

**Comment by hjonnala** [comment]
![image](https://user-images.githubusercontent.com/86132058/193959443-6c6910ce-5f0e-4927-81e2-5e54b76e3a43.png)




Here the operations input and output sizes are too big for TPU. Because of this SRAM memory not allocated. We can't say any concrete limits at which they can be mapped to SRAM as it varies from operation to operation. For this model you may try replacing `14400` with `2560 `or some other value. Thanks!

**Comment by gsirocco** [comment]
Thanks for the evaluation of the model, we will try to see if we can reduce the 14400.
How about the possibility of using tf.sparse.SparseTensor on the TPU?

> We were thinking of other possible optimizations for space. One was to use tf.sparse.SparseTensor, however I didn't notice if the Edge TPU would support it, as there is no mention of it in the compatibility page. Thanks!!

**Comment by hjonnala** [comment]
> How about the possibility of using tf.sparse.SparseTensor on the TPU?

I think, its not possible to use tf.sparse.SparseTenosr on TPU as its not listed as a supported operation. https://coral.ai/docs/edgetpu/models-intro/#supported-operations

**Comment by gsirocco** [comment]
With regard to the restricted size from 14400 to 2560, we need to process a data size of 14400x1800 within a couple of milliseconds. If we have to reduce this to 2560x180 chunks then this would not be practical. Is there a way to get a concrete understanding of what the data size restrictions are for TPU memory operation?

**Comment by hjonnala** [comment]
> Is there a way to get a concrete understanding of what the data size restrictions are for TPU memory operation?

Unfortunately, The only way to know is by experiments as it varies from operation to operation. Please check the pretrained models input size as well if your application falls under one of those categories: https://coral.ai/models/. Thanks!

**Comment by gsirocco** [comment]
Are there any TPU alternatives which are supported that could be explored to better handle a data size of 14400x1800 in hw? Maybe any GPUs which can be recommended to explore as alternatives? Thanks!

Doing a little googling, it looks like Nvidia ones are supported pretty well for Tensorflow, not sure if there are others that could be possibilities?

It looks like short of a hw change, there's no other option with the TPU to handle the 14400x1800 size with the performance that we require?

**Comment by gsirocco** [comment]
> $ edgetpu_compiler --num_segments=5 testmodel.tflite Edge TPU Compiler version 16.0.384591198 /usr/bin/edgetpu_compiler: line 3: 21453 Segmentation fault (core dumped) ${d}/edgetpu_compiler_bin/ld-linux-x86-64.so.2 --library-path ${d}/edgetpu_compiler_bin ${d}/edgetpu_compiler_bin/edgetpu_compiler "$@"
> 
> please share your uncompiled tflite model here..Thanks!

Hi, just checking if there was an update on the segmentation fault? Thanks!

**Comment by gsirocco** [comment]
Had a clarification on the Invoke function when running on the TPU.  I'm assuming this is a blocking call and returns when it's finished. If there are 4 TPUs, is there a non-blocking invocation where other TPUs can be invoked while others are busy?
I'm not doing pipelining here, but would really be doing parallel invocations of parts of an input and then combining at the end after all 4 would be complete. Maybe something a start function and then a function to check that it is complete?

>   // Run inference.
>   if (interpreter->Invoke() != kTfLiteOk) {
>     std::cerr << "Cannot invoke interpreter" << std::endl;
>     return 1;
>   }

**Comment by gsirocco** [comment]
I guess one strategy would be to have a separate thread for each Invoke, if there is no alternative?

**Comment by hjonnala** [comment]
> I guess one strategy would be to have a separate thread for each Invoke, if there is no alternative?

closing as this got covered at: https://github.com/google-coral/edgetpu/issues/677#issuecomment-1298652707
