### ISSUE TITLE
Converting MoveNet.Multipose.Lightning for use with Coral

### ISSUE THREAD

**Issue by benank** [google-coral/edgetpu#665]
### Description

Hello, I'm attempting to use [MoveNet.Multipose.Lightning](https://tfhub.dev/google/lite-model/movenet/multipose/lightning/tflite/float16/1) with Coral but am having difficulty converting it to the proper format for Coral.

I can see that there is already a [pre-converted model here](https://github.com/google-coral/pycoral/blob/master/examples/movenet_pose_estimation.py), but that model is for singlepose MoveNet. What steps were taken to convert/optimize that MoveNet model to the proper format for Coral? How can I do that myself, but for the multipose model?

I've seen [this page](https://coral.ai/docs/edgetpu/models-intro/#model-requirements) on model requirements and I understand what is needed, but I am having difficulty getting there. I've tried converting the `.pb` model using [these steps](https://www.tensorflow.org/lite/models/convert/convert_models#python_api), but it ran into a common error of `Some ops are not supported by the native TFLite runtime`. I tried following the solution steps listed there, but they weren't very clear. I've also tried converting the [tflite model](https://tfhub.dev/google/lite-model/movenet/multipose/lightning/tflite/float16/1) but I don't think it meets the requirements for Coral because I get this error when trying to convert it using `edgetpu_compulter <model>`: `Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.`.

I've also tried the solution listed [here](https://github.com/google-coral/edgetpu/issues/655#issuecomment-1241258031), but am getting this error:
```
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TF Select ops: StridedSlice
```
It looks like I can specify which operations I want, but I don't know which operations the model uses that are supported. All I know is that the `StridedSlice` operation doesn't seem to be supported.

Any help/guidance with this problem would be greatly appreciated! Thanks! 😀

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Windows 10, Linux, Ubuntu

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by koeewin** [comment]
hello benank, hello hjonnala,

any update of the movenet multipose for coral usage?

I've seen this on the move net tensor hub website:
Initial release of the tflite MoveNet.Multipose model. Note that the current model uses dynamic shape input which makes it incompatible with accelerators, e.g. GPU. We are working on the accelerator-compatible version and will release them soon.

Do you know when will the multipose support coral?
