### ISSUE TITLE
How to post-quantize a model with GELU (or any unsupported Op)

### ISSUE THREAD

**Issue by ImanHosseini** [google-coral/edgetpu#667]
### Description

I'm trying to prepare a trained model to run on edge TPU:
```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.int8]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.representative_dataset = representative_data_gen
tflite_model = converter.convert()
```
Then on the output I run "edgetpu_compiler model.tflite" but I get:
```
ERROR: Op builtin_code out of range: 150. Are you using old TFLite binary with newer model?
```
150 is GELU (which is something that my model uses). How can I fix this? (obviously, without retraining my model anew without GELU)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Operating System

Ubuntu

### Coral Device

Dev Board Mini

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, @ImanHosseini 
Please check if you are able to run [inference](https://github.com/hjonnala/snippets/blob/main/coral_inference.py) for int8 tflite model with the [latest tflite runtime](https://coral.ai/software/#pycoral-api). If you are not able run inference then it is not possible to compile the model with the compiler. Thanks!

**Comment by ImanHosseini** [comment]
I sure cant compile. But will this be fixed? Will this ever be supported?

**Comment by hjonnala** [comment]
Unfortunately, as of now we don't have any plans to add support for new activations.

**Comment by InputBlackBoxOutput** [comment]
Hi @ImanHosseini,

I ran into a similar issue with GELU for the BERT model. The Edge TPU has no support for GELU which implies that the edge_tpu compiler must run the operation on the CPU but that is not the case. Sadly, this means that the latter is not implemented in the compiler lowering mechanism.

![image](https://user-images.githubusercontent.com/53337979/229633226-c6bce03f-a474-4329-85a1-7dbc31bef51b.png)

**Comment by MATTYGILO** [comment]
This should be included gelu is an essential up and coming activation function

**Comment by fabito** [comment]
According to [Efficient Deployment of Transformer Models on Edge TPU Accelerators: A Real System Evaluation](https://openreview.net/forum?id=PibYaG2C7An), the author successfully replaced GELU by its polynomial-based approximation known as I-GELU.
