### ISSUE TITLE
Multiple ops mapped to cpu when compiling efficientdet-lite3 and 4 models!

### ISSUE THREAD

**Issue by Plessen** [google-coral/edgetpu#671]
Ran into this exact same issue. I see @ghbn8 compiled it for a single edge tpu, even though the minimum required for efficientdet3 and 4 is 2 edges. This solution does not hold for --num_segments = 2. Not only that, but if I use the -a flag the compilation times out at lower ops than it does without it. It does compile using the -d flag combined with -k 10, but 50% of the ops are mapped to cpu instead of tpu (pretty sure some are even compatible with the tpu). I will open a new issue about this matter. @hjonnala

_Originally posted by @Plessen in https://github.com/google-coral/edgetpu/issues/651#issuecomment-1279071923_

**Comment by Plessen** [comment]
Here is the command (the model architecture is EfficientDet-Lite3):

- !edgetpu_compiler -s -d -k 10 -n 2 "/content/rede_modelo3_73.tflite"

The output is:

Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 84 ops
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 2270 ms.

Input model: rede_modelo3_73_segment_0_of_2.tflite
Input size: 5.21MiB
Output model: rede_modelo3_73_segment_0_of_2_edgetpu.tflite
Output size: 6.51MiB
On-chip memory used for caching model parameters: 6.02MiB
On-chip memory remaining for caching model parameters: 1.02MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 84
Operation log: rede_modelo3_73_segment_0_of_2_edgetpu.log

Operator                       Count      Status

QUANTIZE                       1          Mapped to Edge TPU
DEPTHWISE_CONV_2D              22         Mapped to Edge TPU
ADD                            15         Mapped to Edge TPU
CONV_2D                        46         Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 
Searching for valid delegate with step 10
Try to compile segment with 340 ops
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 330 ops
Intermediate tensors: tfl.dequantize,Reshape,Reshape_8,class-2/separable_conv2d_3/depthwise;class-2/separable_conv2d_3/depthwise,Reshape_2,Reshape_4
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 320 ops
Intermediate tensors: Reshape_2,Reshape_4,Reshape_9,Reshape_1,Reshape_8,Reshape_3,Relu6_15;Relu6_15;box-3-bn-6/FusedBatchNormV3;box-3-bn-6/FusedBatchNormV3;box_net/box-3/bias;box-3/BiasAdd_3;box-3/BiasAdd_3;class_net/class-predict/separable_conv2d_4/depthwise;box-3/separable_conv2d_3;box-3/separable_conv2d_31,Reshape_5,cell_5/fnode6/op_after_combine11/bn/FusedBatchNormV3;cell_5/fnode6/op_after_combine11/bn/FusedBatchNormV3;fpn_cells/cell_5/fnode6/op_after_combine11/conv/bias;cell_5/fnode6/op_after_combine11/conv/BiasAdd;cell_5/fnode6/op_after_combine11/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_5/fnode6/op_after_combine11/conv/separable_conv2d;cell_5/fnode6/op_after_combine11/conv/separable_conv2d,Reshape
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 310 ops
Intermediate tensors: Reshape_2,Reshape_4,Reshape_9,Reshape_1,Reshape_3,Reshape_5,Reshape,cell_5/fnode6/op_after_combine11/bn/FusedBatchNormV3;cell_5/fnode6/op_after_combine11/bn/FusedBatchNormV3;fpn_cells/cell_5/fnode6/op_after_combine11/conv/bias;cell_5/fnode6/op_after_combine11/conv/BiasAdd;cell_5/fnode6/op_after_combine11/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_5/fnode6/op_after_combine11/conv/separable_conv2d;cell_5/fnode6/op_after_combine11/conv/separable_conv2d,class_net/class-predict/separable_conv2d_4/depthwise210
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 300 ops
Intermediate tensors: Reshape_2,cell_5/fnode7/op_after_combine12/bn/FusedBatchNormV3;cell_5/fnode7/op_after_combine12/bn/FusedBatchNormV3;fpn_cells/cell_5/fnode7/op_after_combine12/conv/bias;cell_5/fnode7/op_after_combine12/conv/BiasAdd;cell_5/fnode7/op_after_combine12/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_5/fnode7/op_after_combine12/conv/separable_conv2d;cell_5/fnode7/op_after_combine12/conv/separable_conv2d,Reshape_4,Reshape_1,Reshape_3,box_net/box-predict/BiasAdd_4;box_net/box-predict/separable_conv2d_4;box_net/box-predict/bias11,Reshape_5,cell_5/fnode6/op_after_combine11/bn/FusedBatchNormV3;cell_5/fnode6/op_after_combine11/bn/FusedBatchNormV3;fpn_cells/cell_5/fnode6/op_after_combine11/conv/bias;cell_5/fnode6/op_after_combine11/conv/BiasAdd;cell_5/fnode6/op_after_combine11/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_5/fnode6/op_after_combine11/conv/separable_conv2d;cell_5/fnode6/op_after_combine11/conv/separable_conv2d,Reshape
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 290 ops
Intermediate tensors: Reshape_2,cell_5/fnode7/op_after_combine12/bn/FusedBatchNormV3;cell_5/fnode7/op_after_combine12/bn/FusedBatchNormV3;fpn_cells/cell_5/fnode7/op_after_combine12/conv/bias;cell_5/fnode7/op_after_combine12/conv/BiasAdd;cell_5/fnode7/op_after_combine12/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_5/fnode7/op_after_combine12/conv/separable_conv2d;cell_5/fnode7/op_after_combine12/conv/separable_conv2d,Reshape_4,Reshape_1,Reshape_3,Reshape_5,cell_5/fnode6/op_after_combine11/bn/FusedBatchNormV3;cell_5/fnode6/op_after_combine11/bn/FusedBatchNormV3;fpn_cells/cell_5/fnode6/op_after_combine11/conv/bias;cell_5/fnode6/op_after_combine11/conv/BiasAdd;cell_5/fnode6/op_after_combine11/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_5/fnode6/op_after_combine11/conv/separable_conv2d;cell_5/fnode6/op_after_combine11/conv/separable_conv2d,Reshape
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 280 ops
Intermediate tensors: Reshape_2,cell_5/fnode6/resample_2_10_11/max_pooling2d_22/MaxPool;cell_5/fnode6/resample_2_10_11/max_pooling2d_22/MaxPool,Reshape_1,cell_4/fnode7/op_after_combine12/bn/FusedBatchNormV3;cell_4/fnode7/op_after_combine12/bn/FusedBatchNormV3;fpn_cells/cell_4/fnode7/op_after_combine12/conv/bias;cell_4/fnode7/op_after_combine12/conv/BiasAdd;cell_4/fnode7/op_after_combine12/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_4/fnode7/op_after_combine12/conv/separable_conv2d;cell_4/fnode7/op_after_combine12/conv/separable_conv2d,Reshape_3,cell_4/fnode6/op_after_combine11/bn/FusedBatchNormV3;cell_4/fnode6/op_after_combine11/bn/FusedBatchNormV3;fpn_cells/cell_4/fnode6/op_after_combine11/conv/bias;cell_4/fnode6/op_after_combine11/conv/BiasAdd;cell_4/fnode6/op_after_combine11/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_4/fnode6/op_after_combine11/conv/separable_conv2d;cell_4/fnode6/op_after_combine11/conv/separable_conv2d,cell_5/fnode0/op_after_combine5/bn/FusedBatchNormV3;cell_5/fnode0/op_after_combine5/bn/FusedBatchNormV3;fpn_cells/cell_5/fnode0/op_after_combine5/conv/bias;cell_5/fnode0/op_after_combine5/conv/BiasAdd;cell_5/fnode0/op_after_combine5/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_5/fnode0/op_after_combine5/conv/separable_conv2d;cell_5/fnode0/op_after_combine5/conv/separable_conv2d,Reshape,Reshape_5,class_net/class-predict/separable_conv2d_2/depthwise
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 1899 ms.

Input model: rede_modelo3_73_segment_1_of_2.tflite
Input size: 6.05MiB
Output model: rede_modelo3_73_segment_1_of_2_edgetpu.tflite
Output size: 6.58MiB
On-chip memory used for caching model parameters: 3.78MiB
On-chip memory remaining for caching model parameters: 3.35MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 340
Operation log: rede_modelo3_73_segment_1_of_2_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 185
Number of operations that will run on CPU: 155

Operator                       Count      Status

RESIZE_NEAREST_NEIGHBOR        20         Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        4          More than one subgraph is not supported
CONV_2D                        47         Mapped to Edge TPU
CONV_2D                        59         More than one subgraph is not supported
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
DEPTHWISE_CONV_2D              41         Mapped to Edge TPU
DEPTHWISE_CONV_2D              59         More than one subgraph is not supported
DEQUANTIZE                     2          Operation is working on an unsupported data type
MAX_POOL_2D                    5          More than one subgraph is not supported
MAX_POOL_2D                    21         Mapped to Edge TPU
CUSTOM                         1          Operation is working on an unsupported data type
ADD                            56         Mapped to Edge TPU
ADD                            12         More than one subgraph is not supported
CONCATENATION                  1          More than one subgraph is not supported
CONCATENATION                  1          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        1          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        9          More than one subgraph is not supported
Compilation child process completed within timeout period.
Compilation succeeded!


If I try to run it with the -a flag (which I believe would allow more than one subgraph) it lowers the ops until 0.

**Comment by hjonnala** [comment]
Hello @Plessen please share the models you are trying to compile here. Thanks!

**Comment by Plessen** [comment]
Hi @hjonnala, thanks for the early reply, I noticed there are a lot of issues being assigned to you, and your work has been amazing  throughout. This are some examples of  models that do not compile properly (and don´t compile at all with the -a flag):

[efficientdet-lite3-models.zip](https://github.com/google-coral/edgetpu/files/9809398/efficientdet-lite3-models.zip)

I only included 2 files (of efficientdet-lite3), because the problem when dealing with efficientdet-lite4 and even efficientdet-lite2 is similar.

**Comment by hjonnala** [comment]
Hi @Plessen to map the most of the operations the model needs to be compiled with intermediate tensors due to the large activation tensors. But, passing intermediate tensors is not possible when segmenting the model. As a workaround you can either split the model with the external tools or tweak the [profile based partitiner tool](https://github.com/google-coral/libcoral/blob/master/coral/tools/partitioner/profiling_based_partitioner.cc) to segment the model and compile them individually with intermediate tensors.

To segment with profile based partitioner tool, 

- please comment [this line](https://github.com/google-coral/libcoral/blob/master/coral/tools/partitioner/profiling_based_partitioner.cc#L200) and  compile the libcoral with the below steps:
```
git clone --recurse-submodules https://github.com/google-coral/libcoral
cd libcoarl
make docker-shell
```
build tools for your platform
```
make CPU=k8      tools  # Builds for x86_64 (default CPU value)
make CPU=armv7a  tools  # Builds for ARMv7-A, e.g. Pi 3 or Pi 4
make CPU=aarch64 tools  # Builds for ARMv8, e.g. Coral Dev Board 
```
- change directory to partitioner tool and run the below command: https://coral.ai/docs/edgetpu/compiler/#profiling-partitioner
`hemanth@hemanth:~/libcoral/out/k8/tools/partitioner$ ./partition_with_profiling   --edgetpu_compiler_binary edgetpu_compiler   --model_path /home/Downloads/efficientdet-lite3-models/efficientdet-lite3-3labels-81.tflite  --output_dir /home/hemanthreddyj/Downloads   --num_segments 2 --initial_lower_bound_ns 10000000 --initial_upper_bound_ns 12000000 --partition_search_step 340 --delegate_search_step 340`

- The above step would split the model and save the models in temp directory, from the logs you can find the output temp directory. I have chosen partition and delegate search step as 340 based on normal compilation output.
![image](https://user-images.githubusercontent.com/86132058/196445756-dd4e3efc-22e1-407a-8d11-b3d2694e806f.png)

- Once you have the split models you can compile the first segment normally and  the second segment with the below command:
```
edgetpu_compiler -s -i "box_net/box-predict/BiasAdd;box_net/box-predict/separable_conv2d_4;box_net/box-predict/separable_conv2d;box_net/box-predict/bias,class_net/class-predict/BiasAdd;class_net/class-predict/separable_conv2d_4;class_net/class-predict/separable_conv2d;class_net/class-predict/bias" /tmp/tmpdir.zUdTtM/efficientdet-lite3-3labels-81_segment_1_of_2.tflite

```

Here the segmented models for your reference: https://github.com/hjonnala/snippets/tree/main/models

**Comment by Plessen** [comment]
Well I'm impressed how quickly and easily you explained that to me. This tool is actually pretty handy for my work.  I will be closing this issue as it is solved. Thank you very much @hjonnala.

P.s: In your answer you mentioned I should uncomment a specific line, but it was already uncommented.
