### ISSUE TITLE
Coral Dev Board Mini cannot set a PWM frequency lower than +- 25 Hz

### ISSUE THREAD

**Issue by rodneyML** [google-coral/edgetpu#676]
### Description

I am working on a project which involves variable PWM frequency. I am able to set the PWM frequency to most frequency values above 25 Hz, but for some reason it crashes when setting a frequency lower than approximately 25 Hz. I have tried Adafruit-Blinka as well as Periphery, but none of these API's work with frequencies lower than approximately 25 Hz.

Code produced with Adafruit-Blinka's `pwmio`:
```
import pwmio
pwm_max = 6000
PWM_x = pwmio.PWMOut(board.PWM_B, frequency=pwm_max, variable_frequency=True)
PWM_x.duty_cycle = int(0.5 * 2 ** 16)
while True:
    inp = input('set frequency: ')
    PWM_x.duty_cycle = 0
    PWM_x.frequency = float(inp)
```

Code produced with `Periphery` :
```
from periphery import PWM

pwma = PWM(0, 1)
pwma.frequency = 1000
pwma.duty_cycle = 0.50
pwma.enable()

while True:
    inp = input('set frequency: ')  # Tried with 1000, 500, 250, 100, 25, (24 --> Does not work)
    pwma.duty_cycle = 0.50
    pwma.frequency = float(inp)
```

When given a frequency of example `24 Hz`, it crashes with the output in the log:

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Programming Language

Python 3.7

### Relevant Log Output

```shell
*** ----------------------------------- Periphery -------------------------------- ***

OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Writing.py", line 438, in <module>
    pwma.frequency = float(inp)
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 270, in _set_frequency
    self.period = 1.0 / frequency
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 228, in _set_period
    self.period_ns = int(period * 1e9)
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 179, in _set_period_ns
    self._write_channel_attr("period", str(period_ns))
  File "/usr/local/lib/python3.7/dist-packages/periphery/pwm.py", line 118, in _write_channel_attr
    f_attr.write(value + "\n")
OSError: [Errno 22] Invalid argument

*** ----------------------------------- Adafruit Blinka -------------------------------- ***
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Writing.py", line 445, in <module>
    PWM_x.frequency = float(inp)
  File "/home/mendel/.local/lib/python3.7/site-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 312, in _set_frequency
    self._set_period(1.0 / frequency)
  File "/home/mendel/.local/lib/python3.7/site-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 242, in _set_period
    self._write_pin_attr(self._pin_period_path, "{}".format(period_ns))
  File "/home/mendel/.local/lib/python3.7/site-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 200, in _write_pin_attr
    f_attr.write(value + "\n")
OSError: [Errno 22] Invalid argument
```
</details>

**Comment by hjonnala** [comment]
I think, the error is due to [PWM driver](https://coral.googlesource.com/linux-mtk/+/refs/heads/master/drivers/pwm/pwm-mediatek.c#182) limitation..

**Comment by rodneyML** [comment]
Alright, so what is the direct conclusion? Can it be resolved or should I accept that this is an unfixable limitation?

**Comment by hjonnala** [comment]
This driver is implemented by [Mediatek Team](https://coral.googlesource.com/linux-mtk/+/refs/heads/master/drivers/pwm/pwm-mediatek.c#5) and we don't have any plans to fix/ignore this limitation. If possible, please try your project with [Dev Board](https://coral.ai/products/dev-board) as it would work with frequencies lower than 25. Thanks!

**Comment by rodneyML** [comment]
Luckily I managed a work around, since my project is due Thursday, but I'll keep this in mind for future projects. Thanks
