### ISSUE TITLE
Invoking Inferences on multiple TPUs in parallel

### ISSUE THREAD

**Issue by gsirocco** [google-coral/edgetpu#677]
### Description

I had a clarification on the Invoke function when using multiple TPUs. I'm assuming Invoke is a blocking call and returns when it's finished. If there are 4 TPUs, is there a non-blocking invocation where other TPUs can be invoked while others are busy?
I'm not doing pipelining here, but would really be doing parallel invocations of parts of an input and then combining at the end after all 4 would be complete. Maybe something like a start function and then a function that polls to check that it is complete?
Or would the strategy of using a thread for each Invoke be the preferred method to run these in parallel?

> // Run inference.
> if (interpreter->Invoke() != kTfLiteOk) {
> std::cerr << "Cannot invoke interpreter" << std::endl;
> return 1;
> }

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

M.2 Accelerator with dual Edge TPU

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
please check this example to run multiple models on multiple TPUs(One model on each TPU) at: https://github.com/google-coral/libcoral/blob/master/coral/examples/two_models_two_tpus_threaded.cc#L107

**Comment by gsirocco** [comment]
Thank you, this is very helpful!!
