### ISSUE TITLE
flash.sh is failing, write to device failed

### ISSUE THREAD

**Issue by bsteiner-dandy** [google-coral/edgetpu#680]
### Description

Hi, I am trying to follow the steps of "Flash a new system image" https://coral.ai/docs/dev-board/reflash/#flash-a-new-system-image

These steps are working on my personal laptop, however I am not having luck when trying them using a different laptop, and I am not sure what is going wrong. Here is the output:

```
$ bash flash.sh 
Existing home partition detected, will not flash home (override with -H)
Sending 'bootloader0' (1039 KB)                    OKAY [  0.057s]
Writing 'bootloader0'                              OKAY [  0.139s]
Finished. Total time: 0.219s
Rebooting into bootloader                          OKAY [  0.019s]
Finished. Total time: 0.830s
Sending 'gpt' (33 KB)                              OKAY [  0.022s]
Writing 'gpt'                                      OKAY [  0.223s]
Finished. Total time: 0.267s
Rebooting into bootloader                          OKAY [  0.016s]
Finished. Total time: 0.828s
Erasing 'misc'                                     OKAY [  0.031s]
Finished. Total time: 0.042s
Sending 'boot' (131072 KB)                         FAILED (Write to device failed (No such device))
fastboot: error: Command failed
Failed to execute '/usr/bin/fastboot flash boot ./boot_arm64.img'
```

Anything I should check?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Linux

### Coral Device

Dev Board

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Could you please share the output of below command:

`fastboot devices`

**Comment by bsteiner-dandy** [comment]
Output is: `0c2169d6ef944da7	fastboot`

**Comment by hjonnala** [comment]
Hmm..the flash.sh script working fine for me. Could you please connect the board with [serial console](https://coral.ai/docs/dev-board/serial-console/#connect-with-linux) and check the [logs](https://github.com/hjonnala/snippets/blob/main/devboard/fastboot_flash.txt#L1413).

**Comment by bsteiner-dandy** [comment]
Here is the end of the log when it errors out, let me know if you need more:

```
In:    serial
Out:   serial
Err:   serial

 BuildInfo:
  - ATF 
  - U-Boot 2019.04.1

flash target is MMC:0
Net:   
Warning: ethernet@30be0000 using MAC address from ROM
eth0: ethernet@30be0000
Fastboot: Got bootloader commands!
Configured USB Switch for UFP
request 000000007f95c280 was not queued to ep1in-bulk
request 000000007f95c280 was not queued to ep1in-bulk
erase target is MMC:0
Erasing blocks 278528 to 280576 due to alignment
........ erased 1048576 bytes from 'misc'
request 000000007f95c280 was not queued to ep1in-bulk
request 000000007f95c280 was not queued to ep1in-bulk
request 000000007f95c280 was not queued to ep1in-bulk
WARNING: unknown variable: is-logical:boot
request 000000007f95c280 was not queued to ep1in-bulk
Starting download of 134217728 bytes
request 000000007f95c280 was not queued to ep1in-bulk
..........................................................................
..........................................................................
.....................................................Bad status: -108
```

**Comment by hjonnala** [comment]
> .....................................................Bad status: -108

Not sure the reason for the Bad status. Please try to flash with [sd card](https://coral.ai/docs/dev-board/get-started/#flash-the-board).

**Comment by bsteiner-dandy** [comment]
Any other suggestions? I am able to flash this Coral using my personal laptop, but I would like to setup this other laptop to flash multiple corals. I just don't understand why it would work on one laptop and fail on the other

**Comment by hjonnala** [comment]
Are you getting the same error with other Corals too with the same laptop?

**Comment by bsteiner-dandy** [comment]
Yeah, tried it with two Corals with the same effect

**Comment by hjonnala** [comment]
Seems to be issue with when downloading some data.. not sure the issue is due to Coral device or the laptop. Can you try to flash  with sd card once and then try the flash.sh script.

**Comment by hjonnala** [comment]
can you also try the `sudo bash falsh.sh` as well. Thanks!

**Comment by bsteiner-dandy** [comment]
Slightly different output, but still an error:

```
Sending 'bootloader0' (1039 KB)                    OKAY [  0.029s]
Writing 'bootloader0'                              OKAY [  0.139s]
Finished. Total time: 0.190s
Rebooting into bootloader                          OKAY [  0.018s]
Finished. Total time: 0.880s
Sending 'gpt' (33 KB)                              OKAY [  0.019s]
Writing 'gpt'                                      OKAY [  0.224s]
Finished. Total time: 0.265s
Rebooting into bootloader                          OKAY [  0.017s]
Finished. Total time: 0.880s
Erasing 'misc'                                     OKAY [  0.031s]
Finished. Total time: 0.043s
Sending 'boot' (131072 KB)                         FAILED (Write to device failed in SendBuffer() (Cannot send after transport endpoint shutdown))
fastboot: error: Command failed
Failed to execute '/usr/bin/fastboot flash boot ./boot_arm64.img'
```

**Comment by hjonnala** [comment]
Does both laptops have same fastboot version? and can you try by connecting the dev board to any other laptop usb ports.

**Comment by bsteiner-dandy** [comment]
I think it was the USB port! I swapped which one I had connected to serial and the one for OTG and its working now! Thanks!
