### ISSUE TITLE
Labels not Matching?

### ISSUE THREAD

**Issue by tokenwizard** [google-coral/edgetpu#681]
### Description

I'm using the model and labels files referenced below with an instance of DOOD2 (https://github.com/snowzach/doods2)

It seems the Detection Model is detecting objects but the labels being applied are incorrect. 

I am using the "ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite" model along with the coco_labels.txt, both from the same test_data folder of this project.

It detects the car in the input stream, but labels it as bicycle:
![image](https://user-images.githubusercontent.com/24832561/201155114-d46b5541-4f06-42db-afdc-377e0db9ec62.png)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
It's because pycoral API reads the label file starting with [index 0](https://github.com/google-coral/pycoral/blob/master/pycoral/utils/dataset.py#L20) and DOOD2 API reads the label file with [index 1](https://github.com/snowzach/doods2/blob/master/detectors/labels.py#L5).
