### ISSUE TITLE
Serial peripheral blocks boot

### ISSUE THREAD

**Issue by asymingt** [google-coral/edgetpu#682]
### Description

I have a GNSS module connected to the TX/RX lines of the 40 pin header of a Coral Dev Board Mini. The NMEA sentences appear to block booting, presumably because fastboot or serial console interprets them as input on a tty. Is there a recommended way of handling this correctly. Everything works well if I unplug and replug the lines before and after boot, but that's not a sustainable solution. Thanks!

<details><summary>Click to expand!</summary> 
 
 <details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Programming Language

Other

### Relevant Log Output

_No response_</details></details>

**Comment by asymingt** [comment]
I can confirm this behavior with two different board. The Coral Dev Mini Board never progresses past the Amber LED phase.

![PXL_20221125_003939712.jpg](https://user-images.githubusercontent.com/37671/203878800-e3311576-c750-48e2-9ea0-49700e1d9801.jpg)

**Comment by hjonnala** [comment]
It could be a power supply issue. Can you try the recommendation on page 13( 5.1.3 ) : https://coral.ai/static/files/Coral-Dev-Board-Mini-datasheet.pdf

**Comment by asymingt** [comment]
> It could be a power supply issue. Can you try the recommendation on page 13( 5.1.3 ) : https://coral.ai/static/files/Coral-Dev-Board-Mini-datasheet.pdf

I doubt that's the issue. The largest power consumer on both boards I've tested is the ublox GNSS module, and it's around 120mA@5v, which is a tenth of that threshold.

**Comment by asymingt** [comment]
I'll try and probe the serial line to see what's going on between the GNSS receiver and fastboot on boot. To re-iterate, if I plug the GNSS module or board in *after* boot (status LED on edgetpu board moves to green) everything works as expected.

**Comment by asymingt** [comment]
Looks like fastboot allows you to push any key to stop the boot. So, obviously if you have a GPS unit streaming NMEA sentences at 20Hz, one of the characters is going to look like a keypress on UART0.

Here's what the serial console looks like on boot...

```
...
Settings after calibration ...
=== [DramcRunTimeConfig] ===
HW_GATING: ON
DUMMY_READ_FOR_TRACKING: ON
DFS_HW_SYNC_GATING_TRACKING: OFF
ZQCS_ENABLE: ON
LOWPOWER_GOLDEN_SETTINGS(DCM): ON
SPM_CONTROL_AFTERK: ON
TEMP_SENSOR_ENABLE: OFF
ENABLE_PER_BANK_REFRESH: OFF
HW_SAVE_FOR_SR: OFF
=========================
[MEM] complex R/W mem test pass
NOTICE:  BL2: Booting BL31


U-Boot 2019.10 (Dec 09 2020 - 23:51:30 +0000), Build: jenkins-excelsior.excelsior-bootloader-2

CPU:   MediaTek MT8516
DRAM:  512 MiB
WDT:   Started with servicing (60s timeout)
MMC:   mmc@11120000: 0
Loading Environment from MMC... OK
In:    serial@11005000
Out:   serial@11005000
Err:   serial@11005000
8GB mmc detected
Hit any key to stop autoboot:  0 
u-boot=> 
```

The board just hangs on the final line because the incoming sentences don't match any of the u-boot instructions.

**Comment by hjonnala** [comment]
Hmm.. Thanks for the details. There are two [UARTs](https://coral.ai/docs/dev-board-mini/gpio/#header-pinout) exposed on the header. Can you try to switch the console UART in UBOOT to be UART1?

**Comment by hjonnala** [comment]
Can you also try to see if there is bootdelay in uboot environment variables and set it to -2..https://coral.googlesource.com/u-boot-mtk/+/refs/heads/master/common/Kconfig#357

```
Hit any key to stop autoboot:  0 
u-boot=> printenv
u-boot=>setenv bootdelay -2
u-boot=>saveenv
u-boot=>boot
```

**Comment by asymingt** [comment]
> Hmm.. Thanks for the details. There are two [UARTs](https://coral.ai/docs/dev-board-mini/gpio/#header-pinout) exposed on the header. Can you try to switch the console UART in UBOOT to be UART1?

Thanks, @hjonnala. I have kernel recompilation working, so I can switch or disable the Linux console. But I've never changed the U-Boot UART, I'll need to work out how exactly to do that.

**Comment by asymingt** [comment]
Looks to me like u-boot serial is configured in this way:
```
u-boot=> env print -a
baudrate=115200
...
stderr=serial@11005000
stdin=serial@11005000
stdout=serial@11005000
...
```
I would guess I need to configure stderr, stidin, stdout like this:
```
setenv stderr ...
setenv stdin ...
setenv stdout ...
```
And then persist them with:
```
saveenv
```
I can see from the `bootloader/u-boot/arch/arm/dts/mt8516.dtsi` file that serial@1100500 comes from this block:

```
uart0: serial@11005000 {
    compatible = "mediatek,hsuart";
    reg = <0x11005000 0x1000>;
    reg-shift = <2>;
    interrupts = <GIC_SPI 84 IRQ_TYPE_LEVEL_LOW>;
    clocks = <&topckgen CLK_TOP_UART0_SEL>,
         <&topckgen_cg CLK_TOP_UART0>;
    clock-names = "baud","bus";
    status = "disabled";
};
```

But there is no `uart1` declared. My best guess is that I'd need to recompile the bootloader after adding a block that looks something like this:

```
uart1: serial@11006000 {
    compatible = "mediatek,hsuart";
    reg = <0 0x11006000 0 0x1000>;
    interrupts = <GIC_SPI 85 IRQ_TYPE_LEVEL_LOW>;
    clocks = <&topckgen CLK_TOP_UART1_SEL>,
            <&topckgen CLK_TOP_UART1>;
    clock-names = "baud","bus";
    status = "disabled";
};
``` 

And then do this to move u-boot from UART0 to UART1

```
setenv stderr serial@11006000 
setenv stdin serial@11006000 
setenv stdout serial@11006000
saveenv 
```

**Comment by hjonnala** [comment]
Can you  try to see if there is bootdelay in uboot environment variables and set it to 0 or -2..https://coral.googlesource.com/u-boot-mtk/+/refs/heads/master/common/Kconfig#357

Hit any key to stop autoboot:  0 
u-boot=> printenv
u-boot=>setenv bootdelay 0
u-boot=>saveenv
u-boot=>boot

**Comment by asymingt** [comment]
> Can you  try to see if there is bootdelay in uboot environment variables and set it to 0 or -2..https://coral.googlesource.com/u-boot-mtk/+/refs/heads/master/common/Kconfig#357
> 
> Hit any key to stop autoboot:  0 
> u-boot=> printenv
> u-boot=>setenv bootdelay 0
> u-boot=>saveenv
> u-boot=>boot

I'm a tiny bit worried that if I do this then I won't be able to drop to a u-boot shell if I need to.

**Comment by hjonnala** [comment]
Yes, you won't be able to enter to uboot prompt if its set to -2. But, You would be able to enter to uboot if its set to 0.

**Comment by hjonnala** [comment]
Hi @asymingt are you able to solve this problem either with UART or bootdelay?

**Comment by asymingt** [comment]
> Hi @asymingt are you able to solve this problem either with UART or bootdelay?

I decided that it was easier and safer in the end for me to simply stop using the IMU/GPS board and rather connect a separate GPS module to UART1. This works flawlessly and doesn't require me to awkwardly disable uboot prompt.
