### ISSUE TITLE
It there a way to remove the custom op edgetpu-custom-op from a tflite model file?

### ISSUE THREAD

**Issue by jwallis43** [google-coral/edgetpu#683]
I can can run everything fine on the TPU, however I think at some point
I may need to run the model without a TPU.

Is that possible?

my attempts get:
RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.
See instructions: https://www.tensorflow.org/lite/guide/ops_custom Node number 0 (edgetpu-custom-op) failed to prepare.

**Comment by hjonnala** [comment]
No, it's not possible to remove the edgetpu-custom-op from edgetpu tflite model. You have to use the [uncompiled tflite model](https://github.com/google-coral/test_data) to run the models without a TPU.

**Comment by jwallis43** [comment]
sigh
