### ISSUE TITLE
Disable the LED on the USB accelerator

### ISSUE THREAD

**Issue by G3zz** [google-coral/edgetpu#687]
### Description

Is it possible to permanently disable the coral LED on the USB accelerator? The light can leak into images taken at night.

Thanks

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Operating System

Linux

### Coral Device

USB Accelerator

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
I think, there is no way to disable it as we don't have any API for that (the LED is controlled by MCU firmware). Thanks!

**Comment by G3zz** [comment]
Thanks for confirming, @hjonnala
