### ISSUE TITLE
Add Windows support for Coral Edge TPU M.2/MiniPCIe

### ISSUE THREAD

**Issue by feranick** [google-coral/edgetpu#69]
Currently only the USB accelerator has support for Windows and MacOS. As I rely on the M.2/MiniPCIe version for production, having support for Windows would make the internal accelerator significantly more useful in production, as most of the systems I plan to deploy it in run on Windows.

**Comment by Namburger** [comment]
@feranick 
thanks, I'll put this in as a feature request.

**Comment by Namburger** [comment]
This is now supported!

**Comment by xwyangjshb** [comment]
great job!
