### ISSUE TITLE
Edgetpu link error in Cmake build

### ISSUE THREAD

**Issue by gsirocco** [google-coral/edgetpu#697]
### Description

I am trying to incorporate edgetpu functionality into an existing application which already has it's own build system that uses Cmake. I am getting a link error for 'rdft' undefined reference. It's not clear if this is a build issue, missing library, or an issue with specific version of tensorflow or edgetpu from another [issue](https://github.com/tongtybj/edgetpu_roscpp/issues/5#issuecomment-846348726) solution to the 'rdft' undefined reference. 

```
/usr/bin/ld: /usr/local/lib/libtensorflow-lite.a(spectrogram.cc.o): undefined reference to symbol 'rdft'
/usr/bin/ld: /usr/local/lib//libtensorflow_framework.so.2: error adding symbols: DSO missing from command line
```

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Ubuntu

### Coral Device

M.2 Accelerator B+M

### Programming Language

C++

### Relevant Log Output

```shell
/usr/bin/ld: /usr/local/lib/libtensorflow-lite.a(spectrogram.cc.o): undefined reference to symbol 'rdft'
/usr/bin/ld: /usr/local/lib//libtensorflow_framework.so.2: error adding symbols: DSO missing from command line
```
</details>

**Comment by hjonnala** [comment]
> /usr/bin/ld: /usr/local/lib/libtensorflow-lite.a(spectrogram.cc.o): undefined reference to symbol 'rdft'
> /usr/bin/ld: /usr/local/lib//libtensorflow_framework.so.2: error adding symbols: DSO missing from command line

Looks like the issue is when building the libtensorflow-lite.a. Please try to build it without any edgetpu code and check with [tenosrflow team](https://github.com/tensorflow/tensorflow) team with all the reproducable steps.. Thanks!
