### ISSUE TITLE
Error while trying to run inference on Coral USB Accelerator

### ISSUE THREAD

**Issue by Tridet** [google-coral/edgetpu#70]
I converted a dummy post-quantized model from Tensorflow Lite using `edgetpu_compile <model_path>`. The .log was as follow : 

```
Edge TPU Compiler version 2.0.291256449
Input: head_model.tflite
Output: head_model_edgetpu.tflite

Operator                       Count      Status

MAX_POOL_2D                    1          Mapped to Edge TPU
MUL                            1          Mapped to Edge TPU
QUANTIZE                       3          Mapped to Edge TPU
CONV_2D                        1          Mapped to Edge TPU
```

But when I tried to run inference with it using this code:

```
import tflite_runtime.interpreter as tflite
from PIL import Image
import numpy as np

model_path_main = "mode_edgetpul.tflite"
interpreter = tflite.Interpreter(model_path_main,
                                 experimental_delegates=[tflite.load_delegate('libedgetpu.so.1')])
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

im = Image.open("img.png")
interpreter.set_tensor(input_details[0]['index'], np.copy(np.array(im)[np.newaxis]))
interpreter.invoke()
```

I get this error, and the LED on the Coral USB Accelerator starts to blink with great intensity, even after the program halts (I have to unplug it and plug it back to get it to work after that) : 
```
F :842] transfer on tag 1 failed. Abort. Deadline exceeded: USB transfer error 2 [LibUsbDataOutCallback]

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

I'm using the latest versions of `edgetpu_compiler` and `tflite_runtime`. 
[Here is a link to my model](https://drive.google.com/file/d/1jvHrtBU_dpD6vosBRG8wV_j3-VPCstr3/view?usp=sharing), if you try to visualize it, you will see that it has 2 outputs, which is expected. The input image is simply a 512x512x3 image.

I hope I gave you all the information needed, please do not hesitate to ask for more precisions.

Thanks in advance.

**Comment by yoyomolinas** [comment]
[This issue](https://github.com/google-coral/edgetpu/issues/11) might help

**Comment by Tridet** [comment]
Thank you, I already checked this issue, but I don't actually have a powered USB hub at the moment (I'm using libedgetpu1-std, which should draw less power). Also, contrary to the issue you mentioned, the bug occurs consistently in my case, and I can't seem to run the model at all.

**Comment by Namburger** [comment]
@Tridet humn, I'm actually able to reproduce this on my side, seems like a bug, could I get back with you on this?

**Comment by Tridet** [comment]
@Namburger, thank you very much for your concern ! Here is the tflite model : [link](https://drive.google.com/open?id=1jvHrtBU_dpD6vosBRG8wV_j3-VPCstr3).

**Comment by mtyka** [comment]
@Tridet This model has a large input and an extremely large output size (256x256x32) - this model simply exceeds what the EdgeTPU can handle, especially over USB (The error is indicative of this, since it's timing out on IO to the device). 
If you limit the output to the 512x512x3 output, it *might* work but even that may be too much. FWIW I've been able to create simple U-Net like architectures at 256x256x3 input and output sizes -but even that was really pushing it already.

**Comment by Tridet** [comment]
Thank you for your feedback, I will try to make an architecture with smaller input and output size !
