### ISSUE TITLE
Problem to compile model in edge TPU

### ISSUE THREAD

**Issue by AouatifZ** [google-coral/edgetpu#702]
Hello to all, 

my problem is that my model gives the same results in raspberry pi 4 and edge TPU accelerator, and it means that the model did not compile in edge TPU.

I checked that the model contains only the operations supported by Edge TPU accelerator.(Conv2d, MaxPooling2d,FullyConnected)

also i tried to find information about the total number of compiled and calculated operations in Edge TPU but without results, i found that edgetpu-compiler package is no longer available for arm platform .

any help please to resolve my problem

thanks in advance

**Comment by hjonnala** [comment]
Please try the web based edgetpu compiler: https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb . Thanks!
