### ISSUE TITLE
Power off coral in automated fashion without restart

### ISSUE THREAD

**Issue by roechslin** [google-coral/edgetpu#705]
### Description

Hi,

We want to have an automated way of powering the coral board, processing images and shutting it down after processing.

This [issue ](https://github.com/google-coral/edgetpu/issues/527) explains that the coral may crash when the power is cut abruptly, as it cannot shut down gracefully.

The link that @PeterMalkin provided to configure a boot in read-only mode is specific to raspberry pi's and doesn't work for coral boards.
Could you please mention the necessary steps to boot the coral board in read-only mode? 
We are facing the issue that we cannot shut down our edge device gracefully and therefore the devices regularly crash and need to be reflashed. Is there an alternative to the read-only mode to avoid crashing the devices?

**Our setup:**
1. event happens
2. coral board is being powered externally over power+data cable (uController takes care of this)
3. coral board runs inference on an image
4. we turn the coral board off with either of the two:

- **a)** coral board shuts itself off gracefully
- since power is still ON in the power+data cable, the coral restarts -> unwanted behavior

- **b)** cut the external power from the power+data cable
- coral crashes with high likelihood and needs manual intervention -> unwanted behavior

**Things we have tried:**
- Power cable -> this requires the click of a button in order to start the coral. In our use case this is not possible.
- Ungraceful power cut -> devices crash
- Shutdown from coral and timed external power cut -> difficult to synchronize and devices may crash
- Leaving the device powered -> we run out of battery too soon

**Expected behavior:**
We would like to turn the coral board off, without it restarting.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Other Devices

Raspberry Pi 3

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @roechslin if possible please try the following things:
1) power the board with power port
2) issue the shutdown command via wifi ssh 
3) reboot the board with power button rework --- control the short with external MCU

**Comment by roechslin** [comment]
Hi @hjonnala 

Thanks for the quick answer. I understand: you want me to solder (or short-circuit on demand) the power button / TP of the coral-board with our MCU.

We are looking at a solution that can scale out with hundreds or thousands of devices. In such a scenario hand-soldering individual devices will not be feasible. 
Our MCU is attached on a custom HAT on top of the coral. Is there a way to reprogram the push button (eg. GPIO 9) to control the power button?

**Comment by hjonnala** [comment]
> Is there a way to reprogram the push button (eg. GPIO 9) to control the power button?

I don't think its possible. https://github.com/google-coral/edgetpu/issues/442#issuecomment-900744074

**Comment by roechslin** [comment]
Hi okey, thanks for the answer. Our approaches are now to:

- either solder an interrupt cable directly to the PWR_KEY to control via the OTG cable or
- leave a second charging cable into the OTG connector which is always ON
