### ISSUE TITLE
EdgeTPU Compiler: Compilation failed.

### ISSUE THREAD

**Issue by MalekItani** [google-coral/edgetpu#707]
### Description

I'm trying to compile a very simple PyTorch model and run it on the Google Coral EdgeTPU. My procedure looks like this: PyTorch -> ONNX -> TensorFlow -> TFLite -> TFLite (EdgeTPU).

I can go through the first 4 steps without major issues, but when I want to compile to using the web-based edgetpu_compiler, I'm told the compilation fails, without any other information at all. This is my original PyTorch model:

```
class Net(nn.Module):
    def __init__(self, channels, kernel_size):
        super(Net, self).__init__()
        self.C = channels
        self.K = kernel_size

        self.conv1 = nn.Conv1d(in_channels=1,
                    out_channels=self.C, kernel_size=self.K)
        self.relu = nn.ReLU()
        self.conv2 = nn.Conv1d(in_channels=self.C,
                                out_channels=1, kernel_size=self.K)

   def forward(self, x, y):
        y = torch.mean(y.transpose(1, 2), dim=-1).unsqueeze(2)
        x = self.conv1(x)
        x = self.relu(x)
        x = x + y
        x = self.conv2(x)
        x = self.relu(x)
        return x
```

Here is the TFLite model generated before edge TPU compilation. How can I debug the compilation process?

[model.tflite.zip](https://github.com/google-coral/edgetpu/files/10387174/model.tflite.zip)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

Dev Board

### Programming Language

Python 3.8

### Relevant Log Output

```shell
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 1000 seconds.
Compilation child process completed within timeout period.
Compilation failed!
```
</details>

**Comment by hjonnala** [comment]
Hi, You would be able to compile the model with -d -a flags(! edgetpu_compiler -s -d -a model.tflite). Please try  reducing the model input shapes to map all the ops to TPU..

**Comment by MalekItani** [comment]
Thanks. After reducing the input sizes, I was able to successfully compile, and map most of the ops to the TPU.

**Comment by MalekItani** [comment]
Hi @hjonnala, I compiled the model above into the EdgeTPU compatible TFLite model attached. I now face a different problem.

I'm trying to load the TFLite interpreter to run inference on the EdgeTPU using the following code (as is done [here](https://coral.ai/docs/edgetpu/tflite-python/#update-existing-tf-lite-code-for-the-edge-tpu)):

```
    import tflite_runtime.interpreter as tflite

    ...

    delegate = tflite.load_delegate('libedgetpu.so.1')
    interpreter = tflite.Interpreter(model_path='model_edgetpu.tflite', experimental_delegates=[delegate]) # Segfault here
    interpreter.allocate_tensors()

```

I can load precompiled edgetpu models (like the ones [here](https://coral.ai/models/object-detection/)) just fine, but when I try to initialize the interpreter for my custom model, I run into a segmentation fault, and the program just exits. Is this something you can help with?

[model_edgetpu.tflite.zip](https://github.com/google-coral/edgetpu/files/10416469/model_edgetpu.tflite.zip)

**Comment by hjonnala** [comment]
I am able to run the inference. Please try the script located at: https://github.com/hjonnala/snippets/blob/main/coral_inference.py

Also, please cross the check the versions that you have:
```
hemanthj@:~$ python3 -c "import tflite_runtime as tflite; print('tflite runtime vesrion:', tflite.__version__);import pycoral; print('pycoral version:', pycoral.__version__)"
tflite runtime vesrion: 2.5.0.post1
pycoral version: 2.0.0
```

**Comment by MalekItani** [comment]
Once again, thank you very much. For whatever reason, the error had occured due to tflite-runtime version; any version above 2.9.1 causes a segmentation fault. I downgraded to 2.9.1 and can now run inference.

**Comment by noahwalugembe** [comment]
Am gating  this error {Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
Compilation child process completed within timeout period.
Compilation failed!} how can i deal with it

**Comment by jschauerUdS** [comment]
@noahwalugembe did you fixed that error?
I got the same error ...
