### ISSUE TITLE
Coral External Wi-Fi Antenna

### ISSUE THREAD

**Issue by mdanish1994** [google-coral/edgetpu#710]
Hi,

Can someone please help me with the external Wi-Fi antenna which can be connected to the J1301 and J1302? I'm not able to find any external antenna matching the UFL antenna on the board.

Thanks,

**Comment by hjonnala** [comment]
Hi, could please specify which coral product you are referring to?

**Comment by mdanish1994** [comment]
Hi,

We are using the google coral dev board. I have added the link below for the board which we are using.
[](https://coral.ai/products/dev-board/)

**Comment by mdanish1994** [comment]
https://coral.ai/products/dev-board/

**Comment by hjonnala** [comment]
Hi, 

we don't have any recommended pluggable antenna.

The J1301/J1302 are mounted with the RF switch "Murata MM8930-2600" and you can attach an external antenna, but you have to use Murata's dedicated male connector. Another option is that you can remove the J1301/J1302 and solder Antenna's RF cable directly to the pad.

The RF switch is only for RF test use in factory or lab evaluation. Feel free to  rework and solder the pins, and pick whichever antenna for test and evaluation, we haven't qualified any.
