### ISSUE TITLE
Core dumped with coral

### ISSUE THREAD

**Issue by JasseurHadded1** [google-coral/edgetpu#712]
### Description

Hello,

I have my own tflite model and I want to run it with Coral Usb accelerator, I did the quantization and I compile it with the edgetpu_compiler, when I load the model with interpreter and then I allocate tensors I get Segmentation fault, The tflite models (quantized and not) works well, and I have tried coral with the classify_images example and it worked well.

Any explication or solution for that?

my tensorflow version is 2.12.0 and my tflite version is 2.11.0

Thanks

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Please try with official [pycoral:2.0.0 and tflite_runtime version:2.5.0post1](https://coral.ai/software/#pycoral-api) or try downgrading the tflite runtime version <= 2.9.1: https://github.com/google-coral/edgetpu/issues/707#issuecomment-1385988458

```
hemanthj@:~$ python3 -c "import tflite_runtime as tflite; print('tflite runtime vesrion:', tflite.__version__);import pycoral; print('pycoral version:', pycoral.__version__)"
tflite runtime vesrion: 2.5.0.post1
pycoral version: 2.0.0
```

**Comment by JasseurHadded1** [comment]
Thanks for the answer,

Before I see your comment I have tried it with:
tf version = 2.11.0
tflite_runtime version = 2.11.0
no pycoral installed

And it worked

I'll come back if it bugs again

**Comment by JasseurHadded1** [comment]
I close it because it's resolved, I'll reopen it if it bugs again
