### ISSUE TITLE
GAN: Usb accelerator Vs CPU: Same Performance 

### ISSUE THREAD

**Issue by JasseurHadded1** [google-coral/edgetpu#713]
### Description

Hello,

I have a trained GAN model, I have wanted to increase its inference time performance, I have quantized it then I have compiled it with edgetpu_compiler and I have turned it on USB accelerator, but I got the same performance with cpu (quantized model before edgetpu compilation).

The model was trained with LeakyRelu activation function which is not supported by the edge tpu, so I just used the Relu function in inference instead of LeakyRelu, I know it will decrease accuracy but my aim now is juste to know the time gain with the edge tpu.

Do you know any solution for that? Do you think that's related to the change of LeakyRelu to Relu?

Ps: I have tested the classification example of google coral and I got better performance

Thanks,

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Please share the uncompiled tflite model and the compiler logs.

**Comment by JasseurHadded1** [comment]
Thanks for your answer, but I can't share it for confidentiality reasons!

**Comment by hjonnala** [comment]
If its ok, please share the compiler logs (! edgetpu_compiler -s model.tflite). Otherwise please build the [libcoral](https://github.com/google-coral/libcoral) with the below steps and try the [single_model_enchmark](https://github.com/google-coral/libcoral/blob/master/coral/single_model_benchmark.cc) script.

```
git clone --recurse-submodules https://github.com/google-coral/libcoral
cd libcoral
make docker-shell
make CPU=k8 benchmarks
```

```

hemanthr@hemanth-glaptop:~/libcoral/out/k8/benchmarks/coral$ ./single_model_benchmark -model ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
2021-12-10 08:30:12
Running ./single_model_benchmark
Run on (4 X 3900 MHz CPU s)
CPU Caches:
  L1 Data 32K (x2)
  L1 Instruction 32K (x2)
  L2 Unified 256K (x2)
  L3 Unified 4096K (x1)
Load Average: 1.07, 1.04, 1.00
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_Model         11.7 ms         4.16 ms          131 ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
```
