### ISSUE TITLE
Coral fails at a temperature of -10 C

### ISSUE THREAD

**Issue by muxamilian** [google-coral/edgetpu#716]
### Description

When using the Coral in a production device deployed outside, we noticed that the Coral fails in winter at temperatures less than 0 C. We suspect that cold temperature is causing the error. According to the datasheet the Coral is supposed to work at -20 C or more but we're certain that the temperature did not drop below -10 C. 

To reproduce, we conducted climate cabinet tests at -10 C:
- Leave computer with Coral in climate cabinet for a couple of hours at -10 C. The computer is running, but the Coral is not in use.
- Restart Linux
- Try to use Coral for inference
- Coral fails with `E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000000010, hib_first_error_status = 0000000000000010`

The error can be fixed following these steps:
- Warm up device to 20 C
- Restart Linux
- Try to use Coral for inference
- Coral works again

It is important to note that the Coral never failed while it was actively being used. The error only occurs when the Coral has not been in use and then one tries to use it. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Linux

### Coral Device

M.2 Accelerator A+E

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, can you please share the EdgeTPU temperature when Coral fails using the below command.

`cat /sys/class/apex/apex_0/temp`

**Comment by muxamilian** [comment]
Don't have that file:

```
total 0
lrwxrwxrwx 1 root root    0 Feb  3 15:56 0000:01:00.0 -> ../../../0000:01:00.0
-r--r--r-- 1 root root 4096 Feb  3 15:56 bar_offsets
-r--r--r-- 1 root root 4096 Feb  3 15:56 bar_sizes
-r--r--r-- 1 root root 4096 Feb  3 15:56 dev
lrwxrwxrwx 1 root root    0 Feb  3 15:56 device -> ../../../0000:01:00.0
-r--r--r-- 1 root root 4096 Feb  3 15:56 device_owner
-r--r--r-- 1 root root 4096 Feb  3 15:56 device_type
-r--r--r-- 1 root root 4096 Feb  3 15:56 driver_version
-r--r--r-- 1 root root 4096 Feb  3 15:56 framework_version
-r--r--r-- 1 root root 4096 Feb  3 15:56 interrupt_counts
-r--r--r-- 1 root root 4096 Feb  3 15:56 is_device_owned
-r--r--r-- 1 root root 4096 Feb  3 15:56 node_0_num_mapped_pages
-r--r--r-- 1 root root 4096 Feb  3 15:56 node_0_page_table_entries
-r--r--r-- 1 root root 4096 Feb  3 15:56 node_0_simple_page_table_entries
-r--r--r-- 1 root root 4096 Feb  3 15:56 pci_address
drwxr-xr-x 2 root root    0 Feb  3 15:56 power
-r--r--r-- 1 root root 4096 Feb  3 15:56 reset_count
-r--r--r-- 1 root root 4096 Feb  3 15:56 revision
-r--r--r-- 1 root root 4096 Feb  3 15:56 status
lrwxrwxrwx 1 root root    0 Feb  3 15:56 subsystem -> ../../../../../../class/apex
-rw-r--r-- 1 root root 4096 Feb  3 10:32 uevent
-r--r--r-- 1 root root 4096 Feb  3 15:56 user_mem_ranges
-r--r--r-- 1 root root 4096 Feb  3 15:56 write_open_count
```

**Comment by hjonnala** [comment]
Okay.. could you please share the status file output when Coral fails:

`cat /sys/class/apex/apex_0/status`

**Comment by muxamilian** [comment]
Attached is a copy of the directory `/sys/class/apex/apex_0` after the error occurs. 
[apex_0.zip](https://github.com/google-coral/edgetpu/files/10673987/apex_0.zip)

**Comment by hjonnala** [comment]
Thanks.. Seems to be all [temperature](https://coral.ai/docs/pcie-parameters/) related files are missing. I suspect inbuilt TPU temp sensor might got damaged. Wondering do you have any more M.2 A+E key devices? Is it the same case for other devices?

```
mendel@indigo-bunny:~$ ls /sys/class/apex/apex_0
0001:01:00.0  dev           device_type        hw_temp_warn1     hw_temp_warn2_en  node_0_num_mapped_pages           pci_address  revision   temp                trip_point1_temp  user_mem_ranges
bar_offsets   device        driver_version     hw_temp_warn1_en  interrupt_counts  node_0_page_table_entries         power        status     temp_poll_interval  trip_point2_temp  write_open_count
bar_sizes     device_owner  framework_version  hw_temp_warn2     is_device_owned   node_0_simple_page_table_entries  reset_count  subsystem  trip_point0_temp    uevent
mendel@indigo-bunny:~$ 
```

**Comment by muxamilian** [comment]
I checked on numerous Corals we have have, there were no temperature files in any of them. Some of them were never exposed to the cold, so it can't be that the thermometer broke in all of them I guess. 

Could it be that your Coral is from a different production series? Maybe yours is newer and our old version doesn't have the thermometer yet.

**Comment by hjonnala** [comment]
My outputs are form CoraL Dev Board(PCIe device). Can you please share the output of below command:

```
mendel@indigo-bunny:~$ sudo modinfo apex
filename:       /lib/modules/4.14.98-imx/kernel/drivers/staging/gasket/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.1
description:    Google Apex driver
srcversion:     A480A03FFEEB8547EBFE5A0
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
staging:        Y
intree:         Y
name:           apex
vermagic:       4.14.98-imx SMP preempt mod_unload aarch64
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
parm:           trip_point0_temp:int
parm:           trip_point1_temp:int
parm:           trip_point2_temp:int
parm:           hw_temp_warn1:int
parm:           hw_temp_warn2:int
parm:           hw_temp_warn1_en:bool
parm:           hw_temp_warn2_en:bool
parm:           temp_poll_interval:int
```

**Comment by muxamilian** [comment]
```
$ sudo modinfo apex
filename:       /lib/modules/5.10.64-vrx-73678b2f.1065734/kernel/drivers/staging/gasket/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.0
description:    Google Apex driver
srcversion:     A59D430D2A073385D2E7062
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
staging:        Y
retpoline:      Y
intree:         Y
name:           apex
vermagic:       5.10.64-vrx-73678b2f.1065734 SMP mod_unload
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        35:5E:AF:99:B0:C1:AE:A0:9B:4E:41:32:0E:63:E3:7D:54:B9:CE:27
sig_hashalgo:   sha512
signature:      64:4F:5C:F6:70:EB:6A:C4:31:DC:18:5F:0F:84:5C:46:03:6C:3F:00:
                A0:E7:D5:3C:C0:FE:7C:68:1C:63:9C:B2:10:8C:B5:26:2B:57:9F:74:
                4F:0C:DB:5B:1F:FB:40:99:2E:28:77:B3:52:38:4B:94:08:70:FF:D6:
                4A:98:74:84:7A:01:7E:59:64:5B:26:4F:07:C8:22:EB:28:B9:02:28:
                39:B2:64:C3:EC:6A:95:30:D0:32:C4:D6:EB:B0:BD:78:20:FD:68:11:
                C8:A3:15:C4:34:DF:52:77:C5:B0:93:5A:6A:C3:F0:23:72:4C:E0:E3:
                B8:2F:BF:40:73:B3:5D:21:F0:F3:5A:69:5C:3B:6B:B8:D7:6C:BB:AC:
                B4:A9:88:B1:37:46:04:46:50:24:9C:D5:76:D2:39:9C:D6:CA:09:30:
                44:C7:1D:D2:B0:87:CB:F9:11:C1:8A:E2:AC:2D:8D:13:DA:93:55:67:
                B9:C0:4C:DA:24:30:01:B8:61:E1:78:77:97:DC:A7:A0:9D:35:E7:CA:
                D5:57:EB:FC:90:FB:5D:A5:C8:C8:61:30:1F:C3:59:55:9D:67:7C:E8:
                8A:82:2C:61:E9:41:03:EE:1D:6F:62:BB:7E:40:6E:06:F5:D0:23:B4:
                22:61:E3:99:DD:20:52:05:D6:2B:13:A2:32:EF:91:0E:89:59:22:53:
                62:D1:8D:FD:0A:0C:5B:4F:F7:65:7A:DF:4D:8E:06:65:4A:01:24:51:
                03:D2:D2:B1:0D:45:38:AC:FC:06:81:FE:F3:A2:8D:A3:35:5C:B7:D4:
                AF:2B:D0:B1:19:AD:73:5A:BA:9E:CB:D9:7A:62:C2:06:66:59:78:22:
                52:45:89:F6:E2:33:A8:BC:FC:1B:A1:7C:D0:A2:AC:60:A5:C5:3B:E2:
                55:AF:36:38:AB:7B:BE:D9:45:23:A1:06:0C:AC:F1:F0:91:1E:2A:63:
                A7:A0:02:9F:5F:AE:C1:D8:3D:AC:E8:56:99:EF:DF:8C:CF:FD:23:EF:
                41:E0:48:BE:5F:5B:EC:15:C3:D1:E1:D8:1C:51:ED:57:31:B9:53:AC:
                41:62:4C:F5:50:39:8B:84:1B:98:B0:9C:F6:B9:17:A9:2E:15:8C:67:
                87:45:6E:63:0D:3E:58:09:80:53:25:24:BE:EE:FF:27:54:EE:0C:0D:
                32:9C:C6:66:FF:FB:BD:E3:1A:EF:73:60:06:F4:B6:DB:7F:68:A7:D4:
                86:20:97:60:BD:C6:02:78:E4:30:16:5E:D3:0B:DC:DE:AD:03:50:5E:
                41:34:CA:46:59:C3:7A:C2:C5:3B:8E:A0:50:B6:1B:28:16:FB:3A:61:
                3F:B3:C3:F0:C3:7B:26:94:9C:AD:D0:B2
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
```

**Comment by hjonnala** [comment]
Have you built the driver form the [gasket-driver source](https://github.com/google/gasket-driver)? Can you please share the output of `ls /sys/class/apex/apex_0 -a`

**Comment by muxamilian** [comment]
The kernel is self-compiled, but the sources related to TPU support are from the main line kernel of Debian 11: 5.10.64. 

However, I have the impression that it's rather a hardware than a software issue. 

```
$ ll -aH /sys/class/apex/apex_0
total 0
drwxr-xr-x 3 root root    0 Feb  7 09:07 .
drwxr-xr-x 3 root root    0 Feb  7 09:07 ..
lrwxrwxrwx 1 root root    0 Feb  7 09:20 0000:01:00.0 -> ../../../0000:01:00.0
-r--r--r-- 1 root root 4096 Feb  7 09:20 bar_offsets
-r--r--r-- 1 root root 4096 Feb  7 09:20 bar_sizes
-r--r--r-- 1 root root 4096 Feb  7 09:20 dev
lrwxrwxrwx 1 root root    0 Feb  7 09:20 device -> ../../../0000:01:00.0
-r--r--r-- 1 root root 4096 Feb  7 09:20 device_owner
-r--r--r-- 1 root root 4096 Feb  7 09:20 device_type
-r--r--r-- 1 root root 4096 Feb  7 09:20 driver_version
-r--r--r-- 1 root root 4096 Feb  7 09:20 framework_version
-r--r--r-- 1 root root 4096 Feb  7 09:20 interrupt_counts
-r--r--r-- 1 root root 4096 Feb  7 09:20 is_device_owned
-r--r--r-- 1 root root 4096 Feb  7 09:20 node_0_num_mapped_pages
-r--r--r-- 1 root root 4096 Feb  7 09:20 node_0_page_table_entries
-r--r--r-- 1 root root 4096 Feb  7 09:20 node_0_simple_page_table_entries
-r--r--r-- 1 root root 4096 Feb  7 09:20 pci_address
drwxr-xr-x 2 root root    0 Feb  7 09:20 power
-r--r--r-- 1 root root 4096 Feb  7 09:20 reset_count
-r--r--r-- 1 root root 4096 Feb  7 09:20 revision
-r--r--r-- 1 root root 4096 Feb  7 09:20 status
lrwxrwxrwx 1 root root    0 Feb  7 09:20 subsystem -> ../../../../../../class/apex
-rw-r--r-- 1 root root 4096 Feb  7 09:07 uevent
-r--r--r-- 1 root root 4096 Feb  7 09:20 user_mem_ranges
-r--r--r-- 1 root root 4096 Feb  7 09:20 write_open_count
```

**Comment by hjonnala** [comment]
ok..I would like to know TPU temperature when coral fails. could you please build the [gasket-driver](https://github.com/google/gasket-driver) from the [source](https://github.com/google/gasket-driver/blob/main/src/apex_driver.c#L87) and see if you can get the output of `cat /sys/class/apex/apex_0/temp` when coral fails. Thanks!

**Comment by muxamilian** [comment]
I'm not sure if recompiling the driver from source is feasible for us at the moment. 

However, I can give you the outputs of some other temperature sensors in the device. The climate cabinet in which the device is located is kept at a constant -10 C. 

```
$ sensors
[...]
mcp980x-i2c-1-48
Adapter: Synopsys DesignWare I2C adapter
i2c slot 1:    -2.4°C  (high = +80.0°C, hyst = +75.0°C)

pch_skylake-virtual-0
Adapter: Virtual device
temp1:         -6.0°C
```

**Comment by muxamilian** [comment]
The number in `/sys/class/apex/apex_0/temp` is 10300. 

I updated to the newest driver, repeated the tests and the Coral still fails. Attached is a zip file with all the debug info. 
[apex_0.zip](https://github.com/google-coral/edgetpu/files/10848652/apex_0.zip)

**Comment by muxamilian** [comment]
What does `hib_error_status = 0000000000000010` mean actually?

**Comment by hjonnala** [comment]
> What does `hib_error_status = 0000000000000010` mean actually?

I think, It's an internal chip error. May I please know the model that you are running and is it the same case for any other models too?

**Comment by muxamilian** [comment]
The model is a MobileDet which was trained based on your [manual](https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_ssdlite_mobiledet_qat_tf1.ipynb). Unforunately, I'm not allowed to share the model as it is proprietary. 

I haven't tried with other models yet. I can report to you if it happens for other models. I would assume that it doesn't work in general. 

Does the error code `hib_error_status = 0000000000000010` reveal any additional information regarding what exactly is not working in the chip? Is it a bus error? Or actually an error inside the chip? 

I can also recommend you try to reproduce the error in a climate cabinet following the test procedure I outlined in the first message.

**Comment by muxamilian** [comment]
Any updates? It would be interesting to know what the actual minimum operating temperature of the Coral is and what exactly is causing the problem.

**Comment by hjonnala** [comment]
Unfortuantely, I don't have any updates on this. I think, the temperatures stated in datasheet are acurate as they were tested with the apporved thermal test plan procedures during the development phase. 

Wondering if you are able to test it with any other models or different operaitng system? Thanks!!

**Comment by muxamilian** [comment]
If I have more results I'll let you know. 

Can you give me some more information on your approved thermal test plan? I'm curious if it deviates from the one that I used.

**Comment by muxamilian** [comment]
After further tests it seems that the problem is that the mainboard has temperature issues and this affects the Coral. The Coral itself, however, seems to not be the root cause.
