### ISSUE TITLE
FlexSplitV Select TF Op failed to prepare

### ISSUE THREAD

**Issue by AidanAbramson** [google-coral/edgetpu#718]
### Description

Hi!
I'm trying to convert a model from tflite to edgetpu tflite with the compiler.

When I run the command I get the following error:
```
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 292 ops
Started a compilation timeout timer of 180 seconds.
ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
ERROR: Node number 13 (FlexSplitV) failed to prepare.

Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 282 ops
```

When I tried to convert the model from a Keras model to tflite, I got a similar error which was simply fixed by adding converter.target_spec.supported_ops.append(tf.lite.OpsSet.SELECT_TF_OPS).

Is there something similar to be done here?
Thanks.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Linux, Ubuntu

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi you won't be able to compile if there are any flex operations in the model. Please try to compile after removing/replacing the flex ops from the model. Thanks!

**Comment by AidanAbramson** [comment]
@hjonnala Thanks for the reply! What wold be the best way to replace the flex ops?

Edit:
Also had another question. In the edgetpu docs, it is stated that the Split operation is support. Are the FlexSplitV and Split ops not the same? If so, could I replace one with the other? Thanks.

**Comment by hjonnala** [comment]
> In the edgetpu docs, it is stated that the Split operation is support. Are the FlexSplitV and Split ops not the same? If so, could I replace one with the other? Thanks.

Both are not same.. [splitv](https://www.tensorflow.org/api_docs/python/tf/raw_ops/SplitV) supports uneven split whereas [split](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Split) operation evenly divides the tensor.  If that works you can replace splitv with split operation.
