### ISSUE TITLE
TF model to TFLite and TPU conversion that has custom ops

### ISSUE THREAD

**Issue by gsirocco** [google-coral/edgetpu#719]
### Description

I have a TF model that I want to run entirely on TPU. So I am converting it to TFLite, however when converting it, it cannot be converted to TFLite because it has some custom ops as in the log output. There is a way to register the customs ops in lite kernels and follow [custom_ops documentation](https://www.tensorflow.org/lite/guide/ops_custom) to make it convert to TFLite. The question I have however, is if I go through this process to create a TFLite model with custom ops will I be able to run it on TPU entirely or will I still have to do some conversion of the model to other operators to be able to run on TPU? Thanks for your suggestion on this I want to avoid converting it using the custom op process only to find I have to convert it again for TPU. Thanks for any advice on how to proceed to get this to convert and run on TPU.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

M.2 Accelerator A+E

### Programming Language

Python 3.9

### Relevant Log Output

```shell
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TF Select ops: AsString, FloorDiv, FloorMod, HashTableV2, LookupTableFindV2, LookupTableImportV2, ReduceJoin
Details:
        tf.AsString(tensor<2025x4xi8>) -> (tensor<2025x4x!tf_type.string>) : {device = "", fill = "", precision = -1 : i64, scientific = false, shortest = false, width = -1 : i64}
        tf.FloorDiv(tensor<2025x1x1xui8>, tensor<8xui8>) -> (tensor<2025x1x8xui8>) : {device = ""}
        tf.FloorMod(tensor<2025x1x8xi8>, tensor<i8>) -> (tensor<2025x1x8xi8>) : {device = ""}
        tf.HashTableV2() -> (tensor<!tf_type.resource>) : {container = "", device = "", key_dtype = !tf_type.string, shared_name = "61254", use_node_name_sharing = false, value_dtype = i32}
        tf.LookupTableFindV2(tensor<!tf_type.resource>, tensor<2025x!tf_type.string>, tensor<i32>) -> (tensor<*xi32>) : {device = ""}
        tf.LookupTableImportV2(tensor<!tf_type.resource>, tensor<16x!tf_type.string>, tensor<16xi32>) -> () : {device = ""}
        tf.ReduceJoin(tensor<2025x4x!tf_type.string>, tensor<i32>) -> (tensor<2025x!tf_type.string>) : {device = "", keep_dims = false, separator = ""}
```
</details>

**Comment by hjonnala** [comment]
> The question I have however, is if I go through this process to create a TFLite model with custom ops will I be able to run it on TPU entirely

No, you won't be able to run custom ops on TPU.

To run the model entirely on TPU, model should have only supported operations mentioned at: https://coral.ai/docs/edgetpu/models-intro/#supported-operations

**Comment by gsirocco** [comment]
Thanks this makes sense
