### ISSUE TITLE
PCIe TPU Compatibility with AXI-PCIe Root Port - MSI supported but not MSI-X

### ISSUE THREAD

**Issue by jsg59** [google-coral/edgetpu#724]
### Description

Hello, 

I'm trying to use the [AXI-PCIe root port bridge](https://docs.xilinx.com/r/en-US/pg194-axi-bridge-pcie-gen3) offered by Xilinx with the PCIe Edge TPU.

In the root port configuration, it appears the AXI-PCIe root port bridge only supports single MSI, but not MSI-X: https://github.com/Xilinx/linux-xlnx/blob/master/drivers/pci/controller/pcie-xilinx.c#L273

@mbrooksx indicated that the Edge TPU with PCIe requires MSI-X in [Issue 122](https://github.com/google-coral/edgetpu/issues/122). Are there any Apex driver modifications we can make to use just single MSI, but not MSI-X?

Any advice would be very much appreciated.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

Accelerator Module

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, [AXI-PCIE root bridge](https://docs.xilinx.com/r/en-US/pg194-axi-bridge-pcie-gen3) documentation says it supports MSI-X. If its not, please check with them on how to change pcie-xlinux.c to support for MSI-X. Thanks!! 

![image](https://user-images.githubusercontent.com/86132058/220479223-a61903f8-df85-4785-8337-e97cf0b8bfb6.png)

![image](https://user-images.githubusercontent.com/86132058/220479779-f12f38cb-dfa2-4fda-ae40-cabbe97d2b74.png)
