### ISSUE TITLE
Adding hwmon support so temperature can be monitored by lm-sensors

### ISSUE THREAD

**Issue by mattncsu** [google-coral/edgetpu#725]
### Description

I [reached out to the guys behind lm-sensors](https://github.com/lm-sensors/lm-sensors/issues/429) because I wanted to be able to track the edge tpu temperature (dual tpu card).  They said it would work if the edgetpu driver was in the mainline kernel and had hwmon support.  Is that something reasonable to add in the future?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Operating System

Linux, Ubuntu

### Coral Device

Mini PCIe, M.2 Accelerator A+E, M.2 Accelerator B+M, M.2 Accelerator with dual Edge TPU

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @mattncsu unfortunately, we don't have plans to add hwmon support. Thanks!!
