### ISSUE TITLE
 edgetpu segmentation fault using tflite-runtime 2.5.0 - aarch64 GNU/Linux

### ISSUE THREAD

**Issue by seydang** [google-coral/edgetpu#731]
I compiled tflite_runtime using the official source of tensorflow, but it leads to a segmentation fault.
I used the following commands in:
https://coral.ai/docs/edgetpu/tflite-python/#update-existing-tf-lite-code-for-the-edge-tpu

System: 
$ uname -a
Linux orange-rabbit 4.19.125-mtk #1 SMP PREEMPT Thu Dec 10 02:36:13 UTC 2020 aarch64 GNU/Linux
$ python3 -V
Python 3.7.3

**Comment by hjonnala** [comment]
Hi, which [tensorflow commit](https://github.com/google-coral/libedgetpu/blob/release-grouper/workspace.bzl#L9) are you using? If its not 2.5.0 please go through the instructions at : https://coral.ai/docs/notes/build-coral/ to build libedgetpu, pycoral and tflite_runtime. 

And, the above packages comes with mendel linux for Dev Board Mini. There is no need to compile or install them. Thanks!

**Comment by seydang** [comment]
I am using tensorflow==2.11.0. 
Could you please explain what to do in the link you sent?
