### ISSUE TITLE
Coral Edge not installing properly on Asus motherboard

### ISSUE THREAD

**Issue by ClearlyDazed** [google-coral/edgetpu#734]
My Coral Edge TPU (B+M key) will not install properly. It knocks off my onboard ethernet connection on the system.

The system is running Ubuntu 22.04LTS on an Asus Prime X570-P motherboard with an AMD Ryzen 5 3600 (Zen2) 3rd gen processor.
A GeForce GTX 1660 Super in the PCIeX16_1 slot, a NVMe SSD in the M2_1 socket, and 3 harddrives are connected to SATA6_1, _2 and _3.
Attempted to install the Coral TPU on the M2_2 socket. The initial attempt as state caused the ethernet connection to be dropped.

I have now updated my BIOS to the latest. I will attempt to do a clean install again as stated on https://coral.ai/docs/m2/get-started/#requirements .

Is my current hardware able to accept the coral TPU and are there any suggestions to get it working?

PS. Problem solved: a linux network issue

**Comment by pfeiffee** [comment]
Anyone know what causes this or how it was solved? I am facing the exact same issue. Issue happens when directly in M.2 slot and also M.2 -> PCI adapter. 

I am running an install of Ubuntu 22.04, nearly fresh with only docker and nvidia drivers installed.

**Comment by Doug411** [comment]
Anyone solve this?  I have this problem on a Minisforum MS-01 with a dual edge TPU installed in a m.2 slot with the magic blue smoke m.2 adapter.  I'm running Proxmox (debian 12).
