### ISSUE TITLE
Edge TPU Not On PCI Bus

### ISSUE THREAD

**Issue by weswitt** [google-coral/edgetpu#735]
### Description

i'm using an m.2 edge tpu in an asus b560m-a motherboard. running linux debian 11 and the tpu does not enumerate on the pci bus. lspci shows no device. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Linux

### Coral Device

M.2 Accelerator B+M

### Relevant Log Output

```shell
i see nothing in dmesg or syslog indicating any problem.
```
</details>

**Comment by weswitt** [comment]
this was a hardware issue with my mobo

**Comment by MadhuriPatil1694** [comment]
> this was a hardware issue with my mobo

I am using the same tpu device on operating system 5.10.104-tegra ,it was detecting it before, but since I flashed my machine it is unable to see tpu(I mean when I do lspci it doesn't mention coral edge tpu). What was the hardware issue you had?
