### ISSUE TITLE
How to profile the Coral TPU Usage

### ISSUE THREAD

**Issue by Anandvilayil** [google-coral/edgetpu#737]
Hi Folks 
I Just wanted to know is there any way to profile the performance of Coral TPU on Coral Dev Board  (PCI connected Module) and the Coral accelerator module connected to USB Port. 

The Intention is to assess 
i) Is the TPU fully loaded or not while running the model?
ii) Is there any over power consumption during running a model : (Helpful for deciding the Adaptor input.) 
iii) Identify the Power consumption and TPU performance
etc.

Thanks.

**Comment by hjonnala** [comment]
HI @Anandvilayil power consumption and performance would vary based on the model and operating frequency. Please check section 2.4 and 2.5 for more details at: https://coral.ai/static/files/Coral-Accelerator-Module-datasheet.pdf

Unfortuantely, We don't have any software tools/API to profile the TPU usage. Thanks!!
