### ISSUE TITLE
Unable to get Coral PCIE Driver to load

### ISSUE THREAD

**Issue by jburke26** [google-coral/edgetpu#738]
### Description

I am unable to get the Coral PCIE driver to load on a fresh Ubuntu 22.04.1 LTS VM. This VM is running on ESXi. The Coral PCIE device has passthrough enabled passing the device directly to the Ubuntu VM. 

I followed the instructions provided at https://coral.ai/docs/m2/get-started/#2-install-the-pcie-driver-and-edge-tpu-runtime

I am able to see the device but the driver never loads.

user@coraldev2-srv:~$ lspci -nn | grep 089a
03:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]

user@coraldev2-srv:~$ ls /dev/apex_0
ls: cannot access '/dev/apex_0': No such file or directory

Kernel Version- 
user@coraldev2-srv:~$ uname -r
5.15.0-69-generic

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Ubuntu

### Coral Device

Mini PCIe

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi, could you please uninstall the apex drive and share the installation logs.

`sudo apt-get install gasket-dkms`

**Comment by jburke26** [comment]
I just read the trouble tickets regarding ESXI and PCIE passthrough isn't supported. There are reported known issues. That's very unfortunate as I believe a lot of users will be attempting to use the Mini PCIe version of the coral in this method.

If you think maybe I have a different issue I've provided the output requested.

user@coraldev2-srv:~$ sudo apt-get install gasket-dkms
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  gasket-dkms
0 upgraded, 1 newly installed, 0 to remove and 72 not upgraded.
Need to get 0 B/48.0 kB of archives.
After this operation, 256 kB of additional disk space will be used.
Selecting previously unselected package gasket-dkms.
(Reading database ... 79782 files and directories currently installed.)
Preparing to unpack .../gasket-dkms_1.0-18_all.deb ...
Unpacking gasket-dkms (1.0-18) ...
Setting up gasket-dkms (1.0-18) ...
Loading new gasket-1.0 DKMS files...
Building for 5.15.0-69-generic
Building initial module for 5.15.0-69-generic
Done.

gasket.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-69-generic/updates/dkms/

apex.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-69-generic/updates/dkms/

depmod....

Backing up initrd.img-5.15.0-69-generic to /boot/initrd.img-5.15.0-69-generic.old-dkms
Making new initrd.img-5.15.0-69-generic
(If next boot fails, revert to initrd.img-5.15.0-69-generic.old-dkms image)
update-initramfs..............
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
user@coraldev2-srv:~$

**Comment by hjonnala** [comment]
Thanks.. Can you please check the output of below command. You might be having same issue as others in this thread: https://github.com/google-coral/edgetpu/issues/343

`sudo dmesg |grep apex`

**Comment by jburke26** [comment]
user@coraldev2-srv:~$ sudo dmesg |grep apex
[    8.835089] apex 0000:03:00.0: Page table init timed out
[    8.838448] apex 0000:03:00.0: MSI-X table init timed out
[    8.848389] apex: probe of 0000:03:00.0 failed with error -110

**Comment by hjonnala** [comment]
Yes, same as the other issue: https://github.com/google-coral/edgetpu/issues/343

Closing the issue here, If you would like, please add a comment their if  anyone has as any suggestions or workaround for this. Thanks!

**Comment by jburke26** [comment]
Thanks for the confirmation...
