### ISSUE TITLE
Coral Camera with 60 FPS

### ISSUE THREAD

**Issue by skytect** [google-coral/edgetpu#740]
### Description

I need 60 FPS for my application, and it seems the Coral Camera is only capable of 30 FPS:

```
$ v4l2-ctl --list-formats-ext --device /dev/video1
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'YUYV' (YUYV 4:2:2)
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 720x480
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 1280x720
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 1920x1080
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 2592x1944
                        Interval: Discrete 0.067s (15.000 fps)
```

The driver source code at [https://coral.googlesource.com/linux-imx/+/refs/heads/master/drivers/media/platform/mxc/capture/ov5645_mipi_v2.c#56](https://coral.googlesource.com/linux-imx/+/refs/heads/master/drivers/media/platform/mxc/capture/ov5645_mipi_v2.c#56) also confirms this:

```c
enum ov5645_mode {
  ov5645_mode_MIN = 0,
  ov5645_mode_VGA_640_480 = 0,
  ov5645_mode_NTSC_720_480 = 1,
  ov5645_mode_720P_1280_720 = 2,
  ov5645_mode_1080P_1920_1080 = 3,
  ov5645_mode_QSXGA_2592_1944 = 4,
  ov5645_mode_MAX = 5,
  ov5645_mode_INIT = 0xff, /*only for sensor init*/
};
  
enum ov5645_frame_rate {
  ov5645_15_fps,
  ov5645_30_fps
};  

static int ov5645_framerates[] = {
  [ov5645_15_fps] = 15,
  [ov5645_30_fps] = 30,
};
```

However, the OV5646 sensor used seems to support 60 FPS, as the datasheet says 720p60 is supported.

[OV5645_CSP3_DS_1.1_King Horn International Ltd..pdf](https://github.com/google-coral/edgetpu/files/11154466/OV5645_CSP3_DS_1.1_King.Horn.International.Ltd.pdf)

Is there any way I can get 60 FPS working? Would I need to recompile the driver code? I'm not very familiar with this.

I would appreciate any help I can get. Thanks.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Feel free to make the code changes to camera driver and rebuild the [Mnedel linux kernel](https://coral.googlesource.com/docs/+/refs/heads/master/GettingStarted.md) (m docker-linux-imx) and install the output deb file using with mdt (mdt install path_to_debfile.deb).

Looks like someone was able to make code changes for higher frame rate(not sure if its 60 fps):
https://stackoverflow.com/questions/70045774/building-mendel-linux-with-code-changes-in-camera-driver

**Comment by Edward2k** [comment]
Is there any action being taken to support coral camera @60fps in the Mendel's baseline release? If not, I'll make the modifications myself. If interested, I'll supply the patch so this can be added to the baseline 👍

Edit: is there any particular reason this wasn't done from the getgo? Could save me some headache

**Comment by Edward2k** [comment]
Here is the patch I made. The coral camera now works at 60fps with the following patch/driver. The instructions on how to build the mendel kernel are pretty straight forward. To install it, follow the stackoverflow thread posted above. Good luck!

[ov5645_60fps.zip](https://github.com/google-coral/edgetpu/files/11371837/ov5645_60fps.zip)
