### ISSUE TITLE
openai whisper on coral usb (using flexops)

### ISSUE THREAD

**Issue by vinprofessionalapps** [google-coral/edgetpu#744]
### Description

Hi,

I'm trying to run https://huggingface.co/openai/whisper-small/ (or tiny), using the tflite created by https://github.com/usefulsensors/openai-whisper. Both whisper-tiny.tflite & whisper-small.tflite are working ok on TF2.12 without Coral delegate. 

The problem I get seem to be related to the compatibility of the tflite models (converted using TF2.12) with the tflite_runtime 2.5.post1.

3 questions:
1. do you foresee a gain running whisper-tiny (or small) on USB Coral (requiring some flex ops to run on CPU). Or I should revert to running without Coral? 
2. it's unclear for me if coral only works with the tflite_runtime-2.5.0.post1 (+ delegate), or it should be possible to use TF2.12 (+tf.lite.experimental.delegate)? Tried running on TF2.12 the basic mobilenet_v2_1.0_224_inat_bird_quant detection and doesnt seem to use the accelerator.
3. can you point/help/advise how to convert the whisper model to a coral compatible tflite (running flex ops on RPI4 CPU)

Thanks!!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Linux

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Unfortuantely, Modes with flexops are not supported by the edgetpu_compiler.

**Comment by vinprofessionalapps** [comment]
My plan is to run the flexops on CPU and the compatible part on Coral. Apparently that should be possible. Do you see otherwise?

**Comment by hjonnala** [comment]
Unfortunately, you won't be able to compile the model with flexops, so there is no way you can run the compatiable ops on TPU.

**Comment by vinprofessionalapps** [comment]
Thanks!

Is there anything i can do to get rid of flexops from a pre-trained model?

**Comment by hjonnala** [comment]
> Is there anything i can do to get rid of flexops from a pre-trained model?

Please check with [openai-whisper](https://github.com/usefulsensors/openai-whisper) team on it. Thanks!!

**Comment by ForestJohnson** [comment]
What about this one? I wonder if the same approach they use here to make it work on TensorFlow lite could be applied ? https://aihub.qualcomm.com/models/whisper_tiny_en
