### ISSUE TITLE
Windows on ARM64 Support

### ISSUE THREAD

**Issue by sidd-kishan** [google-coral/edgetpu#746]
### Description

Please let us know when can we have an ARM64 version for Windows on ARM OS. As it will encourage the development of drivers on Windows on ARM platform.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Windows 10

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
H @sidd-kishan unforutnately, we don't have any plans to support Windows ARM64 version. Thanks!!
