### ISSUE TITLE
Cannot install dkms or kernel source on Coral Dev board Mini

### ISSUE THREAD

**Issue by cafrank** [google-coral/edgetpu#749]
### Description

$ sudo apt upgrade gasket-dkms
Setting up gasket-dkms (1.0-14) ...
Removing old gasket-1.0 DKMS files...

------------------------------
Deleting module version: 1.0
completely from the DKMS tree.
------------------------------
Done.
Loading new gasket-1.0 DKMS files...
**Building for 4.19.125-mtk**
Building initial module for 4.19.125-mtk
Error! Bad return status for module build on kernel: 4.19.125-mtk (aarch64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--configure):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 gasket-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

$ sudo apt install linux-source-4.19
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  glmark2 libdrm-dev libdrm-tegra0 libegl1-mesa-dev libgbm-dev libgl1-mesa-dev libgles1 libgles2-mesa libgles2-mesa-dev libglew2.1 libglvnd-core-dev libglvnd-dev libopengl0
  libosmesa6 libpthread-stubs0-dev libwayland-bin libwayland-dev libx11-dev libx11-xcb-dev libxau-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev
  libxcb-randr0 libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb1-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev
  libxshmfence-dev libxxf86vm-dev mesa-common-dev mesa-utils wayland-protocols x11proto-core-dev x11proto-damage-dev x11proto-dev x11proto-fixes-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev xorg-sgml-doctools xtrans-dev
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  libncurses-dev | ncurses-dev libqt4-dev
Recommended packages:
  bc bison flex linux-config-4.19
The following NEW packages will be installed:
  linux-source-4.19
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 107 MB of archives.
After this operation, 107 MB of additional disk space will be used.
Get:1 https://deb.debian.org/debian-security buster/updates/main arm64 linux-source-4.19 all 4.19.269-1 [107 MB]
Fetched 107 MB in 9s (12.0 MB/s)                                                                                                                                                 
Selecting previously unselected package linux-source-4.19.
(Reading database ... 61739 files and directories currently installed.)
Preparing to unpack .../linux-source-4.19_4.19.269-1_all.deb ...
Unpacking linux-source-4.19 (4.19.269-1) ...
Setting up linux-source-4.19 (4.19.269-1) ...
Setting up gasket-dkms (1.0-14) ...
Removing old gasket-1.0 DKMS files...

------------------------------
Deleting module version: 1.0
completely from the DKMS tree.
------------------------------
Done.
Loading new gasket-1.0 DKMS files...
**Building for 4.19.125-mtk**
Same error as above: sudo apt upgrade gasket-dkms

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Programming Language

Python 3.7

### Relevant Log Output

```shell
Deleting module version: 1.0
completely from the DKMS tree.
------------------------------
Done.
Loading new gasket-1.0 DKMS files...
**Building for 4.19.125-mtk**
Building initial module for 4.19.125-mtk
Error! Bad return status for module build on kernel: 4.19.125-mtk (aarch64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--configure):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 gasket-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
</details>

**Comment by hjonnala** [comment]
gasket-dkms package required only for pcie products. This is not needed for Dev Board Mini, as its connected to TPU via USB2.0
