### ISSUE TITLE
Is this architecture abandoned?

### ISSUE THREAD

**Issue by metacritical** [google-coral/edgetpu#753]
### Description

No update on this architecture since 2020. is this an abandoned project heading towards the google graveyard?

**Comment by hjonnala** [comment]
HI, [edgeptu](https://github.com/google-coral/edgetpu) repo is deprecated.

Please refer to the following repos:

https://github.com/google-coral/libedgetpu: The Edge TPU Runtime (libedgetpu)
https://github.com/google-coral/libcoral: The Coral C++ library (libcoral)
https://github.com/google-coral/pycoral: The Coral Python library (PyCoral)
https://github.com/google-coral/test_data: Various models and other testing data
