### ISSUE TITLE
Coral USB keeps resetting despite new PC hardware "reset SuperSpeed USB device"

### ISSUE THREAD

**Issue by LaurenceGough** [google-coral/edgetpu#754]
### Description

Hi all,

I always had the odd reset of the Coral USB on my Raspberry Pi 4, I suspected it was just due to the limited USB power it could provide. I was a bit shocked to see the same thing happening, despite a whole new PC. I've now got a mini desktop PC (Intel Celeron) which should have ample power, it has a 30W power supply and draws around 8W by itself.

Could my Coral USB be faulty? It's temps are not above 38c on the heatsink in a 21c room, and I'm using the cable that came with it out of the box from an official reseller direct. It's plugged into a USB 3 port. I've tried different USB 3 ports.

I've disabled USB suspension:
cat /sys/bus/usb/devices/*/power/control
on
on
on
on
on

The OS before was Diet Pi (Debian based) and now I'm using Clear Linux server OS. Looking at the full syslog around this time there is no other update or errors happening.

Thank you

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Relevant Log Output

```shell
Clear Linux errors:
[159263.023770] usb 2-2: reset SuperSpeed USB device number 3 using xhci_hcd
[159263.035674] usb 2-2: LPM exit latency is zeroed, disabling LPM.
[167524.287925] usb 2-2: reset SuperSpeed USB device number 3 using xhci_hcd
[167524.301045] usb 2-2: LPM exit latency is zeroed, disabling LPM.

Raspberry Pi 4 dmesg errors:
Mar  8 20:24:40 Pi kernel: [2758710.649344] usb 2-2: reset SuperSpeed USB device number 4 using xhci_hcd
Mar  8 20:24:40 Pi kernel: [2758710.668836] usb 2-2: LPM exit latency is zeroed, disabling LPM.
Mar  8 23:51:35 Pi kernel: [2771126.257350] usb 2-2: reset SuperSpeed USB device number 4 using xhci_hcd
Mar  8 23:51:35 Pi kernel: [2771126.276745] usb 2-2: LPM exit latency is zeroed, disabling LPM.
```
</details>

**Comment by hjonnala** [comment]
Hi, does LED light on USB accelrator is ON when connected to host machine?

**Comment by LaurenceGough** [comment]
> Hi, does LED light on USB accelrator is ON when connected to host machine?

Hello, yes. It can work fine for a while but up to 3-4x a day it does this.  No movement near the device. It did it a few hours ago. It seems totally random.

Thanks.

**Comment by LaurenceGough** [comment]
So it appears that the USB cable that came with the USB Coral accelerator was faulty. I see a few comments online mentioning the same.  The cable was never bent or moved, it was just taken out of the provided Coral box and inserted. I did try reconnecting it a few times but that made no difference.

The USB Coral ran at around 38c on the heatsink 24/7. Now, with only a USB cable change it is completely cold to the touch and no more errors.

It is disappointing to see that it arrived with a damaged cable and that it has caused so much additional heat for so long on it.

**Comment by hjonnala** [comment]
> It is disappointing to see that it arrived with a damaged cable and that it has caused so much additional heat for so long on it.

Sorry to know that the cable comes with USB accelrator got damaged, its very unusual. If you would like to get a replacement for the device, please work with the original reseller to get the replacement. Thanks!!

**Comment by amigthea** [comment]
> ### Description
> 
> Hi all,
> 
> I always had the odd reset of the Coral USB on my Raspberry Pi 4, I suspected it was just due to the limited USB power it could provide. I was a bit shocked to see the same thing happening, despite a whole new PC. I've now got a mini desktop PC (Intel Celeron) which should have ample power, it has a 30W power supply and draws around 8W by itself.
> 
> Could my Coral USB be faulty? It's temps are not above 38c on the heatsink in a 21c room, and I'm using the cable that came with it out of the box from an official reseller direct. It's plugged into a USB 3 port. I've tried different USB 3 ports.
> 
> I've disabled USB suspension: cat /sys/bus/usb/devices/*/power/control on on on on on
> 
> The OS before was Diet Pi (Debian based) and now I'm using Clear Linux server OS. Looking at the full syslog around this time there is no other update or errors happening.
> 
> Thank you
> Click to expand!

I've the exact same issue and symptoms and cable replacement did not fix it. Can I ask you how do you disabled USB suspension?
I've tried everything this past month to solve this problem:
- replaced the coral with a new one
- changed the cable
- used it over a powered usb hub
sadly nothing worked out and I'm out of options
