### ISSUE TITLE
Unable to run model on the Edge TPU

### ISSUE THREAD

**Issue by DNA99** [google-coral/edgetpu#757]
Hi, I am using the mini PCIe version of the coral TPU and I installed the files according to https://coral.ai/docs/m2/get-started/#pycoral-on-win

When I try to run the model on the Edge TPU in step 4. I get the following message:

dna@DNASERVER:~/coral$ git clone https://github.com/google-coral/pycoral.git
fatal: destination path 'pycoral' already exists and is not an empty directory.
dna@DNASERVER:~/coral$ cd pycoral
dna@DNASERVER:~/coral/pycoral$ bash examples/install_requirements.sh classify_image.py
DOWNLOAD: mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4197k  100 4197k    0     0  18.4M      0 --:--:-- --:--:-- --:--:-- 18.4M
DOWNLOAD: mobilenet_v2_1.0_224_inat_bird_quant.tflite
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3495k  100 3495k    0     0  4207k      0 --:--:-- --:--:-- --:--:-- 4207k
DOWNLOAD: inat_bird_labels.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 37146  100 37146    0     0   276k      0 --:--:-- --:--:-- --:--:--  276k
DOWNLOAD: parrot.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  582k  100  582k    0     0  3639k      0 --:--:-- --:--:-- --:--:-- 3639k
dna@DNASERVER:~/coral/pycoral$ python3 examples/classify_image.py \
--model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels test_data/inat_bird_labels.txt \
--input test_data/parrot.jpg
Traceback (most recent call last):
  File "/home/dna/coral/pycoral/examples/classify_image.py", line 35, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
dna@DNASERVER:~/coral/pycoral$

Please help me!

**Comment by DNA99** [comment]
I am running on Windows 11

**Comment by hjonnala** [comment]
> ModuleNotFoundError: No module named 'numpy'

Hi, have you run the below command to install [pycoral library](https://coral.ai/docs/m2/get-started/#pycoral-on-win) on Windows 11?

`python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ pycoral~=2.0`

**Comment by easy-and-simple** [comment]
And what is relation between windows setup instructions and linux implementation?
Linux is not Windows!
If you want to use Windows use Windows!
If you try to run it on WSL2 it will not work because PCI devices doesn't work in virtual environment. Only USB version of coral edgetpu works on virtual machines.
Also your Windows installation and setup are for windows, and for Linux you should set it up  for linux, but because it is PCI device it will not work in virtual environment

**Comment by DNA99** [comment]
Yes. Im dumping windows for Linux on the same machine to try out the coral tpu install. You figure that will work?
