### ISSUE TITLE
Can the Coral USB Accelerator be set to a lower power consumption mode?

### ISSUE THREAD

**Issue by zymale** [google-coral/edgetpu#758]
### Description

I am currently using the Coral USB Accelerator . When I am not conducting model inference, its power consumption is approximately 300mw. Can this power consumption be lower? Because my usage situation has strict power consumption requirements.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
> I am currently using the Coral USB Accelerator . When I am not conducting model inference, its power consumption is approximately 300mw. Can this power consumption be lower? Because my usage situation has strict power consumption requirements.

Unfortuantely, we don't have any API to set the device to lower power conumption mode when not running any inference.

USB-accelerator can  run either at the maximum frequency (libedgetpu1-max: 500 MHz) or at the reduced frequency (libedgetpu1-std: 250 MHz). During inference, running at the reduced frequency would lower the power conumption but also reduce the inference speed.

https://coral.ai/static/files/Coral-USB-Accelerator-datasheet.pdf

**Comment by zymale** [comment]
> > I am currently using the Coral USB Accelerator . When I am not conducting model inference, its power consumption is approximately 300mw. Can this power consumption be lower? Because my usage situation has strict power consumption requirements.
> 
> Unfortuantely, we don't have any API to set the device to lower power conumption mode when not running any inference.
> 
> USB-accelerator can run either at the maximum frequency (libedgetpu1-max: 500 MHz) or at the reduced frequency (libedgetpu1-std: 250 MHz). During inference, running at the reduced frequency would lower the power conumption but also reduce the inference speed.
> 
> https://coral.ai/static/files/Coral-USB-Accelerator-datasheet.pdf

Thank you for your reply. If the lower power conumption mode cannot be set  when not running any inference,  my application scenario may not be very suitable for Coral USB Accelerator.Do you have any plans to add this type of API? If there are plans to add this type of API, when will it be?

**Comment by hjonnala** [comment]
> .Do you have any plans to add this type of API? If there are plans to add this type of API, when will it be?

Unfortuantely, we don't have any plans to add this type of API. Thanks!

**Comment by synaption** [comment]
Is there a way to turn the tpu off when not in use?  I am using the som.
