### ISSUE TITLE
error in compiling file to _edgetpu.tflite

### ISSUE THREAD

**Issue by niteshverma21ind** [google-coral/edgetpu#76]
Hello, 
I am trying to convert tflite file to edgetpu.tflite.
I am using Ubuntu 16 for compiling using edge tpu compilier.

There is a message after compiling. 

The output file ("**detect_edgetpu.tfilite**") is not running in my rapberry pi 4.
Screen shot is attached. 

Can anyone tell me what the issue and how to solve it !!!!
![compiling_edgetpu_model](https://user-images.githubusercontent.com/20231709/76405261-e030ad80-63ad-11ea-9632-0c7b27996f8a.jpg)
![RPI4_error](https://user-images.githubusercontent.com/20231709/76405269-e2930780-63ad-11ea-887b-22895c12254e.jpg)

**Comment by Namburger** [comment]
@niteshverma21ind from the given information, you are creating a "detect_edgetpu.tflite", but the python error you are seeing is trying to run a model called "edgetpu.tflite" so make sure you give it the correct file path

**Comment by niteshverma21ind** [comment]
@Namburger  Thanks very much. I got my mistake. Renamed the file to edgetpu.tflite and ran the code. Its running !!!!!!!
