### ISSUE TITLE
USB Malfunction

### ISSUE THREAD

**Issue by selcukyazar** [google-coral/edgetpu#764]
### Description

Hi, 
Hi, I just bought the device, I wanted to try some examples on my windows 11 machine via WSL2. After having problems with USB, I decided to try it on Arduino. When I loaded the face recognition example, the device turned off and now when I turn it on, the STAT led is orange and stays that way. Windows gives an error that the USB device cannot be recognized. What should I do?

Also I  successfully connected with USB to UART Bridge(Silicon labs CP210x). When I connect to device, it says Loading Model on boot, bot I guess crash in here?

I need bootloader or something else

Best regards.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support, Others

### Operating System

Windows 10

### Coral Device

Dev Board Micro

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
@selcukyazar I am able to reset the device by connecting Linux machine with the below method. Unfortunately reset process is not working with WIndows host machine.

- hold the User button while you plug in the USB cable.
Release the button when the orange LED turns on.

**Comment by hjonnala** [comment]
If you are having Arduino IDE 2.1.0 please downgrade to [2.0.4](https://github.com/arduino/arduino-ide/releases/tag/2.0.4).

**Comment by selcukyazar** [comment]
Thank you hjnnala for response. Somehow, with precise timing, I managed to flash the blinkLEd app. But this time, I USB driver problem in my win11 host machine device manager. Where can I Find USB device drivers for coral micro?

Best wishes

**Comment by hjonnala** [comment]
Please ignore the usb driver problem in device manager and try the facedetection example with Arduino IDE 2.0.4.Thanks!!

**Comment by selcukyazar** [comment]
Finally it works again! Thank you for helps.

👍 🥇
