### ISSUE TITLE
Faulty Edge TPU? Very slow inference speeds

### ISSUE THREAD

**Issue by Morphy99** [google-coral/edgetpu#765]
I've just purchased some dual edge TPU's off eBay and it seems one of them has a very slow inference speed when running Frigate. I'm getting 165ms where as with other TPU's on the same hardware, I'm getting more like 10-11ms. Has anyone come across a "bad" board before?

**Comment by hjonnala** [comment]
@Morphy99 could you please check your host machine detecting two TPUs with below command, as most of the hardwares support only one TPU. Thanks!!

- ls /dev/apex_*

**Comment by Morphy99** [comment]
Hi thanks but it only detects one TPU, this is not the issue though. I have two other dual edge boards where the inference speed is normal.

**Comment by hjonnala** [comment]
Okay, I haven't seen this type of issue so far. Please return the device to original reseller. Thanks!!
