### ISSUE TITLE
Cannot compile model: Invalid model

### ISSUE THREAD

**Issue by zye1996** [google-coral/edgetpu#79]
Hi,

I am trying to compile model from a post-quantized 8int tflite model using compiler, specifically mobilefacenet. The compiler is rejecting me for the reason:

**Invalid model: inference_model_0_quant.tflite**

Here attached my model after post quantization
[inference_model_0_quant.tflite.zip](https://github.com/google-coral/edgetpu/files/4339549/inference_model_0_quant.tflite.zip)

I was wondering what might cause the imcompability?

**Comment by Namburger** [comment]
Hello, what tensorflow version are you using and how are you doing the post training quantization?
It looks like the model is not fully quantized, you can use the [tflite's visualize tool](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/visualize.py) to check the tensors of your tflite model. For a fully quantized model, most of the tensors should be marked as uint8 / int8 type.

**Comment by zye1996** [comment]
> Hello, what tensorflow version are you using and how are you doing the post training quantization?
> It looks like the model is not fully quantized, you can use the [tflite's visualize tool](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/visualize.py) to check the tensors of your tflite model. For a fully quantized model, most of the tensors should be marked as uint8 / int8 type.
> I suggest reviewing this [post training quantization](https://www.tensorflow.org/lite/performance/post_training_integer_quant) doc to make sure you can get the model fully quantized.

I tried both tensorflow 1.15.0 and tensorflow 2.1 with v1 compatible converter, and both yield the same result. I explicitly declared the quantization as follow:
----------------------------------------------------
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import cv2
import os

root_dir = "../image"

file_name = 'inference_model_0.993.h5'

def data_generator():
    for file in os.listdir(root_dir):
        img = plt.imread(os.path.join(root_dir, file), format='rgb').astype('float32')
        img = (img.astype('float32') - 127.5) / 128.0
        yield [img[np.newaxis, :, :, :]]


if __name__ == "__main__":

    converter = tf.lite.TFLiteConverter.from_keras_model_file(file_name)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = data_generator
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.TFLITE_BUILTINS]
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    tflite_quant_model = converter.convert()

    # write to file
    with open(file_name.split('.')[0]+'_quant.tflite', "wb") as f:
        f.write(tflite_quant_model)

**Comment by Namburger** [comment]
Hi, I'd change this line:
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.TFLITE_BUILTINS]
```
to 
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
```

**Comment by zye1996** [comment]
> Hi, I'd change this line:
> 
> ```
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.TFLITE_BUILTINS]
> ```
> 
> to
> 
> ```
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
> ```

The model contains operations not supported by 8-bit quantization so I was trying to bypass the limitation by move those operation to CPU so it can successfully convert. Am I doing the right way or there are other ways for this situation?

**Comment by Namburger** [comment]
Hi @zye1996 unfortunately, if there are some ops that is not yet supported then we don't have any suggestions on our side. Any intermediate tensors will need to be quantized in order for it to pass the compiler. Maybe a feature request [here](https://github.com/tensorflow/tensorflow/issues)?

**Comment by zye1996** [comment]
> Hi @zye1996 unfortunately, if there are some ops that is not yet supported then we don't have any suggestions on our side. Any intermediate tensors will need to be quantized in order for it to pass the compiler. Maybe a feature request [here](https://github.com/tensorflow/tensorflow/issues)?

I thought I could select which operations to be mapped to TPU and if there is an unsupported operation, I can execute it on CPU and TPU compiler will handle it by looking into Quantize and Dequantize operation in the tflite file after quantization. Here is my quantized tflite model (though float32 exists for some operations) in netron. Please correct me if I am wrong, thank you!

![Screen Shot 2020-03-26 at 12 27 26 PM](https://user-images.githubusercontent.com/28901953/77670892-303a7300-6f5d-11ea-8585-7e3e94373e7e.png)

**Comment by Namburger** [comment]
Sorry for the late response, but currently the compiler won't allow model to pass if any intermediate tensors are not quantized. Unfortunately it makes it harder to discuss this issue since the compiler is not open source, although there maybe good new regarding this in the future. On another note, how about trying post training quantization with tensorflow 2.*? One of the main reason for incompatibility is that tf2.* no longer support:
```
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
```
But since our compiler can allow float input/output now and a newer version of ptq maybe able to fully quantize your intermediate tensor
