### ISSUE TITLE
minimal.cc build error

### ISSUE THREAD

**Issue by jedichen121** [google-coral/edgetpu#8]
I was trying to run the minimal.cc file to test the c++ code. I'm using Ubuntu 16.04 on a x86-64 machine. I've built the tree following the Mendal get started guide and I've installed the Edge TPU runtime library. 

When I was trying to build the minimal.cc file (bazel 0.27.2), I got errors: 
```
ERROR: /home/jedichen/edgetpu/src/cpp/examples/BUILD:47:1: Linking of rule '//src/cpp/examples:minimal' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-fastbuild/bin/src/cpp/examples/minimal-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/src/cpp/examples/_objs/minimal/minimal.pic.o:minimal.cc:function main: error: undefined reference to 'edgetpu::EdgeTpuManager::GetSingleton()'
bazel-out/k8-fastbuild/bin/src/cpp/examples/_objs/model_utils/model_utils.pic.o:model_utils.cc:function coral::BuildEdgeTpuInterpreter(tflite::FlatBufferModel const&, edgetpu::EdgeTpuContext*): error: undefined reference to 'edgetpu::RegisterCustomOp()'
collect2: error: ld returned 1 exit status
Target //src/cpp/examples:minimal failed to build
```

I'm not sure how to solve this. Isn't `edgetpu.h` the only needed file to make this run? Thank you for any help. 

p.s.: I didn't find the `packages/edgetpu` folder. Is it supposed to be downloaded during the Mendel setup process?

**Comment by Namburger** [comment]
@jedichen121 How are you building it?
I was able to build it by modifying the Makefile and build using `make examples`
Take a look at this diff for reference:
```
diff --git a/Makefile b/Makefile
index 6818059..a2c17f9 100644
--- a/Makefile
+++ b/Makefile
@@ -102,11 +102,13 @@ tools:
 examples:
        bazel build $(BAZEL_BUILD_FLAGS) //src/cpp/examples:two_models_one_tpu \
                                         //src/cpp/examples:two_models_two_tpus_threaded \
+                                        //src/cpp/examples:minimal \
                                         //src/cpp/examples:classify_image \
                                         //src/cpp/examples:object_detection
        mkdir -p $(EXAMPLES_OUT_DIR)
        cp -f $(BAZEL_OUT_DIR)/src/cpp/examples/two_models_one_tpu \
              $(BAZEL_OUT_DIR)/src/cpp/examples/two_models_two_tpus_threaded \
+             $(BAZEL_OUT_DIR)/src/cpp/examples/minimal \
              $(BAZEL_OUT_DIR)/src/cpp/examples/classify_image \
              $(BAZEL_OUT_DIR)/src/cpp/examples/object_detection \
              $(EXAMPLES_OUT_DIR)
```
Also, take a look this BUILD section for minimal:
https://github.com/google-coral/edgetpu/blob/master/src/cpp/examples/BUILD#L47

Hope this helps!

**Comment by jedichen121** [comment]
@Namburger Thank you for the reply. I built it by running `bazel build :minimal` in src/cpp/examples directory. 

Did you install other dependencies?

**Comment by Namburger** [comment]
@jedichen121 No other dependencies are needed, you should build via the provided Makefile instead (since many include flags are added). 
At the `examples` section: 
https://github.com/google-coral/edgetpu/blob/master/Makefile#L97
you can add the 2 lines I showed on my git diff above which is necessary to include minimal along with the rest of the `examples`.

To build, simply run (from this project root dir):
```
$ make examples
```
all binary will be in the "out" directory.

**Comment by jedichen121** [comment]
@Namburger I modified the makefile as you said but still it doesn't work. I was wondering if I did something wrong during the mendel setup process. 

I only want to test the USB accelerator on my Ubuntu desktop. Is it required to follow the mendel setup steps?

**Comment by jedichen121** [comment]
I was finally able to compile and run the minimal binary. It seems like the edge tpu runtime library is not linked during compilation. After copying the `libedgetpu.so.1.0` to the libedgetpu folder and adding it to the BUILD file, the program can compile and run without problem.

**Comment by Namburger** [comment]
@jedichen121 Odd. I imagine the `make` error you ran into must be a different one from above.

As for the run time issue; I believe I didn't run into your issue because I've already installed the shared object file from this update (which goes to /usr/lib/x86_64-linux-gnu for my system):
https://coral.withgoogle.com/news/updates-09-2019/

**Comment by jedichen121** [comment]
@Namburger What I did is I copied the `libedgetpu.so.1.0` from `/usr/lib/x86_64-linux-gnu/` to repository's libedgetpu folder. Then change the BUILD file as follow. 

```
diff --git a/libedgetpu/BUILD b/libedgetpu/BUILD
index f17ee8c..998a652 100644
--- a/libedgetpu/BUILD
+++ b/libedgetpu/BUILD
@@ -7,6 +7,7 @@ licenses(["notice"])  # Apache 2.0
 
 cc_library(
     name = "header",
+    srcs = ["libedgetpu.so.1.0"],
     hdrs = ["edgetpu.h", "edgetpu_c.h"],
     deps = [
         "@org_tensorflow//tensorflow/lite:context",
```

**Comment by Namburger** [comment]
@jedichen121 Please [check this answer](https://github.com/google-coral/edgetpu/issues/54#issuecomment-616149916) if you are still interested in a single make build natively!
