### ISSUE TITLE
Can you use multiple Coral TPUs on the same system

### ISSUE THREAD

**Issue by patersonc** [google-coral/edgetpu#80]
Not an 'issue', just a simple question for curiosity's sake...

Is it possible to use more then one Coral TPU device on the same system?
Either with 2 USB accelerators or with 1 USB accelerator + 1 mini PCIe accelerator.

Would the libraries be able to handle this?
Would performance increase?

Thanks, Chris

**Comment by Namburger** [comment]
@patersonc of course you can!
Take a look at [this doc](https://coral.ai/docs/edgetpu/multiple-edgetpu/) to learn more. 
Here is an example too: https://github.com/google-coral/edgetpu/blob/master/src/cpp/examples/two_models_two_tpus_threaded.cc

**Comment by patersonc** [comment]
Hi @Namburger 

Thanks for the fast response! I'll get reading.

Chris
