### ISSUE TITLE
Dev Board Micro not being detected when plugged in

### ISSUE THREAD

**Issue by Perugius** [google-coral/edgetpu#804]
Tried using two machines for this, one windows 10, and the other a raspberry pi 4 for ubuntu.

To preface, I have tried all of the troublshooting advice here https://coral.ai/docs/dev-board-micro/arduino/#troubleshooting

When I plug the coral micro into any device, only the red STAT light turns on. The device does not get recognized on Ubuntu (it does not show up when running "lsusb") and on Windows I get an error too (described above). Holding the "USR" button and then pressing the Reset button does nothing. The device only gets recognized for a split second after being plugged in or being reset, then it stops being recognized again (after about 0.5 seconds)

To reproduce: Out of the box the coral micro worked normally, with the face detection running. I connected it to a Windows machine and flashed it with "blink-led" Arduino script on Arduino IDE 2.2.1, which worked fine. Afterwards I flashed it again with the "person_detection" script from the Tensorflow Lite library. After this the device broke and started acting as described above.

**Comment by fredgfc** [comment]
same problema here

**Comment by hongyuejin** [comment]
I have the same issue. I used a mac to flash it with detectface example project on Arduino and it just broke. The dev board micro can't be detected anymore.

**Comment by Perugius** [comment]
I solved the problem,
First you have to go into SDP mode, explained in the troubleshooting page: https://coral.ai/docs/dev-board-micro/arduino/#troubleshooting
The way it's explained was weird and I couldn't get it into SDP mode because I was holding the User button down for too long. Just hold it for a second or two while plugging it in and then let go. Then when you run _lsusb_ the board should be listed as:
**NXP Semiconductors SE Blank RT Family**

Finally, just follow the [getting started example](https://coral.ai/docs/dev-board-micro/get-started/#4-set-up-for-freertos-development) and flash it with the face detection example and the board should be fixed! (I did run into some problems when running setup.sh and I manually installed some of the packages and the flashing worked)
