### ISSUE TITLE
USB stick rebooting when starting inference example

### ISSUE THREAD

**Issue by anderssvedberg** [google-coral/edgetpu#81]
I have successfully been able to build and run the "minimal" example on an i.MX8X board (aarch64) after following instructions from other users (compiling tensorflow lite runtime based on the WORKSPACE commit).

When running the "minimal" example, the application 'hangs' for a few seconds, then displaying the result correctly:

> ./minimal mobilenet_v2_1.0_224_quant_edgetpu.tflite resized_cat.bmp
> INFO:` Initialized TensorFlow Lite runtime.
> [Image analysis] max value index: 286 value: 0.773438

Running "dmesg" shows that the USB stick seems to disconnect and reconnect again each time I run the application. This is the reason for the delay before minimal app shows the result I think.

>[14096.074559] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14096.978513] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14097.886527] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14098.790518] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14098.797226] usb 3-1: USB disconnect, device number 8
>[14099.074471] usb 3-1: new high-speed USB device number 9 using ci_hdrc
>[14112.318558] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14113.222557] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14114.126554] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14115.030531] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14115.037223] usb 3-1: USB disconnect, device number 9
>[14115.310468] usb 3-1: new high-speed USB device number 10 using ci_hdrc
>[14128.158577] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14129.062517] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14129.966518] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14130.870531] usb usb3-port1: Cannot enable. Maybe the USB cable is bad?
>[14130.877234] usb 3-1: USB disconnect, device number 10
>[14131.150465] usb 3-1: new high-speed USB device number 11 using ci_hdrc

Anyone knows if this is normal behaviour? 
My device has only USB2 connectors if that can be part of the issue.

**Comment by anderssvedberg** [comment]
Execution hangs on this call for a few seconds, giving the above dmesg printouts, then when usb device is re-initialized, the rest of the code is executed.

`std::unique_ptr<tflite::Interpreter> interpreter = coral::BuildEdgeTpuInterpreter(*model, edgetpu_context.get());
`

**Comment by Namburger** [comment]
@anderssvedberg this is expected behavior, actually, **but only for loading the model**. So that line you post is precisely where the bottleneck would be. After the model has been loaded, each sub-sequence run will be much faster. 
This is especially true with a USB2.0, there will be some data transferring speed bottlenecks. 
Check out results of [this run](https://github.com/google-coral/tflite/tree/master/python/examples/classification#run-the-code) for example (this is a 3.0 USB hub):
```
Initializing TF Lite interpreter...
INFO: Initialized TensorFlow Lite runtime.
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
11.8ms
3.0ms
2.8ms
2.9ms
2.9ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.76562
```

**Comment by anderssvedberg** [comment]
Thank you @Namburger for the clarification.
