### ISSUE TITLE
apex_0 not being created when installing drivers on proxmox

### ISSUE THREAD

**Issue by JEngel98** [google-coral/edgetpu#816]
### Description

I am trying to pass a coral TPU through to frigate. The hardware is an A+E TPU installed in the wifi slot on a 6th gen intel processor. I am running frigate in a portainer in a container on proxmox.

I have run through the following guide 'https://github.com/Bytelake/Coral-in-LXC' and the getting started page 'https://coral.ai/docs/m2/get-started/#2a-on-linux' before spent the next few days following countless guides to get this working. 

I have worked out that gasket and apex aren't installed properly as when I run the commands 'lsmod | grep gasket' or 'lsmod | grep gasket' I get nothing back, whereas my brother with an identical setup gets back the expected 40ish lines listing filename, author, etc... When I run 'ls /dev/apex_0' that returns 'ls: cannot access '/dev/apex_0': No such file or directory'

The only errors I get are promox complaining about packets being unsigned, but my brother has the same issue and it doesn't affect him his TPU has passed right through, he has a 7th gen processor.

Please help!

### Issue Type

Build/Install

### Operating System

Proxmox

### Coral Device

M.2 Accelerator A+E

**Comment by JEngel98** [comment]
Sorted, I had subscription proxmox repositories (removed) a 'buster' suite of debian with issues (removed) and secure boot enabled

**Comment by figadore** [comment]
> Sorted, I had subscription proxmox repositories (removed) a 'buster' suite of debian with issues (removed) and secure boot enabled

Can you explain this a bit more? What did you do to solve it?

**Comment by JEngel98** [comment]
So, the first thing I mentioned was the subscription repository I was using. This would throw up errors every time apt update and apt upgrade would run. if your get an 'E:' error, that will likely stop the kernal from updating. clear all your errors, 'W:' warnings seem not to matter. 

For me the following was the cause of my 'E:; errors
 When you get proxmox it loads the subscription version of debian, I guess there might be a way of specifying otherwise, but by default it's subscription. Without a valid subscription, you're unable to change the kernel. 
 So first thing is to enter the node in question, go to repositories under update, disable the subscription repo and add a non-subscription one that was there by default for me I believe? I also had a repo with the label of 'buster' under Suites tab, that needed disabling too as it was also causing issue when running the update and upgrade commands.

Once that was done, I ran all the code from these two links:
 - https://github.com/Bytelake/Coral-in-LXC
 - https://forum.proxmox.com/threads/update-error-with-coral-tpu-drivers.136888/
In the latter LiloBzH's post from November 24 was the relevant one.

By this point running the following two commands generated a proper list which they handed before and I believe it is showing details on the kernal HAT? Apologies, some of this goes over my head from time to time.

 - sudo modinfo apex
 - sudo modinfo gasket

If these two files are present, then in my case, secure boot was enabled and disabling that in the bios setting fitted it for me. I'd recommend googling 'device model number + disabling secure boot' 

Hope this helps

**Comment by jaxonstagecrew** [comment]
> So, the first thing I mentioned was the subscription repository I was using. This would throw up errors every time apt update and apt upgrade would run. if your get an 'E:' error, that will likely stop the kernal from updating. clear all your errors, 'W:' warnings seem not to matter.
> 
> For me the following was the cause of my 'E:; errors When you get proxmox it loads the subscription version of debian, I guess there might be a way of specifying otherwise, but by default it's subscription. Without a valid subscription, you're unable to change the kernel. So first thing is to enter the node in question, go to repositories under update, disable the subscription repo and add a non-subscription one that was there by default for me I believe? I also had a repo with the label of 'buster' under Suites tab, that needed disabling too as it was also causing issue when running the update and upgrade commands.
> 
> Once that was done, I ran all the code from these two links:
> 
> * https://github.com/Bytelake/Coral-in-LXC
> * https://forum.proxmox.com/threads/update-error-with-coral-tpu-drivers.136888/
>   In the latter LiloBzH's post from November 24 was the relevant one.
> 
> By this point running the following two commands generated a proper list which they handed before and I believe it is showing details on the kernal HAT? Apologies, some of this goes over my head from time to time.
> 
> * sudo modinfo apex
> * sudo modinfo gasket
> 
> If these two files are present, then in my case, secure boot was enabled and disabling that in the bios setting fitted it for me. I'd recommend googling 'device model number + disabling secure boot'
> 
> Hope this helps

You just saved me hours of troubleshooting.  Thanks!
