### ISSUE TITLE
[Ask] edgetpu_demo

### ISSUE THREAD

**Issue by AlexTraan** [google-coral/edgetpu#82]
Hi Coral team,

Do you opensource edgetpu_demo program (i mean not only script but also full source code)?

**Comment by Namburger** [comment]
@AlexTraan Yes, edgetpu demo is opensource [here](https://coral.googlesource.com/edgetpudemo/+/refs/heads/master)
but that demo is just a bash script that calls the `edgetpuvision` library, which is hosted [here](https://coral.googlesource.com/edgetpuvision/+/refs/heads/master).
If you have a devboard, it should already installed and you can find it in your machine with:
```
$ dpkg -L python3-edgetpuvision
```

**Comment by AlexTraan** [comment]
@Namburger Thank you
