### ISSUE TITLE
TensorFlow Lite model on Coral Dev Board not running on TPU

### ISSUE THREAD

**Issue by jakelevi1996** [google-coral/edgetpu#83]
# TensorFlow Lite model on Coral Dev Board not running on TPU

I have a TensorFlow Lite model and a Coral Dev Board, and I want to perform inference on the Dev Board's TPU.

When initialising the TensorFlow Lite interpreter in my Python inference script, I add "libedgetpu.so.1" as an experimental delegate, following the example in [the Google Coral TFLite Python example](https://github.com/google-coral/tflite/blob/master/python/examples/classification/classify_image.py) (linked to in the [getting started guide for the Coral Dev Board](https://coral.ai/docs/dev-board/get-started/#6-run-a-model-using-the-tensorflow-lite-api)), however inference is exactly the same speed as when I don't specify the TPU experimental delegate, so I'm assuming that inference is still running on the Dev Board's CPU. Inference time on the Dev Board (with and without the experimental delegate) is 32s; on my desktop PC, inference time for the same test-set is 10s if I run the TFLite model on CPU, and 1.3s if I run the same model in Keras before converting to TFLite (I assume this is faster than TFLite because it utilises multiple cores).

My question: How can I make inference run on the Dev Board's TPU instead of the CPU?

I wonder if this is something I need to specify while building the Keras model on my PC before converting to TFLite format (EG using a `with tf.device` context manager or something which makes the resulting TFLite model use the TPU), but I can't see anything about this in the [TensorFlow Lite Converter Python API documentation](https://www.tensorflow.org/lite/convert/python_api).

The Dev Board is running Mendel version 2.0, Python version 3.5.3, tflite-runtime version 2.1.0.post1 (I know I should update the Mendel version, however I'm currently using a Windows PC, and it will be a pain to get access to a Linux machine, or to try and update the Dev Board from Windows using Putty, VirtualBox or WSL. If only Coral supported Windows, like Raspberry Pi does...).

Below is my inference script (I can also upload training script and model if necessary; dataset is MNIST, converted to NumPy float data as described in [this Gist](https://gist.github.com/jakelevi1996/5c532463d59016f42d2bbdcfedd3372a)):

```python
import numpy as np
from time import perf_counter
try:
    # Try importing the small tflite_runtime module (this runs on the Dev Board)
    print("Trying to import tensorflow lite runtime...")
    from tflite_runtime.interpreter import Interpreter, load_delegate
    experimental_delegates=[load_delegate('libedgetpu.so.1.0')]
except ModuleNotFoundError:
    # Try importing the full tensorflow module (this runs on PC)
    try:
        print("TFLite runtime not found; trying to import full tensorflow...")
        import tensorflow as tf
        Interpreter = tf.lite.Interpreter
        experimental_delegates = None
    except ModuleNotFoundError:
        # Couldn't import either module
        raise RuntimeError("Could not import Tensorflow or Tensorflow Lite")

# Load data
mnist_file = np.load("data/mnist.npz")
x_test = mnist_file["x_test"]
y_test = mnist_file["y_test"]
x_test = x_test.astype(np.float32)

# Initialise the interpreter
tfl_filename = "lstm_mnist_model_b10000.tflite"
interpreter = Interpreter(model_path=tfl_filename,
    experimental_delegates=experimental_delegates)
interpreter.allocate_tensors()

print("Starting evaluation...")
for _ in range(3):
    input_index = (interpreter.get_input_details()[0]['index'])
    output_index = (interpreter.get_output_details()[0]['index'])
    # Perform inference
    t0 = perf_counter()
    interpreter.set_tensor(input_index, x_test)
    interpreter.invoke()
    result = interpreter.get_tensor(output_index)
    t1 = perf_counter()
    # Print accuracy and speed
    num_correct = (result.argmax(axis=1) == y_test).sum()
    print("Time taken (TFLite) = {:.4f} s".format(t1 - t0))
    print('TensorFlow Lite Evaluation accuracy = {} %'.format(
        100 * num_correct / len(x_test)))
    # Reset interpreter state (I don't know why this should be necessary, but
    # accuracy suffers without it)
    interpreter.reset_all_variables()
```

**Comment by Namburger** [comment]
@jakelevi1996 HAve you compiled the model with the [edgetpu_compiler](https://www.medcram.com/) yet?
with out that, the interpreter won't know which ops to map to the CPU and which to map to TPU

**Comment by Namburger** [comment]
On another note, `tflite_runtime` is the only supported package now, if you want to use `tf.lite.Intepreter` you'll have to make sure that you've used a tensorflow version that was compiled from [this commit](https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5). This is the commit that `libedgetpu.so` was built with, so newer version of tensorflow won't be compatible, unfortunately

**Comment by jakelevi1996** [comment]
Hi Namburger, thank you for your speedy response. I hadn't compiled the model using edgetpu_compiler, I will look into doing that now.

For other people experiencing this problem, it might be beneficial if it stated explicitly in the [getting started guide for the Coral Dev Board](https://coral.ai/docs/dev-board/get-started/#next-steps) after step 6 that TensorFlow Lite models don't run on the TPU by default; to me at least, this wasn't obvious

**Comment by jakelevi1996** [comment]
In answer to your second comment, in my code I try to import `tflite_runtime` first (which succeeds on my Dev Board), and only try to import `tf.lite.Intepreter` if the `tflite_runtime` is not found (just to make it easier to test inference scripts on my PC before running on-platform). So `libedgetpu` should still be supported on the Dev Board, right? (assuming `tflite_runtime` is available, which in my case it is)

**Comment by Namburger** [comment]
Sorry for the confusion, it's actually documented [here](https://coral.ai/docs/edgetpu/models-intro/) where we give the workflow of creating the model. 
As for libedgetpu, yes that is supported in the devboard:
```
dpkg -l | grep edgetpu
```
Cheers

**Comment by jakelevi1996** [comment]
Hi @Namburger , I'm having an issue quantising my Keras LSTM model using `tf.lite.TFLiteConverter`. My model is using `tf.lite.experimental.nn.TFLiteLSTMCell` and `tf.lite.experimental.nn.dynamic_rnn` as shown in [this tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/examples/lstm/TensorFlowLite_LSTM_Keras_Tutorial.ipynb), because I thought that this combination would allow me to use LSTMs in TensorFlow Lite on the TPU, however when I set the converter attributes as shown below I get the error message `Quantization not yet supported for op: UNIDIRECTIONAL_SEQUENCE_LSTM`.

Do you know of any method which could allow `tf.lite.experimental.nn.TFLiteLSTMCell` and `tf.lite.experimental.nn.dynamic_rnn` to work on the TPU, and if not, then do you know if there are any other LSTM/other sequence models which are known to work on the TPU? (If you can link to a Colab or iPython notebook or similar that would be great)

My code for quantising the model (adapted from [this notebook on post-training quantisation, conversion and TPU compilation of a MobileNet-based model](https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf1.ipynb#scrollTo=license):

```python
n_samples=100
def representative_data_gen():
    for i in range(n_samples):
        yield [x_train[i:i+batch_size]]

sess = tf.keras.backend.get_session()
input_tensor = sess.graph.get_tensor_by_name('input:0')
output_tensor = sess.graph.get_tensor_by_name('output/Softmax:0')
input_tensor.set_shape([batch_size, 28, 28])
output_tensor.set_shape([batch_size, 10])
converter = tf.lite.TFLiteConverter.from_session(
    sess, [input_tensor], [output_tensor])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_data_gen
tflite_model = converter.convert()
```

PS sorry this is not really on topic for the original issue

**Comment by Namburger** [comment]
Hi @jakelevi1996 
For this last question, I think opening one with the tensorflow team [here](https://github.com/tensorflow/tensorflow/issues) would give you better answer. The "error" that you're getting right now just means that it's not yet supported so maybe it'd be a good feature request?
On another note, it is advised that you stay within tf1.15 as our current release of the compiler isn't fully compatible with tensorflow2.0 yet. We are expecting full compatibility in future release but can't commit a time frame at the momment.
