### ISSUE TITLE
Google Coral EdgeTPU and full integer quantization of weights and activations as uint8 on time series

### ISSUE THREAD

**Issue by dmfolgado** [google-coral/edgetpu#84]
Hello,

Even after reading the [https://www.tensorflow.org/lite/performance/post_training_quantization](documentation) I am still struggling about the possibilities to get Google Coral work with time series (float) data. I'm trying to implement a 1D-CNN that receives a unidimensional time series (let's assume for the sake of simplicity) and forecasts the next value. During training I normalise the float time series between 0 and 1.

As far my understanding after learning the model (using tf 2.0) I used tf 1.15 to convert the model to TFLite.

```
converter = tf.lite.TFLiteConverter.from_keras_model_file(model_path)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = tf.lite.RepresentativeDataset(representative_dataset_gen)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
```

However, my input (and output) time series data are not uint8 but rather float32. And I do not think it would be reasonable to represent a float32 time series as uint8. Am I missing something here? Can I still take advantage of the inference on Coral?

**Comment by Namburger** [comment]
Humn, with the current version of edgetpu_compiler, you should be able to compile models with float inputs. We haven't extended our api to accommodate these changes yet, so you'll have to write your own code for running inference using the tflite api with `load_delegate`. Are you running into any specific issue?

**Comment by dmfolgado** [comment]
Thanks @Namburger! I was in fact running into a particular issue that was solved after using `tflite_runtime.interpreter` with `load_delefate` as you suggested. For my use case, which is related to a time series regression problem, I changed strategy and I am using a "classification" strategy where the labels are binnarized between 0 to 255, as well converting the time series floats to uint8 in post-quantization.

**Comment by marbortoli** [comment]
@dmfolgado I am testing coral ai usage on a time series data set, but I ran in the same problem, I guess.. would you mind explaining a bit more in details how you could solve it?

**Comment by dmfolgado** [comment]
Hi @marbortoli! Yes, sure. We actually published a paper on that topic. It's available here - [TIP4.0: Industrial Internet of Things Platform for Predictive Maintenance](https://www.mdpi.com/1424-8220/21/14/4676). Check Section 4. I hope that helps!
