### ISSUE TITLE
Co-compiling models gives wrong output

### ISSUE THREAD

**Issue by ShreyasBhanderi** [google-coral/edgetpu#85]
Hi,

I am trying to co-compile two models, one of them is object detection model and one is simple embedding model. when I compile both models individually it works fine but as explained in docs it doesn't cache model parameters together so when I switch my interpreter it takes longer time to predict on first instance. To deal with this problem I tried to co-compile model. after that inference time reduced after switching as explained in docs, but model prediction is all wrong. I also tried switching order while compiling but prediction is still wrong.
I am uploading tflite models, individually compiled and co-compiled model(with their logs) on following link: https://drive.google.com/open?id=1IztRKeIU2TM5RydYG8yQ5hREtTaTxMB0

I am using tflite_runtime-2.1.0 on usb accelerator and edgetpu_compiler 2.0.267685300.

**Comment by Namburger** [comment]
@ShreyasBhanderi Hi,
We do have a known bug with cocompiling models and recently added some unit tests for model validation after cocompiling. 
My suggestion:
* Could you try upgrading to the newer compiler to see if this is fixed?
* If this doesn't do the trick, could you share both of your models with us so we can debug (FYI the gdrive link did not work)?

**Comment by ShreyasBhanderi** [comment]
also tried version 2.0.291256449(latest). doesn't work.

**Comment by Namburger** [comment]
Can you share your models?

**Comment by ShreyasBhanderi** [comment]
model link : https://drive.google.com/open?id=1IztRKeIU2TM5RydYG8yQ5hREtTaTxMB0

**Comment by Namburger** [comment]
Thanks, will take a look now!

**Comment by Namburger** [comment]
@ShreyasBhanderi you are correct, looks like one of your model (`modelsi_480_edgetpu.tflite`) will give different results for the same input tensors. Test script:
```
import numpy as np 
import sys
from tflite_runtime.interpreter import Interpreter
from tflite_runtime.interpreter import load_delegate

if len(sys.argv) != 3:
    print('Usage:', sys.argv[0], 'model1_path model2_path')
    exit()

def main():
    model_path = str(sys.argv[1])
    print('Trying: ', model_path)
    delegates = [load_delegate('libedgetpu.so.1.0')]
    interpreter = Interpreter(model_path)
    interpreter = Interpreter(model_path, experimental_delegates=delegates)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    image = np.zeros(input_details[0]['shape'], input_details[0]['dtype'])
    interpreter.set_tensor(input_details[0]['index'], image)
    interpreter.invoke()
    output_details = interpreter.get_output_details()
    outputs1 = interpreter.get_tensor(output_details[0]['index'])
    print(outputs1)

    model_path = str(sys.argv[2])
    print('Trying: ', model_path)
    delegates = [load_delegate('libedgetpu.so.1.0')]
    interpreter2 = Interpreter(model_path, experimental_delegates=delegates)
    interpreter2.allocate_tensors()
    input_details2 = interpreter2.get_input_details()
    interpreter2.set_tensor(input_details2[0]['index'], image) # using same inputs
    interpreter2.invoke()
    output_details = interpreter2.get_output_details()
    outputs2 = interpreter2.get_tensor(output_details[0]['index'])
    print(outputs2)

    assert outputs1.all() == outputs2.all()

    print('Success.')

if __name__== '__main__':
    main()
```

Fortunately, this is only an issue with the current released of the compiler, we've since fixed this. Expect a new compiler version soon with this fix!

**Comment by ShreyasBhanderi** [comment]
Hey @Namburger, any update on it?

**Comment by Namburger** [comment]
@ShreyasBhanderi 
Sorry I didn't follow up. I reproduced your issue and it looks like you are hitting the same bug as I previously stated. I submitted your model to the eng working on this case for evaluation. Currently we still haven't caught what causing this issue, but there are now 2 of such models failing in our test. Apologies, we'll get this sorted out and give you an update as soon as we have a fix.

**Comment by ShreyasBhanderi** [comment]
One more thing, I also tried Co-compiling model1, model1_clone and model2, model2_clone instead of model1, model2. But Co-compiling same models also gives the same problem and models starts giving wrong output but this wrong output remains the same as before. (output of model1 from Co-compiled model1,model2 = output of model1 from Co-compiled model1, model1_clone = output of model1_clone from Co-compiled model1, model1_clone. same with model2)

**Comment by Namburger** [comment]
Yes, this is issue is model specific, but only happens during co compilation

**Comment by hjonnala** [comment]
Closing the issue due to inactivity. Feel free to reopen if this issue still persists.
