### ISSUE TITLE
Got 'Internal compiler error. Aborting!'.

### ISSUE THREAD

**Issue by ReinForce-II** [google-coral/edgetpu#92]
Hi,

I got 'Internal compiler error. Aborting!' on a 8bit post-quantized model.
Compiler version is 2.1.302470888.

Here is the model.

[pose_mobilenet.zip](https://github.com/google-coral/edgetpu/files/4461981/pose_mobilenet.zip)

**Comment by Namburger** [comment]
@ReinForce-II 
This looks like a bug, thanks for reporting, I'll update you on this within this week.

**Comment by Namburger** [comment]
@ReinForce-II Sorry for the late response, we've fixed this issue, your model will pass on the next release of the compiler! Apologies
