### ISSUE TITLE
Interpreter.invoke() halts after n-th execution

### ISSUE THREAD

**Issue by podestplatz** [google-coral/edgetpu#94]
Hi Team, 

I recently got the EdgeTPU USB accelerator to work with and I am impressed so far. But during experimentation I ran across an issue where I can run inferences just a few times (n<=10) on the same `Interpreter` python object. After that, execution just blocks in `interpreter.invoke()` (given that `interpreter` is the object of the `Interpreter` class).

I am using the python version of the classification example of [https://github.com/google-coral/tflite.git](https://github.com/google-coral/tflite.git) with an inference count of 20, passed as argument to the `-c` option and I wait for 1s between two inferences. 

As to my setup:
The output of `dpkg -l | grep edgetpu` is: 

```
ii  libedgetpu1-std:amd64       14.0                                amd64        Support library for Edge TPU
ii  python3-edgetpu             14.0                                amd64        Edge TPU Python API
```

Furthermore, I am operating the EdgeTPU USB accelerator through an externally powered USB 3 hub, thus power should not be an issue here, and the OS is Ubuntu 18.04 with kernel version 5.3.0-46. 

The output I get running `classify_image.py` is: 
```
$> python3 classify_image.py -m models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite -i images/parrot.jpg -c 20
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
14.5ms
6.0ms
5.6ms
5.9ms
8.9ms
5.4ms
```
In the above example, the 7th call to `interpreter.invoke()` never returns, forcing me to kill the python process. However, starting the program again without reconnecting the accelerator device works, till the 7th execution that is. 

For easier reproducibility I created a [Dockerfile](https://github.com/google-coral/edgetpu/files/4479679/Dockerfile.txt) that can be dropped right into `./tflite/python/examples/classification/`, building and running the image and container can be achieved by the following commands: 

```
# The current workdir is assumed to be `./tflite/python/examples/classification/`
$> docker build --tag <image-tag> .
# `--privileged` is needed to give the container access to the USB devices
$> docker run --privileged <image-tag>
```

I modified the `classify_image.py` script in two small ways: the first one is waiting for 1s after each inference before starting the next one, and the second one is flushing stdout right before sleeping for one second. The second modification was necessary to see the output of the script executed in the container. Following is the output of `git diff`
```
--- a/python/examples/classification/classify_image.py
+++ b/python/examples/classification/classify_image.py
@@ -29,6 +29,7 @@ r"""Example using TF Lite to classify a given image using an Edge TPU.

 import argparse
 import time
+import sys

 from PIL import Image

@@ -112,6 +113,8 @@ def main():
     inference_time = time.perf_counter() - start
     classes = classify.get_output(interpreter, args.top_k, args.threshold)
     print('%.1fms' % (inference_time * 1000))
+    sys.stdout.flush()
+    time.sleep(1)

   print('-------RESULTS--------')
   for klass in classes:
```

Am I doing something wrong in waiting between two inferences? Or is it intended to create a new interpreter object now and then? 

EDIT: Formatted the URL to the tflite github repo as hyperlink

**Comment by podestplatz** [comment]
I forgot to mention that I am using the accelerator inside a VMWare VM. On a native linux system I do not have any problems with the example above.

**Comment by Namburger** [comment]
Hi @podestplatz 
thanks for the detailed description! Unfortunately, vm is not a supported platform for any of our products at this time. Secondly, we recently discovered that usb3.0 is a little unreliable, could you try to see if you can reproduce this in your VM with usb2.0?

**Comment by podestplatz** [comment]
Hey @Namburger 
thanks for the quick reply! I already thought so, the VM setup is probably very hard to support and not used by many developers. Regarding the usb2.0 check: I don't think that I can, because the laptop on which I work only has usb3.0 ports, and the only usb hub I have is also purely 3.0. [This VMWare article](https://kb.vmware.com/s/article/2147568) further suggests that the easy solution, to just use the 2.0 controller for the VM, does not work with a 3.0 device and port. 
Do you have an idea how I could test it?

**Comment by Namburger** [comment]
@podestplatz The only way that I can think of is to try a usb-c 2.0 cable :)
Anyways, I suggest moving away from VM since it won't be as reliable.

**Comment by podestplatz** [comment]
yes that is a good idea ^^ I will setup a test system and close this issue. I will post any updates if I find out something using a usb-c 2.0 cable ;)
