### ISSUE TITLE
Jetson Nano M.2 - Failed to load delegate from libedgetpu.so.1

### ISSUE THREAD

**Issue by rdejana** [google-coral/edgetpu#96]
Close to having this working, but the unable to load the library.

python3 classify_image.py \
> --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
> --labels models/inat_bird_labels.txt \
> --input images/parrot.jpg
Traceback (most recent call last):
  File "/home/rdejana/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 161, in load_delegate
    delegate = Delegate(library, options)
  File "/home/rdejana/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 120, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 99, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 73, in make_interpreter
    {'device': device[0]} if device else {})
  File "/home/rdejana/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 164, in load_delegate
    library, str(e)))
ValueError: Failed to load delegate from libedgetpu.so.1

lsmod:
lsmod
Module                  Size  Used by
zram                   26166  4
overlay                48691  0
spidev                 13282  0
apex                   17970  0
gasket                118068  1 apex
nvgpu                1575721  20
bluedroid_pm           13912  0
ip_tables              19441  0
x_tables               28951  1 ip_tables

ls /dev/apex_0
/dev/apex_0

odinfo gasket
filename:       /lib/modules/4.9.140-tegra/updates/dkms/gasket.ko
author:         Rob Springer <rspringer@google.com>
license:        GPL v2
version:        1.1.3
description:    Google Gasket driver framework
srcversion:     069B6D0F6AE12073F4EAF5D
depends:        
vermagic:       4.9.140-tegra SMP preempt mod_unload modversions aarch64
parm:           dma_bit_mask:int

modinfo apex
filename:       /lib/modules/4.9.140-tegra/updates/dkms/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.1
description:    Google Apex driver
srcversion:     508A8A34D57322CEA287D17
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
vermagic:       4.9.140-tegra SMP preempt mod_unload modversions aarch64
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
parm:           trip_point0_temp:int
parm:           trip_point1_temp:int
parm:           trip_point2_temp:int
parm:           hw_temp_warn1:int
parm:           hw_temp_warn2:int
parm:           hw_temp_warn1_en:bool
parm:           hw_temp_warn2_en:bool
parm:           temp_poll_interval:int

dmesg | grep apex
[    5.354227] apex 0000:01:00.0: can't enable device: BAR 0 [mem 0x00000000-0x00003fff 64bit pref] not claimed
[    5.365610] apex 0000:01:00.0: BAR 2: assigned [mem 0x20000000-0x200fffff 64bit pref]
[    5.365748] apex 0000:01:00.0: BAR 0: assigned [mem 0x20100000-0x20103fff 64bit pref]
[    5.365936] apex 0000:01:00.0: enabling device (0000 -> 0002)
[   10.614865] apex 0000:01:00.0: Apex performance not throttled due to temperature
[  128.375802] apex 0000:01:00.0: Apex performance not throttled due to temperature
[  235.893286] apex 0000:01:00.0: Apex performance not throttled due to temperature

lspci | grep 089a
01:00.0 System peripheral: Device 1ac1:089a

dmesg | grep gasket
[    5.332185] gasket: loading out-of-tree module taints kernel.

thanks

**Comment by Namburger** [comment]
@rdejana Could you share the output of uname -a? If the kernel is newer than 4.15, it's possible that the default apex/gasket driver is still being loaded after installing our drivers.
Please also share `dmesg | grep pcie`

**Comment by rdejana** [comment]
Hi @Namburger, here you go

Linux nano 4.9.140-tegra #1 SMP PREEMPT Mon Dec 9 22:47:42 PST 2019 aarch64 aarch64 aarch64 GNU/Linux


[    0.984258] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.3, lane = pcie-0, function = pcie-x1
[    0.984348] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.4, lane = pcie-1, function = pcie-x4
[    0.984439] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.5, lane = pcie-2, function = pcie-x4
[    0.984524] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.6, lane = pcie-3, function = pcie-x4
[    0.984611] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.7, lane = pcie-4, function = pcie-x4
[    0.984696] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.8, lane = pcie-5, function = xusb
[    0.984781] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.9, lane = pcie-6, function = xusb
[    0.994476] tegra-pcie 1003000.pcie: 4x1, 1x1 configuration
[    0.995788] tegra-pcie 1003000.pcie: PCIE: Enable power rails
[    0.996158] tegra-pcie 1003000.pcie: probing port 0, using 4 lanes
[    1.000171] tegra-pcie 1003000.pcie: probing port 1, using 1 lanes
[    1.044967] tegra-pcie 1003000.pcie: PCI host bridge to bus 0000:00
[    1.067712] pcieport 0000:00:01.0: Signaling PME through PCIe PME interrupt
[    1.067724] pcie_pme 0000:00:01.0:pcie001: service driver pcie_pme loaded
[    1.067933] pcieport 0000:00:02.0: Signaling PME through PCIe PME interrupt
[    1.067943] pcie_pme 0000:00:02.0:pcie001: service driver pcie_pme loaded

**Comment by rdejana** [comment]
And this might be interesting (first time I've seen in logs)

dmesg | grep apex
   4.528225] apex 0000:01:00.0: can't enable device: BAR 0 [mem 0x00000000-0x00003fff 64bit pref] not claimed
[    4.540316] apex 0000:01:00.0: BAR 2: assigned [mem 0x20000000-0x200fffff 64bit pref]
[    4.540444] apex 0000:01:00.0: BAR 0: assigned [mem 0x20100000-0x20103fff 64bit pref]
[    4.564046] apex 0000:01:00.0: BAR 0: error updating (0x2010000c != 0xffffffff)
[    4.593525] apex 0000:01:00.0: BAR 0: error updating (high 0x000000 != 0xffffffff)
[    4.675875] apex 0000:01:00.0: Refused to change power state, currently in D3
[    4.818330] apex 0000:01:00.0: enabling device (0000 -> 0002)
[    4.820543] apex 0000:01:00.0: Couldn't initialize interrupts: -22
[    9.847318] apex 0000:01:00.0: Apex performance not throttled due to temperature

**Comment by rdejana** [comment]
Think I have another issue.  Noticed that once I added the PCIe driver, my wired network connection has become very unstable

**Comment by Namburger** [comment]
@rdejana Hi, although I haven't seen these issue before, we have had success stories fro jetson nano users. There is one thing taht you may need to do:
Could you add `pcie_aspm=off` to your kernel command arguments?
You can do with by  opening this file:
```
$ cat /boot/extlinux/extlinux.conf
TIMEOUT 30
DEFAULT primary

MENU TITLE L4T boot options

LABEL primary
      MENU LABEL primary kernel
      LINUX /boot/Image
      INITRD /boot/initrd
      APPEND ${cbootargs} quiet
```
Change "APPEND ${cbootargs} quiet" to "APPEND ${cbootargs} quiet pcie_aspm=off"
Then reboot your board, let me know if this fixes your issue!

**Comment by rdejana** [comment]
So far so good!
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
14.0ms
2.7ms
2.5ms
2.6ms
2.6ms

Going to keep an eye on things and close this one out!
Thanks @Namburger !

**Comment by joeycasabar** [comment]
@rdejana any further development on wired connection instability? I was able to use `pcie_aspm=off` to get inferencing working but I am also having issues with ethernet no longer working

**Comment by Kuan-ChiehHsu** [comment]
I tried the ```pcie_aspm=off``` method but still get the ```ValueError: Failed to load delegate from libedgetpu.so.1``` error.
My single core M.2 edgetpu is attached on jetson nano.

uname -a
```
Linux nano-2 4.9.201-tegra #1 SMP PREEMPT Fri Feb 19 08:40:32 PST 2021 aarch64 aarch64 aarch64 GNU/Linux
```
lsmod
```
apex                   19188  0
gasket                122109  1 apex
```

lspci
```
01:00.0 System peripheral: Device 1ac1:089a
```
dmesg | grep apex
```
[    4.751575] apex 0000:01:00.0: can't enable device: BAR 0 [mem 0x00000000-0x00003fff 64bit pref] not claimed
[    4.761725] apex 0000:01:00.0: BAR 2: assigned [mem 0x20000000-0x200fffff 64bit pref]
[    4.761742] apex 0000:01:00.0: BAR 0: assigned [mem 0x20100000-0x20103fff 64bit pref]
[    4.761761] apex 0000:01:00.0: enabling device (0000 -> 0002)
[    9.841826] apex 0000:01:00.0: Apex performance not throttled due to temperature
[   11.832996] Modules linked in: xt_conntrack ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink nfnetlink xt_addrtype iptable_filter iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack br_netfilter zram rtl8821au cfg80211 overlay apex(O) gasket(O) spidev userspace_alert nvgpu bluedroid_pm ip_tables x_tables
```
dmesg | grep pcie
```
[    0.000000] Kernel command line: tegraid=21.1.2.0.0 ddr_die=4096M@2048M section=512M memtype=0 vpr_resize usb_port_owner_info=0 lane_owner_info=0 emc_max_dvfs=0 touch_id=0@63 video=tegrafb no_console_suspend=1 console=ttyS0,115200n8 debug_uartport=lsport,4 earlyprintk=uart8250-32bit,0x70006000 maxcpus=4 usbcore.old_scheme_first=1 lp0_vec=0x1000@0xff780000 core_edp_mv=1075 core_edp_ma=4000 gpt  earlycon=uart8250,mmio32,0x70006000  root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyS0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 quiet root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyS0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 pcie_aspm=off
[    1.055963] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.3, lane = pcie-0, function = pcie-x1
[    1.056053] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.4, lane = pcie-1, function = pcie-x4
[    1.056140] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.5, lane = pcie-2, function = pcie-x4
[    1.056228] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.6, lane = pcie-3, function = pcie-x4
[    1.056310] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.7, lane = pcie-4, function = pcie-x4
[    1.056414] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.8, lane = pcie-5, function = xusb
[    1.056502] tegra-xusb-padctl 7009f000.xusb_padctl: dev = phy-pcie.9, lane = pcie-6, function = xusb
[    1.066183] tegra-pcie 1003000.pcie: 4x1, 1x1 configuration
[    1.067464] tegra-pcie 1003000.pcie: PCIE: Enable power rails
[    1.067806] tegra-pcie 1003000.pcie: probing port 0, using 4 lanes
[    1.071863] tegra-pcie 1003000.pcie: probing port 1, using 1 lanes
[    1.613231] tegra-pcie 1003000.pcie: PCI host bridge to bus 0000:00
[    1.615220] pcieport 0000:00:01.0: Signaling PME through PCIe PME interrupt
[    1.615231] pcie_pme 0000:00:01.0:pcie001: service driver pcie_pme loaded
[    1.615347] aer 0000:00:01.0:pcie002: service driver aer loaded
[    1.615565] pcieport 0000:00:02.0: Signaling PME through PCIe PME interrupt
[    1.615575] pcie_pme 0000:00:02.0:pcie001: service driver pcie_pme loaded
[    1.615667] aer 0000:00:02.0:pcie002: service driver aer loaded
```

**Comment by sivom** [comment]
Hi
did anyone find the solution, I tried the solution it doesn't work for me on Jetson nano 4GB

``` 
gowri@gowri-nano:~$ cat /proc/device-tree/model
NVIDIA Jetson Nano Developer Kit
gowri@gowri-nano:~$
gowri@gowri-nano:~$ free
              total        used        free      shared  buff/cache   available
Mem:        4057792      977852     2156876       31884      923064     2894616
Swap:       2028880           0     2028880

gowri@gowri-nano:~$ head -n 1 /etc/nv_tegra_release
# R32 (release), REVISION: 7.6, GCID: 38171779, BOARD: t210ref, EABI: aarch64, DATE: Tue Nov  5 07:46:14 UTC 2024
gowri@gowri-nano:~$ dpkg-query --show nvidia-l4t-core
nvidia-l4t-core 32.7.6-20241104234540

```

```
uname -a
Linux gowri-nano 4.9.337-tegra #1 SMP PREEMPT Mon Nov 4 23:41:41 PST 2024 aarch64 aarch64 aarch64 GNU/Linux ```

Tried reinstalling apex and gasket no errors 
```
gowri@gowri-nano:~$ sudo apt-get install --reinstall gasket-dkms libedgetpu1-std
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apt-clone archdetect-deb bogl-bterm busybox-static cryptsetup-bin dpkg-repack efibootmgr gir1.2-timezonemap-1.0 gir1.2-xkl-1.0 grub-common
  kde-window-manager kinit kio kpackagetool5 kwayland-data kwin-common kwin-data kwin-x11 libdebian-installer4 libkdecorations2-5v5
  libkdecorations2private5v5 libkf5activities5 libkf5attica5 libkf5completion-data libkf5completion5 libkf5declarative-data libkf5declarative5
  libkf5doctools5 libkf5globalaccel-data libkf5globalaccel5 libkf5globalaccelprivate5 libkf5idletime5 libkf5jobwidgets-data libkf5jobwidgets5
  libkf5kcmutils-data libkf5kcmutils5 libkf5kiocore5 libkf5kiontlm5 libkf5kiowidgets5 libkf5newstuff-data libkf5newstuff5 libkf5newstuffcore5
  libkf5package-data libkf5package5 libkf5plasma5 libkf5quickaddons5 libkf5solid5 libkf5solid5-data libkf5sonnet5-data libkf5sonnetcore5 libkf5sonnetui5
  libkf5textwidgets-data libkf5textwidgets5 libkf5waylandclient5 libkf5waylandserver5 libkf5xmlgui-bin libkf5xmlgui-data libkf5xmlgui5 libkscreenlocker5
  libkwin4-effect-builtins1 libkwineffects11 libkwinglutils11 libkwinxrenderutils11 libqgsttools-p1 libqt5designer5 libqt5help5 libqt5multimedia5
  libqt5multimedia5-plugins libqt5multimediaquick-p5 libqt5multimediawidgets5 libqt5opengl5 libqt5quickwidgets5 libqt5sql5 libqt5test5 libxcb-composite0
  libxcb-cursor0 libxcb-damage0 os-prober python3-dbus.mainloop.pyqt5 python3-icu python3-pam python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtwebkit
  qml-module-org-kde-kquickcontrolsaddons qml-module-qtmultimedia qml-module-qtquick2 rdate tasksel tasksel-data
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/389 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 208626 files and directories currently installed.)
Preparing to unpack .../gasket-dkms_1.0-18_all.deb ...

-------- Uninstall Beginning --------
Module:  gasket
Version: 1.0
Kernel:  4.15.0-213-generic (aarch64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

gasket.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.15.0-213-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


apex.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.15.0-213-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

Warning: Unable to find an initial ram disk that I know how to handle.
Will not try to make an initrd.

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  gasket
Version: 1.0
Kernel:  4.9.337-tegra (aarch64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

gasket.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.337-tegra/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


apex.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.9.337-tegra/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

Warning: Unable to find an initial ram disk that I know how to handle.
Will not try to make an initrd.

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0
completely from the DKMS tree.
------------------------------
Done.
Unpacking gasket-dkms (1.0-18) over (1.0-18) ...
Preparing to unpack .../libedgetpu1-std_16.0_arm64.deb ...
Unpacking libedgetpu1-std:arm64 (16.0) over (16.0) ...
Setting up libedgetpu1-std:arm64 (16.0) ...
Setting up gasket-dkms (1.0-18) ...
Loading new gasket-1.0 DKMS files...
It is likely that 4.9.337-tegra belongs to a chroot's host
Building for 4.15.0-213-generic and 4.9.337-tegra
Building initial module for 4.15.0-213-generic
Done.

gasket:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.15.0-213-generic/updates/dkms/

apex.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.15.0-213-generic/updates/dkms/

depmod...

Warning: Unable to find an initial ram disk that I know how to handle.
Will not try to make an initrd.

DKMS: install completed.
Building initial module for 4.9.337-tegra
Done.

gasket:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.337-tegra/updates/dkms/

apex.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.337-tegra/updates/dkms/

depmod...

Warning: Unable to find an initial ram disk that I know how to handle.
Will not try to make an initrd.

DKMS: install completed.
Processing triggers for libc-bin (2.27-3ubuntu1.6) ...
gowri@gowri-nano:~$
```
modinfo output for gasket and apex
```
gowri@gowri-nano:~$ modinfo apex
filename:       /lib/modules/4.9.337-tegra/updates/dkms/apex.ko
author:         John Joseph <jnjoseph@google.com>
license:        GPL v2
version:        1.2
description:    Google Apex driver
srcversion:     BCFB09A9C4DC598D3A05A9C
alias:          pci:v00001AC1d0000089Asv*sd*bc*sc*i*
depends:        gasket
vermagic:       4.9.337-tegra SMP preempt mod_unload modversions aarch64
parm:           allow_power_save:int
parm:           allow_sw_clock_gating:int
parm:           allow_hw_clock_gating:int
parm:           bypass_top_level:int
parm:           trip_point0_temp:int
parm:           trip_point1_temp:int
parm:           trip_point2_temp:int
parm:           hw_temp_warn1:int
parm:           hw_temp_warn2:int
parm:           hw_temp_warn1_en:bool
parm:           hw_temp_warn2_en:bool
parm:           temp_poll_interval:int
gowri@gowri-nano:~$ modinfo gasket
filename:       /lib/modules/4.9.337-tegra/updates/dkms/gasket.ko
author:         Rob Springer <rspringer@google.com>
license:        GPL v2
version:        1.1.4
description:    Google Gasket driver framework
srcversion:     FDB547C246143FA0880920C
depends:
vermagic:       4.9.337-tegra SMP preempt mod_unload modversions aarch64
parm:           dma_bit_mask:int
gowri@gowri-nano:~$
```
lsmod output
```
gowri@gowri-nano:~$ lsmod
Module                  Size  Used by
bnep                   16562  2
fuse                  105514  3
xt_conntrack            3609  1
ipt_MASQUERADE          2346  1
nf_nat_masquerade_ipv4     3111  1 ipt_MASQUERADE
nf_conntrack_netlink    29413  0
nfnetlink               7959  2 nf_conntrack_netlink
xt_addrtype             3734  2
iptable_filter          2481  1
iptable_nat             2882  1
nf_conntrack_ipv4      11992  2
nf_defrag_ipv4          1836  1 nf_conntrack_ipv4
nf_nat_ipv4             6712  1 iptable_nat
nf_nat                 20172  2 nf_nat_masquerade_ipv4,nf_nat_ipv4
nf_conntrack           99637  6 nf_conntrack_ipv4,nf_conntrack_netlink,nf_nat_masquerade_ipv4,xt_conntrack,nf_nat_ipv4,nf_nat
br_netfilter           16216  0
zram                   25920  4
rt2800usb              22944  0
rt2x00usb              12492  1 rt2800usb
rt2800lib              80870  1 rt2800usb
rt2x00lib              61822  3 rt2800lib,rt2800usb,rt2x00usb
mac80211              721898  3 rt2800lib,rt2x00lib,rt2x00usb
cfg80211              589358  2 rt2x00lib,mac80211
overlay                49625  0
userspace_alert         5828  0
binfmt_misc            13103  1
nvgpu                1597641  18
ip_tables              19313  2 iptable_filter,iptable_nat
x_tables               30560  5 ip_tables,iptable_filter,ipt_MASQUERADE,xt_addrtype,xt_conntrack
gowri@gowri-nano:~$ lsmod|grep apex
gowri@gowri-nano:~$
```
tried loading apex and gasket. it loaded once but never created /dev/apex0 device
````
gowri@gowri-nano:~$ sudo insmod apex
insmod: ERROR: could not load module apex: No such file or directory
gowri@gowri-nano:~$ sudo insmod gasket
insmod: ERROR: could not load module gasket: No such file or directory
gowri@gowri-nano:~$
```
extlinux.conf settings
```
gowri@gowri-nano:~$ sudo cat /boot/extlinux/extlinux.conf
TIMEOUT 30
DEFAULT primary

MENU TITLE L4T boot options

LABEL primary
      MENU LABEL primary kernel
      LINUX /boot/Image
      INITRD /boot/initrd
      APPEND ${cbootargs} quiet root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyS0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 pcie_aspm=off gasket.dma_bit_mask=32

```
